import { TAG_SLUGS } from '../../tags/seed-tags'
import { ANUA_PRODUCT_SLUGS } from './anua'

export const ANUA_PRODUCT_TAGS: { productSlug: string; tagSlug: string }[] = [
  // Heartleaf 77% Soothing Toner
  { productSlug: ANUA_PRODUCT_SLUGS.ANUA_HEARTLEAF_77_SOOTHING, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },
  { productSlug: ANUA_PRODUCT_SLUGS.ANUA_HEARTLEAF_77_SOOTHING, tagSlug: TAG_SLUGS.PEAU_REACTIVE },
  { productSlug: ANUA_PRODUCT_SLUGS.ANUA_HEARTLEAF_77_SOOTHING, tagSlug: TAG_SLUGS.ANTI_ROUGEURS },
  {
    productSlug: ANUA_PRODUCT_SLUGS.ANUA_HEARTLEAF_77_SOOTHING,
    tagSlug: TAG_SLUGS.BARRIERE_CUTANEE,
  },
  { productSlug: ANUA_PRODUCT_SLUGS.ANUA_HEARTLEAF_77_SOOTHING, tagSlug: TAG_SLUGS.TONIQUE },
  { productSlug: ANUA_PRODUCT_SLUGS.ANUA_HEARTLEAF_77_SOOTHING, tagSlug: TAG_SLUGS.SANS_PARFUM },
  { productSlug: ANUA_PRODUCT_SLUGS.ANUA_HEARTLEAF_77_SOOTHING, tagSlug: TAG_SLUGS.PEAU_ATOPIQUE },

  // Rice 70 Glow Milky Toner
  { productSlug: ANUA_PRODUCT_SLUGS.ANUA_RICE_70_GLOW_MILKY, tagSlug: TAG_SLUGS.ECLAT },
  { productSlug: ANUA_PRODUCT_SLUGS.ANUA_RICE_70_GLOW_MILKY, tagSlug: TAG_SLUGS.ANTI_TACHES },
  { productSlug: ANUA_PRODUCT_SLUGS.ANUA_RICE_70_GLOW_MILKY, tagSlug: TAG_SLUGS.BRILLANCE },
  { productSlug: ANUA_PRODUCT_SLUGS.ANUA_RICE_70_GLOW_MILKY, tagSlug: TAG_SLUGS.DESHYDRATATION },
  { productSlug: ANUA_PRODUCT_SLUGS.ANUA_RICE_70_GLOW_MILKY, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },
  { productSlug: ANUA_PRODUCT_SLUGS.ANUA_RICE_70_GLOW_MILKY, tagSlug: TAG_SLUGS.CREME_HYDRATANTE }, // Tonique lacté hydratant
  { productSlug: ANUA_PRODUCT_SLUGS.ANUA_RICE_70_GLOW_MILKY, tagSlug: TAG_SLUGS.TONIQUE },
  { productSlug: ANUA_PRODUCT_SLUGS.ANUA_RICE_70_GLOW_MILKY, tagSlug: TAG_SLUGS.SANS_PARFUM },
  { productSlug: ANUA_PRODUCT_SLUGS.ANUA_RICE_70_GLOW_MILKY, tagSlug: TAG_SLUGS.PEAU_MIXTE },
  { productSlug: ANUA_PRODUCT_SLUGS.ANUA_RICE_70_GLOW_MILKY, tagSlug: TAG_SLUGS.PEAU_GRASSE },

  // Azelaic Acid 10% Hyaluron Redness Soothing Serum
  {
    productSlug: ANUA_PRODUCT_SLUGS.ANUA_AZELAIC_10_HYDRATING_REDNESS,
    tagSlug: TAG_SLUGS.ANTI_ROUGEURS,
  },
  { productSlug: ANUA_PRODUCT_SLUGS.ANUA_AZELAIC_10_HYDRATING_REDNESS, tagSlug: TAG_SLUGS.ROSACEE },
  {
    productSlug: ANUA_PRODUCT_SLUGS.ANUA_AZELAIC_10_HYDRATING_REDNESS,
    tagSlug: TAG_SLUGS.ANTI_ACNE,
  },
  {
    productSlug: ANUA_PRODUCT_SLUGS.ANUA_AZELAIC_10_HYDRATING_REDNESS,
    tagSlug: TAG_SLUGS.ANTI_TACHES,
  },
  {
    productSlug: ANUA_PRODUCT_SLUGS.ANUA_AZELAIC_10_HYDRATING_REDNESS,
    tagSlug: TAG_SLUGS.HYPERPIGMENTATION,
  },
  {
    productSlug: ANUA_PRODUCT_SLUGS.ANUA_AZELAIC_10_HYDRATING_REDNESS,
    tagSlug: TAG_SLUGS.POST_ACNE,
  },
  {
    productSlug: ANUA_PRODUCT_SLUGS.ANUA_AZELAIC_10_HYDRATING_REDNESS,
    tagSlug: TAG_SLUGS.BARRIERE_CUTANEE,
  },
  {
    productSlug: ANUA_PRODUCT_SLUGS.ANUA_AZELAIC_10_HYDRATING_REDNESS,
    tagSlug: TAG_SLUGS.PEAU_SENSIBLE,
  },
  { productSlug: ANUA_PRODUCT_SLUGS.ANUA_AZELAIC_10_HYDRATING_REDNESS, tagSlug: TAG_SLUGS.SERUM },
  {
    productSlug: ANUA_PRODUCT_SLUGS.ANUA_AZELAIC_10_HYDRATING_REDNESS,
    tagSlug: TAG_SLUGS.SANS_PARFUM,
  },
  {
    productSlug: ANUA_PRODUCT_SLUGS.ANUA_AZELAIC_10_HYDRATING_REDNESS,
    tagSlug: TAG_SLUGS.HYPOALLERGENIQUE,
  },
  {
    productSlug: ANUA_PRODUCT_SLUGS.ANUA_AZELAIC_10_HYDRATING_REDNESS,
    tagSlug: TAG_SLUGS.NON_COMEDOGENE,
  },

  // Azelaic Acid 3% Cica Skin Clarifying Toner
  { productSlug: ANUA_PRODUCT_SLUGS.ANUA_AZELAIC_3_CICA_TONER, tagSlug: TAG_SLUGS.ANTI_ROUGEURS },
  { productSlug: ANUA_PRODUCT_SLUGS.ANUA_AZELAIC_3_CICA_TONER, tagSlug: TAG_SLUGS.ANTI_ACNE },
  { productSlug: ANUA_PRODUCT_SLUGS.ANUA_AZELAIC_3_CICA_TONER, tagSlug: TAG_SLUGS.BRILLANCE },
  { productSlug: ANUA_PRODUCT_SLUGS.ANUA_AZELAIC_3_CICA_TONER, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },
  { productSlug: ANUA_PRODUCT_SLUGS.ANUA_AZELAIC_3_CICA_TONER, tagSlug: TAG_SLUGS.PEAU_GRASSE },
  { productSlug: ANUA_PRODUCT_SLUGS.ANUA_AZELAIC_3_CICA_TONER, tagSlug: TAG_SLUGS.TONIQUE },
  { productSlug: ANUA_PRODUCT_SLUGS.ANUA_AZELAIC_3_CICA_TONER, tagSlug: TAG_SLUGS.SANS_PARFUM },
]
