export const ANUA_PRODUCT_SLUGS = {
  ANUA_HEARTLEAF_77_SOOTHING: 'anua-heartleaf-77-soothing-toner',
  ANUA_RICE_70_GLOW_MILKY: 'anua-rice-70-glow-milky-toner',
  ANUA_AZELAIC_10_HYDRATING_REDNESS: 'anua-azelaic-acid-10-hyaluron-redness-soothing-serum',
  ANUA_AZELAIC_3_CICA_TONER: 'anua-azelaic-acid-3-cica-skin-clarifying-toner',
  AROMA_ZONE_CONCENTRE_AZELAIC_10: 'aroma-zone-serum-concentre-acide-azelaique-10',
}
export const ANUA_PRODUCT_DATA = [
  {
    name: 'Azelaic Acid 3% Cica Skin Clarifying Toner',
    brand: 'Anua',
    kind: 'skincare',
    unit: 'pump',
    slug: ANUA_PRODUCT_SLUGS.ANUA_AZELAIC_3_CICA_TONER,
    totalAmount: 250,
    amountUnit: 'ml',
    priceCents: 1531,
    description: 'Tonique clarifiant 3% azélaïque + cica + multi-acides. Apaisant mais exfoliant.',
    notes:
      'Concentration trop faible (3%), sur-exfoliation (salicylique + glycolique), HE irritantes (rosemary + tea tree). Incompatible rétinal/post-IPL.',
    inci: 'WATER, AZELAIC ACID (3%), 1,2-HEXANEDIOL, SODIUM HYDROXIDE, PROPYLENE GLYCOL, SALICYLIC ACID, DIPOTASSIUM GLYCYRRHIZATE, PROPANEDIOL, PPG-13-DECYLTETRADECETH-24, BUTYLENE GLYCOL, DISODIUM EDTA, MELIA AZADIRACHTA LEAF EXTRACT, GLYCERIN, ROSMARINUS OFFICINALIS (ROSEMARY) LEAF OIL, MELIA AZADIRACHTA FLOWER EXTRACT, CYNANCHUM ATRATUM EXTRACT, MELALEUCA ALTERNIFOLIA (TEA TREE) LEAF OIL, EPILOBIUM ANGUSTIFOLIUM FLOWER/LEAF/STEM EXTRACT, ETHYLHEXYLGLYCERIN, ALTHAEA ROSEA FLOWER EXTRACT, DOCOSAHEXAENOIC ACID, CITRIC ACID, TOCOPHEROL, MADECASSOSIDE, CENTELLA ASIATICA EXTRACT, PANTHENOL, GLYCINE SOJA (SOYBEAN) PROTEIN, CENTELLA ASIATICA LEAF EXTRACT, ASIATICOSIDE, ALLANTOIN, ECTOIN, GLYCYRRHIZIC ACID, HYDROXYETHYLCELLULOSE, SUCCINIC ACID, ZINC PCA, O-CYMEN-5-OL, SODIUM HYALURONATE, GLYCOLIC ACID, POTASSIUM AZELOYL DIGLYCINATE, COCO-CAPRYLATE/CAPRATE, SODIUM HYALURONATE CROSSPOLYMER, CENTELLA ASIATICA ROOT EXTRACT, HYDROGENATED LECITHIN, POLYGLUTAMIC ACID, XYLOSE, ASIATIC ACID, MADECASSIC ACID, TOTAROL, SQUALANE, CHLORELLA VULGARIS EXTRACT, CERAMIDE NP',
    url: 'https://anua.com',
  },
  {
    name: 'Azelaic Acid 10% Hyaluron Redness Soothing Serum',
    brand: 'Anua',
    kind: 'skincare',
    unit: 'pump',
    slug: ANUA_PRODUCT_SLUGS.ANUA_AZELAIC_10_HYDRATING_REDNESS,
    totalAmount: 30,
    amountUnit: 'ml',
    priceCents: 1697,
    description:
      'Sérum apaisant 10% acide azélaïque + céramides + 7x centella. Réduit rougeurs, imperfections, hyperpigmentation post-IPL, hydrate et répare barrière.',
    notes:
      'TOP 1 recommandé : céramide NP crucial post-IPL, 7 dérivés centella anti-inflammatoires, betaine salicylate doux compatible rétinal, texture légère non comédogène, 4.8/5 (4828 avis).',
    inci: 'WATER, AZELAIC ACID (10%), PROPYLENE GLYCOL, SODIUM HYDROXIDE, DIPROPYLENE GLYCOL, 1,2-HEXANEDIOL, PANTHENOL, HYDROXYETHYLCELLULOSE, BETAINE SALICYLATE, GLYCERIN, BIOSACCHARIDE GUM-1, ETHYLHEXYLGLYCERIN, ALLANTOIN, DIPOTASSIUM GLYCYRRHIZATE, MELIA AZADIRACHTA LEAF EXTRACT, CAMELLIA SINENSIS LEAF WATER, SODIUM HYALURONATE, MELIA AZADIRACHTA FLOWER EXTRACT, NIACINAMIDE, ALOE BARBADENSIS LEAF JUICE, BETA-GLUCAN, CENTELLA ASIATICA EXTRACT, CENTELLA ASIATICA LEAF EXTRACT, CENTELLA ASIATICA ROOT EXTRACT, MADECASSOSIDE, ASIATICOSIDE, ASIATIC ACID, MADECASSIC ACID, SQUALANE, ZINC PCA, BUTYLENE GLYCOL, PENTYLENE GLYCOL, CAPRYLYL/CAPRYL GLUCOSIDE, HYDROGENATED LECITHIN, CERAMIDE NP',
    url: 'https://anua.com',
  },
  {
    name: 'Rice 70 Glow Milky Toner',
    brand: 'Anua',
    kind: 'skincare',
    unit: 'pump',
    slug: ANUA_PRODUCT_SLUGS.ANUA_RICE_70_GLOW_MILKY,
    totalAmount: 250,
    amountUnit: 'ml',
    priceCents: 1428,
    description:
      'Tonique laiteux éclaircissant au riz 70% + niacinamide. Illumine teint terne, équilibre sébum, hydrate et renforce barrière.',
    notes:
      'Texture laiteuse légère non collante. Céramides NP/AP/EOP + HA multi-moléculaire + bêtaïne apaisante. Sans parfum, tous types de peau.',
    inci: 'ORYZA SATIVA (RICE) BRAN WATER, BUTYLENE GLYCOL, GLYCERIN, DIPROPYLENE GLYCOL, NIACINAMIDE, PROPANEDIOL, WATER, 1,2-HEXANEDIOL, METHYL GLUCETH-20, PANTHENOL, BETAINE, ORYZA SATIVA (RICE) EXTRACT, HYDROXYACETOPHENONE, DIPHENYL DIMETHICONE, TRIETHYLHEXANOIN, HYDROGENATED LECITHIN, ADENOSINE, ETHYLHEXYLGLYCERIN, CARBOMER, TROMETHAMINE, XANTHAN GUM, GLYCERYL ACRYLATE/ACRYLIC ACID COPOLYMER, THEOBROMA CACAO (COCOA) SEED EXTRACT, SODIUM HYALURONATE, HYDROLYZED HYALURONIC ACID, HYALURONIC ACID, DEXTRIN, HYDROLYZED RICE PROTEIN, ORYZA SATIVA (RICE) SEED PROTEIN, CERAMIDE NP, SODIUM LAUROYL LACTYLATE, ARBUTIN, ASCORBIC ACID, ALLANTOIN, CERAMIDE AP, PHYTOSPHINGOSINE, CHOLESTEROL, CERAMIDE EOP',
    url: 'https://anua.com',
  },
  {
    name: 'Heartleaf 77% Soothing Toner',
    brand: 'Anua',
    kind: 'skincare',
    unit: 'pump',
    slug: ANUA_PRODUCT_SLUGS.ANUA_HEARTLEAF_77_SOOTHING,
    totalAmount: 250,
    amountUnit: 'ml',
    priceCents: 1467,
    description:
      'Tonique apaisant 77% houttuynia cordata. Calme rougeurs/irritations, équilibre hydro-lipidique, pH doux.',
    notes:
      'Panthénol + centella + extraits végétaux EWG green. Non-irritant, tous types (idéal sensible/acnéique).',
    inci: 'HOUTTUYNIA CORDATA EXTRACT, PURIFIED WATER, 1,2-HEXANEDIOL, GLYCERIN, BETAINE, PANTHENOL, SACCHARUM OFFICINARUM (SUGARCANE) EXTRACT, PORTULACA OLERACEA EXTRACT, BUTYLENE GLYCOL, VITEX AGNUS-CASTUS EXTRACT, CHAMOMILLA RECUTITA (MATRICARIA) FLOWER EXTRACT, ARCTIUM LAPPA ROOT EXTRACT, PHELLINUS LINTEUS EXTRACT, VITIS VINIFERA (GRAPE) FRUIT EXTRACT, PYRUS MALUS (APPLE) FRUIT EXTRACT, CENTELLA ASIATICA EXTRACT, ISOPENTYLDIOL, METHYLPROPANEDIOL, ACRYLATES/C10-30 ALKYL ACRYLATE CROSSPOLYMER, TROMETHAMINE, DISODIUM EDTA',
    url: 'https://anua.com',
  },
]
