import { TAG_SLUGS } from '../../tags/seed-tags'
import { CORPS_PRODUCT_SLUGS } from './corps'

export const CORPS_PRODUCT_TAGS: { productSlug: string; tagSlug: string }[] = [
  // TOPIALYSE Baume Protect+ (Topicrem/SVR)
  { productSlug: CORPS_PRODUCT_SLUGS.TOPIALYSE_BAUME_PROTECT, tagSlug: TAG_SLUGS.PEAU_ATOPIQUE },
  { productSlug: CORPS_PRODUCT_SLUGS.TOPIALYSE_BAUME_PROTECT, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },
  { productSlug: CORPS_PRODUCT_SLUGS.TOPIALYSE_BAUME_PROTECT, tagSlug: TAG_SLUGS.REPARATEUR },
  { productSlug: CORPS_PRODUCT_SLUGS.TOPIALYSE_BAUME_PROTECT, tagSlug: TAG_SLUGS.OCCLUSIF },
  { productSlug: CORPS_PRODUCT_SLUGS.TOPIALYSE_BAUME_PROTECT, tagSlug: TAG_SLUGS.SANS_PARFUM },

  // TOPIALYSE Crème (Topicrem/SVR)
  { productSlug: CORPS_PRODUCT_SLUGS.TOPIALYSE_CREME, tagSlug: TAG_SLUGS.PEAU_SECHE },
  { productSlug: CORPS_PRODUCT_SLUGS.TOPIALYSE_CREME, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },
  { productSlug: CORPS_PRODUCT_SLUGS.TOPIALYSE_CREME, tagSlug: TAG_SLUGS.EMOLLIENT },
  { productSlug: CORPS_PRODUCT_SLUGS.TOPIALYSE_CREME, tagSlug: TAG_SLUGS.CREME_HYDRATANTE },

  // SVR XERIAL 10 Lait
  { productSlug: CORPS_PRODUCT_SLUGS.SVR_XERIAL_10_LAIT, tagSlug: TAG_SLUGS.PEAU_SECHE },
  { productSlug: CORPS_PRODUCT_SLUGS.SVR_XERIAL_10_LAIT, tagSlug: TAG_SLUGS.EXFOLIANT },
  { productSlug: CORPS_PRODUCT_SLUGS.SVR_XERIAL_10_LAIT, tagSlug: TAG_SLUGS.KERATOLYTIQUE },
  { productSlug: CORPS_PRODUCT_SLUGS.SVR_XERIAL_10_LAIT, tagSlug: TAG_SLUGS.HUMECTANT },

  // CeraVe Crème SA Anti-Rugosités
  { productSlug: CORPS_PRODUCT_SLUGS.CERAVE_SA_ANTI_RUGOSITES, tagSlug: TAG_SLUGS.EXFOLIANT },
  { productSlug: CORPS_PRODUCT_SLUGS.CERAVE_SA_ANTI_RUGOSITES, tagSlug: TAG_SLUGS.KERATOLYTIQUE },
  {
    productSlug: CORPS_PRODUCT_SLUGS.CERAVE_SA_ANTI_RUGOSITES,
    tagSlug: TAG_SLUGS.BARRIERE_CUTANEE,
  },
  { productSlug: CORPS_PRODUCT_SLUGS.CERAVE_SA_ANTI_RUGOSITES, tagSlug: TAG_SLUGS.NON_COMEDOGENE },
  { productSlug: CORPS_PRODUCT_SLUGS.CERAVE_SA_ANTI_RUGOSITES, tagSlug: TAG_SLUGS.SANS_PARFUM },

  // CeraVe Baume Hydratant
  { productSlug: CORPS_PRODUCT_SLUGS.CERAVE_BAUME_HYDRATANT, tagSlug: TAG_SLUGS.PEAU_SECHE },
  { productSlug: CORPS_PRODUCT_SLUGS.CERAVE_BAUME_HYDRATANT, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },
  { productSlug: CORPS_PRODUCT_SLUGS.CERAVE_BAUME_HYDRATANT, tagSlug: TAG_SLUGS.OCCLUSIF },
  { productSlug: CORPS_PRODUCT_SLUGS.CERAVE_BAUME_HYDRATANT, tagSlug: TAG_SLUGS.SANS_PARFUM },

  // CeraVe Crème Hydratante
  { productSlug: CORPS_PRODUCT_SLUGS.CERAVE_CREME_HYDRATANTE, tagSlug: TAG_SLUGS.PEAU_NORMALE },
  { productSlug: CORPS_PRODUCT_SLUGS.CERAVE_CREME_HYDRATANTE, tagSlug: TAG_SLUGS.PEAU_SECHE },
  { productSlug: CORPS_PRODUCT_SLUGS.CERAVE_CREME_HYDRATANTE, tagSlug: TAG_SLUGS.CREME_HYDRATANTE },
  { productSlug: CORPS_PRODUCT_SLUGS.CERAVE_CREME_HYDRATANTE, tagSlug: TAG_SLUGS.SANS_PARFUM },

  // CeraVe Lait Hydratant
  { productSlug: CORPS_PRODUCT_SLUGS.CERAVE_LAIT_HYDRATANT, tagSlug: TAG_SLUGS.PEAU_NORMALE },
  { productSlug: CORPS_PRODUCT_SLUGS.CERAVE_LAIT_HYDRATANT, tagSlug: TAG_SLUGS.DESHYDRATATION },
  { productSlug: CORPS_PRODUCT_SLUGS.CERAVE_LAIT_HYDRATANT, tagSlug: TAG_SLUGS.SANS_PARFUM },

  // Eucerin UreaRepair PLUS Lotion 10%
  { productSlug: CORPS_PRODUCT_SLUGS.EUCERIN_UREAREPAIR_LOTION_10, tagSlug: TAG_SLUGS.PEAU_SECHE },
  {
    productSlug: CORPS_PRODUCT_SLUGS.EUCERIN_UREAREPAIR_LOTION_10,
    tagSlug: TAG_SLUGS.KERATOLYTIQUE,
  },
  { productSlug: CORPS_PRODUCT_SLUGS.EUCERIN_UREAREPAIR_LOTION_10, tagSlug: TAG_SLUGS.HUMECTANT },
  { productSlug: CORPS_PRODUCT_SLUGS.EUCERIN_UREAREPAIR_LOTION_10, tagSlug: TAG_SLUGS.SANS_PARFUM },

  // Eucerin UreaRepair PLUS Crème 5%
  { productSlug: CORPS_PRODUCT_SLUGS.EUCERIN_UREAREPAIR_CREME_5, tagSlug: TAG_SLUGS.PEAU_SECHE },
  { productSlug: CORPS_PRODUCT_SLUGS.EUCERIN_UREAREPAIR_CREME_5, tagSlug: TAG_SLUGS.HUMECTANT },
  {
    productSlug: CORPS_PRODUCT_SLUGS.EUCERIN_UREAREPAIR_CREME_5,
    tagSlug: TAG_SLUGS.CREME_HYDRATANTE,
  },
  { productSlug: CORPS_PRODUCT_SLUGS.EUCERIN_UREAREPAIR_CREME_5, tagSlug: TAG_SLUGS.SANS_PARFUM },

  // Eucerin AtopiControl Baume
  { productSlug: CORPS_PRODUCT_SLUGS.EUCERIN_ATOPICONTROL_BAUME, tagSlug: TAG_SLUGS.PEAU_ATOPIQUE },
  {
    productSlug: CORPS_PRODUCT_SLUGS.EUCERIN_ATOPICONTROL_BAUME,
    tagSlug: TAG_SLUGS.BARRIERE_CUTANEE,
  },
  { productSlug: CORPS_PRODUCT_SLUGS.EUCERIN_ATOPICONTROL_BAUME, tagSlug: TAG_SLUGS.REPARATEUR },
  { productSlug: CORPS_PRODUCT_SLUGS.EUCERIN_ATOPICONTROL_BAUME, tagSlug: TAG_SLUGS.SANS_PARFUM },

  // La Roche-Posay Lipikar Baume AP+M
  { productSlug: CORPS_PRODUCT_SLUGS.LRP_LIPIKAR_BAUME_APM, tagSlug: TAG_SLUGS.PEAU_ATOPIQUE },
  { productSlug: CORPS_PRODUCT_SLUGS.LRP_LIPIKAR_BAUME_APM, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },
  { productSlug: CORPS_PRODUCT_SLUGS.LRP_LIPIKAR_BAUME_APM, tagSlug: TAG_SLUGS.REPARATEUR },
  { productSlug: CORPS_PRODUCT_SLUGS.LRP_LIPIKAR_BAUME_APM, tagSlug: TAG_SLUGS.SANS_PARFUM },

  // La Roche-Posay Lipikar Lait
  { productSlug: CORPS_PRODUCT_SLUGS.LRP_LIPIKAR_LAIT, tagSlug: TAG_SLUGS.PEAU_SECHE },
  { productSlug: CORPS_PRODUCT_SLUGS.LRP_LIPIKAR_LAIT, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },
  { productSlug: CORPS_PRODUCT_SLUGS.LRP_LIPIKAR_LAIT, tagSlug: TAG_SLUGS.EMOLLIENT },
  { productSlug: CORPS_PRODUCT_SLUGS.LRP_LIPIKAR_LAIT, tagSlug: TAG_SLUGS.SANS_PARFUM },

  // Bioderma Atoderm Intensive Baume
  {
    productSlug: CORPS_PRODUCT_SLUGS.BIODERMA_ATODERM_INTENSIVE_BAUME,
    tagSlug: TAG_SLUGS.PEAU_ATOPIQUE,
  },
  {
    productSlug: CORPS_PRODUCT_SLUGS.BIODERMA_ATODERM_INTENSIVE_BAUME,
    tagSlug: TAG_SLUGS.BARRIERE_CUTANEE,
  },
  {
    productSlug: CORPS_PRODUCT_SLUGS.BIODERMA_ATODERM_INTENSIVE_BAUME,
    tagSlug: TAG_SLUGS.REPARATEUR,
  },
  {
    productSlug: CORPS_PRODUCT_SLUGS.BIODERMA_ATODERM_INTENSIVE_BAUME,
    tagSlug: TAG_SLUGS.SANS_PARFUM,
  },

  // Bioderma Atoderm Crème Ultra
  { productSlug: CORPS_PRODUCT_SLUGS.BIODERMA_ATODERM_CREME_ULTRA, tagSlug: TAG_SLUGS.PEAU_SECHE },
  {
    productSlug: CORPS_PRODUCT_SLUGS.BIODERMA_ATODERM_CREME_ULTRA,
    tagSlug: TAG_SLUGS.PEAU_SENSIBLE,
  },
  {
    productSlug: CORPS_PRODUCT_SLUGS.BIODERMA_ATODERM_CREME_ULTRA,
    tagSlug: TAG_SLUGS.CREME_HYDRATANTE,
  },
  { productSlug: CORPS_PRODUCT_SLUGS.BIODERMA_ATODERM_CREME_ULTRA, tagSlug: TAG_SLUGS.SANS_PARFUM },

  // Bioderma Atoderm PP Baume
  { productSlug: CORPS_PRODUCT_SLUGS.BIODERMA_ATODERM_PP_BAUME, tagSlug: TAG_SLUGS.PEAU_SECHE },
  { productSlug: CORPS_PRODUCT_SLUGS.BIODERMA_ATODERM_PP_BAUME, tagSlug: TAG_SLUGS.REPARATEUR },
  {
    productSlug: CORPS_PRODUCT_SLUGS.BIODERMA_ATODERM_PP_BAUME,
    tagSlug: TAG_SLUGS.BARRIERE_CUTANEE,
  },
  { productSlug: CORPS_PRODUCT_SLUGS.BIODERMA_ATODERM_PP_BAUME, tagSlug: TAG_SLUGS.SANS_PARFUM },

  // Uriage Xémose C8+ Crème Relipidante
  {
    productSlug: CORPS_PRODUCT_SLUGS.URIAGE_XEMOSE_C8_PLUS_CORPS,
    tagSlug: TAG_SLUGS.PEAU_ATOPIQUE,
  },
  {
    productSlug: CORPS_PRODUCT_SLUGS.URIAGE_XEMOSE_C8_PLUS_CORPS,
    tagSlug: TAG_SLUGS.BARRIERE_CUTANEE,
  },
  { productSlug: CORPS_PRODUCT_SLUGS.URIAGE_XEMOSE_C8_PLUS_CORPS, tagSlug: TAG_SLUGS.EMOLLIENT },
  { productSlug: CORPS_PRODUCT_SLUGS.URIAGE_XEMOSE_C8_PLUS_CORPS, tagSlug: TAG_SLUGS.REPARATEUR },
  { productSlug: CORPS_PRODUCT_SLUGS.URIAGE_XEMOSE_C8_PLUS_CORPS, tagSlug: TAG_SLUGS.SANS_PARFUM },
]
