import { TAG_SLUGS } from '../../tags/seed-tags'
import { CORPS_PRODUCT_SLUGS } from './corps'

interface ProductTagGroups {
  primary: string[] // tags principaux / attendus / très représentatifs
  secondary: string[] // tags complémentaires / bonus / moins centraux
  avoid: string[] // tags à exclure (contre-indications fortes)
}

export const CORPS_PRODUCT_TAGS: Record<string, ProductTagGroups> = {
  // ─── CeraVe ───────────────────────────────────────────────────────────────
  [CORPS_PRODUCT_SLUGS.CERAVE_SA_ANTI_RUGOSITES]: {
    primary: [
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.EXFOLIANT,
      TAG_SLUGS.KERATOLYTIQUE,
      TAG_SLUGS.HUMECTANT,
      TAG_SLUGS.EMOLLIENT,
      TAG_SLUGS.DESHYDRATATION,
    ],
    secondary: [
      TAG_SLUGS.PEAU_NORMALE,
      TAG_SLUGS.BARRIERE_CUTANEE,
      TAG_SLUGS.BIOMIMETIQUE,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.NON_COMEDOGENE,
    ],
    avoid: [
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.PEAU_REACTIVE,
      TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE,
      TAG_SLUGS.PEAU_ATOPIQUE,
      TAG_SLUGS.GROSSESSE_COMPATIBLE,
    ],
  },

  [CORPS_PRODUCT_SLUGS.CERAVE_BAUME_HYDRATANT]: {
    primary: [
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.PEAU_ATOPIQUE,
      TAG_SLUGS.BARRIERE_CUTANEE,
      TAG_SLUGS.REPARATEUR,
      TAG_SLUGS.EMOLLIENT,
      TAG_SLUGS.OCCLUSIF,
      TAG_SLUGS.TEXTURE_RICHE,
    ],
    secondary: [
      TAG_SLUGS.BIOMIMETIQUE,
      TAG_SLUGS.HUMECTANT,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.NON_COMEDOGENE,
      TAG_SLUGS.GROSSESSE_COMPATIBLE,
    ],
    avoid: [TAG_SLUGS.PEAU_GRASSE, TAG_SLUGS.PEAU_MIXTE, TAG_SLUGS.ANTI_ACNE, TAG_SLUGS.BRILLANCE],
  },

  [CORPS_PRODUCT_SLUGS.CERAVE_CREME_HYDRATANTE]: {
    primary: [
      TAG_SLUGS.PEAU_NORMALE,
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.BARRIERE_CUTANEE,
      TAG_SLUGS.EMOLLIENT,
      TAG_SLUGS.HUMECTANT,
    ],
    secondary: [
      TAG_SLUGS.CREME_HYDRATANTE,
      TAG_SLUGS.BIOMIMETIQUE,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.NON_COMEDOGENE,
      TAG_SLUGS.GROSSESSE_COMPATIBLE,
    ],
    avoid: [TAG_SLUGS.PEAU_GRASSE, TAG_SLUGS.ANTI_ACNE, TAG_SLUGS.BRILLANCE],
  },

  [CORPS_PRODUCT_SLUGS.CERAVE_LAIT_HYDRATANT]: {
    primary: [
      TAG_SLUGS.PEAU_NORMALE,
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.BARRIERE_CUTANEE,
      TAG_SLUGS.HUMECTANT,
      TAG_SLUGS.EMOLLIENT,
      TAG_SLUGS.TEXTURE_LEGERE,
    ],
    secondary: [
      TAG_SLUGS.BIOMIMETIQUE,
      TAG_SLUGS.DESHYDRATATION,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.NON_COMEDOGENE,
      TAG_SLUGS.GROSSESSE_COMPATIBLE,
    ],
    avoid: [TAG_SLUGS.PEAU_GRASSE, TAG_SLUGS.ANTI_ACNE, TAG_SLUGS.BRILLANCE],
  },

  // ─── Eucerin ──────────────────────────────────────────────────────────────
  [CORPS_PRODUCT_SLUGS.EUCERIN_UREAREPAIR_LOTION_10]: {
    primary: [
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.EXFOLIANT,
      TAG_SLUGS.KERATOLYTIQUE,
      TAG_SLUGS.HUMECTANT,
      TAG_SLUGS.EMOLLIENT,
      TAG_SLUGS.DESHYDRATATION,
    ],
    secondary: [
      TAG_SLUGS.BARRIERE_CUTANEE,
      TAG_SLUGS.BIOMIMETIQUE,
      TAG_SLUGS.TEXTURE_LEGERE,
      TAG_SLUGS.SANS_PARFUM,
    ],
    avoid: [
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.PEAU_REACTIVE,
      TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE,
      TAG_SLUGS.GROSSESSE_COMPATIBLE,
    ],
  },

  [CORPS_PRODUCT_SLUGS.EUCERIN_UREAREPAIR_CREME_5]: {
    primary: [
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.HUMECTANT,
      TAG_SLUGS.EMOLLIENT,
      TAG_SLUGS.BARRIERE_CUTANEE,
      TAG_SLUGS.CREME_HYDRATANTE,
    ],
    secondary: [
      TAG_SLUGS.KERATOLYTIQUE,
      TAG_SLUGS.BIOMIMETIQUE,
      TAG_SLUGS.DESHYDRATATION,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.NON_COMEDOGENE,
    ],
    avoid: [
      TAG_SLUGS.PEAU_REACTIVE,
      TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE,
      TAG_SLUGS.GROSSESSE_COMPATIBLE,
    ],
  },

  [CORPS_PRODUCT_SLUGS.EUCERIN_ATOPICONTROL_BAUME]: {
    primary: [
      TAG_SLUGS.PEAU_ATOPIQUE,
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.ECZEMA,
      TAG_SLUGS.BARRIERE_CUTANEE,
      TAG_SLUGS.REPARATEUR,
      TAG_SLUGS.EMOLLIENT,
      TAG_SLUGS.OCCLUSIF,
      TAG_SLUGS.TEXTURE_RICHE,
    ],
    secondary: [
      TAG_SLUGS.BIOMIMETIQUE,
      TAG_SLUGS.HUMECTANT,
      TAG_SLUGS.ANTI_OXYDANT,
      TAG_SLUGS.APAISANT,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.NON_COMEDOGENE,
      TAG_SLUGS.GROSSESSE_COMPATIBLE,
    ],
    avoid: [TAG_SLUGS.PEAU_GRASSE, TAG_SLUGS.PEAU_MIXTE, TAG_SLUGS.ANTI_ACNE, TAG_SLUGS.BRILLANCE],
  },
}
