import type { FilterFieldConfig } from '../../Filter/Filter'

export type FilterKey = 'skinType' | 'concern' | 'attribute' | 'category'

export const INGREDIENT_FILTER_FIELDS: FilterFieldConfig<FilterKey>[] = [
  {
    key: 'category',
    label: 'Catégorie technique',
    placeholder: 'Toutes',
    options: [
      { value: 'actif', label: 'Actif' },
      { value: 'emollient', label: 'Émollient' },
      { value: 'occlusif', label: 'Occlusif' },
      { value: 'conservateur', label: 'Conservateur' },
      { value: 'tensioactif', label: 'Tensioactif' },
      { value: 'vitamine', label: 'Vitamine' },
      { value: 'mineral', label: 'Minéral' },
      { value: 'excipient', label: 'Excipient' },
    ],
  },
  {
    key: 'skinType',
    label: 'Type de peau',
    placeholder: 'Tous types',
    options: [
      { value: 'peau-seche', label: 'Peau sèche' },
      { value: 'peau-mixte', label: 'Peau mixte' },
      { value: 'peau-grasse', label: 'Peau grasse' },
      { value: 'peau-reactive', label: 'Peau réactive' },
      { value: 'peau-normale', label: 'Peau normale' },
      { value: 'peau-atopique', label: 'Peau atopique' },
      { value: 'peau-rugueuse', label: 'Peau rugueuse' },
      { value: 'tous-types', label: 'Tous types de peau' },
    ],
  },
  {
    key: 'concern',
    label: 'Problématique',
    placeholder: 'Toutes',
    options: [
      { value: 'anti-rougeurs', label: 'Anti-rougeurs' },
      { value: 'rosacee', label: 'Rosacée' },
      { value: 'couperose', label: 'Couperose' },
      { value: 'flushs', label: 'Flushs' },
      { value: 'peau-sensible', label: 'Peau sensible' },
      { value: 'anti-taches', label: 'Anti-taches' },
      { value: 'hyperpigmentation', label: 'Hyperpigmentation' },
      { value: 'anti-acne', label: 'Anti-acné' },
      { value: 'post-acne', label: 'Marques post-acné' },
      { value: 'anti-age', label: 'Anti-âge' },
      { value: 'deshydratation', label: 'Déshydratation' },
      { value: 'eclat', label: 'Éclat' },
      { value: 'teint-terne', label: 'Teint terne' },
      { value: 'pores-dilates', label: 'Pores dilatés' },
      { value: 'cernes-poches', label: 'Cernes & poches' },
      { value: 'brillance', label: 'Brillance' },
      { value: 'barriere-cutanee', label: 'Barrière cutanée' },
      { value: 'cicatrisation', label: 'Cicatrisation' },
      { value: 'repulpant', label: 'Repulpant' },
      { value: 'photo-vieillissement', label: 'Photo-vieillissement' },
      { value: 'lumiere-bleue', label: 'Lumière bleue' },
      { value: 'pollution', label: 'Pollution' },
      { value: 'microbiome', label: 'Microbiome' },
      { value: 'eczema', label: 'Eczéma' },
      { value: 'grain-peau', label: 'Grain de peau' },
      { value: 'keratose-pilaire', label: 'Kératose pilaire' },
    ],
  },
  {
    key: 'attribute',
    label: 'Propriétés & actions',
    placeholder: 'Toutes',
    options: [
      { value: 'anti-oxydant', label: 'Anti-oxydant' },
      { value: 'humectant', label: 'Humectant' },
      { value: 'emollient', label: 'Émollient' },
      { value: 'occlusif', label: 'Occlusif' },
      { value: 'reparateur', label: 'Réparateur' },
      { value: 'keratolytique', label: 'Kératolytique' },
      { value: 'sebo-regulateur', label: 'Sébo-régulateur' },
      { value: 'matifiant', label: 'Matifiant' },
      { value: 'antiseptique', label: 'Antiseptique' },
      { value: 'anti-bacterien', label: 'Anti-bactérien' },
      { value: 'apaisant', label: 'Apaisant' },
      { value: 'biomimetique', label: 'Biomimétique' },
      { value: 'prebiotique', label: 'Prébiotique' },
      { value: 'astringent', label: 'Astringent' },
      { value: 'texture-riche', label: 'Texture riche' },
      { value: 'texture-legere', label: 'Texture légère' },
      { value: 'protection-cutanee', label: 'Protection cutanée' },
      { value: 'sans-parfum', label: 'Sans parfum' },
      { value: 'non-comedogene', label: 'Non comédogène' },
      { value: 'comedogene', label: 'Comédogène' },
      { value: 'bio-naturel', label: 'Bio / Naturel' },
      { value: 'vegan', label: 'Vegan' },
      { value: 'cruelty-free', label: 'Cruelty-free' },
      { value: 'hypoallergenique', label: 'Hypoallergénique' },
      { value: 'pigments-verts', label: 'Pigments verts' },
      { value: 'sans-savon', label: 'Sans savon' },
      { value: 'filtres-chimiques', label: 'Filtres chimiques' },
      { value: 'filtres-mineraux', label: 'Filtres minéraux' },
      { value: 'grossesse-compatible', label: 'Grossesse compatible' },
      { value: 'barriere-cutanee-alteree', label: 'Barrière altérée' },
    ],
  },
]
