import { TAG_SLUGS } from '../../tags/seed-tags'
import { URIAGE_PRODUCT_SLUGS } from './uriage'

export const URIAGE_PRODUCT_TAGS: { productSlug: string; tagSlug: string }[] = [
  // ── Xémose C8+ Soin Visage ──────────────────────────────────────────────
  { productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_XEMOSE_C8_PLUS_VISAGE, tagSlug: TAG_SLUGS.PEAU_SECHE },
  {
    productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_XEMOSE_C8_PLUS_VISAGE,
    tagSlug: TAG_SLUGS.PEAU_ATOPIQUE,
  },
  {
    productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_XEMOSE_C8_PLUS_VISAGE,
    tagSlug: TAG_SLUGS.PEAU_SENSIBLE,
  },
  {
    productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_XEMOSE_C8_PLUS_VISAGE,
    tagSlug: TAG_SLUGS.CREME_HYDRATANTE,
  },
  {
    productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_XEMOSE_C8_PLUS_VISAGE,
    tagSlug: TAG_SLUGS.SOIN_DE_JOUR,
  },
  {
    productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_XEMOSE_C8_PLUS_VISAGE,
    tagSlug: TAG_SLUGS.BARRIERE_CUTANEE,
  },
  { productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_XEMOSE_C8_PLUS_VISAGE, tagSlug: TAG_SLUGS.REPARATEUR },
  { productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_XEMOSE_C8_PLUS_VISAGE, tagSlug: TAG_SLUGS.EMOLLIENT },
  {
    productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_XEMOSE_C8_PLUS_VISAGE,
    tagSlug: TAG_SLUGS.SANS_PARFUM,
  },
  {
    productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_XEMOSE_C8_PLUS_VISAGE,
    tagSlug: TAG_SLUGS.HYPOALLERGENIQUE,
  },

  // ── Roséliane Soin Anti-Rougeurs (fluide) ──────────────────────────────
  { productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_ROSELIANE, tagSlug: TAG_SLUGS.ANTI_ROUGEURS },
  { productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_ROSELIANE, tagSlug: TAG_SLUGS.ROSACEE },
  { productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_ROSELIANE, tagSlug: TAG_SLUGS.COUPEROSE },
  { productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_ROSELIANE, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },
  { productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_ROSELIANE, tagSlug: TAG_SLUGS.PEAU_REACTIVE },
  { productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_ROSELIANE, tagSlug: TAG_SLUGS.CREME_HYDRATANTE },
  { productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_ROSELIANE, tagSlug: TAG_SLUGS.SOIN_DE_JOUR },
  { productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_ROSELIANE, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },
  { productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_ROSELIANE, tagSlug: TAG_SLUGS.PIGMENTS_VERTS },

  // ── HYSEAC Sérum ────────────────────────────────────────────────────────
  { productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_HYSEAC_SERUM, tagSlug: TAG_SLUGS.ANTI_ACNE },
  { productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_HYSEAC_SERUM, tagSlug: TAG_SLUGS.POST_ACNE },
  { productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_HYSEAC_SERUM, tagSlug: TAG_SLUGS.PORES_DILATES },
  { productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_HYSEAC_SERUM, tagSlug: TAG_SLUGS.BRILLANCE },
  { productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_HYSEAC_SERUM, tagSlug: TAG_SLUGS.PEAU_GRASSE },
  { productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_HYSEAC_SERUM, tagSlug: TAG_SLUGS.PEAU_MIXTE },
  { productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_HYSEAC_SERUM, tagSlug: TAG_SLUGS.SERUM },
  { productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_HYSEAC_SERUM, tagSlug: TAG_SLUGS.KERATOLYTIQUE },
  { productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_HYSEAC_SERUM, tagSlug: TAG_SLUGS.SEBO_REGULATEUR },
  { productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_HYSEAC_SERUM, tagSlug: TAG_SLUGS.NON_COMEDOGENE },

  // ── Cica Daily Sérum ────────────────────────────────────────────────────
  { productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_CICA_DAILY_SERUM, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },
  { productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_CICA_DAILY_SERUM, tagSlug: TAG_SLUGS.PEAU_REACTIVE },
  { productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_CICA_DAILY_SERUM, tagSlug: TAG_SLUGS.SERUM },
  {
    productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_CICA_DAILY_SERUM,
    tagSlug: TAG_SLUGS.BARRIERE_CUTANEE,
  },
  { productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_CICA_DAILY_SERUM, tagSlug: TAG_SLUGS.REPARATEUR },
  { productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_CICA_DAILY_SERUM, tagSlug: TAG_SLUGS.HUMECTANT },
  { productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_CICA_DAILY_SERUM, tagSlug: TAG_SLUGS.DESHYDRATATION },
  { productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_CICA_DAILY_SERUM, tagSlug: TAG_SLUGS.SANS_PARFUM },

  // ── Roséliane Sérum ─────────────────────────────────────────────────────
  { productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_ROSELIANE_SERUM, tagSlug: TAG_SLUGS.ANTI_ROUGEURS },
  { productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_ROSELIANE_SERUM, tagSlug: TAG_SLUGS.ROSACEE },
  { productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_ROSELIANE_SERUM, tagSlug: TAG_SLUGS.COUPEROSE },
  { productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_ROSELIANE_SERUM, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },
  { productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_ROSELIANE_SERUM, tagSlug: TAG_SLUGS.SERUM },
  { productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_ROSELIANE_SERUM, tagSlug: TAG_SLUGS.ANTI_AGE },
  { productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_ROSELIANE_SERUM, tagSlug: TAG_SLUGS.PIGMENTS_VERTS },
  { productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_ROSELIANE_SERUM, tagSlug: TAG_SLUGS.SANS_PARFUM },

  // ── Dépiderm Sérum ──────────────────────────────────────────────────────
  { productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_DEPIDERM_SERUM, tagSlug: TAG_SLUGS.ANTI_TACHES },
  { productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_DEPIDERM_SERUM, tagSlug: TAG_SLUGS.HYPERPIGMENTATION },
  { productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_DEPIDERM_SERUM, tagSlug: TAG_SLUGS.ECLAT },
  { productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_DEPIDERM_SERUM, tagSlug: TAG_SLUGS.POST_ACNE },
  { productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_DEPIDERM_SERUM, tagSlug: TAG_SLUGS.SERUM },
  { productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_DEPIDERM_SERUM, tagSlug: TAG_SLUGS.ANTI_OXYDANT },
  { productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_DEPIDERM_SERUM, tagSlug: TAG_SLUGS.KERATOLYTIQUE },
  { productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_DEPIDERM_SERUM, tagSlug: TAG_SLUGS.NON_COMEDOGENE },
  { productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_DEPIDERM_SERUM, tagSlug: TAG_SLUGS.SANS_PARFUM },

  // ── Xémose C8+ Huile Lavante ────────────────────────────────────────────
  { productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_XEMOSE_HUILE_LAVANTE, tagSlug: TAG_SLUGS.PEAU_SECHE },
  {
    productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_XEMOSE_HUILE_LAVANTE,
    tagSlug: TAG_SLUGS.PEAU_ATOPIQUE,
  },
  {
    productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_XEMOSE_HUILE_LAVANTE,
    tagSlug: TAG_SLUGS.PEAU_SENSIBLE,
  },
  { productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_XEMOSE_HUILE_LAVANTE, tagSlug: TAG_SLUGS.NETTOYANT },
  { productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_XEMOSE_HUILE_LAVANTE, tagSlug: TAG_SLUGS.HUILE },
  { productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_XEMOSE_HUILE_LAVANTE, tagSlug: TAG_SLUGS.SANS_SAVON },
  { productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_XEMOSE_HUILE_LAVANTE, tagSlug: TAG_SLUGS.EMOLLIENT },
  { productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_XEMOSE_HUILE_LAVANTE, tagSlug: TAG_SLUGS.SANS_PARFUM },
  {
    productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_XEMOSE_HUILE_LAVANTE,
    tagSlug: TAG_SLUGS.HYPOALLERGENIQUE,
  },

  // ── Xémose C8+ Baume Relipidant ─────────────────────────────────────────
  { productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_XEMOSE_BAUME, tagSlug: TAG_SLUGS.PEAU_SECHE },
  { productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_XEMOSE_BAUME, tagSlug: TAG_SLUGS.PEAU_ATOPIQUE },
  { productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_XEMOSE_BAUME, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },
  { productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_XEMOSE_BAUME, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },
  { productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_XEMOSE_BAUME, tagSlug: TAG_SLUGS.REPARATEUR },
  { productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_XEMOSE_BAUME, tagSlug: TAG_SLUGS.EMOLLIENT },
  { productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_XEMOSE_BAUME, tagSlug: TAG_SLUGS.OCCLUSIF },
  { productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_XEMOSE_BAUME, tagSlug: TAG_SLUGS.SANS_PARFUM },
  { productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_XEMOSE_BAUME, tagSlug: TAG_SLUGS.HYPOALLERGENIQUE },

  // ── Gel Surgras Dermatologique ──────────────────────────────────────────
  { productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_GEL_SURGRAS, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },
  { productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_GEL_SURGRAS, tagSlug: TAG_SLUGS.PEAU_SECHE },
  { productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_GEL_SURGRAS, tagSlug: TAG_SLUGS.NETTOYANT },
  { productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_GEL_SURGRAS, tagSlug: TAG_SLUGS.SANS_SAVON },
  { productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_GEL_SURGRAS, tagSlug: TAG_SLUGS.EMOLLIENT },

  // ── Roséliane Soin Anti-Rougeurs Crème ──────────────────────────────────
  { productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_ROSELIANE_CREME, tagSlug: TAG_SLUGS.ANTI_ROUGEURS },
  { productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_ROSELIANE_CREME, tagSlug: TAG_SLUGS.ROSACEE },
  { productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_ROSELIANE_CREME, tagSlug: TAG_SLUGS.COUPEROSE },
  { productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_ROSELIANE_CREME, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },
  { productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_ROSELIANE_CREME, tagSlug: TAG_SLUGS.PEAU_REACTIVE },
  { productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_ROSELIANE_CREME, tagSlug: TAG_SLUGS.CREME_HYDRATANTE },
  { productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_ROSELIANE_CREME, tagSlug: TAG_SLUGS.SOIN_DE_JOUR },
  { productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_ROSELIANE_CREME, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },
  { productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_ROSELIANE_CREME, tagSlug: TAG_SLUGS.PIGMENTS_VERTS },

  // ── Roséliane Soin Teinté SPF50+ ────────────────────────────────────────
  { productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_ROSELIANE_TEINTE, tagSlug: TAG_SLUGS.ANTI_ROUGEURS },
  { productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_ROSELIANE_TEINTE, tagSlug: TAG_SLUGS.ROSACEE },
  { productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_ROSELIANE_TEINTE, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },
  {
    productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_ROSELIANE_TEINTE,
    tagSlug: TAG_SLUGS.PROTECTION_SOLAIRE,
  },
  { productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_ROSELIANE_TEINTE, tagSlug: TAG_SLUGS.SOIN_DE_JOUR },
  { productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_ROSELIANE_TEINTE, tagSlug: TAG_SLUGS.NON_COMEDOGENE },
  { productSlug: URIAGE_PRODUCT_SLUGS.URIAGE_ROSELIANE_TEINTE, tagSlug: TAG_SLUGS.PIGMENTS_VERTS },
]
