import { TAG_SLUGS } from '../../tags/seed-tags'
import { ADERMA_PRODUCT_SLUGS } from './aDerma'

export const ADERMA_PRODUCT_TAGS: { productSlug: string; tagSlug: string }[] = [
  // Biology AR
  { productSlug: ADERMA_PRODUCT_SLUGS.ADERMA_BIOLOGY_AR, tagSlug: TAG_SLUGS.ANTI_ROUGEURS },
  { productSlug: ADERMA_PRODUCT_SLUGS.ADERMA_BIOLOGY_AR, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },
  { productSlug: ADERMA_PRODUCT_SLUGS.ADERMA_BIOLOGY_AR, tagSlug: TAG_SLUGS.PEAU_REACTIVE },
  { productSlug: ADERMA_PRODUCT_SLUGS.ADERMA_BIOLOGY_AR, tagSlug: TAG_SLUGS.CREME_HYDRATANTE },
  { productSlug: ADERMA_PRODUCT_SLUGS.ADERMA_BIOLOGY_AR, tagSlug: TAG_SLUGS.BIO_NATUREL },
  { productSlug: ADERMA_PRODUCT_SLUGS.ADERMA_BIOLOGY_AR, tagSlug: TAG_SLUGS.SANS_PARFUM },
  { productSlug: ADERMA_PRODUCT_SLUGS.ADERMA_BIOLOGY_AR, tagSlug: TAG_SLUGS.VEGAN },

  // Lait Corps 72h
  { productSlug: ADERMA_PRODUCT_SLUGS.ADERMA_LAIT_CORPS_72H, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },
  { productSlug: ADERMA_PRODUCT_SLUGS.ADERMA_LAIT_CORPS_72H, tagSlug: TAG_SLUGS.DESHYDRATATION },
  { productSlug: ADERMA_PRODUCT_SLUGS.ADERMA_LAIT_CORPS_72H, tagSlug: TAG_SLUGS.CREME_HYDRATANTE },
  { productSlug: ADERMA_PRODUCT_SLUGS.ADERMA_LAIT_CORPS_72H, tagSlug: TAG_SLUGS.VEGAN },

  // Gel Douche Surgras
  { productSlug: ADERMA_PRODUCT_SLUGS.ADERMA_GEL_DOUCHE_SURGRAS, tagSlug: TAG_SLUGS.PEAU_SECHE },
  { productSlug: ADERMA_PRODUCT_SLUGS.ADERMA_GEL_DOUCHE_SURGRAS, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },
  { productSlug: ADERMA_PRODUCT_SLUGS.ADERMA_GEL_DOUCHE_SURGRAS, tagSlug: TAG_SLUGS.NETTOYANT },
  { productSlug: ADERMA_PRODUCT_SLUGS.ADERMA_GEL_DOUCHE_SURGRAS, tagSlug: TAG_SLUGS.EMOLLIENT },

  // Exomega Lait Émollient
  {
    productSlug: ADERMA_PRODUCT_SLUGS.ADERMA_EXOMEGA_LAIT_EMOLLIENT,
    tagSlug: TAG_SLUGS.PEAU_ATOPIQUE,
  },
  {
    productSlug: ADERMA_PRODUCT_SLUGS.ADERMA_EXOMEGA_LAIT_EMOLLIENT,
    tagSlug: TAG_SLUGS.PEAU_SECHE,
  },
  {
    productSlug: ADERMA_PRODUCT_SLUGS.ADERMA_EXOMEGA_LAIT_EMOLLIENT,
    tagSlug: TAG_SLUGS.BARRIERE_CUTANEE,
  },
  { productSlug: ADERMA_PRODUCT_SLUGS.ADERMA_EXOMEGA_LAIT_EMOLLIENT, tagSlug: TAG_SLUGS.EMOLLIENT },
  {
    productSlug: ADERMA_PRODUCT_SLUGS.ADERMA_EXOMEGA_LAIT_EMOLLIENT,
    tagSlug: TAG_SLUGS.REPARATEUR,
  },
  {
    productSlug: ADERMA_PRODUCT_SLUGS.ADERMA_EXOMEGA_LAIT_EMOLLIENT,
    tagSlug: TAG_SLUGS.SANS_PARFUM,
  },

  // Exomega Huile Lavante
  { productSlug: ADERMA_PRODUCT_SLUGS.ADERMA_EXOMEGA_HUILE_500, tagSlug: TAG_SLUGS.PEAU_ATOPIQUE },
  { productSlug: ADERMA_PRODUCT_SLUGS.ADERMA_EXOMEGA_HUILE_500, tagSlug: TAG_SLUGS.PEAU_SECHE },
  { productSlug: ADERMA_PRODUCT_SLUGS.ADERMA_EXOMEGA_HUILE_500, tagSlug: TAG_SLUGS.NETTOYANT },
  { productSlug: ADERMA_PRODUCT_SLUGS.ADERMA_EXOMEGA_HUILE_500, tagSlug: TAG_SLUGS.HUILE },
  { productSlug: ADERMA_PRODUCT_SLUGS.ADERMA_EXOMEGA_HUILE_500, tagSlug: TAG_SLUGS.EMOLLIENT },
]
