export const ADERMA_PRODUCT_SLUGS = {
  ADERMA_EXOMEGA_HUILE_500: 'aderma-exomega-huile-500',
  ADERMA_EXOMEGA_LAIT_EMOLLIENT: 'aderma-lait-emollient',
  ADERMA_GEL_DOUCHE_SURGRAS: 'aderma-gel-douche-surgras',
  ADERMA_LAIT_CORPS_72H: 'aderma-lait-corps-72h',
  ADERMA_BIOLOGY_AR: 'a-derma-biology-ar',
}
export const ADERMA_PRODUCT_DATA = [
  {
    name: 'Biology AR',
    brand: 'A-Derma',
    kind: 'skincare',
    unit: 'pump',
    slug: ADERMA_PRODUCT_SLUGS.ADERMA_BIOLOGY_AR,
    totalAmount: 40,
    amountUnit: 'ml',
    priceCents: 1750,
    description: 'Soin dermatologique certifié Bio pour apaiser les peaux fragiles.',
    notes: 'Certifié COSMOS ORGANIC. 99% naturel.',
    inci: 'WATER (AQUA). GLYCERIN. DICAPRYLYL CARBONATE. PENTYLENE GLYCOL. C14-22 ALCOHOLS. BUTYLENE GLYCOL. HELIANTHUS ANNUUS (SUNFLOWER) SEED OIL (HELIANTHUS ANNUUS SEED OIL). BEHENYL ALCOHOL. CITRUS AURANTIUM DULCIS (ORANGE) FRUIT WATER (CITRUS AURANTIUM DULCIS FRUIT WATER). SODIUM STEAROYL GLUTAMATE. ALOE BARBADENSIS LEAF JUICE POWDER. AVENA SATIVA (OAT) FLOWER/LEAF/STEM JUICE (AVENA SATIVA FLOWER/LEAF/STEM JUICE). C12-20 ALKYL GLUCOSIDE. CITRIC ACID. CITRUS RETICULATA (TANGERINE) PEEL EXTRACT (CITRUS RETICULATA PEEL EXTRACT). GLYCERYL CAPRYLATE. SCLEROTIUM GUM. SODIUM BENZOATE. TARAXACUM OFFICINALE (DANDELION) RHIZOME/ROOT EXTRACT (TARAXACUM OFFICINALE RHIZOME/ROOT EXTRACT). TOCOPHEROL. XANTHAN GUM',
  },
  {
    name: 'Les Indispensables Lait Corps Hydratation 72h',
    brand: 'A-Derma',
    kind: 'skincare',
    unit: 'pump',
    slug: ADERMA_PRODUCT_SLUGS.ADERMA_LAIT_CORPS_72H,
    totalAmount: 400,
    amountUnit: 'ml',
    priceCents: 1119,
    description:
      'Lait corps hydratation 72h pour peaux fragiles. Enrichi en acide hyaluronique et Avoine Rhealba®.',
    notes: '92% origine naturelle. Convient dès 2 ans. Vegan. Délicatement parfumé, non collant.',
    inci: 'AQUA/WATER, GLYCERIN, CAPRYLIC/CAPRIC TRIGLYCERIDE, ISOPROPYL PALMITATE, PROPYLENE GLYCOL, C14-22 ALCOHOLS, DIMETHICONE, HYDROXYETHYL ACRYLATE/SODIUM ACRYLOYLDIMETHYL TAURATE COPOLYMER, AVENA SATIVA (OAT) SPROUT OIL, BENZOIC ACID, C12-20 ALKYL GLUCOSIDE, C20-22 ALCOHOLS, C20-22 ALKYL PHOSPHATE, CAPRYLYL GLYCOL, FRAGRANCE, POLYSORBATE 60, SODIUM HYALURONATE, SODIUM HYDROXIDE, SORBITAN ISOSTEARATE, SQUALANE, TOCOPHERYL ACETATE, XANTHAN GUM',
    url: 'https://www.aderma.fr',
  },
  {
    name: 'Les Indispensables Gel Douche Surgras',
    brand: 'A-Derma',
    kind: 'skincare',
    unit: 'pump',
    slug: ADERMA_PRODUCT_SLUGS.ADERMA_GEL_DOUCHE_SURGRAS,
    totalAmount: 750,
    amountUnit: 'ml',
    priceCents: 936,
    description:
      'Gel douche surgras pour peaux sèches et délicates. Nettoie, hydrate et nourrit au quotidien.',
    notes: "Lait d'Avoine Rhealba®. Visage et corps. Eco-conçu.",
    inci: 'AQUA/WATER, GLYCERIN, HYDROGENATED STARCH HYDROLYSATE, CETEARETH-60 MYRISTYL GLYCOL, DECYL GLUCOSIDE, SODIUM LAUROYL METHYL ISETHIONATE, POLYSORBATE 20, DISODIUM COCOAMPHODIACETATE, AVENA SATIVA (OAT) KERNEL EXTRACT, CAPRYLYL GLYCOL, CARAMEL, CITRIC ACID, COCO-GLUCOSIDE, FRAGRANCE, GLYCERYL OLEATE, HYDROGENATED PALM GLYCERIDES CITRATE, LAURIC ACID, PROPYLENE GLYCOL, SODIUM BENZOATE, SODIUM CHLORIDE, SODIUM GLYCOLATE, SODIUM METHYL ISETHIONATE, TOCOPHEROL, TRISODIUM ETHYLENEDIAMINE DISUCCINATE',
    url: 'https://www.aderma.fr',
  },
  {
    name: 'Exomega Control Lait Émollient Anti-Grattage',
    brand: 'A-Derma',
    kind: 'skincare',
    unit: 'pump',
    slug: ADERMA_PRODUCT_SLUGS.ADERMA_EXOMEGA_LAIT_EMOLLIENT,
    totalAmount: 400,
    amountUnit: 'ml',
    priceCents: 1908,
    description:
      'Lait émollient anti-grattage pour peaux sèches à tendance atopique. Apaise, nourrit et renforce la barrière cutanée.',
    notes: '95% origine naturelle. Sans parfum. Dès la naissance. Niacinamide. 1 application/jour.',
    inci: 'AQUA/WATER, GLYCERIN, CAPRYLIC/CAPRIC TRIGLYCERIDE, GLYCERYL STEARATE, NIACINAMIDE, PEG-100 STEARATE, 10-HYDROXYDECENOIC ACID, AVENA SATIVA (OAT) LEAF/STEM EXTRACT, BENZOIC ACID, CAPRYLYL GLYCOL, CARBOMER, CETEARYL ALCOHOL, CETEARYL GLUCOSIDE, OENOTHERA BIENNIS (EVENING PRIMROSE) OIL, POLYACRYLATE-13, POLYISOBUTENE, POLYSORBATE 20, SODIUM HYDROXIDE, SORBITAN ISOSTEARATE, TOCOPHEROL, TOCOPHERYL ACETATE',
    url: 'https://www.aderma.fr',
  },
  {
    name: 'Exomega Control Huile Lavante Émolliente Anti-Grattage',
    brand: 'A-Derma',
    kind: 'skincare',
    unit: 'pump',
    slug: ADERMA_PRODUCT_SLUGS.ADERMA_EXOMEGA_HUILE_500,
    totalAmount: 500,
    amountUnit: 'ml',
    priceCents: 1249,
    description: 'Huile lavante émolliente anti-grattage pour peaux sèches à tendance atopique.',
    notes:
      '91% origine naturelle. Dès la naissance. Ne pique pas les yeux. Avoine Rhealba® + onagre.',
    inci: 'AQUA/WATER, GLYCERIN, HYDROGENATED STARCH HYDROLYSATE, COCO-GLUCOSIDE, ZINC COCETH SULFATE, SODIUM COCOAMPHOACETATE, CETEARETH-60 MYRISTYL GLYCOL, PEG-40 HYDROGENATED CASTOR OIL, 10-HYDROXYDECENOIC ACID, ASCORBYL PALMITATE, AVENA SATIVA (OAT) LEAF/STEM EXTRACT, CITRIC ACID, FRAGRANCE, GLYCERYL OLEATE, HYDROGENATED PALM GLYCERIDES CITRATE, LAURIC ACID, LECITHIN, OENOTHERA BIENNIS (EVENING PRIMROSE) OIL, PEG-120 METHYL GLUCOSE DIOLEATE, PROPYLENE GLYCOL, SODIUM BENZOATE, SODIUM CHLORIDE, SODIUM HYDROXIDE, SODIUM LAUROYL METHYL ISETHIONATE, SODIUM METHYL ISETHIONATE, TOCOPHEROL, TRISODIUM ETHYLENEDIAMINE DISUCCINATE',
    url: 'https://www.aderma.fr',
  },
]
