import { TAG_SLUGS } from '../../tags/seed-tags'
import { SOLAIRES_PRODUCT_SLUGS } from './solaires'

interface ProductTagGroups {
  primary: string[] // Tags principaux
  secondary: string[] // Tags secondaires
  avoid: string[] // Tags à éviter/exclure
}

export const SOLAIRES_PRODUCT_TAGS: Record<string, ProductTagGroups> = {
  // ── Actinica
  [SOLAIRES_PRODUCT_SLUGS.ACTINICA_LOTION_SPF50_LOT3]: {
    primary: [
      TAG_SLUGS.PROTECTION_SOLAIRE,
      TAG_SLUGS.SOLAIRE_VISAGE,
      TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE,
    ],
    secondary: [TAG_SLUGS.TEXTURE_LEGERE, TAG_SLUGS.FILTRES_CHIMIQUES, TAG_SLUGS.SANS_PARFUM],
    avoid: [],
  },

  // ── Eucerin
  [SOLAIRES_PRODUCT_SLUGS.EUCERIN_PHOTOAGING_CONTROL_FLUIDE_SPF50]: {
    primary: [
      TAG_SLUGS.PROTECTION_SOLAIRE,
      TAG_SLUGS.ANTI_AGE,
      TAG_SLUGS.PHOTO_VIEILLISSEMENT,
      TAG_SLUGS.SOLAIRE_VISAGE,
    ],
    secondary: [
      TAG_SLUGS.MATIFIANT,
      TAG_SLUGS.TEXTURE_LEGERE,
      TAG_SLUGS.FILTRES_CHIMIQUES,
      TAG_SLUGS.PEAU_SENSIBLE,
    ],
    avoid: [],
  },

  [SOLAIRES_PRODUCT_SLUGS.EUCERIN_LEB_PROTECT_CREME_GEL_SPF50]: {
    primary: [
      TAG_SLUGS.PROTECTION_SOLAIRE,
      TAG_SLUGS.PEAU_REACTIVE,
      TAG_SLUGS.SOLAIRE_CORPS,
      TAG_SLUGS.SOLAIRE_VISAGE,
    ],
    secondary: [TAG_SLUGS.TEXTURE_LEGERE, TAG_SLUGS.FILTRES_CHIMIQUES, TAG_SLUGS.APAISANT],
    avoid: [],
  },

  // ── Riemann P20
  [SOLAIRES_PRODUCT_SLUGS.RIEMANN_P20_SENSITIVE_FACE_SPF50]: {
    primary: [TAG_SLUGS.PROTECTION_SOLAIRE, TAG_SLUGS.PEAU_SENSIBLE, TAG_SLUGS.SOLAIRE_VISAGE],
    secondary: [
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.FILTRES_CHIMIQUES,
      TAG_SLUGS.APAISANT,
      TAG_SLUGS.HYPOALLERGENIQUE,
    ],
    avoid: [],
  },

  [SOLAIRES_PRODUCT_SLUGS.RIEMANN_P20_URBAN_SHIELD_SPF50]: {
    primary: [
      TAG_SLUGS.PROTECTION_SOLAIRE,
      TAG_SLUGS.POLLUTION,
      TAG_SLUGS.ANTI_OXYDANT,
      TAG_SLUGS.SOLAIRE_VISAGE,
    ],
    secondary: [TAG_SLUGS.TEXTURE_LEGERE, TAG_SLUGS.FILTRES_CHIMIQUES, TAG_SLUGS.SOIN_DE_JOUR],
    avoid: [],
  },

  [SOLAIRES_PRODUCT_SLUGS.RIEMANN_P20_SENSITIVE_SKIN_SPF50]: {
    primary: [TAG_SLUGS.PROTECTION_SOLAIRE, TAG_SLUGS.PEAU_SENSIBLE, TAG_SLUGS.SOLAIRE_CORPS],
    secondary: [TAG_SLUGS.SANS_PARFUM, TAG_SLUGS.FILTRES_CHIMIQUES, TAG_SLUGS.HYPOALLERGENIQUE],
    avoid: [],
  },
}
