// ─── Slugs ────────────────────────────────────────────────

export const SOLAIRES_PRODUCT_SLUGS = {
  ACTINICA_LOTION_SPF50_LOT3: 'actinica-lotion-tres-haute-protection-spf50-lot-3',
  EUCERIN_PHOTOAGING_CONTROL_FLUIDE_SPF50:
    'eucerin-sun-protection-photoaging-control-fluide-anti-age-spf50',
  EUCERIN_LEB_PROTECT_CREME_GEL_SPF50:
    'eucerin-sun-protection-leb-protect-creme-gel-visage-corps-spf50',
  RIEMANN_P20_SENSITIVE_FACE_SPF50: 'riemann-p20-sensitive-face-creme-solaire-ip50-plus',
  RIEMANN_P20_URBAN_SHIELD_SPF50: 'riemann-p20-urban-shield-creme-solaire-ip50-plus',
  RIEMANN_P20_SENSITIVE_SKIN_SPF50: 'riemann-p20-sensitive-skin-creme-solaire-ip50-plus',

  // TODO
}

// ─── Data ─────────────────────────────────────────────────

export const SOLAIRE_PRODUCT_DATA = [
  {
    name: 'Lotion Très Haute Protection SPF50+ Lot de 3',
    brand: 'Actinica',
    kind: 'skincare',
    unit: 'pump',
    slug: SOLAIRES_PRODUCT_SLUGS.ACTINICA_LOTION_SPF50_LOT3,
    totalAmount: 80,
    amountUnit: 'g',
    priceCents: 1449,
    description:
      'Lotion SPF50+ prévention kératoses actiniques et cancers cutanés non-mélanomes. Très haute protection UVA/UVB.',
    notes:
      'Filtres chimiques large spectre. Texture lotion légère. Usage quotidien peaux à risque.',
    inci: 'BIS-ETHYLHEXYLOXYPHENOL METHOXYPHENYL TRIAZINE, ETHYLHEXYL TRIAZONE, ISOAMYL P-METHOXYCINNAMATE, ETHYLHEXYL METHOXYCINNAMATE, METHYLENE BIS-BENZOTRIAZOLYL TETRAMETHYLBUTYLPHENOL, BUTYL METHOXYDIBENZOYLMETHANE, PROPYLPARABEN, METHYLPARABEN, EXCIPIENT',
    url: 'https://www.actinica.com',
  },

  {
    name: 'Sun Protection Photoaging Control Fluide Anti-Âge SPF50',
    brand: 'Eucerin',
    kind: 'skincare',
    unit: 'pump',
    slug: SOLAIRES_PRODUCT_SLUGS.EUCERIN_PHOTOAGING_CONTROL_FLUIDE_SPF50,
    totalAmount: 50,
    amountUnit: 'ml',
    priceCents: 1249,
    description:
      'Fluide anti-âge SPF50 protection photo-vieillissement. Anti-rides, raffermissant, matifiant.',
    notes:
      'Filtres chimiques + Glycyrrhetinic Acid + extrait réglisse + HA. Texture fluide légère, peaux matures/sensibles.',
    inci: 'AQUA, C12-15 ALKYL BENZOATE, GLYCERIN, ALCOHOL DENAT., BUTYL METHOXYDIBENZOYLMETHANE, BIS-ETHYLHEXYLOXYPHENOL METHOXYPHENYL TRIAZINE, BUTYLENE GLYCOL DICAPRYLATE/DICAPRATE, ETHYLHEXYL TRIAZONE, DIBUTYL ADIPATE, DISTARCH PHOSPHATE, TAPIOCA STARCH, DIETHYLAMINO HYDROXYBENZOYL HEXYL BENZOATE, GLYCERYL STEARATE CITRATE, PHENYLBENZIMIDAZOLE SULFONIC ACID, BEHENYL ALCOHOL, CETEARYL ALCOHOL, SODIUM HYALURONATE, GLYCYRRHETINIC ACID, GLYCYRRHIZA INFLATA ROOT EXTRACT, COPERNICIA CERIFERA CERA, CARRAGEENAN, XANTHAN GUM, HYDROXYPROPYL METHYLCELLULOSE, SILICA, TRISODIUM ETHYLENEDIAMINE DISUCCINATE, SODIUM HYDROXIDE, HYDROXYACETOPHENONE, ETHYLHEXYLGLYCERIN, BENZYL ALCOHOL',
    url: 'https://int.eucerin.com',
  },
  {
    name: 'Sun Protection LEB Protect Crème-Gel Visage Corps SPF50',
    brand: 'Eucerin',
    kind: 'skincare',
    unit: 'pump',
    slug: SOLAIRES_PRODUCT_SLUGS.EUCERIN_LEB_PROTECT_CREME_GEL_SPF50,
    totalAmount: 150,
    amountUnit: 'ml',
    priceCents: 1199,
    description:
      'Crème-gel SPF50 protection très haute UVA/UVB pour peaux sensibles. Texture légère non grasse.',
    notes:
      'Filtres chimiques + extrait réglisse + tocophérol. Idéal visage/corps, peaux intolérantes.',
    inci: 'AQUA, ALCOHOL DENAT., BUTYL METHOXYDIBENZOYLMETHANE, ISOPROPYL PALMITATE, BIS-ETHYLHEXYLOXYPHENOL METHOXYPHENYL TRIAZINE, C12-15 ALKYL BENZOATE, DIBUTYL ADIPATE, DISTARCH PHOSPHATE, DIETHYLAMINO HYDROXYBENZOYL HEXYL BENZOATE, ETHYLHEXYL TRIAZONE, BUTYLENE GLYCOL DICAPRYLATE/DICAPRATE, PHENYLBENZIMIDAZOLE SULFONIC ACID, DIETHYLHEXYL BUTAMIDO TRIAZONE, GLYCERYL STEARATE, HYDROXYPROPYL STARCH PHOSPHATE, GLYCYRRHIZA INFLATA ROOT EXTRACT, GLUCOSYLRUTIN, ISOQUERCITRIN, GLYCYRRHETINIC ACID, TOCOPHEROL, GLYCERIN, C18-38 ALKYL HYDROXYSTEAROYL STEARATE, COPERNICIA CERIFERA CERA, HYDROGENATED RAPESEED OIL, CETYL PALMITATE, MICROCRYSTALLINE CELLULOSE, XANTHAN GUM, CELLULOSE GUM, SODIUM STEAROYL GLUTAMATE, SILICA DIMETHYL SILYLATE, PHENOXYETHANOL, CAPRYLYL GLYCOL, HYDROXYACETOPHENONE, TRISODIUM EDTA, SODIUM HYDROXIDE, SODIUM CHLORIDE',
    url: 'https://int.eucerin.com',
  },
  {
    name: 'P20 Sensitive Face Crème Solaire IP50+ Nouvelle Formule',
    brand: 'Riemann P20',
    kind: 'skincare',
    unit: 'pump',
    slug: SOLAIRES_PRODUCT_SLUGS.RIEMANN_P20_SENSITIVE_FACE_SPF50,
    totalAmount: 50,
    amountUnit: 'g',
    priceCents: 2549,
    description:
      "Crème SPF50+ sensitive pour visage. Protection très haute, résistante à l'eau, sans parfum.",
    notes:
      'Filtres chimiques + panthénol + tréhalose. Texture crème légère, peaux sensibles/irritées.',
    inci: 'AQUA, DIETHYLAMINO HYDROXYBENZOYL HEXYL BENZOATE, DIBUTYL ADIPATE, BIS-ETHYLHEXYLOXYPHENOL METHOXYPHENYL TRIAZINE, DICAPRYLYL CARBONATE, TRIS-BIPHENYL TRIAZINE (NANO), GLYCERIN, PHENOXYETHYL CAPRYLATE, CAPRYLYL CAPRYLATE/CAPRATE, CANOLA OIL, SILICA, POTASSIUM CETYL PHOSPHATE, PANTHENOL, TREHALOSE, CETEARYL ALCOHOL, ETHYLHEXYL TRIAZONE, VP/EICOSENE COPOLYMER, PHENOXYETHANOL, SQUALANE, GLYCERYL STEARATE, SODIUM OLIVOYL GLUTAMATE, SORBITAN CAPRYLATE, TOCOPHERYL ACETATE, DECYL GLUCOSIDE, BENZOIC ACID, CAPRYLYL GLYCOL, PROPANEDIOL, ACACIA SENEGAL GUM, XANTHAN GUM, SODIUM PHYTATE, TOCOPHEROLS, DEHYDROACETIC ACID, ASCORBYL PALMITATE, ETHYLHEXYLGLYCERIN, BUTYLENE GLYCOL, DISODIUM PHOSPHATE, CITRIC ACID, BIOSACCHARIDE GUM-1, POTASSIUM SORBATE, SODIUM BENZOATE, GLYCERYL CAPRYLATE, SODIUM LEVULINATE, SODIUM ANISATE, SODIUM HYDROXIDE',
    url: 'https://www.p20.com',
  },
  {
    name: 'P20 Urban Shield Crème Solaire IP50+',
    brand: 'Riemann P20',
    kind: 'skincare',
    unit: 'pump',
    slug: SOLAIRES_PRODUCT_SLUGS.RIEMANN_P20_URBAN_SHIELD_SPF50,
    totalAmount: 50,
    amountUnit: 'g',
    priceCents: 2569,
    description:
      'Crème SPF50+ anti-pollution urbaine. Protection large spectre + antioxydants, texture légère.',
    notes:
      'Filtres chimiques + extraits végétaux (épinard, myrtille, pissenlit). Idéal ville/exposition quotidienne.',
    inci: 'AQUA/WATER/EAU, NEOPENTYL GLYCOL DIHEPTANOATE, ETHYLHEXYL METHOXYCINNAMATE, HOMOSALATE, ETHYLHEXYL SALICYLATE, DIETHYLAMINO HYDROXYBENZOYL HEXYL BENZOATE, GLYCERYL STEARATE CITRATE, BIS-ETHYLHEXYLOXYPHENOL METHOXYPHENYL TRIAZINE, ISOPENTYLDIOL, METHYL METHACRYLATE CROSSPOLYMER, SYNTHETIC FLUORPHLOGOPITE, TAPIOCA STARCH/TRITICUM VULGARE (WHEAT) STARCH, POTASSIUM CETYL PHOSPHATE, CETYL ALCOHOL, PROPANEDIOL, CAPRYLYL GLYCOL, SODIUM POLYACRYLATE, BENZYL ALCOHOL, PENTYLENE GLYCOL, POLYACRYLATE CROSSPOLYMER-11, SPINACIA OLERACEA LEAF EXTRACT, CARNOSINE, ARISTOTELIA CHILENSIS FRUIT EXTRACT, ETHYLHEXYLGLYCERIN, TARAXACUM OFFICINALE RHIZOME/ROOT EXTRACT, DISODIUM EDTA, CAPRYLHYDROXAMIC ACID, GLYCERIN, SODIUM HYDROXIDE, TEPHROSIA PURPUREA SEED EXTRACT, TIN OXIDE, BHT, SODIUM BENZOATE, POTASSIUM SORBATE, AMMONIUM C6-16 PERFLUOROALKYLETHYL PHOSPHATE, CI 77891/TITANIUM DIOXIDE, CI 77491/IRON OXIDES',
    url: 'https://www.p20.com',
  },
  {
    name: 'P20 Sensitive Skin Crème Solaire IP50+',
    brand: 'Riemann P20',
    kind: 'skincare',
    unit: 'pump',
    slug: SOLAIRES_PRODUCT_SLUGS.RIEMANN_P20_SENSITIVE_SKIN_SPF50,
    totalAmount: 200,
    amountUnit: 'ml',
    priceCents: 4145,
    description:
      'Crème SPF50+ sensitive corps/visage. Très haute protection, résistante eau, sans parfum.',
    notes:
      'Filtres chimiques + panthénol + squalane. Texture crème légère, peaux très sensibles/irritées.',
    inci: 'AQUA, DIETHYLAMINO HYDROXYBENZOYL HEXYL BENZOATE, DIBUTYL ADIPATE, DICAPRYLYL CARBONATE, ETHYLHEXYL TRIAZONE, BIS-ETHYLHEXYLOXYPHENOL METHOXYPHENYL TRIAZINE, GLYCERIN, PHENOXYETHYL CAPRYLATE, DICAPRYLYL ETHER, TRIS-BIPHENYL TRIAZINE (NANO), POTASSIUM CETYL PHOSPHATE, CETEARYL ALCOHOL, SILICA, VP/ACRYLATES/LAURYL METHACRYLATE COPOLYMER, PHENOXYETHANOL, DIETHYLHEXYL BUTAMIDO TRIAZONE, SORBITAN CAPRYLATE, GLYCERYL STEARATE, SODIUM OLIVOYL GLUTAMATE, CANOLA OIL, ACRYLATES/C12-22 ALKYL METHACRYLATE COPOLYMER, BENZOIC ACID, DECYL GLUCOSIDE, PROPANEDIOL, ACACIA SENEGAL GUM, XANTHAN GUM, CAPRYLYL GLYCOL, SODIUM PHYTATE, PENTYLENE GLYCOL, DEHYDROACETIC ACID, SODIUM HYDROXIDE, ETHYLHEXYLGLYCERIN, DISODIUM PHOSPHATE, BUTYLENE GLYCOL, SODIUM BENZOATE, POTASSIUM SORBATE, TOCOPHEROL, CITRIC ACID',
    url: 'https://www.p20.com',
  },
]
