export const ISISPHARMA_PRODUCT_SLUGS = {
  ISISPHARMA_RUBORIL_EXPERT_M: 'isispharma-ruboril-expert-m',
  ISISPHARMA_RUBORIL_EXPERT_S: 'isispharma-ruboril-expert-s',
}

export const ISISPHARMA_PRODUCT_DATA = [
  {
    name: 'Ruboril Expert S',
    brand: 'Isispharma',
    kind: 'skincare',
    unit: 'pump',
    slug: ISISPHARMA_PRODUCT_SLUGS.ISISPHARMA_RUBORIL_EXPERT_S,
    totalAmount: 40,
    amountUnit: 'ml',
    priceCents: 1650,
    description: 'Crème anti-rougeurs pour peaux sèches, renforce les capillaires.',
    notes: 'Texture riche et confortable.',
    inci: 'AQUA (WATER), GLYCERIN, CAPRYLIC/CAPRIC TRIGLYCERIDE, BETAINE, BUTYLENE GLYCOL, DIMETHICONE, PENTYLENE GLYCOL, DICAPRYLYL CARBONATE, BUTYROSPERMUM PARKII (SHEA) BUTTER, MYRISTYL MYRISTATE, GLYCYRRHETINIC ACID, CETYL ALCOHOL, SODIUM POLYACRYLATE, HYDROXYETHYL ACRYLATE/SODIUM ACRYLOYLDIMETHYL TAURATE COPOLYMER, TRICETEARETH-4 PHOSPHATE, GLYCOL STEARATE, PEG-2 STEARATE, ALUMINUM STARCH OCTENYLSUCCINATE, NIACINAMIDE, ACACIA DECURRENS/JOJOBA/SUNFLOWER SEED WAX POLYGLYCERYL-3 ESTERS, CARBOMER, PANTHENOL, CHLORPHENESIN, C12-16 ALCOHOLS, CAMELINA SATIVA SEED OIL, O-CYMEN-5-OL, ESCIN, SODIUM HYDROXIDE, PALMITIC ACID, HYDROGENATED LECITHIN, DISODIUM EDTA, RUSCUS ACULEATUS ROOT EXTRACT, POLYSORBATE 60, SORBITAN ISOSTEARATE, AMMONIUM GLYCYRRHIZATE, CENTELLA ASIATICA LEAF EXTRACT, HYDROLYZED YEAST PROTEIN, CALENDULA OFFICINALIS FLOWER EXTRACT, SODIUM CITRATE, TOCOPHEROL',
  },
  {
    name: 'Ruboril Expert M',
    brand: 'Isispharma',
    kind: 'skincare',
    unit: 'pump',
    slug: ISISPHARMA_PRODUCT_SLUGS.ISISPHARMA_RUBORIL_EXPERT_M,
    totalAmount: 40,
    amountUnit: 'ml',
    priceCents: 0,
    description:
      'Gel-crème anti-rougeurs pour peaux sensibles sujettes aux rougeurs diffuses et vaisseaux visibles.',
    notes:
      'Occlusion 5.5/10. Texture gel-crème légère. Complexe B-Calm breveté pour cibler les causes des rougeurs.',
    inci: 'AQUA (WATER), CAPRYLIC/CAPRIC TRIGLYCERIDE, BETAINE, BUTYLENE GLYCOL, PENTYLENE GLYCOL, ACACIA DECURRENS/JOJOBA/SUNFLOWER SEED WAX POLYGLYCERYL-3 ESTERS, HYDROXYETHYL ACRYLATE/SODIUM ACRYLOYLDIMETHYL TAURATE COPOLYMER, GLYCYRRHETINIC ACID, CETYL ALCOHOL, NIACINAMIDE, PANTHENOL, CHLORPHENESIN, C12-16 ALCOHOLS, CITRIC ACID, CAMELINA SATIVA SEED OIL, CARBOMER, O-CYMEN-5-OL, ESCIN, SODIUM HYDROXIDE, POLYSORBATE 60, SORBITAN ISOSTEARATE, GLYCERIN, PALMITIC ACID, HYDROGENATED LECITHIN, RUSCUS ACULEATUS ROOT EXTRACT, AMMONIUM GLYCYRRHIZATE, CENTELLA ASIATICA LEAF EXTRACT, HYDROLYZED YEAST PROTEIN, CALENDULA OFFICINALIS FLOWER EXTRACT, SODIUM CITRATE, TOCOPHEROL, ASCORBIC ACID',
    url: 'https://www.isispharma.com',
  },
]
