import { TAG_SLUGS } from '../../tags/seed-tags'
import { ISISPHARMA_PRODUCT_SLUGS } from './isispharma'

export const ISISPHARMA_PRODUCT_TAGS: { productSlug: string; tagSlug: string }[] = [
  // Ruboril Expert S – Crème anti-rougeurs riche pour peaux sèches/sensibles
  { productSlug: ISISPHARMA_PRODUCT_SLUGS.ISISPHARMA_RUBORIL, tagSlug: TAG_SLUGS.ANTI_ROUGEURS },
  { productSlug: ISISPHARMA_PRODUCT_SLUGS.ISISPHARMA_RUBORIL, tagSlug: TAG_SLUGS.ROSACEE },
  { productSlug: ISISPHARMA_PRODUCT_SLUGS.ISISPHARMA_RUBORIL, tagSlug: TAG_SLUGS.COUPEROSE },
  { productSlug: ISISPHARMA_PRODUCT_SLUGS.ISISPHARMA_RUBORIL, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },
  { productSlug: ISISPHARMA_PRODUCT_SLUGS.ISISPHARMA_RUBORIL, tagSlug: TAG_SLUGS.PEAU_SECHE },
  { productSlug: ISISPHARMA_PRODUCT_SLUGS.ISISPHARMA_RUBORIL, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },
  { productSlug: ISISPHARMA_PRODUCT_SLUGS.ISISPHARMA_RUBORIL, tagSlug: TAG_SLUGS.CREME_HYDRATANTE },
  { productSlug: ISISPHARMA_PRODUCT_SLUGS.ISISPHARMA_RUBORIL, tagSlug: TAG_SLUGS.SOIN_DE_JOUR },
  { productSlug: ISISPHARMA_PRODUCT_SLUGS.ISISPHARMA_RUBORIL, tagSlug: TAG_SLUGS.SOIN_DE_NUIT },
  { productSlug: ISISPHARMA_PRODUCT_SLUGS.ISISPHARMA_RUBORIL, tagSlug: TAG_SLUGS.REPARATEUR },
  { productSlug: ISISPHARMA_PRODUCT_SLUGS.ISISPHARMA_RUBORIL, tagSlug: TAG_SLUGS.HYPOALLERGENIQUE },

  // Ruboril Expert M – Gel-crème anti-rougeurs léger pour peaux mixtes/sensibles
  {
    productSlug: ISISPHARMA_PRODUCT_SLUGS.ISISPHARMA_RUBORIL_EXPERT_M,
    tagSlug: TAG_SLUGS.ANTI_ROUGEURS,
  },
  { productSlug: ISISPHARMA_PRODUCT_SLUGS.ISISPHARMA_RUBORIL_EXPERT_M, tagSlug: TAG_SLUGS.ROSACEE },
  {
    productSlug: ISISPHARMA_PRODUCT_SLUGS.ISISPHARMA_RUBORIL_EXPERT_M,
    tagSlug: TAG_SLUGS.COUPEROSE,
  },
  {
    productSlug: ISISPHARMA_PRODUCT_SLUGS.ISISPHARMA_RUBORIL_EXPERT_M,
    tagSlug: TAG_SLUGS.PEAU_SENSIBLE,
  },
  {
    productSlug: ISISPHARMA_PRODUCT_SLUGS.ISISPHARMA_RUBORIL_EXPERT_M,
    tagSlug: TAG_SLUGS.PEAU_MIXTE,
  },
  {
    productSlug: ISISPHARMA_PRODUCT_SLUGS.ISISPHARMA_RUBORIL_EXPERT_M,
    tagSlug: TAG_SLUGS.PEAU_NORMALE,
  },
  {
    productSlug: ISISPHARMA_PRODUCT_SLUGS.ISISPHARMA_RUBORIL_EXPERT_M,
    tagSlug: TAG_SLUGS.BARRIERE_CUTANEE,
  },
  {
    productSlug: ISISPHARMA_PRODUCT_SLUGS.ISISPHARMA_RUBORIL_EXPERT_M,
    tagSlug: TAG_SLUGS.CREME_HYDRATANTE,
  },
  {
    productSlug: ISISPHARMA_PRODUCT_SLUGS.ISISPHARMA_RUBORIL_EXPERT_M,
    tagSlug: TAG_SLUGS.SOIN_DE_JOUR,
  },
  {
    productSlug: ISISPHARMA_PRODUCT_SLUGS.ISISPHARMA_RUBORIL_EXPERT_M,
    tagSlug: TAG_SLUGS.SANS_PARFUM,
  },
  {
    productSlug: ISISPHARMA_PRODUCT_SLUGS.ISISPHARMA_RUBORIL_EXPERT_M,
    tagSlug: TAG_SLUGS.HYPOALLERGENIQUE,
  },
  {
    productSlug: ISISPHARMA_PRODUCT_SLUGS.ISISPHARMA_RUBORIL_EXPERT_M,
    tagSlug: TAG_SLUGS.REPARATEUR,
  },
]
