export const NOREVA_PRODUCT_SLUGS = {
  SENSIDIANE_HUILE_DEMAQUILLANTE: 'noreva-sensidiane-huile-demaquillante-apaisante',
  SENSIDIANE_AR_PLUS_SOIN_CONCENTRE: 'noreva-sensidiane-ar-plus-soin-concentre',
  ALPHA_KM_PLUS_SOIN_CORPS: 'noreva-alpha-km-plus-soin-raffermissant-corps',
  ALPHA_KM_PLUS_SERUM: 'noreva-alpha-km-plus-serum-repulpant-fermete',
  ALPHA_KM_PLUS_CREME_JOUR: 'noreva-alpha-km-plus-creme-de-jour-repulpante',
  ALPHA_KM_PLUS_CREME_NUIT: 'noreva-alpha-km-plus-creme-de-nuit-repulpante',
  EXFOLIAC_GLOBAL_X_PRO: 'noreva-exfoliac-global-x-pro-soin-intensif',
  EXFOLIAC_GEL_MOUSSANT: 'noreva-exfoliac-gel-moussant-doux',
  EXFOLIAC_CREME_REPARATRICE: 'noreva-exfoliac-creme-reparatrice',
  TRIO_WHITE_MELA_SERUM: 'noreva-trio-white-mela-serum-anti-taches',
  SENSIDIANE_SERUM_APAISANT: 'noreva-sensidiane-serum-apaisant',
  ACTIPUR_PEEL_SERUM: 'noreva-actipur-peel-serum-concentre',
  IKLEN_PURE_C_REVERSE_SERUM: 'noreva-iklen-pure-c-reverse-serum-booster',
  AQUAREVA_SERUM_24H: 'noreva-aquareva-serum-hydratant-24h',
  NOVEANE_PREMIUM_SERUM: 'noreva-noveane-premium-serum-multi-corrections',
  SEBODIANE_DS_SERUM_LP: 'noreva-sebodiane-ds-serum-lp-seboregulateur',
  PSORIANE_CREME_VISAGE: 'noreva-psoriane-creme-apaisante-visage',
  SENSIDIANE_CREME_LEGERE: 'noreva-sensidiane-creme-legere-apaisante',
  SENSIDIANE_CREME_RICHE: 'noreva-sensidiane-creme-riche-apaisante',
  ACTIPUR_EXPERT_SENSI_PLUS: 'noreva-actipur-expert-sensi-plus-soin',
  SENSIDIANE_AR_PLUS_SOIN_ANTI_ROUGEURS: 'noreva-sensidiane-ar-plus-soin-anti-rougeurs',
  AQUAREVA_LAIT_CORPOREL: 'noreva-aquareva-lait-corporel-hydratant',
  TRIO_WHITE_XP_LAIT_CORPS: 'noreva-trio-white-xp-lait-corporel-anti-taches',
  PSORIANE_LAIT_CORPS: 'noreva-psoriane-lait-apaisant-corps',
  STRIVADIANE_ANTI_VERGETURES: 'noreva-strivadiane-concentre-anti-vergetures',
  ECZEANE_BRUME_RELIPIDANTE: 'noreva-eczeane-brume-relipidante-48h',
  XERODIANE_CERA_PLUS_BAUME: 'noreva-xerodiane-cera-plus-baume-nutritif',
  TRIO_WHITE_MELA_SOIN_NUIT: 'noreva-trio-white-mela-soin-de-nuit',
} as const

export const PRODUCT_DATA = [
  {
    name: 'Sensidiane® Huile Démaquillante Apaisante',
    brand: 'Noreva',
    kind: 'skincare',
    unit: 'bottle',
    slug: NOREVA_PRODUCT_SLUGS.SENSIDIANE_HUILE_DEMAQUILLANTE,
    totalAmount: 150,
    amountUnit: 'ml',
    priceCents: 1450,
    description:
      'Solution démaquillante douce pour peaux sensibles retirant le maquillage waterproof.',
    notes:
      'Non parfumée. Contient le complexe Neutrazen™ et 4 huiles végétales (onagre, tsubaki, coton, bourrache).',
    inci: 'AQUA (WATER) • PEG-7 GLYCERYL COCOATE • GLYCERIN • COCO-GLUCOSIDE • SODIUM COCOAMPHOACETATE • PEG-40 HYDROGENATED CASTOR OIL • PEG-90 GLYCERYL ISOSTEARATE • BORAGO OFFICINALIS SEED OIL • GOSSYPIUM HERBACEUM (COTTON) SEED OIL • OENOTHERA BIENNIS (EVENING PRIMROSE) OIL • CAMELLIA JAPONICA SEED OIL • TOCOPHEROL • PALMITOYL TRIPEPTIDE-8 • GLYCERYL OLEATE • CITRIC ACID • SODIUM BENZOATE • POTASSIUM SORBATE • LAURETH-2 • SODIUM CHLORIDE • BUTYLENE GLYCOL • CARAMEL • HYDROGENATED PALM GLYCERIDES CITRATE • DEXTRAN',
    url: '',
  },
  {
    name: 'Sensidiane® AR+ Soin Concentré',
    brand: 'Noreva',
    kind: 'skincare',
    unit: 'tube',
    slug: NOREVA_PRODUCT_SLUGS.SENSIDIANE_AR_PLUS_SOIN_CONCENTRE,
    totalAmount: 30,
    amountUnit: 'ml',
    priceCents: 2150,
    description: 'Soin intensif anti-rougeurs pour peaux à tendance couperosique.',
    notes:
      'Contient 4% Niacinamide, Azéloglycine et Acide Hyaluronique 450 kDa. Texture onctueuse, pigments verts.',
    inci: 'AQUA (WATER) • NIACINAMIDE • OCTYLDODECANOL • COCONUT ALKANES • GLYCERIN • CETEARYL ALCOHOL • CAPRYLIC/CAPRIC TRIGLYCERIDE • C20-22 ALKYL PHOSPHATE • DIMETHICONE • POTASSIUM AZELOYL DIGLYCINATE • C20-22 ALCOHOLS • PENTYLENE GLYCOL • ALLANTOIN • HYDROLYZED HYALURONIC ACID • ASPARAGOPSIS ARMATA EXTRACT • ASCOPHYLLUM NODOSUM EXTRACT • DEXTRAN • PALMITOYL TRIPEPTIDE 8 • GLYCERYL HYDROXYSTEARATE • HYDROXYETHYL ACRYLATE/SODIUM ACRYLOYLDIMETHYL TAURATE COPOLYMER • METHYLPROPANEDIOL • TALC • BUTYLENE GLYCOL • COCO-CAPRYLATE/CAPRATE • ETHYLHEXYLGLYCERIN • CHLORPHENESIN • POLYISOBUTENE • CAPRYLHYDROXAMIC ACID • SODIUM HYDROXIDE • HYDROGENATED STARCH HYDROLYSATE • DISODIUM EDTA • PEG-7 TRIMETHYLOLPROPANE COCONUT ETHER • CI 77288 (CHROMIUM OXIDE GREENS) • SORBITAN ISOSTEARATE • PHENOXYETHANOL • POTASSIUM SORBATE',
    url: '',
  },
  {
    name: 'Alpha KM®+ Soin Raffermissant Corps',
    brand: 'Noreva',
    kind: 'skincare',
    unit: 'bottle',
    slug: NOREVA_PRODUCT_SLUGS.ALPHA_KM_PLUS_SOIN_CORPS,
    totalAmount: 200,
    amountUnit: 'ml',
    priceCents: 2390,
    description: 'Soin corps anti-rides correcteur pour peaux sèches et déshydratées.',
    notes: "Contient 10% Lactate d'Ammonium, AHA et Biocéramides. Vegan.",
    inci: 'AQUA (WATER) • AMMONIUM LACTATE • C12-15 ALKYL BENZOATE • ISONONYL ISONONANOATE • ISOPROPYL PALMITATE • PEG-100 STEARATE • GLYCERYL STEARATE • MALIC ACID • PRUNUS AMYGDALUS DULCIS (SWEET ALMOND) OIL • CERAMIDE NP • GLYCOLIC ACID • OLEIC ACID • ARACHIDYL ALCOHOL • CETYL ALCOHOL • CETYL LACTATE • DIMETHICONE • LACTIC ACID • PARFUM (FRAGRANCE) • Xanthan Gum • SODIUM BENZOATE • BEHENYL ALCOHOL • CHLORPHENESIN • TOCOPHERYL ACETATE • CYCLOPENTASILOXANE • ARACHIDYL GLUCOSIDE • PVP • LIMONENE • HEXYL CINNAMAL • LINALOOL • CITRONELLOL • GERANIOL',
    url: '',
  },
  {
    name: 'Alpha KM®+ Sérum Repulpant Fermeté',
    brand: 'Noreva',
    kind: 'skincare',
    unit: 'dropper',
    slug: NOREVA_PRODUCT_SLUGS.ALPHA_KM_PLUS_SERUM,
    totalAmount: 30,
    amountUnit: 'ml',
    priceCents: 3540,
    description: 'Concentré anti-âge pour lisser les rides et renforcer la barrière cutanée.',
    notes: 'Contient Matrixyl®, Acide Polyglutamique et Biocéramides.',
    inci: 'AQUA (WATER) • PROPANEDIOL • GLYCERIN • AMMONIUM LACTATE • BUTYLENE GLYCOL • AMMONIUM ACRYLOYLDIMETHYLTAURATE/VP COPOLYMER • CELLULOSE • IRIS FLORENTINA ROOT EXTRACT • CERAMIDE NP • SODIUM LACTATE • CERAMIDE AP • PHYTOSPHINGOSINE • PALMITOYL PENTAPEPTIDE-4 • CERAMIDE EOP • SODIUM POLYACRYLATE • ETHYLHEXYLGLYCERIN • PARFUM (FRAGRANCE) • CHLORPHENESIN • POLYGLYCERYL-10 STEARATE • TRIETHYL CITRATE • SODIUM POLYGLUTAMATE • DISODIUM EDTA • POLYGLYCERYL-6 BEHENATE • CARBOMER • CITRUS LIMON PEEL OIL • CHOLESTEROL • BEHENIC ACID • CETEARYL ALCOHOL • GLYCERYL STEARATE • SODIUM LEVULINATE • LIMONENE • HEXYL CINNAMAL • POLYSORBATE 20 • LINALYL ACETATE • LINALOOL • PINENE • TETRAMETHYL ACETYLOCTAHYDRONAPHTHALENES • POTASSIUM SORBATE • HEXAMETHYLINDANOPYRAN • CITRIC ACID • CITRONELLOL • SODIUM CETEARYL SULFATE • TRIMETHYLBENZENEPROPANOL • GERANIOL • TOCOPHEROL',
    url: '',
  },
  {
    name: 'Exfoliac® Global X-PRO',
    brand: 'Noreva',
    kind: 'skincare',
    unit: 'tube',
    slug: NOREVA_PRODUCT_SLUGS.EXFOLIAC_GLOBAL_X_PRO,
    totalAmount: 30,
    amountUnit: 'ml',
    priceCents: 1490,
    description: 'Soin global intensif pour acné modérée à sévère.',
    notes: '8 actions en 1. Contient Acnésyl X-Pro, X-Régénol, 4% Vitamine PP et Azéloglycine.',
    inci: 'AQUA (WATER) • GLYCERIN • NIACINAMIDE • CAPRYLIC/CAPRIC TRIGLYCERIDE • ORYZA SATIVA (RICE) POWDER • OENOTHERA BIENNIS (EVENING PRIMROSE) OIL • PROPANEDIOL • IMPERATA CYLINDRICA ROOT EXTRACT • SODIUM POLYACRYLATE • TOCOPHERYL ACETATE • POTASSIUM AZELOYL DIGLYCINATE • PUNICA GRANATUM PERICARP EXTRACT • HELIANTHUS ANNUUS (SUNFLOWER) SEED OIL • SACCHARIDE ISOMERATE • GLYCOLIC ACID • PARFUM (FRAGRANCE) • CARBOMER • MALTODEXTRIN • CAPRYLYL GLYCOL • 1,2-HEXANEDIOL • ETHYLHEXYLGLYCERIN • SODIUM HYDROXIDE • LACTIC ACID • SODIUM MAGNESIUM SILICATE • CITRIC ACID • TOCOPHEROL • PAPAIN • SODIUM CITRATE • XANTHAN GUM • ACRYLATES/C10-30 ALKYL ACRYLATE CROSSPOLYMER • ALGIN • BIOTIN • HEXAMETHYLINDANOPYRAN',
    url: '',
  },
  {
    name: 'Trio White® MELA Sérum Anti-taches',
    brand: 'Noreva',
    kind: 'skincare',
    unit: 'dropper',
    slug: NOREVA_PRODUCT_SLUGS.TRIO_WHITE_MELA_SERUM,
    totalAmount: 30,
    amountUnit: 'ml',
    priceCents: 4720,
    description: 'Sérum dépigmentant agissant sur le microbiote.',
    notes: 'Résultats dès 10 jours. Contient Pigmentbright®, Algue rouge et Vitamine C stabilisée.',
    inci: 'AQUA (WATER) • GLYCERIN • PROPANEDIOL • ASCORBYL GLUCOSIDE • GLYCERYL STEARATE CITRATE • CAPRYLIC/CAPRIC TRIGLYCERIDE • HEXYLRESORCINOL • ASTRAGALUS MEMBRANACEUS ROOT EXTRACT • ATRACTYLODES MACROCEPHALA ROOT EXTRACT • BUPLEURUM FALCATUM ROOT EXTRACT • GOSSYPIUM HERBACEUM (COTTON) SEED EXTRACT • PUNICA GRANATUM SEED EXTRACT • PALMARIA PALMATA EXTRACT • HYDROLYZED OPUNTIA FICUS-INDICA FLOWER EXTRACT • TREHALOSE • SCHISANDRA SPHENANTHERA FRUIT EXTRACT • CYSTOSEIRA TAMARISCIFOLIA EXTRACT • HELIANTHUS ANNUUS (SUNFLOWER) SEED OIL • FRUCTOOLIGOSACCHARIDES • FERULIC ACID • ACETYL TETRAPEPTIDE-2 • POLYACRYLATE CROSSPOLYMER-6 • 1,2-HEXANEDIOL • CAPRYLYL GLYCOL • PARFUM (FRAGRANCE) • ETHYLHEXYLGLYCERIN • HYDROXYETHYL ACRYLATE/SODIUM ACRYLOYLDIMETHYL TAURATE COPOLYMER • MALTODEXTRIN • SODIUM HYDROXIDE • PENTYLENE GLYCOL • POLYSORBATE 60 • SORBITAN ISOSTEARATE • TOCOPHEROL • PHYTIC ACID',
    url: '',
  },
  {
    name: 'Iklen®+ [Pure-C-Reverse] Sérum',
    brand: 'Noreva',
    kind: 'skincare',
    unit: 'dropper',
    slug: NOREVA_PRODUCT_SLUGS.IKLEN_PURE_C_REVERSE_SERUM,
    totalAmount: 24, // 3x8ml
    amountUnit: 'ml',
    priceCents: 1650,
    description: "Sérum anti-âge 4 en 1 booster d'éclat.",
    notes:
      'Contient 10% Vitamine C pure, 3% Niacinamide, Acide Hyaluronique BPM et 4-Butylrésorcinol.',
    inci: 'AQUA (WATER) • ASCORBIC ACID • NIACINAMIDE • GLYCERIN • ISOPROPYL PALMITATE • ALCOHOL DENAT. • PROPANEDIOL • ARACHIDYL ALCOHOL • IMPERATA CYLINDRICA ROOT EXTRACT • OENOTHERA BIENNIS (EVENING PRIMROSE) OIL • 4-BUTYLRESORCINOL • SODIUM HYALURONATE • HELIANTHUS ANNUUS (SUNFLOWER) SEED OIL • BEHENYL ALCOHOL • 1,2-HEXANEDIOL • ARACHIDYL GLUCOSIDE • ACACIA SENEGAL GUM • CAPRYLYL GLYCOL • ETHYLHEXYLGLYCERIN • XANTHAN GUM • SODIUM POLYACRYLATE • INULIN LAURYL CARBAMATE • SODIUM PHYTATE • TOCOPHEROL • CARBOMER • CITRIC ACID • SODIUM CITRATE • ACRYLATES/C10-30 ALKYL ACRYLATE CROSSPOLYMER • BIOTIN',
    url: '',
  },
  {
    name: 'Strivadiane® Concentré Anti-vergetures',
    brand: 'Noreva',
    kind: 'skincare',
    unit: 'tube',
    slug: NOREVA_PRODUCT_SLUGS.STRIVADIANE_ANTI_VERGETURES,
    totalAmount: 125,
    amountUnit: 'ml',
    priceCents: 1890,
    description: 'Soin prévenant et réduisant les vergetures, adapté à la grossesse.',
    notes: '97% ingrédients naturels. Complexes Cicagen-C et Elastigène-3D.',
    inci: 'AQUA (WATER) • CAPRYLIC/CAPRIC TRIGLYCERIDE • GLYCERIN • SODIUM ACRYLATES COPOLYMER • 3-O-ETHYL ASCORBIC ACID • GLYCERYL CAPRYLATE • CARBOMER • PARFUM (FRAGRANCE) • LECITHIN • SODIUM HYDROXIDE • CHLORPHENESIN • SODIUM CITRATE • HYDROLYZED HYALURONIC ACID • CITRIC ACID • BUTYLENE GLYCOL • PEUCEDANUM GRAVEOLENS (DILL) EXTRACT • PENTYLENE GLYCOL • XANTHAN GUM',
    url: '',
  },
  {
    name: 'Xerodiane® CERA+ Baume Nutritif',
    brand: 'Noreva',
    kind: 'skincare',
    unit: 'bottle',
    slug: NOREVA_PRODUCT_SLUGS.XERODIANE_CERA_PLUS_BAUME,
    totalAmount: 400,
    amountUnit: 'ml',
    priceCents: 1690,
    description: 'Baume relipidant 72h pour peaux sèches à très sèches.',
    notes:
      'Contient Complexe CERA+, Aquabiome (prébiotique), Acide Hyaluronique 450 kDa et Huile Inca Inchi.',
    inci: 'AQUA (WATER) • PARAFFINUM LIQUIDUM (MINERAL OIL) • GLYCERIN • PENTAERYTHRITYL DISTEARATE • PROPANEDIOL • GLYCERYL STEARATE • PEG-100 STEARATE • NIACINAMIDE • INULIN • BUTYROSPERMUM PARKII (SHEA) BUTTER • OLEIC/LINOLEIC/LINOLENIC POLYGLYCERIDES • PLUKENETIA VOLUBILIS SEED OIL • TOCOPHEROL • HELIANTHUS ANNUUS (SUNFLOWER) SEED OIL • PCA • CERAMIDE NP • HYDROLYZED HYALURONIC ACID • CERAMIDE AP • PHYTOSPHINGOSINE • CHOLESTEROL • CERAMIDE EOP • CERA MICROCRISTALLINA • GLYCERYL CAPRYLATE • PARAFFIN • CHLORPHENESIN • ACRYLATES/C10-30 ALKYL ACRYLATE CROSSPOLYMER • SODIUM HYDROXIDE • POLYGLYCERYL-10 STEARATE • TRIETHYL CITRATE • POLYGLYCERYL-6 BEHENATE • BEHENIC ACID • CETEARYL ALCOHOL • SODIUM LEVULINATE • POTASSIUM SORBATE • CITRIC ACID • SODIUM CETEARYL SULFATE',
    url: '',
  },
]
