import { TAG_SLUGS } from '../../tags/seed-tags'
import { NOREVA_PRODUCT_SLUGS } from './noreva'

interface ProductTagGroups {
  primary: string[] // Tags principaux (Bénéfices correctifs)
  secondary: string[] // Tags secondaires (Routine, Format, Texture)
  avoid: string[] // Tags à éviter/exclure
}
export const PRODUCT_TAGS: Record<string, ProductTagGroups> = {
  [NOREVA_PRODUCT_SLUGS.SENSIDIANE_HUILE_DEMAQUILLANTE]: {
    primary: [TAG_SLUGS.PEAU_SENSIBLE, TAG_SLUGS.PEAU_REACTIVE],
    secondary: [
      TAG_SLUGS.HUILE_DEMAQUILLANTE,
      TAG_SLUGS.DOUBLE_NETTOYAGE_1,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.APAISANT,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.PEAU_NORMALE,
      TAG_SLUGS.PEAU_TOUS_TYPES,
    ],
    avoid: [],
  },

  [NOREVA_PRODUCT_SLUGS.SENSIDIANE_AR_PLUS_SOIN_CONCENTRE]: {
    primary: [TAG_SLUGS.ANTI_ROUGEURS, TAG_SLUGS.ROSACEE],
    secondary: [
      TAG_SLUGS.SERUM,
      TAG_SLUGS.COUPEROSE,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.APAISANT,
      TAG_SLUGS.NON_COMEDOGENE,
      TAG_SLUGS.HYDRATATION,
    ],
    avoid: [],
  },

  [NOREVA_PRODUCT_SLUGS.ALPHA_KM_PLUS_SERUM]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.ECLAT],
    secondary: [
      TAG_SLUGS.SERUM,
      TAG_SLUGS.TRAITEMENT,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.REPULPANT,
      TAG_SLUGS.GRAIN_PEAU,
      TAG_SLUGS.TEXTURE_LEGERE,
      TAG_SLUGS.PEAU_SENSIBLE,
    ],
    avoid: [],
  },

  [NOREVA_PRODUCT_SLUGS.EXFOLIAC_GLOBAL_X_PRO]: {
    primary: [TAG_SLUGS.ANTI_ACNE, TAG_SLUGS.POST_ACNE],
    secondary: [
      TAG_SLUGS.GEL_CREME,
      TAG_SLUGS.MATIFIANT,
      TAG_SLUGS.SEBO_REGULATEUR,
      TAG_SLUGS.EXFOLIANT_CHIMIQUE,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.GRAIN_PEAU,
    ],
    avoid: [TAG_SLUGS.PEAU_ATOPIQUE],
  },

  [NOREVA_PRODUCT_SLUGS.TRIO_WHITE_MELA_SERUM]: {
    primary: [TAG_SLUGS.ANTI_TACHES, TAG_SLUGS.HYPERPIGMENTATION],
    secondary: [
      TAG_SLUGS.SERUM,
      TAG_SLUGS.ECLAT,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.GROSSESSE_COMPATIBLE,
      TAG_SLUGS.PHOTO_VIEILLISSEMENT,
    ],
    avoid: [],
  },

  [NOREVA_PRODUCT_SLUGS.ECZEANE_BRUME_RELIPIDANTE]: {
    primary: [TAG_SLUGS.ECZEMA, TAG_SLUGS.PEAU_ATOPIQUE],
    secondary: [
      TAG_SLUGS.BRUME,
      TAG_SLUGS.REPARATEUR,
      TAG_SLUGS.EMOLLIENT,
      TAG_SLUGS.APAISANT,
      TAG_SLUGS.BARRIERE_CUTANEE,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.PEAU_SECHE,
    ],
    avoid: [],
  },

  [NOREVA_PRODUCT_SLUGS.XERODIANE_CERA_PLUS_BAUME]: {
    primary: [TAG_SLUGS.PEAU_SECHE, TAG_SLUGS.BARRIERE_CUTANEE],
    secondary: [
      TAG_SLUGS.BAUME,
      TAG_SLUGS.HYDRATATION,
      TAG_SLUGS.REPARATEUR,
      TAG_SLUGS.MICROBIOME,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.GROSSESSE_COMPATIBLE,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
    ],
    avoid: [],
  },

  [NOREVA_PRODUCT_SLUGS.SENSIDIANE_SERUM_APAISANT]: {
    primary: [TAG_SLUGS.PEAU_SENSIBLE, TAG_SLUGS.BARRIERE_CUTANEE],
    secondary: [
      TAG_SLUGS.SERUM,
      TAG_SLUGS.HYDRATATION,
      TAG_SLUGS.REPARATEUR,
      TAG_SLUGS.APAISANT,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.TEXTURE_LEGERE,
    ],
    avoid: [],
  },

  [NOREVA_PRODUCT_SLUGS.ACTIPUR_PEEL_SERUM]: {
    primary: [TAG_SLUGS.ANTI_ACNE, TAG_SLUGS.ANTI_AGE],
    secondary: [
      TAG_SLUGS.SERUM,
      TAG_SLUGS.EXFOLIANT_CHIMIQUE,
      TAG_SLUGS.MATIFIANT,
      TAG_SLUGS.SEBO_REGULATEUR,
      TAG_SLUGS.PORES_DILATES,
      TAG_SLUGS.ECLAT,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
    ],
    avoid: [],
  },

  [NOREVA_PRODUCT_SLUGS.SENSIDIANE_CREME_RICHE]: {
    primary: [TAG_SLUGS.PEAU_SENSIBLE, TAG_SLUGS.PEAU_SECHE],
    secondary: [
      TAG_SLUGS.CREME_HYDRATANTE,
      TAG_SLUGS.TEXTURE_RICHE,
      TAG_SLUGS.EMOLLIENT,
      TAG_SLUGS.APAISANT,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
    ],
    avoid: [TAG_SLUGS.PEAU_GRASSE, TAG_SLUGS.TEXTURE_LEGERE],
  },

  [NOREVA_PRODUCT_SLUGS.STRIVADIANE_ANTI_VERGETURES]: {
    primary: [TAG_SLUGS.CICATRISATION],
    secondary: [
      TAG_SLUGS.LAIT_CORPS,
      TAG_SLUGS.GROSSESSE_COMPATIBLE,
      TAG_SLUGS.REPARATEUR,
      TAG_SLUGS.HYDRATATION,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
    ],
    avoid: [],
  },
}
