import { TAG_SLUGS } from '../../tags/seed-tags'
import { LAB_BIARRITZ_PRODUCT_SLUGS } from './labBiarritz'

interface ProductTagGroups {
  primary: string[]
  secondary: string[]
  avoid: string[]
}

export const LAB_BIARRITZ_PRODUCT_TAGS: Record<string, ProductTagGroups> = {
  // ── SOLAIRES (Protection Minérale) ────────────────────────────────
  [LAB_BIARRITZ_PRODUCT_SLUGS.LABORATOIRES_BIARRITZ_CREME_SOLAIRE_TEINTEE_SPF50]: {
    primary: [TAG_SLUGS.PROTECTION_SOLAIRE, TAG_SLUGS.FILTRES_MINERAUX, TAG_SLUGS.ECLAT],
    secondary: [
      TAG_SLUGS.ZONE_VISAGE,
      TAG_SLUGS.BIO_NATUREL,
      TAG_SLUGS.ANTI_OXYDANT,
      TAG_SLUGS.PHOTO_VIEILLISSEMENT,
      TAG_SLUGS.NON_COMEDOGENE,
      TAG_SLUGS.MATIN,
    ],
    avoid: [],
  },

  [LAB_BIARRITZ_PRODUCT_SLUGS.LABORATOIRES_BIARRITZ_CREME_SOLAIRE_VISAGE_SPF50]: {
    primary: [TAG_SLUGS.PROTECTION_SOLAIRE, TAG_SLUGS.FILTRES_MINERAUX, TAG_SLUGS.SANS_PARFUM],
    secondary: [
      TAG_SLUGS.ZONE_VISAGE,
      TAG_SLUGS.BIO_NATUREL,
      TAG_SLUGS.VEGAN,
      TAG_SLUGS.ANTI_OXYDANT,
      TAG_SLUGS.HYPOALLERGENIQUE,
    ],
    avoid: [],
  },

  // ── RÉPARATION & HYDRATATION ──────────────────────────────────────
  [LAB_BIARRITZ_PRODUCT_SLUGS.LABORATOIRES_BIARRITZ_CICA_REPA_CREME_REPARATRICE]: {
    primary: [TAG_SLUGS.REPARATEUR, TAG_SLUGS.BARRIERE_CUTANEE, TAG_SLUGS.CICATRISATION],
    secondary: [
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.BIO_NATUREL,
      TAG_SLUGS.HYPOALLERGENIQUE,
      TAG_SLUGS.ZONE_VISAGE,
      TAG_SLUGS.ZONE_CORPS,
    ],
    avoid: [],
  },

  [LAB_BIARRITZ_PRODUCT_SLUGS.LABORATOIRES_BIARRITZ_CREME_VISAGE]: {
    primary: [TAG_SLUGS.HYDRATATION, TAG_SLUGS.ANTI_OXYDANT, TAG_SLUGS.PHOTO_VIEILLISSEMENT],
    secondary: [
      TAG_SLUGS.PEAU_NORMALE,
      TAG_SLUGS.BIO_NATUREL,
      TAG_SLUGS.ECLAT,
      TAG_SLUGS.ZONE_VISAGE,
      TAG_SLUGS.MATIN,
    ],
    avoid: [],
  },

  [LAB_BIARRITZ_PRODUCT_SLUGS.LABORATOIRES_BIARRITZ_CREME_NUIT_REGENERANTE]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.BARRIERE_CUTANEE, TAG_SLUGS.MICROBIOME],
    secondary: [
      TAG_SLUGS.BIO_NATUREL,
      TAG_SLUGS.EMOLLIENCE,
      TAG_SLUGS.REPULPANT,
      TAG_SLUGS.ZONE_VISAGE,
    ],
    avoid: [],
  },

  // ── SOINS CIBLÉS (Anti-taches & Repulpant) ────────────────────────
  [LAB_BIARRITZ_PRODUCT_SLUGS.LABORATOIRES_BIARRITZ_SERUM_ANTI_TACHES]: {
    primary: [TAG_SLUGS.ANTI_TACHES, TAG_SLUGS.HYPERPIGMENTATION, TAG_SLUGS.ECLAT],
    secondary: [
      TAG_SLUGS.SERUM,
      TAG_SLUGS.BIO_NATUREL,
      TAG_SLUGS.PREBIOTIQUE,
      TAG_SLUGS.MICROBIOME,
      TAG_SLUGS.ZONE_VISAGE,
      TAG_SLUGS.CERNES_POCHES, // Indiqué pour cernes hyperpigmentés
    ],
    avoid: [],
  },

  [LAB_BIARRITZ_PRODUCT_SLUGS.LABORATOIRES_BIARRITZ_CREME_NUIT_ANTI_TACHES]: {
    primary: [TAG_SLUGS.ANTI_TACHES, TAG_SLUGS.HYPERPIGMENTATION, TAG_SLUGS.CREME_DE_NUIT],
    secondary: [
      TAG_SLUGS.BIO_NATUREL,
      TAG_SLUGS.ECLAT,
      TAG_SLUGS.EMOLLIENCE,
      TAG_SLUGS.ZONE_VISAGE,
    ],
    avoid: [],
  },

  [LAB_BIARRITZ_PRODUCT_SLUGS.LABORATOIRES_BIARRITZ_SERUM_REPULPANT]: {
    primary: [TAG_SLUGS.REPULPANT, TAG_SLUGS.DESHYDRATATION, TAG_SLUGS.ANTI_AGE],
    secondary: [
      TAG_SLUGS.SERUM,
      TAG_SLUGS.BIO_NATUREL,
      TAG_SLUGS.HYDRATATION,
      TAG_SLUGS.ZONE_VISAGE,
      TAG_SLUGS.ECLAT,
    ],
    avoid: [],
  },

  [LAB_BIARRITZ_PRODUCT_SLUGS.LABORATOIRES_BIARRITZ_CREME_SOLAIRE_TEINTEE_SPF50_DOREE]: {
    primary: [TAG_SLUGS.PROTECTION_SOLAIRE, TAG_SLUGS.FILTRES_MINERAUX, TAG_SLUGS.ECLAT],
    secondary: [
      TAG_SLUGS.ZONE_VISAGE,
      TAG_SLUGS.BIO_NATUREL,
      TAG_SLUGS.ANTI_OXYDANT,
      TAG_SLUGS.PHOTO_VIEILLISSEMENT,
      TAG_SLUGS.NON_COMEDOGENE,
      TAG_SLUGS.MATIN,
    ],
    avoid: [],
  },

  [LAB_BIARRITZ_PRODUCT_SLUGS.LABORATOIRES_BIARRITZ_LAIT_SOLAIRE_SPF50]: {
    primary: [TAG_SLUGS.PROTECTION_SOLAIRE, TAG_SLUGS.FILTRES_MINERAUX, TAG_SLUGS.PEAU_SENSIBLE],
    secondary: [
      TAG_SLUGS.ZONE_VISAGE,
      TAG_SLUGS.ZONE_CORPS,
      TAG_SLUGS.BIO_NATUREL,
      TAG_SLUGS.EMOLLIENCE,
    ],
    avoid: [],
  },
}
