import { TAG_SLUGS } from '../../tags/seed-tags'
import { LAB_BIARRITZ_PRODUCT_SLUGS } from './labBiarritz'

export const LAB_BIARRITZ_PRODUCT_TAGS: { productSlug: string; tagSlug: string }[] = [
  // Crème solaire visage SPF50
  {
    productSlug: LAB_BIARRITZ_PRODUCT_SLUGS.LABORATOIRES_BIARRITZ_CREME_SOLAIRE_VISAGE_SPF50,
    tagSlug: TAG_SLUGS.SOLAIRE_VISAGE,
  },
  {
    productSlug: LAB_BIARRITZ_PRODUCT_SLUGS.LABORATOIRES_BIARRITZ_CREME_SOLAIRE_VISAGE_SPF50,
    tagSlug: TAG_SLUGS.FILTRES_MINERAUX,
  },
  {
    productSlug: LAB_BIARRITZ_PRODUCT_SLUGS.LABORATOIRES_BIARRITZ_CREME_SOLAIRE_VISAGE_SPF50,
    tagSlug: TAG_SLUGS.SANS_PARFUM,
  },
  {
    productSlug: LAB_BIARRITZ_PRODUCT_SLUGS.LABORATOIRES_BIARRITZ_CREME_SOLAIRE_VISAGE_SPF50,
    tagSlug: TAG_SLUGS.PEAU_SENSIBLE,
  },

  // Crème solaire teintée SPF50 (Dorée et Classique)
  {
    productSlug: LAB_BIARRITZ_PRODUCT_SLUGS.LABORATOIRES_BIARRITZ_CREME_SOLAIRE_TEINTEE_SPF50_DOREE,
    tagSlug: TAG_SLUGS.SOLAIRE_VISAGE,
  },
  {
    productSlug: LAB_BIARRITZ_PRODUCT_SLUGS.LABORATOIRES_BIARRITZ_CREME_SOLAIRE_TEINTEE_SPF50_DOREE,
    tagSlug: TAG_SLUGS.SOLAIRE_TEINTE,
  },
  {
    productSlug: LAB_BIARRITZ_PRODUCT_SLUGS.LABORATOIRES_BIARRITZ_CREME_SOLAIRE_TEINTEE_SPF50_DOREE,
    tagSlug: TAG_SLUGS.PROTECTION_LUMIERE_BLEUE,
  },
  {
    productSlug: LAB_BIARRITZ_PRODUCT_SLUGS.LABORATOIRES_BIARRITZ_CREME_SOLAIRE_TEINTEE_SPF50_DOREE,
    tagSlug: TAG_SLUGS.NON_COMEDOGENE,
  },

  // Lait solaire SPF50 (Corps et Visage)
  {
    productSlug: LAB_BIARRITZ_PRODUCT_SLUGS.LABORATOIRES_BIARRITZ_LAIT_SOLAIRE_SPF50,
    tagSlug: TAG_SLUGS.SOLAIRE_CORPS,
  },
  {
    productSlug: LAB_BIARRITZ_PRODUCT_SLUGS.LABORATOIRES_BIARRITZ_LAIT_SOLAIRE_SPF50,
    tagSlug: TAG_SLUGS.FILTRES_MINERAUX,
  },
  {
    productSlug: LAB_BIARRITZ_PRODUCT_SLUGS.LABORATOIRES_BIARRITZ_LAIT_SOLAIRE_SPF50,
    tagSlug: TAG_SLUGS.SANS_PARFUM,
  },
  {
    productSlug: LAB_BIARRITZ_PRODUCT_SLUGS.LABORATOIRES_BIARRITZ_LAIT_SOLAIRE_SPF50,
    tagSlug: TAG_SLUGS.PEAU_ATOPIQUE,
  }, // Adapté bébés/enfants

  // CICA REPA Crème réparatrice
  {
    productSlug: LAB_BIARRITZ_PRODUCT_SLUGS.LABORATOIRES_BIARRITZ_CICA_REPA_CREME_REPARATRICE,
    tagSlug: TAG_SLUGS.REPARATEUR,
  },
  {
    productSlug: LAB_BIARRITZ_PRODUCT_SLUGS.LABORATOIRES_BIARRITZ_CICA_REPA_CREME_REPARATRICE,
    tagSlug: TAG_SLUGS.REPARATEUR,
  },
  {
    productSlug: LAB_BIARRITZ_PRODUCT_SLUGS.LABORATOIRES_BIARRITZ_CICA_REPA_CREME_REPARATRICE,
    tagSlug: TAG_SLUGS.BARRIERE_CUTANEE,
  },
  {
    productSlug: LAB_BIARRITZ_PRODUCT_SLUGS.LABORATOIRES_BIARRITZ_CICA_REPA_CREME_REPARATRICE,
    tagSlug: TAG_SLUGS.SANS_PARFUM,
  },

  // Crème de nuit régénérante
  {
    productSlug: LAB_BIARRITZ_PRODUCT_SLUGS.LABORATOIRES_BIARRITZ_CREME_NUIT_REGENERANTE,
    tagSlug: TAG_SLUGS.SOIN_DE_NUIT,
  },
  {
    productSlug: LAB_BIARRITZ_PRODUCT_SLUGS.LABORATOIRES_BIARRITZ_CREME_NUIT_REGENERANTE,
    tagSlug: TAG_SLUGS.ANTI_AGE,
  },
  {
    productSlug: LAB_BIARRITZ_PRODUCT_SLUGS.LABORATOIRES_BIARRITZ_CREME_NUIT_REGENERANTE,
    tagSlug: TAG_SLUGS.DESHYDRATATION,
  },

  // La crème de Biarritz (Visage)
  {
    productSlug: LAB_BIARRITZ_PRODUCT_SLUGS.LABORATOIRES_BIARRITZ_CREME_VISAGE,
    tagSlug: TAG_SLUGS.CREME_HYDRATANTE,
  },
  {
    productSlug: LAB_BIARRITZ_PRODUCT_SLUGS.LABORATOIRES_BIARRITZ_CREME_VISAGE,
    tagSlug: TAG_SLUGS.ANTI_AGE,
  },
  {
    productSlug: LAB_BIARRITZ_PRODUCT_SLUGS.LABORATOIRES_BIARRITZ_CREME_VISAGE,
    tagSlug: TAG_SLUGS.ECLAT,
  },

  // Sérum anti-taches & Crème de nuit anti-taches
  {
    productSlug: LAB_BIARRITZ_PRODUCT_SLUGS.LABORATOIRES_BIARRITZ_SERUM_ANTI_TACHES,
    tagSlug: TAG_SLUGS.SERUM,
  },
  {
    productSlug: LAB_BIARRITZ_PRODUCT_SLUGS.LABORATOIRES_BIARRITZ_SERUM_ANTI_TACHES,
    tagSlug: TAG_SLUGS.ANTI_TACHES,
  },
  {
    productSlug: LAB_BIARRITZ_PRODUCT_SLUGS.LABORATOIRES_BIARRITZ_SERUM_ANTI_TACHES,
    tagSlug: TAG_SLUGS.HYPERPIGMENTATION,
  },
  {
    productSlug: LAB_BIARRITZ_PRODUCT_SLUGS.LABORATOIRES_BIARRITZ_CREME_NUIT_ANTI_TACHES,
    tagSlug: TAG_SLUGS.ANTI_TACHES,
  },
  {
    productSlug: LAB_BIARRITZ_PRODUCT_SLUGS.LABORATOIRES_BIARRITZ_CREME_NUIT_ANTI_TACHES,
    tagSlug: TAG_SLUGS.SOIN_DE_NUIT,
  },

  // Sérum repulpant
  {
    productSlug: LAB_BIARRITZ_PRODUCT_SLUGS.LABORATOIRES_BIARRITZ_SERUM_REPULPANT,
    tagSlug: TAG_SLUGS.SERUM,
  },
  {
    productSlug: LAB_BIARRITZ_PRODUCT_SLUGS.LABORATOIRES_BIARRITZ_SERUM_REPULPANT,
    tagSlug: TAG_SLUGS.HUMECTANT,
  }, // Riche en Acide Hyaluronique
  {
    productSlug: LAB_BIARRITZ_PRODUCT_SLUGS.LABORATOIRES_BIARRITZ_SERUM_REPULPANT,
    tagSlug: TAG_SLUGS.DESHYDRATATION,
  },
]
