import { TAG_SLUGS } from '../../tags/seed-tags'
import { TONERS_PRODUCT_SLUGS } from './toners'

export const TONERS_PRODUCT_TAGS: { productSlug: string; tagSlug: string }[] = [
  {
    productSlug: TONERS_PRODUCT_SLUGS.HARUHARU_BLACK_RICE_HYALURONIC_FF,
    tagSlug: TAG_SLUGS.TONIQUE,
  },
  {
    productSlug: TONERS_PRODUCT_SLUGS.HARUHARU_BLACK_RICE_HYALURONIC_FF,
    tagSlug: TAG_SLUGS.DESHYDRATATION,
  },
  {
    productSlug: TONERS_PRODUCT_SLUGS.HARUHARU_BLACK_RICE_HYALURONIC_FF,
    tagSlug: TAG_SLUGS.PEAU_SENSIBLE,
  },
  {
    productSlug: TONERS_PRODUCT_SLUGS.HARUHARU_BLACK_RICE_HYALURONIC_FF,
    tagSlug: TAG_SLUGS.SANS_PARFUM,
  },
  {
    productSlug: TONERS_PRODUCT_SLUGS.HARUHARU_BLACK_RICE_HYALURONIC_FF,
    tagSlug: TAG_SLUGS.HUMECTANT,
  },
  { productSlug: TONERS_PRODUCT_SLUGS.HARUHARU_BLACK_RICE_HYALURONIC_FF, tagSlug: TAG_SLUGS.ECLAT },
  { productSlug: TONERS_PRODUCT_SLUGS.IM_FROM_RICE_TONER, tagSlug: TAG_SLUGS.TONIQUE },
  { productSlug: TONERS_PRODUCT_SLUGS.IM_FROM_RICE_TONER, tagSlug: TAG_SLUGS.PEAU_SECHE },
  { productSlug: TONERS_PRODUCT_SLUGS.IM_FROM_RICE_TONER, tagSlug: TAG_SLUGS.ECLAT },
  { productSlug: TONERS_PRODUCT_SLUGS.IM_FROM_RICE_TONER, tagSlug: TAG_SLUGS.ANTI_AGE },
  { productSlug: TONERS_PRODUCT_SLUGS.IM_FROM_RICE_TONER, tagSlug: TAG_SLUGS.EMOLLIENT },
  { productSlug: TONERS_PRODUCT_SLUGS.EQQUALBERRY_SWIMMING_POOL, tagSlug: TAG_SLUGS.TONIQUE },
  { productSlug: TONERS_PRODUCT_SLUGS.EQQUALBERRY_SWIMMING_POOL, tagSlug: TAG_SLUGS.EXFOLIANT },
  { productSlug: TONERS_PRODUCT_SLUGS.EQQUALBERRY_SWIMMING_POOL, tagSlug: TAG_SLUGS.PORES_DILATES },
  {
    productSlug: TONERS_PRODUCT_SLUGS.EQQUALBERRY_SWIMMING_POOL,
    tagSlug: TAG_SLUGS.HYPOALLERGENIQUE,
  },
  { productSlug: TONERS_PRODUCT_SLUGS.EQQUALBERRY_SWIMMING_POOL, tagSlug: TAG_SLUGS.ANTI_OXYDANT },
  { productSlug: TONERS_PRODUCT_SLUGS.MIXSOON_CENTELLA_ASIATICA, tagSlug: TAG_SLUGS.TONIQUE },
  { productSlug: TONERS_PRODUCT_SLUGS.MIXSOON_CENTELLA_ASIATICA, tagSlug: TAG_SLUGS.PEAU_REACTIVE },
  { productSlug: TONERS_PRODUCT_SLUGS.MIXSOON_CENTELLA_ASIATICA, tagSlug: TAG_SLUGS.ANTI_ROUGEURS },
  { productSlug: TONERS_PRODUCT_SLUGS.MIXSOON_CENTELLA_ASIATICA, tagSlug: TAG_SLUGS.SANS_PARFUM },
  { productSlug: TONERS_PRODUCT_SLUGS.MIXSOON_CENTELLA_ASIATICA, tagSlug: TAG_SLUGS.REPARATEUR },
  // No.9 NAD+ PDRN Glow
  { productSlug: TONERS_PRODUCT_SLUGS.NUMBUZIN_NO9_NAD_PDRN_GLOW, tagSlug: TAG_SLUGS.TONIQUE },
  { productSlug: TONERS_PRODUCT_SLUGS.NUMBUZIN_NO9_NAD_PDRN_GLOW, tagSlug: TAG_SLUGS.ANTI_AGE },
  { productSlug: TONERS_PRODUCT_SLUGS.NUMBUZIN_NO9_NAD_PDRN_GLOW, tagSlug: TAG_SLUGS.ECLAT },
  {
    productSlug: TONERS_PRODUCT_SLUGS.NUMBUZIN_NO9_NAD_PDRN_GLOW,
    tagSlug: TAG_SLUGS.NON_COMEDOGENE,
  },
  // No.1 Pure-Full Calming
  { productSlug: TONERS_PRODUCT_SLUGS.NUMBUZIN_NO1_PURE_FULL_CALMING, tagSlug: TAG_SLUGS.TONIQUE },
  {
    productSlug: TONERS_PRODUCT_SLUGS.NUMBUZIN_NO1_PURE_FULL_CALMING,
    tagSlug: TAG_SLUGS.ANTI_ACNE,
  },
  {
    productSlug: TONERS_PRODUCT_SLUGS.NUMBUZIN_NO1_PURE_FULL_CALMING,
    tagSlug: TAG_SLUGS.ANTI_ROUGEURS,
  },
  {
    productSlug: TONERS_PRODUCT_SLUGS.NUMBUZIN_NO1_PURE_FULL_CALMING,
    tagSlug: TAG_SLUGS.NON_COMEDOGENE,
  },
  // No.5+ Glutathione Vitamin
  {
    productSlug: TONERS_PRODUCT_SLUGS.NUMBUZIN_NO5_GLUTATHIONE_VITAMIN,
    tagSlug: TAG_SLUGS.TONIQUE,
  },
  {
    productSlug: TONERS_PRODUCT_SLUGS.NUMBUZIN_NO5_GLUTATHIONE_VITAMIN,
    tagSlug: TAG_SLUGS.ANTI_TACHES,
  },
  {
    productSlug: TONERS_PRODUCT_SLUGS.NUMBUZIN_NO5_GLUTATHIONE_VITAMIN,
    tagSlug: TAG_SLUGS.HYPERPIGMENTATION,
  },
  { productSlug: TONERS_PRODUCT_SLUGS.NUMBUZIN_NO5_GLUTATHIONE_VITAMIN, tagSlug: TAG_SLUGS.ECLAT },
]
