import type { CreateProductInput } from '@habit-tracker/shared'

// ─── Slugs ────────────────────────────────────────────────

export const SOLAIRES_SLUGS = {
  AVENE_CLEANANCE_SPF50: 'avene-solaire-cleanance-solaire-spf50-plus',
  AVENE_SUNSIMED_KA_SPF50: 'avene-solaire-sunsimed-ka-spf50-plus',
  ACTINICA_LOTION_SPF50_LOT3: 'actinica-lotion-tres-haute-protection-spf50-lot-3',
  AVENE_TEINTEE_ANTI_LUMIERE_BLEUE_SPF50:
    'avene-solaires-creme-teinte-anti-lumiere-bleue-spf50-plus',
  EUCERIN_PHOTOAGING_CONTROL_FLUIDE_SPF50:
    'eucerin-sun-protection-photoaging-control-fluide-anti-age-spf50',
  EUCERIN_LEB_PROTECT_CREME_GEL_SPF50:
    'eucerin-sun-protection-leb-protect-creme-gel-visage-corps-spf50',
  RIEMANN_P20_SENSITIVE_FACE_SPF50: 'riemann-p20-sensitive-face-creme-solaire-ip50-plus',
  RIEMANN_P20_URBAN_SHIELD_SPF50: 'riemann-p20-urban-shield-creme-solaire-ip50-plus',
  RIEMANN_P20_SENSITIVE_SKIN_SPF50: 'riemann-p20-sensitive-skin-creme-solaire-ip50-plus',
  AVENE_ULTRA_FLUID_OIL_CONTROL_SPF50: 'avene-ultra-fluid-oil-control-spf50',
  AVENE_ULTRA_FLUID_ECLAT_RADIANCE_SPF50: 'avene-ultra-fluid-eclat-radiance-spf50-plus',
  AVENE_ULTRA_FLUID_PERFECTEUR_SPF50: 'avene-ultra-fluid-perfecteur-spf50-plus',
} as const

// ─── Data ─────────────────────────────────────────────────

export const solairesProductData: CreateProductInput[] = [
  {
    name: 'Solaire Cleanance Solaire SPF50+',
    brand: 'Avène',
    kind: 'skincare',
    unit: 'pump',
    slug: SOLAIRES_SLUGS.AVENE_CLEANANCE_SPF50,
    totalAmount: 50,
    amountUnit: 'ml',
    priceCents: 1299,
    description:
      'Protection solaire SPF50+ matifiante pour peaux grasses/acnéiques. Contrôle sébum, anti-imperfections, tolérance élevée.',
    notes:
      'Filtres chimiques + minéraux (Tinosorb M, Mexoryl SX/XL, Uvinul A Plus). Eau thermale apaisante, texture fluide non grasse. Sans parfum fort.',
    inci: 'AVENE THERMAL SPRING WATER (AVENE AQUA), C12-15 ALKYL BENZOATE, METHYLENE BIS-BENZOTRIAZOLYL TETRAMETHYLBUTYLPHENOL [NANO], CETEARYL ISONONANOATE, WATER (AQUA), DIISOPROPYL ADIPATE, ISODECYL NEOPENTANOATE, BIS-ETHYLHEXYLOXYPHENOL METHOXYPHENYL TRIAZINE, DIETHYLHEXYL BUTAMIDO TRIAZONE, POLYMETHYL METHACRYLATE, BUTYL METHOXYDIBENZOYLMETHANE, POTASSIUM CETYL PHOSPHATE, DECYL GLUCOSIDE, GLYCERYL LAURATE, ACRYLATES/C10-30 ALKYL ACRYLATE CROSSPOLYMER, BENZOIC ACID, CAPRYLIC/CAPRIC TRIGLYCERIDE, CAPRYLYL GLYCOL, DISODIUM EDTA, FRAGRANCE (PARFUM), GLYCERYL BEHENATE, GLYCERYL DIBEHENATE, HYDROGENATED PALM GLYCERIDES, HYDROGENATED PALM KERNEL GLYCERIDES, PROPYLENE GLYCOL, SILICA, SODIUM HYDROXIDE, TOCOPHERYL GLUCOSIDE, TRIBEHENIN, XANTHAN GUM, ZINC GLUCONATE',
    url: 'https://www.eau-thermale-avene.fr',
  },
  {
    name: 'SunsiMed KA SPF50+',
    brand: 'Avène',
    kind: 'skincare',
    unit: 'pump',
    slug: SOLAIRES_SLUGS.AVENE_SUNSIMED_KA_SPF50,
    totalAmount: 80,
    amountUnit: 'ml',
    priceCents: 1799,
    description:
      'Protection SPF50+ très haute pour peaux à kératoses actiniques. Prévention photo-vieillissement et cancers cutanés.',
    notes:
      'Filtres large spectre + eau thermale + anti-oxydants. Texture crème non grasse, tolérance optimale peaux fragiles/sensibles.',
    inci: 'AVENE THERMAL SPRING WATER (AVENE AQUA), C12-15 ALKYL BENZOATE, METHYLENE BIS-BENZOTRIAZOLYL TETRAMETHYLBUTYLPHENOL [NANO], WATER (AQUA), CETEARYL ISONONANOATE, DIISOPROPYL ADIPATE, ISODECYL NEOPENTANOATE, BIS-ETHYLHEXYLOXYPHENOL METHOXYPHENYL TRIAZINE, DIETHYLHEXYL BUTAMIDO TRIAZONE, ALUMINUM STARCH OCTENYLSUCCINATE, BUTYL METHOXYDIBENZOYLMETHANE, POTASSIUM CETYL PHOSPHATE, DECYL GLUCOSIDE, C10-18 TRIGLYCERIDES, ACRYLATES/C10-30 ALKYL ACRYLATE CROSSPOLYMER, BENZOIC ACID, CAPRYLIC/CAPRIC TRIGLYCERIDE, CAPRYLYL GLYCOL, DISODIUM EDTA, GLYCERYL BEHENATE, GLYCERYL DIBEHENATE, GLYCERYL LAURATE, PROPYLENE GLYCOL, SILICA (NANO), SODIUM HYDROXIDE, TOCOPHERYL GLUCOSIDE, TRIBEHENIN, XANTHAN GUM',
    url: 'https://www.eau-thermale-avene.fr',
  },
  {
    name: 'Lotion Très Haute Protection SPF50+ Lot de 3',
    brand: 'Actinica',
    kind: 'skincare',
    unit: 'pump',
    slug: SOLAIRES_SLUGS.ACTINICA_LOTION_SPF50_LOT3,
    totalAmount: 80,
    amountUnit: 'g',
    priceCents: 1449,
    description:
      'Lotion SPF50+ prévention kératoses actiniques et cancers cutanés non-mélanomes. Très haute protection UVA/UVB.',
    notes:
      'Filtres chimiques large spectre. Texture lotion légère. Usage quotidien peaux à risque.',
    inci: 'BIS-ETHYLHEXYLOXYPHENOL METHOXYPHENYL TRIAZINE, ETHYLHEXYL TRIAZONE, ISOAMYL P-METHOXYCINNAMATE, ETHYLHEXYL METHOXYCINNAMATE, METHYLENE BIS-BENZOTRIAZOLYL TETRAMETHYLBUTYLPHENOL, BUTYL METHOXYDIBENZOYLMETHANE, PROPYLPARABEN, METHYLPARABEN, EXCIPIENT',
    url: 'https://www.actinica.com',
  },
  {
    name: 'Crème Teintée Anti-Lumière Bleue SPF50+',
    brand: 'Avène',
    kind: 'skincare',
    unit: 'pump',
    slug: SOLAIRES_SLUGS.AVENE_TEINTEE_ANTI_LUMIERE_BLEUE_SPF50,
    totalAmount: 50,
    amountUnit: 'ml',
    priceCents: 1299,
    description:
      'Crème teintée SPF50+ anti-lumière bleue/UV. Protection large spectre + anti-pollution, unifie teint.',
    notes:
      'Filtres chimiques/minéraux + pigments naturels. Texture crème légère teintée, eau thermale apaisante. Peaux sensibles.',
    inci: 'AVENE THERMAL SPRING WATER (AVENE AQUA), C12-15 ALKYL BENZOATE, DIETHYLAMINO HYDROXYBENZOYL HEXYL BENZOATE, ETHYLHEXYL TRIAZONE, GLYCERIN, PHENYLENE BIS-DIPHENYLTRIAZINE, WATER (AQUA), BIS-ETHYLHEXYLOXYPHENOL METHOXYPHENYL TRIAZINE, TITANIUM DIOXIDE (CI 77891), POTASSIUM CETYL PHOSPHATE, MYRISTYL ALCOHOL, ORYZA SATIVA (RICE) STARCH, STEARYL ALCOHOL, ISONONYL ISONONANOATE, VP/EICOSENE COPOLYMER, ALUMINA, BENZOIC ACID, CAPRYLIC/CAPRIC TRIGLYCERIDE, CAPRYLYL GLYCOL, FRAGRANCE (PARFUM), GLYCERYL BEHENATE, GLYCERYL DIBEHENATE, IRON OXIDES (CI 77492) (CI 77491) (CI 77499), ISOPROPYL MYRISTATE, ISOPROPYL TITANIUM TRIISOSTEARATE, MYRISTYL GLUCOSIDE, POLYHYDROXYSTEARIC ACID, PPG-1-PEG-9 LAURYL GLYCOL ETHER, PROPYLENE CARBONATE, STEARALKONIUM HECTORITE, TOCOPHERYL GLUCOSIDE, TRIBEHENIN, XANTHAN GUM',
    url: 'https://www.eau-thermale-avene.fr',
  },
  {
    name: 'Sun Protection Photoaging Control Fluide Anti-Âge SPF50',
    brand: 'Eucerin',
    kind: 'skincare',
    unit: 'pump',
    slug: SOLAIRES_SLUGS.EUCERIN_PHOTOAGING_CONTROL_FLUIDE_SPF50,
    totalAmount: 50,
    amountUnit: 'ml',
    priceCents: 1249,
    description:
      'Fluide anti-âge SPF50 protection photo-vieillissement. Anti-rides, raffermissant, matifiant.',
    notes:
      'Filtres chimiques + Glycyrrhetinic Acid + extrait réglisse + HA. Texture fluide légère, peaux matures/sensibles.',
    inci: 'AQUA, C12-15 ALKYL BENZOATE, GLYCERIN, ALCOHOL DENAT., BUTYL METHOXYDIBENZOYLMETHANE, BIS-ETHYLHEXYLOXYPHENOL METHOXYPHENYL TRIAZINE, BUTYLENE GLYCOL DICAPRYLATE/DICAPRATE, ETHYLHEXYL TRIAZONE, DIBUTYL ADIPATE, DISTARCH PHOSPHATE, TAPIOCA STARCH, DIETHYLAMINO HYDROXYBENZOYL HEXYL BENZOATE, GLYCERYL STEARATE CITRATE, PHENYLBENZIMIDAZOLE SULFONIC ACID, BEHENYL ALCOHOL, CETEARYL ALCOHOL, SODIUM HYALURONATE, GLYCYRRHETINIC ACID, GLYCYRRHIZA INFLATA ROOT EXTRACT, COPERNICIA CERIFERA CERA, CARRAGEENAN, XANTHAN GUM, HYDROXYPROPYL METHYLCELLULOSE, SILICA, TRISODIUM ETHYLENEDIAMINE DISUCCINATE, SODIUM HYDROXIDE, HYDROXYACETOPHENONE, ETHYLHEXYLGLYCERIN, BENZYL ALCOHOL',
    url: 'https://int.eucerin.com',
  },
  {
    name: 'Sun Protection LEB Protect Crème-Gel Visage Corps SPF50',
    brand: 'Eucerin',
    kind: 'skincare',
    unit: 'pump',
    slug: SOLAIRES_SLUGS.EUCERIN_LEB_PROTECT_CREME_GEL_SPF50,
    totalAmount: 150,
    amountUnit: 'ml',
    priceCents: 1199,
    description:
      'Crème-gel SPF50 protection très haute UVA/UVB pour peaux sensibles. Texture légère non grasse.',
    notes:
      'Filtres chimiques + extrait réglisse + tocophérol. Idéal visage/corps, peaux intolérantes.',
    inci: 'AQUA, ALCOHOL DENAT., BUTYL METHOXYDIBENZOYLMETHANE, ISOPROPYL PALMITATE, BIS-ETHYLHEXYLOXYPHENOL METHOXYPHENYL TRIAZINE, C12-15 ALKYL BENZOATE, DIBUTYL ADIPATE, DISTARCH PHOSPHATE, DIETHYLAMINO HYDROXYBENZOYL HEXYL BENZOATE, ETHYLHEXYL TRIAZONE, BUTYLENE GLYCOL DICAPRYLATE/DICAPRATE, PHENYLBENZIMIDAZOLE SULFONIC ACID, DIETHYLHEXYL BUTAMIDO TRIAZONE, GLYCERYL STEARATE, HYDROXYPROPYL STARCH PHOSPHATE, GLYCYRRHIZA INFLATA ROOT EXTRACT, GLUCOSYLRUTIN, ISOQUERCITRIN, GLYCYRRHETINIC ACID, TOCOPHEROL, GLYCERIN, C18-38 ALKYL HYDROXYSTEAROYL STEARATE, COPERNICIA CERIFERA CERA, HYDROGENATED RAPESEED OIL, CETYL PALMITATE, MICROCRYSTALLINE CELLULOSE, XANTHAN GUM, CELLULOSE GUM, SODIUM STEAROYL GLUTAMATE, SILICA DIMETHYL SILYLATE, PHENOXYETHANOL, CAPRYLYL GLYCOL, HYDROXYACETOPHENONE, TRISODIUM EDTA, SODIUM HYDROXIDE, SODIUM CHLORIDE',
    url: 'https://int.eucerin.com',
  },
  {
    name: 'P20 Sensitive Face Crème Solaire IP50+ Nouvelle Formule',
    brand: 'Riemann P20',
    kind: 'skincare',
    unit: 'pump',
    slug: SOLAIRES_SLUGS.RIEMANN_P20_SENSITIVE_FACE_SPF50,
    totalAmount: 50,
    amountUnit: 'g',
    priceCents: 2549,
    description:
      "Crème SPF50+ sensitive pour visage. Protection très haute, résistante à l'eau, sans parfum.",
    notes:
      'Filtres chimiques + panthénol + tréhalose. Texture crème légère, peaux sensibles/irritées.',
    inci: 'AQUA, DIETHYLAMINO HYDROXYBENZOYL HEXYL BENZOATE, DIBUTYL ADIPATE, BIS-ETHYLHEXYLOXYPHENOL METHOXYPHENYL TRIAZINE, DICAPRYLYL CARBONATE, TRIS-BIPHENYL TRIAZINE (NANO), GLYCERIN, PHENOXYETHYL CAPRYLATE, CAPRYLYL CAPRYLATE/CAPRATE, CANOLA OIL, SILICA, POTASSIUM CETYL PHOSPHATE, PANTHENOL, TREHALOSE, CETEARYL ALCOHOL, ETHYLHEXYL TRIAZONE, VP/EICOSENE COPOLYMER, PHENOXYETHANOL, SQUALANE, GLYCERYL STEARATE, SODIUM OLIVOYL GLUTAMATE, SORBITAN CAPRYLATE, TOCOPHERYL ACETATE, DECYL GLUCOSIDE, BENZOIC ACID, CAPRYLYL GLYCOL, PROPANEDIOL, ACACIA SENEGAL GUM, XANTHAN GUM, SODIUM PHYTATE, TOCOPHEROLS, DEHYDROACETIC ACID, ASCORBYL PALMITATE, ETHYLHEXYLGLYCERIN, BUTYLENE GLYCOL, DISODIUM PHOSPHATE, CITRIC ACID, BIOSACCHARIDE GUM-1, POTASSIUM SORBATE, SODIUM BENZOATE, GLYCERYL CAPRYLATE, SODIUM LEVULINATE, SODIUM ANISATE, SODIUM HYDROXIDE',
    url: 'https://www.p20.com',
  },
  {
    name: 'P20 Urban Shield Crème Solaire IP50+',
    brand: 'Riemann P20',
    kind: 'skincare',
    unit: 'pump',
    slug: SOLAIRES_SLUGS.RIEMANN_P20_URBAN_SHIELD_SPF50,
    totalAmount: 50,
    amountUnit: 'g',
    priceCents: 2569,
    description:
      'Crème SPF50+ anti-pollution urbaine. Protection large spectre + antioxydants, texture légère.',
    notes:
      'Filtres chimiques + extraits végétaux (épinard, myrtille, pissenlit). Idéal ville/exposition quotidienne.',
    inci: 'AQUA/WATER/EAU, NEOPENTYL GLYCOL DIHEPTANOATE, ETHYLHEXYL METHOXYCINNAMATE, HOMOSALATE, ETHYLHEXYL SALICYLATE, DIETHYLAMINO HYDROXYBENZOYL HEXYL BENZOATE, GLYCERYL STEARATE CITRATE, BIS-ETHYLHEXYLOXYPHENOL METHOXYPHENYL TRIAZINE, ISOPENTYLDIOL, METHYL METHACRYLATE CROSSPOLYMER, SYNTHETIC FLUORPHLOGOPITE, TAPIOCA STARCH/TRITICUM VULGARE (WHEAT) STARCH, POTASSIUM CETYL PHOSPHATE, CETYL ALCOHOL, PROPANEDIOL, CAPRYLYL GLYCOL, SODIUM POLYACRYLATE, BENZYL ALCOHOL, PENTYLENE GLYCOL, POLYACRYLATE CROSSPOLYMER-11, SPINACIA OLERACEA LEAF EXTRACT, CARNOSINE, ARISTOTELIA CHILENSIS FRUIT EXTRACT, ETHYLHEXYLGLYCERIN, TARAXACUM OFFICINALE RHIZOME/ROOT EXTRACT, DISODIUM EDTA, CAPRYLHYDROXAMIC ACID, GLYCERIN, SODIUM HYDROXIDE, TEPHROSIA PURPUREA SEED EXTRACT, TIN OXIDE, BHT, SODIUM BENZOATE, POTASSIUM SORBATE, AMMONIUM C6-16 PERFLUOROALKYLETHYL PHOSPHATE, CI 77891/TITANIUM DIOXIDE, CI 77491/IRON OXIDES',
    url: 'https://www.p20.com',
  },
  {
    name: 'P20 Sensitive Skin Crème Solaire IP50+',
    brand: 'Riemann P20',
    kind: 'skincare',
    unit: 'pump',
    slug: SOLAIRES_SLUGS.RIEMANN_P20_SENSITIVE_SKIN_SPF50,
    totalAmount: 200,
    amountUnit: 'ml',
    priceCents: 4145,
    description:
      'Crème SPF50+ sensitive corps/visage. Très haute protection, résistante eau, sans parfum.',
    notes:
      'Filtres chimiques + panthénol + squalane. Texture crème légère, peaux très sensibles/irritées.',
    inci: 'AQUA, DIETHYLAMINO HYDROXYBENZOYL HEXYL BENZOATE, DIBUTYL ADIPATE, DICAPRYLYL CARBONATE, ETHYLHEXYL TRIAZONE, BIS-ETHYLHEXYLOXYPHENOL METHOXYPHENYL TRIAZINE, GLYCERIN, PHENOXYETHYL CAPRYLATE, DICAPRYLYL ETHER, TRIS-BIPHENYL TRIAZINE (NANO), POTASSIUM CETYL PHOSPHATE, CETEARYL ALCOHOL, SILICA, VP/ACRYLATES/LAURYL METHACRYLATE COPOLYMER, PHENOXYETHANOL, DIETHYLHEXYL BUTAMIDO TRIAZONE, SORBITAN CAPRYLATE, GLYCERYL STEARATE, SODIUM OLIVOYL GLUTAMATE, CANOLA OIL, ACRYLATES/C12-22 ALKYL METHACRYLATE COPOLYMER, BENZOIC ACID, DECYL GLUCOSIDE, PROPANEDIOL, ACACIA SENEGAL GUM, XANTHAN GUM, CAPRYLYL GLYCOL, SODIUM PHYTATE, PENTYLENE GLYCOL, DEHYDROACETIC ACID, SODIUM HYDROXIDE, ETHYLHEXYLGLYCERIN, DISODIUM PHOSPHATE, BUTYLENE GLYCOL, SODIUM BENZOATE, POTASSIUM SORBATE, TOCOPHEROL, CITRIC ACID',
    url: 'https://www.p20.com',
  },
  {
    name: 'Ultra Fluid Oil Control SPF50',
    brand: 'Avène',
    kind: 'skincare',
    unit: 'pump',
    slug: SOLAIRES_SLUGS.AVENE_ULTRA_FLUID_OIL_CONTROL_SPF50,
    totalAmount: 50,
    amountUnit: 'ml',
    priceCents: 1369,
    description:
      'Fluide matifiant SPF50 contrôle brillance/peaux grasses. Absorption rapide, fini sec.',
    notes:
      'Filtres chimiques + amidon riz/tapioca + lentille exfoliante douce. Texture ultra-fluide non grasse, peaux mixtes/grasses.',
    inci: 'AVENE THERMAL SPRING WATER (AVENE AQUA), C12-15 ALKYL BENZOATE, DICAPRYLYL CARBONATE, DIETHYLAMINO HYDROXYBENZOYL HEXYL BENZOATE, WATER (AQUA), DIISOPROPYL ADIPATE, ETHYLHEXYL TRIAZONE, ORYZA SATIVA (RICE) STARCH, PHENYLENE BIS-DIPHENYLTRIAZINE, TAPIOCA STARCH, BIS-ETHYLHEXYLOXYPHENOL METHOXYPHENYL TRIAZINE, POTASSIUM CETYL PHOSPHATE, C9-12 ALKANE, LAURYL GLUCOSIDE, POLYGLYCERYL-2 DIPOLYHYDROXYSTEARATE, GLYCERIN, TRIMETHYLPENTANEDIOL/ADIPIC ACID/GLYCERIN CROSSPOLYMER, BENZOIC ACID, CAPRYLIC/CAPRIC TRIGLYCERIDE, CAPRYLYL GLYCOL, CITRIC ACID, COCO-CAPRYLATE/CAPRATE, ETHYLHEXYLGLYCERIN, GLYCERYL LAURATE, HELIANTHUS ANNUUS (SUNFLOWER) SEED OIL, LENS ESCULENTA (LENTIL) SEED EXTRACT, PENTYLENE GLYCOL, PPG-1-PEG-9 LAURYL GLYCOL ETHER, RED 33 (CI 17200), SODIUM BENZOATE, SODIUM PHYTATE, TOCOPHEROL, TOCOPHERYL GLUCOSIDE, XANTHAN GUM',
    url: 'https://www.eau-thermale-avene.fr',
  },
  {
    name: 'Ultra Fluid Éclat Radiance SPF50+',
    brand: 'Avène',
    kind: 'skincare',
    unit: 'pump',
    slug: SOLAIRES_SLUGS.AVENE_ULTRA_FLUID_ECLAT_RADIANCE_SPF50,
    totalAmount: 50,
    amountUnit: 'ml',
    priceCents: 1399,
    description:
      'Fluide SPF50+ éclat radiance pour peaux normales/mixtes. Illumine, matifie, protection large spectre.',
    notes:
      'Filtres chimiques + amidon riz + lentille + huiles végétales. Texture fluide glowy non grasse.',
    inci: 'AVENE THERMAL SPRING WATER (AVENE AQUA), C12-15 ALKYL BENZOATE, DICAPRYLYL CARBONATE, DIETHYLAMINO HYDROXYBENZOYL HEXYL BENZOATE, WATER (AQUA), DIISOPROPYL ADIPATE, ETHYLHEXYL TRIAZONE, ORYZA SATIVA (RICE) STARCH, PHENYLENE BIS-DIPHENYLTRIAZINE, BIS-ETHYLHEXYLOXYPHENOL METHOXYPHENYL TRIAZINE, POTASSIUM CETYL PHOSPHATE, C9-12 ALKANE, LAURYL GLUCOSIDE, POLYGLYCERYL-2 DIPOLYHYDROXYSTEARATE, GLYCERIN, TAPIOCA STARCH, TRIMETHYLPENTANEDIOL/ADIPIC ACID/GLYCERIN CROSSPOLYMER, BENZOIC ACID, CAPRYLIC/CAPRIC TRIGLYCERIDE, CAPRYLYL GLYCOL, CITRIC ACID, COCO-CAPRYLATE/CAPRATE, GLYCERYL LAURATE, GLYCINE SOJA (SOYBEAN) OIL, LENS ESCULENTA (LENTIL) SEED EXTRACT, PENTYLENE GLYCOL, PPG-1-PEG-9 LAURYL GLYCOL ETHER, RED 33 (CI 17200), SODIUM BENZOATE, SODIUM PHYTATE, TOCOPHEROL, TOCOPHERYL GLUCOSIDE, XANTHAN GUM',
    url: 'https://www.eau-thermale-avene.fr',
  },
  {
    name: 'Ultra Fluid Perfecteur SPF50+',
    brand: 'Avène',
    kind: 'skincare',
    unit: 'pump',
    slug: SOLAIRES_SLUGS.AVENE_ULTRA_FLUID_PERFECTEUR_SPF50,
    totalAmount: 50,
    amountUnit: 'ml',
    priceCents: 1549,
    description:
      'Fluide perfecteur SPF50+ teint parfait. Uniformise, matifie, protège des UV/lumière bleue.',
    notes:
      'Filtres chimiques + pigments + amidon riz + lentille. Texture fluide teintée légère, fini velours.',
    inci: 'AVENE THERMAL SPRING WATER (AVENE AQUA), C12-15 ALKYL BENZOATE, DIETHYLAMINO HYDROXYBENZOYL HEXYL BENZOATE, WATER (AQUA), ETHYLHEXYL TRIAZONE, ORYZA SATIVA (RICE) STARCH, PHENYLENE BIS-DIPHENYLTRIAZINE, BIS-ETHYLHEXYLOXYPHENOL METHOXYPHENYL TRIAZINE, POTASSIUM CETYL PHOSPHATE, LAURYL GLUCOSIDE, POLYGLYCERYL-2 DIPOLYHYDROXYSTEARATE, GLYCERIN, TAPIOCA STARCH, TRIMETHYLPENTANEDIOL/ADIPIC ACID/GLYCERIN CROSSPOLYMER, ALUMINA, BENZOIC ACID, CAPRYLIC/CAPRIC TRIGLYCERIDE, CAPRYLYL GLYCOL, CITRIC ACID, ETHYLHEXYLGLYCERIN, GLYCERYL LAURATE, IRON OXIDES (CI 77492) (CI 77491) (CI 77499), ISONONYL ISONONANOATE, ISOPROPYL MYRISTATE, ISOPROPYL TITANIUM TRIISOSTEARATE, LENS ESCULENTA (LENTIL) SEED EXTRACT, PENTYLENE GLYCOL, POLYHYDROXYSTEARIC ACID, PPG-1-PEG-9 LAURYL GLYCOL ETHER, PROPYLENE CARBONATE, SODIUM BENZOATE, SODIUM PHYTATE, STEARALKONIUM HECTORITE, TITANIUM DIOXIDE (CI 77891), TOCOPHEROL, TOCOPHERYL GLUCOSIDE, XANTHAN GUM',
    url: 'https://www.eau-thermale-avene.fr',
  },
]
