import { TAG_SLUGS } from '../../tags/seed-tags'
import { KOREAN_PRODUCT_SLUGS } from './koreanSkincare'

export const KOREAN_PRODUCT_TAGS: { productSlug: string; tagSlug: string }[] = [
  // COSRX - Advanced Snail 96 Mucin Essence
  { productSlug: KOREAN_PRODUCT_SLUGS.COSRX_ADVANCED_SNAIL_96, tagSlug: TAG_SLUGS.ESSENCE },
  { productSlug: KOREAN_PRODUCT_SLUGS.COSRX_ADVANCED_SNAIL_96, tagSlug: TAG_SLUGS.REPARATEUR },
  { productSlug: KOREAN_PRODUCT_SLUGS.COSRX_ADVANCED_SNAIL_96, tagSlug: TAG_SLUGS.DESHYDRATATION },
  { productSlug: KOREAN_PRODUCT_SLUGS.COSRX_ADVANCED_SNAIL_96, tagSlug: TAG_SLUGS.ECLAT },
  { productSlug: KOREAN_PRODUCT_SLUGS.COSRX_ADVANCED_SNAIL_96, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },
  { productSlug: KOREAN_PRODUCT_SLUGS.COSRX_ADVANCED_SNAIL_96, tagSlug: TAG_SLUGS.SANS_PARFUM },

  // SOME BY MI - 30 Days Miracle Clear Spot Patch
  {
    productSlug: KOREAN_PRODUCT_SLUGS.SOME_BY_MI_30_DAYS_MIRACLE_PATCH,
    tagSlug: TAG_SLUGS.ANTI_ACNE,
  },
  {
    productSlug: KOREAN_PRODUCT_SLUGS.SOME_BY_MI_30_DAYS_MIRACLE_PATCH,
    tagSlug: TAG_SLUGS.REPARATEUR,
  },

  // Dr.G - R.E.D Blemish Cica Soothing Cream
  {
    productSlug: KOREAN_PRODUCT_SLUGS.DRG_RED_BLEMISH_CICA_SOOTHING,
    tagSlug: TAG_SLUGS.CREME_HYDRATANTE,
  },
  {
    productSlug: KOREAN_PRODUCT_SLUGS.DRG_RED_BLEMISH_CICA_SOOTHING,
    tagSlug: TAG_SLUGS.ANTI_ROUGEURS,
  },
  {
    productSlug: KOREAN_PRODUCT_SLUGS.DRG_RED_BLEMISH_CICA_SOOTHING,
    tagSlug: TAG_SLUGS.PEAU_REACTIVE,
  },
  {
    productSlug: KOREAN_PRODUCT_SLUGS.DRG_RED_BLEMISH_CICA_SOOTHING,
    tagSlug: TAG_SLUGS.REPARATEUR,
  },
  {
    productSlug: KOREAN_PRODUCT_SLUGS.DRG_RED_BLEMISH_CICA_SOOTHING,
    tagSlug: TAG_SLUGS.NON_COMEDOGENE,
  },

  // Purito SEOUL - Oat-In Calming Gel Cream
  {
    productSlug: KOREAN_PRODUCT_SLUGS.PURITO_OAT_IN_CALMING_GEL,
    tagSlug: TAG_SLUGS.CREME_HYDRATANTE,
  }, // Version Gel
  { productSlug: KOREAN_PRODUCT_SLUGS.PURITO_OAT_IN_CALMING_GEL, tagSlug: TAG_SLUGS.PEAU_MIXTE },
  { productSlug: KOREAN_PRODUCT_SLUGS.PURITO_OAT_IN_CALMING_GEL, tagSlug: TAG_SLUGS.PEAU_GRASSE },
  { productSlug: KOREAN_PRODUCT_SLUGS.PURITO_OAT_IN_CALMING_GEL, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },
  { productSlug: KOREAN_PRODUCT_SLUGS.PURITO_OAT_IN_CALMING_GEL, tagSlug: TAG_SLUGS.SANS_PARFUM },
  { productSlug: KOREAN_PRODUCT_SLUGS.PURITO_OAT_IN_CALMING_GEL, tagSlug: TAG_SLUGS.VEGAN },

  // COSRX - Advanced Snail 92 All In One Cream
  {
    productSlug: KOREAN_PRODUCT_SLUGS.COSRX_ADVANCED_SNAIL_92,
    tagSlug: TAG_SLUGS.CREME_HYDRATANTE,
  },
  { productSlug: KOREAN_PRODUCT_SLUGS.COSRX_ADVANCED_SNAIL_92, tagSlug: TAG_SLUGS.REPARATEUR },
  { productSlug: KOREAN_PRODUCT_SLUGS.COSRX_ADVANCED_SNAIL_92, tagSlug: TAG_SLUGS.ANTI_AGE },
  {
    productSlug: KOREAN_PRODUCT_SLUGS.COSRX_ADVANCED_SNAIL_92,
    tagSlug: TAG_SLUGS.BARRIERE_CUTANEE,
  },
  { productSlug: KOREAN_PRODUCT_SLUGS.COSRX_ADVANCED_SNAIL_92, tagSlug: TAG_SLUGS.SANS_PARFUM },

  // Isntree - Hyaluronic Acid Moist Cream
  {
    productSlug: KOREAN_PRODUCT_SLUGS.ISNTREE_HYALURONIC_ACID_MOIST,
    tagSlug: TAG_SLUGS.CREME_HYDRATANTE,
  },
  {
    productSlug: KOREAN_PRODUCT_SLUGS.ISNTREE_HYALURONIC_ACID_MOIST,
    tagSlug: TAG_SLUGS.DESHYDRATATION,
  },
  { productSlug: KOREAN_PRODUCT_SLUGS.ISNTREE_HYALURONIC_ACID_MOIST, tagSlug: TAG_SLUGS.HUMECTANT },
  {
    productSlug: KOREAN_PRODUCT_SLUGS.ISNTREE_HYALURONIC_ACID_MOIST,
    tagSlug: TAG_SLUGS.PEAU_NORMALE,
  },
  {
    productSlug: KOREAN_PRODUCT_SLUGS.ISNTREE_HYALURONIC_ACID_MOIST,
    tagSlug: TAG_SLUGS.SANS_PARFUM,
  },
]
