import { TAG_SLUGS } from '../../tags/seed-tags'
import { AVENE_PRODUCT_SLUGS } from './avene'

export const AVENE_PRODUCT_TAGS: { productSlug: string; tagSlug: string }[] = [
  // Cleanance Comedomed Sérum Intensif
  {
    productSlug: AVENE_PRODUCT_SLUGS.AVENE_CLEANANCE_COMEDOMED_SERUM_INTENSIF,
    tagSlug: TAG_SLUGS.ANTI_ACNE,
  },
  {
    productSlug: AVENE_PRODUCT_SLUGS.AVENE_CLEANANCE_COMEDOMED_SERUM_INTENSIF,
    tagSlug: TAG_SLUGS.POST_ACNE,
  },
  {
    productSlug: AVENE_PRODUCT_SLUGS.AVENE_CLEANANCE_COMEDOMED_SERUM_INTENSIF,
    tagSlug: TAG_SLUGS.PEAU_GRASSE,
  },
  {
    productSlug: AVENE_PRODUCT_SLUGS.AVENE_CLEANANCE_COMEDOMED_SERUM_INTENSIF,
    tagSlug: TAG_SLUGS.PORES_DILATES,
  },
  {
    productSlug: AVENE_PRODUCT_SLUGS.AVENE_CLEANANCE_COMEDOMED_SERUM_INTENSIF,
    tagSlug: TAG_SLUGS.SERUM,
  },
  {
    productSlug: AVENE_PRODUCT_SLUGS.AVENE_CLEANANCE_COMEDOMED_SERUM_INTENSIF,
    tagSlug: TAG_SLUGS.KERATOLYTIQUE,
  },
  {
    productSlug: AVENE_PRODUCT_SLUGS.AVENE_CLEANANCE_COMEDOMED_SERUM_INTENSIF,
    tagSlug: TAG_SLUGS.SEBO_REGULATEUR,
  },

  // Hyaluron Activ Procedure Crème Lifting
  {
    productSlug: AVENE_PRODUCT_SLUGS.AVENE_HYALURON_ACTIV_PROCEDURE_CREME_LIFTING,
    tagSlug: TAG_SLUGS.ANTI_AGE,
  },
  {
    productSlug: AVENE_PRODUCT_SLUGS.AVENE_HYALURON_ACTIV_PROCEDURE_CREME_LIFTING,
    tagSlug: TAG_SLUGS.CREME_HYDRATANTE,
  },
  {
    productSlug: AVENE_PRODUCT_SLUGS.AVENE_HYALURON_ACTIV_PROCEDURE_CREME_LIFTING,
    tagSlug: TAG_SLUGS.SOIN_DE_JOUR,
  },
  {
    productSlug: AVENE_PRODUCT_SLUGS.AVENE_HYALURON_ACTIV_PROCEDURE_CREME_LIFTING,
    tagSlug: TAG_SLUGS.SOIN_DE_NUIT,
  },
  {
    productSlug: AVENE_PRODUCT_SLUGS.AVENE_HYALURON_ACTIV_PROCEDURE_CREME_LIFTING,
    tagSlug: TAG_SLUGS.PEAU_SENSIBLE,
  },
  {
    productSlug: AVENE_PRODUCT_SLUGS.AVENE_HYALURON_ACTIV_PROCEDURE_CREME_LIFTING,
    tagSlug: TAG_SLUGS.ECLAT,
  },

  // XeraCalm A.D Crème Relipidante
  {
    productSlug: AVENE_PRODUCT_SLUGS.AVENE_XERACALM_AD_CREME_RELIPIDANTE,
    tagSlug: TAG_SLUGS.PEAU_SECHE,
  },
  {
    productSlug: AVENE_PRODUCT_SLUGS.AVENE_XERACALM_AD_CREME_RELIPIDANTE,
    tagSlug: TAG_SLUGS.PEAU_ATOPIQUE,
  },
  {
    productSlug: AVENE_PRODUCT_SLUGS.AVENE_XERACALM_AD_CREME_RELIPIDANTE,
    tagSlug: TAG_SLUGS.BARRIERE_CUTANEE,
  },
  {
    productSlug: AVENE_PRODUCT_SLUGS.AVENE_XERACALM_AD_CREME_RELIPIDANTE,
    tagSlug: TAG_SLUGS.CREME_HYDRATANTE,
  },
  {
    productSlug: AVENE_PRODUCT_SLUGS.AVENE_XERACALM_AD_CREME_RELIPIDANTE,
    tagSlug: TAG_SLUGS.REPARATEUR,
  },
  {
    productSlug: AVENE_PRODUCT_SLUGS.AVENE_XERACALM_AD_CREME_RELIPIDANTE,
    tagSlug: TAG_SLUGS.EMOLLIENT,
  },
  {
    productSlug: AVENE_PRODUCT_SLUGS.AVENE_XERACALM_AD_CREME_RELIPIDANTE,
    tagSlug: TAG_SLUGS.OCCLUSIF,
  },

  // Cleanance Gel Nettoyant
  { productSlug: AVENE_PRODUCT_SLUGS.AVENE_CLEANANCE_GEL_NETTOYANT, tagSlug: TAG_SLUGS.NETTOYANT },
  {
    productSlug: AVENE_PRODUCT_SLUGS.AVENE_CLEANANCE_GEL_NETTOYANT,
    tagSlug: TAG_SLUGS.PEAU_GRASSE,
  },
  { productSlug: AVENE_PRODUCT_SLUGS.AVENE_CLEANANCE_GEL_NETTOYANT, tagSlug: TAG_SLUGS.ANTI_ACNE },
  {
    productSlug: AVENE_PRODUCT_SLUGS.AVENE_CLEANANCE_GEL_NETTOYANT,
    tagSlug: TAG_SLUGS.SEBO_REGULATEUR,
  },
  { productSlug: AVENE_PRODUCT_SLUGS.AVENE_CLEANANCE_GEL_NETTOYANT, tagSlug: TAG_SLUGS.SANS_SAVON },

  // Hydrance Riche Crème Hydratante
  {
    productSlug: AVENE_PRODUCT_SLUGS.AVENE_HYDRANCE_RICHE_CREME_HYDRATANTE,
    tagSlug: TAG_SLUGS.PEAU_SECHE,
  },
  {
    productSlug: AVENE_PRODUCT_SLUGS.AVENE_HYDRANCE_RICHE_CREME_HYDRATANTE,
    tagSlug: TAG_SLUGS.PEAU_SENSIBLE,
  },
  {
    productSlug: AVENE_PRODUCT_SLUGS.AVENE_HYDRANCE_RICHE_CREME_HYDRATANTE,
    tagSlug: TAG_SLUGS.DESHYDRATATION,
  },
  {
    productSlug: AVENE_PRODUCT_SLUGS.AVENE_HYDRANCE_RICHE_CREME_HYDRATANTE,
    tagSlug: TAG_SLUGS.CREME_HYDRATANTE,
  },
  {
    productSlug: AVENE_PRODUCT_SLUGS.AVENE_HYDRANCE_RICHE_CREME_HYDRATANTE,
    tagSlug: TAG_SLUGS.SOIN_DE_JOUR,
  },
  {
    productSlug: AVENE_PRODUCT_SLUGS.AVENE_HYDRANCE_RICHE_CREME_HYDRATANTE,
    tagSlug: TAG_SLUGS.SOIN_DE_NUIT,
  },

  // Cicalfate Crème Réparatrice
  {
    productSlug: AVENE_PRODUCT_SLUGS.AVENE_CICALFATE_CREME_REPARATRICE,
    tagSlug: TAG_SLUGS.REPARATEUR,
  },
  {
    productSlug: AVENE_PRODUCT_SLUGS.AVENE_CICALFATE_CREME_REPARATRICE,
    tagSlug: TAG_SLUGS.BARRIERE_CUTANEE,
  },
  {
    productSlug: AVENE_PRODUCT_SLUGS.AVENE_CICALFATE_CREME_REPARATRICE,
    tagSlug: TAG_SLUGS.PEAU_SENSIBLE,
  },
  {
    productSlug: AVENE_PRODUCT_SLUGS.AVENE_CICALFATE_CREME_REPARATRICE,
    tagSlug: TAG_SLUGS.ANTISEPTIQUE,
  },
  {
    productSlug: AVENE_PRODUCT_SLUGS.AVENE_CICALFATE_CREME_REPARATRICE,
    tagSlug: TAG_SLUGS.CREME_HYDRATANTE,
  },

  // Hyaluron Activ B3 Crème Régénération
  {
    productSlug: AVENE_PRODUCT_SLUGS.AVENE_HYALURON_ACTIV_B3_CREME_REGENERATION,
    tagSlug: TAG_SLUGS.ANTI_AGE,
  },
  {
    productSlug: AVENE_PRODUCT_SLUGS.AVENE_HYALURON_ACTIV_B3_CREME_REGENERATION,
    tagSlug: TAG_SLUGS.CREME_HYDRATANTE,
  },
  {
    productSlug: AVENE_PRODUCT_SLUGS.AVENE_HYALURON_ACTIV_B3_CREME_REGENERATION,
    tagSlug: TAG_SLUGS.ECLAT,
  },
  {
    productSlug: AVENE_PRODUCT_SLUGS.AVENE_HYALURON_ACTIV_B3_CREME_REGENERATION,
    tagSlug: TAG_SLUGS.PEAU_SENSIBLE,
  },

  // XeraCalm A.D Huile Lavante Relipidante
  {
    productSlug: AVENE_PRODUCT_SLUGS.AVENE_XERACALM_AD_HUILE_LAVANTE_RELIPIDANTE,
    tagSlug: TAG_SLUGS.HUILE,
  },
  {
    productSlug: AVENE_PRODUCT_SLUGS.AVENE_XERACALM_AD_HUILE_LAVANTE_RELIPIDANTE,
    tagSlug: TAG_SLUGS.NETTOYANT,
  },
  {
    productSlug: AVENE_PRODUCT_SLUGS.AVENE_XERACALM_AD_HUILE_LAVANTE_RELIPIDANTE,
    tagSlug: TAG_SLUGS.PEAU_ATOPIQUE,
  },
  {
    productSlug: AVENE_PRODUCT_SLUGS.AVENE_XERACALM_AD_HUILE_LAVANTE_RELIPIDANTE,
    tagSlug: TAG_SLUGS.PEAU_SECHE,
  },
  {
    productSlug: AVENE_PRODUCT_SLUGS.AVENE_XERACALM_AD_HUILE_LAVANTE_RELIPIDANTE,
    tagSlug: TAG_SLUGS.SANS_SAVON,
  },

  // Vitamin Activ C Sérum Éclat
  { productSlug: AVENE_PRODUCT_SLUGS.AVENE_VITAMIN_ACTIV_C_SERUM_ECLAT, tagSlug: TAG_SLUGS.SERUM },
  { productSlug: AVENE_PRODUCT_SLUGS.AVENE_VITAMIN_ACTIV_C_SERUM_ECLAT, tagSlug: TAG_SLUGS.ECLAT },
  {
    productSlug: AVENE_PRODUCT_SLUGS.AVENE_VITAMIN_ACTIV_C_SERUM_ECLAT,
    tagSlug: TAG_SLUGS.ANTI_TACHES,
  },
  {
    productSlug: AVENE_PRODUCT_SLUGS.AVENE_VITAMIN_ACTIV_C_SERUM_ECLAT,
    tagSlug: TAG_SLUGS.ANTI_OXYDANT,
  },
  {
    productSlug: AVENE_PRODUCT_SLUGS.AVENE_VITAMIN_ACTIV_C_SERUM_ECLAT,
    tagSlug: TAG_SLUGS.HYPERPIGMENTATION,
  },

  // Cleanance Solaire SPF50+
  { productSlug: AVENE_PRODUCT_SLUGS.AVENE_CLEANANCE_SPF50, tagSlug: TAG_SLUGS.PROTECTION_SOLAIRE },
  { productSlug: AVENE_PRODUCT_SLUGS.AVENE_CLEANANCE_SPF50, tagSlug: TAG_SLUGS.SOLAIRE_VISAGE },
  { productSlug: AVENE_PRODUCT_SLUGS.AVENE_CLEANANCE_SPF50, tagSlug: TAG_SLUGS.PEAU_GRASSE },
  { productSlug: AVENE_PRODUCT_SLUGS.AVENE_CLEANANCE_SPF50, tagSlug: TAG_SLUGS.ANTI_ACNE },
  { productSlug: AVENE_PRODUCT_SLUGS.AVENE_CLEANANCE_SPF50, tagSlug: TAG_SLUGS.SEBO_REGULATEUR },

  // Fluide Anti-Imperfection SPF50
  {
    productSlug: AVENE_PRODUCT_SLUGS.AVENE_FLUIDE_ANTI_IMPERFECTION_SPF50,
    tagSlug: TAG_SLUGS.PROTECTION_SOLAIRE,
  },
  {
    productSlug: AVENE_PRODUCT_SLUGS.AVENE_FLUIDE_ANTI_IMPERFECTION_SPF50,
    tagSlug: TAG_SLUGS.SOLAIRE_VISAGE,
  },
  {
    productSlug: AVENE_PRODUCT_SLUGS.AVENE_FLUIDE_ANTI_IMPERFECTION_SPF50,
    tagSlug: TAG_SLUGS.ANTI_ACNE,
  },
  {
    productSlug: AVENE_PRODUCT_SLUGS.AVENE_FLUIDE_ANTI_IMPERFECTION_SPF50,
    tagSlug: TAG_SLUGS.POST_ACNE,
  },
  {
    productSlug: AVENE_PRODUCT_SLUGS.AVENE_FLUIDE_ANTI_IMPERFECTION_SPF50,
    tagSlug: TAG_SLUGS.PEAU_SENSIBLE,
  },

  // SunsiMed KA SPF50+
  {
    productSlug: AVENE_PRODUCT_SLUGS.AVENE_SUNSIMED_KA_SPF50,
    tagSlug: TAG_SLUGS.PROTECTION_SOLAIRE,
  },
  { productSlug: AVENE_PRODUCT_SLUGS.AVENE_SUNSIMED_KA_SPF50, tagSlug: TAG_SLUGS.SOLAIRE_VISAGE },
  { productSlug: AVENE_PRODUCT_SLUGS.AVENE_SUNSIMED_KA_SPF50, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },

  // Crème Teintée Anti-Lumière Bleue SPF50+
  {
    productSlug: AVENE_PRODUCT_SLUGS.AVENE_TEINTEE_ANTI_LUMIERE_BLEUE_SPF50,
    tagSlug: TAG_SLUGS.PROTECTION_SOLAIRE,
  },
  {
    productSlug: AVENE_PRODUCT_SLUGS.AVENE_TEINTEE_ANTI_LUMIERE_BLEUE_SPF50,
    tagSlug: TAG_SLUGS.SOLAIRE_TEINTE,
  },
  {
    productSlug: AVENE_PRODUCT_SLUGS.AVENE_TEINTEE_ANTI_LUMIERE_BLEUE_SPF50,
    tagSlug: TAG_SLUGS.PROTECTION_LUMIERE_BLEUE,
  },
  {
    productSlug: AVENE_PRODUCT_SLUGS.AVENE_TEINTEE_ANTI_LUMIERE_BLEUE_SPF50,
    tagSlug: TAG_SLUGS.PEAU_SENSIBLE,
  },

  // Ultra Fluid Oil Control SPF50
  {
    productSlug: AVENE_PRODUCT_SLUGS.AVENE_ULTRA_FLUID_OIL_CONTROL_SPF50,
    tagSlug: TAG_SLUGS.PROTECTION_SOLAIRE,
  },
  {
    productSlug: AVENE_PRODUCT_SLUGS.AVENE_ULTRA_FLUID_OIL_CONTROL_SPF50,
    tagSlug: TAG_SLUGS.SOLAIRE_VISAGE,
  },
  {
    productSlug: AVENE_PRODUCT_SLUGS.AVENE_ULTRA_FLUID_OIL_CONTROL_SPF50,
    tagSlug: TAG_SLUGS.PEAU_GRASSE,
  },
  {
    productSlug: AVENE_PRODUCT_SLUGS.AVENE_ULTRA_FLUID_OIL_CONTROL_SPF50,
    tagSlug: TAG_SLUGS.BRILLANCE,
  },
  {
    productSlug: AVENE_PRODUCT_SLUGS.AVENE_ULTRA_FLUID_OIL_CONTROL_SPF50,
    tagSlug: TAG_SLUGS.SEBO_REGULATEUR,
  },

  // Tolérance Control Crème
  {
    productSlug: AVENE_PRODUCT_SLUGS.AVENE_TOLERANCE_CONTROL_CREME,
    tagSlug: TAG_SLUGS.PEAU_SENSIBLE,
  },
  {
    productSlug: AVENE_PRODUCT_SLUGS.AVENE_TOLERANCE_CONTROL_CREME,
    tagSlug: TAG_SLUGS.PEAU_REACTIVE,
  },
  {
    productSlug: AVENE_PRODUCT_SLUGS.AVENE_TOLERANCE_CONTROL_CREME,
    tagSlug: TAG_SLUGS.BARRIERE_CUTANEE,
  },
  {
    productSlug: AVENE_PRODUCT_SLUGS.AVENE_TOLERANCE_CONTROL_CREME,
    tagSlug: TAG_SLUGS.CREME_HYDRATANTE,
  },

  // XeraCalm A.D Baume Relipidant
  { productSlug: AVENE_PRODUCT_SLUGS.AVENE_XERACALM_AD_BAUME, tagSlug: TAG_SLUGS.PEAU_ATOPIQUE },
  { productSlug: AVENE_PRODUCT_SLUGS.AVENE_XERACALM_AD_BAUME, tagSlug: TAG_SLUGS.PEAU_SECHE },
  { productSlug: AVENE_PRODUCT_SLUGS.AVENE_XERACALM_AD_BAUME, tagSlug: TAG_SLUGS.CREME_HYDRATANTE },
  { productSlug: AVENE_PRODUCT_SLUGS.AVENE_XERACALM_AD_BAUME, tagSlug: TAG_SLUGS.OCCLUSIF },
  { productSlug: AVENE_PRODUCT_SLUGS.AVENE_XERACALM_AD_BAUME, tagSlug: TAG_SLUGS.REPARATEUR },

  // Antirougeurs Rosamed
  { productSlug: AVENE_PRODUCT_SLUGS.AVENE_ROSAMED, tagSlug: TAG_SLUGS.ANTI_ROUGEURS },
  { productSlug: AVENE_PRODUCT_SLUGS.AVENE_ROSAMED, tagSlug: TAG_SLUGS.ROSACEE },
  { productSlug: AVENE_PRODUCT_SLUGS.AVENE_ROSAMED, tagSlug: TAG_SLUGS.COUPEROSE },
  { productSlug: AVENE_PRODUCT_SLUGS.AVENE_ROSAMED, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },
  { productSlug: AVENE_PRODUCT_SLUGS.AVENE_ROSAMED, tagSlug: TAG_SLUGS.SANS_PARFUM },
]
