import { TAG_SLUGS } from '../../tags/seed-tags'
import { AVENE_PRODUCT_SLUGS } from './avene'

interface ProductTagGroups {
  primary: string[] // Pathologies, cibles principales, types de peau
  secondary: string[] // Bénéfices secondaires, textures, catégories, actifs
  avoid: string[] // Tags à exclure
}

export const AVENE_PRODUCT_TAGS: Record<string, ProductTagGroups> = {
  // ─── Cleanance ────────────────────────────────────────────────────────────

  [AVENE_PRODUCT_SLUGS.AVENE_CLEANANCE_COMEDOMED_SERUM_INTENSIF]: {
    primary: [
      TAG_SLUGS.ANTI_ACNE,
      TAG_SLUGS.POST_ACNE,
      TAG_SLUGS.HYPERPIGMENTATION,
      TAG_SLUGS.PEAU_GRASSE,
      TAG_SLUGS.PEAU_MIXTE,
    ],
    secondary: [
      TAG_SLUGS.PORES_DILATES,
      TAG_SLUGS.SERUM,
      TAG_SLUGS.SOIN_DE_JOUR,
      TAG_SLUGS.SOIN_DE_NUIT,
      TAG_SLUGS.KERATOLYTIQUE,
      TAG_SLUGS.SEBO_REGULATEUR,
      TAG_SLUGS.ANTI_OXYDANT,
    ],
    avoid: [
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.PEAU_REACTIVE,
      TAG_SLUGS.ROSACEE,
      TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE,
      TAG_SLUGS.GROSSESSE_COMPATIBLE,
    ],
  },
  [AVENE_PRODUCT_SLUGS.AVENE_CLEANANCE_COMEDOMED_SOIN_INTENSIF_ANTI_IMPERFECTION]: {
    primary: [TAG_SLUGS.ANTI_ACNE, TAG_SLUGS.SEBO_REGULATEUR],
    secondary: [
      TAG_SLUGS.PEAU_GRASSE,
      TAG_SLUGS.PEAU_MIXTE,
      TAG_SLUGS.NON_COMEDOGENE,
      TAG_SLUGS.MATIFIANT,
      TAG_SLUGS.SOIN_DE_JOUR,
      TAG_SLUGS.SOIN_DE_NUIT,
      TAG_SLUGS.TEXTURE_LEGERE,
    ],
    avoid: [],
  },

  [AVENE_PRODUCT_SLUGS.AVENE_CLEANANCE_GEL_NETTOYANT]: {
    primary: [TAG_SLUGS.PEAU_GRASSE, TAG_SLUGS.PEAU_MIXTE, TAG_SLUGS.ANTI_ACNE],
    secondary: [
      TAG_SLUGS.NETTOYANT,
      TAG_SLUGS.PORES_DILATES,
      TAG_SLUGS.BRILLANCE,
      TAG_SLUGS.SEBO_REGULATEUR,
      TAG_SLUGS.MATIFIANT,
      TAG_SLUGS.SANS_SAVON,
    ],
    avoid: [
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.PEAU_ATOPIQUE,
      TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE,
      TAG_SLUGS.GROSSESSE_COMPATIBLE,
    ],
  },

  // [AVENE_PRODUCT_SLUGS.AVENE_CLEANANCE_HYDRA_CREME]: {
  //   primary: [TAG_SLUGS.ANTI_ACNE, TAG_SLUGS.DESHYDRATATION, TAG_SLUGS.PEAU_SENSIBLE],
  //   secondary: [
  //     TAG_SLUGS.BARRIERE_CUTANEE,
  //     TAG_SLUGS.POST_ACNE,
  //     TAG_SLUGS.PEAU_GRASSE,
  //     TAG_SLUGS.PEAU_MIXTE,
  //     TAG_SLUGS.SOIN_DE_JOUR,
  //     TAG_SLUGS.CREME_HYDRATANTE,
  //     TAG_SLUGS.HUMECTANT,
  //     TAG_SLUGS.EMOLLIENT,
  //     TAG_SLUGS.APAISANT,
  //     TAG_SLUGS.NON_COMEDOGENE,
  //   ],
  //   avoid: [TAG_SLUGS.PEAU_SECHE, TAG_SLUGS.GROSSESSE_COMPATIBLE],
  // },

  [AVENE_PRODUCT_SLUGS.AVENE_CLEANANCE_SPF50]: {
    primary: [
      TAG_SLUGS.PROTECTION_SOLAIRE,
      TAG_SLUGS.ANTI_ACNE,
      TAG_SLUGS.PEAU_GRASSE,
      TAG_SLUGS.PEAU_MIXTE,
    ],
    secondary: [
      TAG_SLUGS.SOLAIRE_VISAGE,
      TAG_SLUGS.PHOTO_VIEILLISSEMENT,
      TAG_SLUGS.POST_ACNE,
      TAG_SLUGS.PORES_DILATES,
      TAG_SLUGS.BRILLANCE,
      TAG_SLUGS.SOIN_DE_JOUR,
      TAG_SLUGS.SEBO_REGULATEUR,
      TAG_SLUGS.MATIFIANT,
      TAG_SLUGS.FILTRES_CHIMIQUES,
      TAG_SLUGS.NON_COMEDOGENE,
    ],
    avoid: [
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.ROSACEE,
      TAG_SLUGS.FILTRES_MINERAUX,
      TAG_SLUGS.GROSSESSE_COMPATIBLE,
    ],
  },

  [AVENE_PRODUCT_SLUGS.AVENE_FLUIDE_ANTI_IMPERFECTION_SPF50]: {
    primary: [
      TAG_SLUGS.PROTECTION_SOLAIRE,
      TAG_SLUGS.ANTI_ACNE,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.PEAU_GRASSE,
      TAG_SLUGS.PEAU_MIXTE,
    ],
    secondary: [
      TAG_SLUGS.SOLAIRE_VISAGE,
      TAG_SLUGS.PHOTO_VIEILLISSEMENT,
      TAG_SLUGS.LUMIERE_BLEUE,
      TAG_SLUGS.POST_ACNE,
      TAG_SLUGS.PORES_DILATES,
      TAG_SLUGS.SOIN_DE_JOUR,
      TAG_SLUGS.SEBO_REGULATEUR,
      TAG_SLUGS.MATIFIANT,
      TAG_SLUGS.FILTRES_CHIMIQUES,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.NON_COMEDOGENE,
    ],
    avoid: [
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.ROSACEE,
      TAG_SLUGS.FILTRES_MINERAUX,
      TAG_SLUGS.GROSSESSE_COMPATIBLE,
    ],
  },

  // ─── XeraCalm A.D ─────────────────────────────────────────────────────────

  [AVENE_PRODUCT_SLUGS.AVENE_XERACALM_AD_CREME_RELIPIDANTE]: {
    primary: [
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.PEAU_ATOPIQUE,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.ECZEMA,
    ],
    secondary: [
      TAG_SLUGS.BARRIERE_CUTANEE,
      TAG_SLUGS.CREME_HYDRATANTE,
      TAG_SLUGS.SOIN_DE_JOUR,
      TAG_SLUGS.SOIN_DE_NUIT,
      TAG_SLUGS.REPARATEUR,
      TAG_SLUGS.EMOLLIENT,
      TAG_SLUGS.OCCLUSIF,
      TAG_SLUGS.HUMECTANT,
      TAG_SLUGS.APAISANT,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.NON_COMEDOGENE,
      TAG_SLUGS.GROSSESSE_COMPATIBLE,
    ],
    avoid: [TAG_SLUGS.PEAU_GRASSE, TAG_SLUGS.PEAU_MIXTE, TAG_SLUGS.ANTI_ACNE, TAG_SLUGS.BRILLANCE],
  },

  [AVENE_PRODUCT_SLUGS.AVENE_XERACALM_AD_BAUME]: {
    primary: [
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.PEAU_ATOPIQUE,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.ECZEMA,
    ],
    secondary: [
      TAG_SLUGS.BARRIERE_CUTANEE,
      TAG_SLUGS.CREME_HYDRATANTE,
      TAG_SLUGS.SOIN_DE_JOUR,
      TAG_SLUGS.SOIN_DE_NUIT,
      TAG_SLUGS.REPARATEUR,
      TAG_SLUGS.EMOLLIENT,
      TAG_SLUGS.OCCLUSIF,
      TAG_SLUGS.TEXTURE_RICHE,
      TAG_SLUGS.APAISANT,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.NON_COMEDOGENE,
      TAG_SLUGS.GROSSESSE_COMPATIBLE,
    ],
    avoid: [TAG_SLUGS.PEAU_GRASSE, TAG_SLUGS.PEAU_MIXTE, TAG_SLUGS.ANTI_ACNE, TAG_SLUGS.BRILLANCE],
  },

  [AVENE_PRODUCT_SLUGS.AVENE_XERACALM_HUILE_LAVANTE]: {
    primary: [
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.PEAU_ATOPIQUE,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.ECZEMA,
    ],
    secondary: [
      TAG_SLUGS.NETTOYANT,
      TAG_SLUGS.HUILE,
      TAG_SLUGS.BARRIERE_CUTANEE,
      TAG_SLUGS.EMOLLIENT,
      TAG_SLUGS.MICROBIOME,
      TAG_SLUGS.APAISANT,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.SANS_SAVON,
      TAG_SLUGS.NON_COMEDOGENE,
      TAG_SLUGS.GROSSESSE_COMPATIBLE,
    ],
    avoid: [TAG_SLUGS.PEAU_GRASSE, TAG_SLUGS.PEAU_MIXTE, TAG_SLUGS.ANTI_ACNE],
  },

  [AVENE_PRODUCT_SLUGS.AVENE_XERACALM_NUTRITION_BAUME]: {
    primary: [TAG_SLUGS.PEAU_SECHE, TAG_SLUGS.PEAU_SENSIBLE],
    secondary: [
      TAG_SLUGS.BARRIERE_CUTANEE,
      TAG_SLUGS.EMOLLIENT,
      TAG_SLUGS.OCCLUSIF,
      TAG_SLUGS.TEXTURE_RICHE,
      TAG_SLUGS.APAISANT,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.NON_COMEDOGENE,
      TAG_SLUGS.GROSSESSE_COMPATIBLE,
    ],
    avoid: [TAG_SLUGS.PEAU_GRASSE, TAG_SLUGS.PEAU_MIXTE, TAG_SLUGS.ANTI_ACNE, TAG_SLUGS.BRILLANCE],
  },

  // ─── Hydrance ─────────────────────────────────────────────────────────────

  [AVENE_PRODUCT_SLUGS.AVENE_HYDRANCE_RICHE_CREME_HYDRATANTE]: {
    primary: [TAG_SLUGS.PEAU_SECHE, TAG_SLUGS.PEAU_SENSIBLE, TAG_SLUGS.DESHYDRATATION],
    secondary: [
      TAG_SLUGS.PEAU_NORMALE,
      TAG_SLUGS.BARRIERE_CUTANEE,
      TAG_SLUGS.SOIN_DE_JOUR,
      TAG_SLUGS.SOIN_DE_NUIT,
      TAG_SLUGS.CREME_HYDRATANTE,
      TAG_SLUGS.HUMECTANT,
      TAG_SLUGS.EMOLLIENT,
      TAG_SLUGS.TEXTURE_RICHE,
      TAG_SLUGS.APAISANT,
    ],
    avoid: [TAG_SLUGS.PEAU_GRASSE, TAG_SLUGS.PEAU_MIXTE, TAG_SLUGS.BRILLANCE, TAG_SLUGS.ANTI_ACNE],
  },

  [AVENE_PRODUCT_SLUGS.AVENE_HYDRANCE_LIGHT_CREME_HYDRATANTE]: {
    primary: [TAG_SLUGS.PEAU_NORMALE, TAG_SLUGS.PEAU_MIXTE, TAG_SLUGS.DESHYDRATATION],
    secondary: [
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.BARRIERE_CUTANEE,
      TAG_SLUGS.SOIN_DE_JOUR,
      TAG_SLUGS.SOIN_DE_NUIT,
      TAG_SLUGS.CREME_HYDRATANTE,
      TAG_SLUGS.HUMECTANT,
      TAG_SLUGS.EMOLLIENT,
      TAG_SLUGS.TEXTURE_LEGERE,
      TAG_SLUGS.APAISANT,
    ],
    avoid: [TAG_SLUGS.PEAU_SECHE, TAG_SLUGS.ANTI_ACNE, TAG_SLUGS.BRILLANCE],
  },

  [AVENE_PRODUCT_SLUGS.AVENE_HYDRANCE_BOOST_SERUM]: {
    primary: [TAG_SLUGS.DESHYDRATATION, TAG_SLUGS.PEAU_SENSIBLE],
    secondary: [
      TAG_SLUGS.REPULPANT,
      TAG_SLUGS.BARRIERE_CUTANEE,
      TAG_SLUGS.PEAU_NORMALE,
      TAG_SLUGS.PEAU_MIXTE,
      TAG_SLUGS.SERUM,
      TAG_SLUGS.SOIN_DE_JOUR,
      TAG_SLUGS.SOIN_DE_NUIT,
      TAG_SLUGS.HUMECTANT,
      TAG_SLUGS.APAISANT,
      TAG_SLUGS.TEXTURE_LEGERE,
    ],
    avoid: [TAG_SLUGS.ANTI_ACNE, TAG_SLUGS.EXFOLIANT],
  },

  // ─── Cicalfate ────────────────────────────────────────────────────────────

  [AVENE_PRODUCT_SLUGS.AVENE_CICALFATE_CREME_REPARATRICE]: {
    primary: [
      TAG_SLUGS.REPARATEUR,
      TAG_SLUGS.CICATRISATION,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.PEAU_ATOPIQUE,
    ],
    secondary: [
      TAG_SLUGS.BARRIERE_CUTANEE,
      TAG_SLUGS.ANTI_ROUGEURS,
      TAG_SLUGS.POST_ACNE,
      TAG_SLUGS.SOIN_DE_JOUR,
      TAG_SLUGS.SOIN_DE_NUIT,
      TAG_SLUGS.CREME_HYDRATANTE,
      TAG_SLUGS.HUMECTANT,
      TAG_SLUGS.EMOLLIENT,
      TAG_SLUGS.OCCLUSIF,
      TAG_SLUGS.ANTISEPTIQUE,
      TAG_SLUGS.APAISANT,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.NON_COMEDOGENE,
      TAG_SLUGS.GROSSESSE_COMPATIBLE,
    ],
    avoid: [TAG_SLUGS.ANTI_ACNE, TAG_SLUGS.EXFOLIANT],
  },

  // ─── Hyaluron Activ B3 ────────────────────────────────────────────────────

  [AVENE_PRODUCT_SLUGS.AVENE_HYALURON_ACTIV_B3_CREME_REGENERATION]: {
    primary: [
      TAG_SLUGS.ANTI_AGE,
      TAG_SLUGS.DESHYDRATATION,
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.PEAU_SENSIBLE,
    ],
    secondary: [
      TAG_SLUGS.REPULPANT,
      TAG_SLUGS.ECLAT,
      TAG_SLUGS.PEAU_NORMALE,
      TAG_SLUGS.SOIN_DE_JOUR,
      TAG_SLUGS.SOIN_DE_NUIT,
      TAG_SLUGS.CREME_HYDRATANTE,
      TAG_SLUGS.HUMECTANT,
      TAG_SLUGS.EMOLLIENT,
      TAG_SLUGS.ANTI_OXYDANT,
    ],
    avoid: [TAG_SLUGS.PEAU_GRASSE, TAG_SLUGS.BRILLANCE, TAG_SLUGS.ANTI_ACNE],
  },

  [AVENE_PRODUCT_SLUGS.AVENE_HYALURON_ACTIV_B3_SERUM]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.DESHYDRATATION, TAG_SLUGS.PEAU_SENSIBLE],
    secondary: [
      TAG_SLUGS.REPULPANT,
      TAG_SLUGS.ECLAT,
      TAG_SLUGS.PEAU_NORMALE,
      TAG_SLUGS.PEAU_MIXTE,
      TAG_SLUGS.SERUM,
      TAG_SLUGS.SOIN_DE_JOUR,
      TAG_SLUGS.SOIN_DE_NUIT,
      TAG_SLUGS.HUMECTANT,
      TAG_SLUGS.ANTI_OXYDANT,
      TAG_SLUGS.TEXTURE_LEGERE,
    ],
    avoid: [TAG_SLUGS.ANTI_ACNE],
  },

  // ─── Hyaluron Activ Procedure ─────────────────────────────────────────────

  [AVENE_PRODUCT_SLUGS.AVENE_HYALURON_ACTIV_PROCEDURE_CREME_LIFTING_0_1_RETINAL]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.PHOTO_VIEILLISSEMENT, TAG_SLUGS.PEAU_SENSIBLE],
    secondary: [
      TAG_SLUGS.REPULPANT,
      TAG_SLUGS.DESHYDRATATION,
      TAG_SLUGS.ECLAT,
      TAG_SLUGS.PORES_DILATES,
      TAG_SLUGS.PEAU_NORMALE,
      TAG_SLUGS.SOIN_DE_JOUR,
      TAG_SLUGS.SOIN_DE_NUIT,
      TAG_SLUGS.CREME_HYDRATANTE,
      TAG_SLUGS.HUMECTANT,
      TAG_SLUGS.EMOLLIENT,
      TAG_SLUGS.KERATOLYTIQUE,
      TAG_SLUGS.ANTI_OXYDANT,
    ],
    avoid: [
      TAG_SLUGS.PEAU_REACTIVE,
      TAG_SLUGS.ROSACEE,
      TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE,
      TAG_SLUGS.GROSSESSE_COMPATIBLE,
    ],
  },

  [AVENE_PRODUCT_SLUGS.AVENE_HYALURON_ACTIV_PROCEDURE_SERUM_TENSEUR]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.DESHYDRATATION, TAG_SLUGS.PEAU_SENSIBLE],
    secondary: [
      TAG_SLUGS.REPULPANT,
      TAG_SLUGS.ECLAT,
      TAG_SLUGS.PEAU_NORMALE,
      TAG_SLUGS.SERUM,
      TAG_SLUGS.SOIN_DE_JOUR,
      TAG_SLUGS.SOIN_DE_NUIT,
      TAG_SLUGS.HUMECTANT,
      TAG_SLUGS.ANTI_OXYDANT,
    ],
    avoid: [
      TAG_SLUGS.PEAU_REACTIVE,
      TAG_SLUGS.ROSACEE,
      TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE,
      TAG_SLUGS.GROSSESSE_COMPATIBLE,
    ],
  },

  [AVENE_PRODUCT_SLUGS.AVENE_HYALURON_ACTIV_PROCEDURE_CREME_MICRO_LIFT_YEUX_LEVRES]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.CERNES_POCHES, TAG_SLUGS.PEAU_SENSIBLE],
    secondary: [
      TAG_SLUGS.REPULPANT,
      TAG_SLUGS.CONTOUR_YEUX,
      TAG_SLUGS.HUMECTANT,
      TAG_SLUGS.ANTI_OXYDANT,
    ],
    avoid: [TAG_SLUGS.GROSSESSE_COMPATIBLE],
  },

  // ─── Vitamin Activ C ──────────────────────────────────────────────────────

  [AVENE_PRODUCT_SLUGS.AVENE_VITAMIN_ACTIV_C_SERUM_ECLAT]: {
    primary: [
      TAG_SLUGS.ECLAT,
      TAG_SLUGS.TEINT_TERNE,
      TAG_SLUGS.ANTI_TACHES,
      TAG_SLUGS.HYPERPIGMENTATION,
      TAG_SLUGS.PEAU_SENSIBLE,
    ],
    secondary: [
      TAG_SLUGS.POST_ACNE,
      TAG_SLUGS.ANTI_AGE,
      TAG_SLUGS.PHOTO_VIEILLISSEMENT,
      TAG_SLUGS.PEAU_NORMALE,
      TAG_SLUGS.PEAU_MIXTE,
      TAG_SLUGS.SERUM,
      TAG_SLUGS.SOIN_DE_JOUR,
      TAG_SLUGS.ANTI_OXYDANT,
      TAG_SLUGS.HUMECTANT,
    ],
    avoid: [TAG_SLUGS.PEAU_REACTIVE, TAG_SLUGS.ROSACEE, TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE],
  },

  // ─── Tolérance Control ────────────────────────────────────────────────────

  [AVENE_PRODUCT_SLUGS.AVENE_TOLERANCE_CONTROL_CREME]: {
    primary: [TAG_SLUGS.PEAU_SENSIBLE, TAG_SLUGS.PEAU_REACTIVE, TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE],
    secondary: [
      TAG_SLUGS.BARRIERE_CUTANEE,
      TAG_SLUGS.PEAU_NORMALE,
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.SOIN_DE_JOUR,
      TAG_SLUGS.SOIN_DE_NUIT,
      TAG_SLUGS.CREME_HYDRATANTE,
      TAG_SLUGS.HUMECTANT,
      TAG_SLUGS.EMOLLIENT,
      TAG_SLUGS.OCCLUSIF,
      TAG_SLUGS.APAISANT,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.HYPOALLERGENIQUE,
      TAG_SLUGS.NON_COMEDOGENE,
      TAG_SLUGS.GROSSESSE_COMPATIBLE,
    ],
    avoid: [TAG_SLUGS.PEAU_GRASSE, TAG_SLUGS.ANTI_ACNE, TAG_SLUGS.BRILLANCE],
  },

  [AVENE_PRODUCT_SLUGS.AVENE_TOLERANCE_CONTROL_BAUME]: {
    primary: [
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.PEAU_REACTIVE,
      TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE,
      TAG_SLUGS.PEAU_SECHE,
    ],
    secondary: [
      TAG_SLUGS.BARRIERE_CUTANEE,
      TAG_SLUGS.SOIN_DE_JOUR,
      TAG_SLUGS.SOIN_DE_NUIT,
      TAG_SLUGS.CREME_HYDRATANTE,
      TAG_SLUGS.EMOLLIENT,
      TAG_SLUGS.OCCLUSIF,
      TAG_SLUGS.TEXTURE_RICHE,
      TAG_SLUGS.APAISANT,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.HYPOALLERGENIQUE,
      TAG_SLUGS.NON_COMEDOGENE,
      TAG_SLUGS.GROSSESSE_COMPATIBLE,
    ],
    avoid: [TAG_SLUGS.PEAU_GRASSE, TAG_SLUGS.PEAU_MIXTE, TAG_SLUGS.ANTI_ACNE, TAG_SLUGS.BRILLANCE],
  },

  // ─── Antirougeurs ─────────────────────────────────────────────────────────

  [AVENE_PRODUCT_SLUGS.AVENE_ROSAMED]: {
    primary: [
      TAG_SLUGS.ANTI_ROUGEURS,
      TAG_SLUGS.ROSACEE,
      TAG_SLUGS.COUPEROSE,
      TAG_SLUGS.FLUSHS,
      TAG_SLUGS.PEAU_SENSIBLE,
    ],
    secondary: [
      TAG_SLUGS.PEAU_REACTIVE,
      TAG_SLUGS.SERUM,
      TAG_SLUGS.SOIN_DE_JOUR,
      TAG_SLUGS.SOIN_DE_NUIT,
      TAG_SLUGS.HUMECTANT,
      TAG_SLUGS.APAISANT,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.NON_COMEDOGENE,
    ],
    avoid: [TAG_SLUGS.ANTI_ACNE, TAG_SLUGS.EXFOLIANT, TAG_SLUGS.KERATOLYTIQUE],
  },

  // ─── Eau thermale ─────────────────────────────────────────────────────────

  [AVENE_PRODUCT_SLUGS.AVENE_THERMAL_SPRING_WATER]: {
    primary: [TAG_SLUGS.PEAU_SENSIBLE, TAG_SLUGS.PEAU_REACTIVE, TAG_SLUGS.ANTI_ROUGEURS],
    secondary: [
      TAG_SLUGS.APAISANT,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.HYPOALLERGENIQUE,
      TAG_SLUGS.GROSSESSE_COMPATIBLE,
    ],
    avoid: [],
  },

  // ─── Solaires ─────────────────────────────────────────────────────────────

  [AVENE_PRODUCT_SLUGS.AVENE_SUNSIMED_KA_SPF50]: {
    primary: [TAG_SLUGS.PROTECTION_SOLAIRE, TAG_SLUGS.PEAU_SENSIBLE, TAG_SLUGS.PEAU_REACTIVE],
    secondary: [
      TAG_SLUGS.SOLAIRE_VISAGE,
      TAG_SLUGS.PHOTO_VIEILLISSEMENT,
      TAG_SLUGS.SOIN_DE_JOUR,
      TAG_SLUGS.FILTRES_CHIMIQUES,
      TAG_SLUGS.APAISANT,
      TAG_SLUGS.NON_COMEDOGENE,
    ],
    avoid: [TAG_SLUGS.FILTRES_MINERAUX, TAG_SLUGS.GROSSESSE_COMPATIBLE],
  },

  [AVENE_PRODUCT_SLUGS.AVENE_TEINTEE_ANTI_LUMIERE_BLEUE_SPF50]: {
    primary: [TAG_SLUGS.PROTECTION_SOLAIRE, TAG_SLUGS.PEAU_SENSIBLE, TAG_SLUGS.PEAU_NORMALE],
    secondary: [
      TAG_SLUGS.SOLAIRE_VISAGE,
      TAG_SLUGS.SOLAIRE_TEINTE,
      TAG_SLUGS.PHOTO_VIEILLISSEMENT,
      TAG_SLUGS.LUMIERE_BLEUE,
      TAG_SLUGS.POLLUTION,
      TAG_SLUGS.PROTECTION_LUMIERE_BLEUE,
      TAG_SLUGS.SOIN_DE_JOUR,
      TAG_SLUGS.ECLAT,
      TAG_SLUGS.FILTRES_CHIMIQUES,
      TAG_SLUGS.FILTRES_MINERAUX,
      TAG_SLUGS.APAISANT,
    ],
    avoid: [TAG_SLUGS.PEAU_GRASSE, TAG_SLUGS.BRILLANCE, TAG_SLUGS.GROSSESSE_COMPATIBLE],
  },

  [AVENE_PRODUCT_SLUGS.AVENE_ULTRA_FLUID_OIL_CONTROL_SPF50]: {
    primary: [TAG_SLUGS.PROTECTION_SOLAIRE, TAG_SLUGS.PEAU_GRASSE, TAG_SLUGS.PEAU_MIXTE],
    secondary: [
      TAG_SLUGS.SOLAIRE_VISAGE,
      TAG_SLUGS.PHOTO_VIEILLISSEMENT,
      TAG_SLUGS.BRILLANCE,
      TAG_SLUGS.PORES_DILATES,
      TAG_SLUGS.SOIN_DE_JOUR,
      TAG_SLUGS.SEBO_REGULATEUR,
      TAG_SLUGS.MATIFIANT,
      TAG_SLUGS.FILTRES_CHIMIQUES,
      TAG_SLUGS.NON_COMEDOGENE,
    ],
    avoid: [
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.ROSACEE,
      TAG_SLUGS.FILTRES_MINERAUX,
      TAG_SLUGS.GROSSESSE_COMPATIBLE,
    ],
  },

  [AVENE_PRODUCT_SLUGS.AVENE_ULTRA_FLUID_ECLAT_RADIANCE_SPF50]: {
    primary: [
      TAG_SLUGS.PROTECTION_SOLAIRE,
      TAG_SLUGS.ECLAT,
      TAG_SLUGS.TEINT_TERNE,
      TAG_SLUGS.PEAU_NORMALE,
      TAG_SLUGS.PEAU_MIXTE,
    ],
    secondary: [
      TAG_SLUGS.SOLAIRE_VISAGE,
      TAG_SLUGS.PHOTO_VIEILLISSEMENT,
      TAG_SLUGS.SOIN_DE_JOUR,
      TAG_SLUGS.FILTRES_CHIMIQUES,
      TAG_SLUGS.ANTI_OXYDANT,
      TAG_SLUGS.NON_COMEDOGENE,
    ],
    avoid: [
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.ROSACEE,
      TAG_SLUGS.FILTRES_MINERAUX,
      TAG_SLUGS.GROSSESSE_COMPATIBLE,
    ],
  },

  [AVENE_PRODUCT_SLUGS.AVENE_ULTRA_FLUID_PERFECTEUR_SPF50]: {
    primary: [
      TAG_SLUGS.PROTECTION_SOLAIRE,
      TAG_SLUGS.ANTI_TACHES,
      TAG_SLUGS.PEAU_NORMALE,
      TAG_SLUGS.PEAU_MIXTE,
    ],
    secondary: [
      TAG_SLUGS.SOLAIRE_VISAGE,
      TAG_SLUGS.SOLAIRE_TEINTE,
      TAG_SLUGS.PHOTO_VIEILLISSEMENT,
      TAG_SLUGS.LUMIERE_BLEUE,
      TAG_SLUGS.SOIN_DE_JOUR,
      TAG_SLUGS.MATIFIANT,
      TAG_SLUGS.FILTRES_CHIMIQUES,
      TAG_SLUGS.FILTRES_MINERAUX,
      TAG_SLUGS.NON_COMEDOGENE,
    ],
    avoid: [TAG_SLUGS.PEAU_SECHE, TAG_SLUGS.ROSACEE, TAG_SLUGS.GROSSESSE_COMPATIBLE],
  },

  [AVENE_PRODUCT_SLUGS.AVENE_ULTRA_FLUID_INVISIBLE_SPF50]: {
    primary: [
      TAG_SLUGS.PROTECTION_SOLAIRE,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.PEAU_NORMALE,
      TAG_SLUGS.PEAU_MIXTE,
    ],
    secondary: [
      TAG_SLUGS.SOLAIRE_VISAGE,
      TAG_SLUGS.PHOTO_VIEILLISSEMENT,
      TAG_SLUGS.SOIN_DE_JOUR,
      TAG_SLUGS.FILTRES_CHIMIQUES,
      TAG_SLUGS.TEXTURE_LEGERE,
      TAG_SLUGS.NON_COMEDOGENE,
    ],
    avoid: [TAG_SLUGS.PEAU_SECHE, TAG_SLUGS.FILTRES_MINERAUX, TAG_SLUGS.GROSSESSE_COMPATIBLE],
  },
}
