import { TAG_SLUGS } from '../../tags/seed-tags'
import { LRP_PRODUCT_SLUGS } from './laRochePosay'

export const LRP_PRODUCT_TAGS: { productSlug: string; tagSlug: string }[] = [
  // Anthelios XL Brume Solaire Invisible Corps SPF50+
  {
    productSlug: LRP_PRODUCT_SLUGS.ANTHELIOS_XL_BRUME_SPF50,
    tagSlug: TAG_SLUGS.PROTECTION_SOLAIRE,
  },
  { productSlug: LRP_PRODUCT_SLUGS.ANTHELIOS_XL_BRUME_SPF50, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },
  { productSlug: LRP_PRODUCT_SLUGS.ANTHELIOS_XL_BRUME_SPF50, tagSlug: TAG_SLUGS.PEAU_REACTIVE },
  { productSlug: LRP_PRODUCT_SLUGS.ANTHELIOS_XL_BRUME_SPF50, tagSlug: TAG_SLUGS.HYPOALLERGENIQUE },

  // Hyalu B5 Sérum
  { productSlug: LRP_PRODUCT_SLUGS.HYALU_B5_SERUM, tagSlug: TAG_SLUGS.DESHYDRATATION },
  { productSlug: LRP_PRODUCT_SLUGS.HYALU_B5_SERUM, tagSlug: TAG_SLUGS.ANTI_AGE },
  { productSlug: LRP_PRODUCT_SLUGS.HYALU_B5_SERUM, tagSlug: TAG_SLUGS.ECLAT },
  { productSlug: LRP_PRODUCT_SLUGS.HYALU_B5_SERUM, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },
  { productSlug: LRP_PRODUCT_SLUGS.HYALU_B5_SERUM, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },
  { productSlug: LRP_PRODUCT_SLUGS.HYALU_B5_SERUM, tagSlug: TAG_SLUGS.SERUM },
  { productSlug: LRP_PRODUCT_SLUGS.HYALU_B5_SERUM, tagSlug: TAG_SLUGS.HUMECTANT },

  // Effaclar Duo+M Soin Triple Correction Anti-Imperfections
  { productSlug: LRP_PRODUCT_SLUGS.EFFACLAR_DUO_M, tagSlug: TAG_SLUGS.ANTI_ACNE },
  { productSlug: LRP_PRODUCT_SLUGS.EFFACLAR_DUO_M, tagSlug: TAG_SLUGS.POST_ACNE },
  { productSlug: LRP_PRODUCT_SLUGS.EFFACLAR_DUO_M, tagSlug: TAG_SLUGS.PEAU_GRASSE },
  { productSlug: LRP_PRODUCT_SLUGS.EFFACLAR_DUO_M, tagSlug: TAG_SLUGS.BRILLANCE },
  { productSlug: LRP_PRODUCT_SLUGS.EFFACLAR_DUO_M, tagSlug: TAG_SLUGS.PORES_DILATES },
  { productSlug: LRP_PRODUCT_SLUGS.EFFACLAR_DUO_M, tagSlug: TAG_SLUGS.CREME_HYDRATANTE },
  { productSlug: LRP_PRODUCT_SLUGS.EFFACLAR_DUO_M, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },
  { productSlug: LRP_PRODUCT_SLUGS.EFFACLAR_DUO_M, tagSlug: TAG_SLUGS.NON_COMEDOGENE },

  // Cicaplast Baume B5+ Réparateur Apaisant SPF50
  { productSlug: LRP_PRODUCT_SLUGS.CICAPLAST_B5_SPF50, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },
  { productSlug: LRP_PRODUCT_SLUGS.CICAPLAST_B5_SPF50, tagSlug: TAG_SLUGS.REPARATEUR },
  { productSlug: LRP_PRODUCT_SLUGS.CICAPLAST_B5_SPF50, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },
  { productSlug: LRP_PRODUCT_SLUGS.CICAPLAST_B5_SPF50, tagSlug: TAG_SLUGS.PROTECTION_SOLAIRE },
  { productSlug: LRP_PRODUCT_SLUGS.CICAPLAST_B5_SPF50, tagSlug: TAG_SLUGS.PEAU_ATOPIQUE },
  { productSlug: LRP_PRODUCT_SLUGS.CICAPLAST_B5_SPF50, tagSlug: TAG_SLUGS.POST_ACNE },
  { productSlug: LRP_PRODUCT_SLUGS.CICAPLAST_B5_SPF50, tagSlug: TAG_SLUGS.CREME_HYDRATANTE },

  // Toleriane Rosaliac AR
  { productSlug: LRP_PRODUCT_SLUGS.ROSALIAC_AR, tagSlug: TAG_SLUGS.ANTI_ROUGEURS },
  { productSlug: LRP_PRODUCT_SLUGS.ROSALIAC_AR, tagSlug: TAG_SLUGS.ROSACEE },
  { productSlug: LRP_PRODUCT_SLUGS.ROSALIAC_AR, tagSlug: TAG_SLUGS.COUPEROSE },
  { productSlug: LRP_PRODUCT_SLUGS.ROSALIAC_AR, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },
  { productSlug: LRP_PRODUCT_SLUGS.ROSALIAC_AR, tagSlug: TAG_SLUGS.PEAU_REACTIVE },
  { productSlug: LRP_PRODUCT_SLUGS.ROSALIAC_AR, tagSlug: TAG_SLUGS.CREME_HYDRATANTE },
  { productSlug: LRP_PRODUCT_SLUGS.ROSALIAC_AR, tagSlug: TAG_SLUGS.SANS_PARFUM },
  { productSlug: LRP_PRODUCT_SLUGS.ROSALIAC_AR, tagSlug: TAG_SLUGS.HYPOALLERGENIQUE },
  { productSlug: LRP_PRODUCT_SLUGS.ROSALIAC_AR, tagSlug: TAG_SLUGS.PIGMENTS_VERTS },

  // Effaclar H Iso-Biome
  { productSlug: LRP_PRODUCT_SLUGS.EFFACLAR_H_ISO_BIOME, tagSlug: TAG_SLUGS.DESHYDRATATION },
  { productSlug: LRP_PRODUCT_SLUGS.EFFACLAR_H_ISO_BIOME, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },
  { productSlug: LRP_PRODUCT_SLUGS.EFFACLAR_H_ISO_BIOME, tagSlug: TAG_SLUGS.PEAU_GRASSE },
  { productSlug: LRP_PRODUCT_SLUGS.EFFACLAR_H_ISO_BIOME, tagSlug: TAG_SLUGS.ANTI_ACNE },
  { productSlug: LRP_PRODUCT_SLUGS.EFFACLAR_H_ISO_BIOME, tagSlug: TAG_SLUGS.CREME_HYDRATANTE },
  { productSlug: LRP_PRODUCT_SLUGS.EFFACLAR_H_ISO_BIOME, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },

  // Cicaplast Baume B5+
  { productSlug: LRP_PRODUCT_SLUGS.CICAPLAST_BAUME_B5_PLUS, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },
  { productSlug: LRP_PRODUCT_SLUGS.CICAPLAST_BAUME_B5_PLUS, tagSlug: TAG_SLUGS.REPARATEUR },
  { productSlug: LRP_PRODUCT_SLUGS.CICAPLAST_BAUME_B5_PLUS, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },
  { productSlug: LRP_PRODUCT_SLUGS.CICAPLAST_BAUME_B5_PLUS, tagSlug: TAG_SLUGS.PEAU_ATOPIQUE },
  { productSlug: LRP_PRODUCT_SLUGS.CICAPLAST_BAUME_B5_PLUS, tagSlug: TAG_SLUGS.CREME_HYDRATANTE },
  { productSlug: LRP_PRODUCT_SLUGS.CICAPLAST_BAUME_B5_PLUS, tagSlug: TAG_SLUGS.POST_ACNE },

  // Hyalu B5 Crème
  { productSlug: LRP_PRODUCT_SLUGS.HYALU_B5_CREME, tagSlug: TAG_SLUGS.DESHYDRATATION },
  { productSlug: LRP_PRODUCT_SLUGS.HYALU_B5_CREME, tagSlug: TAG_SLUGS.ANTI_AGE },
  { productSlug: LRP_PRODUCT_SLUGS.HYALU_B5_CREME, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },
  { productSlug: LRP_PRODUCT_SLUGS.HYALU_B5_CREME, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },
  { productSlug: LRP_PRODUCT_SLUGS.HYALU_B5_CREME, tagSlug: TAG_SLUGS.CREME_HYDRATANTE },

  // Effaclar Mat
  { productSlug: LRP_PRODUCT_SLUGS.EFFACLAR_MAT, tagSlug: TAG_SLUGS.BRILLANCE },
  { productSlug: LRP_PRODUCT_SLUGS.EFFACLAR_MAT, tagSlug: TAG_SLUGS.PORES_DILATES },
  { productSlug: LRP_PRODUCT_SLUGS.EFFACLAR_MAT, tagSlug: TAG_SLUGS.PEAU_GRASSE },
  { productSlug: LRP_PRODUCT_SLUGS.EFFACLAR_MAT, tagSlug: TAG_SLUGS.SEBO_REGULATEUR },
  { productSlug: LRP_PRODUCT_SLUGS.EFFACLAR_MAT, tagSlug: TAG_SLUGS.CREME_HYDRATANTE },
  { productSlug: LRP_PRODUCT_SLUGS.EFFACLAR_MAT, tagSlug: TAG_SLUGS.NON_COMEDOGENE },

  // Tolériane Sensitive Crème
  { productSlug: LRP_PRODUCT_SLUGS.TOLERIANE_SENSITIVE, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },
  { productSlug: LRP_PRODUCT_SLUGS.TOLERIANE_SENSITIVE, tagSlug: TAG_SLUGS.DESHYDRATATION },
  { productSlug: LRP_PRODUCT_SLUGS.TOLERIANE_SENSITIVE, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },
  { productSlug: LRP_PRODUCT_SLUGS.TOLERIANE_SENSITIVE, tagSlug: TAG_SLUGS.CREME_HYDRATANTE },
  { productSlug: LRP_PRODUCT_SLUGS.TOLERIANE_SENSITIVE, tagSlug: TAG_SLUGS.SANS_PARFUM },
  { productSlug: LRP_PRODUCT_SLUGS.TOLERIANE_SENSITIVE, tagSlug: TAG_SLUGS.HYPOALLERGENIQUE },

  // Pure Vitamin C12 Sérum
  { productSlug: LRP_PRODUCT_SLUGS.PURE_VITAMIN_C12, tagSlug: TAG_SLUGS.ECLAT },
  { productSlug: LRP_PRODUCT_SLUGS.PURE_VITAMIN_C12, tagSlug: TAG_SLUGS.ANTI_AGE },
  { productSlug: LRP_PRODUCT_SLUGS.PURE_VITAMIN_C12, tagSlug: TAG_SLUGS.ANTI_TACHES },
  { productSlug: LRP_PRODUCT_SLUGS.PURE_VITAMIN_C12, tagSlug: TAG_SLUGS.HYPERPIGMENTATION },
  { productSlug: LRP_PRODUCT_SLUGS.PURE_VITAMIN_C12, tagSlug: TAG_SLUGS.SERUM },
  { productSlug: LRP_PRODUCT_SLUGS.PURE_VITAMIN_C12, tagSlug: TAG_SLUGS.ANTI_OXYDANT },
  { productSlug: LRP_PRODUCT_SLUGS.PURE_VITAMIN_C12, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },

  // Lipikar Baume AP+M
  { productSlug: LRP_PRODUCT_SLUGS.LIPIKAR_BAUME_AP_M, tagSlug: TAG_SLUGS.PEAU_SECHE },
  { productSlug: LRP_PRODUCT_SLUGS.LIPIKAR_BAUME_AP_M, tagSlug: TAG_SLUGS.PEAU_ATOPIQUE },
  { productSlug: LRP_PRODUCT_SLUGS.LIPIKAR_BAUME_AP_M, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },
  { productSlug: LRP_PRODUCT_SLUGS.LIPIKAR_BAUME_AP_M, tagSlug: TAG_SLUGS.REPARATEUR },
  { productSlug: LRP_PRODUCT_SLUGS.LIPIKAR_BAUME_AP_M, tagSlug: TAG_SLUGS.CREME_HYDRATANTE },
  { productSlug: LRP_PRODUCT_SLUGS.LIPIKAR_BAUME_AP_M, tagSlug: TAG_SLUGS.SANS_PARFUM },

  // Effaclar Gel Nettoyant
  { productSlug: LRP_PRODUCT_SLUGS.EFFACLAR_GEL_NETTOYANT, tagSlug: TAG_SLUGS.NETTOYANT },
  { productSlug: LRP_PRODUCT_SLUGS.EFFACLAR_GEL_NETTOYANT, tagSlug: TAG_SLUGS.PEAU_GRASSE },
  { productSlug: LRP_PRODUCT_SLUGS.EFFACLAR_GEL_NETTOYANT, tagSlug: TAG_SLUGS.ANTI_ACNE },
  { productSlug: LRP_PRODUCT_SLUGS.EFFACLAR_GEL_NETTOYANT, tagSlug: TAG_SLUGS.BRILLANCE },
  { productSlug: LRP_PRODUCT_SLUGS.EFFACLAR_GEL_NETTOYANT, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },

  // Sérum Mela B3
  { productSlug: LRP_PRODUCT_SLUGS.SERUM_MELA_B3, tagSlug: TAG_SLUGS.ANTI_TACHES },
  { productSlug: LRP_PRODUCT_SLUGS.SERUM_MELA_B3, tagSlug: TAG_SLUGS.HYPERPIGMENTATION },
  { productSlug: LRP_PRODUCT_SLUGS.SERUM_MELA_B3, tagSlug: TAG_SLUGS.POST_ACNE },
  { productSlug: LRP_PRODUCT_SLUGS.SERUM_MELA_B3, tagSlug: TAG_SLUGS.ECLAT },
  { productSlug: LRP_PRODUCT_SLUGS.SERUM_MELA_B3, tagSlug: TAG_SLUGS.SERUM },
  { productSlug: LRP_PRODUCT_SLUGS.SERUM_MELA_B3, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },

  // Sérum Rétinol B3
  { productSlug: LRP_PRODUCT_SLUGS.SERUM_B3_RETINOL, tagSlug: TAG_SLUGS.ANTI_AGE },
  { productSlug: LRP_PRODUCT_SLUGS.SERUM_B3_RETINOL, tagSlug: TAG_SLUGS.ECLAT },
  { productSlug: LRP_PRODUCT_SLUGS.SERUM_B3_RETINOL, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },
  { productSlug: LRP_PRODUCT_SLUGS.SERUM_B3_RETINOL, tagSlug: TAG_SLUGS.SERUM },
  { productSlug: LRP_PRODUCT_SLUGS.SERUM_B3_RETINOL, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },
]
