export const LRP_PRODUCT_SLUGS = {
  ANTHELIOS_XL_BRUME_SPF50: 'la-roche-posay-anthelios-xl-brume-spf50',
  HYALU_B5_SERUM: 'la-roche-posay-hyalu-b5-serum',
  EFFACLAR_DUO_M: 'la-roche-posay-effaclar-duo-m',
  CICAPLAST_B5_SPF50: 'la-roche-posay-cicaplast-baume-b5-spf50',
  ROSALIAC_AR: 'la-roche-posay-toleriane-rosaliac-ar',
  EFFACLAR_H_ISO_BIOME: 'la-roche-posay-effaclar-h-iso-biome',
  CICAPLAST_BAUME_B5_PLUS: 'la-roche-posay-cicaplast-baume-b5-plus',
  HYALU_B5_CREME: 'la-roche-posay-hyalu-b5-cream',
  EFFACLAR_MAT: 'la-roche-posay-effaclar-mat',
  TOLERIANE_SENSITIVE: 'la-roche-posay-toleriane-sensitive',
  PURE_VITAMIN_C12: 'la-roche-posay-vitamin-c12-serum',
  LIPIKAR_HUILE_LAVANTE_AP_PLUS: 'la-roche-posay-lipikar-huile-lavante-ap-plus',
  LRP_LIPIKAR_LAIT: 'la-roche-posay-lipikar-lait',
  LIPIKAR_BAUME_AP_M: 'la-roche-posay-lipikar-baume-ap-m',
  EFFACLAR_GEL_NETTOYANT: 'la-roche-posay-effaclar-gel',
  SERUM_B3_RETINOL: 'serum-b3-retinol',
  SERUM_MELA_B3: 'serum-mela-b3',
}
export const LRP_PRODUCT_DATA = [
  {
    name: 'Lipikar Huile Lavante AP+',
    brand: 'La Roche-Posay',
    kind: 'skincare',
    unit: 'pump',
    slug: LRP_PRODUCT_SLUGS.LIPIKAR_HUILE_LAVANTE_AP_PLUS,
    totalAmount: 750,
    amountUnit: 'ml',
    priceCents: 2350,
    description:
      "Huile lavante relipidante anti-irritation et anti-grattage enrichie en Beurre de Karité. Conçue pour les peaux à tendance à l'eczéma atopique.",
    notes:
      "Note: 4.6/5. Contient de la Niacinamide pour apaiser les démangeaisons et de l'Aqua Posae Filiformis pour l'équilibre cutané. Convient dès la naissance.",
    inci: 'AQUA / WATER / EAU • GLYCERIN • SUCROSE • SODIUM LAURETH SULFATE • COCO-BETAINE • SODIUM CHLORIDE • CITRIC ACID • SODIUM HYDROXIDE • TRISODIUM ETHYLENEDIAMINE DISUCCINATE • VITREOSCILLA FERMENT • NIACINAMIDE • PEG-75 SHEA BUTTER GLYCERIDES • PENTYLENE GLYCOL • POLYSORBATE 20 • SODIUM BENZOATE • PARFUM / FRAGRANCE (F.I.L. N70019790/1).',
    url: 'https://www.laroche-posay.fr',
  },
  {
    name: 'Anthelios XL Brume Solaire Invisible Corps SPF50+',
    brand: 'La Roche-Posay',
    kind: 'sunscreen',
    unit: 'spray',
    slug: LRP_PRODUCT_SLUGS.ANTHELIOS_XL_BRUME_SPF50,
    totalAmount: 200,
    amountUnit: 'ml',
    priceCents: 1899,
    description:
      'Brume solaire corps SPF50+ très haute protection UVA/UVB. Convient aux peaux sensibles.',
    notes: 'Mexoryl XL. XL-Protect. Très résistante à l’eau. Fini invisible.',
    inci: 'BUTANE, AQUA/WATER, HOMOSALATE, DICAPRYLYL ETHER, OCTOCRYLENE, ETHYLHEXYL SALICYLATE, DIMETHICONE, STYRENE/ACRYLATES COPOLYMER, BUTYL METHOXYDIBENZOYLMETHANE, DROMETRIZOLE TRISILOXANE, PEG-30 DIPOLYHYDROXYSTEARATE, NYLON-12, DICAPRYLYL CARBONATE, METHYL METHACRYLATE CROSSPOLYMER, CYCLOHEXASILOXANE, POLYMETHYLSILSESQUIOXANE, P-ANISIC ACID, CAPRYLYL GLYCOL, DISODIUM EDTA, DISTEARDIMONIUM HECTORITE, DODECENE, ETHYLHEXYL TRIAZONE, ISODODECANE, LAURYL PEG/PPG-18/18 METHICONE, PEG-8 LAURATE, PHENOXYETHANOL, POLOXAMER 407, POLY C10-30 ALKYL ACRYLATE, PROPYLENE CARBONATE, SODIUM CHLORIDE, TOCOPHEROL, PARFUM',
    url: 'https://www.laroche-posay.fr',
  },

  {
    name: 'Hyalu B5 Sérum',
    brand: 'La Roche-Posay',
    kind: 'skincare',
    unit: 'dropper',
    slug: LRP_PRODUCT_SLUGS.HYALU_B5_SERUM,
    totalAmount: 30,
    amountUnit: 'ml',
    priceCents: 3149,
    description:
      'Sérum hydratant repulpant anti-rides à l’acide hyaluronique. Convient aux peaux sensibles.',
    notes: '4 formes d’AH. Vitamine B5. Madecassoside.',
    inci: 'AQUA/WATER, GLYCERIN, ALCOHOL DENAT., PROPYLENE GLYCOL, PANTHENOL, PENTYLENE GLYCOL, DIMETHICONE, PEG-6 CAPRYLIC/CAPRIC GLYCERIDES, ALPINIA GALANGA LEAF EXTRACT, CALCIUM CHLORIDE, GLYCERYL ISOSTEARATE, PPG-6-DECYLTETRADECETH-30, SODIUM ACETYLATED HYALURONATE, SODIUM HYALURONATE, ALGIN, ADENOSINE, AMMONIUM POLYACRYLOYLDIMETHYL TAURATE, PROPANEDIOL, HYDROLYZED HYALURONIC ACID, HYDROXYACETOPHENONE, CAPRYLIC/CAPRIC TRIGLYCERIDE, CAPRYLYL GLYCOL, CITRIC ACID, TRISODIUM ETHYLENEDIAMINE DISUCCINATE, ACETYL GLUCOSAMINE, XANTHAN GUM, BUTYLENE GLYCOL, 1,2-HEXANEDIOL, TOCOPHEROL, PHENOXYETHANOL, PARFUM',
    url: 'https://www.laroche-posay.fr',
  },
  {
    name: 'Effaclar Duo+M Soin Triple Correction Anti-Imperfections',
    brand: 'La Roche-Posay',
    kind: 'skincare',
    unit: 'tube',
    slug: LRP_PRODUCT_SLUGS.EFFACLAR_DUO_M,
    totalAmount: 40,
    amountUnit: 'ml',
    priceCents: 1375,
    description:
      'Soin anti-imperfections pour peaux grasses à tendance acnéique. Agit sur boutons, marques et récidive.',
    notes: 'Niacinamide. Zinc PCA. Acide salicylique + LHA. Texture gel-crème. Peaux sensibles.',
    inci: 'AQUA/WATER, GLYCERIN, DIMETHICONE, ISOCETYL STEARATE, NIACINAMIDE, ISOPROPYL LAUROYL SARCOSINATE, SILICA, AMMONIUM POLYACRYLOYLDIMETHYL TAURATE, ORYZA SATIVA STARCH, PUNICA GRANATUM PERICARP EXTRACT, POTASSIUM CETYL PHOSPHATE, SORBITAN OLEATE, ZINC PCA, GLYCERYL STEARATE SE, ISOHEXADECANE, SODIUM HYDROXIDE, MYRISTYL MYRISTATE, 2-OLEAMIDO-1,3-OCTADECANEDIOL, MANNOSE, POLOXAMER 338, PROPANEDIOL, HYDROXYETHOXYPHENYL BUTANONE, CAPRYLOYL SALICYLIC ACID, CAPRYLYL GLYCOL, VITREOSCILLA FERMENT, CITRIC ACID, TRISODIUM ETHYLENEDIAMINE DISUCCINATE, MALTODEXTRIN, XANTHAN GUM, PENTYLENE GLYCOL, POLYSORBATE 80, ACRYLAMIDE/SODIUM ACRYLOYLDIMETHYLTAURATE COPOLYMER, SALICYLIC ACID, PIROCTONE OLAMINE, PARFUM',
    url: 'https://www.laroche-posay.fr',
  },

  {
    name: 'Cicaplast Baume B5+ Réparateur Apaisant SPF50',
    brand: 'La Roche-Posay',
    kind: 'skincare',
    unit: 'tube',
    slug: LRP_PRODUCT_SLUGS.CICAPLAST_B5_SPF50,
    totalAmount: 40,
    amountUnit: 'ml',
    priceCents: 1350,
    description:
      'Baume réparateur apaisant SPF50 pour peaux fragilisées. Protège des UV et limite les marques.',
    notes: 'Panthénol. Madecassoside. Zinc. Protection minérale.',
    inci: 'AQUA/WATER, HYDROGENATED POLYISOBUTENE, DIMETHICONE, GLYCERIN, BUTYROSPERMUM PARKII BUTTER, PANTHENOL, PROPANEDIOL, BUTYLENE GLYCOL, ALUMINUM STARCH OCTENYLSUCCINATE, CETYL PEG/PPG-10/1 DIMETHICONE, TRIHYDROXYSTEARIN, ZINC GLUCONATE, MADECASSOSIDE, MANGANESE GLUCONATE, SILICA, ALUMINUM HYDROXIDE, MAGNESIUM SULFATE, DISODIUM EDTA, COPPER GLUCONATE, CAPRYLOYL GLYCINE, CITRIC ACID, ACETYLATED GLYCOL STEARATE, POLYGLYCERYL-4 ISOSTEARATE, TOCOPHEROL, PENTAERYTHRITYL TETRA-DI-T-BUTYL HYDROXYHYDROCINNAMATE, CI 77891',
    url: 'https://www.laroche-posay.fr',
  },

  {
    name: 'Toleriane Rosaliac AR',
    brand: 'La Roche-Posay',
    kind: 'skincare',
    unit: 'pump',
    slug: LRP_PRODUCT_SLUGS.ROSALIAC_AR,
    totalAmount: 40,
    amountUnit: 'ml',
    priceCents: 2330,
    description: 'Soin correcteur qui rééquilibre le microbiome et apaise les échauffements.',
    notes: 'Texture gel-crème. Sans parfum.',
    inci: 'AQUA / WATER / EAU, GLYCERIN, ISOSTEARYL NEOPENTANOATE, BUTYLENE GLYCOL, BORON NITRIDE, BUTYROSPERMUM PARKII BUTTER / SHEA BUTTER, CI 77891 / TITANIUM DIOXIDE, PENTYLENE GLYCOL, HYDROGENATED COCO-GLYCERIDES, POLYSORBATE 20, ZEA MAYS STARCH / CORN STARCH, SCHISANDRA SPHENANTHERA FRUIT EXTRACT, TIN OXIDE, SORBITAN OLEATE, GLYCERYL ACRYLATE/ACRYLIC ACID COPOLYMER, GLYCERYL STEARATE CITRATE, ISOHEXADECANE, SPHINGOMONAS FERMENT EXTRACT, SILICA, ALUMINUM HYDROXIDE, MANNITOL, AMMONIUM POLYACRYLOYLDIMETHYL TAURATE, HYDROGENATED LECITHIN, CAPRYLYL GLYCOL, CITRIC ACID, TRISODIUM ETHYLENEDIAMINE DISUCCINATE, ACETYL DIPEPTIDE-1 CETYL ESTER, MALTODEXTRIN, POLYSORBATE 80, ACRYLAMIDE/SODIUM ACRYLOYLDIMETHYLTAURATE COPOLYMER, MICA, CI 77288 / CHROMIUM OXIDE GREENS, CI 77491 / IRON OXIDES, CI 77492 / IRON OXIDES, CI 77499 / IRON OXIDES',
  },
  {
    name: 'Effaclar H Iso-Biome',
    brand: 'La Roche-Posay',
    kind: 'skincare',
    unit: 'pump',
    slug: LRP_PRODUCT_SLUGS.EFFACLAR_H_ISO_BIOME,
    totalAmount: 40,
    amountUnit: 'ml',
    priceCents: 0,
    description:
      'Crème hydratante compensatrice pour peaux grasses fragilisées par les traitements asséchants anti-acné.',
    notes: 'Occlusion 6/10. Texture crème légère. Répare et réduit imperfections/marqués.',
    inci: 'AQUA/WATER/EAU, GLYCERIN, SQUALANE, DIMETHICONE, PANTHENOL, ZEA MAYS STARCH/CORN STARCH, NIACINAMIDE, AMMONIUM POLYACRYLOYLDIMETHYL TAURATE, MYRISTYL MYRISTATE, BIXA ORELLANA SEED EXTRACT, STEARIC ACID, POTASSIUM CETYL PHOSPHATE, GLYCERYL STEARATE SE, SODIUM HYDROXIDE, MYRISTIC ACID, 2-OLEAMIDO-1,3-OCTADECANEDIOL, PALMITIC ACID, HYDROXYACETOPHENONE, CAPRYLOYL GLYCINE, CAPRYLYL GLYCOL, VITREOSCILLA FERMENT, CITRIC ACID, MALTODEXTRIN, XANTHAN GUM, PARFUM/FRAGRANCE',
    url: 'https://www.laroche-posay.fr',
  },
  {
    name: 'Cicaplast Baume B5+',
    brand: 'La Roche-Posay',
    kind: 'skincare',
    unit: 'pump',
    slug: LRP_PRODUCT_SLUGS.CICAPLAST_BAUME_B5_PLUS,
    totalAmount: 40,
    amountUnit: 'ml',
    priceCents: 0,
    description: 'Baume réparateur multi-usage apaisant pour peaux irritées, lésions, post-actes.',
    notes: 'Occlusion 8/10. Texture baume riche. Effet pansement, anti-marques.',
    inci: 'AQUA/WATER/EAU, HYDROGENATED POLYISOBUTENE, DIMETHICONE, GLYCERIN, BUTYROSPERMUM PARKII BUTTER/SHEA BUTTER, PANTHENOL, ZEA MAYS STARCH/CORN STARCH, PROPANEDIOL, BUTYLENE GLYCOL, CETYL PEG/PPG-10/1 DIMETHICONE, TRIHYDROXYSTEARIN, CENTELLA ASIATICA LEAF EXTRACT, POLYMNIA SONCHIFOLIA ROOT JUICE, ZINC GLUCONATE, MADECASSOSIDE, MANGANESE GLUCONATE, ALPHA-GLUCAN OLIGOSACCHARIDE, SILICA, ALUMINUM HYDROXIDE, MAGNESIUM SULFATE, MANNOSE, CAPRYLOYL GLYCINE, CAPRYLYL GLYCOL, VITREOSCILLA FERMENT, CITRIC ACID, TRISODIUM ETHYLENEDIAMINE DISUCCINATE, LACTOBACILLUS, ACETYLATED GLYCOL STEARATE, MALTODEXTRIN, POLYGLYCERYL-4 ISOSTEARATE, TOCOPHEROL, PENTAERYTHRITYL TETRA-DI-T-BUTYL HYDROXYHYDROCINNAMATE, CI 77891/TITANIUM DIOXIDE',
    url: 'https://www.laroche-posay.fr',
  },
  {
    name: 'Hyalu B5 Soin Crème',
    brand: 'La Roche-Posay',
    kind: 'skincare',
    unit: 'tube',
    slug: LRP_PRODUCT_SLUGS.HYALU_B5_CREME,
    totalAmount: 40,
    amountUnit: 'ml',
    priceCents: 2699,
    description:
      'Crème anti-rides hydratante et repulpante à l’acide hyaluronique. Adaptée aux peaux sensibles.',
    notes: 'Acide hyaluronique haut & bas PM. Vitamine B5. Texture riche.',
    inci: 'AQUA/WATER, GLYCERIN, DIMETHICONE, HYDROGENATED POLYISOBUTENE, PROPYLENE GLYCOL, HYDROXYPROPYL TETRAHYDROPYRANTRIOL, ALCOHOL DENAT., PROPANEDIOL, PANTHENOL, SYNTHETIC WAX, NYLON-12, PEG-10 DIMETHICONE, DIMETHICONE/PEG-10/15 CROSSPOLYMER, HYDROXYETHYLPIPERAZINE ETHANE SULFONIC ACID, TOCOPHEROL, SODIUM POLYACRYLATE, SODIUM HYALURONATE, HYDROLYZED HYALURONIC ACID, SODIUM CITRATE, PHENOXYETHANOL, ADENOSINE, CHLORPHENESIN, PROPYLENE CARBONATE, DIPROPYLENE GLYCOL, DISTEARDIMONIUM HECTORITE, DISODIUM EDTA, PARFUM',
    url: 'https://www.laroche-posay.fr',
  },

  {
    name: 'Effaclar Mat Crème Hydratante Sébo-Régulatrice',
    brand: 'La Roche-Posay',
    kind: 'skincare',
    unit: 'tube',
    slug: LRP_PRODUCT_SLUGS.EFFACLAR_MAT,
    totalAmount: 40,
    amountUnit: 'ml',
    priceCents: 1149,
    description:
      'Crème hydratante sébo-régulatrice pour peaux grasses. Réduit brillance et pores dilatés.',
    notes: 'Sebulyse. Zinc. Perlite absorbante. LHA.',
    inci: 'AQUA/WATER, GLYCERIN, DIMETHICONE, ISOCETYL STEARATE, ALCOHOL DENAT., SILICA, DIMETHICONE/VINYL DIMETHICONE CROSSPOLYMER, ACRYLAMIDE/SODIUM ACRYLOYLDIMETHYLTAURATE COPOLYMER, METHYL METHACRYLATE CROSSPOLYMER, BUTYLENE GLYCOL, PEG-100 STEARATE, COCAMIDE MEA, SARCOSINE, GLYCERYL STEARATE, TRIETHANOLAMINE, ISOHEXADECANE, PERLITE, CAPRYLOYL SALICYLIC ACID, TETRASODIUM EDTA, PENTYLENE GLYCOL, POLYSORBATE 80, ACRYLATES/C10-30 ALKYL ACRYLATE CROSSPOLYMER, SALICYLIC ACID, PARFUM',
    url: 'https://www.laroche-posay.fr',
  },

  {
    name: 'Tolériane Sensitive Crème',
    brand: 'La Roche-Posay',
    kind: 'skincare',
    unit: 'tube',
    slug: LRP_PRODUCT_SLUGS.TOLERIANE_SENSITIVE,
    totalAmount: 40,
    amountUnit: 'ml',
    priceCents: 1499,
    description: 'Crème hydratante apaisante pour peaux sensibles. Renforce la barrière cutanée.',
    notes: 'Niacinamide. Céramide NP. Sans parfum.',
    inci: 'AQUA/WATER, GLYCERIN, SQUALANE, DIMETHICONE, ZEA MAYS STARCH, NIACINAMIDE, AMMONIUM POLYACRYLOYLDIMETHYL TAURATE, MYRISTYL MYRISTATE, STEARIC ACID, CERAMIDE NP, POTASSIUM CETYL PHOSPHATE, GLYCERYL STEARATE SE, SODIUM HYDROXIDE, MYRISTIC ACID, PALMITIC ACID, CAPRYLOYL GLYCINE, CAPRYLYL GLYCOL, XANTHAN GUM',
    url: 'https://www.laroche-posay.fr',
  },

  {
    name: 'Pure Vitamin C12 Sérum',
    brand: 'La Roche-Posay',
    kind: 'skincare',
    unit: 'dropper',
    slug: LRP_PRODUCT_SLUGS.PURE_VITAMIN_C12,
    totalAmount: 30,
    amountUnit: 'ml',
    priceCents: 3433,
    description: 'Sérum éclat anti-rides à 12% de vitamine C pure. Adapté aux peaux sensibles.',
    notes: '12% acide ascorbique. Acide salicylique. Neurosensine.',
    inci: 'AQUA/WATER, ASCORBIC ACID, DIMETHICONE, GLYCERIN, ALCOHOL DENAT., POTASSIUM HYDROXIDE, POLYSILICONE-11, SILICA, PENTAERYTHRITYL TETRAETHYLHEXANOATE, PEG-20 METHYL GLUCOSE SESQUISTEARATE, SODIUM HYALURONATE, ADENOSINE, POLOXAMER 338, AMMONIUM POLYACRYLOYLDIMETHYL TAURATE, HYDROLYZED HYALURONIC ACID, CAPRYLIC/CAPRIC TRIGLYCERIDE, CAPRYLYL GLYCOL, CITRIC ACID, LAURETH-7, TRISODIUM ETHYLENEDIAMINE DISUCCINATE, BIS-PEG/PPG-16/16 PEG/PPG-16/16 DIMETHICONE, ACETYL DIPEPTIDE-1 CETYL ESTER, XANTHAN GUM, PENTYLENE GLYCOL, POLYACRYLAMIDE, C13-14 ISOALKANE, TOCOPHEROL, PENTAERYTHRITYL TETRA-DI-T-BUTYL HYDROXYHYDROCINNAMATE, SALICYLIC ACID, PARFUM',
    url: 'https://www.laroche-posay.fr',
  },
  {
    name: 'Lipikar Baume AP+M Triple-Réparation Anti-Grattage Hydratant',
    brand: 'La Roche-Posay',
    kind: 'moisturizer',
    unit: 'pot',
    slug: LRP_PRODUCT_SLUGS.LIPIKAR_BAUME_AP_M,
    totalAmount: 400,
    amountUnit: 'ml',
    priceCents: 1899,
    description:
      'Baume relipidant anti-irritations pour peaux très sèches, sensibles, fragilisées et à tendance atopique/eczéma. Apaise les démangeaisons, restaure la barrière cutanée et rééquilibre le microbiome. Convient dès la naissance.',
    notes:
      'Enrichi en beurre de karité (20%), niacinamide apaisante et Aqua Posae Filiformis (prébiotique). Texture crème non grasse, non collante. Testé sur peaux à tendance eczéma atopique.',
    inci: 'Aqua / Water, Butyrospermum Parkii Butter / Shea Butter, Glycerin, Dimethicone, Niacinamide, Cetearyl Alcohol, Brassica Campestris Seed Oil / Rapeseed Seed Oil, Glyceryl Stearate, Ammonium Polyacryloyldimethyl Taurate, Peg-100 Stearate, Propanediol, Ophiopogon Japonicus Root Extract, Peg-20 Methyl Glucose Sesquistearate, Sorbitan Tristearate, Dimethiconol, Sodium Chloride, Mannose, Coco-Betaine, Disodium Edta, Capryloyl Glycine, Caprylyl Glycol, Vitreoscilla Ferment, Citric Acid, Maltodextrin, Xanthan Gum, Tocopherol, Pentaerythrityl Tetra-Di-T-Butyl Hydroxyhydrocinnamate',
    url: 'https://www.laroche-posay.fr',
  },
  {
    name: 'Lipikar Lait',
    brand: 'La Roche-Posay',
    kind: 'skincare',
    unit: 'pump',
    slug: LRP_PRODUCT_SLUGS.LRP_LIPIKAR_LAIT,
    totalAmount: 400,
    amountUnit: 'ml',
    priceCents: 1750,
    description:
      'Lait relipidant pour peaux sèches/sensibles. Hydratation 48h, texture fluide absorption immédiate, sans fini gras.',
    notes:
      'Beurre de karité 20% + eau thermale. Sans parfum. Idéal quotidien/climats chauds, toute la famille.',
    inci: 'AQUA/WATER, BUTYROSPERMUM PARKII BUTTER/SHEA BUTTER, GLYCERIN, ISOPROPYL PALMITATE, DIMETHICONE, CAPRYLIC/CAPRIC TRIGLYCERIDE, CETEARYL ALCOHOL, NIACINAMIDE, PEG-100 STEARATE, GLYCERYL STEARATE, SODIUM HYDROXIDE, CARBOMER, AMMONIUM POLYACRYLOYLDIMETHYL TAURATE, CAPRYLYL GLYCOL, CITRIC ACID, VITREOSCILLA FERMENT, XANTHAN GUM, PENTYLENE GLYCOL',
    url: 'https://www.laroche-posay.fr',
  },
  {
    name: 'Effaclar Gel Moussant Purifiant Nettoyant Anti-Imperfection',
    brand: 'La Roche-Posay',
    kind: 'cleanser',
    unit: 'tube',
    slug: LRP_PRODUCT_SLUGS.EFFACLAR_GEL_NETTOYANT,
    totalAmount: 400,
    amountUnit: 'ml',
    priceCents: 1262,
    description:
      'Gel nettoyant purifiant moussant pour peaux grasses à tendance acnéique. Réduit boutons et points noirs, régule le sébum, optimise le pH cutané grâce à Phylobioma. Doux, sans agresser la peau, enrichi en Eau Thermale apaisante.',
    notes:
      'Innovation microbiome avec Phylobioma. Action anti-imperfections en profondeur. Testé sur peaux sensibles/acnéiques. Sans alcool agressif.',
    inci: 'AQUA / WATER / EAU, SODIUM LAURETH SULFATE, PEG-8, COCO-BETAINE, HEXYLENE GLYCOL, SODIUM CHLORIDE, PUNICA GRANATUM PERICARP EXTRACT, ZINC PCA, PEG-120 METHYL GLUCOSE DIOLEATE, SODIUM CITRATE, SODIUM HYDROXIDE, CAPRYLYL GLYCOL, CITRIC ACID, TRISODIUM ETHYLENEDIAMINE DISUCCINATE, MALTODEXTRIN, PENTYLENE GLYCOL, TOCOPHEROL, SODIUM BENZOATE, PHENOXYETHANOL, PARFUM / FRAGRANCE',
    url: 'https://www.laroche-posay.fr',
  },
  {
    name: 'Mela B3 Sérum anti-taches concentré intensif',
    brand: 'La Roche-Posay',
    kind: 'serum',
    unit: 'flacon compte-gouttes',
    slug: LRP_PRODUCT_SLUGS.SERUM_MELA_B3,
    totalAmount: 30,
    amountUnit: 'ml',
    priceCents: 4499,
    description:
      "Sérum anti-taches intensif contre les taches brunes persistantes, perte d'éclat et hyperpigmentation. Corrige taches, post-acné, âge et soleil avec Melasyl™ multibreveté + 10% Niacinamide. Action anti-récidive.",
    notes:
      'Innovation Melasyl™ pour hyperpigmentation. Niacinamide apaisante et hydratante. Testé sur tous types de peaux, y compris sensibles. Efficacité visible sur taches tenaces.',
    inci: 'AQUA / WATER / EAU, DIMETHICONE, NIACINAMIDE, GLYCERIN, PROPYLENE GLYCOL, POLYSILICONE-11, SILICA, BIS-PEG/PPG-16/16 PEG/PPG-16/16 DIMETHICONE, CYSTOSEIRA TAMARISCIFOLIA EXTRACT, 2-MERCAPTONICOTINOYL GLYCINE, PEG-20 METHYL GLUCOSE SESQUISTEARATE, SODIUM HYALURONATE, SODIUM HYDROXIDE, SODIUM THIOSULFATE, CARNOSINE, POLOXAMER 338, AMMONIUM POLYACRYLOYLDIMETHYL TAURATE, DIPOTASSIUM GLYCYRRHIZATE, CAPRYLIC/CAPRIC TRIGLYCERIDE, CAPRYLOYL SALICYLIC ACID, CAPRYLYL GLYCOL, CITRIC ACID, TRISODIUM ETHYLENEDIAMINE DISUCCINATE, XANTHAN GUM, PENTYLENE GLYCOL, OCTYLDODECANOL, RETINYL PALMITATE, TOCOPHEROL, PENTAERYTHRITYL TETRA-DI-T-BUTYL HYDROXYHYDROCINNAMATE, PHENOXYETHANOL, CI 17200 / RED 33, PARFUM / FRAGRANCE',
    url: 'https://www.laroche-posay.fr',
  },
  {
    name: 'Rétinol B3 Sérum anti-rides au rétinol régénérant resurfaçant',
    brand: 'La Roche-Posay',
    kind: 'serum',
    unit: 'flacon compte-gouttes',
    slug: LRP_PRODUCT_SLUGS.SERUM_B3_RETINOL,
    totalAmount: 30,
    amountUnit: 'ml',
    priceCents: 4499,
    description:
      "Sérum anti-âge au rétinol pur + libération graduelle, associé à la Vitamine B3 (Niacinamide). Corrige rides profondes, taches, perte de fermeté et signes de l'âge. Régénère et resurface la peau tout en apaisant et renforçant la barrière cutanée.",
    notes:
      'Rétinol pur + graduel pour tolérance optimale. Niacinamide apaisante et réparatrice. Glycérine hydratante. Convient à tous types de peaux, introduction progressive recommandée.',
    inci: 'AQUA / WATER / EAU, GLYCERIN, DIMETHICONE, ALCOHOL DENAT., PENTYLENE GLYCOL, NIACINAMIDE, GLYCINE SOJA OIL / SOYBEAN OIL, PPG-6-DECYLTETRADECETH-30, SODIUM HYALURONATE, RETINOL, ADENOSINE, AMMONIUM POLYACRYLOYLDIMETHYL TAURATE, CAPRYLYL GLYCOL, CITRIC ACID, TRISODIUM ETHYLENEDIAMINE DISUCCINATE, XANTHAN GUM, POLYSILICONE-11, RETINYL PALMITATE, TOCOPHEROL, PHENOXYETHANOL, PARFUM / FRAGRANCE',
    url: 'https://www.laroche-posay.fr',
  },
]
