import { TAG_SLUGS } from '../../tags/seed-tags'
import { SKIN1004_PRODUCT_SLUGS } from './skin1004'

export const SKIN1004_PRODUCT_TAGS: { productSlug: string; tagSlug: string }[] = [
  // Madagascar Centella Probio-Cica Enrich Cream
  {
    productSlug: SKIN1004_PRODUCT_SLUGS.SKIN1004_MADAGASCAR_CENTELLA_PROBIO_CICA,
    tagSlug: TAG_SLUGS.PEAU_SENSIBLE,
  },
  {
    productSlug: SKIN1004_PRODUCT_SLUGS.SKIN1004_MADAGASCAR_CENTELLA_PROBIO_CICA,
    tagSlug: TAG_SLUGS.BARRIERE_CUTANEE,
  },
  {
    productSlug: SKIN1004_PRODUCT_SLUGS.SKIN1004_MADAGASCAR_CENTELLA_PROBIO_CICA,
    tagSlug: TAG_SLUGS.REPARATEUR,
  },
  {
    productSlug: SKIN1004_PRODUCT_SLUGS.SKIN1004_MADAGASCAR_CENTELLA_PROBIO_CICA,
    tagSlug: TAG_SLUGS.OCCLUSIF,
  },
  {
    productSlug: SKIN1004_PRODUCT_SLUGS.SKIN1004_MADAGASCAR_CENTELLA_PROBIO_CICA,
    tagSlug: TAG_SLUGS.CREME_HYDRATANTE,
  },
  {
    productSlug: SKIN1004_PRODUCT_SLUGS.SKIN1004_MADAGASCAR_CENTELLA_PROBIO_CICA,
    tagSlug: TAG_SLUGS.PEAU_SECHE,
  },

  // Madagascar Centella Soothing Cream
  {
    productSlug: SKIN1004_PRODUCT_SLUGS.SKIN1004_MADAGASCAR_CENTELLA_SOOTHING_CREAM,
    tagSlug: TAG_SLUGS.ANTI_ROUGEURS,
  },
  {
    productSlug: SKIN1004_PRODUCT_SLUGS.SKIN1004_MADAGASCAR_CENTELLA_SOOTHING_CREAM,
    tagSlug: TAG_SLUGS.PEAU_REACTIVE,
  },
  {
    productSlug: SKIN1004_PRODUCT_SLUGS.SKIN1004_MADAGASCAR_CENTELLA_SOOTHING_CREAM,
    tagSlug: TAG_SLUGS.CREME_HYDRATANTE,
  },
  {
    productSlug: SKIN1004_PRODUCT_SLUGS.SKIN1004_MADAGASCAR_CENTELLA_SOOTHING_CREAM,
    tagSlug: TAG_SLUGS.PEAU_MIXTE,
  },

  // Tea-Trica Relief Ampoule Mini
  {
    productSlug: SKIN1004_PRODUCT_SLUGS.SKIN1004_TEA_TRICA_RELIEF_MINI,
    tagSlug: TAG_SLUGS.ANTI_ACNE,
  },
  {
    productSlug: SKIN1004_PRODUCT_SLUGS.SKIN1004_TEA_TRICA_RELIEF_MINI,
    tagSlug: TAG_SLUGS.ANTI_ROUGEURS,
  },
  { productSlug: SKIN1004_PRODUCT_SLUGS.SKIN1004_TEA_TRICA_RELIEF_MINI, tagSlug: TAG_SLUGS.SERUM },
  {
    productSlug: SKIN1004_PRODUCT_SLUGS.SKIN1004_TEA_TRICA_RELIEF_MINI,
    tagSlug: TAG_SLUGS.ANTISEPTIQUE,
  },

  // Madagascar Centella Asiatica 100 Ampoule
  {
    productSlug: SKIN1004_PRODUCT_SLUGS.SKIN1004_MADAGASCAR_CENTELLA_100,
    tagSlug: TAG_SLUGS.PEAU_SENSIBLE,
  },
  {
    productSlug: SKIN1004_PRODUCT_SLUGS.SKIN1004_MADAGASCAR_CENTELLA_100,
    tagSlug: TAG_SLUGS.REPARATEUR,
  },
  {
    productSlug: SKIN1004_PRODUCT_SLUGS.SKIN1004_MADAGASCAR_CENTELLA_100,
    tagSlug: TAG_SLUGS.SERUM,
  },
  {
    productSlug: SKIN1004_PRODUCT_SLUGS.SKIN1004_MADAGASCAR_CENTELLA_100,
    tagSlug: TAG_SLUGS.SANS_PARFUM,
  },

  // Spot Cover Patch
  { productSlug: SKIN1004_PRODUCT_SLUGS.SKIN1004_SPOT_COVER_PATCH, tagSlug: TAG_SLUGS.ANTI_ACNE },
  {
    productSlug: SKIN1004_PRODUCT_SLUGS.SKIN1004_SPOT_COVER_PATCH,
    tagSlug: TAG_SLUGS.PROTECTION_SOLAIRE,
  }, // Utilisé comme barrière physique/protection

  // Madagascar Centella Probio-Cica Essence Toner
  {
    productSlug: SKIN1004_PRODUCT_SLUGS.SKIN1004_CENTELLA_PROBIO_CICA_ESSENCE,
    tagSlug: TAG_SLUGS.TONIQUE,
  },
  {
    productSlug: SKIN1004_PRODUCT_SLUGS.SKIN1004_CENTELLA_PROBIO_CICA_ESSENCE,
    tagSlug: TAG_SLUGS.BARRIERE_CUTANEE,
  },
  {
    productSlug: SKIN1004_PRODUCT_SLUGS.SKIN1004_CENTELLA_PROBIO_CICA_ESSENCE,
    tagSlug: TAG_SLUGS.DESHYDRATATION,
  },
  {
    productSlug: SKIN1004_PRODUCT_SLUGS.SKIN1004_CENTELLA_PROBIO_CICA_ESSENCE,
    tagSlug: TAG_SLUGS.SANS_PARFUM,
  },

  // Madagascar Centella Toning Toner
  {
    productSlug: SKIN1004_PRODUCT_SLUGS.SKIN1004_MADAGASCAR_CENTELLA_TONING,
    tagSlug: TAG_SLUGS.TONIQUE,
  },
  {
    productSlug: SKIN1004_PRODUCT_SLUGS.SKIN1004_MADAGASCAR_CENTELLA_TONING,
    tagSlug: TAG_SLUGS.EXFOLIANT,
  },
  {
    productSlug: SKIN1004_PRODUCT_SLUGS.SKIN1004_MADAGASCAR_CENTELLA_TONING,
    tagSlug: TAG_SLUGS.ECLAT,
  },
  {
    productSlug: SKIN1004_PRODUCT_SLUGS.SKIN1004_MADAGASCAR_CENTELLA_TONING,
    tagSlug: TAG_SLUGS.PEAU_SENSIBLE,
  },
]
