import { TAG_SLUGS } from '../../tags/seed-tags'
import { AZELAIQUE_PRODUCT_SLUGS } from './azelaique'

export const AZELAIQUE_PRODUCT_TAGS: { productSlug: string; tagSlug: string }[] = [
  // Nine Less - A-Control 10% Azelaic Acid Serum
  { productSlug: AZELAIQUE_PRODUCT_SLUGS.NINE_LESS_A_CONTROL_10, tagSlug: TAG_SLUGS.ANTI_ACNE },
  { productSlug: AZELAIQUE_PRODUCT_SLUGS.NINE_LESS_A_CONTROL_10, tagSlug: TAG_SLUGS.ANTI_ROUGEURS },
  { productSlug: AZELAIQUE_PRODUCT_SLUGS.NINE_LESS_A_CONTROL_10, tagSlug: TAG_SLUGS.REPARATEUR },
  { productSlug: AZELAIQUE_PRODUCT_SLUGS.NINE_LESS_A_CONTROL_10, tagSlug: TAG_SLUGS.ANTI_AGE },
  { productSlug: AZELAIQUE_PRODUCT_SLUGS.NINE_LESS_A_CONTROL_10, tagSlug: TAG_SLUGS.SERUM },
  { productSlug: AZELAIQUE_PRODUCT_SLUGS.NINE_LESS_A_CONTROL_10, tagSlug: TAG_SLUGS.HUMECTANT },

  // Purito Seoul - Azelaic Kojic Tea Tree Serum
  {
    productSlug: AZELAIQUE_PRODUCT_SLUGS.PURITO_AZELAIC_KOJIC_TEA_TREE,
    tagSlug: TAG_SLUGS.ANTI_ACNE,
  },
  {
    productSlug: AZELAIQUE_PRODUCT_SLUGS.PURITO_AZELAIC_KOJIC_TEA_TREE,
    tagSlug: TAG_SLUGS.HYPERPIGMENTATION,
  },
  {
    productSlug: AZELAIQUE_PRODUCT_SLUGS.PURITO_AZELAIC_KOJIC_TEA_TREE,
    tagSlug: TAG_SLUGS.ANTI_TACHES,
  },
  {
    productSlug: AZELAIQUE_PRODUCT_SLUGS.PURITO_AZELAIC_KOJIC_TEA_TREE,
    tagSlug: TAG_SLUGS.SEBO_REGULATEUR,
  },
  { productSlug: AZELAIQUE_PRODUCT_SLUGS.PURITO_AZELAIC_KOJIC_TEA_TREE, tagSlug: TAG_SLUGS.SERUM },
  { productSlug: AZELAIQUE_PRODUCT_SLUGS.PURITO_AZELAIC_KOJIC_TEA_TREE, tagSlug: TAG_SLUGS.ECLAT },

  // Nooance - Sérum Acide Azélaïque 15%
  { productSlug: AZELAIQUE_PRODUCT_SLUGS.NOOANCE_AZELAIC_15, tagSlug: TAG_SLUGS.ANTI_ROUGEURS },
  { productSlug: AZELAIQUE_PRODUCT_SLUGS.NOOANCE_AZELAIC_15, tagSlug: TAG_SLUGS.ROSACEE },
  { productSlug: AZELAIQUE_PRODUCT_SLUGS.NOOANCE_AZELAIC_15, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },
  { productSlug: AZELAIQUE_PRODUCT_SLUGS.NOOANCE_AZELAIC_15, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },
  { productSlug: AZELAIQUE_PRODUCT_SLUGS.NOOANCE_AZELAIC_15, tagSlug: TAG_SLUGS.REPARATEUR },
  { productSlug: AZELAIQUE_PRODUCT_SLUGS.NOOANCE_AZELAIC_15, tagSlug: TAG_SLUGS.SERUM },
  { productSlug: AZELAIQUE_PRODUCT_SLUGS.NOOANCE_AZELAIC_15, tagSlug: TAG_SLUGS.SANS_PARFUM },

  // Allies of Skin - Azelaic & Kojic Advanced Clarifying Serum
  {
    productSlug: AZELAIQUE_PRODUCT_SLUGS.ALLIES_OF_SKIN_AZELAIC_KOJIC,
    tagSlug: TAG_SLUGS.HYPERPIGMENTATION,
  },
  {
    productSlug: AZELAIQUE_PRODUCT_SLUGS.ALLIES_OF_SKIN_AZELAIC_KOJIC,
    tagSlug: TAG_SLUGS.ANTI_TACHES,
  },
  { productSlug: AZELAIQUE_PRODUCT_SLUGS.ALLIES_OF_SKIN_AZELAIC_KOJIC, tagSlug: TAG_SLUGS.ECLAT },
  {
    productSlug: AZELAIQUE_PRODUCT_SLUGS.ALLIES_OF_SKIN_AZELAIC_KOJIC,
    tagSlug: TAG_SLUGS.ANTI_AGE,
  },
  { productSlug: AZELAIQUE_PRODUCT_SLUGS.ALLIES_OF_SKIN_AZELAIC_KOJIC, tagSlug: TAG_SLUGS.SERUM },
  {
    productSlug: AZELAIQUE_PRODUCT_SLUGS.ALLIES_OF_SKIN_AZELAIC_KOJIC,
    tagSlug: TAG_SLUGS.SANS_PARFUM,
  },

  // Dr Sam Bunting (Sonya Driver) - Flawless Brightly
  { productSlug: AZELAIQUE_PRODUCT_SLUGS.DR_SAM_FLAWLESS_BRIGHTLY, tagSlug: TAG_SLUGS.ECLAT },
  { productSlug: AZELAIQUE_PRODUCT_SLUGS.DR_SAM_FLAWLESS_BRIGHTLY, tagSlug: TAG_SLUGS.ANTI_AGE },
  { productSlug: AZELAIQUE_PRODUCT_SLUGS.DR_SAM_FLAWLESS_BRIGHTLY, tagSlug: TAG_SLUGS.ANTI_TACHES },
  { productSlug: AZELAIQUE_PRODUCT_SLUGS.DR_SAM_FLAWLESS_BRIGHTLY, tagSlug: TAG_SLUGS.SERUM },
  { productSlug: AZELAIQUE_PRODUCT_SLUGS.DR_SAM_FLAWLESS_BRIGHTLY, tagSlug: TAG_SLUGS.VEGAN },
  {
    productSlug: AZELAIQUE_PRODUCT_SLUGS.DR_SAM_FLAWLESS_BRIGHTLY,
    tagSlug: TAG_SLUGS.CRUELTY_FREE,
  },
]
