import { TAG_SLUGS } from '../../tags/seed-tags'
import { DERMEDEN_PRODUCT_SLUGS } from './dermeden'

interface ProductTagGroups {
  primary: string[] // Préoccupations majeures + actions clés
  secondary: string[] // Type de produit, étapes routine, propriétés, labels
  avoid: string[] // Exclusions (incompatibilités avec le produit)
}

export const PRODUCT_TAGS: Record<string, ProductTagGroups> = {
  [DERMEDEN_PRODUCT_SLUGS.ADVANCED_PEEL]: {
    primary: [TAG_SLUGS.ANTI_TACHES, TAG_SLUGS.GRAIN_PEAU], //
    secondary: [
      TAG_SLUGS.EXFOLIANT_CHIMIQUE,
      TAG_SLUGS.EXFOLIATION,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.KERATOLYTIQUE,
      TAG_SLUGS.ECLAT,
      TAG_SLUGS.PEAU_TOUS_TYPES,
    ], //
    avoid: [TAG_SLUGS.PEAU_SENSIBLE, TAG_SLUGS.PEAU_REACTIVE, TAG_SLUGS.GROSSESSE_COMPATIBLE], //
  },

  [DERMEDEN_PRODUCT_SLUGS.CONCENTRE_ANTI_TACHES_TXA_5]: {
    primary: [TAG_SLUGS.ANTI_TACHES, TAG_SLUGS.HYPERPIGMENTATION], //
    secondary: [
      TAG_SLUGS.SERUM,
      TAG_SLUGS.TRAITEMENT,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.NON_COMEDOGENE,
      TAG_SLUGS.ECLAT,
      TAG_SLUGS.POST_ACNE,
    ], //
    avoid: [],
  },

  [DERMEDEN_PRODUCT_SLUGS.LUMIXDERM_CREME_ECLAIRCISSANTE]: {
    primary: [TAG_SLUGS.ANTI_TACHES, TAG_SLUGS.ECLAT], //
    secondary: [
      TAG_SLUGS.CREME_HYDRATANTE,
      TAG_SLUGS.HYDRATATION,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.PEAU_TOUS_TYPES,
      TAG_SLUGS.NON_COMEDOGENE,
    ], //
    avoid: [],
  },

  [DERMEDEN_PRODUCT_SLUGS.DAY_PROTOCOLE_MIXTE_GRASSE]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.ANTI_TACHES], //
    secondary: [
      TAG_SLUGS.CREME_SOLAIRE,
      TAG_SLUGS.PROTECTION_SOLAIRE,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.MATIFIANT,
      TAG_SLUGS.LUMIERE_BLEUE,
      TAG_SLUGS.PEAU_GRASSE,
      TAG_SLUGS.PEAU_MIXTE,
      TAG_SLUGS.SANS_PARFUM,
    ], //
    avoid: [TAG_SLUGS.PEAU_SECHE], //
  },

  [DERMEDEN_PRODUCT_SLUGS.DAY_PROTOCOLE_SECHE]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.ANTI_TACHES], //
    secondary: [
      TAG_SLUGS.CREME_SOLAIRE,
      TAG_SLUGS.PROTECTION_SOLAIRE,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.TEXTURE_RICHE,
      TAG_SLUGS.LUMIERE_BLEUE,
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.SANS_PARFUM,
    ], //
    avoid: [TAG_SLUGS.PEAU_GRASSE, TAG_SLUGS.BRILLANCE], //
  },

  [DERMEDEN_PRODUCT_SLUGS.NIGHT_PROTOCOLE_CREME_NUIT_INTENSE]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.ANTI_TACHES], //
    secondary: [
      TAG_SLUGS.CREME_DE_NUIT,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.EXFOLIATION,
      TAG_SLUGS.REPULPANT,
      TAG_SLUGS.GRAIN_PEAU,
      TAG_SLUGS.HYDRATATION,
    ], //
    avoid: [TAG_SLUGS.MATIN, TAG_SLUGS.GROSSESSE_COMPATIBLE, TAG_SLUGS.PEAU_REACTIVE], //
  },

  [DERMEDEN_PRODUCT_SLUGS.NIGHT_PROTOCOLE_SERUM_INTENSE]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.ECLAT], //
    secondary: [
      TAG_SLUGS.SERUM,
      TAG_SLUGS.TRAITEMENT,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.REPULPANT,
      TAG_SLUGS.BIO_NATUREL,
    ], //
    avoid: [TAG_SLUGS.MATIN, TAG_SLUGS.GROSSESSE_COMPATIBLE], //
  },

  [DERMEDEN_PRODUCT_SLUGS.CONTOUR_YEUX_INTENSE]: {
    primary: [TAG_SLUGS.CERNES_POCHES, TAG_SLUGS.ANTI_AGE], //
    secondary: [
      TAG_SLUGS.CONTOUR_YEUX,
      TAG_SLUGS.SOIN_YEUX,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.HYDRATATION,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.ANTI_TACHES,
    ], //
    avoid: [TAG_SLUGS.MATIN], //
  },

  [DERMEDEN_PRODUCT_SLUGS.CICADERM_SOIN_REPARATEUR]: {
    primary: [TAG_SLUGS.BARRIERE_CUTANEE, TAG_SLUGS.CICATRISATION], //
    secondary: [
      TAG_SLUGS.BAUME,
      TAG_SLUGS.REPARATEUR,
      TAG_SLUGS.APAISANT,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.ANTISEPTIQUE,
      TAG_SLUGS.PHOTO_VIEILLISSEMENT,
    ], //
    avoid: [],
  },

  [DERMEDEN_PRODUCT_SLUGS.CREME_MAINS_ACTION_GLOBALE]: {
    primary: [TAG_SLUGS.ANTI_TACHES, TAG_SLUGS.HYDRATATION], //
    secondary: [
      TAG_SLUGS.BAUME,
      TAG_SLUGS.ANTI_AGE,
      TAG_SLUGS.ANTI_BACTERIEN,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
    ], //
    avoid: [],
  },

  [DERMEDEN_PRODUCT_SLUGS.LAIT_CORPS_ECLAT]: {
    primary: [TAG_SLUGS.HYDRATATION, TAG_SLUGS.ECLAT], //
    secondary: [
      TAG_SLUGS.LAIT_CORPS,
      TAG_SLUGS.REPULPANT,
      TAG_SLUGS.ANTI_TACHES,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.EMOLLIENT,
    ], //
    avoid: [],
  },

  [DERMEDEN_PRODUCT_SLUGS.SOIN_VERGETURES_RAFFERMISSANT]: {
    primary: [TAG_SLUGS.CICATRISATION, TAG_SLUGS.ANTI_AGE], //
    secondary: [
      TAG_SLUGS.LAIT_CORPS,
      TAG_SLUGS.EXFOLIATION,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.REPULPANT,
      TAG_SLUGS.GRAIN_PEAU,
    ], //
    avoid: [TAG_SLUGS.MATIN, TAG_SLUGS.GROSSESSE_COMPATIBLE], //
  },

  [DERMEDEN_PRODUCT_SLUGS.GEL_NETTOYANT_PURIFIANT]: {
    primary: [TAG_SLUGS.ANTI_ACNE, TAG_SLUGS.BRILLANCE], //
    secondary: [
      TAG_SLUGS.GEL_NETTOYANT,
      TAG_SLUGS.NETTOYANT,
      TAG_SLUGS.SEBO_REGULATEUR,
      TAG_SLUGS.PORES_DILATES,
      TAG_SLUGS.MATIFIANT,
      TAG_SLUGS.EXFOLIANT_PHYSIQUE,
    ], //
    avoid: [TAG_SLUGS.PEAU_SECHE, TAG_SLUGS.PEAU_ATOPIQUE], //
  },

  [DERMEDEN_PRODUCT_SLUGS.HA_LIKE_LOTION_MICELLAIRE]: {
    primary: [TAG_SLUGS.PEAU_SENSIBLE, TAG_SLUGS.BARRIERE_CUTANEE], //
    secondary: [
      TAG_SLUGS.EAU_MICELLAIRE,
      TAG_SLUGS.NETTOYANT,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.PREBIOTIQUE,
    ], //
    avoid: [],
  },

  [DERMEDEN_PRODUCT_SLUGS.MOUSSE_NETTOYANTE_ANTIOXYDANTE]: {
    primary: [TAG_SLUGS.ECLAT, TAG_SLUGS.TEINT_TERNE], //
    secondary: [
      TAG_SLUGS.MOUSSE_NETTOYANTE,
      TAG_SLUGS.NETTOYANT,
      TAG_SLUGS.ANTI_OXYDANT,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.POLLUTION,
    ], //
    avoid: [],
  },

  [DERMEDEN_PRODUCT_SLUGS.MASQUE_EXFOLIANT_DETOX]: {
    primary: [TAG_SLUGS.PORES_DILATES, TAG_SLUGS.GRAIN_PEAU], //
    secondary: [
      TAG_SLUGS.MASQUE_ARGILE,
      TAG_SLUGS.EXFOLIANT_PHYSIQUE,
      TAG_SLUGS.MASQUE_HEBDO,
      TAG_SLUGS.MATIFIANT,
      TAG_SLUGS.ANTI_OXYDANT,
      TAG_SLUGS.PEAU_GRASSE,
    ], //
    avoid: [TAG_SLUGS.PEAU_REACTIVE], //
  },

  [DERMEDEN_PRODUCT_SLUGS.DEMAQUILLANT_TOTAL_LAIT_LOTION]: {
    primary: [TAG_SLUGS.HYDRATATION, TAG_SLUGS.PEAU_SENSIBLE], //
    secondary: [
      TAG_SLUGS.LAIT_NETTOYANT,
      TAG_SLUGS.DOUBLE_NETTOYAGE_1,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.APAISANT,
      TAG_SLUGS.REPARATEUR,
      TAG_SLUGS.PEAU_TOUS_TYPES,
    ], //
    avoid: [],
  },

  [DERMEDEN_PRODUCT_SLUGS.HYDRA_PROTOCOLE_CREME_LEGERE]: {
    primary: [TAG_SLUGS.DESHYDRATATION, TAG_SLUGS.ANTI_AGE], //
    secondary: [
      TAG_SLUGS.GEL_CREME,
      TAG_SLUGS.MATIFIANT,
      TAG_SLUGS.TEXTURE_LEGERE,
      TAG_SLUGS.NON_COMEDOGENE,
      TAG_SLUGS.HUMECTANT,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
    ], //
    avoid: [TAG_SLUGS.PEAU_SECHE], //
  },

  [DERMEDEN_PRODUCT_SLUGS.HYDRA_PROTOCOLE_CREME_RICHE]: {
    primary: [TAG_SLUGS.DESHYDRATATION, TAG_SLUGS.ANTI_AGE], //
    secondary: [
      TAG_SLUGS.CREME_HYDRATANTE,
      TAG_SLUGS.TEXTURE_RICHE,
      TAG_SLUGS.EMOLLIENT,
      TAG_SLUGS.HYDRATATION,
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
    ], //
    avoid: [TAG_SLUGS.PEAU_GRASSE, TAG_SLUGS.BRILLANCE], //
  },

  [DERMEDEN_PRODUCT_SLUGS.DD_CREAM]: {
    primary: [TAG_SLUGS.ECLAT, TAG_SLUGS.ANTI_AGE], //
    secondary: [
      TAG_SLUGS.CREME_SOLAIRE,
      TAG_SLUGS.PROTECTION_SOLAIRE,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.LUMIERE_BLEUE,
      TAG_SLUGS.REPULPANT,
      TAG_SLUGS.PEAU_TOUS_TYPES,
    ], //
    avoid: [TAG_SLUGS.SOIR], //
  },

  [DERMEDEN_PRODUCT_SLUGS.CONCENTRE_REPULPANT_15]: {
    primary: [TAG_SLUGS.DESHYDRATATION, TAG_SLUGS.REPULPANT], //
    secondary: [
      TAG_SLUGS.SERUM,
      TAG_SLUGS.TRAITEMENT,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.BIOMIMETIQUE,
      TAG_SLUGS.HUMECTANT,
    ], //
    avoid: [],
  },

  [DERMEDEN_PRODUCT_SLUGS.CONCENTRE_RETINOIDES_6]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.GRAIN_PEAU], //
    secondary: [
      TAG_SLUGS.SERUM,
      TAG_SLUGS.TRAITEMENT,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.ECLAT,
      TAG_SLUGS.ANTI_OXYDANT,
    ], //
    avoid: [TAG_SLUGS.MATIN, TAG_SLUGS.GROSSESSE_COMPATIBLE], //
  },
}
