export const DERMEDEN_PRODUCT_SLUGS = {
  ADVANCED_PEEL: 'dermeden-advanced-peel',
  CONCENTRE_ANTI_TACHES_TXA_5: 'dermeden-concentre-anti-taches-txa-5',
  LUMIXDERM_CREME_ECLAIRCISSANTE: 'dermeden-lumixderm-creme-eclaircissante',
  DAY_PROTOCOLE_MIXTE_GRASSE: 'dermeden-day-protocole-creme-de-jour-4-en-1-peaux-mixtes-a-grasses',
  DAY_PROTOCOLE_SECHE: 'dermeden-day-protocole-creme-de-jour-4-en-1-peaux-seches',
  NIGHT_PROTOCOLE_CREME_NUIT_INTENSE: 'dermeden-night-protocole-creme-de-night-intense',
  NIGHT_PROTOCOLE_SERUM_INTENSE: 'dermeden-night-protocole-serum-intense',
  CONTOUR_YEUX_INTENSE: 'dermeden-soin-contour-des-yeux-intense',
  CICADERM_SOIN_REPARATEUR: 'dermeden-cicaderm-soin-reparateur',
  CREME_MAINS_ACTION_GLOBALE: 'dermeden-creme-mains-action-globale',
  LAIT_CORPS_ECLAT: 'dermeden-lait-corps-eclat',
  SOIN_VERGETURES_RAFFERMISSANT: 'dermeden-soin-vergetures-raffermissant',
  GEL_NETTOYANT_PURIFIANT: 'dermeden-gel-nettoyant-purifiant',
  HA_LIKE_LOTION_MICELLAIRE: 'dermeden-ha-like-lotion-micellaire',
  MOUSSE_NETTOYANTE_ANTIOXYDANTE: 'dermeden-mousse-nettoyante-antioxydante',
  MASQUE_EXFOLIANT_DETOX: 'dermeden-masque-exfoliant-detox-2-en-1',
  DEMAQUILLANT_TOTAL_LAIT_LOTION: 'dermeden-demaquillant-total-lait-lotion-2-en-1',
  HYDRA_PROTOCOLE_CREME_LEGERE: 'dermeden-hydra-protocole-creme-legere-matifiante',
  HYDRA_PROTOCOLE_CREME_RICHE: 'dermeden-hydra-protocole-creme-riche',
  DD_CREAM: 'dermeden-dd-cream-spf50',
  CONCENTRE_REPULPANT_15: 'dermeden-concentre-repulpant-et-hydratant-15',
  CONCENTRE_RETINOIDES_6: 'dermeden-concentre-retinoides-nuit-6',
} as const

export const DERMEDEN_PRODUCT_DATA = [
  {
    name: 'Advanced Peel',
    brand: 'DermEden',
    kind: 'skincare',
    unit: 'bottle',
    slug: DERMEDEN_PRODUCT_SLUGS.ADVANCED_PEEL,
    totalAmount: 60,
    amountUnit: 'ml',
    priceCents: 4000,
    description:
      "Protocole peeling en 2 étapes (Pre-Peel & Peel) pour traiter l'hyperpigmentation et le grain de peau.",
    notes: "pH 4.5 PRE-PEEL / pH 3.5 PEEL. Contient de l'acide glycolique encapsulé.",
    inci: 'Aqua (water) • decyl glucoside • 1.2-hexanediol • glycerin • panthenol • glycolic acid • cyclodextrin • sodium hydroxide • propanediol • xanthan gum • caramel • cl 17200 (red33)',
  },
  {
    name: 'Concentré Anti-Taches TXA 5%',
    brand: 'DermEden',
    kind: 'skincare',
    unit: 'bottle',
    slug: DERMEDEN_PRODUCT_SLUGS.CONCENTRE_ANTI_TACHES_TXA_5,
    totalAmount: 30,
    amountUnit: 'ml',
    priceCents: 6290,
    description:
      "Solution concentrée pour traiter le mélasma et l'hyperpigmentation post-inflammatoire.",
    notes: 'Sans parfum, sans silicone, sans alcool.',
    inci: 'Aqua (water) • niacinamide • tranexamic acid • propanediol • xanthan gum • ethylhexyl glycerin • chlorphenesin • citric acid • tocopherol',
  },
  {
    name: 'Lumixderm - Crème Éclaircissante',
    brand: 'DermEden',
    kind: 'skincare',
    unit: 'tube',
    slug: DERMEDEN_PRODUCT_SLUGS.LUMIXDERM_CREME_ECLAIRCISSANTE,
    totalAmount: 40,
    amountUnit: 'ml',
    priceCents: 6090,
    description: 'Préparation dermo-cosmétique à haute concentration d’actifs dépigmentants.',
    notes: 'Convient à tous les phototypes. Haute tolérance.',
    inci: 'Aqua (Water) • Cetearyl alcohol • Caprylic/Capric triglyceride • Glycerin • Pentylene glycol • Dimethicone • Sodium PCA • Citronellyl methylcrotonate • Octadecenedioic acid • Helianthus annuus (Sunflower) seed oil • Dicetyl phosphate • Ceteth-10 phosphate • Glutathione • Panthenol • Aloe barbadensis leaf juic • Dipotassium glycyrrhizate • Phenylethyl Resorcinol • Ethylhexylglycerin • Xanthan gum • Chlorphenesin • Allantoin • Spiraea ulmaria flower extract • Sodium hydroxide • Sodium benzoate • Decapeptide-12 • Sodium hyaluronate • BHT • Tocopherol',
  },
  {
    name: 'Crème de Jour 4 en 1 - Peaux Mixtes à Grasses',
    brand: 'DermEden',
    kind: 'skincare',
    unit: 'pump',
    slug: DERMEDEN_PRODUCT_SLUGS.DAY_PROTOCOLE_MIXTE_GRASSE,
    totalAmount: 50,
    amountUnit: 'ml',
    priceCents: 3990,
    description:
      'Protège et répare des rayonnements UVA/UVB et lumière bleue tout en traitant les rides et taches.',
    notes: 'SPF 50+ PA+++. Texture non grasse, excellente base de maquillage.',
    inci: 'Aqua (Water) • Ethylhexyl Methoxycinnamate • Diethylamino Hydroxybenzoyl Hexyl Benzoate • Niacidamide • Diisopropyl Sebacate • Ethylhexyl Triazone • Dimethicone • Bis Ethylhexyloxyphenol Methoxyphenyl Triazine • Methylene Bis-Benzotriazolyl Tetramethylbutylphenol [Nano] • Pentylene Glycol • Homosalate • Polyglyceryl-6 Stearate • Cetearyl Alcohol • Sodium Acrylates Copolymer • Octadecenedioic Acid • Diethylhexyl Syringylidenemalonate • Lecithin • Decyl Glucoside • Ethylhexylglycerin • Chlorphenesin • Xanthan Gum • Sclerotium Gum • Ceteareth-20 • Polyglyceryl-6 Behenate • Caprylic/Capric Triglyceride • Propylene Glycol • Sodium Hyaluronate • Tocopherol',
  },
  {
    name: 'Crème de Jour 4 en 1 - Peaux Sèches',
    brand: 'DermEden',
    kind: 'skincare',
    unit: 'pump',
    slug: DERMEDEN_PRODUCT_SLUGS.DAY_PROTOCOLE_SECHE,
    totalAmount: 50,
    amountUnit: 'ml',
    priceCents: 3990,
    description: 'Soin complet anti-âge et anti-taches avec une texture riche pour peaux sèches.',
    notes: "SPF 50+ PA+++. Contient 1% d'Huile d'Avocat.",
    inci: 'Aqua (Water) • Ethylhexyl Methoxycinnamate • Diethylamino Hydroxybenzoyl Hexyl Benzoate • Niacidamide • Diisopropyl Sebacate • Ethylhexyl Triazone • Dimethicone • Bis-Ethylhexyloxyphenol Methoxyphenyl Triazine • Methylene Bis-Benzotriazolyl Tetramethylbutylphenol [Nano] • Pentylene Glycol • Homosalate • Polyglyceryl-6 Stearate • Cetearyl Alcohol • Persea Gratissima (Avocado) Oil • Octadecenedioic Acid • Sodium Acrylates Copolymer • Diethylhexyl Syringylidenemalonate • Decyl Glucoside • Lecithin • Ethylhexylglycerin • Chlorphenesin • Xanthan Gum • Sclerotium Gum • Ceteareth-20 • Polyglyceryl-6 Behenate • Caprylic/Capric Triglyceride • Propylene Glycol • Sodium Hyaluronate • Tocopherol',
  },
  {
    name: 'Crème de Nuit Intense',
    brand: 'DermEden',
    kind: 'skincare',
    unit: 'pump',
    slug: DERMEDEN_PRODUCT_SLUGS.NIGHT_PROTOCOLE_CREME_NUIT_INTENSE,
    totalAmount: 50,
    amountUnit: 'ml',
    priceCents: 5590,
    description:
      "Soin de nuit exfoliant et régénérant pour réduire les signes de l'âge et les taches.",
    notes: "Contient 1% de Rétinol encapsulé et 4% d'Acide Glycolique.",
    inci: 'Aqua (Water) • Coco Caprylate/Caprate • Niacinamide • Cetearyl Alcohol • Caprylic Capric Triglyceride • Dimethicone • Glycolic Acid • Undecane • Glyceryl Stearate • Tridecane • Glycerin • Glyceryl Stearate SE • PEG-100 Stearate • Dimethicone Vinyl Dimethicone Crosspolymer • Parfum (Fragrance) • Octadecenedioic Acid • Sodium Hydroxide • Polyacrylate Crosspolymer-6 • Polysorbate 20 • Ceteareth-20 • Cetyl Palmitate • Cocoglycerides • Ethylhexylglycerin • Chlorphenesin • Hydroxyethyl Acrylate/Sodium Acryloyldimethyl Taurate Copolymer • Salicylic Acid • Tocopheryl Acetate • Caprylic Capric Triglyceride • Hydroxypropyl Cyclodextrin • Disodium EDTA • Retinol • Sorbitan Isostearate • Polysorbate 60 • T-Butyl Alcohol • Sodium Hyaluronate • Tocopherol • Sodium Metabisulfite • Helianthus Annuus Sunflower) Seed Oil',
  },
  {
    name: 'Sérum Intense',
    brand: 'DermEden',
    kind: 'skincare',
    unit: 'pump',
    slug: DERMEDEN_PRODUCT_SLUGS.NIGHT_PROTOCOLE_SERUM_INTENSE,
    totalAmount: 30,
    amountUnit: 'ml',
    priceCents: 6090,
    description: 'Concentré puissant de molécules anti-âge pour une action pro-lift.',
    notes: 'Plus de 14,5% de molécules actives. Effet tenseur immédiat.',
    inci: 'Aqua (Water) • Dimethicone • Niacinamide • Dimethicone/Vinyl Dimethicone Crosspolymer • Glycerin • Sodium Polyacrylate • Octadecenedioic Acid • Polyglyceryl-3 Disiloxane Dimethicone • Phenoxyethanol • Caprylic/Capric Triglyceride • Dimethicone/PEG-10/15 Crosspolymer • Butylene Glycol • Polysorbate 20 • Hexylresorcinol • Chlorphenesin • Ethyl Linoleate • Citric Acid • Alcohol • Hydroxypropyl Cyclodextrin • Disodium EDTA • Sodium Acrylate/Sodium • Acryloyldimethyl Taurate Copolymer • Tocopheryl Acetate • Isohexadecane • Hydrogenated Lecithin • Magnesium Ascorbyl Phosphate • Carbomer • Retinol • Dipropylene Glycol • Polysorbate 80 • Sodium Hyaluronate • Tocopherol • Sodium Citrate • Sorbitan Oleate • Sodium Ascorbate • Palmitoyl Oligopeptide • Palmitoyl Tetrapeptide-7',
  },
  {
    name: 'Soin Contour des Yeux Intense',
    brand: 'DermEden',
    kind: 'skincare',
    unit: 'tube',
    slug: DERMEDEN_PRODUCT_SLUGS.CONTOUR_YEUX_INTENSE,
    totalAmount: 15,
    amountUnit: 'ml',
    priceCents: 3990,
    description: 'Cible les rides, les taches et les cernes de la zone délicate du regard.',
    notes: 'Sans parfum. pH adapté. Contient du Rétinol et de la Vitamine C.',
    inci: 'Aqua (Water) • Propanediol Dicaprylate • Niacinamide • Dimethicone • Coco Caprylate/Caprate • Glyceryl Stearate SE • Glycolic Acid • Isostearyl Alcohol • Cetyl Alcohol • Glyceryl Stearate • Butylene Glycol Cocoate • Polyacrylate Crosspolymer-6 • Octadecenedioic Acid • Sodium Hydroxide • Polyglyceryl-6 Laurate • PEG-75 Stearate • Polysorbate 20 • Polyglyceryl-10 Oleate • Ethylhexylglycerin • Chlorphenesin • Ceteth-20 • Steareth-20 • Tocopheryl Acetate • Caprylic/Capric Triglyceride • Sorbitan Palmitate • Xanthan Gum • 3-O-Ethyl Ascorbic Acid • Ethylcellulose • Hydroxypropyl Cyclodextrin • Magnolol/Honokiol • Retinol • T-Butyl Alcohol • Sodium Hyaluronate • Tocopherol • Sodium Metabisulfite',
  },
  {
    name: 'Soin Réparateur Cicaderm',
    brand: 'DermEden',
    kind: 'skincare',
    unit: 'tube',
    slug: DERMEDEN_PRODUCT_SLUGS.CICADERM_SOIN_REPARATEUR,
    totalAmount: 30,
    amountUnit: 'ml',
    priceCents: 1690,
    description: 'Apaise, assainit et favorise la cicatrisation des peaux fragilisées.',
    notes: 'Texture fluide non grasse. Idéal post-interventions esthétiques.',
    inci: 'Aqua (Water) • Caprylic/Capric Triglyceride • Butylene Glycol • Glycerin • Dimethicone • Cetearyl Alcohol • Propylene Glycol • Zinc Oxide • Polyglyceryl-3 Diisostearate • Octadecenedioic Acid • Hydroxyethyl Acrylate/Sodium Acryloyldimethyl Taurate Copolymer • Glyceryl Stearate SE • PEG-100 Stearate • Chlorphenesin • Tocopheryl Acetate • Ceteareth-20 • Mimosa Tenuiflora Bark Extract • Citric Acid • Sorbitan Isostearate • Polysorbate 60 • Disodium EDTA • Chlorhexidine Digluconate • Arnica Montana Flower Extract • Sodium Hyaluronate • Tocopherol',
  },
  {
    name: 'Crème Mains Action Globale',
    brand: 'DermEden',
    kind: 'skincare',
    unit: 'tube',
    slug: DERMEDEN_PRODUCT_SLUGS.CREME_MAINS_ACTION_GLOBALE,
    totalAmount: 50,
    amountUnit: 'ml',
    priceCents: 1790,
    description: 'Hydrate, prévient les taches et offre une protection anti-bactérienne.',
    notes: 'Contient de la Chlorhexidine et du Zinc.',
    inci: 'Aqua (Water) • Niacinamide • Caprylic/Capric Triglyceride • Isononyl Isononanoate • Cyclopentasiloxane • Dimethicone • Glycerin • Cetearyl Alcohol • Arachidyl Alcohol • Sodium Lactate • Glyceryl Stearate Se • Peg-100 Stearate • Octadecenedioic Acid • Behenyl Alcohol • Carbomer • Arachidyl Glucoside • Zinc Oxide • Chlorphenesin • Ceteareth-20 • Tocopheryl Acetate • Parfum (Fragrance) • Disodium Edta • Sodium Hydroxide • Chlorhexidine Digluconate • Sodium Hyaluronate • Tocopherol',
  },
  {
    name: 'Lait Corps Éclat',
    brand: 'DermEden',
    kind: 'skincare',
    unit: 'bottle',
    slug: DERMEDEN_PRODUCT_SLUGS.LAIT_CORPS_ECLAT,
    totalAmount: 200,
    amountUnit: 'ml',
    priceCents: 2690,
    description: 'Soin nourrissant et repulpant pour le corps avec une action anti-taches.',
    notes: 'Sans parfum. Contient 3% de beurre de Karité.',
    inci: 'Aqua (Water) • Octyldodecanol • Cocoglycerides • Glycerin • Propanediol • Butyrospermum Parkii (Shea) Butter • Cetearyl Alcohol • Helianthus Annuus (Sunflower) Seed Wax • Glyceryl Stearate SE • PEG-100 Stearate • Octadecenedioic Acid • Sodium Polyacrylate • Parfum (Fragrance) • Ceteareth-20 • Ethylhexylglycerin • Chlorphenesin • Tocopheryl Acetate • Sodium Hyaluronate • Tocopherol • BHT',
  },
  {
    name: 'Soin Vergetures Raffermissant',
    brand: 'DermEden',
    kind: 'skincare',
    unit: 'tube',
    slug: DERMEDEN_PRODUCT_SLUGS.SOIN_VERGETURES_RAFFERMISSANT,
    totalAmount: 200,
    amountUnit: 'ml',
    priceCents: 2890,
    description: 'Traitement intensif triple action pour prévenir et atténuer les vergetures.',
    notes: "Contient 2% d'Acide Glycolique et 1% de Rétinol encapsulé.",
    inci: 'Aqua (Water) • Caprylic/Capric Triglyceride • Isononyl Isononanoate • Coco Caprylate/Caprate • Cetearyl Alcohol • Macadamia Integrifolia Seed Oil • Dimethicone • Glyceryl Stearate SE • PEG-100 Stearate • Glycolic Acid • Glycerin • Octadecenedioic Acid • Butylene Glycol • Polyacrylate Crosspolymer-6 • Polysorbate 20 • Ceteareth-20 • Sodium Hydroxide • Parfum (Fragrance) • Vanillyl Butyl Ether • Ethylhexylglycerin • Chlorphenesin • Hydroxyethyl Acrylate/Sodium Acryloyldimethyl Taurate Copolymer • Tocopheryl Acetate • Hydroxypropyl Cyclodextrin • Disodium EDTA • Retinol • Centella Asiatica Leaf Extract • Sorbitan Isostearate • Polysorbate 60 • T-Butyl Alcohol • Sodium Hyaluronate • Tocopherol • Sodium Metabisulfite',
  },
  {
    name: 'Gel Nettoyant Purifiant',
    brand: 'DermEden',
    kind: 'skincare',
    unit: 'bottle',
    slug: DERMEDEN_PRODUCT_SLUGS.GEL_NETTOYANT_PURIFIANT,
    totalAmount: 150,
    amountUnit: 'ml',
    priceCents: 1890,
    description: 'Élimine les impuretés et régule le sébum des peaux mixtes à grasses.',
    notes: 'Sans savon. Contient des micro-particules de silice pour une exfoliation mécanique.',
    inci: 'Aqua (Water) • Sodium Laureth Sulfate • Coco-glucoside • Acrylate Copolymer • Pentylene glycol • Hydrated Silica • Sodium Hydroxyde • Salicylic Acid • Zinc Gluconate • Sodium Benzoate • Chlorphenesin • Bisabolol • Cetrimonium Bromide • Disodium EDTA • Benzotriazoyl Dodecyl P-Cresol • Glycerin • CI 74260 • alcohol • Tris(tetramethylhydroxypiperidinol) citrate • Hydrolyzed Algin • Zinc Sulfate',
  },
  {
    name: 'HA-Like Lotion Micellaire',
    brand: 'DermEden',
    kind: 'skincare',
    unit: 'bottle',
    slug: DERMEDEN_PRODUCT_SLUGS.HA_LIKE_LOTION_MICELLAIRE,
    totalAmount: 200,
    amountUnit: 'ml',
    priceCents: 1790,
    description: 'Démaquille même le waterproof tout en hydratant et détoxifiant la peau.',
    notes: "99% d'origine naturelle. Sans savon, ne colle pas.",
    inci: 'Aqua (water) • Propanediol • Inulin • Caprylyl/capryl glucoside • Sodium benzoate • Caprylyl glycol • Aloe barbadensis leaf juice powder • Citric acid • Parfum (fragrance) • Butylene glycol • Camellia sinensis leaf extract • Codium tomentosum extract',
  },
  {
    name: 'Mousse Nettoyante Antioxydante',
    brand: 'DermEden',
    kind: 'skincare',
    unit: 'bottle',
    slug: DERMEDEN_PRODUCT_SLUGS.MOUSSE_NETTOYANTE_ANTIOXYDANTE,
    totalAmount: 150,
    amountUnit: 'ml',
    priceCents: 1990,
    description:
      "Nettoie en douceur tout en apportant un cocktail d'extraits naturels antioxydants.",
    notes: 'Sans savon. Extraits de concombre, gingembre et thé vert.',
    inci: 'Aqua (Water) • Sodium Laureth Sulfate • PEG-7 Glyceryl Cocoate • Decyl Glucoside • Benzyl Alcohol • Sodium Benzoate • Glycerin • Chlorphenesin • Cucumis Sativus (Cucumber) Fruit Extract • Imidazolidinyl Urea • Parfum (Fragrance) • Citric Acid • O-Cymen-5-Ol • Propylene Glycol • Potassium Sorbate • Zingiber Officinale (Ginger) Root Extract • Rosmarinus Officinalis (Rosemary) Leaf Extract • Camellia Sinensis Leaf Extract • Malpighia Punicifolia (Acerola) Fruit Extract',
  },
  {
    name: 'Masque Exfoliant Détox 2 en 1',
    brand: 'DermEden',
    kind: 'skincare',
    unit: 'jar',
    slug: DERMEDEN_PRODUCT_SLUGS.MASQUE_EXFOLIANT_DETOX,
    totalAmount: 50,
    amountUnit: 'ml',
    priceCents: 2390,
    description: 'Combine gommage mécanique et masque purifiant aux argiles.',
    notes: "Contient 20% d'Argiles et des micro-grains de noyau d'abricot.",
    inci: 'Aqua (Water) • Montmorillonite • Kaolin • Prunus Armeniaca (Apricot) Seed Powder • Cetearyl Alcohol • Glycerin • Decyl Oleate • Cetyl Alcohol • Cetearyl Glucoside • Panthenol • Zinc PCA • Capryloyl Glycine • Tocopheryl Acetate • Ethylhexylglycerin • Maris Sal (Sea Salt) • Tromethamine • Xanthan Gum • Parfum (Fragrance) • Algae Extract • Undecylenoyl Glycine • Lactic Acid • Arginine • Sodium Benzoate • Potassium Sorbate • Tocopherol • Silica • Hydrogenated Palm Glycerides Citrate • Limonene • Hexyl Cinnamal • Linalool • Benzyl Salicylate • Citronellol • Alpha-Isomethyl Ionone • Eugenol',
  },
  {
    name: 'Démaquillant Total Lait-Lotion 2 en 1',
    brand: 'DermEden',
    kind: 'skincare',
    unit: 'bottle',
    slug: DERMEDEN_PRODUCT_SLUGS.DEMAQUILLANT_TOTAL_LAIT_LOTION,
    totalAmount: 150,
    amountUnit: 'ml',
    priceCents: 1690,
    description: 'Nettoie, tonifie et hydrate en un seul geste.',
    notes: 'Élimine les filtres solaires et le maquillage waterproof.',
    inci: 'Aqua (Water) • Isostearyl Isostearate • Cetearyl Alcohol • Ethylhexylglycerin • Carbomer • Chlorphenesin • Ceteareth-20 • Parfum (Fragrance) • Tocopheryl Acetate • Sodium Hydroxide • Disodium EDTA • Tocopherol',
  },
  {
    name: 'Hydra Protocole Crème Légère Matifiante',
    brand: 'DermEden',
    kind: 'skincare',
    unit: 'jar',
    slug: DERMEDEN_PRODUCT_SLUGS.HYDRA_PROTOCOLE_CREME_LEGERE,
    totalAmount: 50,
    amountUnit: 'ml',
    priceCents: 4390,
    description: 'Soin hydratant anti-âge intensif au fini poudré pour peaux mixtes.',
    notes: 'Sans parfum. Non comédogène. Contient 4% de Silice absorbante.',
    inci: 'Aqua • Coco Caprylate Caprate • Gluconolactone • Dimethicone And Dimethicone/Vinyl Dimethicone Crosspolymer • Silica • Cetearyl Olivate • Sorbitan Olivate • Sodium Hydroxyde • Glyceryl Stearate SE • Cetearyl Alcohol • Hydrolyzed Hyaluronic Acid • Sodium Hyaluronate • Tocopheryl Acetate • Ethylhexylglycerin • Ammonium Acryloyldimethyltaurate/VP Copolymer • Chlorphenesin • Xanthan Gum',
  },
  {
    name: 'Hydra Protocole Crème Riche',
    brand: 'DermEden',
    kind: 'skincare',
    unit: 'jar',
    slug: DERMEDEN_PRODUCT_SLUGS.HYDRA_PROTOCOLE_CREME_RICHE,
    totalAmount: 50,
    amountUnit: 'ml',
    priceCents: 4390,
    description: 'Concentré hydratant et nourrissant avec 3% de Phytosqualane.',
    notes: 'Sans parfum. Renforce la barrière cutanée des peaux sèches.',
    inci: 'Aqua • Coco Caprylate Caprate • Helianthus Annuus Seed Oil • Cetearyl Olivate • Sorbitan Olivate • Glycerin • Gluconolactone • C10-18 Triglyceride • Squalan • Cetearyl Alcohol • Sodium Hydroxyde • Glyceryl Stearate SE • Hydrolyzed Hyaluronic Acid • Sodium Hyaluronate • Tocopheryl Acetate • Ammonium Acryloyldimethyltaurate/VP Copolymer • Ethylhexylglycerin • Chlorphenesin',
  },
  {
    name: 'DD Cream SPF 50',
    brand: 'DermEden',
    kind: 'skincare',
    unit: 'pump',
    slug: DERMEDEN_PRODUCT_SLUGS.DD_CREAM,
    totalAmount: 50,
    amountUnit: 'ml',
    priceCents: 4190,
    description: 'Soin de jour teinté protecteur (UV/Lumière bleue) et stimulateur de Vitamine D.',
    notes: "Contient des micro-pigments encapsulés qui s'adaptent à la carnation.",
    inci: 'Aqua (Water) • Ethylhexyl Methoxycinnamate • Diethylamino Hydroxybenzoyl Hexyl Benzoate • Caprylyl Caprylate/Caprate • C12-15 Alkyl Benzoate • Methylene Bis-Benzotriazolyl Tetramethylbutylphenol • Caprylic/Capric Triglyceride • Bis-Ethylhexyloxyphenol Methoxyphenyl Triazine • Ethylhexyl Triazone • Cetearyl Alcohol • Propylene Glycol Laurate • Dimethicone • Glycerin • Talc • Glyceryl Stearate SE • PEG-100 Stearate • Octadecenedioic Acid • Sodium Polyacrylate • CI 77891 (Titanium Dioxide) • Mannitol • CI 77492 (Iron Oxide) • Decyl Glucoside • Dimethicone/Vinyl Dimethicone Crosspolymer • Diethylhexyl Syringylidenemalonate • Ethylhexylglycerin • Ceteareth-20 • Chlorphenesin • Hydrogenated Lecithin • Cichorium Intybus (Chicory) Root Extract • Ethylcellulose • Propylene Glycol Isostearate • Polymethyl Methacrylate • CI 77491(Iron Oxide) • Disodium EDTA • Propylene Glycol • Aluminum Hydroxide • CI 77499 (Iron Oxide) • Xanthan Gum • Phenoxyethanol • Sodium Hyaluronate • BHT • Tocopherol • Helianthus Annuus (Sunflower) Seed Oil',
  },
  {
    name: 'Concentré Repulpant et Hydratant 15%',
    brand: 'DermEden',
    kind: 'skincare',
    unit: 'dropper',
    slug: DERMEDEN_PRODUCT_SLUGS.CONCENTRE_REPULPANT_15,
    totalAmount: 30,
    amountUnit: 'ml',
    priceCents: 6290,
    description: "Effet filler dès 30 minutes grâce à 10% d'anti-hyaluronidase.",
    notes: "Idéal en post-injections d'acide hyaluronique.",
    inci: 'Aqua (Water) • Glycerin • 1.2-hexanediol • Sucrose palmitate • Polysorbate 20 • Yeast extract (Anti-Hyaluronidase) • Sodium hyaluronate • Sodium acetylated hyaluronate • Tocopherol • Glyceryl linoleate • Helianthus annuus (Sunflower) seed oil • Parfum (Fragrance) • Xanthan gum • Caprylyl glycol • CI 42090',
  },
  {
    name: 'Concentré Rétinoïdes Nuit 6%',
    brand: 'DermEden',
    kind: 'skincare',
    unit: 'pump',
    slug: DERMEDEN_PRODUCT_SLUGS.CONCENTRE_RETINOIDES_6,
    totalAmount: 30,
    amountUnit: 'ml',
    priceCents: 6290,
    description: 'Traitement anti-âge intensif avec duo de Rétinal et Rétinol.',
    notes:
      "Usage nuit uniquement. Formule puissante mais adaptée aux peaux sensibles grâce à l'encapsulation.",
    inci: 'Glycerin • Aqua (Water) • 1.2-hexanediol • Polysorbate 20 • Retinal (Retinaldehyde) • Retinol • Tocopherol • Lecithin • Pentylene glycol • Helianthus annuus (Sunflower) seed oil • Xanthan gum • Parfum (Fragrance) • Potassium phosphate • Alcohol • CI 19140',
  },
]
