import { TAG_SLUGS } from '../../tags/seed-tags'
import { AZ_PRODUCT_SLUGS } from './aromaZone'

export const AZ_PRODUCT_TAGS: { productSlug: string; tagSlug: string }[] = [
  // Sérum Concentré Acide Azélaïque 10%
  { productSlug: AZ_PRODUCT_SLUGS.AROMA_ZONE_CONCENTRE_AZELAIC_10, tagSlug: TAG_SLUGS.ANTI_ACNE },
  {
    productSlug: AZ_PRODUCT_SLUGS.AROMA_ZONE_CONCENTRE_AZELAIC_10,
    tagSlug: TAG_SLUGS.ANTI_ROUGEURS,
  },
  {
    productSlug: AZ_PRODUCT_SLUGS.AROMA_ZONE_CONCENTRE_AZELAIC_10,
    tagSlug: TAG_SLUGS.SEBO_REGULATEUR,
  },
  { productSlug: AZ_PRODUCT_SLUGS.AROMA_ZONE_CONCENTRE_AZELAIC_10, tagSlug: TAG_SLUGS.BRILLANCE },
  { productSlug: AZ_PRODUCT_SLUGS.AROMA_ZONE_CONCENTRE_AZELAIC_10, tagSlug: TAG_SLUGS.SERUM },
  { productSlug: AZ_PRODUCT_SLUGS.AROMA_ZONE_CONCENTRE_AZELAIC_10, tagSlug: TAG_SLUGS.BIO_NATUREL },
  { productSlug: AZ_PRODUCT_SLUGS.AROMA_ZONE_CONCENTRE_AZELAIC_10, tagSlug: TAG_SLUGS.SANS_PARFUM },

  // Sérum Concentré Vitamine C 10% & Astaxanthine
  {
    productSlug: AZ_PRODUCT_SLUGS.AZ_SERUM_VITAMINE_C_10_ASTAXANTHINE,
    tagSlug: TAG_SLUGS.ANTI_OXYDANT,
  },
  { productSlug: AZ_PRODUCT_SLUGS.AZ_SERUM_VITAMINE_C_10_ASTAXANTHINE, tagSlug: TAG_SLUGS.ECLAT },
  {
    productSlug: AZ_PRODUCT_SLUGS.AZ_SERUM_VITAMINE_C_10_ASTAXANTHINE,
    tagSlug: TAG_SLUGS.ANTI_TACHES,
  },
  {
    productSlug: AZ_PRODUCT_SLUGS.AZ_SERUM_VITAMINE_C_10_ASTAXANTHINE,
    tagSlug: TAG_SLUGS.ANTI_AGE,
  },
  { productSlug: AZ_PRODUCT_SLUGS.AZ_SERUM_VITAMINE_C_10_ASTAXANTHINE, tagSlug: TAG_SLUGS.SERUM },
  { productSlug: AZ_PRODUCT_SLUGS.AZ_SERUM_VITAMINE_C_10_ASTAXANTHINE, tagSlug: TAG_SLUGS.VEGAN },
  {
    productSlug: AZ_PRODUCT_SLUGS.AZ_SERUM_VITAMINE_C_10_ASTAXANTHINE,
    tagSlug: TAG_SLUGS.BIO_NATUREL,
  },

  // Sérum Bakuchiol
  { productSlug: AZ_PRODUCT_SLUGS.AZ_SERUM_BAKUCHIOL, tagSlug: TAG_SLUGS.ANTI_AGE },
  { productSlug: AZ_PRODUCT_SLUGS.AZ_SERUM_BAKUCHIOL, tagSlug: TAG_SLUGS.SERUM },
  { productSlug: AZ_PRODUCT_SLUGS.AZ_SERUM_BAKUCHIOL, tagSlug: TAG_SLUGS.HUILE },
  { productSlug: AZ_PRODUCT_SLUGS.AZ_SERUM_BAKUCHIOL, tagSlug: TAG_SLUGS.PEAU_REACTIVE },
  { productSlug: AZ_PRODUCT_SLUGS.AZ_SERUM_BAKUCHIOL, tagSlug: TAG_SLUGS.VEGAN },
  { productSlug: AZ_PRODUCT_SLUGS.AZ_SERUM_BAKUCHIOL, tagSlug: TAG_SLUGS.SANS_PARFUM },
  { productSlug: AZ_PRODUCT_SLUGS.AZ_SERUM_BAKUCHIOL, tagSlug: TAG_SLUGS.BIO_NATUREL },
]
