import { INGREDIENT_SLUGS } from '../ingredients/ingredient-slugs'
import { TAG_SLUGS } from '../tags/seed-tags'

export interface IngredientAssociation {
  /** Tags principaux : bénéfices majeurs prouvés de l'actif */
  primary: string[]
  /** Tags secondaires : bénéfices d'accompagnement ou cibles spécifiques */
  secondary: string[]
  /** Tags d'exclusion : types de peau ou conditions où l'actif est déconseillé */
  avoid: string[]
}

export type IngredientTagMap = Record<string, IngredientAssociation>

export const ingredientTagMap: IngredientTagMap = {
  [INGREDIENT_SLUGS.ULVA_LACTUCA]: {
    primary: [TAG_SLUGS.REPULPANT, TAG_SLUGS.GRAIN_PEAU, TAG_SLUGS.ANTI_AGE],
    secondary: [TAG_SLUGS.PEAU_RUGUEUSE, TAG_SLUGS.BARRIERE_CUTANEE, TAG_SLUGS.PEAU_NORMALE],
    avoid: [],
  },
  [INGREDIENT_SLUGS.CHLORELLA_VULGARIS]: {
    primary: [TAG_SLUGS.CERNES_POCHES, TAG_SLUGS.ANTI_AGE, TAG_SLUGS.REPARATEUR],
    secondary: [TAG_SLUGS.POLLUTION, TAG_SLUGS.MICROBIOME, TAG_SLUGS.ZONE_YEUX],
    avoid: [],
  },
  [INGREDIENT_SLUGS.SPIRULINA_PLATENSIS]: {
    primary: [TAG_SLUGS.ANTI_OXYDANT, TAG_SLUGS.TEINT_TERNE, TAG_SLUGS.POLLUTION],
    secondary: [TAG_SLUGS.ECLAT, TAG_SLUGS.REPARATEUR, TAG_SLUGS.PEAU_TOUS_TYPES],
    avoid: [],
  },
  [INGREDIENT_SLUGS.DUNALIELLA_SALINA]: {
    primary: [TAG_SLUGS.ANTI_OXYDANT, TAG_SLUGS.ECLAT, TAG_SLUGS.PHOTO_VIEILLISSEMENT],
    secondary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.LUMIERE_BLEUE, TAG_SLUGS.TEINT_TERNE],
    avoid: [],
  },
  [INGREDIENT_SLUGS.CHONDRUS_CRISPUS]: {
    primary: [TAG_SLUGS.HUMECTANT, TAG_SLUGS.PROTECTION_CUTANEE, TAG_SLUGS.DESHYDRATATION],
    secondary: [TAG_SLUGS.EMOLLIENT, TAG_SLUGS.PEAU_SENSIBLE, TAG_SLUGS.GRAIN_PEAU],
    avoid: [],
  },
  [INGREDIENT_SLUGS.PALMARIA_PALMATA]: {
    primary: [TAG_SLUGS.ECLAT, TAG_SLUGS.ANTI_ROUGEURS, TAG_SLUGS.TEINT_TERNE],
    secondary: [TAG_SLUGS.ANTI_TACHES, TAG_SLUGS.PHOTO_VIEILLISSEMENT, TAG_SLUGS.PEAU_TOUS_TYPES],
    avoid: [],
  },
  [INGREDIENT_SLUGS.JANIA_RUBENS]: {
    primary: [TAG_SLUGS.HUMECTANT, TAG_SLUGS.ECLAT, TAG_SLUGS.DESHYDRATATION],
    secondary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.PEAU_REACTIVE, TAG_SLUGS.TEINT_TERNE],
    avoid: [],
  },
  [INGREDIENT_SLUGS.LAMINARIA_DIGITATA]: {
    primary: [TAG_SLUGS.HUMECTANT, TAG_SLUGS.DESHYDRATATION, TAG_SLUGS.APAISANT],
    secondary: [TAG_SLUGS.BARRIERE_CUTANEE, TAG_SLUGS.PEAU_MIXTE, TAG_SLUGS.REPARATEUR],
    avoid: [],
  },
  [INGREDIENT_SLUGS.FUCUS_VESICULOSUS]: {
    primary: [TAG_SLUGS.CERNES_POCHES, TAG_SLUGS.POLLUTION, TAG_SLUGS.ANTI_OXYDANT],
    secondary: [TAG_SLUGS.ZONE_YEUX, TAG_SLUGS.TEINT_TERNE, TAG_SLUGS.PEAU_GRASSE],
    avoid: [],
  },
  [INGREDIENT_SLUGS.ALARIA_ESCULENTA]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.REPULPANT, TAG_SLUGS.ANTI_OXYDANT],
    secondary: [TAG_SLUGS.PEAU_SECHE, TAG_SLUGS.PEAU_REACTIVE, TAG_SLUGS.GRAIN_PEAU],
    avoid: [],
  },
  [INGREDIENT_SLUGS.UNDARIA_PINNATIFIDA]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.ANTI_OXYDANT, TAG_SLUGS.REPARATEUR],
    secondary: [TAG_SLUGS.REPULPANT, TAG_SLUGS.PROTECTION_CUTANEE, TAG_SLUGS.PEAU_TOUS_TYPES],
    avoid: [],
  },
  [INGREDIENT_SLUGS.NMN]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.REPARATEUR, TAG_SLUGS.ECLAT],
    secondary: [TAG_SLUGS.BIOMIMETIQUE, TAG_SLUGS.PHOTO_VIEILLISSEMENT, TAG_SLUGS.PEAU_TOUS_TYPES],
    avoid: [],
  },
  [INGREDIENT_SLUGS.MYRTUS_COMMUNIS_LEAF_EXTRACT]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.ANTI_OXYDANT, TAG_SLUGS.TEINT_TERNE],
    secondary: [TAG_SLUGS.ASTRINGENT, TAG_SLUGS.POLLUTION, TAG_SLUGS.PEAU_NORMALE],
    avoid: [],
  },
  [INGREDIENT_SLUGS.TRIPTERYGIUM_WILFORDII_CALLUS_EXTRACT]: {
    primary: [TAG_SLUGS.APAISANT, TAG_SLUGS.REPARATEUR, TAG_SLUGS.ANTI_AGE],
    secondary: [
      TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE,
      TAG_SLUGS.PEAU_REACTIVE,
      TAG_SLUGS.PEAU_SENSIBLE,
    ],
    avoid: [],
  },
  [INGREDIENT_SLUGS.CAPRYLIC_CAPRIC_TRIGLYCERIDE]: {
    primary: [TAG_SLUGS.EMOLLIENT, TAG_SLUGS.BARRIERE_CUTANEE, TAG_SLUGS.PEAU_SENSIBLE],
    secondary: [TAG_SLUGS.NON_COMEDOGENE, TAG_SLUGS.BIOMIMETIQUE, TAG_SLUGS.PEAU_TOUS_TYPES],
    avoid: [],
  },

  [INGREDIENT_SLUGS.POSTBIOTICS]: {
    primary: [
      TAG_SLUGS.REPARATEUR,
      TAG_SLUGS.BARRIERE_CUTANEE,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.MICROBIOME,
    ],
    secondary: [
      TAG_SLUGS.NON_COMEDOGENE,
      TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE,
      TAG_SLUGS.PEAU_TOUS_TYPES,
    ],
    avoid: [],
  },
  [INGREDIENT_SLUGS.HUILE_COLZA]: {
    primary: [TAG_SLUGS.PEAU_SECHE, TAG_SLUGS.PEAU_ATOPIQUE, TAG_SLUGS.REPARATEUR],
    secondary: [
      TAG_SLUGS.ECZEMA,
      TAG_SLUGS.ANTI_OXYDANT,
      TAG_SLUGS.TEXTURE_RICHE,
      TAG_SLUGS.GROSSESSE_COMPATIBLE,
    ],
    avoid: [],
  },

  [INGREDIENT_SLUGS.BUTYLENE_GLYCOL]: {
    primary: [TAG_SLUGS.HUMECTANT, TAG_SLUGS.DESHYDRATATION],
    secondary: [TAG_SLUGS.TEXTURE_LEGERE, TAG_SLUGS.PEAU_TOUS_TYPES],
    avoid: [],
  },

  [INGREDIENT_SLUGS.EXTRAIT_CAMOMILLE]: {
    primary: [TAG_SLUGS.APAISANT, TAG_SLUGS.ANTI_ROUGEURS, TAG_SLUGS.PEAU_REACTIVE],
    secondary: [TAG_SLUGS.PEAU_SENSIBLE, TAG_SLUGS.BIO_NATUREL, TAG_SLUGS.GROSSESSE_COMPATIBLE],
    avoid: [],
  },

  [INGREDIENT_SLUGS.EXTRAIT_EPILOBE]: {
    primary: [TAG_SLUGS.SEBO_REGULATEUR, TAG_SLUGS.MATIFIANT, TAG_SLUGS.PORES_DILATES],
    secondary: [
      TAG_SLUGS.ANTI_ACNE,
      TAG_SLUGS.BRILLANCE,
      TAG_SLUGS.PEAU_GRASSE,
      TAG_SLUGS.PEAU_MIXTE,
    ],
    avoid: [],
  },

  [INGREDIENT_SLUGS.ENDOTHELYOL]: {
    primary: [TAG_SLUGS.ANTI_ROUGEURS, TAG_SLUGS.COUPEROSE],
    secondary: [TAG_SLUGS.ROSACEE, TAG_SLUGS.APAISANT],
    avoid: [],
  },

  [INGREDIENT_SLUGS.DIETHYLAMINO_HYDROXYBENZOYL_HEXYL_BENZOATE]: {
    primary: [TAG_SLUGS.PROTECTION_SOLAIRE, TAG_SLUGS.ANTI_AGE],
    secondary: [TAG_SLUGS.FILTRES_CHIMIQUES],
    avoid: [],
  },

  [INGREDIENT_SLUGS.ETHYLHEXYL_TRIAZONE]: {
    primary: [TAG_SLUGS.PROTECTION_SOLAIRE],
    secondary: [TAG_SLUGS.FILTRES_CHIMIQUES],
    avoid: [],
  },

  [INGREDIENT_SLUGS.BRIMONIDINE]: {
    primary: [TAG_SLUGS.ANTI_ROUGEURS, TAG_SLUGS.FLUSHS],
    secondary: [TAG_SLUGS.COUPEROSE, TAG_SLUGS.ROSACEE],
    avoid: [TAG_SLUGS.PEAU_REACTIVE],
  },

  [INGREDIENT_SLUGS.IVERMECTINE]: {
    primary: [TAG_SLUGS.ROSACEE, TAG_SLUGS.ANTI_ACNE],
    secondary: [TAG_SLUGS.APAISANT, TAG_SLUGS.MICROBIOME],
    avoid: [],
  },

  [INGREDIENT_SLUGS.METRONIDAZOLE]: {
    primary: [TAG_SLUGS.ROSACEE, TAG_SLUGS.ANTISEPTIQUE],
    secondary: [TAG_SLUGS.ANTI_ROUGEURS, TAG_SLUGS.ANTI_ACNE],
    avoid: [],
  },

  [INGREDIENT_SLUGS.OXYMETAZOLINE]: {
    primary: [TAG_SLUGS.ANTI_ROUGEURS, TAG_SLUGS.FLUSHS],
    secondary: [TAG_SLUGS.COUPEROSE],
    avoid: [],
  },

  [INGREDIENT_SLUGS.ACETYL_DIPEPTIDE_1_CETYL_ESTER]: {
    primary: [TAG_SLUGS.PEAU_REACTIVE, TAG_SLUGS.APAISANT],
    secondary: [TAG_SLUGS.PEAU_SENSIBLE, TAG_SLUGS.FLUSHS],
    avoid: [],
  },

  [INGREDIENT_SLUGS.ADENOSINE]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.REPARATEUR, TAG_SLUGS.REPULPANT],
    secondary: [TAG_SLUGS.APAISANT, TAG_SLUGS.PEAU_SENSIBLE],
    avoid: [],
  },

  [INGREDIENT_SLUGS.ALPHA_GLUCAN_OLIGOSACCHARIDE]: {
    primary: [TAG_SLUGS.MICROBIOME, TAG_SLUGS.PREBIOTIQUE],
    secondary: [TAG_SLUGS.BARRIERE_CUTANEE, TAG_SLUGS.BIOMIMETIQUE, TAG_SLUGS.PEAU_ATOPIQUE],
    avoid: [],
  },

  [INGREDIENT_SLUGS.ANGIOPAUSINE]: {
    primary: [TAG_SLUGS.ANTI_ROUGEURS, TAG_SLUGS.ROSACEE],
    secondary: [TAG_SLUGS.COUPEROSE],
    avoid: [],
  },

  [INGREDIENT_SLUGS.AQUAPHILUS_DOLOMIAE_EXTRACT]: {
    primary: [TAG_SLUGS.PEAU_ATOPIQUE, TAG_SLUGS.PEAU_REACTIVE],
    secondary: [TAG_SLUGS.ANTI_ROUGEURS, TAG_SLUGS.APAISANT],
    avoid: [],
  },

  [INGREDIENT_SLUGS.AQUAPHILUS_DOLOMIAE_FERMENT_FILTRATE]: {
    primary: [TAG_SLUGS.REPARATEUR, TAG_SLUGS.CICATRISATION],
    secondary: [TAG_SLUGS.POST_ACNE, TAG_SLUGS.BARRIERE_CUTANEE],
    avoid: [],
  },

  [INGREDIENT_SLUGS.ARGININE_PCA]: {
    primary: [TAG_SLUGS.HUMECTANT, TAG_SLUGS.DESHYDRATATION],
    secondary: [TAG_SLUGS.BIOMIMETIQUE],
    avoid: [],
  },

  [INGREDIENT_SLUGS.CALCIUM_PCA]: {
    primary: [TAG_SLUGS.BARRIERE_CUTANEE, TAG_SLUGS.PEAU_SECHE],
    secondary: [TAG_SLUGS.EMOLLIENT],
    avoid: [],
  },

  [INGREDIENT_SLUGS.COLLAGEN_AMINO_ACIDS]: {
    primary: [TAG_SLUGS.HUMECTANT, TAG_SLUGS.ANTI_AGE],
    secondary: [],
    avoid: [],
  },

  [INGREDIENT_SLUGS.COMEDOCLASTIN]: {
    primary: [TAG_SLUGS.ANTI_ACNE, TAG_SLUGS.SEBO_REGULATEUR],
    secondary: [TAG_SLUGS.NON_COMEDOGENE, TAG_SLUGS.BRILLANCE],
    avoid: [TAG_SLUGS.PEAU_SECHE, TAG_SLUGS.PEAU_ATOPIQUE],
  },

  [INGREDIENT_SLUGS.COPPER_SULFATE]: {
    primary: [TAG_SLUGS.ANTISEPTIQUE, TAG_SLUGS.ANTI_ACNE],
    secondary: [TAG_SLUGS.ANTI_ROUGEURS],
    avoid: [TAG_SLUGS.PEAU_REACTIVE, TAG_SLUGS.PEAU_SENSIBLE],
  },

  [INGREDIENT_SLUGS.CURCUMA_LONGA_ROOT_EXTRACT]: {
    primary: [TAG_SLUGS.ANTI_OXYDANT, TAG_SLUGS.ECLAT],
    secondary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.TEINT_TERNE],
    avoid: [],
  },

  [INGREDIENT_SLUGS.D_SENSINOSE]: {
    primary: [TAG_SLUGS.PEAU_REACTIVE, TAG_SLUGS.APAISANT],
    secondary: [TAG_SLUGS.PEAU_SENSIBLE, TAG_SLUGS.HYPOALLERGENIQUE],
    avoid: [],
  },

  [INGREDIENT_SLUGS.ECTOIN]: {
    primary: [TAG_SLUGS.BARRIERE_CUTANEE, TAG_SLUGS.PEAU_REACTIVE],
    secondary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.DESHYDRATATION],
    avoid: [],
  },

  [INGREDIENT_SLUGS.GLYCERYL_GLUCOSIDE]: {
    primary: [TAG_SLUGS.DESHYDRATATION, TAG_SLUGS.HUMECTANT],
    secondary: [],
    avoid: [],
  },

  [INGREDIENT_SLUGS.HUILE_ONAGRE]: {
    primary: [TAG_SLUGS.PEAU_SECHE, TAG_SLUGS.PEAU_ATOPIQUE],
    secondary: [TAG_SLUGS.ZONE_CORPS, TAG_SLUGS.ZONE_VISAGE, TAG_SLUGS.EMOLLIENT],
    avoid: [TAG_SLUGS.PEAU_GRASSE, TAG_SLUGS.COMEDOGENE, TAG_SLUGS.ANTI_ACNE],
  },

  [INGREDIENT_SLUGS.IRON_OXIDE]: {
    primary: [TAG_SLUGS.PROTECTION_SOLAIRE, TAG_SLUGS.HYPERPIGMENTATION],
    secondary: [],
    avoid: [],
  },

  [INGREDIENT_SLUGS.LENS_ESCULENTA_SEED_EXTRACT]: {
    primary: [TAG_SLUGS.PORES_DILATES, TAG_SLUGS.SEBO_REGULATEUR],
    secondary: [TAG_SLUGS.BRILLANCE],
    avoid: [TAG_SLUGS.PEAU_SECHE],
  },

  [INGREDIENT_SLUGS.MALIC_ACID_ESTER]: {
    primary: [TAG_SLUGS.EXFOLIANT_CHIMIQUE, TAG_SLUGS.EXFOLIATION, TAG_SLUGS.ECLAT],
    secondary: [TAG_SLUGS.TEINT_TERNE],
    avoid: [TAG_SLUGS.PEAU_REACTIVE, TAG_SLUGS.ROSACEE],
  },

  [INGREDIENT_SLUGS.MELITANE]: {
    primary: [TAG_SLUGS.HYPERPIGMENTATION, TAG_SLUGS.PROTECTION_SOLAIRE],
    secondary: [TAG_SLUGS.ANTI_TACHES],
    avoid: [],
  },

  [INGREDIENT_SLUGS.PALMITAMIDE_MEA]: {
    primary: [TAG_SLUGS.PEAU_ATOPIQUE, TAG_SLUGS.BARRIERE_CUTANEE],
    secondary: [TAG_SLUGS.PEAU_SENSIBLE, TAG_SLUGS.APAISANT],
    avoid: [],
  },

  [INGREDIENT_SLUGS.PAPAIN]: {
    primary: [TAG_SLUGS.EXFOLIANT_CHIMIQUE, TAG_SLUGS.EXFOLIATION, TAG_SLUGS.ECLAT],
    secondary: [TAG_SLUGS.KERATOLYTIQUE, TAG_SLUGS.TEINT_TERNE],
    avoid: [TAG_SLUGS.PEAU_REACTIVE, TAG_SLUGS.PEAU_SENSIBLE],
  },

  [INGREDIENT_SLUGS.PIROCTONE_OLAMINE]: {
    primary: [TAG_SLUGS.ANTISEPTIQUE],
    secondary: [TAG_SLUGS.ANTI_ACNE],
    avoid: [],
  },

  [INGREDIENT_SLUGS.PRUNUS_AMYGDALUS_DULCIS_OIL]: {
    primary: [TAG_SLUGS.EMOLLIENT, TAG_SLUGS.APAISANT, TAG_SLUGS.HUILE_VISAGE],
    secondary: [TAG_SLUGS.PEAU_SECHE, TAG_SLUGS.TEXTURE_RICHE],
    avoid: [TAG_SLUGS.PEAU_GRASSE, TAG_SLUGS.ANTI_ACNE, TAG_SLUGS.COMEDOGENE],
  },

  [INGREDIENT_SLUGS.RESVERATROL]: {
    primary: [TAG_SLUGS.ANTI_OXYDANT, TAG_SLUGS.ANTI_AGE],
    secondary: [TAG_SLUGS.ECLAT, TAG_SLUGS.PHOTO_VIEILLISSEMENT, TAG_SLUGS.ANTI_ROUGEURS],
    avoid: [],
  },

  [INGREDIENT_SLUGS.HUILE_DE_RICIN]: {
    primary: [TAG_SLUGS.HUILE_VISAGE, TAG_SLUGS.OCCLUSIF],
    secondary: [TAG_SLUGS.REPARATEUR],
    avoid: [TAG_SLUGS.PEAU_GRASSE, TAG_SLUGS.COMEDOGENE, TAG_SLUGS.ANTI_ACNE],
  },

  [INGREDIENT_SLUGS.SEPIWHITE]: {
    primary: [TAG_SLUGS.ANTI_TACHES, TAG_SLUGS.HYPERPIGMENTATION],
    secondary: [TAG_SLUGS.ECLAT, TAG_SLUGS.TEINT_TERNE],
    avoid: [TAG_SLUGS.PEAU_REACTIVE],
  },

  [INGREDIENT_SLUGS.SODIUM_PCA]: {
    primary: [TAG_SLUGS.HUMECTANT, TAG_SLUGS.DESHYDRATATION],
    secondary: [TAG_SLUGS.BARRIERE_CUTANEE, TAG_SLUGS.BIOMIMETIQUE],
    avoid: [],
  },

  [INGREDIENT_SLUGS.CHARDON_MARIE]: {
    primary: [TAG_SLUGS.ANTI_OXYDANT, TAG_SLUGS.ANTI_ACNE],
    secondary: [
      TAG_SLUGS.ROSACEE,
      TAG_SLUGS.COUPEROSE,
      TAG_SLUGS.PHOTO_VIEILLISSEMENT,
      TAG_SLUGS.ANTI_ROUGEURS,
      TAG_SLUGS.SEBO_REGULATEUR,
      TAG_SLUGS.PEAU_SENSIBLE,
    ],
    avoid: [],
  },
  [INGREDIENT_SLUGS.TITANIUM_DIOXIDE]: {
    primary: [TAG_SLUGS.PROTECTION_SOLAIRE, TAG_SLUGS.FILTRES_MINERAUX],
    secondary: [],
    avoid: [],
  },

  [INGREDIENT_SLUGS.TOCOPHERYL_GLUCOSIDE]: {
    primary: [TAG_SLUGS.ANTI_OXYDANT, TAG_SLUGS.ANTI_AGE],
    secondary: [TAG_SLUGS.PEAU_SENSIBLE],
    avoid: [],
  },

  [INGREDIENT_SLUGS.TRIASORB]: {
    primary: [TAG_SLUGS.PROTECTION_SOLAIRE, TAG_SLUGS.LUMIERE_BLEUE],
    secondary: [TAG_SLUGS.ANTI_TACHES],
    avoid: [],
  },

  [INGREDIENT_SLUGS.ZINC_OXIDE]: {
    primary: [TAG_SLUGS.PROTECTION_SOLAIRE, TAG_SLUGS.FILTRES_MINERAUX],
    secondary: [TAG_SLUGS.ANTI_ROUGEURS, TAG_SLUGS.APAISANT],
    avoid: [],
  },

  [INGREDIENT_SLUGS.ZINC_PCA]: {
    primary: [TAG_SLUGS.SEBO_REGULATEUR, TAG_SLUGS.ANTI_ACNE],
    secondary: [TAG_SLUGS.MATIFIANT, TAG_SLUGS.HUMECTANT, TAG_SLUGS.BRILLANCE],
    avoid: [TAG_SLUGS.PEAU_SECHE],
  },

  [INGREDIENT_SLUGS.ZINC_SULFATE]: {
    primary: [TAG_SLUGS.ANTISEPTIQUE, TAG_SLUGS.ANTI_ACNE],
    secondary: [TAG_SLUGS.ANTI_ROUGEURS],
    avoid: [TAG_SLUGS.PEAU_REACTIVE],
  },

  // --- VITAMIN C ---
  [INGREDIENT_SLUGS.VITAMIN_C]: {
    primary: [TAG_SLUGS.ANTI_OXYDANT, TAG_SLUGS.ECLAT, TAG_SLUGS.ANTI_TACHES],
    secondary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.HYPERPIGMENTATION],
    avoid: [
      TAG_SLUGS.PEAU_REACTIVE,
      TAG_SLUGS.ROSACEE,
      TAG_SLUGS.COUPEROSE,
      TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE,
      TAG_SLUGS.PEAU_SENSIBLE,
    ],
  },

  // --- 3-O-ETHYL ASCORBIC ACID ---
  [INGREDIENT_SLUGS.THREE_O_ETHYL_ASCORBIC_ACID]: {
    primary: [TAG_SLUGS.ECLAT, TAG_SLUGS.ANTI_TACHES, TAG_SLUGS.HYPERPIGMENTATION],
    secondary: [TAG_SLUGS.ANTI_OXYDANT, TAG_SLUGS.ANTI_AGE],
    avoid: [],
  },

  // --- ASCORBYL GLUCOSIDE ---
  [INGREDIENT_SLUGS.ASCORBYL_GLUCOSIDE]: {
    primary: [TAG_SLUGS.ECLAT, TAG_SLUGS.PEAU_SENSIBLE, TAG_SLUGS.TEINT_TERNE],
    secondary: [TAG_SLUGS.ANTI_OXYDANT, TAG_SLUGS.ANTI_TACHES],
    avoid: [],
  },

  // --- ASCORBYL PALMITATE ---
  [INGREDIENT_SLUGS.ASCORBYL_PALMITATE]: {
    primary: [TAG_SLUGS.ANTI_OXYDANT, TAG_SLUGS.PEAU_SECHE, TAG_SLUGS.TEXTURE_RICHE],
    secondary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.ECLAT],
    avoid: [TAG_SLUGS.PEAU_GRASSE, TAG_SLUGS.BRILLANCE],
  },

  // --- MAGNESIUM ASCORBYL PHOSPHATE (MAP) ---
  [INGREDIENT_SLUGS.MAGNESIUM_ASCORBYL_PHOSPHATE]: {
    primary: [TAG_SLUGS.PEAU_SENSIBLE, TAG_SLUGS.ANTI_TACHES, TAG_SLUGS.HYPERPIGMENTATION],
    secondary: [TAG_SLUGS.ANTI_OXYDANT, TAG_SLUGS.ANTI_ACNE, TAG_SLUGS.ECLAT, TAG_SLUGS.REPULPANT],
    avoid: [],
  },

  // --- SODIUM ASCORBYL PHOSPHATE (SAP) ---
  [INGREDIENT_SLUGS.SODIUM_ASCORBYL_PHOSPHATE]: {
    primary: [TAG_SLUGS.ANTI_ACNE, TAG_SLUGS.SEBO_REGULATEUR, TAG_SLUGS.PEAU_GRASSE],
    secondary: [
      TAG_SLUGS.ANTI_OXYDANT,
      TAG_SLUGS.PEAU_MIXTE,
      TAG_SLUGS.HYPERPIGMENTATION,
      TAG_SLUGS.POST_ACNE,
    ],
    avoid: [],
  },

  // --- THD ASCORBATE ---
  [INGREDIENT_SLUGS.THD_ASCORBATE]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.HYPERPIGMENTATION, TAG_SLUGS.PHOTO_VIEILLISSEMENT],
    secondary: [TAG_SLUGS.PEAU_SECHE, TAG_SLUGS.ANTI_OXYDANT, TAG_SLUGS.ECLAT],
    avoid: [TAG_SLUGS.PEAU_GRASSE, TAG_SLUGS.COMEDOGENE],
  },

  // --- ALPHA ARBUTIN ---
  [INGREDIENT_SLUGS.ALPHA_ARBUTIN]: {
    primary: [TAG_SLUGS.ANTI_TACHES, TAG_SLUGS.HYPERPIGMENTATION, TAG_SLUGS.ECLAT],
    secondary: [
      TAG_SLUGS.POST_ACNE,
      TAG_SLUGS.PHOTO_VIEILLISSEMENT,
      TAG_SLUGS.TEINT_TERNE,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.PEAU_REACTIVE,
    ],
    avoid: [],
  },

  // --- BOSWELLIA SERRATA ---
  [INGREDIENT_SLUGS.BOSWELLIA_SERRATA]: {
    primary: [
      TAG_SLUGS.APAISANT,
      TAG_SLUGS.ANTI_ROUGEURS,
      TAG_SLUGS.ROSACEE,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.COUPEROSE,
    ],
    secondary: [
      TAG_SLUGS.ANTI_OXYDANT,
      TAG_SLUGS.REPARATEUR,
      TAG_SLUGS.ECZEMA,
      TAG_SLUGS.BARRIERE_CUTANEE,
      TAG_SLUGS.BIOMIMETIQUE,
      TAG_SLUGS.GROSSESSE_COMPATIBLE,
    ],
    avoid: [],
  },

  // --- ZINGIBER OFFICINALE ---
  [INGREDIENT_SLUGS.ZINGIBER_OFFICINALE]: {
    primary: [TAG_SLUGS.ANTI_OXYDANT, TAG_SLUGS.APAISANT],
    secondary: [
      TAG_SLUGS.ECLAT,
      TAG_SLUGS.ANTI_AGE,
      TAG_SLUGS.ANTI_ACNE,
      TAG_SLUGS.PEAU_GRASSE,
      TAG_SLUGS.NON_COMEDOGENE,
    ],
    avoid: [
      TAG_SLUGS.PEAU_REACTIVE,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.ROSACEE,
      TAG_SLUGS.COUPEROSE,
    ],
  },

  // --- CITRUS LIMON FRUIT WATER ---
  [INGREDIENT_SLUGS.CITRUS_LIMON_FRUIT_WATER]: {
    primary: [
      TAG_SLUGS.EXFOLIANT_CHIMIQUE,
      TAG_SLUGS.EXFOLIATION,
      TAG_SLUGS.ECLAT,
      TAG_SLUGS.MICROBIOME,
      TAG_SLUGS.PEAU_GRASSE,
    ],
    secondary: [
      TAG_SLUGS.ANTI_ACNE,
      TAG_SLUGS.POST_ACNE,
      TAG_SLUGS.ANTI_OXYDANT,
      TAG_SLUGS.NON_COMEDOGENE,
      TAG_SLUGS.SEBO_REGULATEUR,
      TAG_SLUGS.ANTI_BACTERIEN,
    ],
    avoid: [
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.GROSSESSE_COMPATIBLE,
      TAG_SLUGS.ECZEMA,
      TAG_SLUGS.ROSACEE,
      TAG_SLUGS.COUPEROSE,
    ],
  },

  // --- MORINDA CITRIFOLIA (NONI) ---
  [INGREDIENT_SLUGS.MORINDA_CITRIFOLIA]: {
    primary: [
      TAG_SLUGS.ANTI_OXYDANT,
      TAG_SLUGS.REPARATEUR,
      TAG_SLUGS.ANTI_AGE,
      TAG_SLUGS.PORES_DILATES,
    ],
    secondary: [
      TAG_SLUGS.APAISANT,
      TAG_SLUGS.HUMECTANT,
      TAG_SLUGS.ECLAT,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.PEAU_TOUS_TYPES,
    ],
    avoid: [],
  },

  // --- PROTEOGLYCAN COMPLEX ---
  [INGREDIENT_SLUGS.PROTEOGLYCAN_COMPLEX]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.HUMECTANT],
    secondary: [
      TAG_SLUGS.ECLAT,
      TAG_SLUGS.REPARATEUR,
      TAG_SLUGS.BARRIERE_CUTANEE,
      TAG_SLUGS.PEAU_SECHE,
    ],
    avoid: [],
  },

  // --- KOJIC ACID ---
  [INGREDIENT_SLUGS.KOJIC_ACID]: {
    primary: [TAG_SLUGS.ANTI_TACHES, TAG_SLUGS.HYPERPIGMENTATION, TAG_SLUGS.ECLAT],
    secondary: [
      TAG_SLUGS.POST_ACNE,
      TAG_SLUGS.TEINT_TERNE,
      TAG_SLUGS.PHOTO_VIEILLISSEMENT,
      TAG_SLUGS.ANTI_OXYDANT,
      TAG_SLUGS.ANTISEPTIQUE,
    ],
    avoid: [
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.PEAU_REACTIVE,
      TAG_SLUGS.PEAU_ATOPIQUE,
      TAG_SLUGS.ECZEMA,
    ],
  },

  // --- TRANEXAMIC ACID ---
  [INGREDIENT_SLUGS.TRANEXAMIC_ACID]: {
    primary: [TAG_SLUGS.HYPERPIGMENTATION, TAG_SLUGS.ANTI_TACHES],
    secondary: [TAG_SLUGS.ROSACEE, TAG_SLUGS.ANTI_ROUGEURS, TAG_SLUGS.ECLAT],
    avoid: [],
  },

  // --- GLUTATHION ---
  [INGREDIENT_SLUGS.GLUTATHION]: {
    primary: [TAG_SLUGS.ANTI_OXYDANT, TAG_SLUGS.ECLAT],
    secondary: [TAG_SLUGS.ANTI_TACHES, TAG_SLUGS.HYPERPIGMENTATION, TAG_SLUGS.ANTI_AGE],
    avoid: [],
  },

  // --- AZELAIC ACID ---
  [INGREDIENT_SLUGS.AZELAIC_ACID]: {
    primary: [
      TAG_SLUGS.ROSACEE,
      TAG_SLUGS.ANTI_ACNE,
      TAG_SLUGS.ANTI_ROUGEURS,
      TAG_SLUGS.ANTI_BACTERIEN,
    ],
    secondary: [
      TAG_SLUGS.HYPERPIGMENTATION,
      TAG_SLUGS.POST_ACNE,
      TAG_SLUGS.ANTI_TACHES,
      TAG_SLUGS.SEBO_REGULATEUR,
      TAG_SLUGS.COUPEROSE,
      TAG_SLUGS.KERATOLYTIQUE,
      TAG_SLUGS.ECLAT,
      TAG_SLUGS.PORES_DILATES,
      TAG_SLUGS.MICROBIOME,
      TAG_SLUGS.MATIFIANT,
      TAG_SLUGS.GROSSESSE_COMPATIBLE,
    ],
    avoid: [TAG_SLUGS.PEAU_REACTIVE, TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE],
  },

  // --- NIACINAMIDE ---
  [INGREDIENT_SLUGS.NIACINAMIDE]: {
    primary: [
      TAG_SLUGS.BARRIERE_CUTANEE,
      TAG_SLUGS.APAISANT,
      TAG_SLUGS.SEBO_REGULATEUR,
      TAG_SLUGS.ANTI_ROUGEURS,
      TAG_SLUGS.ANTI_TACHES,
    ],
    secondary: [
      TAG_SLUGS.ANTI_ACNE,
      TAG_SLUGS.PORES_DILATES,
      TAG_SLUGS.ECLAT,
      TAG_SLUGS.ANTI_OXYDANT,
      TAG_SLUGS.ANTI_AGE,
      TAG_SLUGS.HYPERPIGMENTATION,
      TAG_SLUGS.POST_ACNE,
      TAG_SLUGS.PEAU_MIXTE,
      TAG_SLUGS.PEAU_GRASSE,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.PEAU_REACTIVE,
      TAG_SLUGS.GROSSESSE_COMPATIBLE,
    ],
    avoid: [],
  },

  // --- CENTELLA ASIATICA ---
  [INGREDIENT_SLUGS.CENTELLA_ASIATICA]: {
    primary: [TAG_SLUGS.REPARATEUR, TAG_SLUGS.APAISANT, TAG_SLUGS.ANTI_ROUGEURS],
    secondary: [
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.BARRIERE_CUTANEE,
      TAG_SLUGS.ANTI_ACNE,
      TAG_SLUGS.POST_ACNE,
      TAG_SLUGS.ECLAT,
      TAG_SLUGS.BIO_NATUREL,
    ],
    avoid: [],
  },

  // --- ASIATICOSIDE ---
  [INGREDIENT_SLUGS.ASIATICOSIDE]: {
    primary: [TAG_SLUGS.REPARATEUR, TAG_SLUGS.CICATRISATION, TAG_SLUGS.ANTI_AGE],
    secondary: [
      TAG_SLUGS.BARRIERE_CUTANEE,
      TAG_SLUGS.PEAU_REACTIVE,
      TAG_SLUGS.ROSACEE,
      TAG_SLUGS.ANTI_ROUGEURS,
      TAG_SLUGS.HYPOALLERGENIQUE,
      TAG_SLUGS.PHOTO_VIEILLISSEMENT,
      TAG_SLUGS.BIOMIMETIQUE,
    ],
    avoid: [],
  },

  // --- PANTHENOL ---
  [INGREDIENT_SLUGS.PANTHENOL]: {
    primary: [TAG_SLUGS.REPARATEUR, TAG_SLUGS.HUMECTANT, TAG_SLUGS.BARRIERE_CUTANEE],
    secondary: [
      TAG_SLUGS.APAISANT,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.ANTI_ROUGEURS,
      TAG_SLUGS.PEAU_ATOPIQUE,
      TAG_SLUGS.PEAU_REACTIVE,
      TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE,
      TAG_SLUGS.BIOMIMETIQUE,
    ],
    avoid: [],
  },

  // --- ALLANTOIN ---
  [INGREDIENT_SLUGS.ALLANTOIN]: {
    primary: [TAG_SLUGS.APAISANT, TAG_SLUGS.PEAU_REACTIVE, TAG_SLUGS.PROTECTION_CUTANEE],
    secondary: [
      TAG_SLUGS.REPARATEUR,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.BARRIERE_CUTANEE,
      TAG_SLUGS.ANTI_ROUGEURS,
      TAG_SLUGS.CICATRISATION,
      TAG_SLUGS.POST_ACNE,
      TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE,
      TAG_SLUGS.HYPOALLERGENIQUE,
    ],
    avoid: [],
  },

  // --- REGLISSE ---
  [INGREDIENT_SLUGS.REGLISSE]: {
    primary: [TAG_SLUGS.ANTI_ROUGEURS, TAG_SLUGS.APAISANT, TAG_SLUGS.ROSACEE],
    secondary: [
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.SEBO_REGULATEUR,
      TAG_SLUGS.PEAU_REACTIVE,
      TAG_SLUGS.ANTI_TACHES,
      TAG_SLUGS.ANTI_ACNE,
      TAG_SLUGS.ANTI_OXYDANT,
    ],
    avoid: [],
  },

  // --- HEARTLEAF ---
  [INGREDIENT_SLUGS.HEARTLEAF]: {
    primary: [TAG_SLUGS.APAISANT, TAG_SLUGS.ANTI_ACNE],
    secondary: [
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.ANTI_ROUGEURS,
      TAG_SLUGS.SEBO_REGULATEUR,
      TAG_SLUGS.HUMECTANT,
    ],
    avoid: [],
  },

  // --- AVENA SATIVA ---
  [INGREDIENT_SLUGS.AVENA_SATIVA]: {
    primary: [TAG_SLUGS.PEAU_SENSIBLE, TAG_SLUGS.APAISANT, TAG_SLUGS.PEAU_ATOPIQUE],
    secondary: [
      TAG_SLUGS.ANTI_ROUGEURS,
      TAG_SLUGS.REPARATEUR,
      TAG_SLUGS.BARRIERE_CUTANEE,
      TAG_SLUGS.PEAU_REACTIVE,
      TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE,
      TAG_SLUGS.MICROBIOME,
      TAG_SLUGS.BIO_NATUREL,
    ],
    avoid: [],
  },

  // --- CALENDULA ---
  [INGREDIENT_SLUGS.CALENDULA]: {
    primary: [TAG_SLUGS.REPARATEUR, TAG_SLUGS.APAISANT],
    secondary: [TAG_SLUGS.PEAU_SENSIBLE, TAG_SLUGS.BIO_NATUREL],
    avoid: [],
  },

  // --- GREEN TEA ---
  [INGREDIENT_SLUGS.GREEN_TEA]: {
    primary: [TAG_SLUGS.ANTI_OXYDANT, TAG_SLUGS.SEBO_REGULATEUR, TAG_SLUGS.APAISANT],
    secondary: [
      TAG_SLUGS.ANTI_ROUGEURS,
      TAG_SLUGS.ANTI_AGE,
      TAG_SLUGS.ANTI_ACNE,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.PEAU_GRASSE,
      TAG_SLUGS.PEAU_MIXTE,
      TAG_SLUGS.ECLAT,
      TAG_SLUGS.POLLUTION,
      TAG_SLUGS.PHOTO_VIEILLISSEMENT,
      TAG_SLUGS.BIO_NATUREL,
    ],
    avoid: [],
  },

  // --- ALOE VERA ---
  [INGREDIENT_SLUGS.ALOE_VERA]: {
    primary: [TAG_SLUGS.HUMECTANT, TAG_SLUGS.APAISANT],
    secondary: [TAG_SLUGS.PEAU_SENSIBLE, TAG_SLUGS.ANTI_ROUGEURS, TAG_SLUGS.REPARATEUR],
    avoid: [],
  },

  // --- HYALURONIC ACID ---
  [INGREDIENT_SLUGS.HYALURONIC_ACID]: {
    primary: [TAG_SLUGS.HUMECTANT, TAG_SLUGS.DESHYDRATATION, TAG_SLUGS.REPULPANT],
    secondary: [
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.ANTI_AGE,
      TAG_SLUGS.ECLAT,
      TAG_SLUGS.BARRIERE_CUTANEE,
      TAG_SLUGS.BIOMIMETIQUE,
    ],
    avoid: [],
  },

  // --- SODIUM HYALURONATE ---
  [INGREDIENT_SLUGS.SODIUM_HYALURONATE]: {
    primary: [TAG_SLUGS.HUMECTANT, TAG_SLUGS.DESHYDRATATION, TAG_SLUGS.BIOMIMETIQUE],
    secondary: [
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.ANTI_AGE,
      TAG_SLUGS.REPULPANT,
      TAG_SLUGS.BARRIERE_CUTANEE,
      TAG_SLUGS.TEXTURE_LEGERE,
    ],
    avoid: [],
  },

  // --- POLYGLUTAMIC ACID ---
  [INGREDIENT_SLUGS.POLYGLUTAMIC_ACID]: {
    primary: [TAG_SLUGS.HUMECTANT, TAG_SLUGS.DESHYDRATATION, TAG_SLUGS.REPULPANT],
    secondary: [
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.ANTI_AGE,
      TAG_SLUGS.ECLAT,
      TAG_SLUGS.BARRIERE_CUTANEE,
      TAG_SLUGS.CICATRISATION,
      TAG_SLUGS.BIO_NATUREL,
    ],
    avoid: [],
  },

  // --- ARGIRELINE ---
  [INGREDIENT_SLUGS.ARGIRELINE]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.REPULPANT],
    secondary: [
      TAG_SLUGS.BIOMIMETIQUE,
      TAG_SLUGS.PHOTO_VIEILLISSEMENT,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.DESHYDRATATION,
    ],
    avoid: [TAG_SLUGS.EXFOLIANT_CHIMIQUE, TAG_SLUGS.EXFOLIATION],
  },

  // --- BAKUCHIOL ---
  [INGREDIENT_SLUGS.BAKUCHIOL]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.PEAU_SENSIBLE, TAG_SLUGS.REPULPANT],
    secondary: [
      TAG_SLUGS.ANTI_ACNE,
      TAG_SLUGS.ECLAT,
      TAG_SLUGS.ANTI_TACHES,
      TAG_SLUGS.HYPERPIGMENTATION,
      TAG_SLUGS.PHOTO_VIEILLISSEMENT,
      TAG_SLUGS.PEAU_REACTIVE,
      TAG_SLUGS.ANTI_OXYDANT,
      TAG_SLUGS.APAISANT,
      TAG_SLUGS.BIO_NATUREL,
    ],
    avoid: [],
  },
  [INGREDIENT_SLUGS.BEEF_TALLOW]: {
    primary: [TAG_SLUGS.PEAU_SECHE, TAG_SLUGS.OCCLUSIF],
    secondary: [TAG_SLUGS.BARRIERE_CUTANEE, TAG_SLUGS.EMOLLIENT, TAG_SLUGS.HUMECTANT],
    avoid: [TAG_SLUGS.PEAU_GRASSE, TAG_SLUGS.ANTI_ACNE, TAG_SLUGS.COMEDOGENE],
  },

  [INGREDIENT_SLUGS.CERAMIDE_AP]: {
    primary: [TAG_SLUGS.BARRIERE_CUTANEE, TAG_SLUGS.REPARATEUR],
    secondary: [
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.PEAU_REACTIVE,
      TAG_SLUGS.PEAU_ATOPIQUE,
      TAG_SLUGS.BIOMIMETIQUE,
    ],
    avoid: [],
  },

  [INGREDIENT_SLUGS.CERAMIDE_EOP]: {
    primary: [TAG_SLUGS.BARRIERE_CUTANEE, TAG_SLUGS.REPARATEUR],
    secondary: [
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.PEAU_REACTIVE,
      TAG_SLUGS.PEAU_ATOPIQUE,
      TAG_SLUGS.BIOMIMETIQUE,
    ],
    avoid: [],
  },

  [INGREDIENT_SLUGS.CERAMIDE_NP]: {
    primary: [TAG_SLUGS.BARRIERE_CUTANEE, TAG_SLUGS.REPARATEUR],
    secondary: [
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.PEAU_REACTIVE,
      TAG_SLUGS.PEAU_ATOPIQUE,
      TAG_SLUGS.BIOMIMETIQUE,
    ],
    avoid: [],
  },

  [INGREDIENT_SLUGS.CERAMIDE_NS]: {
    primary: [TAG_SLUGS.BARRIERE_CUTANEE, TAG_SLUGS.REPARATEUR],
    secondary: [
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.PEAU_REACTIVE,
      TAG_SLUGS.PEAU_ATOPIQUE,
      TAG_SLUGS.BIOMIMETIQUE,
    ],
    avoid: [],
  },

  [INGREDIENT_SLUGS.CERAMIDES]: {
    primary: [TAG_SLUGS.BARRIERE_CUTANEE, TAG_SLUGS.REPARATEUR],
    secondary: [
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.PEAU_REACTIVE,
      TAG_SLUGS.PEAU_ATOPIQUE,
      TAG_SLUGS.BIOMIMETIQUE,
    ],
    avoid: [],
  },

  [INGREDIENT_SLUGS.CHOLESTEROL]: {
    primary: [TAG_SLUGS.BARRIERE_CUTANEE, TAG_SLUGS.EMOLLIENT],
    secondary: [TAG_SLUGS.PEAU_SECHE, TAG_SLUGS.REPARATEUR, TAG_SLUGS.BIOMIMETIQUE],
    avoid: [],
  },

  [INGREDIENT_SLUGS.ESCIN]: {
    primary: [TAG_SLUGS.ANTI_ROUGEURS, TAG_SLUGS.ROSACEE, TAG_SLUGS.CERNES_POCHES],
    secondary: [
      TAG_SLUGS.ZONE_YEUX,
      TAG_SLUGS.PEAU_REACTIVE,
      TAG_SLUGS.ECLAT,
      TAG_SLUGS.APAISANT,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.COUPEROSE,
      TAG_SLUGS.ANTI_OXYDANT,
      TAG_SLUGS.BIO_NATUREL,
    ],
    avoid: [],
  },

  [INGREDIENT_SLUGS.GLYCOSPHINGOLIPIDS]: {
    primary: [TAG_SLUGS.BARRIERE_CUTANEE, TAG_SLUGS.PEAU_SECHE],
    secondary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.ANTI_OXYDANT],
    avoid: [],
  },

  [INGREDIENT_SLUGS.HUILE_ARGOUSIER]: {
    primary: [TAG_SLUGS.ANTI_OXYDANT, TAG_SLUGS.REPARATEUR],
    secondary: [
      TAG_SLUGS.ANTI_AGE,
      TAG_SLUGS.BARRIERE_CUTANEE,
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.HUILE_VISAGE,
    ],
    avoid: [],
  },

  [INGREDIENT_SLUGS.PLANKTON_EXTRACT]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.ANTI_OXYDANT],
    secondary: [TAG_SLUGS.BARRIERE_CUTANEE, TAG_SLUGS.REPARATEUR, TAG_SLUGS.HUMECTANT],
    avoid: [],
  },

  [INGREDIENT_SLUGS.RHAMNOSE]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.PEAU_SENSIBLE],
    secondary: [TAG_SLUGS.BARRIERE_CUTANEE, TAG_SLUGS.ANTI_ROUGEURS, TAG_SLUGS.APAISANT],
    avoid: [],
  },

  [INGREDIENT_SLUGS.RUSCUS_ACULEATUS]: {
    primary: [
      TAG_SLUGS.ANTI_ROUGEURS,
      TAG_SLUGS.COUPEROSE,
      TAG_SLUGS.ROSACEE,
      TAG_SLUGS.FLUSHS,
      TAG_SLUGS.APAISANT,
    ],
    secondary: [
      TAG_SLUGS.CERNES_POCHES,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.PEAU_REACTIVE,
      TAG_SLUGS.MICROBIOME,
      TAG_SLUGS.ANTI_OXYDANT,
      TAG_SLUGS.BARRIERE_CUTANEE,
      TAG_SLUGS.ECLAT,
    ],
    avoid: [],
  },

  [INGREDIENT_SLUGS.SCHISANDRA]: {
    primary: [TAG_SLUGS.ANTI_OXYDANT, TAG_SLUGS.APAISANT],
    secondary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.ANTI_ROUGEURS, TAG_SLUGS.PEAU_SENSIBLE],
    avoid: [],
  },

  [INGREDIENT_SLUGS.SHEA_BUTTER]: {
    primary: [TAG_SLUGS.PEAU_SECHE, TAG_SLUGS.EMOLLIENT],
    secondary: [
      TAG_SLUGS.BARRIERE_CUTANEE,
      TAG_SLUGS.REPARATEUR,
      TAG_SLUGS.PEAU_ATOPIQUE,
      TAG_SLUGS.OCCLUSIF,
      TAG_SLUGS.PEAU_SENSIBLE,
    ],
    avoid: [TAG_SLUGS.PEAU_GRASSE, TAG_SLUGS.ANTI_ACNE, TAG_SLUGS.COMEDOGENE],
  },

  [INGREDIENT_SLUGS.SNOW_MUSHROOM]: {
    primary: [TAG_SLUGS.HUMECTANT, TAG_SLUGS.DESHYDRATATION],
    secondary: [
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.BARRIERE_CUTANEE,
      TAG_SLUGS.ANTI_AGE,
      TAG_SLUGS.ECLAT,
      TAG_SLUGS.PEAU_SENSIBLE,
    ],
    avoid: [],
  },

  [INGREDIENT_SLUGS.SULFUR]: {
    primary: [TAG_SLUGS.ANTI_ACNE, TAG_SLUGS.KERATOLYTIQUE, TAG_SLUGS.SEBO_REGULATEUR],
    secondary: [
      TAG_SLUGS.ANTISEPTIQUE,
      TAG_SLUGS.ROSACEE,
      TAG_SLUGS.ANTI_ROUGEURS,
      TAG_SLUGS.PEAU_GRASSE,
      TAG_SLUGS.PEAU_MIXTE,
      TAG_SLUGS.BRILLANCE,
      TAG_SLUGS.PORES_DILATES,
    ],
    avoid: [
      TAG_SLUGS.PEAU_REACTIVE,
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE,
      TAG_SLUGS.PEAU_SENSIBLE,
    ],
  },

  [INGREDIENT_SLUGS.SPHINGOMONAS_FERMENT]: {
    primary: [TAG_SLUGS.MICROBIOME, TAG_SLUGS.BARRIERE_CUTANEE],
    secondary: [
      TAG_SLUGS.HUMECTANT,
      TAG_SLUGS.REPARATEUR,
      TAG_SLUGS.ANTI_AGE,
      TAG_SLUGS.ANTI_OXYDANT,
      TAG_SLUGS.PEAU_SENSIBLE,
    ],
    avoid: [],
  },

  [INGREDIENT_SLUGS.SQUALANE]: {
    primary: [TAG_SLUGS.EMOLLIENT, TAG_SLUGS.BARRIERE_CUTANEE, TAG_SLUGS.BIOMIMETIQUE],
    secondary: [
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.REPARATEUR,
      TAG_SLUGS.DESHYDRATATION,
      TAG_SLUGS.NON_COMEDOGENE,
      TAG_SLUGS.TEXTURE_LEGERE,
      TAG_SLUGS.PEAU_REACTIVE,
      TAG_SLUGS.HYPOALLERGENIQUE,
    ],
    avoid: [],
  },

  [INGREDIENT_SLUGS.SYN_AKE]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.REPULPANT],
    secondary: [TAG_SLUGS.ECLAT, TAG_SLUGS.PHOTO_VIEILLISSEMENT],
    avoid: [],
  },

  [INGREDIENT_SLUGS.MATRIXYL_3000]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.REPULPANT],
    secondary: [TAG_SLUGS.ECLAT, TAG_SLUGS.BARRIERE_CUTANEE, TAG_SLUGS.PHOTO_VIEILLISSEMENT],
    avoid: [],
  },

  [INGREDIENT_SLUGS.PALMITOYL_TRIPEPTIDE_1]: {
    primary: [TAG_SLUGS.ANTI_AGE],
    secondary: [TAG_SLUGS.BARRIERE_CUTANEE, TAG_SLUGS.REPARATEUR],
    avoid: [],
  },

  [INGREDIENT_SLUGS.PALMITOYL_TETRAPEPTIDE_7]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.ANTI_ROUGEURS],
    secondary: [TAG_SLUGS.REPARATEUR, TAG_SLUGS.APAISANT],
    avoid: [],
  },

  [INGREDIENT_SLUGS.PALMITOYL_PENTAPEPTIDE_4]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.REPARATEUR],
    secondary: [TAG_SLUGS.ECLAT, TAG_SLUGS.BARRIERE_CUTANEE],
    avoid: [],
  },

  [INGREDIENT_SLUGS.COPPER_PEPTIDES]: {
    primary: [TAG_SLUGS.REPARATEUR, TAG_SLUGS.ANTI_AGE, TAG_SLUGS.REPULPANT],
    secondary: [
      TAG_SLUGS.CICATRISATION,
      TAG_SLUGS.ANTI_OXYDANT,
      TAG_SLUGS.BARRIERE_CUTANEE,
      TAG_SLUGS.PHOTO_VIEILLISSEMENT,
    ],
    avoid: [TAG_SLUGS.PEAU_REACTIVE, TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE],
  },

  [INGREDIENT_SLUGS.PEPTIDES]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.BARRIERE_CUTANEE, TAG_SLUGS.REPULPANT],
    secondary: [
      TAG_SLUGS.REPARATEUR,
      TAG_SLUGS.CICATRISATION,
      TAG_SLUGS.PHOTO_VIEILLISSEMENT,
      TAG_SLUGS.BIOMIMETIQUE,
    ],
    avoid: [],
  },

  [INGREDIENT_SLUGS.RETINOL]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.ANTI_ACNE],
    secondary: [
      TAG_SLUGS.ECLAT,
      TAG_SLUGS.ANTI_TACHES,
      TAG_SLUGS.KERATOLYTIQUE,
      TAG_SLUGS.HYPERPIGMENTATION,
      TAG_SLUGS.PHOTO_VIEILLISSEMENT,
      TAG_SLUGS.TEINT_TERNE,
      TAG_SLUGS.PORES_DILATES,
      TAG_SLUGS.REPULPANT,
    ],
    avoid: [
      TAG_SLUGS.PEAU_REACTIVE,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.ROSACEE,
      TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE,
      TAG_SLUGS.PROTECTION_SOLAIRE,
    ],
  },

  [INGREDIENT_SLUGS.RETINAL]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.ANTI_ACNE],
    secondary: [
      TAG_SLUGS.ECLAT,
      TAG_SLUGS.ANTI_TACHES,
      TAG_SLUGS.KERATOLYTIQUE,
      TAG_SLUGS.ANTI_ROUGEURS,
      TAG_SLUGS.HYPERPIGMENTATION,
      TAG_SLUGS.PHOTO_VIEILLISSEMENT,
      TAG_SLUGS.PORES_DILATES,
      TAG_SLUGS.REPULPANT,
    ],
    avoid: [
      TAG_SLUGS.PEAU_REACTIVE,
      TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE,
      TAG_SLUGS.PROTECTION_SOLAIRE,
    ],
  },

  [INGREDIENT_SLUGS.SALICYLIC_ACID]: {
    primary: [
      TAG_SLUGS.ANTI_ACNE,
      TAG_SLUGS.EXFOLIANT_CHIMIQUE,
      TAG_SLUGS.EXFOLIATION,
      TAG_SLUGS.PORES_DILATES,
    ],
    secondary: [
      TAG_SLUGS.SEBO_REGULATEUR,
      TAG_SLUGS.KERATOLYTIQUE,
      TAG_SLUGS.PEAU_GRASSE,
      TAG_SLUGS.BRILLANCE,
      TAG_SLUGS.POST_ACNE,
      TAG_SLUGS.PEAU_MIXTE,
      TAG_SLUGS.NON_COMEDOGENE,
    ],
    avoid: [TAG_SLUGS.PEAU_SECHE, TAG_SLUGS.PEAU_REACTIVE, TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE],
  },

  [INGREDIENT_SLUGS.GLYCOLIC_ACID]: {
    primary: [TAG_SLUGS.EXFOLIANT_CHIMIQUE, TAG_SLUGS.EXFOLIATION, TAG_SLUGS.ECLAT],
    secondary: [
      TAG_SLUGS.ANTI_AGE,
      TAG_SLUGS.ANTI_TACHES,
      TAG_SLUGS.HYPERPIGMENTATION,
      TAG_SLUGS.KERATOLYTIQUE,
      TAG_SLUGS.PORES_DILATES,
      TAG_SLUGS.TEINT_TERNE,
      TAG_SLUGS.PHOTO_VIEILLISSEMENT,
    ],
    avoid: [
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.PEAU_REACTIVE,
      TAG_SLUGS.ROSACEE,
      TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE,
      TAG_SLUGS.PROTECTION_SOLAIRE,
    ],
  },

  [INGREDIENT_SLUGS.LACTIC_ACID]: {
    primary: [
      TAG_SLUGS.EXFOLIANT_CHIMIQUE,
      TAG_SLUGS.EXFOLIATION,
      TAG_SLUGS.HUMECTANT,
      TAG_SLUGS.ECLAT,
    ],
    secondary: [
      TAG_SLUGS.ANTI_AGE,
      TAG_SLUGS.KERATOLYTIQUE,
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.BIOMIMETIQUE,
      TAG_SLUGS.TEINT_TERNE,
      TAG_SLUGS.HYPERPIGMENTATION,
    ],
    avoid: [TAG_SLUGS.PEAU_REACTIVE, TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE],
  },

  [INGREDIENT_SLUGS.MANDELIC_ACID]: {
    primary: [
      TAG_SLUGS.EXFOLIANT_CHIMIQUE,
      TAG_SLUGS.EXFOLIATION,
      TAG_SLUGS.ANTI_ACNE,
      TAG_SLUGS.PEAU_SENSIBLE,
    ],
    secondary: [
      TAG_SLUGS.ANTI_TACHES,
      TAG_SLUGS.KERATOLYTIQUE,
      TAG_SLUGS.POST_ACNE,
      TAG_SLUGS.HYPERPIGMENTATION,
      TAG_SLUGS.TEXTURE_LEGERE,
    ],
    avoid: [TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE],
  },

  [INGREDIENT_SLUGS.PHA]: {
    primary: [
      TAG_SLUGS.EXFOLIANT_CHIMIQUE,
      TAG_SLUGS.EXFOLIATION,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.HUMECTANT,
    ],
    secondary: [
      TAG_SLUGS.BARRIERE_CUTANEE,
      TAG_SLUGS.ECLAT,
      TAG_SLUGS.ANTI_AGE,
      TAG_SLUGS.KERATOLYTIQUE,
      TAG_SLUGS.PEAU_REACTIVE,
      TAG_SLUGS.ROSACEE,
    ],
    avoid: [TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE],
  },

  [INGREDIENT_SLUGS.UREA]: {
    primary: [TAG_SLUGS.HUMECTANT, TAG_SLUGS.KERATOLYTIQUE],
    secondary: [
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.EMOLLIENT,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.PEAU_ATOPIQUE,
      TAG_SLUGS.BARRIERE_CUTANEE,
      TAG_SLUGS.REPARATEUR,
      TAG_SLUGS.BIOMIMETIQUE,
    ],
    avoid: [TAG_SLUGS.PEAU_REACTIVE, TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE],
  },

  [INGREDIENT_SLUGS.GLYCERIN]: {
    primary: [TAG_SLUGS.HUMECTANT, TAG_SLUGS.DESHYDRATATION],
    secondary: [TAG_SLUGS.PEAU_SECHE, TAG_SLUGS.BARRIERE_CUTANEE, TAG_SLUGS.BIOMIMETIQUE],
    avoid: [],
  },

  [INGREDIENT_SLUGS.PDRN]: {
    primary: [TAG_SLUGS.REPARATEUR, TAG_SLUGS.ANTI_AGE],
    secondary: [TAG_SLUGS.BARRIERE_CUTANEE, TAG_SLUGS.PEAU_SENSIBLE, TAG_SLUGS.CICATRISATION],
    avoid: [],
  },

  [INGREDIENT_SLUGS.HYPOCHLOROUS_ACID]: {
    primary: [TAG_SLUGS.ANTISEPTIQUE, TAG_SLUGS.ANTI_ACNE, TAG_SLUGS.APAISANT],
    secondary: [
      TAG_SLUGS.ANTI_ROUGEURS,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.REPARATEUR,
      TAG_SLUGS.PEAU_REACTIVE,
      TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE,
      TAG_SLUGS.POST_ACNE,
      TAG_SLUGS.ECZEMA,
      TAG_SLUGS.MICROBIOME,
    ],
    avoid: [],
  },

  [INGREDIENT_SLUGS.PROBIOTICS]: {
    primary: [TAG_SLUGS.MICROBIOME, TAG_SLUGS.BARRIERE_CUTANEE],
    secondary: [TAG_SLUGS.PEAU_SENSIBLE, TAG_SLUGS.ANTI_ROUGEURS, TAG_SLUGS.PREBIOTIQUE],
    avoid: [],
  },
  [INGREDIENT_SLUGS.PHYTOSPHINGOSINE]: {
    primary: [TAG_SLUGS.BARRIERE_CUTANEE, TAG_SLUGS.ANTI_ACNE],
    secondary: [TAG_SLUGS.PEAU_SENSIBLE, TAG_SLUGS.REPARATEUR, TAG_SLUGS.BIOMIMETIQUE],
    avoid: [],
  },

  [INGREDIENT_SLUGS.PENTYLENE_GLYCOL]: {
    primary: [TAG_SLUGS.HUMECTANT],
    secondary: [TAG_SLUGS.PEAU_SENSIBLE, TAG_SLUGS.ANTISEPTIQUE],
    avoid: [],
  },

  [INGREDIENT_SLUGS.TOCOPHEROL]: {
    primary: [TAG_SLUGS.ANTI_OXYDANT, TAG_SLUGS.ANTI_AGE],
    secondary: [TAG_SLUGS.BARRIERE_CUTANEE, TAG_SLUGS.EMOLLIENT, TAG_SLUGS.PEAU_SENSIBLE],
    avoid: [],
  },

  [INGREDIENT_SLUGS.VACCINIUM_MYRTILLUS]: {
    primary: [TAG_SLUGS.ANTI_OXYDANT, TAG_SLUGS.ANTI_ROUGEURS],
    secondary: [TAG_SLUGS.ECLAT, TAG_SLUGS.TEINT_TERNE],
    avoid: [],
  },

  [INGREDIENT_SLUGS.OPHIOPOGON_JAPONICUS]: {
    primary: [TAG_SLUGS.PEAU_SENSIBLE, TAG_SLUGS.REPARATEUR],
    secondary: [TAG_SLUGS.HUMECTANT, TAG_SLUGS.BARRIERE_CUTANEE],
    avoid: [],
  },

  [INGREDIENT_SLUGS.HUMECTANTS_EMOLLIENTS_OCCLUSIFS]: {
    primary: [TAG_SLUGS.PEAU_SECHE, TAG_SLUGS.BARRIERE_CUTANEE],
    secondary: [TAG_SLUGS.HUMECTANT, TAG_SLUGS.EMOLLIENT, TAG_SLUGS.OCCLUSIF],
    avoid: [],
  },

  [INGREDIENT_SLUGS.HUILE_D_ARGAN]: {
    primary: [TAG_SLUGS.PEAU_SECHE, TAG_SLUGS.ANTI_AGE],
    secondary: [TAG_SLUGS.EMOLLIENT, TAG_SLUGS.ANTI_OXYDANT, TAG_SLUGS.ZONE_CORPS],
    avoid: [TAG_SLUGS.PEAU_GRASSE, TAG_SLUGS.ANTI_ACNE],
  },

  [INGREDIENT_SLUGS.HUILE_DE_JOJOBA]: {
    primary: [TAG_SLUGS.SEBO_REGULATEUR, TAG_SLUGS.PEAU_MIXTE],
    secondary: [
      TAG_SLUGS.PEAU_GRASSE,
      TAG_SLUGS.EMOLLIENT,
      TAG_SLUGS.ZONE_VISAGE,
      TAG_SLUGS.ZONE_CORPS,
      TAG_SLUGS.NON_COMEDOGENE,
    ],
    avoid: [],
  },

  [INGREDIENT_SLUGS.HUILE_DE_PEPINS_DE_FIGUE_DE_BARBARIE]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.ANTI_OXYDANT],
    secondary: [TAG_SLUGS.ECLAT, TAG_SLUGS.ZONE_VISAGE, TAG_SLUGS.REPARATEUR],
    avoid: [],
  },

  [INGREDIENT_SLUGS.HUILE_DE_PEPINS_DE_RAISIN]: {
    primary: [TAG_SLUGS.ANTI_OXYDANT, TAG_SLUGS.PEAU_MIXTE],
    secondary: [
      TAG_SLUGS.PORES_DILATES,
      TAG_SLUGS.EMOLLIENT,
      TAG_SLUGS.ZONE_VISAGE,
      TAG_SLUGS.SEBO_REGULATEUR,
    ],
    avoid: [],
  },

  [INGREDIENT_SLUGS.MENTHE_POIVREE]: {
    primary: [TAG_SLUGS.BRILLANCE, TAG_SLUGS.ANTI_ACNE, TAG_SLUGS.PEAU_GRASSE],
    secondary: [
      TAG_SLUGS.ECLAT,
      TAG_SLUGS.ANTISEPTIQUE,
      TAG_SLUGS.SEBO_REGULATEUR,
      TAG_SLUGS.BIO_NATUREL,
    ],
    avoid: [
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.PEAU_REACTIVE,
      TAG_SLUGS.ZONE_YEUX,
      TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE,
    ],
  },

  [INGREDIENT_SLUGS.ROMARIN]: {
    primary: [TAG_SLUGS.ANTI_ACNE, TAG_SLUGS.ANTI_OXYDANT, TAG_SLUGS.ANTISEPTIQUE],
    secondary: [
      TAG_SLUGS.PEAU_GRASSE,
      TAG_SLUGS.PEAU_MIXTE,
      TAG_SLUGS.SEBO_REGULATEUR,
      TAG_SLUGS.PORES_DILATES,
      TAG_SLUGS.BIO_NATUREL,
    ],
    avoid: [TAG_SLUGS.PEAU_SENSIBLE, TAG_SLUGS.PEAU_REACTIVE],
  },

  [INGREDIENT_SLUGS.VERVEINE]: {
    primary: [TAG_SLUGS.ECLAT, TAG_SLUGS.PEAU_REACTIVE, TAG_SLUGS.APAISANT],
    secondary: [TAG_SLUGS.TEINT_TERNE, TAG_SLUGS.ANTI_OXYDANT, TAG_SLUGS.BIO_NATUREL],
    avoid: [],
  },

  [INGREDIENT_SLUGS.BOURRACHE]: {
    primary: [TAG_SLUGS.PEAU_ATOPIQUE, TAG_SLUGS.REPARATEUR, TAG_SLUGS.EMOLLIENT],
    secondary: [
      TAG_SLUGS.BARRIERE_CUTANEE,
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.ANTI_AGE,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.BIO_NATUREL,
    ],
    avoid: [],
  },

  [INGREDIENT_SLUGS.PAQUERETTE]: {
    primary: [TAG_SLUGS.ECLAT, TAG_SLUGS.ANTI_AGE],
    secondary: [TAG_SLUGS.TEINT_TERNE, TAG_SLUGS.BIO_NATUREL, TAG_SLUGS.REPULPANT],
    avoid: [],
  },

  [INGREDIENT_SLUGS.MAUVE]: {
    primary: [TAG_SLUGS.PEAU_SENSIBLE, TAG_SLUGS.APAISANT, TAG_SLUGS.HUMECTANT],
    secondary: [
      TAG_SLUGS.ANTI_ROUGEURS,
      TAG_SLUGS.DESHYDRATATION,
      TAG_SLUGS.PEAU_REACTIVE,
      TAG_SLUGS.BARRIERE_CUTANEE,
      TAG_SLUGS.BIO_NATUREL,
    ],
    avoid: [],
  },

  [INGREDIENT_SLUGS.MANGANESE_GLUCONATE]: {
    primary: [TAG_SLUGS.ECLAT, TAG_SLUGS.ANTI_OXYDANT],
    secondary: [],
    avoid: [],
  },

  [INGREDIENT_SLUGS.PALMITOYL_TETRAPEPTIDE_10]: {
    primary: [TAG_SLUGS.ECLAT, TAG_SLUGS.ANTI_AGE],
    secondary: [TAG_SLUGS.TEINT_TERNE],
    avoid: [],
  },

  [INGREDIENT_SLUGS.PHENYLALANINE]: {
    primary: [TAG_SLUGS.HYPERPIGMENTATION, TAG_SLUGS.HUMECTANT],
    secondary: [TAG_SLUGS.ECLAT],
    avoid: [],
  },

  [INGREDIENT_SLUGS.PROPYLENE_GLYCOL]: {
    primary: [TAG_SLUGS.HUMECTANT, TAG_SLUGS.DESHYDRATATION],
    secondary: [],
    avoid: [TAG_SLUGS.PEAU_REACTIVE],
  },

  [INGREDIENT_SLUGS.SALVIA_MILTIORRHIZA]: {
    primary: [TAG_SLUGS.PEAU_SENSIBLE, TAG_SLUGS.ANTI_ROUGEURS],
    secondary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.APAISANT],
    avoid: [],
  },

  [INGREDIENT_SLUGS.SERINE]: {
    primary: [TAG_SLUGS.HUMECTANT, TAG_SLUGS.BARRIERE_CUTANEE],
    secondary: [TAG_SLUGS.BIOMIMETIQUE],
    avoid: [],
  },

  [INGREDIENT_SLUGS.TRETINOINE]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.ANTI_ACNE],
    secondary: [
      TAG_SLUGS.KERATOLYTIQUE,
      TAG_SLUGS.HYPERPIGMENTATION,
      TAG_SLUGS.ANTI_TACHES,
      TAG_SLUGS.ECLAT,
    ],
    avoid: [
      TAG_SLUGS.PEAU_REACTIVE,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.ROSACEE,
      TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE,
    ],
  },

  [INGREDIENT_SLUGS.TRIBEHENIN]: {
    primary: [TAG_SLUGS.EMOLLIENT, TAG_SLUGS.PEAU_SECHE],
    secondary: [TAG_SLUGS.BARRIERE_CUTANEE],
    avoid: [],
  },

  [INGREDIENT_SLUGS.TYROSINE]: {
    primary: [TAG_SLUGS.HUMECTANT],
    secondary: [],
    avoid: [],
  },

  [INGREDIENT_SLUGS.ZEA_MAYS_STARCH]: {
    primary: [TAG_SLUGS.BRILLANCE, TAG_SLUGS.PEAU_GRASSE],
    secondary: [TAG_SLUGS.MATIFIANT],
    avoid: [TAG_SLUGS.PEAU_SECHE],
  },

  [INGREDIENT_SLUGS.ZINC_GLUCONATE]: {
    primary: [TAG_SLUGS.SEBO_REGULATEUR, TAG_SLUGS.ANTI_ACNE],
    secondary: [
      TAG_SLUGS.PEAU_GRASSE,
      TAG_SLUGS.BRILLANCE,
      TAG_SLUGS.ANTI_ROUGEURS,
      TAG_SLUGS.APAISANT,
      TAG_SLUGS.PEAU_MIXTE,
    ],
    avoid: [TAG_SLUGS.PEAU_SECHE],
  },

  [INGREDIENT_SLUGS.DIMETHICONE]: {
    primary: [TAG_SLUGS.OCCLUSIF, TAG_SLUGS.BARRIERE_CUTANEE],
    secondary: [TAG_SLUGS.EMOLLIENT, TAG_SLUGS.PROTECTION_CUTANEE, TAG_SLUGS.TEXTURE_LEGERE],
    avoid: [],
  },

  [INGREDIENT_SLUGS.EAU_DE_ROSE]: {
    primary: [TAG_SLUGS.ECLAT, TAG_SLUGS.APAISANT],
    secondary: [TAG_SLUGS.PEAU_SENSIBLE, TAG_SLUGS.TEINT_TERNE],
    avoid: [],
  },

  [INGREDIENT_SLUGS.GLUTAMINE]: {
    primary: [TAG_SLUGS.REPARATEUR, TAG_SLUGS.BARRIERE_CUTANEE],
    secondary: [TAG_SLUGS.ANTI_AGE],
    avoid: [],
  },

  [INGREDIENT_SLUGS.GLYCERYL_DIBEHENATE]: {
    primary: [TAG_SLUGS.EMOLLIENT, TAG_SLUGS.PEAU_SECHE],
    secondary: [TAG_SLUGS.BARRIERE_CUTANEE],
    avoid: [],
  },

  [INGREDIENT_SLUGS.HAMAMELIS]: {
    primary: [TAG_SLUGS.PORES_DILATES, TAG_SLUGS.ANTI_ROUGEURS, TAG_SLUGS.ASTRINGENT],
    secondary: [
      TAG_SLUGS.PEAU_MIXTE,
      TAG_SLUGS.PEAU_GRASSE,
      TAG_SLUGS.SEBO_REGULATEUR,
      TAG_SLUGS.ECLAT,
      TAG_SLUGS.BIO_NATUREL,
    ],
    avoid: [TAG_SLUGS.PEAU_SECHE, TAG_SLUGS.PEAU_REACTIVE, TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE],
  },

  [INGREDIENT_SLUGS.HUILE_GRAINES_TOURNESOL]: {
    primary: [TAG_SLUGS.EMOLLIENT, TAG_SLUGS.BARRIERE_CUTANEE, TAG_SLUGS.BIO_NATUREL],
    secondary: [
      TAG_SLUGS.ZONE_VISAGE,
      TAG_SLUGS.ZONE_CORPS,
      TAG_SLUGS.ANTI_OXYDANT,
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.PEAU_SENSIBLE,
    ],
    avoid: [],
  },

  [INGREDIENT_SLUGS.HELICHRYSE_IMMORTELLE]: {
    primary: [
      TAG_SLUGS.ANTI_ROUGEURS,
      TAG_SLUGS.COUPEROSE,
      TAG_SLUGS.ROSACEE,
      TAG_SLUGS.REPARATEUR,
      TAG_SLUGS.BARRIERE_CUTANEE,
      TAG_SLUGS.CICATRISATION,
      TAG_SLUGS.APAISANT,
    ],
    secondary: [
      TAG_SLUGS.ANTI_AGE,
      TAG_SLUGS.FLUSHS,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.HYPERPIGMENTATION, // Via l'activité anti-tyrosinase mentionnée
      TAG_SLUGS.REPULPANT, // Via la stimulation de HAS-2 (Acide Hyaluronique)
      TAG_SLUGS.ANTI_OXYDANT,
      TAG_SLUGS.PHOTO_VIEILLISSEMENT,
    ],
    avoid: [],
  },

  [INGREDIENT_SLUGS.HISTIDINE]: {
    primary: [TAG_SLUGS.HUMECTANT, TAG_SLUGS.ANTI_OXYDANT],
    secondary: [TAG_SLUGS.APAISANT],
    avoid: [],
  },

  [INGREDIENT_SLUGS.HYDROGENATED_POLYISOBUTENE]: {
    primary: [TAG_SLUGS.EMOLLIENT, TAG_SLUGS.PEAU_SECHE],
    secondary: [TAG_SLUGS.TEXTURE_RICHE],
    avoid: [],
  },

  [INGREDIENT_SLUGS.LEUCINE]: {
    primary: [TAG_SLUGS.REPARATEUR, TAG_SLUGS.ANTI_AGE],
    secondary: [TAG_SLUGS.CICATRISATION],
    avoid: [],
  },

  [INGREDIENT_SLUGS.LYSINE_HCL]: {
    primary: [TAG_SLUGS.HUMECTANT, TAG_SLUGS.REPARATEUR],
    secondary: [],
    avoid: [],
  },

  [INGREDIENT_SLUGS.ACETYL_GLUCOSAMINE]: {
    primary: [TAG_SLUGS.ANTI_TACHES, TAG_SLUGS.HYPERPIGMENTATION],
    secondary: [TAG_SLUGS.ECLAT, TAG_SLUGS.ANTI_AGE, TAG_SLUGS.HUMECTANT],
    avoid: [],
  },

  [INGREDIENT_SLUGS.ADAPALENE]: {
    primary: [TAG_SLUGS.ANTI_ACNE, TAG_SLUGS.POST_ACNE],
    secondary: [TAG_SLUGS.KERATOLYTIQUE, TAG_SLUGS.ANTI_AGE],
    avoid: [TAG_SLUGS.PEAU_REACTIVE, TAG_SLUGS.PEAU_SECHE],
  },

  [INGREDIENT_SLUGS.ARGININE]: {
    primary: [TAG_SLUGS.REPARATEUR, TAG_SLUGS.HUMECTANT],
    secondary: [TAG_SLUGS.BARRIERE_CUTANEE, TAG_SLUGS.BIOMIMETIQUE],
    avoid: [],
  },

  [INGREDIENT_SLUGS.ARNICA]: {
    primary: [TAG_SLUGS.APAISANT, TAG_SLUGS.REPARATEUR, TAG_SLUGS.CERNES_POCHES],
    secondary: [
      TAG_SLUGS.ANTI_ROUGEURS,
      TAG_SLUGS.CICATRISATION,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.POST_ACNE,
      TAG_SLUGS.ANTISEPTIQUE,
      TAG_SLUGS.ANTI_OXYDANT,
    ],
    avoid: [],
  },

  [INGREDIENT_SLUGS.BIXA_ORELLANA]: {
    primary: [TAG_SLUGS.SEBO_REGULATEUR, TAG_SLUGS.ANTI_OXYDANT],
    secondary: [TAG_SLUGS.PEAU_GRASSE, TAG_SLUGS.MATIFIANT],
    avoid: [],
  },

  [INGREDIENT_SLUGS.BLEUET]: {
    primary: [TAG_SLUGS.CERNES_POCHES, TAG_SLUGS.ZONE_YEUX, TAG_SLUGS.APAISANT],
    secondary: [
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.PEAU_REACTIVE,
      TAG_SLUGS.ANTI_OXYDANT,
      TAG_SLUGS.HUMECTANT,
    ],
    avoid: [],
  },

  [INGREDIENT_SLUGS.CARNOSINE]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.ANTI_OXYDANT],
    secondary: [TAG_SLUGS.LUMIERE_BLEUE, TAG_SLUGS.POLLUTION],
    avoid: [],
  },

  [INGREDIENT_SLUGS.DICAPRYLYL_ETHER]: {
    primary: [TAG_SLUGS.EMOLLIENT, TAG_SLUGS.NON_COMEDOGENE],
    secondary: [TAG_SLUGS.TEXTURE_LEGERE],
    avoid: [],
  },

  [INGREDIENT_SLUGS.ASCOPHYLLUM_NODOSUM_EXTRACT]: {
    primary: [TAG_SLUGS.ANTI_ROUGEURS, TAG_SLUGS.ROSACEE],
    secondary: [TAG_SLUGS.PEAU_SENSIBLE, TAG_SLUGS.ANTI_OXYDANT],
    avoid: [],
  },

  [INGREDIENT_SLUGS.BIS_ETHYLHEXYLOXYPHENOL_METHOXYPHENYL_TRIAZINE]: {
    primary: [TAG_SLUGS.PROTECTION_SOLAIRE],
    secondary: [TAG_SLUGS.FILTRES_CHIMIQUES],
    avoid: [],
  },

  [INGREDIENT_SLUGS.DIACETYL_BOLDINE]: {
    primary: [TAG_SLUGS.ANTI_TACHES, TAG_SLUGS.HYPERPIGMENTATION],
    secondary: [TAG_SLUGS.ECLAT, TAG_SLUGS.ANTI_ROUGEURS],
    avoid: [],
  },

  [INGREDIENT_SLUGS.HUILE_DE_COCO]: {
    primary: [TAG_SLUGS.EMOLLIENT, TAG_SLUGS.OCCLUSIF],
    secondary: [TAG_SLUGS.ZONE_CORPS],
    avoid: [
      TAG_SLUGS.PEAU_GRASSE,
      TAG_SLUGS.ANTI_ACNE,
      TAG_SLUGS.COMEDOGENE,
      TAG_SLUGS.PORES_DILATES,
    ],
  },
  // ── Cupressus Sempervirens (Cyprès - Tonique circulatoire) ──
  [INGREDIENT_SLUGS.CYPRES]: {
    primary: [TAG_SLUGS.ANTI_ROUGEURS, TAG_SLUGS.ASTRINGENT],
    secondary: [TAG_SLUGS.COUPEROSE, TAG_SLUGS.TONIQUE],
    avoid: [],
  },

  // ── Hexylresorcinol (Éclaircissant puissant) ──
  [INGREDIENT_SLUGS.HEXYLRESORCINOL]: {
    primary: [TAG_SLUGS.ANTI_TACHES, TAG_SLUGS.HYPERPIGMENTATION],
    secondary: [TAG_SLUGS.ECLAT, TAG_SLUGS.ANTI_AGE],
    avoid: [],
  },

  // ── Melasyl (Molécule brevetée anti-taches) ──
  [INGREDIENT_SLUGS.MELASYL]: {
    primary: [TAG_SLUGS.ANTI_TACHES, TAG_SLUGS.HYPERPIGMENTATION],
    secondary: [TAG_SLUGS.POST_ACNE, TAG_SLUGS.TEINT_TERNE],
    avoid: [],
  },

  // ── Gallyl Glucoside (Apaisant / Anti-rougeurs) ──
  [INGREDIENT_SLUGS.GALLYL_GLUCOSIDE]: {
    primary: [TAG_SLUGS.ANTI_ROUGEURS, TAG_SLUGS.APAISANT],
    secondary: [TAG_SLUGS.ROSACEE, TAG_SLUGS.ANTI_OXYDANT],
    avoid: [],
  },

  // ── Copper Gluconate (Gluconate de Cuivre - Réparateur) ──
  [INGREDIENT_SLUGS.COPPER_GLUCONATE]: {
    primary: [TAG_SLUGS.REPARATEUR, TAG_SLUGS.CICATRISATION],
    secondary: [TAG_SLUGS.BARRIERE_CUTANEE, TAG_SLUGS.ANTI_BACTERIEN],
    avoid: [],
  },

  // ── Tea Tree (Arbre à thé - Purifiant) ──
  [INGREDIENT_SLUGS.TEA_TREE]: {
    primary: [TAG_SLUGS.ANTI_ACNE, TAG_SLUGS.ANTI_BACTERIEN],
    secondary: [TAG_SLUGS.SEBO_REGULATEUR, TAG_SLUGS.ANTISEPTIQUE],
    avoid: [TAG_SLUGS.PEAU_REACTIVE, TAG_SLUGS.PEAU_ATOPIQUE],
  },

  // ── Drometrizole Trisiloxane (Mexoryl XL - Filtre UV) ──
  [INGREDIENT_SLUGS.DROMETRIZOLE_TRISILOXANE]: {
    primary: [TAG_SLUGS.PROTECTION_SOLAIRE, TAG_SLUGS.FILTRES_CHIMIQUES],
    secondary: [TAG_SLUGS.PHOTO_VIEILLISSEMENT],
    avoid: [],
  },

  // ── Butyl Methoxydibenzoylmethane (Avobenzone - Filtre UVA) ──
  [INGREDIENT_SLUGS.BUTYL_METHOXYDIBENZOYLMETHANE]: {
    primary: [TAG_SLUGS.PROTECTION_SOLAIRE, TAG_SLUGS.FILTRES_CHIMIQUES],
    secondary: [TAG_SLUGS.PHOTO_VIEILLISSEMENT],
    avoid: [],
  },

  // ── Octocrylene (Filtre UV stabilisateur) ──
  [INGREDIENT_SLUGS.OCTOCRYLENE]: {
    primary: [TAG_SLUGS.PROTECTION_SOLAIRE, TAG_SLUGS.FILTRES_CHIMIQUES],
    secondary: [],
    avoid: [TAG_SLUGS.PEAU_REACTIVE],
  },

  // ── Homosalate (Filtre UVB) ──
  [INGREDIENT_SLUGS.HOMOSALATE]: {
    primary: [TAG_SLUGS.PROTECTION_SOLAIRE, TAG_SLUGS.FILTRES_CHIMIQUES],
    secondary: [],
    avoid: [],
  },

  // ── Ethylhexyl Salicylate (Octisalate - Filtre UVB) ──
  [INGREDIENT_SLUGS.ETHYLHEXYL_SALICYLATE]: {
    primary: [TAG_SLUGS.PROTECTION_SOLAIRE, TAG_SLUGS.FILTRES_CHIMIQUES],
    secondary: [],
    avoid: [],
  },
  [INGREDIENT_SLUGS.SNAIL_MUCIN]: {
    primary: [TAG_SLUGS.REPARATEUR, TAG_SLUGS.HUMECTANT, TAG_SLUGS.CICATRISATION],
    secondary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.REPULPANT, TAG_SLUGS.POST_ACNE],
    avoid: [],
  },

  // ── Vitreoscilla Ferment (Fraction de probiotique - Microbiome) ──
  [INGREDIENT_SLUGS.VITREOSCILLA_FERMENT]: {
    primary: [TAG_SLUGS.MICROBIOME, TAG_SLUGS.APAISANT, TAG_SLUGS.BARRIERE_CUTANEE],
    secondary: [TAG_SLUGS.PEAU_REACTIVE, TAG_SLUGS.PEAU_ATOPIQUE, TAG_SLUGS.PREBIOTIQUE],
    avoid: [],
  },

  // ── Fructooligosaccharides (Prébiotiques - Sucres) ──
  [INGREDIENT_SLUGS.FRUCTOOLIGOSACCHARIDES]: {
    primary: [TAG_SLUGS.PREBIOTIQUE, TAG_SLUGS.MICROBIOME, TAG_SLUGS.HUMECTANT],
    secondary: [TAG_SLUGS.BARRIERE_CUTANEE, TAG_SLUGS.PEAU_SENSIBLE],
    avoid: [],
  },

  // ── Asiatic Acid (Composant de la Centella Asiatica) ──
  [INGREDIENT_SLUGS.ASIATIC_ACID]: {
    primary: [TAG_SLUGS.REPARATEUR, TAG_SLUGS.ANTI_AGE],
    secondary: [TAG_SLUGS.CICATRISATION, TAG_SLUGS.ANTI_OXYDANT],
    avoid: [],
  },

  // ── Madecassic Acid (Composant de la Centella Asiatica - Apaisant) ──
  [INGREDIENT_SLUGS.MADECASSIC_ACID]: {
    primary: [TAG_SLUGS.APAISANT, TAG_SLUGS.REPARATEUR],
    secondary: [TAG_SLUGS.ANTI_ROUGEURS, TAG_SLUGS.CICATRISATION],
    avoid: [],
  },

  // ── Hydroxypalmitoyl Sphinganine (Précurseur de Céramide) ──
  [INGREDIENT_SLUGS.HYDROXYPALMITOYL_SPHINGANINE]: {
    primary: [TAG_SLUGS.BARRIERE_CUTANEE, TAG_SLUGS.REPARATEUR],
    secondary: [TAG_SLUGS.PEAU_SECHE, TAG_SLUGS.BIOMIMETIQUE],
    avoid: [],
  },

  // ── 2-Oleamido-1-3-Octadecanediol (Céramide synthétique - Ceramide 5) ──
  [INGREDIENT_SLUGS.TWO_OLEAMIDO_1_3_OCTADECANEDIOL]: {
    primary: [TAG_SLUGS.BARRIERE_CUTANEE, TAG_SLUGS.EMOLLIENT],
    secondary: [TAG_SLUGS.PROTECTION_CUTANEE, TAG_SLUGS.PEAU_SENSIBLE],
    avoid: [],
  },

  // ── Caffeine (Drainant / Éclat) ──
  [INGREDIENT_SLUGS.CAFFEINE]: {
    primary: [TAG_SLUGS.CERNES_POCHES, TAG_SLUGS.ECLAT],
    secondary: [TAG_SLUGS.ANTI_OXYDANT, TAG_SLUGS.CONTOUR_YEUX],
    avoid: [],
  },

  // ── Coco Glucoside (Tensioactif doux dérivé de la coco) ──
  [INGREDIENT_SLUGS.COCO_GLUCOSIDE]: {
    primary: [TAG_SLUGS.NETTOYANT, TAG_SLUGS.SANS_SAVON],
    secondary: [TAG_SLUGS.PEAU_SENSIBLE, TAG_SLUGS.NON_COMEDOGENE],
    avoid: [],
  },

  // ── Decyl Glucoside (Tensioactif très doux) ──
  [INGREDIENT_SLUGS.DECYL_GLUCOSIDE]: {
    primary: [TAG_SLUGS.NETTOYANT, TAG_SLUGS.HYPOALLERGENIQUE],
    secondary: [TAG_SLUGS.PEAU_ATOPIQUE, TAG_SLUGS.SANS_SAVON],
    avoid: [],
  },

  // ── Sodium Lauroyl Methyl Isethionate (Nettoyant doux / "Sulfate-free") ──
  [INGREDIENT_SLUGS.SODIUM_LAUROYL_METHYL_ISETHIONATE]: {
    primary: [TAG_SLUGS.NETTOYANT, TAG_SLUGS.TEXTURE_LEGERE],
    secondary: [TAG_SLUGS.PEAU_MIXTE, TAG_SLUGS.PEAU_GRASSE],
    avoid: [],
  },

  // ── Sodium Cocoyl Isethionate (Nettoyant crémeux doux) ──
  [INGREDIENT_SLUGS.SODIUM_COCOYL_ISETHIONATE]: {
    primary: [TAG_SLUGS.NETTOYANT, TAG_SLUGS.SANS_SAVON],
    secondary: [TAG_SLUGS.PEAU_SECHE, TAG_SLUGS.PEAU_NORMALE],
    avoid: [],
  },

  // ── Silica (Silice - Matifiant / Texturisant) ──
  [INGREDIENT_SLUGS.SILICA]: {
    primary: [TAG_SLUGS.MATIFIANT, TAG_SLUGS.BRILLANCE],
    secondary: [TAG_SLUGS.PEAU_GRASSE, TAG_SLUGS.TEXTURE_LEGERE],
    avoid: [],
  },

  // ── Hydrocolloid (Pansement actif) ──
  [INGREDIENT_SLUGS.HYDROCOLLOID]: {
    primary: [TAG_SLUGS.ANTI_ACNE, TAG_SLUGS.CICATRISATION],
    secondary: [TAG_SLUGS.PROTECTION_CUTANEE, TAG_SLUGS.POST_ACNE],
    avoid: [],
  },
  [INGREDIENT_SLUGS.ORYZA_SATIVA]: {
    primary: [TAG_SLUGS.APAISANT, TAG_SLUGS.BIO_NATUREL],
    secondary: [TAG_SLUGS.MATIFIANT, TAG_SLUGS.PEAU_SENSIBLE],
    avoid: [],
  },

  // ── Salix Nigra (Saule Noir - Acide salicylique naturel) ──
  [INGREDIENT_SLUGS.SALIX_NIGRA]: {
    primary: [TAG_SLUGS.ANTI_ACNE, TAG_SLUGS.KERATOLYTIQUE],
    secondary: [TAG_SLUGS.PORES_DILATES, TAG_SLUGS.BIO_NATUREL],
    avoid: [TAG_SLUGS.PEAU_REACTIVE],
  },

  // ── Citrus Aurantium Dulcis (Orange Douce - Éclat / Tonifiant) ──
  [INGREDIENT_SLUGS.CITRUS_AURANTIUM_DULCIS]: {
    primary: [TAG_SLUGS.ECLAT, TAG_SLUGS.TEINT_TERNE],
    secondary: [TAG_SLUGS.ANTI_OXYDANT, TAG_SLUGS.ASTRINGENT],
    avoid: [TAG_SLUGS.PEAU_REACTIVE, TAG_SLUGS.PEAU_ATOPIQUE],
  },

  // ── Biosaccharide Gum-1 (Fucocert - Apaisant sensoriel) ──
  [INGREDIENT_SLUGS.BIOSACCHARIDE_GUM_1]: {
    primary: [TAG_SLUGS.APAISANT, TAG_SLUGS.HUMECTANT],
    secondary: [TAG_SLUGS.PEAU_SENSIBLE, TAG_SLUGS.DESHYDRATATION],
    avoid: [],
  },

  // ── Ahnfeltia Concinna (Algue Rouge - HU profonde) ──
  [INGREDIENT_SLUGS.AHNFELTIA_CONCINNA]: {
    primary: [TAG_SLUGS.REPARATEUR, TAG_SLUGS.HUMECTANT],
    secondary: [TAG_SLUGS.BARRIERE_CUTANEE, TAG_SLUGS.PROTECTION_CUTANEE],
    avoid: [],
  },

  // ── Amaranthus (Amarante - Nourrissant) ──
  [INGREDIENT_SLUGS.AMARANTHUS_CAUDATUS]: {
    primary: [TAG_SLUGS.EMOLLIENT, TAG_SLUGS.TEXTURE_RICHE],
    secondary: [TAG_SLUGS.PEAU_SECHE, TAG_SLUGS.BARRIERE_CUTANEE],
    avoid: [],
  },

  // ── Isosorbide Dicaprylate (Booster d'HU) ──
  [INGREDIENT_SLUGS.ISOSORBIDE_DICAPRYLATE]: {
    primary: [TAG_SLUGS.HUMECTANT, TAG_SLUGS.BARRIERE_CUTANEE],
    secondary: [TAG_SLUGS.DESHYDRATATION, TAG_SLUGS.REPULPANT],
    avoid: [],
  },

  // ── Rice Amino Acids (Acides Aminés de Riz) ──
  [INGREDIENT_SLUGS.RICE_AMINO_ACIDS]: {
    primary: [TAG_SLUGS.REPARATEUR, TAG_SLUGS.HUMECTANT],
    secondary: [TAG_SLUGS.BIOMIMETIQUE, TAG_SLUGS.PEAU_SENSIBLE],
    avoid: [],
  },

  // ── Orbignya Oleifera (Huile de Babassu) ──
  [INGREDIENT_SLUGS.HUILE_BABASSU]: {
    primary: [TAG_SLUGS.EMOLLIENT, TAG_SLUGS.HUILE_VISAGE],
    secondary: [TAG_SLUGS.PEAU_MIXTE],
    avoid: [],
  },

  // ── Pinus Palustris (Pin des Marais - Purifiant / Résine) ──
  [INGREDIENT_SLUGS.PINUS_PALUSTRIS]: {
    primary: [TAG_SLUGS.ANTISEPTIQUE, TAG_SLUGS.ASTRINGENT],
    secondary: [TAG_SLUGS.PEAU_GRASSE, TAG_SLUGS.ANTI_BACTERIEN],
    avoid: [],
  },

  // ── Vetiveria Zizanoides (Vétiver - Régénérant) ──
  [INGREDIENT_SLUGS.VETIVERIA_ZIZANOIDES]: {
    primary: [TAG_SLUGS.APAISANT, TAG_SLUGS.CICATRISATION],
    secondary: [TAG_SLUGS.ANTI_OXYDANT, TAG_SLUGS.PEAU_REACTIVE],
    avoid: [],
  },

  // ── Aphanizomenon Flos-Aquae (Algue Bleue - "Rétinol-like" naturel) ──
  [INGREDIENT_SLUGS.APHANIZOMENON_FLOS_AQUAE]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.REPULPANT],
    secondary: [TAG_SLUGS.ECLAT, TAG_SLUGS.BIO_NATUREL],
    avoid: [],
  },

  // ── Betaine (Dérivé de betterave - Osmoprotecteur) ──
  [INGREDIENT_SLUGS.BETAINE]: {
    primary: [TAG_SLUGS.HUMECTANT, TAG_SLUGS.APAISANT],
    secondary: [TAG_SLUGS.DESHYDRATATION, TAG_SLUGS.PEAU_SENSIBLE],
    avoid: [],
  },

  // ── Xylitylglucoside (Partie de l'Aquaxyl - Circulation de l'eau) ──
  [INGREDIENT_SLUGS.XYLITYLGLUCOSIDE]: {
    primary: [TAG_SLUGS.HUMECTANT, TAG_SLUGS.DESHYDRATATION],
    secondary: [TAG_SLUGS.BARRIERE_CUTANEE, TAG_SLUGS.REPULPANT],
    avoid: [],
  },
  [INGREDIENT_SLUGS.XYLITOL]: {
    primary: [TAG_SLUGS.HUMECTANT, TAG_SLUGS.DESHYDRATATION],
    secondary: [TAG_SLUGS.BARRIERE_CUTANEE, TAG_SLUGS.MICROBIOME],
    avoid: [],
  },
  [INGREDIENT_SLUGS.ANHYDROXYLITOL]: {
    primary: [TAG_SLUGS.HUMECTANT, TAG_SLUGS.DESHYDRATATION],
    secondary: [TAG_SLUGS.BARRIERE_CUTANEE],
    avoid: [],
  },

  // ── PCA (Pyrrolidone Carboxylic Acid - NMF Naturel) ──
  [INGREDIENT_SLUGS.PCA]: {
    primary: [TAG_SLUGS.HUMECTANT, TAG_SLUGS.BIOMIMETIQUE],
    secondary: [TAG_SLUGS.DESHYDRATATION, TAG_SLUGS.PEAU_SENSIBLE],
    avoid: [],
  },

  // ── Trehalose (Sucre de résurrection) ──
  [INGREDIENT_SLUGS.TREHALOSE]: {
    primary: [TAG_SLUGS.HUMECTANT, TAG_SLUGS.PROTECTION_CUTANEE],
    secondary: [TAG_SLUGS.DESHYDRATATION, TAG_SLUGS.ANTI_OXYDANT],
    avoid: [],
  },

  // ── Glycine (Acide aminé collagène) ──
  [INGREDIENT_SLUGS.GLYCINE]: {
    primary: [TAG_SLUGS.REPARATEUR, TAG_SLUGS.ANTI_AGE],
    secondary: [TAG_SLUGS.BIOMIMETIQUE, TAG_SLUGS.HUMECTANT],
    avoid: [],
  },

  // ── Cera Alba (Cire d'abeille) ──
  [INGREDIENT_SLUGS.CIRE_ABEILLE]: {
    primary: [TAG_SLUGS.OCCLUSIF, TAG_SLUGS.PROTECTION_CUTANEE],
    secondary: [TAG_SLUGS.PEAU_SECHE, TAG_SLUGS.TEXTURE_RICHE],
    avoid: [TAG_SLUGS.PEAU_GRASSE, TAG_SLUGS.COMEDOGENE],
  },

  [INGREDIENT_SLUGS.CAMELLIA_JAPONICA_OIL]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.EMOLLIENT],
    secondary: [TAG_SLUGS.ANTI_OXYDANT, TAG_SLUGS.HUILE_VISAGE, TAG_SLUGS.HUILE_CORPS],
    avoid: [],
  },
  [INGREDIENT_SLUGS.APRICOT_KERNEL_OIL]: {
    primary: [TAG_SLUGS.ECLAT, TAG_SLUGS.EMOLLIENT],
    secondary: [TAG_SLUGS.TEINT_TERNE, TAG_SLUGS.PEAU_SECHE],
    avoid: [],
  },
  [INGREDIENT_SLUGS.HUILE_CARTHAME]: {
    primary: [TAG_SLUGS.ANTI_ROUGEURS, TAG_SLUGS.EMOLLIENT],
    secondary: [TAG_SLUGS.COUPEROSE, TAG_SLUGS.PEAU_MIXTE],
    avoid: [],
  },
  [INGREDIENT_SLUGS.HUILE_SOJA]: {
    primary: [TAG_SLUGS.EMOLLIENT, TAG_SLUGS.REPARATEUR],
    secondary: [TAG_SLUGS.ANTI_OXYDANT, TAG_SLUGS.PEAU_SECHE],
    avoid: [],
  },

  // ── Ceramide NG (Céramide 2 - Réparation barrière) ──
  [INGREDIENT_SLUGS.CERAMIDE_NG]: {
    primary: [TAG_SLUGS.BARRIERE_CUTANEE, TAG_SLUGS.REPARATEUR],
    secondary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.BIOMIMETIQUE],
    avoid: [],
  },

  // ── Acides Gras (Linoleic & Oleic) ──
  [INGREDIENT_SLUGS.LINOLEIC_ACID]: {
    primary: [TAG_SLUGS.BARRIERE_CUTANEE, TAG_SLUGS.ANTI_ACNE],
    secondary: [TAG_SLUGS.PEAU_MIXTE, TAG_SLUGS.REPARATEUR],
    avoid: [],
  },
  [INGREDIENT_SLUGS.OLEIC_ACID]: {
    primary: [TAG_SLUGS.EMOLLIENT, TAG_SLUGS.TEXTURE_RICHE],
    secondary: [TAG_SLUGS.PEAU_SECHE],
    avoid: [TAG_SLUGS.PEAU_GRASSE],
  },

  // ── Theobroma Cacao Butter (Beurre de cacao) ──
  [INGREDIENT_SLUGS.BEURRE_CACAO]: {
    primary: [TAG_SLUGS.EMOLLIENT, TAG_SLUGS.TEXTURE_RICHE],
    secondary: [TAG_SLUGS.PEAU_SECHE, TAG_SLUGS.OCCLUSIF],
    avoid: [TAG_SLUGS.NON_COMEDOGENE], // Car il est potentiellement comédogène
  },

  // ── Protease (Enzyme exfoliante) ──
  [INGREDIENT_SLUGS.PROTEASE]: {
    primary: [TAG_SLUGS.EXFOLIATION, TAG_SLUGS.KERATOLYTIQUE],
    secondary: [TAG_SLUGS.ECLAT, TAG_SLUGS.TEINT_TERNE],
    avoid: [TAG_SLUGS.PEAU_REACTIVE],
  },

  // ── Capryloyl Salicylic Acid (LHA - Exfoliation douce) ──
  [INGREDIENT_SLUGS.CAPRYLOYL_SALICYLIC_ACID]: {
    primary: [TAG_SLUGS.ANTI_ACNE, TAG_SLUGS.KERATOLYTIQUE],
    secondary: [TAG_SLUGS.PORES_DILATES, TAG_SLUGS.TEINT_TERNE],
    avoid: [],
  },

  // ── Palmitoyl Tripeptide-38 (Matrixyl Synthe'6) ──
  [INGREDIENT_SLUGS.PALMITOYL_TRIPEPTIDE_38]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.REPULPANT],
    secondary: [TAG_SLUGS.CICATRISATION, TAG_SLUGS.REPARATEUR],
    avoid: [],
  },
  [INGREDIENT_SLUGS.ACETYL_TETRAPEPTIDE_5]: {
    primary: [TAG_SLUGS.CERNES_POCHES, TAG_SLUGS.CONTOUR_YEUX],
    secondary: [TAG_SLUGS.HUMECTANT, TAG_SLUGS.DESHYDRATATION],
    avoid: [],
  },

  // ── Acetyl Tetrapeptide-2 (Uplevity - Fermeté) ──
  [INGREDIENT_SLUGS.ACETYL_TETRAPEPTIDE_2]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.REPULPANT],
    secondary: [TAG_SLUGS.REPARATEUR, TAG_SLUGS.BARRIERE_CUTANEE],
    avoid: [],
  },

  // ── Myristoyl Nonapeptide-3 (Retinoïde-like sans irritation) ──
  [INGREDIENT_SLUGS.MYRISTOYL_NONAPEPTIDE_3]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.PHOTO_VIEILLISSEMENT],
    secondary: [TAG_SLUGS.ECLAT, TAG_SLUGS.TEINT_TERNE],
    avoid: [],
  },

  // ── Peptide Complex (Mélange générique de peptides) ──
  [INGREDIENT_SLUGS.PEPTIDE_COMPLEX]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.REPULPANT],
    secondary: [TAG_SLUGS.REPARATEUR, TAG_SLUGS.BIOMIMETIQUE],
    avoid: [],
  },

  // ── Nicotiana Benthamiana (Facteurs de croissance biotechnologiques) ──
  // Note : Ces peptides "sh" imitent les facteurs de croissance humains (EGF, TGF-beta)
  [INGREDIENT_SLUGS.NICOTIANA_BENTHAMIANA_OCTAPEPTIDE_30_SH_OLIGOPEPTIDE_2]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.REPARATEUR],
    secondary: [TAG_SLUGS.REPULPANT, TAG_SLUGS.CICATRISATION],
    avoid: [],
  },
  [INGREDIENT_SLUGS.NICOTIANA_BENTHAMIANA_HEXAPEPTIDE_40_SH_POLYPEPTIDE_76]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.REPULPANT],
    secondary: [TAG_SLUGS.PHOTO_VIEILLISSEMENT, TAG_SLUGS.BIOMIMETIQUE],
    avoid: [],
  },
  [INGREDIENT_SLUGS.NICOTIANA_BENTHAMIANA_HEXAPEPTIDE_40_SH_OLIGOPEPTIDE_1]: {
    primary: [TAG_SLUGS.REPARATEUR, TAG_SLUGS.CICATRISATION],
    secondary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.BARRIERE_CUTANEE],
    avoid: [],
  },

  // ── Tetrapeptide-21 (Booster de collagène) ──
  [INGREDIENT_SLUGS.TETRAPEPTIDE_21]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.REPULPANT],
    secondary: [TAG_SLUGS.PHOTO_VIEILLISSEMENT, TAG_SLUGS.REPARATEUR],
    avoid: [],
  },

  // ── Copper Heptapeptide / Heptapeptide-15 (Drones cosmétiques) ──
  [INGREDIENT_SLUGS.COPPER_PALMITOYL_HEPTAPEPTIDE_14]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.REPULPANT],
    secondary: [TAG_SLUGS.REPARATEUR, TAG_SLUGS.BIOMIMETIQUE],
    avoid: [],
  },
  [INGREDIENT_SLUGS.HEPTAPEPTIDE_15_PALMITATE]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.REPULPANT],
    secondary: [TAG_SLUGS.ECLAT, TAG_SLUGS.HYPERPIGMENTATION],
    avoid: [],
  },

  // ── Copper Tripeptide-1 Palmitamide (Peptide de Cuivre stable) ──
  [INGREDIENT_SLUGS.COPPER_TRIPEPTIDE_1_PALMITAMIDE]: {
    primary: [TAG_SLUGS.REPARATEUR, TAG_SLUGS.CICATRISATION],
    secondary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.MICROBIOME],
    avoid: [],
  },

  // ── Trifluoroacetyl Tripeptide-2 (Progeline - Anti-relâchement) ──
  [INGREDIENT_SLUGS.TRIFLUOROACETYL_TRIPEPTIDE_2]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.REPULPANT],
    secondary: [TAG_SLUGS.PHOTO_VIEILLISSEMENT],
    avoid: [],
  },
  [INGREDIENT_SLUGS.TRIPEPTIDE_1]: {
    primary: [TAG_SLUGS.REPARATEUR, TAG_SLUGS.ANTI_AGE],
    secondary: [TAG_SLUGS.CICATRISATION, TAG_SLUGS.REPULPANT],
    avoid: [],
  },

  // ── Tocopheryl Acetate (Vitamine E - Stabilité) ──
  [INGREDIENT_SLUGS.TOCOPHERYL_ACETATE]: {
    primary: [TAG_SLUGS.ANTI_OXYDANT, TAG_SLUGS.PROTECTION_CUTANEE],
    secondary: [TAG_SLUGS.BARRIERE_CUTANEE, TAG_SLUGS.EMOLLIENT],
    avoid: [],
  },

  // ── Cyanocobalamin (Vitamine B12 - Rose naturel) ──
  [INGREDIENT_SLUGS.CYANOCOBALAMIN]: {
    primary: [TAG_SLUGS.APAISANT, TAG_SLUGS.REPARATEUR],
    secondary: [TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE, TAG_SLUGS.ECZEMA],
    avoid: [],
  },

  // ── NAD (Nicotinamide Adenine Dinucleotide - Énergie cellulaire) ──
  [INGREDIENT_SLUGS.NAD]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.PHOTO_VIEILLISSEMENT],
    secondary: [TAG_SLUGS.ECLAT, TAG_SLUGS.REPARATEUR],
    avoid: [],
  },

  // ── Ribose (Sucre énergétique) ──
  [INGREDIENT_SLUGS.RIBOSE]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.ECLAT],
    secondary: [TAG_SLUGS.REPULPANT, TAG_SLUGS.TEINT_TERNE],
    avoid: [],
  },

  // ── CoQ10 (Ubiquinone - Antioxydant puissant) ──
  [INGREDIENT_SLUGS.COQ10]: {
    primary: [TAG_SLUGS.ANTI_OXYDANT, TAG_SLUGS.ANTI_AGE],
    secondary: [TAG_SLUGS.PHOTO_VIEILLISSEMENT, TAG_SLUGS.REPARATEUR],
    avoid: [],
  },

  // ── Ergothioneine (Acide aminé antioxydant) ──
  [INGREDIENT_SLUGS.ERGOTHIONEINE]: {
    primary: [TAG_SLUGS.ANTI_OXYDANT, TAG_SLUGS.POLLUTION],
    secondary: [TAG_SLUGS.ECLAT, TAG_SLUGS.PHOTO_VIEILLISSEMENT],
    avoid: [],
  },

  // ── Panax Ginseng (Vitalisant) ──
  [INGREDIENT_SLUGS.PANAX_GINSENG]: {
    primary: [TAG_SLUGS.ECLAT, TAG_SLUGS.ANTI_AGE],
    secondary: [TAG_SLUGS.TEINT_TERNE, TAG_SLUGS.REPULPANT],
    avoid: [],
  },

  // ── Haematococcus Pluvialis (Source d'Astaxanthine) ──
  [INGREDIENT_SLUGS.HAEMATOCOCCUS_PLUVIALIS]: {
    primary: [TAG_SLUGS.ANTI_OXYDANT, TAG_SLUGS.PHOTO_VIEILLISSEMENT],
    secondary: [TAG_SLUGS.ECLAT, TAG_SLUGS.PROTECTION_CUTANEE],
    avoid: [],
  },

  // ── Punica Granatum (Grenade - Antioxydant) ──
  [INGREDIENT_SLUGS.PUNICA_GRANATUM]: {
    primary: [TAG_SLUGS.ANTI_OXYDANT, TAG_SLUGS.ASTRINGENT],
    secondary: [TAG_SLUGS.ECLAT, TAG_SLUGS.BIO_NATUREL],
    avoid: [],
  },

  // ── Centella Complex & Madecassoside (Cica-care) ──
  [INGREDIENT_SLUGS.CENTELLA_COMPLEX]: {
    primary: [TAG_SLUGS.APAISANT, TAG_SLUGS.REPARATEUR],
    secondary: [TAG_SLUGS.CICATRISATION, TAG_SLUGS.BARRIERE_CUTANEE],
    avoid: [],
  },
  [INGREDIENT_SLUGS.MADECASSOSIDE]: {
    primary: [TAG_SLUGS.APAISANT, TAG_SLUGS.CICATRISATION],
    secondary: [TAG_SLUGS.ANTI_ROUGEURS, TAG_SLUGS.PEAU_SENSIBLE],
    avoid: [],
  },

  // ── Beta-Glucan (HU apaisante) ──
  [INGREDIENT_SLUGS.BETA_GLUCAN]: {
    primary: [TAG_SLUGS.BARRIERE_CUTANEE, TAG_SLUGS.APAISANT],
    secondary: [TAG_SLUGS.HUMECTANT, TAG_SLUGS.REPULPANT],
    avoid: [],
  },

  // ── Bisabolol (Actif apaisant de la Camomille) ──
  [INGREDIENT_SLUGS.BISABOLOL]: {
    primary: [TAG_SLUGS.APAISANT, TAG_SLUGS.ANTI_ROUGEURS],
    secondary: [TAG_SLUGS.PEAU_SENSIBLE, TAG_SLUGS.HYPOALLERGENIQUE],
    avoid: [],
  },

  // ── Cucumis Sativus (Concombre - Fraîcheur) ──
  [INGREDIENT_SLUGS.CUCUMBER_EXTRACT]: {
    primary: [TAG_SLUGS.DESHYDRATATION, TAG_SLUGS.ECLAT],
    secondary: [TAG_SLUGS.APAISANT, TAG_SLUGS.CERNES_POCHES],
    avoid: [],
  },

  // ── Portulaca Oleracea (Pourpier - Anti-inflammatoire) ──
  [INGREDIENT_SLUGS.PORTULACA_OLERACEA]: {
    primary: [TAG_SLUGS.APAISANT, TAG_SLUGS.ANTI_OXYDANT],
    secondary: [TAG_SLUGS.PEAU_REACTIVE, TAG_SLUGS.REPARATEUR],
    avoid: [],
  },

  // ── Royal Jelly Extract (Gelée Royale) ──
  [INGREDIENT_SLUGS.ROYAL_JELLY_EXTRACT]: {
    primary: [TAG_SLUGS.REPARATEUR, TAG_SLUGS.ANTI_AGE],
    secondary: [TAG_SLUGS.EMOLLIENT, TAG_SLUGS.TEXTURE_RICHE],
    avoid: [],
  },

  // ── Zanthoxylum Bungeanum (Poivre du Sichuan - Effet tenseur/apaisant) ──
  [INGREDIENT_SLUGS.ZANTHOXYLUM_BUNGEANUM]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.APAISANT],
    secondary: [TAG_SLUGS.REPULPANT, TAG_SLUGS.PEAU_SENSIBLE],
    avoid: [],
  },

  [INGREDIENT_SLUGS.VITAMIN_K1]: {
    primary: [TAG_SLUGS.ANTI_ROUGEURS, TAG_SLUGS.CERNES_POCHES],
    secondary: [TAG_SLUGS.COUPEROSE, TAG_SLUGS.CICATRISATION, TAG_SLUGS.REPARATEUR],
    avoid: [],
  },
  [INGREDIENT_SLUGS.FERULIC_ACID]: {
    primary: [TAG_SLUGS.ANTI_OXYDANT, TAG_SLUGS.PHOTO_VIEILLISSEMENT],
    secondary: [TAG_SLUGS.ECLAT, TAG_SLUGS.ANTI_AGE, TAG_SLUGS.POLLUTION],
    avoid: [],
  },
  [INGREDIENT_SLUGS.RETINYL_RETINOATE]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.ANTI_TACHES, TAG_SLUGS.REPULPANT],
    secondary: [TAG_SLUGS.ANTI_ACNE, TAG_SLUGS.ECLAT, TAG_SLUGS.PEAU_SENSIBLE],
    avoid: [],
  },
  [INGREDIENT_SLUGS.SODIUM_RETINOYL_HYALURONATE]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.HYPERPIGMENTATION, TAG_SLUGS.DESHYDRATATION],
    secondary: [TAG_SLUGS.HUMECTANT, TAG_SLUGS.REPULPANT, TAG_SLUGS.POST_ACNE],
    avoid: [],
  },
  [INGREDIENT_SLUGS.GRANACTIVE_RETINOID]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.ANTI_ACNE, TAG_SLUGS.PORES_DILATES],
    secondary: [TAG_SLUGS.ANTI_TACHES, TAG_SLUGS.TEXTURE_LEGERE, TAG_SLUGS.ECLAT],
    avoid: [],
  },
  [INGREDIENT_SLUGS.COLLOIDAL_OATMEAL]: {
    primary: [TAG_SLUGS.APAISANT, TAG_SLUGS.BARRIERE_CUTANEE, TAG_SLUGS.PEAU_ATOPIQUE],
    secondary: [TAG_SLUGS.PEAU_SENSIBLE, TAG_SLUGS.ECZEMA, TAG_SLUGS.PROTECTION_CUTANEE],
    avoid: [],
  },
  [INGREDIENT_SLUGS.RETINYL_ACETATE]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.ECLAT, TAG_SLUGS.PEAU_SENSIBLE],
    secondary: [TAG_SLUGS.TEINT_TERNE, TAG_SLUGS.DESHYDRATATION, TAG_SLUGS.BARRIERE_CUTANEE],
    avoid: [],
  },
  [INGREDIENT_SLUGS.RETINYL_LINOLLEATE]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.PEAU_SENSIBLE, TAG_SLUGS.BARRIERE_CUTANEE],
    secondary: [TAG_SLUGS.ECLAT, TAG_SLUGS.DESHYDRATATION, TAG_SLUGS.REPARATEUR],
    avoid: [],
  },
  [INGREDIENT_SLUGS.ISOTRETINOIN]: {
    primary: [TAG_SLUGS.ANTI_ACNE, TAG_SLUGS.POST_ACNE, TAG_SLUGS.KERATOLYTIQUE],
    secondary: [TAG_SLUGS.PORES_DILATES, TAG_SLUGS.SEBO_REGULATEUR, TAG_SLUGS.CICATRISATION],
    avoid: [TAG_SLUGS.GROSSESSE_COMPATIBLE], // Tératogène majeur, même topique
  },
  [INGREDIENT_SLUGS.ALITRETINOIN]: {
    primary: [TAG_SLUGS.ECZEMA, TAG_SLUGS.PEAU_ATOPIQUE, TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE],
    secondary: [TAG_SLUGS.REPARATEUR, TAG_SLUGS.CICATRISATION, TAG_SLUGS.ANTI_ROUGEURS],
    avoid: [TAG_SLUGS.GROSSESSE_COMPATIBLE], // Tératogène, usage oral strict
  },
  [INGREDIENT_SLUGS.RETINYL_PALMITATE]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.ECLAT, TAG_SLUGS.PEAU_SENSIBLE],
    secondary: [TAG_SLUGS.TEINT_TERNE, TAG_SLUGS.DESHYDRATATION, TAG_SLUGS.BARRIERE_CUTANEE],
    avoid: [TAG_SLUGS.GROSSESSE_COMPATIBLE], // Rétinoïde ester → prudence maximale en grossesse (cat. C ou évitement recommandé, risque tératogène potentiel même topique faible)
  },

  [INGREDIENT_SLUGS.RETINYL_PROPIONATE]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.ECLAT, TAG_SLUGS.PEAU_SENSIBLE],
    secondary: [TAG_SLUGS.TEINT_TERNE, TAG_SLUGS.DESHYDRATATION, TAG_SLUGS.BARRIERE_CUTANEE],
    avoid: [TAG_SLUGS.GROSSESSE_COMPATIBLE], // Rétinoïde ester → prudence en grossesse (éviter par précaution, absorption systémique faible mais risque théorique)
  },

  [INGREDIENT_SLUGS.HYDROXYPINACOLONE_RETINOATE]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.REPULPANT, TAG_SLUGS.ANTI_TACHES],
    secondary: [
      TAG_SLUGS.ECLAT,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.ANTI_ACNE,
      TAG_SLUGS.PHOTO_VIEILLISSEMENT,
    ],
    avoid: [TAG_SLUGS.GROSSESSE_COMPATIBLE], // Rétinoïde direct (ester d'acide rétinoïque) → contre-indiqué grossesse/allaitement (risque tératogène potentiel, usage externe prudent)
  },

  [INGREDIENT_SLUGS.TAZAROTENE]: {
    primary: [TAG_SLUGS.ANTI_ACNE, TAG_SLUGS.ANTI_AGE, TAG_SLUGS.PHOTO_VIEILLISSEMENT],
    secondary: [TAG_SLUGS.POST_ACNE, TAG_SLUGS.PORES_DILATES, TAG_SLUGS.HYPERPIGMENTATION],
    avoid: [TAG_SLUGS.GROSSESSE_COMPATIBLE, TAG_SLUGS.PEAU_SENSIBLE], // Cat. X (tératogène fort) + irritation très élevée → éviter grossesse et peaux réactives
  },

  [INGREDIENT_SLUGS.TRIFAROTENE]: {
    primary: [TAG_SLUGS.ANTI_ACNE, TAG_SLUGS.POST_ACNE, TAG_SLUGS.CICATRISATION],
    secondary: [
      TAG_SLUGS.PORES_DILATES,
      TAG_SLUGS.HYPERPIGMENTATION,
      TAG_SLUGS.PHOTO_VIEILLISSEMENT,
    ],
    avoid: [TAG_SLUGS.GROSSESSE_COMPATIBLE, TAG_SLUGS.PEAU_SENSIBLE], // Contre-indiqué grossesse (tératogène potentiel) + irritation initiale possible → prudence peaux réactives
  },
}
