import { INGREDIENT_SLUGS } from '../ingredients/seed-ingredients'
import { TAG_SLUGS } from '../tags/seed-tags'

export const ingredientTagAssociations: { ingredientSlug: string; tagSlug: string }[] = [
  {
    ingredientSlug: INGREDIENT_SLUGS.ACETYL_DIPEPTIDE_1_CETYL_ESTER,
    tagSlug: TAG_SLUGS.PEAU_REACTIVE,
  },
  {
    ingredientSlug: INGREDIENT_SLUGS.ACETYL_DIPEPTIDE_1_CETYL_ESTER,
    tagSlug: TAG_SLUGS.PEAU_SENSIBLE,
  },
  { ingredientSlug: INGREDIENT_SLUGS.ACETYL_DIPEPTIDE_1_CETYL_ESTER, tagSlug: TAG_SLUGS.FLUSHS },

  // adenosine (Énergie cellulaire & Anti-inflammatoire)
  { ingredientSlug: INGREDIENT_SLUGS.ADENOSINE, tagSlug: TAG_SLUGS.ANTI_AGE },
  { ingredientSlug: INGREDIENT_SLUGS.ADENOSINE, tagSlug: TAG_SLUGS.REPARATEUR },
  { ingredientSlug: INGREDIENT_SLUGS.ADENOSINE, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },

  // alpha-glucan-oligosaccharide (Prébiotique protecteur)
  {
    ingredientSlug: INGREDIENT_SLUGS.ALPHA_GLUCAN_OLIGOSACCHARIDE,
    tagSlug: TAG_SLUGS.BARRIERE_CUTANEE,
  },
  {
    ingredientSlug: INGREDIENT_SLUGS.ALPHA_GLUCAN_OLIGOSACCHARIDE,
    tagSlug: TAG_SLUGS.PEAU_ATOPIQUE,
  },
  {
    ingredientSlug: INGREDIENT_SLUGS.ALPHA_GLUCAN_OLIGOSACCHARIDE,
    tagSlug: TAG_SLUGS.BIOMIMETIQUE,
  },

  // angiopausine (Spécifique microcirculation)
  { ingredientSlug: INGREDIENT_SLUGS.ANGIOPAUSINE, tagSlug: TAG_SLUGS.ANTI_ROUGEURS },
  { ingredientSlug: INGREDIENT_SLUGS.ANGIOPAUSINE, tagSlug: TAG_SLUGS.ROSACEE },
  { ingredientSlug: INGREDIENT_SLUGS.ANGIOPAUSINE, tagSlug: TAG_SLUGS.COUPEROSE },

  // aquaphilus-dolomiae-extract (I-modulia - Anti-inflammatoire puissant)
  {
    ingredientSlug: INGREDIENT_SLUGS.AQUAPHILUS_DOLOMIAE_EXTRACT,
    tagSlug: TAG_SLUGS.PEAU_ATOPIQUE,
  },
  {
    ingredientSlug: INGREDIENT_SLUGS.AQUAPHILUS_DOLOMIAE_EXTRACT,
    tagSlug: TAG_SLUGS.PEAU_REACTIVE,
  },
  {
    ingredientSlug: INGREDIENT_SLUGS.AQUAPHILUS_DOLOMIAE_EXTRACT,
    tagSlug: TAG_SLUGS.ANTI_ROUGEURS,
  },

  // aquaphilus-dolomiae-ferment-filtrate (C+ Restore - Cicatrisation)
  {
    ingredientSlug: INGREDIENT_SLUGS.AQUAPHILUS_DOLOMIAE_FERMENT_FILTRATE,
    tagSlug: TAG_SLUGS.REPARATEUR,
  },
  {
    ingredientSlug: INGREDIENT_SLUGS.AQUAPHILUS_DOLOMIAE_FERMENT_FILTRATE,
    tagSlug: TAG_SLUGS.POST_ACNE,
  },
  {
    ingredientSlug: INGREDIENT_SLUGS.AQUAPHILUS_DOLOMIAE_FERMENT_FILTRATE,
    tagSlug: TAG_SLUGS.BARRIERE_CUTANEE,
  },

  // arginine-pca (Hydratation biomimétique)
  { ingredientSlug: INGREDIENT_SLUGS.ARGININE_PCA, tagSlug: TAG_SLUGS.HUMECTANT },
  { ingredientSlug: INGREDIENT_SLUGS.ARGININE_PCA, tagSlug: TAG_SLUGS.DESHYDRATATION },
  { ingredientSlug: INGREDIENT_SLUGS.ARGININE_PCA, tagSlug: TAG_SLUGS.BIOMIMETIQUE },

  // calcium-pca (Renfort barrière)
  { ingredientSlug: INGREDIENT_SLUGS.CALCIUM_PCA, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },
  { ingredientSlug: INGREDIENT_SLUGS.CALCIUM_PCA, tagSlug: TAG_SLUGS.PEAU_SECHE },

  // collagen-amino-acids
  { ingredientSlug: INGREDIENT_SLUGS.COLLAGEN_AMINO_ACIDS, tagSlug: TAG_SLUGS.HUMECTANT },
  { ingredientSlug: INGREDIENT_SLUGS.COLLAGEN_AMINO_ACIDS, tagSlug: TAG_SLUGS.ANTI_AGE },

  // comedoclastin (Extrait de chardon-marie titré pour l'acné)
  { ingredientSlug: INGREDIENT_SLUGS.COMEDOCLASTIN, tagSlug: TAG_SLUGS.ANTI_ACNE },
  { ingredientSlug: INGREDIENT_SLUGS.COMEDOCLASTIN, tagSlug: TAG_SLUGS.SEBO_REGULATEUR },
  { ingredientSlug: INGREDIENT_SLUGS.COMEDOCLASTIN, tagSlug: TAG_SLUGS.NON_COMEDOGENE },

  // copper-sulfate (Purifiant & Anti-inflammatoire)
  { ingredientSlug: INGREDIENT_SLUGS.COPPER_SULFATE, tagSlug: TAG_SLUGS.ANTISEPTIQUE },
  { ingredientSlug: INGREDIENT_SLUGS.COPPER_SULFATE, tagSlug: TAG_SLUGS.ANTI_ACNE },
  { ingredientSlug: INGREDIENT_SLUGS.COPPER_SULFATE, tagSlug: TAG_SLUGS.ANTI_ROUGEURS },

  // curcuma-longa-root-extract
  { ingredientSlug: INGREDIENT_SLUGS.CURCUMA_LONGA_ROOT_EXTRACT, tagSlug: TAG_SLUGS.ANTI_OXYDANT },
  { ingredientSlug: INGREDIENT_SLUGS.CURCUMA_LONGA_ROOT_EXTRACT, tagSlug: TAG_SLUGS.ECLAT },
  { ingredientSlug: INGREDIENT_SLUGS.CURCUMA_LONGA_ROOT_EXTRACT, tagSlug: TAG_SLUGS.ANTI_AGE },

  // d-sensinose (Postbiotique ultra-apaisant)
  { ingredientSlug: INGREDIENT_SLUGS.D_SENSINOSE, tagSlug: TAG_SLUGS.PEAU_REACTIVE },
  { ingredientSlug: INGREDIENT_SLUGS.D_SENSINOSE, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },
  { ingredientSlug: INGREDIENT_SLUGS.D_SENSINOSE, tagSlug: TAG_SLUGS.HYPOALLERGENIQUE },

  // ectoin (Protection stress environnemental)
  { ingredientSlug: INGREDIENT_SLUGS.ECTOIN, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },
  { ingredientSlug: INGREDIENT_SLUGS.ECTOIN, tagSlug: TAG_SLUGS.PEAU_REACTIVE },
  { ingredientSlug: INGREDIENT_SLUGS.ECTOIN, tagSlug: TAG_SLUGS.ANTI_AGE },
  { ingredientSlug: INGREDIENT_SLUGS.ECTOIN, tagSlug: TAG_SLUGS.DESHYDRATATION },

  // glyceryl-glucoside (Activateur d'aquaporines)
  { ingredientSlug: INGREDIENT_SLUGS.GLYCERYL_GLUCOSIDE, tagSlug: TAG_SLUGS.DESHYDRATATION },
  { ingredientSlug: INGREDIENT_SLUGS.GLYCERYL_GLUCOSIDE, tagSlug: TAG_SLUGS.HUMECTANT },

  // huile-onagre (Riche en GLA pour la barrière)
  { ingredientSlug: INGREDIENT_SLUGS.HUILE_ONAGRE, tagSlug: TAG_SLUGS.HUILE },
  { ingredientSlug: INGREDIENT_SLUGS.HUILE_ONAGRE, tagSlug: TAG_SLUGS.PEAU_ATOPIQUE },
  { ingredientSlug: INGREDIENT_SLUGS.HUILE_ONAGRE, tagSlug: TAG_SLUGS.PEAU_SECHE },
  { ingredientSlug: INGREDIENT_SLUGS.HUILE_ONAGRE, tagSlug: TAG_SLUGS.EMOLLIENT },

  // oxyde-de-fer (Pigments protecteurs)
  { ingredientSlug: INGREDIENT_SLUGS.IRON_OXIDES, tagSlug: TAG_SLUGS.SOLAIRE_TEINTE },
  { ingredientSlug: INGREDIENT_SLUGS.IRON_OXIDES, tagSlug: TAG_SLUGS.HYPERPIGMENTATION },

  // lens-esculenta-seed-extract
  {
    ingredientSlug: INGREDIENT_SLUGS.LENS_ESCULENTA_SEED_EXTRACT,
    tagSlug: TAG_SLUGS.PORES_DILATES,
  },
  {
    ingredientSlug: INGREDIENT_SLUGS.LENS_ESCULENTA_SEED_EXTRACT,
    tagSlug: TAG_SLUGS.SEBO_REGULATEUR,
  },
  { ingredientSlug: INGREDIENT_SLUGS.LENS_ESCULENTA_SEED_EXTRACT, tagSlug: TAG_SLUGS.BRILLANCE },

  // malic-acid-ester
  { ingredientSlug: INGREDIENT_SLUGS.MALIC_ACID_ESTER, tagSlug: TAG_SLUGS.EXFOLIANT },
  { ingredientSlug: INGREDIENT_SLUGS.MALIC_ACID_ESTER, tagSlug: TAG_SLUGS.ECLAT },

  // melitane (Peptide stimulant la mélanine)
  { ingredientSlug: INGREDIENT_SLUGS.MELITANE, tagSlug: TAG_SLUGS.PROTECTION_SOLAIRE },
  { ingredientSlug: INGREDIENT_SLUGS.MELITANE, tagSlug: TAG_SLUGS.HYPERPIGMENTATION },

  // palmitamide-mea (Apaise l'inflammation barrière)
  { ingredientSlug: INGREDIENT_SLUGS.PALMITAMIDE_MEA, tagSlug: TAG_SLUGS.PEAU_ATOPIQUE },
  { ingredientSlug: INGREDIENT_SLUGS.PALMITAMIDE_MEA, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },
  { ingredientSlug: INGREDIENT_SLUGS.PALMITAMIDE_MEA, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },

  // papain
  { ingredientSlug: INGREDIENT_SLUGS.PAPAIN, tagSlug: TAG_SLUGS.EXFOLIANT },
  { ingredientSlug: INGREDIENT_SLUGS.PAPAIN, tagSlug: TAG_SLUGS.ECLAT },

  // piroctone-olamine
  { ingredientSlug: INGREDIENT_SLUGS.PIROCTONE_OLAMINE, tagSlug: TAG_SLUGS.ANTISEPTIQUE },

  // prunus-amygdalus-dulcis-oil
  { ingredientSlug: INGREDIENT_SLUGS.PRUNUS_AMYGDALUS_DULCIS_OIL, tagSlug: TAG_SLUGS.PEAU_SECHE },
  { ingredientSlug: INGREDIENT_SLUGS.PRUNUS_AMYGDALUS_DULCIS_OIL, tagSlug: TAG_SLUGS.EMOLLIENT },
  { ingredientSlug: INGREDIENT_SLUGS.PRUNUS_AMYGDALUS_DULCIS_OIL, tagSlug: TAG_SLUGS.HUILE },

  // resveratrol
  { ingredientSlug: INGREDIENT_SLUGS.RESVERATROL, tagSlug: TAG_SLUGS.ANTI_OXYDANT },
  { ingredientSlug: INGREDIENT_SLUGS.RESVERATROL, tagSlug: TAG_SLUGS.ANTI_AGE },
  { ingredientSlug: INGREDIENT_SLUGS.RESVERATROL, tagSlug: TAG_SLUGS.ANTI_ROUGEURS },

  // ricinus-communis-seed-oil
  { ingredientSlug: INGREDIENT_SLUGS.RICINUS_COMMUNIS_SEED_OIL, tagSlug: TAG_SLUGS.HUILE },
  { ingredientSlug: INGREDIENT_SLUGS.RICINUS_COMMUNIS_SEED_OIL, tagSlug: TAG_SLUGS.OCCLUSIF },

  // sepiwhite
  { ingredientSlug: INGREDIENT_SLUGS.SEPIWHITE, tagSlug: TAG_SLUGS.ANTI_TACHES },
  { ingredientSlug: INGREDIENT_SLUGS.SEPIWHITE, tagSlug: TAG_SLUGS.HYPERPIGMENTATION },
  { ingredientSlug: INGREDIENT_SLUGS.SEPIWHITE, tagSlug: TAG_SLUGS.ECLAT },

  // sodium-pca
  { ingredientSlug: INGREDIENT_SLUGS.SODIUM_PCA, tagSlug: TAG_SLUGS.HUMECTANT },
  { ingredientSlug: INGREDIENT_SLUGS.SODIUM_PCA, tagSlug: TAG_SLUGS.BIOMIMETIQUE },
  { ingredientSlug: INGREDIENT_SLUGS.SODIUM_PCA, tagSlug: TAG_SLUGS.DESHYDRATATION },

  // sylibum-marianum-fruit-extract (Antioxydant & Anti-imperfections)
  {
    ingredientSlug: INGREDIENT_SLUGS.SYLIBUM_MARIANUM_FRUIT_EXTRACT,
    tagSlug: TAG_SLUGS.ANTI_OXYDANT,
  },
  { ingredientSlug: INGREDIENT_SLUGS.SYLIBUM_MARIANUM_FRUIT_EXTRACT, tagSlug: TAG_SLUGS.ANTI_ACNE },
  {
    ingredientSlug: INGREDIENT_SLUGS.SYLIBUM_MARIANUM_FRUIT_EXTRACT,
    tagSlug: TAG_SLUGS.ANTI_ROUGEURS,
  },

  // titanium-dioxide
  { ingredientSlug: INGREDIENT_SLUGS.TITANIUM_DIOXIDE, tagSlug: TAG_SLUGS.PROTECTION_SOLAIRE },
  { ingredientSlug: INGREDIENT_SLUGS.TITANIUM_DIOXIDE, tagSlug: TAG_SLUGS.FILTRES_MINERAUX },

  // tocopheryl-glucoside (Précurseur Vitamine E stable)
  { ingredientSlug: INGREDIENT_SLUGS.TOCOPHERYL_GLUCOSIDE, tagSlug: TAG_SLUGS.ANTI_OXYDANT },
  { ingredientSlug: INGREDIENT_SLUGS.TOCOPHERYL_GLUCOSIDE, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },
  { ingredientSlug: INGREDIENT_SLUGS.TOCOPHERYL_GLUCOSIDE, tagSlug: TAG_SLUGS.ANTI_AGE },

  // triasorb (Filtre organique ultra-large spectre)
  { ingredientSlug: INGREDIENT_SLUGS.TRIASORB, tagSlug: TAG_SLUGS.PROTECTION_SOLAIRE },
  { ingredientSlug: INGREDIENT_SLUGS.TRIASORB, tagSlug: TAG_SLUGS.PROTECTION_LUMIERE_BLEUE },
  { ingredientSlug: INGREDIENT_SLUGS.TRIASORB, tagSlug: TAG_SLUGS.ANTI_TACHES },

  // zinc-oxide
  { ingredientSlug: INGREDIENT_SLUGS.ZINC_OXIDE, tagSlug: TAG_SLUGS.PROTECTION_SOLAIRE },
  { ingredientSlug: INGREDIENT_SLUGS.ZINC_OXIDE, tagSlug: TAG_SLUGS.FILTRES_MINERAUX },
  { ingredientSlug: INGREDIENT_SLUGS.ZINC_OXIDE, tagSlug: TAG_SLUGS.ANTI_ROUGEURS },

  // zinc-pca
  { ingredientSlug: INGREDIENT_SLUGS.ZINC_PCA, tagSlug: TAG_SLUGS.SEBO_REGULATEUR },
  { ingredientSlug: INGREDIENT_SLUGS.ZINC_PCA, tagSlug: TAG_SLUGS.ANTI_ACNE },
  { ingredientSlug: INGREDIENT_SLUGS.ZINC_PCA, tagSlug: TAG_SLUGS.BRILLANCE },

  // zinc-sulfate
  { ingredientSlug: INGREDIENT_SLUGS.ZINC_SULFATE, tagSlug: TAG_SLUGS.ANTISEPTIQUE },
  { ingredientSlug: INGREDIENT_SLUGS.ZINC_SULFATE, tagSlug: TAG_SLUGS.ANTI_ACNE },
  { ingredientSlug: INGREDIENT_SLUGS.ZINC_SULFATE, tagSlug: TAG_SLUGS.ANTI_ROUGEURS },
  { ingredientSlug: INGREDIENT_SLUGS.VITAMIN_C, tagSlug: TAG_SLUGS.ANTI_TACHES },
  { ingredientSlug: INGREDIENT_SLUGS.VITAMIN_C, tagSlug: TAG_SLUGS.ANTI_AGE },
  { ingredientSlug: INGREDIENT_SLUGS.VITAMIN_C, tagSlug: TAG_SLUGS.ANTI_OXYDANT },
  { ingredientSlug: INGREDIENT_SLUGS.VITAMIN_C, tagSlug: TAG_SLUGS.ECLAT },
  { ingredientSlug: INGREDIENT_SLUGS.VITAMIN_C, tagSlug: TAG_SLUGS.HYPERPIGMENTATION },
  { ingredientSlug: INGREDIENT_SLUGS.VITAMIN_C, tagSlug: TAG_SLUGS.SOIN_DE_JOUR },

  { ingredientSlug: INGREDIENT_SLUGS.THREE_O_ETHYL_ASCORBIC_ACID, tagSlug: TAG_SLUGS.ANTI_TACHES },
  {
    ingredientSlug: INGREDIENT_SLUGS.THREE_O_ETHYL_ASCORBIC_ACID,
    tagSlug: TAG_SLUGS.HYPERPIGMENTATION,
  },
  { ingredientSlug: INGREDIENT_SLUGS.THREE_O_ETHYL_ASCORBIC_ACID, tagSlug: TAG_SLUGS.ANTI_AGE },
  { ingredientSlug: INGREDIENT_SLUGS.THREE_O_ETHYL_ASCORBIC_ACID, tagSlug: TAG_SLUGS.ANTI_OXYDANT },
  { ingredientSlug: INGREDIENT_SLUGS.THREE_O_ETHYL_ASCORBIC_ACID, tagSlug: TAG_SLUGS.ECLAT },
  { ingredientSlug: INGREDIENT_SLUGS.THREE_O_ETHYL_ASCORBIC_ACID, tagSlug: TAG_SLUGS.SOIN_DE_JOUR },

  { ingredientSlug: INGREDIENT_SLUGS.ASCORBYL_GLUCOSIDE, tagSlug: TAG_SLUGS.ANTI_TACHES },
  { ingredientSlug: INGREDIENT_SLUGS.ASCORBYL_GLUCOSIDE, tagSlug: TAG_SLUGS.HYPERPIGMENTATION },
  { ingredientSlug: INGREDIENT_SLUGS.ASCORBYL_GLUCOSIDE, tagSlug: TAG_SLUGS.ANTI_OXYDANT },
  { ingredientSlug: INGREDIENT_SLUGS.ASCORBYL_GLUCOSIDE, tagSlug: TAG_SLUGS.ECLAT },
  { ingredientSlug: INGREDIENT_SLUGS.ASCORBYL_GLUCOSIDE, tagSlug: TAG_SLUGS.SOIN_DE_JOUR },
  { ingredientSlug: INGREDIENT_SLUGS.ASCORBYL_GLUCOSIDE, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },

  { ingredientSlug: INGREDIENT_SLUGS.ASCORBYL_PALMITATE, tagSlug: TAG_SLUGS.ANTI_AGE },
  { ingredientSlug: INGREDIENT_SLUGS.ASCORBYL_PALMITATE, tagSlug: TAG_SLUGS.ANTI_OXYDANT },
  { ingredientSlug: INGREDIENT_SLUGS.ASCORBYL_PALMITATE, tagSlug: TAG_SLUGS.SOIN_DE_NUIT },
  { ingredientSlug: INGREDIENT_SLUGS.ASCORBYL_PALMITATE, tagSlug: TAG_SLUGS.PEAU_SECHE },

  { ingredientSlug: INGREDIENT_SLUGS.MAGNESIUM_ASCORBYL_PHOSPHATE, tagSlug: TAG_SLUGS.ANTI_TACHES },
  { ingredientSlug: INGREDIENT_SLUGS.MAGNESIUM_ASCORBYL_PHOSPHATE, tagSlug: TAG_SLUGS.ANTI_ACNE },
  {
    ingredientSlug: INGREDIENT_SLUGS.MAGNESIUM_ASCORBYL_PHOSPHATE,
    tagSlug: TAG_SLUGS.ANTI_OXYDANT,
  },
  {
    ingredientSlug: INGREDIENT_SLUGS.MAGNESIUM_ASCORBYL_PHOSPHATE,
    tagSlug: TAG_SLUGS.PEAU_SENSIBLE,
  },

  { ingredientSlug: INGREDIENT_SLUGS.SODIUM_ASCORBYL_PHOSPHATE, tagSlug: TAG_SLUGS.ANTI_ACNE },
  {
    ingredientSlug: INGREDIENT_SLUGS.SODIUM_ASCORBYL_PHOSPHATE,
    tagSlug: TAG_SLUGS.HYPERPIGMENTATION,
  },
  { ingredientSlug: INGREDIENT_SLUGS.SODIUM_ASCORBYL_PHOSPHATE, tagSlug: TAG_SLUGS.ANTI_OXYDANT },
  {
    ingredientSlug: INGREDIENT_SLUGS.SODIUM_ASCORBYL_PHOSPHATE,
    tagSlug: TAG_SLUGS.SEBO_REGULATEUR,
  },
  { ingredientSlug: INGREDIENT_SLUGS.SODIUM_ASCORBYL_PHOSPHATE, tagSlug: TAG_SLUGS.PEAU_MIXTE },

  { ingredientSlug: INGREDIENT_SLUGS.THD_ASCORBATE, tagSlug: TAG_SLUGS.ANTI_AGE },
  { ingredientSlug: INGREDIENT_SLUGS.THD_ASCORBATE, tagSlug: TAG_SLUGS.HYPERPIGMENTATION },
  { ingredientSlug: INGREDIENT_SLUGS.THD_ASCORBATE, tagSlug: TAG_SLUGS.ANTI_OXYDANT },
  { ingredientSlug: INGREDIENT_SLUGS.THD_ASCORBATE, tagSlug: TAG_SLUGS.ECLAT },
  { ingredientSlug: INGREDIENT_SLUGS.THD_ASCORBATE, tagSlug: TAG_SLUGS.PEAU_SECHE },
  { ingredientSlug: INGREDIENT_SLUGS.THD_ASCORBATE, tagSlug: TAG_SLUGS.SOIN_DE_NUIT },

  // ── Dépigmentants hors vitamine C ─────────────────────────────────────────
  { ingredientSlug: INGREDIENT_SLUGS.ALPHA_ARBUTIN, tagSlug: TAG_SLUGS.ANTI_TACHES },
  { ingredientSlug: INGREDIENT_SLUGS.ALPHA_ARBUTIN, tagSlug: TAG_SLUGS.HYPERPIGMENTATION },
  { ingredientSlug: INGREDIENT_SLUGS.ALPHA_ARBUTIN, tagSlug: TAG_SLUGS.ECLAT },
  { ingredientSlug: INGREDIENT_SLUGS.ALPHA_ARBUTIN, tagSlug: TAG_SLUGS.POST_ACNE },

  { ingredientSlug: INGREDIENT_SLUGS.KOJIC_ACID, tagSlug: TAG_SLUGS.ANTI_TACHES },
  { ingredientSlug: INGREDIENT_SLUGS.KOJIC_ACID, tagSlug: TAG_SLUGS.HYPERPIGMENTATION },
  { ingredientSlug: INGREDIENT_SLUGS.KOJIC_ACID, tagSlug: TAG_SLUGS.ECLAT },

  { ingredientSlug: INGREDIENT_SLUGS.TRANEXAMIC_ACID, tagSlug: TAG_SLUGS.HYPERPIGMENTATION },
  { ingredientSlug: INGREDIENT_SLUGS.TRANEXAMIC_ACID, tagSlug: TAG_SLUGS.ANTI_TACHES },
  { ingredientSlug: INGREDIENT_SLUGS.TRANEXAMIC_ACID, tagSlug: TAG_SLUGS.ROSACEE },
  { ingredientSlug: INGREDIENT_SLUGS.TRANEXAMIC_ACID, tagSlug: TAG_SLUGS.ECLAT },

  { ingredientSlug: INGREDIENT_SLUGS.GLUTATHION, tagSlug: TAG_SLUGS.ANTI_TACHES },
  { ingredientSlug: INGREDIENT_SLUGS.GLUTATHION, tagSlug: TAG_SLUGS.HYPERPIGMENTATION },
  { ingredientSlug: INGREDIENT_SLUGS.GLUTATHION, tagSlug: TAG_SLUGS.ANTI_AGE },
  { ingredientSlug: INGREDIENT_SLUGS.GLUTATHION, tagSlug: TAG_SLUGS.ANTI_OXYDANT },
  { ingredientSlug: INGREDIENT_SLUGS.GLUTATHION, tagSlug: TAG_SLUGS.ECLAT },

  // ── Anti-rougeurs / Rosacée / Peau sensible ───────────────────────────────
  { ingredientSlug: INGREDIENT_SLUGS.AZELAIC_ACID, tagSlug: TAG_SLUGS.ROSACEE },
  { ingredientSlug: INGREDIENT_SLUGS.AZELAIC_ACID, tagSlug: TAG_SLUGS.ANTI_ROUGEURS },
  { ingredientSlug: INGREDIENT_SLUGS.AZELAIC_ACID, tagSlug: TAG_SLUGS.ANTI_ACNE },
  { ingredientSlug: INGREDIENT_SLUGS.AZELAIC_ACID, tagSlug: TAG_SLUGS.HYPERPIGMENTATION },
  { ingredientSlug: INGREDIENT_SLUGS.AZELAIC_ACID, tagSlug: TAG_SLUGS.COUPEROSE },
  { ingredientSlug: INGREDIENT_SLUGS.AZELAIC_ACID, tagSlug: TAG_SLUGS.SEBO_REGULATEUR },
  { ingredientSlug: INGREDIENT_SLUGS.AZELAIC_ACID, tagSlug: TAG_SLUGS.POST_ACNE },
  { ingredientSlug: INGREDIENT_SLUGS.AZELAIC_ACID, tagSlug: TAG_SLUGS.ANTI_TACHES },

  { ingredientSlug: INGREDIENT_SLUGS.NIACINAMIDE, tagSlug: TAG_SLUGS.ANTI_ROUGEURS },
  { ingredientSlug: INGREDIENT_SLUGS.NIACINAMIDE, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },
  { ingredientSlug: INGREDIENT_SLUGS.NIACINAMIDE, tagSlug: TAG_SLUGS.PEAU_MIXTE },
  { ingredientSlug: INGREDIENT_SLUGS.NIACINAMIDE, tagSlug: TAG_SLUGS.PEAU_GRASSE },
  { ingredientSlug: INGREDIENT_SLUGS.NIACINAMIDE, tagSlug: TAG_SLUGS.ANTI_ACNE },
  { ingredientSlug: INGREDIENT_SLUGS.NIACINAMIDE, tagSlug: TAG_SLUGS.SEBO_REGULATEUR },
  { ingredientSlug: INGREDIENT_SLUGS.NIACINAMIDE, tagSlug: TAG_SLUGS.ECLAT },
  { ingredientSlug: INGREDIENT_SLUGS.NIACINAMIDE, tagSlug: TAG_SLUGS.HYPERPIGMENTATION },
  { ingredientSlug: INGREDIENT_SLUGS.NIACINAMIDE, tagSlug: TAG_SLUGS.ANTI_TACHES },

  { ingredientSlug: INGREDIENT_SLUGS.CENTELLA_ASIATICA, tagSlug: TAG_SLUGS.REPARATEUR },
  { ingredientSlug: INGREDIENT_SLUGS.CENTELLA_ASIATICA, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },
  { ingredientSlug: INGREDIENT_SLUGS.CENTELLA_ASIATICA, tagSlug: TAG_SLUGS.ANTI_ROUGEURS },
  { ingredientSlug: INGREDIENT_SLUGS.CENTELLA_ASIATICA, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },
  { ingredientSlug: INGREDIENT_SLUGS.CENTELLA_ASIATICA, tagSlug: TAG_SLUGS.ANTI_ACNE },

  { ingredientSlug: INGREDIENT_SLUGS.ASIATICOSIDE, tagSlug: TAG_SLUGS.REPARATEUR },
  { ingredientSlug: INGREDIENT_SLUGS.ASIATICOSIDE, tagSlug: TAG_SLUGS.ROSACEE },
  { ingredientSlug: INGREDIENT_SLUGS.ASIATICOSIDE, tagSlug: TAG_SLUGS.PEAU_REACTIVE },

  { ingredientSlug: INGREDIENT_SLUGS.PANTHENOL, tagSlug: TAG_SLUGS.REPARATEUR },
  { ingredientSlug: INGREDIENT_SLUGS.PANTHENOL, tagSlug: TAG_SLUGS.HUMECTANT },
  { ingredientSlug: INGREDIENT_SLUGS.PANTHENOL, tagSlug: TAG_SLUGS.PEAU_SECHE },
  { ingredientSlug: INGREDIENT_SLUGS.PANTHENOL, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },

  { ingredientSlug: INGREDIENT_SLUGS.ALLANTOIN, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },
  { ingredientSlug: INGREDIENT_SLUGS.ALLANTOIN, tagSlug: TAG_SLUGS.REPARATEUR },
  { ingredientSlug: INGREDIENT_SLUGS.ALLANTOIN, tagSlug: TAG_SLUGS.ANTI_ROUGEURS },
  { ingredientSlug: INGREDIENT_SLUGS.ALLANTOIN, tagSlug: TAG_SLUGS.PEAU_REACTIVE },

  { ingredientSlug: INGREDIENT_SLUGS.GLYCYRRHETINIC_ACID, tagSlug: TAG_SLUGS.ANTI_ROUGEURS },
  { ingredientSlug: INGREDIENT_SLUGS.GLYCYRRHETINIC_ACID, tagSlug: TAG_SLUGS.PEAU_REACTIVE },
  { ingredientSlug: INGREDIENT_SLUGS.GLYCYRRHETINIC_ACID, tagSlug: TAG_SLUGS.ROSACEE },

  { ingredientSlug: INGREDIENT_SLUGS.AMMONIUM_GLYCYRRHIZATE, tagSlug: TAG_SLUGS.ANTI_ROUGEURS },
  { ingredientSlug: INGREDIENT_SLUGS.AMMONIUM_GLYCYRRHIZATE, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },

  { ingredientSlug: INGREDIENT_SLUGS.GLYCYRRHIZA_INFLATA, tagSlug: TAG_SLUGS.ROSACEE },
  { ingredientSlug: INGREDIENT_SLUGS.GLYCYRRHIZA_INFLATA, tagSlug: TAG_SLUGS.ANTI_ROUGEURS },
  { ingredientSlug: INGREDIENT_SLUGS.GLYCYRRHIZA_INFLATA, tagSlug: TAG_SLUGS.ANTI_ACNE },
  { ingredientSlug: INGREDIENT_SLUGS.GLYCYRRHIZA_INFLATA, tagSlug: TAG_SLUGS.SEBO_REGULATEUR },
  { ingredientSlug: INGREDIENT_SLUGS.GLYCYRRHIZA_INFLATA, tagSlug: TAG_SLUGS.ANTI_OXYDANT },

  { ingredientSlug: INGREDIENT_SLUGS.HEARTLEAF, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },
  { ingredientSlug: INGREDIENT_SLUGS.HEARTLEAF, tagSlug: TAG_SLUGS.ANTI_ROUGEURS },
  { ingredientSlug: INGREDIENT_SLUGS.HEARTLEAF, tagSlug: TAG_SLUGS.ANTI_ACNE },
  { ingredientSlug: INGREDIENT_SLUGS.HEARTLEAF, tagSlug: TAG_SLUGS.SEBO_REGULATEUR },
  { ingredientSlug: INGREDIENT_SLUGS.HEARTLEAF, tagSlug: TAG_SLUGS.HUMECTANT },

  { ingredientSlug: INGREDIENT_SLUGS.AVENA_SATIVA, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },
  { ingredientSlug: INGREDIENT_SLUGS.AVENA_SATIVA, tagSlug: TAG_SLUGS.ANTI_ROUGEURS },
  { ingredientSlug: INGREDIENT_SLUGS.AVENA_SATIVA, tagSlug: TAG_SLUGS.REPARATEUR },

  { ingredientSlug: INGREDIENT_SLUGS.CALENDULA, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },
  { ingredientSlug: INGREDIENT_SLUGS.CALENDULA, tagSlug: TAG_SLUGS.BIO_NATUREL },
  { ingredientSlug: INGREDIENT_SLUGS.CALENDULA, tagSlug: TAG_SLUGS.REPARATEUR },

  { ingredientSlug: INGREDIENT_SLUGS.GREEN_TEA, tagSlug: TAG_SLUGS.ANTI_ROUGEURS },
  { ingredientSlug: INGREDIENT_SLUGS.GREEN_TEA, tagSlug: TAG_SLUGS.ANTI_AGE },
  { ingredientSlug: INGREDIENT_SLUGS.GREEN_TEA, tagSlug: TAG_SLUGS.ANTI_ACNE },
  { ingredientSlug: INGREDIENT_SLUGS.GREEN_TEA, tagSlug: TAG_SLUGS.ANTI_OXYDANT },
  { ingredientSlug: INGREDIENT_SLUGS.GREEN_TEA, tagSlug: TAG_SLUGS.SEBO_REGULATEUR },

  { ingredientSlug: INGREDIENT_SLUGS.ALOE_VERA, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },
  { ingredientSlug: INGREDIENT_SLUGS.ALOE_VERA, tagSlug: TAG_SLUGS.ANTI_ROUGEURS },
  { ingredientSlug: INGREDIENT_SLUGS.ALOE_VERA, tagSlug: TAG_SLUGS.REPARATEUR },
  { ingredientSlug: INGREDIENT_SLUGS.ALOE_VERA, tagSlug: TAG_SLUGS.HUMECTANT },

  // ── Hydratation / Barrière ─────────────────────────────────────────────────
  { ingredientSlug: INGREDIENT_SLUGS.HYALURONIC_ACID, tagSlug: TAG_SLUGS.HUMECTANT },
  { ingredientSlug: INGREDIENT_SLUGS.HYALURONIC_ACID, tagSlug: TAG_SLUGS.PEAU_SECHE },
  { ingredientSlug: INGREDIENT_SLUGS.HYALURONIC_ACID, tagSlug: TAG_SLUGS.DESHYDRATATION },

  { ingredientSlug: INGREDIENT_SLUGS.SODIUM_HYALURONATE, tagSlug: TAG_SLUGS.HUMECTANT },
  { ingredientSlug: INGREDIENT_SLUGS.SODIUM_HYALURONATE, tagSlug: TAG_SLUGS.PEAU_SECHE },
  { ingredientSlug: INGREDIENT_SLUGS.SODIUM_HYALURONATE, tagSlug: TAG_SLUGS.DESHYDRATATION },

  { ingredientSlug: INGREDIENT_SLUGS.POLYGLUTAMIC_ACID, tagSlug: TAG_SLUGS.HUMECTANT },
  { ingredientSlug: INGREDIENT_SLUGS.POLYGLUTAMIC_ACID, tagSlug: TAG_SLUGS.PEAU_SECHE },

  { ingredientSlug: INGREDIENT_SLUGS.ARGIRELINE, tagSlug: TAG_SLUGS.ANTI_AGE },
  { ingredientSlug: INGREDIENT_SLUGS.ARGIRELINE, tagSlug: TAG_SLUGS.ECLAT },

  { ingredientSlug: INGREDIENT_SLUGS.BAKUCHIOL, tagSlug: TAG_SLUGS.ANTI_AGE },
  { ingredientSlug: INGREDIENT_SLUGS.BAKUCHIOL, tagSlug: TAG_SLUGS.ANTI_ACNE },
  { ingredientSlug: INGREDIENT_SLUGS.BAKUCHIOL, tagSlug: TAG_SLUGS.ECLAT },
  { ingredientSlug: INGREDIENT_SLUGS.BAKUCHIOL, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },

  { ingredientSlug: INGREDIENT_SLUGS.BEEF_TALLOW, tagSlug: TAG_SLUGS.PEAU_SECHE },
  { ingredientSlug: INGREDIENT_SLUGS.BEEF_TALLOW, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },
  { ingredientSlug: INGREDIENT_SLUGS.BEEF_TALLOW, tagSlug: TAG_SLUGS.HUMECTANT },

  { ingredientSlug: INGREDIENT_SLUGS.CERAMIDE_AP, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },
  { ingredientSlug: INGREDIENT_SLUGS.CERAMIDE_AP, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },
  { ingredientSlug: INGREDIENT_SLUGS.CERAMIDE_AP, tagSlug: TAG_SLUGS.PEAU_SECHE },
  { ingredientSlug: INGREDIENT_SLUGS.CERAMIDE_AP, tagSlug: TAG_SLUGS.REPARATEUR },
  { ingredientSlug: INGREDIENT_SLUGS.CERAMIDE_AP, tagSlug: TAG_SLUGS.PEAU_REACTIVE },

  { ingredientSlug: INGREDIENT_SLUGS.CERAMIDE_EOP, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },
  { ingredientSlug: INGREDIENT_SLUGS.CERAMIDE_EOP, tagSlug: TAG_SLUGS.PEAU_SECHE },
  { ingredientSlug: INGREDIENT_SLUGS.CERAMIDE_EOP, tagSlug: TAG_SLUGS.REPARATEUR },
  { ingredientSlug: INGREDIENT_SLUGS.CERAMIDE_EOP, tagSlug: TAG_SLUGS.PEAU_REACTIVE },

  { ingredientSlug: INGREDIENT_SLUGS.CERAMIDE_NP, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },
  { ingredientSlug: INGREDIENT_SLUGS.CERAMIDE_NP, tagSlug: TAG_SLUGS.PEAU_SECHE },
  { ingredientSlug: INGREDIENT_SLUGS.CERAMIDE_NP, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },
  { ingredientSlug: INGREDIENT_SLUGS.CERAMIDE_NP, tagSlug: TAG_SLUGS.REPARATEUR },
  { ingredientSlug: INGREDIENT_SLUGS.CERAMIDE_NP, tagSlug: TAG_SLUGS.PEAU_REACTIVE },

  { ingredientSlug: INGREDIENT_SLUGS.CERAMIDE_NS, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },
  { ingredientSlug: INGREDIENT_SLUGS.CERAMIDE_NS, tagSlug: TAG_SLUGS.PEAU_SECHE },
  { ingredientSlug: INGREDIENT_SLUGS.CERAMIDE_NS, tagSlug: TAG_SLUGS.REPARATEUR },
  { ingredientSlug: INGREDIENT_SLUGS.CERAMIDE_NS, tagSlug: TAG_SLUGS.PEAU_REACTIVE },

  { ingredientSlug: INGREDIENT_SLUGS.CERAMIDES, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },
  { ingredientSlug: INGREDIENT_SLUGS.CERAMIDES, tagSlug: TAG_SLUGS.PEAU_SECHE },
  { ingredientSlug: INGREDIENT_SLUGS.CERAMIDES, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },
  { ingredientSlug: INGREDIENT_SLUGS.CERAMIDES, tagSlug: TAG_SLUGS.REPARATEUR },
  { ingredientSlug: INGREDIENT_SLUGS.CERAMIDES, tagSlug: TAG_SLUGS.PEAU_REACTIVE },

  { ingredientSlug: INGREDIENT_SLUGS.CHOLESTEROL, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },
  { ingredientSlug: INGREDIENT_SLUGS.CHOLESTEROL, tagSlug: TAG_SLUGS.PEAU_SECHE },
  { ingredientSlug: INGREDIENT_SLUGS.CHOLESTEROL, tagSlug: TAG_SLUGS.REPARATEUR },

  { ingredientSlug: INGREDIENT_SLUGS.ESCIN, tagSlug: TAG_SLUGS.ANTI_ROUGEURS },
  { ingredientSlug: INGREDIENT_SLUGS.ESCIN, tagSlug: TAG_SLUGS.PEAU_REACTIVE },
  { ingredientSlug: INGREDIENT_SLUGS.ESCIN, tagSlug: TAG_SLUGS.ROSACEE },
  { ingredientSlug: INGREDIENT_SLUGS.ESCIN, tagSlug: TAG_SLUGS.ECLAT },
  { ingredientSlug: INGREDIENT_SLUGS.ESCIN, tagSlug: TAG_SLUGS.CONTOUR_YEUX },

  { ingredientSlug: INGREDIENT_SLUGS.GLYCOSPHINGOLIPIDS, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },
  { ingredientSlug: INGREDIENT_SLUGS.GLYCOSPHINGOLIPIDS, tagSlug: TAG_SLUGS.PEAU_SECHE },
  { ingredientSlug: INGREDIENT_SLUGS.GLYCOSPHINGOLIPIDS, tagSlug: TAG_SLUGS.ANTI_AGE },
  { ingredientSlug: INGREDIENT_SLUGS.GLYCOSPHINGOLIPIDS, tagSlug: TAG_SLUGS.ANTI_OXYDANT },

  { ingredientSlug: INGREDIENT_SLUGS.GREEN_TEA, tagSlug: TAG_SLUGS.ANTI_OXYDANT },
  { ingredientSlug: INGREDIENT_SLUGS.GREEN_TEA, tagSlug: TAG_SLUGS.ANTI_ROUGEURS },
  { ingredientSlug: INGREDIENT_SLUGS.GREEN_TEA, tagSlug: TAG_SLUGS.ANTI_ACNE },
  { ingredientSlug: INGREDIENT_SLUGS.GREEN_TEA, tagSlug: TAG_SLUGS.SEBO_REGULATEUR },
  { ingredientSlug: INGREDIENT_SLUGS.GREEN_TEA, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },

  { ingredientSlug: INGREDIENT_SLUGS.HIPPOPHAE_RHAMNOIDES, tagSlug: TAG_SLUGS.ANTI_AGE },
  { ingredientSlug: INGREDIENT_SLUGS.HIPPOPHAE_RHAMNOIDES, tagSlug: TAG_SLUGS.ANTI_OXYDANT },
  { ingredientSlug: INGREDIENT_SLUGS.HIPPOPHAE_RHAMNOIDES, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },
  { ingredientSlug: INGREDIENT_SLUGS.HIPPOPHAE_RHAMNOIDES, tagSlug: TAG_SLUGS.PEAU_SECHE },
  { ingredientSlug: INGREDIENT_SLUGS.HIPPOPHAE_RHAMNOIDES, tagSlug: TAG_SLUGS.REPARATEUR },

  { ingredientSlug: INGREDIENT_SLUGS.PLANKTON_EXTRACT, tagSlug: TAG_SLUGS.ANTI_AGE },
  { ingredientSlug: INGREDIENT_SLUGS.PLANKTON_EXTRACT, tagSlug: TAG_SLUGS.ANTI_OXYDANT },
  { ingredientSlug: INGREDIENT_SLUGS.PLANKTON_EXTRACT, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },
  { ingredientSlug: INGREDIENT_SLUGS.PLANKTON_EXTRACT, tagSlug: TAG_SLUGS.REPARATEUR },
  { ingredientSlug: INGREDIENT_SLUGS.PLANKTON_EXTRACT, tagSlug: TAG_SLUGS.HUMECTANT },

  { ingredientSlug: INGREDIENT_SLUGS.RHAMNOSE, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },
  { ingredientSlug: INGREDIENT_SLUGS.RHAMNOSE, tagSlug: TAG_SLUGS.ANTI_ROUGEURS },
  { ingredientSlug: INGREDIENT_SLUGS.RHAMNOSE, tagSlug: TAG_SLUGS.ANTI_AGE },

  { ingredientSlug: INGREDIENT_SLUGS.RUSCUS_ACULEATUS, tagSlug: TAG_SLUGS.ANTI_ROUGEURS },
  { ingredientSlug: INGREDIENT_SLUGS.RUSCUS_ACULEATUS, tagSlug: TAG_SLUGS.ROSACEE },
  { ingredientSlug: INGREDIENT_SLUGS.RUSCUS_ACULEATUS, tagSlug: TAG_SLUGS.ECLAT },
  { ingredientSlug: INGREDIENT_SLUGS.RUSCUS_ACULEATUS, tagSlug: TAG_SLUGS.CONTOUR_YEUX },

  { ingredientSlug: INGREDIENT_SLUGS.SCHISANDRA, tagSlug: TAG_SLUGS.ANTI_AGE },
  { ingredientSlug: INGREDIENT_SLUGS.SCHISANDRA, tagSlug: TAG_SLUGS.ANTI_OXYDANT },
  { ingredientSlug: INGREDIENT_SLUGS.SCHISANDRA, tagSlug: TAG_SLUGS.ANTI_ROUGEURS },
  { ingredientSlug: INGREDIENT_SLUGS.SCHISANDRA, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },

  { ingredientSlug: INGREDIENT_SLUGS.SHEA_BUTTER, tagSlug: TAG_SLUGS.PEAU_SECHE },
  { ingredientSlug: INGREDIENT_SLUGS.SHEA_BUTTER, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },
  { ingredientSlug: INGREDIENT_SLUGS.SHEA_BUTTER, tagSlug: TAG_SLUGS.REPARATEUR },
  { ingredientSlug: INGREDIENT_SLUGS.SHEA_BUTTER, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },

  { ingredientSlug: INGREDIENT_SLUGS.SILYBUM_MARIANUM, tagSlug: TAG_SLUGS.ANTI_OXYDANT },
  { ingredientSlug: INGREDIENT_SLUGS.SILYBUM_MARIANUM, tagSlug: TAG_SLUGS.ANTI_ACNE },
  { ingredientSlug: INGREDIENT_SLUGS.SILYBUM_MARIANUM, tagSlug: TAG_SLUGS.SEBO_REGULATEUR },
  { ingredientSlug: INGREDIENT_SLUGS.SILYBUM_MARIANUM, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },

  { ingredientSlug: INGREDIENT_SLUGS.SNOW_MUSHROOM, tagSlug: TAG_SLUGS.HUMECTANT },
  { ingredientSlug: INGREDIENT_SLUGS.SNOW_MUSHROOM, tagSlug: TAG_SLUGS.PEAU_SECHE },
  { ingredientSlug: INGREDIENT_SLUGS.SNOW_MUSHROOM, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },
  { ingredientSlug: INGREDIENT_SLUGS.SNOW_MUSHROOM, tagSlug: TAG_SLUGS.ANTI_AGE },
  { ingredientSlug: INGREDIENT_SLUGS.SNOW_MUSHROOM, tagSlug: TAG_SLUGS.ECLAT },
  { ingredientSlug: INGREDIENT_SLUGS.SNOW_MUSHROOM, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },

  { ingredientSlug: INGREDIENT_SLUGS.SULFUR, tagSlug: TAG_SLUGS.ANTI_ACNE },
  { ingredientSlug: INGREDIENT_SLUGS.SULFUR, tagSlug: TAG_SLUGS.SEBO_REGULATEUR },
  { ingredientSlug: INGREDIENT_SLUGS.SULFUR, tagSlug: TAG_SLUGS.KERATOLYTIQUE },
  { ingredientSlug: INGREDIENT_SLUGS.SULFUR, tagSlug: TAG_SLUGS.ANTI_ROUGEURS },
  { ingredientSlug: INGREDIENT_SLUGS.SULFUR, tagSlug: TAG_SLUGS.ROSACEE },

  { ingredientSlug: INGREDIENT_SLUGS.SPHINGOMONAS_FERMENT, tagSlug: TAG_SLUGS.HUMECTANT },
  { ingredientSlug: INGREDIENT_SLUGS.SPHINGOMONAS_FERMENT, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },
  { ingredientSlug: INGREDIENT_SLUGS.SPHINGOMONAS_FERMENT, tagSlug: TAG_SLUGS.ANTI_AGE },
  { ingredientSlug: INGREDIENT_SLUGS.SPHINGOMONAS_FERMENT, tagSlug: TAG_SLUGS.ANTI_OXYDANT },
  { ingredientSlug: INGREDIENT_SLUGS.SPHINGOMONAS_FERMENT, tagSlug: TAG_SLUGS.REPARATEUR },
  { ingredientSlug: INGREDIENT_SLUGS.SPHINGOMONAS_FERMENT, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },

  { ingredientSlug: INGREDIENT_SLUGS.SQUALANE, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },
  { ingredientSlug: INGREDIENT_SLUGS.SQUALANE, tagSlug: TAG_SLUGS.PEAU_SECHE },
  { ingredientSlug: INGREDIENT_SLUGS.SQUALANE, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },
  { ingredientSlug: INGREDIENT_SLUGS.SQUALANE, tagSlug: TAG_SLUGS.REPARATEUR },
  { ingredientSlug: INGREDIENT_SLUGS.SQUALANE, tagSlug: TAG_SLUGS.EMOLLIENT },

  { ingredientSlug: INGREDIENT_SLUGS.SYN_AKE, tagSlug: TAG_SLUGS.ANTI_AGE },
  { ingredientSlug: INGREDIENT_SLUGS.SYN_AKE, tagSlug: TAG_SLUGS.ECLAT },

  // ── Advanced Peptides (Matrixyl family & similar) ─────────────────────────────────────────────
  { ingredientSlug: INGREDIENT_SLUGS.MATRIXYL_3000, tagSlug: TAG_SLUGS.ANTI_AGE },
  { ingredientSlug: INGREDIENT_SLUGS.MATRIXYL_3000, tagSlug: TAG_SLUGS.ECLAT },
  { ingredientSlug: INGREDIENT_SLUGS.MATRIXYL_3000, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },

  { ingredientSlug: INGREDIENT_SLUGS.PALMITOYL_TRIPEPTIDE_1, tagSlug: TAG_SLUGS.ANTI_AGE },
  { ingredientSlug: INGREDIENT_SLUGS.PALMITOYL_TRIPEPTIDE_1, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },

  { ingredientSlug: INGREDIENT_SLUGS.PALMITOYL_TETRAPEPTIDE_7, tagSlug: TAG_SLUGS.ANTI_AGE },
  { ingredientSlug: INGREDIENT_SLUGS.PALMITOYL_TETRAPEPTIDE_7, tagSlug: TAG_SLUGS.ANTI_ROUGEURS },
  { ingredientSlug: INGREDIENT_SLUGS.PALMITOYL_TETRAPEPTIDE_7, tagSlug: TAG_SLUGS.REPARATEUR },

  { ingredientSlug: INGREDIENT_SLUGS.PALMITOYL_PENTAPEPTIDE_4, tagSlug: TAG_SLUGS.ANTI_AGE },
  { ingredientSlug: INGREDIENT_SLUGS.PALMITOYL_PENTAPEPTIDE_4, tagSlug: TAG_SLUGS.ECLAT },
  {
    ingredientSlug: INGREDIENT_SLUGS.PALMITOYL_PENTAPEPTIDE_4,
    tagSlug: TAG_SLUGS.BARRIERE_CUTANEE,
  },

  // ── Copper Peptides ─────────────────────────────────────────────

  { ingredientSlug: INGREDIENT_SLUGS.COPPER_PEPTIDES, tagSlug: TAG_SLUGS.ANTI_AGE },
  { ingredientSlug: INGREDIENT_SLUGS.COPPER_PEPTIDES, tagSlug: TAG_SLUGS.REPARATEUR },
  { ingredientSlug: INGREDIENT_SLUGS.COPPER_PEPTIDES, tagSlug: TAG_SLUGS.ANTI_OXYDANT },
  { ingredientSlug: INGREDIENT_SLUGS.COPPER_PEPTIDES, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },
  { ingredientSlug: INGREDIENT_SLUGS.COPPER_PEPTIDES, tagSlug: TAG_SLUGS.ANTI_AGE },

  // ── Other Peptides ─────────────────────────────────────────────
  { ingredientSlug: INGREDIENT_SLUGS.PEPTIDES, tagSlug: TAG_SLUGS.ANTI_AGE },
  { ingredientSlug: INGREDIENT_SLUGS.PEPTIDES, tagSlug: TAG_SLUGS.REPARATEUR },
  { ingredientSlug: INGREDIENT_SLUGS.PEPTIDES, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },

  // ── Exfoliants & Acids (stronger ones) ─────────────────────────────────────────────
  { ingredientSlug: INGREDIENT_SLUGS.RETINOL, tagSlug: TAG_SLUGS.ANTI_AGE },
  { ingredientSlug: INGREDIENT_SLUGS.RETINOL, tagSlug: TAG_SLUGS.ECLAT },
  { ingredientSlug: INGREDIENT_SLUGS.RETINOL, tagSlug: TAG_SLUGS.ANTI_TACHES },
  { ingredientSlug: INGREDIENT_SLUGS.RETINOL, tagSlug: TAG_SLUGS.ANTI_ACNE },
  { ingredientSlug: INGREDIENT_SLUGS.RETINOL, tagSlug: TAG_SLUGS.KERATOLYTIQUE },
  { ingredientSlug: INGREDIENT_SLUGS.RETINOL, tagSlug: TAG_SLUGS.SOIN_DE_NUIT },

  { ingredientSlug: INGREDIENT_SLUGS.RETINAL, tagSlug: TAG_SLUGS.ANTI_AGE },
  { ingredientSlug: INGREDIENT_SLUGS.RETINAL, tagSlug: TAG_SLUGS.ECLAT },
  { ingredientSlug: INGREDIENT_SLUGS.RETINAL, tagSlug: TAG_SLUGS.ANTI_TACHES },
  { ingredientSlug: INGREDIENT_SLUGS.RETINAL, tagSlug: TAG_SLUGS.ANTI_ACNE },
  { ingredientSlug: INGREDIENT_SLUGS.RETINAL, tagSlug: TAG_SLUGS.KERATOLYTIQUE },
  { ingredientSlug: INGREDIENT_SLUGS.RETINAL, tagSlug: TAG_SLUGS.SOIN_DE_NUIT },

  { ingredientSlug: INGREDIENT_SLUGS.SALICYLIC_ACID, tagSlug: TAG_SLUGS.ANTI_ACNE },
  { ingredientSlug: INGREDIENT_SLUGS.SALICYLIC_ACID, tagSlug: TAG_SLUGS.SEBO_REGULATEUR },
  { ingredientSlug: INGREDIENT_SLUGS.SALICYLIC_ACID, tagSlug: TAG_SLUGS.KERATOLYTIQUE },
  { ingredientSlug: INGREDIENT_SLUGS.SALICYLIC_ACID, tagSlug: TAG_SLUGS.PEAU_GRASSE },
  { ingredientSlug: INGREDIENT_SLUGS.SALICYLIC_ACID, tagSlug: TAG_SLUGS.POST_ACNE },
  { ingredientSlug: INGREDIENT_SLUGS.SALICYLIC_ACID, tagSlug: TAG_SLUGS.ANTI_ROUGEURS },

  { ingredientSlug: INGREDIENT_SLUGS.GLYCOLIC_ACID, tagSlug: TAG_SLUGS.ANTI_AGE },
  { ingredientSlug: INGREDIENT_SLUGS.GLYCOLIC_ACID, tagSlug: TAG_SLUGS.ECLAT },
  { ingredientSlug: INGREDIENT_SLUGS.GLYCOLIC_ACID, tagSlug: TAG_SLUGS.KERATOLYTIQUE },
  { ingredientSlug: INGREDIENT_SLUGS.GLYCOLIC_ACID, tagSlug: TAG_SLUGS.ANTI_TACHES },
  { ingredientSlug: INGREDIENT_SLUGS.GLYCOLIC_ACID, tagSlug: TAG_SLUGS.HYPERPIGMENTATION },

  { ingredientSlug: INGREDIENT_SLUGS.LACTIC_ACID, tagSlug: TAG_SLUGS.HUMECTANT },
  { ingredientSlug: INGREDIENT_SLUGS.LACTIC_ACID, tagSlug: TAG_SLUGS.KERATOLYTIQUE },
  { ingredientSlug: INGREDIENT_SLUGS.LACTIC_ACID, tagSlug: TAG_SLUGS.PEAU_SECHE },
  { ingredientSlug: INGREDIENT_SLUGS.LACTIC_ACID, tagSlug: TAG_SLUGS.ANTI_AGE },

  { ingredientSlug: INGREDIENT_SLUGS.MANDELIC_ACID, tagSlug: TAG_SLUGS.ANTI_ACNE },
  { ingredientSlug: INGREDIENT_SLUGS.MANDELIC_ACID, tagSlug: TAG_SLUGS.KERATOLYTIQUE },
  { ingredientSlug: INGREDIENT_SLUGS.MANDELIC_ACID, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },
  { ingredientSlug: INGREDIENT_SLUGS.MANDELIC_ACID, tagSlug: TAG_SLUGS.ANTI_TACHES },

  { ingredientSlug: INGREDIENT_SLUGS.PHA, tagSlug: TAG_SLUGS.HUMECTANT },
  { ingredientSlug: INGREDIENT_SLUGS.PHA, tagSlug: TAG_SLUGS.KERATOLYTIQUE },
  { ingredientSlug: INGREDIENT_SLUGS.PHA, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },
  { ingredientSlug: INGREDIENT_SLUGS.PHA, tagSlug: TAG_SLUGS.ANTI_AGE },
  { ingredientSlug: INGREDIENT_SLUGS.PHA, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },

  // ── Hydrators & Barrier Support ─────────────────────────────────────────────
  { ingredientSlug: INGREDIENT_SLUGS.UREA, tagSlug: TAG_SLUGS.HUMECTANT },
  { ingredientSlug: INGREDIENT_SLUGS.UREA, tagSlug: TAG_SLUGS.KERATOLYTIQUE },
  { ingredientSlug: INGREDIENT_SLUGS.UREA, tagSlug: TAG_SLUGS.PEAU_SECHE },
  { ingredientSlug: INGREDIENT_SLUGS.UREA, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },
  { ingredientSlug: INGREDIENT_SLUGS.UREA, tagSlug: TAG_SLUGS.REPARATEUR },

  { ingredientSlug: INGREDIENT_SLUGS.GLYCERIN, tagSlug: TAG_SLUGS.HUMECTANT },
  { ingredientSlug: INGREDIENT_SLUGS.GLYCERIN, tagSlug: TAG_SLUGS.PEAU_SECHE },
  { ingredientSlug: INGREDIENT_SLUGS.GLYCERIN, tagSlug: TAG_SLUGS.DESHYDRATATION },
  { ingredientSlug: INGREDIENT_SLUGS.GLYCERIN, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },

  // ── Regenerative / Healing ─────────────────────────────────────────────
  { ingredientSlug: INGREDIENT_SLUGS.PDRN, tagSlug: TAG_SLUGS.REPARATEUR },
  { ingredientSlug: INGREDIENT_SLUGS.PDRN, tagSlug: TAG_SLUGS.ANTI_AGE },
  { ingredientSlug: INGREDIENT_SLUGS.PDRN, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },
  { ingredientSlug: INGREDIENT_SLUGS.PDRN, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },

  // ── Miscellaneous ─────────────────────────────────────────────
  { ingredientSlug: INGREDIENT_SLUGS.HYPOCHLOROUS_ACID, tagSlug: TAG_SLUGS.ANTI_ROUGEURS },
  { ingredientSlug: INGREDIENT_SLUGS.HYPOCHLOROUS_ACID, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },
  { ingredientSlug: INGREDIENT_SLUGS.HYPOCHLOROUS_ACID, tagSlug: TAG_SLUGS.ANTI_ACNE },
  { ingredientSlug: INGREDIENT_SLUGS.HYPOCHLOROUS_ACID, tagSlug: TAG_SLUGS.REPARATEUR },

  { ingredientSlug: INGREDIENT_SLUGS.PROBIOTICS, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },
  { ingredientSlug: INGREDIENT_SLUGS.PROBIOTICS, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },
  { ingredientSlug: INGREDIENT_SLUGS.PROBIOTICS, tagSlug: TAG_SLUGS.ANTI_ROUGEURS },

  { ingredientSlug: INGREDIENT_SLUGS.POSTBIOTICS, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },
  { ingredientSlug: INGREDIENT_SLUGS.POSTBIOTICS, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },
  { ingredientSlug: INGREDIENT_SLUGS.POSTBIOTICS, tagSlug: TAG_SLUGS.REPARATEUR },

  { ingredientSlug: INGREDIENT_SLUGS.PHYTOSPHINGOSINE, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },
  { ingredientSlug: INGREDIENT_SLUGS.PHYTOSPHINGOSINE, tagSlug: TAG_SLUGS.ANTI_ACNE },
  { ingredientSlug: INGREDIENT_SLUGS.PHYTOSPHINGOSINE, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },

  { ingredientSlug: INGREDIENT_SLUGS.PENTYLENE_GLYCOL, tagSlug: TAG_SLUGS.HUMECTANT },
  { ingredientSlug: INGREDIENT_SLUGS.PENTYLENE_GLYCOL, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },

  { ingredientSlug: INGREDIENT_SLUGS.TOCOPHEROL, tagSlug: TAG_SLUGS.ANTI_OXYDANT },
  { ingredientSlug: INGREDIENT_SLUGS.TOCOPHEROL, tagSlug: TAG_SLUGS.ANTI_AGE },
  { ingredientSlug: INGREDIENT_SLUGS.TOCOPHEROL, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },

  { ingredientSlug: INGREDIENT_SLUGS.VACCINIUM_MYRTILLUS, tagSlug: TAG_SLUGS.ANTI_OXYDANT },
  { ingredientSlug: INGREDIENT_SLUGS.VACCINIUM_MYRTILLUS, tagSlug: TAG_SLUGS.ECLAT },
  { ingredientSlug: INGREDIENT_SLUGS.VACCINIUM_MYRTILLUS, tagSlug: TAG_SLUGS.ANTI_ROUGEURS },

  { ingredientSlug: INGREDIENT_SLUGS.OPHIOPOGON_JAPONICUS, tagSlug: TAG_SLUGS.HUMECTANT },
  { ingredientSlug: INGREDIENT_SLUGS.OPHIOPOGON_JAPONICUS, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },
  { ingredientSlug: INGREDIENT_SLUGS.OPHIOPOGON_JAPONICUS, tagSlug: TAG_SLUGS.REPARATEUR },

  {
    ingredientSlug: INGREDIENT_SLUGS.HUMECTANTS_EMOLLIENTS_OCCLUSIFS,
    tagSlug: TAG_SLUGS.HUMECTANT,
  },
  {
    ingredientSlug: INGREDIENT_SLUGS.HUMECTANTS_EMOLLIENTS_OCCLUSIFS,
    tagSlug: TAG_SLUGS.PEAU_SECHE,
  },
  {
    ingredientSlug: INGREDIENT_SLUGS.HUMECTANTS_EMOLLIENTS_OCCLUSIFS,
    tagSlug: TAG_SLUGS.BARRIERE_CUTANEE,
  },
  // ── Huile d'Argan (Nourrissante, anti-âge)
  { ingredientSlug: INGREDIENT_SLUGS.HUILE_D_ARGAN, tagSlug: TAG_SLUGS.EMOLLIENT },
  { ingredientSlug: INGREDIENT_SLUGS.HUILE_D_ARGAN, tagSlug: TAG_SLUGS.PEAU_SECHE },
  { ingredientSlug: INGREDIENT_SLUGS.HUILE_D_ARGAN, tagSlug: TAG_SLUGS.ANTI_AGE },

  // ── Huile de Jojoba (Sébo-régulatrice, proche du sébum humain)
  { ingredientSlug: INGREDIENT_SLUGS.HUILE_DE_JOJOBA, tagSlug: TAG_SLUGS.SEBO_REGULATEUR },
  { ingredientSlug: INGREDIENT_SLUGS.HUILE_DE_JOJOBA, tagSlug: TAG_SLUGS.PEAU_MIXTE },
  { ingredientSlug: INGREDIENT_SLUGS.HUILE_DE_JOJOBA, tagSlug: TAG_SLUGS.PEAU_GRASSE },

  // ── Huile de Pépins de Figue de Barbarie (Puissant anti-oxydant, tenseur)
  {
    ingredientSlug: INGREDIENT_SLUGS.HUILE_DE_PEPINS_DE_FIGUE_DE_BARBARIE,
    tagSlug: TAG_SLUGS.ANTI_AGE,
  },
  {
    ingredientSlug: INGREDIENT_SLUGS.HUILE_DE_PEPINS_DE_FIGUE_DE_BARBARIE,
    tagSlug: TAG_SLUGS.ANTI_OXYDANT,
  },
  {
    ingredientSlug: INGREDIENT_SLUGS.HUILE_DE_PEPINS_DE_FIGUE_DE_BARBARIE,
    tagSlug: TAG_SLUGS.ECLAT,
  },

  // ── Huile de Pépins de Raisin (Légère, régulatrice)
  { ingredientSlug: INGREDIENT_SLUGS.HUILE_DE_PEPINS_DE_RAISIN, tagSlug: TAG_SLUGS.ANTI_OXYDANT },
  { ingredientSlug: INGREDIENT_SLUGS.HUILE_DE_PEPINS_DE_RAISIN, tagSlug: TAG_SLUGS.PEAU_MIXTE },
  { ingredientSlug: INGREDIENT_SLUGS.HUILE_DE_PEPINS_DE_RAISIN, tagSlug: TAG_SLUGS.PORES_DILATES },

  // ── Menthe Poivrée (Rafraîchissante, purifiante)
  { ingredientSlug: INGREDIENT_SLUGS.MENTHE_POIVREE, tagSlug: TAG_SLUGS.ANTI_ACNE },
  { ingredientSlug: INGREDIENT_SLUGS.MENTHE_POIVREE, tagSlug: TAG_SLUGS.ECLAT },
  { ingredientSlug: INGREDIENT_SLUGS.MENTHE_POIVREE, tagSlug: TAG_SLUGS.BRILLANCE },

  // ── Romarin (Purifiant, revitalisant)
  { ingredientSlug: INGREDIENT_SLUGS.ROMARIN, tagSlug: TAG_SLUGS.ANTI_ACNE },
  { ingredientSlug: INGREDIENT_SLUGS.ROMARIN, tagSlug: TAG_SLUGS.ANTI_OXYDANT },
  { ingredientSlug: INGREDIENT_SLUGS.ROMARIN, tagSlug: TAG_SLUGS.PEAU_GRASSE },

  // ── Verveine (Apaisante, tonifiante)
  { ingredientSlug: INGREDIENT_SLUGS.VERVEINE, tagSlug: TAG_SLUGS.PEAU_REACTIVE },
  { ingredientSlug: INGREDIENT_SLUGS.VERVEINE, tagSlug: TAG_SLUGS.ECLAT },

  // ── Bourrache (Régénérante, souplesse)
  { ingredientSlug: INGREDIENT_SLUGS.BOURRACHE, tagSlug: TAG_SLUGS.REPARATEUR },
  { ingredientSlug: INGREDIENT_SLUGS.BOURRACHE, tagSlug: TAG_SLUGS.PEAU_ATOPIQUE },
  { ingredientSlug: INGREDIENT_SLUGS.BOURRACHE, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },

  // ── Pâquerette (Tenseur, raffermissant)
  { ingredientSlug: INGREDIENT_SLUGS.PAQUERETTE, tagSlug: TAG_SLUGS.ANTI_AGE },
  { ingredientSlug: INGREDIENT_SLUGS.PAQUERETTE, tagSlug: TAG_SLUGS.ECLAT },

  // ── Mauve (Adoucissante, apaisante)
  { ingredientSlug: INGREDIENT_SLUGS.MAUVE, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },
  { ingredientSlug: INGREDIENT_SLUGS.MAUVE, tagSlug: TAG_SLUGS.ANTI_ROUGEURS },
  { ingredientSlug: INGREDIENT_SLUGS.MAUVE, tagSlug: TAG_SLUGS.DESHYDRATATION },
  // ── Manganese Gluconate (Éclat et tonifiant)
  { ingredientSlug: INGREDIENT_SLUGS.MANGANESE_GLUCONATE, tagSlug: TAG_SLUGS.ECLAT },
  { ingredientSlug: INGREDIENT_SLUGS.MANGANESE_GLUCONATE, tagSlug: TAG_SLUGS.ANTI_OXYDANT },

  // ── Palmitoyl Tetrapeptide-10 (Éclat "cristallin" et lissage)
  { ingredientSlug: INGREDIENT_SLUGS.PALMITOYL_TETRAPEPTIDE_10, tagSlug: TAG_SLUGS.ECLAT },
  { ingredientSlug: INGREDIENT_SLUGS.PALMITOYL_TETRAPEPTIDE_10, tagSlug: TAG_SLUGS.ANTI_AGE },

  // ── Phenylalanine (Acide aminé - Hydratation et pigment)
  { ingredientSlug: INGREDIENT_SLUGS.PHENYLALANINE, tagSlug: TAG_SLUGS.HUMECTANT },
  { ingredientSlug: INGREDIENT_SLUGS.PHENYLALANINE, tagSlug: TAG_SLUGS.HYPERPIGMENTATION },

  // ── Propylene Glycol (Solvant et hydratant)
  { ingredientSlug: INGREDIENT_SLUGS.PROPYLENE_GLYCOL, tagSlug: TAG_SLUGS.HUMECTANT },
  { ingredientSlug: INGREDIENT_SLUGS.PROPYLENE_GLYCOL, tagSlug: TAG_SLUGS.DESHYDRATATION },

  // ── Salvia Miltiorrhiza (Sauge rouge - Apaisante et anti-glycation)
  { ingredientSlug: INGREDIENT_SLUGS.SALVIA_MILTIORRHIZA, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },
  { ingredientSlug: INGREDIENT_SLUGS.SALVIA_MILTIORRHIZA, tagSlug: TAG_SLUGS.ANTI_ROUGEURS },
  { ingredientSlug: INGREDIENT_SLUGS.SALVIA_MILTIORRHIZA, tagSlug: TAG_SLUGS.ANTI_AGE },

  // ── Serine (Acide aminé - Barrière cutanée)
  { ingredientSlug: INGREDIENT_SLUGS.SERINE, tagSlug: TAG_SLUGS.HUMECTANT },
  { ingredientSlug: INGREDIENT_SLUGS.SERINE, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },

  // ── Tretinoine (Rétinoïde puissant)
  { ingredientSlug: INGREDIENT_SLUGS.TRETINOINE, tagSlug: TAG_SLUGS.ANTI_AGE },
  { ingredientSlug: INGREDIENT_SLUGS.TRETINOINE, tagSlug: TAG_SLUGS.ANTI_ACNE },
  { ingredientSlug: INGREDIENT_SLUGS.TRETINOINE, tagSlug: TAG_SLUGS.KERATOLYTIQUE },
  { ingredientSlug: INGREDIENT_SLUGS.TRETINOINE, tagSlug: TAG_SLUGS.HYPERPIGMENTATION },

  // ── Tribehenin (Agent de texture et adoucissant)
  { ingredientSlug: INGREDIENT_SLUGS.TRIBEHENIN, tagSlug: TAG_SLUGS.EMOLLIENT },
  { ingredientSlug: INGREDIENT_SLUGS.TRIBEHENIN, tagSlug: TAG_SLUGS.PEAU_SECHE },

  // ── Tyrosine (Acide aminé)
  { ingredientSlug: INGREDIENT_SLUGS.TYROSINE, tagSlug: TAG_SLUGS.HUMECTANT },

  // ── Zea Mays Starch (Amidon de maïs - Matifiant)
  { ingredientSlug: INGREDIENT_SLUGS.ZEA_MAYS_STARCH, tagSlug: TAG_SLUGS.BRILLANCE },
  { ingredientSlug: INGREDIENT_SLUGS.ZEA_MAYS_STARCH, tagSlug: TAG_SLUGS.PEAU_GRASSE },

  // ── Zinc Gluconate (Purifiant et apaisant)
  { ingredientSlug: INGREDIENT_SLUGS.ZINC_GLUCONATE, tagSlug: TAG_SLUGS.SEBO_REGULATEUR },
  { ingredientSlug: INGREDIENT_SLUGS.ZINC_GLUCONATE, tagSlug: TAG_SLUGS.ANTI_ACNE },
  { ingredientSlug: INGREDIENT_SLUGS.ZINC_GLUCONATE, tagSlug: TAG_SLUGS.PEAU_GRASSE },
  // ── Dimethicone (Silicone - Protection et lissage)
  { ingredientSlug: INGREDIENT_SLUGS.DIMETHICONE, tagSlug: TAG_SLUGS.OCCLUSIF },
  { ingredientSlug: INGREDIENT_SLUGS.DIMETHICONE, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },

  // ── Eau de Rose (Apaisante et rafraîchissante)
  { ingredientSlug: INGREDIENT_SLUGS.EAU_DE_ROSE, tagSlug: TAG_SLUGS.ECLAT },
  { ingredientSlug: INGREDIENT_SLUGS.EAU_DE_ROSE, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },

  // ── Glutamine (Acide aminé - Réparation)
  { ingredientSlug: INGREDIENT_SLUGS.GLUTAMINE, tagSlug: TAG_SLUGS.REPARATEUR },
  { ingredientSlug: INGREDIENT_SLUGS.GLUTAMINE, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },

  // ── Glyceryl Dibehenate (Agent de texture et gras)
  { ingredientSlug: INGREDIENT_SLUGS.GLYCERYL_DIBEHENATE, tagSlug: TAG_SLUGS.EMOLLIENT },
  { ingredientSlug: INGREDIENT_SLUGS.GLYCERYL_DIBEHENATE, tagSlug: TAG_SLUGS.PEAU_SECHE },

  // ── HAMAMELIS (Astringent et tonifiant)
  { ingredientSlug: INGREDIENT_SLUGS.HAMAMELIS, tagSlug: TAG_SLUGS.PORES_DILATES },
  { ingredientSlug: INGREDIENT_SLUGS.HAMAMELIS, tagSlug: TAG_SLUGS.PEAU_MIXTE },
  { ingredientSlug: INGREDIENT_SLUGS.HAMAMELIS, tagSlug: TAG_SLUGS.ANTI_ROUGEURS },

  // ── Helianthus Annuus (Huile de Tournesol - Nourrissante)
  { ingredientSlug: INGREDIENT_SLUGS.HELIANTHUS_ANNUUS, tagSlug: TAG_SLUGS.EMOLLIENT },
  { ingredientSlug: INGREDIENT_SLUGS.HELIANTHUS_ANNUUS, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },

  // ── Helichryse Immortelle (Cicatrisante et circulatoire)
  { ingredientSlug: INGREDIENT_SLUGS.HELICHRYSE_IMMORTELLE, tagSlug: TAG_SLUGS.ANTI_ROUGEURS },
  { ingredientSlug: INGREDIENT_SLUGS.HELICHRYSE_IMMORTELLE, tagSlug: TAG_SLUGS.COUPEROSE },
  { ingredientSlug: INGREDIENT_SLUGS.HELICHRYSE_IMMORTELLE, tagSlug: TAG_SLUGS.ANTI_AGE },

  // ── Histidine (Acide aminé - Antioxydant)
  { ingredientSlug: INGREDIENT_SLUGS.HISTIDINE, tagSlug: TAG_SLUGS.HUMECTANT },
  { ingredientSlug: INGREDIENT_SLUGS.HISTIDINE, tagSlug: TAG_SLUGS.ANTI_OXYDANT },

  // ── Hydrogenated Polyisobutene (Substitut de squalane synthétique)
  { ingredientSlug: INGREDIENT_SLUGS.HYDROGENATED_POLYISOBUTENE, tagSlug: TAG_SLUGS.EMOLLIENT },
  { ingredientSlug: INGREDIENT_SLUGS.HYDROGENATED_POLYISOBUTENE, tagSlug: TAG_SLUGS.PEAU_SECHE },

  // ── Leucine (Acide aminé - Structure)
  { ingredientSlug: INGREDIENT_SLUGS.LEUCINE, tagSlug: TAG_SLUGS.REPARATEUR },
  { ingredientSlug: INGREDIENT_SLUGS.LEUCINE, tagSlug: TAG_SLUGS.ANTI_AGE },

  // ── Lysine HCL (Acide aminé - Hydratation)
  { ingredientSlug: INGREDIENT_SLUGS.LYSINE_HCL, tagSlug: TAG_SLUGS.HUMECTANT },
  { ingredientSlug: INGREDIENT_SLUGS.LYSINE_HCL, tagSlug: TAG_SLUGS.REPARATEUR },
  // ── Acetyl Glucosamine (Précurseur d'acide hyaluronique - Éclat)
  { ingredientSlug: INGREDIENT_SLUGS.ACETYL_GLUCOSAMINE, tagSlug: TAG_SLUGS.HYPERPIGMENTATION },
  { ingredientSlug: INGREDIENT_SLUGS.ACETYL_GLUCOSAMINE, tagSlug: TAG_SLUGS.ECLAT },
  { ingredientSlug: INGREDIENT_SLUGS.ACETYL_GLUCOSAMINE, tagSlug: TAG_SLUGS.ANTI_AGE },

  // ── Adapalene (Rétinoïde de 3ème génération)
  { ingredientSlug: INGREDIENT_SLUGS.ADAPALENE, tagSlug: TAG_SLUGS.ANTI_ACNE },
  { ingredientSlug: INGREDIENT_SLUGS.ADAPALENE, tagSlug: TAG_SLUGS.KERATOLYTIQUE },
  { ingredientSlug: INGREDIENT_SLUGS.ADAPALENE, tagSlug: TAG_SLUGS.POST_ACNE },

  // ── Arginine (Acide aminé - Cicatrisation)
  { ingredientSlug: INGREDIENT_SLUGS.ARGININE, tagSlug: TAG_SLUGS.REPARATEUR },
  { ingredientSlug: INGREDIENT_SLUGS.ARGININE, tagSlug: TAG_SLUGS.HUMECTANT },

  // ── Arnica (Apaisant et circulatoire)
  { ingredientSlug: INGREDIENT_SLUGS.ARNICA, tagSlug: TAG_SLUGS.ANTI_ROUGEURS },
  { ingredientSlug: INGREDIENT_SLUGS.ARNICA, tagSlug: TAG_SLUGS.CERNES_POCHES },

  // ── Bixa Orellana (Rocou - Antioxydant et matifiant)
  { ingredientSlug: INGREDIENT_SLUGS.BIXA_ORELLANA, tagSlug: TAG_SLUGS.ANTI_OXYDANT },
  { ingredientSlug: INGREDIENT_SLUGS.BIXA_ORELLANA, tagSlug: TAG_SLUGS.SEBO_REGULATEUR },
  { ingredientSlug: INGREDIENT_SLUGS.BIXA_ORELLANA, tagSlug: TAG_SLUGS.PEAU_GRASSE },

  // ── Bleuet (Apaisant et décongestionnant)
  { ingredientSlug: INGREDIENT_SLUGS.BLEUET, tagSlug: TAG_SLUGS.CERNES_POCHES },
  { ingredientSlug: INGREDIENT_SLUGS.BLEUET, tagSlug: TAG_SLUGS.CONTOUR_YEUX },
  { ingredientSlug: INGREDIENT_SLUGS.BLEUET, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },

  // ── Carnosine (Peptide - Anti-glycation)
  { ingredientSlug: INGREDIENT_SLUGS.CARNOSINE, tagSlug: TAG_SLUGS.ANTI_AGE },
  { ingredientSlug: INGREDIENT_SLUGS.CARNOSINE, tagSlug: TAG_SLUGS.ANTI_OXYDANT },

  // ── Dicaprylyl Ether (Émollient sec)
  { ingredientSlug: INGREDIENT_SLUGS.DICAPRYLYL_ETHER, tagSlug: TAG_SLUGS.EMOLLIENT },
  { ingredientSlug: INGREDIENT_SLUGS.DICAPRYLYL_ETHER, tagSlug: TAG_SLUGS.NON_COMEDOGENE },

  // ─── ACETYL_GLUCOSAMINE ───
  { ingredientSlug: INGREDIENT_SLUGS.ACETYL_GLUCOSAMINE, tagSlug: TAG_SLUGS.ANTI_AGE },
  { ingredientSlug: INGREDIENT_SLUGS.ACETYL_GLUCOSAMINE, tagSlug: TAG_SLUGS.HUMECTANT },
  { ingredientSlug: INGREDIENT_SLUGS.ACETYL_GLUCOSAMINE, tagSlug: TAG_SLUGS.ANTI_TACHES },

  // ─── ADAPALENE ───
  { ingredientSlug: INGREDIENT_SLUGS.ADAPALENE, tagSlug: TAG_SLUGS.ANTI_ACNE },
  { ingredientSlug: INGREDIENT_SLUGS.ADAPALENE, tagSlug: TAG_SLUGS.ANTI_AGE },
  { ingredientSlug: INGREDIENT_SLUGS.ADAPALENE, tagSlug: TAG_SLUGS.KERATOLYTIQUE },
  { ingredientSlug: INGREDIENT_SLUGS.ADAPALENE, tagSlug: TAG_SLUGS.POST_ACNE },

  // ─── ALLANTOIN ───
  { ingredientSlug: INGREDIENT_SLUGS.ALLANTOIN, tagSlug: TAG_SLUGS.REPARATEUR },
  { ingredientSlug: INGREDIENT_SLUGS.ALLANTOIN, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },
  { ingredientSlug: INGREDIENT_SLUGS.ALLANTOIN, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },

  // ─── ALOE_VERA ───
  { ingredientSlug: INGREDIENT_SLUGS.ALOE_VERA, tagSlug: TAG_SLUGS.HUMECTANT },
  { ingredientSlug: INGREDIENT_SLUGS.ALOE_VERA, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },
  { ingredientSlug: INGREDIENT_SLUGS.ALOE_VERA, tagSlug: TAG_SLUGS.ANTI_ROUGEURS },

  // ─── ALPHA_ARBUTIN ───
  { ingredientSlug: INGREDIENT_SLUGS.ALPHA_ARBUTIN, tagSlug: TAG_SLUGS.ANTI_TACHES },
  { ingredientSlug: INGREDIENT_SLUGS.ALPHA_ARBUTIN, tagSlug: TAG_SLUGS.HYPERPIGMENTATION },
  { ingredientSlug: INGREDIENT_SLUGS.ALPHA_ARBUTIN, tagSlug: TAG_SLUGS.ECLAT },

  // ─── AMMONIUM_GLYCYRRHIZATE ───
  { ingredientSlug: INGREDIENT_SLUGS.AMMONIUM_GLYCYRRHIZATE, tagSlug: TAG_SLUGS.ANTI_ROUGEURS },
  { ingredientSlug: INGREDIENT_SLUGS.AMMONIUM_GLYCYRRHIZATE, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },

  // ─── ARGININE ───
  { ingredientSlug: INGREDIENT_SLUGS.ARGININE, tagSlug: TAG_SLUGS.HUMECTANT },
  { ingredientSlug: INGREDIENT_SLUGS.ARGININE, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },
  { ingredientSlug: INGREDIENT_SLUGS.ARGININE, tagSlug: TAG_SLUGS.REPARATEUR },

  // ─── ARGIRELINE ───
  { ingredientSlug: INGREDIENT_SLUGS.ARGIRELINE, tagSlug: TAG_SLUGS.ANTI_AGE },

  // ─── ASCORBYL_GLUCOSIDE ───
  { ingredientSlug: INGREDIENT_SLUGS.ASCORBYL_GLUCOSIDE, tagSlug: TAG_SLUGS.ANTI_TACHES },
  { ingredientSlug: INGREDIENT_SLUGS.ASCORBYL_GLUCOSIDE, tagSlug: TAG_SLUGS.ECLAT },
  { ingredientSlug: INGREDIENT_SLUGS.ASCORBYL_GLUCOSIDE, tagSlug: TAG_SLUGS.ANTI_OXYDANT },

  // ─── ASCORBYL_PALMITATE ───
  { ingredientSlug: INGREDIENT_SLUGS.ASCORBYL_PALMITATE, tagSlug: TAG_SLUGS.ANTI_OXYDANT },
  { ingredientSlug: INGREDIENT_SLUGS.ASCORBYL_PALMITATE, tagSlug: TAG_SLUGS.ANTI_TACHES },
  { ingredientSlug: INGREDIENT_SLUGS.ASCORBYL_PALMITATE, tagSlug: TAG_SLUGS.ECLAT },

  // ─── ASIATICOSIDE ───
  { ingredientSlug: INGREDIENT_SLUGS.ASIATICOSIDE, tagSlug: TAG_SLUGS.REPARATEUR },
  { ingredientSlug: INGREDIENT_SLUGS.ASIATICOSIDE, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },
  { ingredientSlug: INGREDIENT_SLUGS.ASIATICOSIDE, tagSlug: TAG_SLUGS.ANTI_ROUGEURS },
  { ingredientSlug: INGREDIENT_SLUGS.ASIATICOSIDE, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },

  // ─── AZELAIC_ACID ───
  { ingredientSlug: INGREDIENT_SLUGS.AZELAIC_ACID, tagSlug: TAG_SLUGS.ANTI_ROUGEURS },
  { ingredientSlug: INGREDIENT_SLUGS.AZELAIC_ACID, tagSlug: TAG_SLUGS.ROSACEE },
  { ingredientSlug: INGREDIENT_SLUGS.AZELAIC_ACID, tagSlug: TAG_SLUGS.ANTI_ACNE },
  { ingredientSlug: INGREDIENT_SLUGS.AZELAIC_ACID, tagSlug: TAG_SLUGS.ANTI_TACHES },
  { ingredientSlug: INGREDIENT_SLUGS.AZELAIC_ACID, tagSlug: TAG_SLUGS.HYPERPIGMENTATION },
  { ingredientSlug: INGREDIENT_SLUGS.AZELAIC_ACID, tagSlug: TAG_SLUGS.SEBO_REGULATEUR },
  { ingredientSlug: INGREDIENT_SLUGS.AZELAIC_ACID, tagSlug: TAG_SLUGS.POST_ACNE },

  // ─── BAKUCHIOL ───
  { ingredientSlug: INGREDIENT_SLUGS.BAKUCHIOL, tagSlug: TAG_SLUGS.ANTI_AGE },
  { ingredientSlug: INGREDIENT_SLUGS.BAKUCHIOL, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },

  // ─── CENTELLA_ASIATICA / CENTELLA_ASIATICA_EXTRACT ───
  { ingredientSlug: INGREDIENT_SLUGS.CENTELLA_ASIATICA, tagSlug: TAG_SLUGS.REPARATEUR },
  { ingredientSlug: INGREDIENT_SLUGS.CENTELLA_ASIATICA, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },
  { ingredientSlug: INGREDIENT_SLUGS.CENTELLA_ASIATICA, tagSlug: TAG_SLUGS.ANTI_ROUGEURS },
  { ingredientSlug: INGREDIENT_SLUGS.CENTELLA_ASIATICA, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },
  // ─── CERAMIDES ───
  { ingredientSlug: INGREDIENT_SLUGS.CERAMIDE_AP, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },
  { ingredientSlug: INGREDIENT_SLUGS.CERAMIDE_AP, tagSlug: TAG_SLUGS.REPARATEUR },
  { ingredientSlug: INGREDIENT_SLUGS.CERAMIDE_AP, tagSlug: TAG_SLUGS.PEAU_SECHE },
  { ingredientSlug: INGREDIENT_SLUGS.CERAMIDE_AP, tagSlug: TAG_SLUGS.PEAU_ATOPIQUE },
  { ingredientSlug: INGREDIENT_SLUGS.CERAMIDE_EOP, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },
  { ingredientSlug: INGREDIENT_SLUGS.CERAMIDE_EOP, tagSlug: TAG_SLUGS.REPARATEUR },
  { ingredientSlug: INGREDIENT_SLUGS.CERAMIDE_EOP, tagSlug: TAG_SLUGS.PEAU_SECHE },
  { ingredientSlug: INGREDIENT_SLUGS.CERAMIDE_EOP, tagSlug: TAG_SLUGS.PEAU_ATOPIQUE },
  { ingredientSlug: INGREDIENT_SLUGS.CERAMIDE_NP, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },
  { ingredientSlug: INGREDIENT_SLUGS.CERAMIDE_NP, tagSlug: TAG_SLUGS.REPARATEUR },
  { ingredientSlug: INGREDIENT_SLUGS.CERAMIDE_NP, tagSlug: TAG_SLUGS.PEAU_SECHE },
  { ingredientSlug: INGREDIENT_SLUGS.CERAMIDE_NP, tagSlug: TAG_SLUGS.PEAU_ATOPIQUE },
  { ingredientSlug: INGREDIENT_SLUGS.CERAMIDE_NS, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },
  { ingredientSlug: INGREDIENT_SLUGS.CERAMIDE_NS, tagSlug: TAG_SLUGS.REPARATEUR },
  { ingredientSlug: INGREDIENT_SLUGS.CERAMIDE_NS, tagSlug: TAG_SLUGS.PEAU_SECHE },
  { ingredientSlug: INGREDIENT_SLUGS.CERAMIDE_NS, tagSlug: TAG_SLUGS.PEAU_ATOPIQUE },
  { ingredientSlug: INGREDIENT_SLUGS.CERAMIDES, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },
  { ingredientSlug: INGREDIENT_SLUGS.CERAMIDES, tagSlug: TAG_SLUGS.REPARATEUR },
  { ingredientSlug: INGREDIENT_SLUGS.CERAMIDES, tagSlug: TAG_SLUGS.PEAU_SECHE },
  { ingredientSlug: INGREDIENT_SLUGS.CERAMIDES, tagSlug: TAG_SLUGS.PEAU_ATOPIQUE },

  // ─── CHOLESTEROL ───
  { ingredientSlug: INGREDIENT_SLUGS.CHOLESTEROL, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },
  { ingredientSlug: INGREDIENT_SLUGS.CHOLESTEROL, tagSlug: TAG_SLUGS.EMOLLIENT },
  { ingredientSlug: INGREDIENT_SLUGS.CHOLESTEROL, tagSlug: TAG_SLUGS.PEAU_SECHE },

  // ─── COPPER_PEPTIDES ───
  { ingredientSlug: INGREDIENT_SLUGS.COPPER_PEPTIDES, tagSlug: TAG_SLUGS.ANTI_AGE },
  { ingredientSlug: INGREDIENT_SLUGS.COPPER_PEPTIDES, tagSlug: TAG_SLUGS.REPARATEUR },

  // ─── DICAPRYLYL_ETHER ───
  { ingredientSlug: INGREDIENT_SLUGS.DICAPRYLYL_ETHER, tagSlug: TAG_SLUGS.EMOLLIENT },

  // ─── DIMETHICONE ───
  { ingredientSlug: INGREDIENT_SLUGS.DIMETHICONE, tagSlug: TAG_SLUGS.OCCLUSIF },
  { ingredientSlug: INGREDIENT_SLUGS.DIMETHICONE, tagSlug: TAG_SLUGS.EMOLLIENT },
  { ingredientSlug: INGREDIENT_SLUGS.DIMETHICONE, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },

  // ─── GLYCERIN ───
  { ingredientSlug: INGREDIENT_SLUGS.GLYCERIN, tagSlug: TAG_SLUGS.HUMECTANT },
  { ingredientSlug: INGREDIENT_SLUGS.GLYCERIN, tagSlug: TAG_SLUGS.DESHYDRATATION },
  { ingredientSlug: INGREDIENT_SLUGS.GLYCERIN, tagSlug: TAG_SLUGS.PEAU_SECHE },

  // ─── GLYCOLIC_ACID ───
  { ingredientSlug: INGREDIENT_SLUGS.GLYCOLIC_ACID, tagSlug: TAG_SLUGS.EXFOLIANT },
  { ingredientSlug: INGREDIENT_SLUGS.GLYCOLIC_ACID, tagSlug: TAG_SLUGS.KERATOLYTIQUE },
  { ingredientSlug: INGREDIENT_SLUGS.GLYCOLIC_ACID, tagSlug: TAG_SLUGS.ECLAT },
  { ingredientSlug: INGREDIENT_SLUGS.GLYCOLIC_ACID, tagSlug: TAG_SLUGS.ANTI_AGE },
  { ingredientSlug: INGREDIENT_SLUGS.GLYCOLIC_ACID, tagSlug: TAG_SLUGS.ANTI_TACHES },
  { ingredientSlug: INGREDIENT_SLUGS.GLYCOLIC_ACID, tagSlug: TAG_SLUGS.PORES_DILATES },

  // ─── GLYCYRRHETINIC_ACID ───
  { ingredientSlug: INGREDIENT_SLUGS.GLYCYRRHETINIC_ACID, tagSlug: TAG_SLUGS.ANTI_ROUGEURS },
  { ingredientSlug: INGREDIENT_SLUGS.GLYCYRRHETINIC_ACID, tagSlug: TAG_SLUGS.ROSACEE },
  { ingredientSlug: INGREDIENT_SLUGS.GLYCYRRHETINIC_ACID, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },
  { ingredientSlug: INGREDIENT_SLUGS.GLYCYRRHETINIC_ACID, tagSlug: TAG_SLUGS.ANTI_TACHES },

  // ─── GLYCYRRHIZA_INFLATA ───
  { ingredientSlug: INGREDIENT_SLUGS.GLYCYRRHIZA_INFLATA, tagSlug: TAG_SLUGS.ANTI_ROUGEURS },
  { ingredientSlug: INGREDIENT_SLUGS.GLYCYRRHIZA_INFLATA, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },
  { ingredientSlug: INGREDIENT_SLUGS.GLYCYRRHIZA_INFLATA, tagSlug: TAG_SLUGS.ANTI_ACNE },

  // ─── HEARTLEAF ───
  { ingredientSlug: INGREDIENT_SLUGS.HEARTLEAF, tagSlug: TAG_SLUGS.ANTI_ROUGEURS },
  { ingredientSlug: INGREDIENT_SLUGS.HEARTLEAF, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },
  { ingredientSlug: INGREDIENT_SLUGS.HEARTLEAF, tagSlug: TAG_SLUGS.ANTI_ACNE },

  // ─── HYALURONIC_ACID ───
  { ingredientSlug: INGREDIENT_SLUGS.HYALURONIC_ACID, tagSlug: TAG_SLUGS.HUMECTANT },
  { ingredientSlug: INGREDIENT_SLUGS.HYALURONIC_ACID, tagSlug: TAG_SLUGS.DESHYDRATATION },
  { ingredientSlug: INGREDIENT_SLUGS.HYALURONIC_ACID, tagSlug: TAG_SLUGS.ANTI_AGE },

  // ─── KOJIC_ACID ───
  { ingredientSlug: INGREDIENT_SLUGS.KOJIC_ACID, tagSlug: TAG_SLUGS.ANTI_TACHES },
  { ingredientSlug: INGREDIENT_SLUGS.KOJIC_ACID, tagSlug: TAG_SLUGS.HYPERPIGMENTATION },
  { ingredientSlug: INGREDIENT_SLUGS.KOJIC_ACID, tagSlug: TAG_SLUGS.ECLAT },

  // ─── LACTIC_ACID ───
  { ingredientSlug: INGREDIENT_SLUGS.LACTIC_ACID, tagSlug: TAG_SLUGS.EXFOLIANT },
  { ingredientSlug: INGREDIENT_SLUGS.LACTIC_ACID, tagSlug: TAG_SLUGS.KERATOLYTIQUE },
  { ingredientSlug: INGREDIENT_SLUGS.LACTIC_ACID, tagSlug: TAG_SLUGS.HUMECTANT },
  { ingredientSlug: INGREDIENT_SLUGS.LACTIC_ACID, tagSlug: TAG_SLUGS.ECLAT },
  { ingredientSlug: INGREDIENT_SLUGS.LACTIC_ACID, tagSlug: TAG_SLUGS.PEAU_SECHE },

  // ─── MANDELIC_ACID ───
  { ingredientSlug: INGREDIENT_SLUGS.MANDELIC_ACID, tagSlug: TAG_SLUGS.EXFOLIANT },
  { ingredientSlug: INGREDIENT_SLUGS.MANDELIC_ACID, tagSlug: TAG_SLUGS.ANTI_ACNE },
  { ingredientSlug: INGREDIENT_SLUGS.MANDELIC_ACID, tagSlug: TAG_SLUGS.ANTI_TACHES },
  { ingredientSlug: INGREDIENT_SLUGS.MANDELIC_ACID, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },

  // ─── MATRIXYL_3000 ───
  { ingredientSlug: INGREDIENT_SLUGS.MATRIXYL_3000, tagSlug: TAG_SLUGS.ANTI_AGE },

  // ─── NIACINAMIDE ───
  { ingredientSlug: INGREDIENT_SLUGS.NIACINAMIDE, tagSlug: TAG_SLUGS.ANTI_TACHES },
  { ingredientSlug: INGREDIENT_SLUGS.NIACINAMIDE, tagSlug: TAG_SLUGS.ANTI_ROUGEURS },
  { ingredientSlug: INGREDIENT_SLUGS.NIACINAMIDE, tagSlug: TAG_SLUGS.SEBO_REGULATEUR },
  { ingredientSlug: INGREDIENT_SLUGS.NIACINAMIDE, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },
  { ingredientSlug: INGREDIENT_SLUGS.NIACINAMIDE, tagSlug: TAG_SLUGS.PORES_DILATES },
  { ingredientSlug: INGREDIENT_SLUGS.NIACINAMIDE, tagSlug: TAG_SLUGS.ECLAT },
  { ingredientSlug: INGREDIENT_SLUGS.NIACINAMIDE, tagSlug: TAG_SLUGS.HYPERPIGMENTATION },
  { ingredientSlug: INGREDIENT_SLUGS.NIACINAMIDE, tagSlug: TAG_SLUGS.POST_ACNE },

  // ─── PANTHENOL ───
  { ingredientSlug: INGREDIENT_SLUGS.PANTHENOL, tagSlug: TAG_SLUGS.REPARATEUR },
  { ingredientSlug: INGREDIENT_SLUGS.PANTHENOL, tagSlug: TAG_SLUGS.HUMECTANT },
  { ingredientSlug: INGREDIENT_SLUGS.PANTHENOL, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },
  { ingredientSlug: INGREDIENT_SLUGS.PANTHENOL, tagSlug: TAG_SLUGS.ANTI_ROUGEURS },

  // ─── PEPTIDES (génériques) ───
  { ingredientSlug: INGREDIENT_SLUGS.PEPTIDES, tagSlug: TAG_SLUGS.ANTI_AGE },
  { ingredientSlug: INGREDIENT_SLUGS.PALMITOYL_PENTAPEPTIDE_4, tagSlug: TAG_SLUGS.ANTI_AGE },
  { ingredientSlug: INGREDIENT_SLUGS.PALMITOYL_TRIPEPTIDE_1, tagSlug: TAG_SLUGS.ANTI_AGE },
  { ingredientSlug: INGREDIENT_SLUGS.PALMITOYL_TETRAPEPTIDE_7, tagSlug: TAG_SLUGS.ANTI_AGE },
  { ingredientSlug: INGREDIENT_SLUGS.PALMITOYL_TETRAPEPTIDE_10, tagSlug: TAG_SLUGS.ANTI_AGE },

  // ─── PHA ───
  { ingredientSlug: INGREDIENT_SLUGS.PHA, tagSlug: TAG_SLUGS.EXFOLIANT },
  { ingredientSlug: INGREDIENT_SLUGS.PHA, tagSlug: TAG_SLUGS.KERATOLYTIQUE },
  { ingredientSlug: INGREDIENT_SLUGS.PHA, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },
  { ingredientSlug: INGREDIENT_SLUGS.PHA, tagSlug: TAG_SLUGS.ECLAT },

  // ─── PHYTOSPHINGOSINE ───
  { ingredientSlug: INGREDIENT_SLUGS.PHYTOSPHINGOSINE, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },
  { ingredientSlug: INGREDIENT_SLUGS.PHYTOSPHINGOSINE, tagSlug: TAG_SLUGS.ANTI_ACNE },
  { ingredientSlug: INGREDIENT_SLUGS.PHYTOSPHINGOSINE, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },

  // ─── RETINAL ───
  { ingredientSlug: INGREDIENT_SLUGS.RETINAL, tagSlug: TAG_SLUGS.ANTI_AGE },
  { ingredientSlug: INGREDIENT_SLUGS.RETINAL, tagSlug: TAG_SLUGS.ANTI_ACNE },
  { ingredientSlug: INGREDIENT_SLUGS.RETINAL, tagSlug: TAG_SLUGS.ECLAT },
  { ingredientSlug: INGREDIENT_SLUGS.RETINAL, tagSlug: TAG_SLUGS.KERATOLYTIQUE },
  { ingredientSlug: INGREDIENT_SLUGS.RETINAL, tagSlug: TAG_SLUGS.ANTI_TACHES },

  // ─── RETINOL ───
  { ingredientSlug: INGREDIENT_SLUGS.RETINOL, tagSlug: TAG_SLUGS.ANTI_AGE },
  { ingredientSlug: INGREDIENT_SLUGS.RETINOL, tagSlug: TAG_SLUGS.ANTI_ACNE },
  { ingredientSlug: INGREDIENT_SLUGS.RETINOL, tagSlug: TAG_SLUGS.KERATOLYTIQUE },
  { ingredientSlug: INGREDIENT_SLUGS.RETINOL, tagSlug: TAG_SLUGS.ANTI_TACHES },

  // ─── RHAMNOSE ───
  { ingredientSlug: INGREDIENT_SLUGS.RHAMNOSE, tagSlug: TAG_SLUGS.ANTI_AGE },
  { ingredientSlug: INGREDIENT_SLUGS.RHAMNOSE, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },

  // ─── SALICYLIC_ACID ───
  { ingredientSlug: INGREDIENT_SLUGS.SALICYLIC_ACID, tagSlug: TAG_SLUGS.ANTI_ACNE },
  { ingredientSlug: INGREDIENT_SLUGS.SALICYLIC_ACID, tagSlug: TAG_SLUGS.EXFOLIANT },
  { ingredientSlug: INGREDIENT_SLUGS.SALICYLIC_ACID, tagSlug: TAG_SLUGS.KERATOLYTIQUE },
  { ingredientSlug: INGREDIENT_SLUGS.SALICYLIC_ACID, tagSlug: TAG_SLUGS.SEBO_REGULATEUR },
  { ingredientSlug: INGREDIENT_SLUGS.SALICYLIC_ACID, tagSlug: TAG_SLUGS.PORES_DILATES },
  { ingredientSlug: INGREDIENT_SLUGS.SALICYLIC_ACID, tagSlug: TAG_SLUGS.BRILLANCE },

  // ─── SHEA_BUTTER ───
  { ingredientSlug: INGREDIENT_SLUGS.SHEA_BUTTER, tagSlug: TAG_SLUGS.EMOLLIENT },
  { ingredientSlug: INGREDIENT_SLUGS.SHEA_BUTTER, tagSlug: TAG_SLUGS.OCCLUSIF },
  { ingredientSlug: INGREDIENT_SLUGS.SHEA_BUTTER, tagSlug: TAG_SLUGS.PEAU_SECHE },
  { ingredientSlug: INGREDIENT_SLUGS.SHEA_BUTTER, tagSlug: TAG_SLUGS.PEAU_ATOPIQUE },
  { ingredientSlug: INGREDIENT_SLUGS.SHEA_BUTTER, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },

  // ─── SODIUM_HYALURONATE ───
  { ingredientSlug: INGREDIENT_SLUGS.SODIUM_HYALURONATE, tagSlug: TAG_SLUGS.HUMECTANT },
  { ingredientSlug: INGREDIENT_SLUGS.SODIUM_HYALURONATE, tagSlug: TAG_SLUGS.DESHYDRATATION },
  { ingredientSlug: INGREDIENT_SLUGS.SODIUM_HYALURONATE, tagSlug: TAG_SLUGS.ANTI_AGE },

  // ─── SQUALANE ───
  { ingredientSlug: INGREDIENT_SLUGS.SQUALANE, tagSlug: TAG_SLUGS.EMOLLIENT },
  { ingredientSlug: INGREDIENT_SLUGS.SQUALANE, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },
  { ingredientSlug: INGREDIENT_SLUGS.SQUALANE, tagSlug: TAG_SLUGS.PEAU_SECHE },
  { ingredientSlug: INGREDIENT_SLUGS.SQUALANE, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },

  // ─── THD_ASCORBATE ───
  { ingredientSlug: INGREDIENT_SLUGS.THD_ASCORBATE, tagSlug: TAG_SLUGS.ANTI_OXYDANT },
  { ingredientSlug: INGREDIENT_SLUGS.THD_ASCORBATE, tagSlug: TAG_SLUGS.ANTI_TACHES },
  { ingredientSlug: INGREDIENT_SLUGS.THD_ASCORBATE, tagSlug: TAG_SLUGS.ECLAT },
  { ingredientSlug: INGREDIENT_SLUGS.THD_ASCORBATE, tagSlug: TAG_SLUGS.HYPERPIGMENTATION },

  // ─── THREE_O_ETHYL_ASCORBIC_ACID ───
  { ingredientSlug: INGREDIENT_SLUGS.THREE_O_ETHYL_ASCORBIC_ACID, tagSlug: TAG_SLUGS.ANTI_OXYDANT },
  { ingredientSlug: INGREDIENT_SLUGS.THREE_O_ETHYL_ASCORBIC_ACID, tagSlug: TAG_SLUGS.ANTI_TACHES },
  { ingredientSlug: INGREDIENT_SLUGS.THREE_O_ETHYL_ASCORBIC_ACID, tagSlug: TAG_SLUGS.ECLAT },

  // ─── TOCOPHEROL ───
  { ingredientSlug: INGREDIENT_SLUGS.TOCOPHEROL, tagSlug: TAG_SLUGS.ANTI_OXYDANT },
  { ingredientSlug: INGREDIENT_SLUGS.TOCOPHEROL, tagSlug: TAG_SLUGS.EMOLLIENT },
  { ingredientSlug: INGREDIENT_SLUGS.TOCOPHEROL, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },

  // ─── TRANEXAMIC_ACID ───
  { ingredientSlug: INGREDIENT_SLUGS.TRANEXAMIC_ACID, tagSlug: TAG_SLUGS.ANTI_TACHES },
  { ingredientSlug: INGREDIENT_SLUGS.TRANEXAMIC_ACID, tagSlug: TAG_SLUGS.HYPERPIGMENTATION },
  { ingredientSlug: INGREDIENT_SLUGS.TRANEXAMIC_ACID, tagSlug: TAG_SLUGS.ANTI_ROUGEURS },
  { ingredientSlug: INGREDIENT_SLUGS.TRANEXAMIC_ACID, tagSlug: TAG_SLUGS.ECLAT },

  // ─── TRETINOINE ───
  { ingredientSlug: INGREDIENT_SLUGS.TRETINOINE, tagSlug: TAG_SLUGS.ANTI_AGE },
  { ingredientSlug: INGREDIENT_SLUGS.TRETINOINE, tagSlug: TAG_SLUGS.ANTI_ACNE },
  { ingredientSlug: INGREDIENT_SLUGS.TRETINOINE, tagSlug: TAG_SLUGS.KERATOLYTIQUE },
  { ingredientSlug: INGREDIENT_SLUGS.TRETINOINE, tagSlug: TAG_SLUGS.ANTI_TACHES },
  { ingredientSlug: INGREDIENT_SLUGS.TRETINOINE, tagSlug: TAG_SLUGS.ECLAT },

  // ─── UREA ───
  { ingredientSlug: INGREDIENT_SLUGS.UREA, tagSlug: TAG_SLUGS.HUMECTANT },
  { ingredientSlug: INGREDIENT_SLUGS.UREA, tagSlug: TAG_SLUGS.KERATOLYTIQUE },
  { ingredientSlug: INGREDIENT_SLUGS.UREA, tagSlug: TAG_SLUGS.PEAU_SECHE },
  { ingredientSlug: INGREDIENT_SLUGS.UREA, tagSlug: TAG_SLUGS.PEAU_ATOPIQUE },

  // ─── VITAMIN_C ───
  { ingredientSlug: INGREDIENT_SLUGS.VITAMIN_C, tagSlug: TAG_SLUGS.ANTI_OXYDANT },
  { ingredientSlug: INGREDIENT_SLUGS.VITAMIN_C, tagSlug: TAG_SLUGS.ANTI_TACHES },
  { ingredientSlug: INGREDIENT_SLUGS.VITAMIN_C, tagSlug: TAG_SLUGS.ECLAT },
  { ingredientSlug: INGREDIENT_SLUGS.VITAMIN_C, tagSlug: TAG_SLUGS.HYPERPIGMENTATION },
  { ingredientSlug: INGREDIENT_SLUGS.VITAMIN_C, tagSlug: TAG_SLUGS.ANTI_AGE },

  // ─── ZINC_GLUCONATE ───
  { ingredientSlug: INGREDIENT_SLUGS.ZINC_GLUCONATE, tagSlug: TAG_SLUGS.ANTI_ACNE },
  { ingredientSlug: INGREDIENT_SLUGS.ZINC_GLUCONATE, tagSlug: TAG_SLUGS.SEBO_REGULATEUR },
  { ingredientSlug: INGREDIENT_SLUGS.ZINC_GLUCONATE, tagSlug: TAG_SLUGS.BRILLANCE },
  { ingredientSlug: INGREDIENT_SLUGS.ZINC_GLUCONATE, tagSlug: TAG_SLUGS.ANTI_ROUGEURS },

  // ─── ASCOPHYLLUM_NODOSUM_EXTRACT ───
  {
    ingredientSlug: INGREDIENT_SLUGS.ASCOPHYLLUM_NODOSUM_EXTRACT,
    tagSlug: TAG_SLUGS.ANTI_ROUGEURS,
  },
  { ingredientSlug: INGREDIENT_SLUGS.ASCOPHYLLUM_NODOSUM_EXTRACT, tagSlug: TAG_SLUGS.ROSACEE },
  {
    ingredientSlug: INGREDIENT_SLUGS.ASCOPHYLLUM_NODOSUM_EXTRACT,
    tagSlug: TAG_SLUGS.PEAU_SENSIBLE,
  },
  { ingredientSlug: INGREDIENT_SLUGS.ASCOPHYLLUM_NODOSUM_EXTRACT, tagSlug: TAG_SLUGS.ANTI_OXYDANT },

  // ─── BIS_ETHYLHEXYLOXYPHENOL_METHOXYPHENYL_TRIAZINE ───
  {
    ingredientSlug: INGREDIENT_SLUGS.BIS_ETHYLHEXYLOXYPHENOL_METHOXYPHENYL_TRIAZINE,
    tagSlug: TAG_SLUGS.PROTECTION_SOLAIRE,
  },

  // ─── DIACETYL_BOLDINE ───
  { ingredientSlug: INGREDIENT_SLUGS.DIACETYL_BOLDINE, tagSlug: TAG_SLUGS.ANTI_TACHES },
  { ingredientSlug: INGREDIENT_SLUGS.DIACETYL_BOLDINE, tagSlug: TAG_SLUGS.HYPERPIGMENTATION },
  { ingredientSlug: INGREDIENT_SLUGS.DIACETYL_BOLDINE, tagSlug: TAG_SLUGS.ECLAT },

  // ─── HUILES ───
  { ingredientSlug: INGREDIENT_SLUGS.HUILE_D_ARGAN, tagSlug: TAG_SLUGS.EMOLLIENT },
  { ingredientSlug: INGREDIENT_SLUGS.HUILE_D_ARGAN, tagSlug: TAG_SLUGS.ANTI_OXYDANT },
  { ingredientSlug: INGREDIENT_SLUGS.HUILE_D_ARGAN, tagSlug: TAG_SLUGS.PEAU_SECHE },
  { ingredientSlug: INGREDIENT_SLUGS.HUILE_DE_JOJOBA, tagSlug: TAG_SLUGS.EMOLLIENT },
  { ingredientSlug: INGREDIENT_SLUGS.HUILE_DE_JOJOBA, tagSlug: TAG_SLUGS.SEBO_REGULATEUR },
  { ingredientSlug: INGREDIENT_SLUGS.HUILE_DE_COCO, tagSlug: TAG_SLUGS.EMOLLIENT },
  { ingredientSlug: INGREDIENT_SLUGS.HUILE_DE_COCO, tagSlug: TAG_SLUGS.OCCLUSIF },
  { ingredientSlug: INGREDIENT_SLUGS.HUILE_DE_PEPINS_DE_RAISIN, tagSlug: TAG_SLUGS.EMOLLIENT },
  { ingredientSlug: INGREDIENT_SLUGS.HUILE_DE_PEPINS_DE_RAISIN, tagSlug: TAG_SLUGS.ANTI_OXYDANT },

  // ─── MAGNESIUM_ASCORBYL_PHOSPHATE ───
  {
    ingredientSlug: INGREDIENT_SLUGS.MAGNESIUM_ASCORBYL_PHOSPHATE,
    tagSlug: TAG_SLUGS.ANTI_OXYDANT,
  },
  { ingredientSlug: INGREDIENT_SLUGS.MAGNESIUM_ASCORBYL_PHOSPHATE, tagSlug: TAG_SLUGS.ANTI_TACHES },
  { ingredientSlug: INGREDIENT_SLUGS.MAGNESIUM_ASCORBYL_PHOSPHATE, tagSlug: TAG_SLUGS.ECLAT },

  // ─── SODIUM_ASCORBYL_PHOSPHATE ───
  { ingredientSlug: INGREDIENT_SLUGS.SODIUM_ASCORBYL_PHOSPHATE, tagSlug: TAG_SLUGS.ANTI_OXYDANT },
  { ingredientSlug: INGREDIENT_SLUGS.SODIUM_ASCORBYL_PHOSPHATE, tagSlug: TAG_SLUGS.ANTI_TACHES },
  { ingredientSlug: INGREDIENT_SLUGS.SODIUM_ASCORBYL_PHOSPHATE, tagSlug: TAG_SLUGS.ANTI_ACNE },
  { ingredientSlug: INGREDIENT_SLUGS.SODIUM_ASCORBYL_PHOSPHATE, tagSlug: TAG_SLUGS.ECLAT },

  // ─── PROBIOTICS / POSTBIOTICS ───
  { ingredientSlug: INGREDIENT_SLUGS.PROBIOTICS, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },
  { ingredientSlug: INGREDIENT_SLUGS.PROBIOTICS, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },
  { ingredientSlug: INGREDIENT_SLUGS.POSTBIOTICS, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },
  { ingredientSlug: INGREDIENT_SLUGS.POSTBIOTICS, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },

  // ─── PENTYLENE_GLYCOL ───
  { ingredientSlug: INGREDIENT_SLUGS.PENTYLENE_GLYCOL, tagSlug: TAG_SLUGS.HUMECTANT },
  { ingredientSlug: INGREDIENT_SLUGS.PENTYLENE_GLYCOL, tagSlug: TAG_SLUGS.ANTISEPTIQUE },

  // ─── POLYGLUTAMIC_ACID ───
  { ingredientSlug: INGREDIENT_SLUGS.POLYGLUTAMIC_ACID, tagSlug: TAG_SLUGS.HUMECTANT },
  { ingredientSlug: INGREDIENT_SLUGS.POLYGLUTAMIC_ACID, tagSlug: TAG_SLUGS.DESHYDRATATION },
  { ingredientSlug: INGREDIENT_SLUGS.POLYGLUTAMIC_ACID, tagSlug: TAG_SLUGS.ANTI_AGE },

  // ─── SULFUR ───
  { ingredientSlug: INGREDIENT_SLUGS.SULFUR, tagSlug: TAG_SLUGS.ANTI_ACNE },
  { ingredientSlug: INGREDIENT_SLUGS.SULFUR, tagSlug: TAG_SLUGS.SEBO_REGULATEUR },
  { ingredientSlug: INGREDIENT_SLUGS.SULFUR, tagSlug: TAG_SLUGS.ANTISEPTIQUE },

  // ─── SNOW_MUSHROOM ───
  { ingredientSlug: INGREDIENT_SLUGS.SNOW_MUSHROOM, tagSlug: TAG_SLUGS.HUMECTANT },
  { ingredientSlug: INGREDIENT_SLUGS.SNOW_MUSHROOM, tagSlug: TAG_SLUGS.ANTI_AGE },
  { ingredientSlug: INGREDIENT_SLUGS.SNOW_MUSHROOM, tagSlug: TAG_SLUGS.DESHYDRATATION },

  // ─── BEEF_TALLOW ───
  { ingredientSlug: INGREDIENT_SLUGS.BEEF_TALLOW, tagSlug: TAG_SLUGS.EMOLLIENT },
  { ingredientSlug: INGREDIENT_SLUGS.BEEF_TALLOW, tagSlug: TAG_SLUGS.OCCLUSIF },
  { ingredientSlug: INGREDIENT_SLUGS.BEEF_TALLOW, tagSlug: TAG_SLUGS.PEAU_SECHE },
]
