export const DERMACEUTIC_PRODUCTS_SLUG = {
  MASK_15: 'dermaceutic-mask-15',
  OXYBIOME: 'dermaceutic-oxybiome',
  ADVANCED_CLEANSER: 'dermaceutic-advanced-cleanser',
  FOAMER_5: 'dermaceutic-foamer-5',
  FOAMER_15: 'dermaceutic-foamer-15',
  ACTIVABIOME: 'dermaceutic-activabiome',
  LIGHT_CEUTIC: 'dermaceutic-light-ceutic',
  TURN_OVER_10: 'dermaceutic-turn-over-10',
  TURN_OVER_15: 'dermaceutic-turn-over-15',
  HYAL_CEUTIC: 'dermaceutic-hyal-ceutic',
  REGEN_CEUTIC: 'dermaceutic-regen-ceutic',
  HYAL_CEUTIC_REDENS_PLUS: 'dermaceutic-hyal-ceutic-redens-plus',
  K_CEUTIC: 'dermaceutic-k-ceutic',
  PANTHENOL_CEUTIC: 'dermaceutic-panthenol-ceutic',
  C25_CREAM: 'dermaceutic-c25-cream',
  ACTIV_RETINOL_0_5: 'dermaceutic-activ-retinol-0-5',
  ACTIV_RETINOL_1_0: 'dermaceutic-activ-retinol-1-0',
  DERMA_LIFT_5_0: 'dermaceutic-derma-lift-5-0',
  REVEAL_4X: 'dermaceutic-reveal-4x',
  RADIANCE: 'dermaceutic-radiance',
  YELLOW_CREAM: 'dermaceutic-yellow-cream',
} as const

export const DERMACEUTIC_PRODUCT_DATA = [
  {
    name: 'Mask 15',
    brand: 'Dermaceutic',
    kind: 'skincare',
    unit: 'jar',
    slug: DERMACEUTIC_PRODUCTS_SLUG.MASK_15,
    totalAmount: 30,
    amountUnit: 'ml',
    priceCents: 4590,
    description:
      'Masque visage purifiant qui réduit l’apparence des imperfections et les cellules mortes.',
    notes: 'Action kératolytique. Laisser agir 2 à 4 minutes. Déconseillé pendant la grossesse.',
    inci: 'Water (Aqua) • Glycolic Acid • Bentonite • Kaolin • Cetyl Palmitate • Cetearyl Alcohol • Ethylhexyl Palmitate • Glycerin • Titanium Dioxide (CI77891) • Salicylic Acid • Steareth 21 • Glyceryl Stearate • PEG-100 Stearate • Cocamidopropyl Betaine • Disodium Cocoamphodiacetate • Xanthan Gum • Sodium Chloride • Tetrasodium EDTA • Octadecyl Di-T-Butyl-4 Hydroxyhydrocinnamate',
    url: 'https://www.dermaceutic.com/fr/mask-15.html',
  },
  {
    name: 'Oxybiome',
    brand: 'Dermaceutic',
    kind: 'skincare',
    unit: 'bottle',
    slug: DERMACEUTIC_PRODUCTS_SLUG.OXYBIOME,
    totalAmount: 400,
    amountUnit: 'ml',
    priceCents: 2990,
    description: 'Eau micellaire nettoyante qui purifie la peau et soutient le microbiote.',
    notes: 'Effet anti-pollution. Sans parfum.',
    inci: 'Water (Aqua) • Glycerin • Poloxamer 184 • Pentylene Glycol • Niacinamide • Zinc Gluconate • Chlorella Vulgaris Extract • Laminaria Digitata Extract • Maris Aqua (Sea Water) • Saccharide Isomerate • Tetrasodium Glutamate Diacetate • PPG-26-Buteth-26 • Phenethyl Alcohol • PEG-40 Hydrogenated Castor Oil • Chlorphenesin • O-Cymen-5-Ol • Citric Acid • Sodium Benzoate',
    url: 'https://www.dermaceutic.com/fr/oxybiome.html',
  },
  {
    name: 'Advanced Cleanser',
    brand: 'Dermaceutic',
    kind: 'skincare',
    unit: 'pump',
    slug: DERMACEUTIC_PRODUCTS_SLUG.ADVANCED_CLEANSER,
    totalAmount: 150,
    amountUnit: 'ml',
    priceCents: 2590,
    description: 'Mousse nettoyante douce qui élimine les impuretés et l’excès de sébum.',
    notes: 'Texture légère. Vegan.',
    inci: 'Water (Aqua) • Cocamidopropyl Betaine • Glycerin • Sodium Cocoyl Glutamate • Xylitylglucoside • Pentylene Glycol • Xylitol • Anhydroxylitol • Urea • Zinc PCA • Tocopherol • Coco-Glucoside • Glyceryl Oleate • Capryloyl Glycine • Fragrance (Parfum) • Tetrasodium Glutamate Diacetate • Propylene Glycol • Hydrogenated Palm Glycerides Citrate • Ethylhexylglycerin • Citric Acid • O-Cymen-5-Ol • Sodium Benzoate',
    url: 'https://www.dermaceutic.com/fr/advanced-cleanser.html',
  },
  {
    name: 'Foamer 5',
    brand: 'Dermaceutic',
    kind: 'skincare',
    unit: 'pump',
    slug: DERMACEUTIC_PRODUCTS_SLUG.FOAMER_5,
    totalAmount: 100,
    amountUnit: 'ml',
    priceCents: 3690,
    description: 'Mousse exfoliante douce pour teints ternes et textures irrégulières.',
    notes: '5% Acide glycolique. Sans silicone & sans parfum.',
    inci: 'Water (Aqua) • Glycolic Acid • Glycerin • Cocamidopropyl Betaine • Sodium Hydroxide • Polysorbate 80 • Propylene Glycol • Sodium Laureth Sulfate • Methylpropanediol • Glycyrrhetinic Acid • Dipotassium Glycyrrhizate • Potassium Sorbate',
    url: 'https://www.dermaceutic.com/fr/foamer-5.html',
  },
  {
    name: 'Foamer 15',
    brand: 'Dermaceutic',
    kind: 'skincare',
    unit: 'pump',
    slug: DERMACEUTIC_PRODUCTS_SLUG.FOAMER_15,
    totalAmount: 100,
    amountUnit: 'ml',
    priceCents: 3790,
    description: 'Mousse exfoliante intense pour purifier la peau et éliminer les cellules mortes.',
    notes: '15% Acide glycolique. Sans parfum & sans silicone.',
    inci: 'Water (Aqua) • Glycolic Acid • Sodium Hydroxide • Glycerin • Cocamidopropyl Betaine • Polysorbate 80 • Propylene Glycol • Methylpropanediol • Glycyrrhetinic Acid • Dipotassium Glycyrrhizate • Potassium Sorbate',
    url: 'https://www.dermaceutic.com/fr/foamer-15.html',
  },
  {
    name: 'Activabiome',
    brand: 'Dermaceutic',
    kind: 'skincare',
    unit: 'pump',
    slug: DERMACEUTIC_PRODUCTS_SLUG.ACTIVABIOME,
    totalAmount: 40,
    amountUnit: 'ml',
    priceCents: 4390,
    description: 'Crème de nuit pour peau à tendance acnéique.',
    notes: 'Action comédolytique et kératolytique pendant la nuit.',
    inci: 'Water (Aqua) • Caprylic/Capric Triglyceride • Glycolic Acid • Propylene Glycol • Dimethicone • Glycerin • Betaine • Cetearyl Alcohol • Glyceryl Stearate • PEG-100 Stearate • Ammonia • Salicylic Acid • Zinc Sulfate • Chlorella Vulgaris Extract • Laminaria Digitata Extract • Maris Aqua (Sea Water) • Saccharide Isomerate • Tetrasodium Glutamate Diacetate • Hydrolyzed Algin • Sclerotium Gum • Citronellyl Methylcrotonate • Fragrance (Parfum) • Phenethyl Alcohol • Chlorphenesin • Sodium Hydroxide • O-Cymen-5-Ol',
    url: 'https://www.dermaceutic.com/fr/activabiome.html',
  },
  {
    name: 'Light Ceutic',
    brand: 'Dermaceutic',
    kind: 'skincare',
    unit: 'pump',
    slug: DERMACEUTIC_PRODUCTS_SLUG.LIGHT_CEUTIC,
    totalAmount: 40,
    amountUnit: 'ml',
    priceCents: 4290,
    description: 'Crème de nuit unifiante qui réduit l’apparence des taches pigmentaires.',
    notes: 'Combinaison d’acides glycolique, phytique et Vitamine C.',
    inci: 'Water (Aqua) • Caprylic/Capric Triglyceride • Glycolic Acid • Glycerin • Sodium Hydroxide • Hydroxyethyl Acrylate/Sodium Acryloyldimethyl Taurate Copolymer • Phytic Acid • Steareth-21 • Gluconolactone • Steareth-2 • Ascorbyl Methylsilanol Pectinate • Tocopheryl Acetate • Tocopherol • Cholesterol • Sclerotium Gum • Lecithin • Helianthus Annuus (Sunflower) Seed Oil • Silica • Calcium Gluconate • Xanthan Gum • Squalane • Pullulan • Sorbitan Isostearate • Tetrasodium Glutamate Diacetate • Ethylhexylglycerin • Polysorbate 60 • Citronellyl Methylcrotonate • Phenethyl Alcohol • Methylpropanediol • Sodium Benzoate • Fragrance (Parfum)',
    url: 'https://www.dermaceutic.com/fr/light-ceutic.html',
  },
  {
    name: 'Turn Over 10',
    brand: 'Dermaceutic',
    kind: 'skincare',
    unit: 'pump',
    slug: DERMACEUTIC_PRODUCTS_SLUG.TURN_OVER_10,
    totalAmount: 40,
    amountUnit: 'ml',
    priceCents: 4290,
    description: 'Crème de nuit anti-âge lissante pour réduire les rides et ridules.',
    notes: '10.5% acide glycolique. Sans parfum.',
    inci: 'Water (Aqua) • Glycolic Acid • Caprylic/Capric Triglyceride • Glycerin • Cetearyl Alcohol • PEG-40 Stearate • Hydroxyethyl Acrylate/Sodium Acryloyldimethyl Taurate Copolymer • Polysorbate 80 • Dimethicone • Ammonia • Magnesium Aluminum Silicate • Cholesterol • Squalane • Xanthan Gum • Disodium EDTA • Polysorbate 60 • Sorbitan Isostearate • Octadecyl Di-T-Butyl-4-Hydroxyhydrocinnamate',
    url: 'https://www.dermaceutic.com/fr/turn-over.html',
  },
  {
    name: 'Turn Over 15',
    brand: 'Dermaceutic',
    kind: 'skincare',
    unit: 'pump',
    slug: DERMACEUTIC_PRODUCTS_SLUG.TURN_OVER_15,
    totalAmount: 40,
    amountUnit: 'ml',
    priceCents: 4390,
    description: 'Crème de nuit lissante intense pour les signes de vieillissement avancés.',
    notes: '15% acide glycolique pur. pH 3.0 – 3.5.',
    inci: 'Water (Aqua) • Glycolic Acid • Caprylic/Capric Triglyceride • Glycerin • Cetearyl Alcohol • PEG-40 Stearate • Hydroxyethyl Acrylate/Sodium Acryloyldimethyl Taurate Copolymer • Polysorbate 80 • Dimethicone • Ammonia • Magnesium Aluminum Silicate • Cholesterol • Squalane • Xanthan Gum • Disodium EDTA • Polysorbate 60 • Sorbitan Isostearate • Octadecyl Di-T-Butyl-4-Hydroxyhydrocinnamate',
    url: 'https://www.dermaceutic.com/fr/turn-over-15.html',
  },
  {
    name: 'Hyal Ceutic',
    brand: 'Dermaceutic',
    kind: 'skincare',
    unit: 'pump',
    slug: DERMACEUTIC_PRODUCTS_SLUG.HYAL_CEUTIC,
    totalAmount: 40,
    amountUnit: 'ml',
    priceCents: 4890,
    description:
      'Crème hydratante intense à l’acide hyaluronique de haut et bas poids moléculaire.',
    notes: 'Non-comédogène. Sans parfum. Vegan.',
    inci: 'Water (Aqua) • Ethylhexyl Palmitate • Butyrospermum Parkii (Shea) Butter • Hydrolyzed Soy Protein • Simmondsia Chinensis (Jojoba) Seed Oil • Triticum Vulgare (Wheat) Germ Oil • Isopropyl Palmitate • Polyacrylamide • Propylene Glycol • C13-14 Isoparaffin • Sodium Hyaluronate • Aloe Barbadensis Leaf Extract • Tocopheryl Acetate • Rosmarinus Officinalis (Rosemary) Leaf Extract • Pentylene Glycol • Chlorphenesin • Laureth-7 • O-Cymen-5-Ol • Benzoic Acid • Sorbic Acid',
    url: 'https://www.dermaceutic.com/fr/hyal-ceutic.html',
  },
  {
    name: 'Regen Ceutic',
    brand: 'Dermaceutic',
    kind: 'skincare',
    unit: 'pump',
    slug: DERMACEUTIC_PRODUCTS_SLUG.REGEN_CEUTIC,
    totalAmount: 40,
    amountUnit: 'ml',
    priceCents: 4990,
    description: 'Crème hydratante nourrissante qui raffermit la peau grâce aux peptides.',
    notes: 'Sans parfum & sans silicone.',
    inci: 'Water (Aqua) • Decyl Oleate • Glycerin • Propanediol • Butyrospermum Parkii (Shea) Butter • Neopentyl Glycol Diheptanoate • Glyceryl Stearate Citrate • Isododecane • C12-16 Alcohols • C10-18 Triglycerides • Hydrogenated Vegetable Glycerides • Pentylene Glycol • 1,2-Hexanediol • Palmitoyl Tripeptide-1 • Palmitoyl Tetrapeptide-7 • Ascorbyl Tetraisopalmitate • Sodium Hyaluronate • Tocopherol • Leontopodium Alpinum Flower/Leaf Extract • Hydrogenated Lecithin • Hydrogenated Palm Glycerides Citrate • Butylene Glycol • Xanthan Gum • Hexamidine Diisethionate • Agar • Palmitic Acid • Sodium Lactate • Carbomer • Coco-Glucoside • Sodium Hydroxide • Citric Acid',
    url: 'https://www.dermaceutic.com/fr/regen-ceutic.html',
  },
  {
    name: 'Hyal Ceutic Redens+',
    brand: 'Dermaceutic',
    kind: 'skincare',
    unit: 'jar',
    slug: DERMACEUTIC_PRODUCTS_SLUG.HYAL_CEUTIC_REDENS_PLUS,
    totalAmount: 50,
    amountUnit: 'ml',
    priceCents: 5590,
    description: 'Crème redensifiante riche pour peaux matures ciblant la zone SENEB.',
    notes: 'Acide polyglutamique et 3 poids d’acide hyaluronique. Sans parfum.',
    inci: 'Water (Aqua) • Glycerin • Caprylic/Capric Triglyceride • Cetearyl Alcohol • Butyrospermum Parkii (Shea) Butter • Glyceryl Stearate • Glyceryl Stearate Citrate • Olus Oil (Vegetable Oil) • Simmondsia Chinensis (Jojoba) Seed Oil • Pentylene Glycol • Myristyl Myristate • Hydrolyzed Hyaluronic Acid • Sodium Hyaluronate • Natto Gum • Salicyloyl Phytosphingosine • Pistacia Lentiscus (Mastic) Gum • Hydrolyzed Rhodophyceae Extract • Tocopheryl Acetate • Glycine Soja (Soybean) Oil • Candelilla Cera (Euphorbia Cerifera (Candelilla) Wax) • Glyceryl Caprylate • Sodium Stearoyl Glutamate • Microcrystalline Cellulose • Hydrogenated Vegetable Oil • Butylene Glycol • Polyacrylate Crosspolymer-6 • Sodium Benzoate • Xanthan Gum • Cellulose Gum • Sodium Chloride • Citric Acid',
    url: 'https://www.dermaceutic.com/fr/hyal-ceutic-redens.html',
  },
  {
    name: 'K Ceutic',
    brand: 'Dermaceutic',
    kind: 'skincare',
    unit: 'pump',
    slug: DERMACEUTIC_PRODUCTS_SLUG.K_CEUTIC,
    totalAmount: 30,
    amountUnit: 'ml',
    priceCents: 3890,
    description: 'Crème post-traitement protectrice avec SPF 50.',
    notes: 'Hypoallergénique. Sans parfum. Contient des filtres minéraux et organiques.',
    inci: 'Water (Aqua) • Isononyl Isononanoate • Ethylhexyl Methoxycinnamate • Beeswax (Cera Alba) • Titanium Dioxide [Nano] • Glycerin • Homosalate • Butyl Methoxydibenzoylmethane • Octyldodecanol • Bis-Ethylhexyloxyphenol Methoxyphenyl Triazine • Butyrospermum Parkii (Shea) Butter • Oleic/Linoleic/Linolenic Polyglycerides • Cyclopentasiloxane • Tocopherol • Bisabolol • Octyldodecyl Xyloside • PEG-30 Dipolyhydroxystearate • Zinc Stearate • Phenethyl Alcohol • Oxidized Corn Oil • Sodium Ascorbyl Phosphate • Hyaluronic Acid • Dipotassium Glycyrrhizate • Silica • Ammonium Acryloyldimethyltaurate/VP Copolymer • Magnesium Sulfate • Alpha-Glucan Oligosaccharide • Methylpropanediol • Sclerotium Gum • Tocopheryl Acetate • Glyceryl Caprylate • Citric Acid • Dimethiconol • Sodium Benzoate • Dimethicone • Pseudoalteromonas Ferment Extract • Ethylhexylglycerin • Xanthan Gum • Maltodextrin • Caprylyl Glycol • Glyceryl Undecylenate • Yellow 5 (CI 19140) • Glycine Soja (Soybean) Seed Extract • Silanetriol • Red 4 (CI 14700) • BHT • Sodium Sulfate • Salicylic Acid • Glucose • Phytic Acid • Red 33 (CI 17200) • Blue 1 (CI 42090) • Sodium Hydroxide',
    url: 'https://www.dermaceutic.com/fr/k-ceutic.html',
  },
  {
    name: 'Panthenol Ceutic',
    brand: 'Dermaceutic',
    kind: 'skincare',
    unit: 'tube',
    slug: DERMACEUTIC_PRODUCTS_SLUG.PANTHENOL_CEUTIC,
    totalAmount: 30,
    amountUnit: 'g',
    priceCents: 2390,
    description: 'Baume réparateur nourrissant enrichi en panthénol et beurre de karité.',
    notes: 'Idéal peaux sensibles et post-interventions. Sans parfum.',
    inci: 'Paraffinum Liquidum (Mineral Oil) • Cera Microcristallina (Microcrystalline Wax) • Paraffin • Panthenol • Helianthus Annuus (Sunflower) Seed Oil • Butyrospermum Parkii (Shea) Butter • Cera Alba (Beeswax) • Bisabolol • Lanolin • Tocopheryl Acetate',
    url: 'https://www.dermaceutic.com/fr/panthenol-ceutic.html',
  },
  {
    name: 'C25 Cream',
    brand: 'Dermaceutic',
    kind: 'skincare',
    unit: 'pump',
    slug: DERMACEUTIC_PRODUCTS_SLUG.C25_CREAM,
    totalAmount: 30,
    amountUnit: 'ml',
    priceCents: 5790,
    description: 'Crème antioxydante concentrée à 25% de complexe vitamine C.',
    notes: 'Contient de la Vitamine A (Retinyl Palmitate). Sans parfum.',
    inci: 'Water (Aqua) • Ascorbyl Methylsilanol Pectinate • Ethylhexyl Cocoate • Glycerin • Methylpropanediol • C15-19 Alkane • Caprylic/Capric Triglyceride • Panthenol • Pentylene Glycol • Sodium Acrylate/Sodium Acryloyldimethyl Taurate Copolymer • Glyceryl Stearate • PEG-100 Stearate • Tocopheryl Acetate • Retinyl Palmitate • Lactic Acid • Tocopherol • Morus Alba Root Extract • Vitis Vinifera (Grape) Seed Extract • Isohexadecane • Butylene Glycol • Polysorbate 80 • Sclerotium Gum • Citronellyl Methylcrotonate • Alcohol • Sorbitan Oleate • Citric Acid • PEG-40 Hydrogenated Castor Oil • Tetrasodium Glutamate Diacetate • Chlorphenesin • O-Cymen-5-Ol • Fragrance (Parfum)',
    url: 'https://www.dermaceutic.com/fr/c25-cream.html',
  },
  {
    name: 'Activ Retinol 0.5',
    brand: 'Dermaceutic',
    kind: 'skincare',
    unit: 'pump',
    slug: DERMACEUTIC_PRODUCTS_SLUG.ACTIV_RETINOL_0_5,
    totalAmount: 30,
    amountUnit: 'ml',
    priceCents: 6090,
    description: 'Sérum anti-âge à concentration optimale en rétinol.',
    notes: '0.2% Rétinol pur + 1% Retinol Boost. Usage soir.',
    inci: 'Water (Aqua) • Pentylene Glycol • Polyglyceryl-10 Stearate • Caprylic/Capric Triglyceride • Diglycerin • Glycine Soja (Soybean) Oil • Undecane • Panthenol • Microcrystalline Cellulose • Retinol • Chlorella Vulgaris Extract • Ascorbyl Tetraisopalmitate • Tocopherol • Sodium Ascorbyl Phosphate • Tocopheryl Acetate • Phospholipids • Sphingolipids • Allantoin • Glycerin • Tridecane • Phosphatidylcholine • Carbomer • Polyglyceryl-10 Laurate • Propanediol • Sodium Gluconate • Xanthan Gum • Coco-Caprylate/ Caprate • Hydrogenated Olive Oil Unsaponifiables • O-Cymen-5-Ol • Sodium Dehydroacetate • Lecithin • Cetyl Alcohol • Sodium Hydroxide • Caesalpinia Spinosa Gum • Oryza Sativa (Rice) Hull Powder • Lactic Acid • Sodium Citrate • P-Anisic Acid',
    url: 'https://www.dermaceutic.com/fr/activ-retinol-0-5.html',
  },
  {
    name: 'Activ Retinol 1.0',
    brand: 'Dermaceutic',
    kind: 'skincare',
    unit: 'pump',
    slug: DERMACEUTIC_PRODUCTS_SLUG.ACTIV_RETINOL_1_0,
    totalAmount: 30,
    amountUnit: 'ml',
    priceCents: 6890,
    description: 'Sérum anti-âge intense avec triple technologie rétinol.',
    notes: '0.3% Rétinol pur + 1% Retinol Boost. Usage soir.',
    inci: 'Water (Aqua) • Pentylene Glycol • Polyglyceryl-10 Stearate • Caprylic/Capric Triglyceride • Diglycerin • Glycine Soja (Soybean) Oil • Undecane • Panthenol • Microcrystalline Cellulose • Retinol • Chlorella Vulgaris Extract • Ascorbyl Tetraisopalmitate • Tocopherol • Sodium Ascorbyl Phosphate • Tocopheryl Acetate • Phospholipids • Sphingolipids • Allantoin • Glycerin • Tridecane • Phosphatidylcholine • Carbomer • Polyglyceryl-10 Laurate • Propanediol • Sodium Gluconate • Xanthan Gum • Coco-Caprylate/ Caprate • Hydrogenated Olive Oil Unsaponifiables • O-Cymen-5-Ol • Sodium Dehydroacetate • Lecithin • Cetyl Alcohol • Sodium Hydroxide • Caesalpinia Spinosa Gum • Oryza Sativa (Rice) Hull Powder • Lactic Acid • Sodium Citrate • P-Anisic Acid',
    url: 'https://www.dermaceutic.com/fr/activ-retinol-1-0.html',
  },
  {
    name: 'Derma Lift 5.0',
    brand: 'Dermaceutic',
    kind: 'skincare',
    unit: 'pump',
    slug: DERMACEUTIC_PRODUCTS_SLUG.DERMA_LIFT_5_0,
    totalAmount: 30,
    amountUnit: 'ml',
    priceCents: 6090,
    description: 'Sérum liftant ciblant la fermeté et les rides.',
    notes: 'Contient 0.5% Bakuchiol. Sans parfum.',
    inci: 'Water (Aqua) • Propanediol • Pentylene Glycol • Glycerin • Acrylates/Ethylhexyl Acrylate Copolymer • Undecane • Dicaprylyl Carbonate • Tridecane • Sorbitan Olivate • Cetearyl Olivate • Panthenol • Butylene Glycol • Palmitoyl Tripeptide-1 • Palmitoyl Tetrapeptide-7 • Phospholipids • Sphingolipids • Prunus Amygdalus Dulcis (Sweet Almond) Seed Extract • Bakuchiol • Allantoin • Sodium PCA • Zinc PCA • Magnesium PCA • Manganese PCA • Prunus Armeniaca (Apricot) Kernel Oil • Ascorbyl Tetraisopalmitate • Cetyl Palmitate • Maltodextrin • Ammonium Acryloyldimethyltaurate/VP Copolymer • Sorbitan Palmitate • Xanthan Gum • Chlorphenesin • Coco-Caprylate/Caprate • Hydrogenated Olive Oil Unsaponifiables • Stearalkonium Hectorite • Citric Acid • O-Cymen-5-Ol • Propylene Carbonate • Tocopherol • Carbomer • Sodium Lactate • 1,2-Hexanediol • Caprylyl Glycol • Laureth-21 • Polysorbate 20 • Sodium Dehydroacetate • P-Anisic Acid • Sodium Citrate',
    url: 'https://www.dermaceutic.com/fr/derma-lift.html',
  },
  {
    name: 'Reveal 4X',
    brand: 'Dermaceutic',
    kind: 'skincare',
    unit: 'tube',
    slug: DERMACEUTIC_PRODUCTS_SLUG.REVEAL_4X,
    totalAmount: 15,
    amountUnit: 'ml',
    priceCents: 4990,
    description: 'Sérum contour des yeux global ciblant cernes, poches, ridules et déshydratation.',
    notes: 'Applicateur ZAMAC. Testé sous contrôle ophtalmologique.',
    inci: 'Water (Aqua) • Pentylene Glycol • Oryza Sativa (Rice) Starch • Butylene Glycol • C15-19 Alkane • Glycerin • Propanediol • Sodium Acrylates Copolymer • Niacinamide • Ethylhexyl Polyhydroxystearate • Prunus Amygdalus Dulcis (Sweet Almond) Oil • Caffeine • Hydrolyzed Hyaluronic Acid • Sodium Polyglutamate • Fraxinus Excelsior Bark Extract • Persea Gratissima (Avocado) Fruit Extract • Bacillus Ferment • Aloe Barbadensis Leaf Juice Powder • Siloxanetriol Alginate • Silanetriol • Tocopheryl Acetate • Tocopherol • Glycine Soja (Soybean) Oil • Glycolic Acid • Glyceryl Caprylate • Lecithin • Sodium Stearoyl Glutamate • Xanthan Gum • Chlorphenesin • Sodium Gluconate • Citric Acid • Sodium Hydroxide',
    url: 'https://www.dermaceutic.com/fr/reveal-4x.html',
  },
  {
    name: 'Radiance',
    brand: 'Dermaceutic',
    kind: 'skincare',
    unit: 'pump',
    slug: DERMACEUTIC_PRODUCTS_SLUG.RADIANCE,
    totalAmount: 30,
    amountUnit: 'ml',
    priceCents: 5490,
    description: 'Crème éclaircissante qui exfolie en douceur et redonne de l’éclat.',
    notes: 'Contient Acide Kojique et Arbutine. Sans parfum.',
    inci: 'Water (Aqua) • Coco-Caprylate/Caprate • Behenyl Alcohol • Arbutin • Niacinamide • Hydroxyphenoxy Propionic Acid • Mandelic Acid • Salicylic Acid • Cetearyl Alcohol • Sodium Hydroxide • Arachidyl Alcohol • Kojic Acid • Glycyrrhetinic Acid • Hydroxyacetophenone • Cetearyl Glucoside • Arachidyl Glucoside • Xanthan Gum • 1,2 Hexanediol • Caprylyl Glycol • Sodium Gluconate • Tocopherol • Citric Acid',
    url: 'https://www.dermaceutic.com/fr/radiance.html',
  },
  {
    name: 'Yellow Cream',
    brand: 'Dermaceutic',
    kind: 'skincare',
    unit: 'tube',
    slug: DERMACEUTIC_PRODUCTS_SLUG.YELLOW_CREAM,
    totalAmount: 15,
    amountUnit: 'ml',
    priceCents: 4390,
    description: 'Correcteur anti-taches ciblant les taches pigmentaires localisées.',
    notes: 'Vegan. Sans parfum & sans silicone.',
    inci: 'Water (Aqua) • Butylene Glycol • Glycolic Acid • Cetearyl Alcohol • Glyceryl Stearate • Ceteareth-20 • Cetyl Palmitate • Arctostaphylos Uva Ursi Leaf Extract • Propylene Glycol • Glycine Soja (Soybean) Oil • Undecylenoyl Phenylalanine • Maltodextrin • Triethanolamine • Kojic Acid • Alpha-Arbutin • Glycyrrhiza Glabra (Licorice) Root Extract • Morus Alba Bark Extract • Morus Alba Root Extract • Salicylic Acid • Scutellaria Baicalensis Root Extract • Prunus Amygdalus Dulcis (Sweet Almond) Oil • Prunus Armeniaca (Apricot) Kernel Oil • Simmondsia Chinensis (Jojoba) Seed Oil • Tocopheryl Acetate • Triticum Vulgare (Wheat) Germ Oil • Pentylene Glycol • Hydroxyethyl Acrylate/Sodium Acryloyldimethyl Taurate Copolymer • Magnesium Aluminum Silicate • Xanthan Gum • Sodium Hydroxide • Sodium Metabisulfite • Tetrasodium EDTA • Polysorbate 60 • Sorbitan Isostearate • Yellow 5 (CI 19140)',
    url: 'https://www.dermaceutic.com/fr/yellow-cream.html',
  },
]
