import { TAG_SLUGS } from '../../tags/seed-tags'
import { DERMACEUTIC_PRODUCTS_SLUG } from './dermaceutic'

interface ProductTagGroups {
  primary: string[] // Préoccupations majeures + actions clés
  secondary: string[] // Type de produit, étapes routine, propriétés, labels
  avoid: string[] // Exclusions (incompatibilités avec le produit)
}

export const DERMACEUTIC_PRODUCT_TAGS: Record<string, ProductTagGroups> = {
  [DERMACEUTIC_PRODUCTS_SLUG.MASK_15]: {
    primary: [TAG_SLUGS.ANTI_ACNE, TAG_SLUGS.PORES_DILATES],
    secondary: [
      TAG_SLUGS.MASQUE_ARGILE,
      TAG_SLUGS.EXFOLIATION,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.PEAU_GRASSE,
      TAG_SLUGS.KERATOLYTIQUE,
      TAG_SLUGS.ZONE_VISAGE,
    ],
    avoid: [TAG_SLUGS.PEAU_SENSIBLE, TAG_SLUGS.PEAU_REACTIVE, TAG_SLUGS.GROSSESSE_COMPATIBLE],
  },

  [DERMACEUTIC_PRODUCTS_SLUG.OXYBIOME]: {
    primary: [TAG_SLUGS.MICROBIOME, TAG_SLUGS.ECLAT],
    secondary: [
      TAG_SLUGS.EAU_MICELLAIRE,
      TAG_SLUGS.NETTOYANT,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.PEAU_TOUS_TYPES,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.POLLUTION,
    ],
    avoid: [],
  },

  [DERMACEUTIC_PRODUCTS_SLUG.ADVANCED_CLEANSER]: {
    primary: [TAG_SLUGS.BARRIERE_CUTANEE, TAG_SLUGS.HYDRATATION],
    secondary: [
      TAG_SLUGS.MOUSSE_NETTOYANTE,
      TAG_SLUGS.NETTOYANT,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.PEAU_TOUS_TYPES,
      TAG_SLUGS.VEGAN,
      TAG_SLUGS.HUMECTANT,
    ],
    avoid: [],
  },

  [DERMACEUTIC_PRODUCTS_SLUG.FOAMER_5]: {
    primary: [TAG_SLUGS.ECLAT, TAG_SLUGS.GRAIN_PEAU],
    secondary: [
      TAG_SLUGS.MOUSSE_NETTOYANTE,
      TAG_SLUGS.EXFOLIATION,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.PEAU_TOUS_TYPES,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.VEGAN,
    ],
    avoid: [],
  },

  [DERMACEUTIC_PRODUCTS_SLUG.FOAMER_15]: {
    primary: [TAG_SLUGS.GRAIN_PEAU, TAG_SLUGS.ANTI_ACNE],
    secondary: [
      TAG_SLUGS.MOUSSE_NETTOYANTE,
      TAG_SLUGS.EXFOLIATION,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.PEAU_GRASSE,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.VEGAN,
      TAG_SLUGS.KERATOLYTIQUE,
    ],
    avoid: [TAG_SLUGS.PEAU_SENSIBLE, TAG_SLUGS.PEAU_REACTIVE],
  },

  [DERMACEUTIC_PRODUCTS_SLUG.ACTIVABIOME]: {
    primary: [TAG_SLUGS.ANTI_ACNE, TAG_SLUGS.MICROBIOME],
    secondary: [
      TAG_SLUGS.CREME_DE_NUIT,
      TAG_SLUGS.TRAITEMENT,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.PEAU_GRASSE,
      TAG_SLUGS.SEBO_REGULATEUR,
      TAG_SLUGS.KERATOLYTIQUE,
    ],
    avoid: [TAG_SLUGS.PEAU_REACTIVE],
  },

  [DERMACEUTIC_PRODUCTS_SLUG.LIGHT_CEUTIC]: {
    primary: [TAG_SLUGS.ANTI_TACHES, TAG_SLUGS.HYPERPIGMENTATION],
    secondary: [
      TAG_SLUGS.CREME_DE_NUIT,
      TAG_SLUGS.TRAITEMENT,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.ECLAT,
      TAG_SLUGS.ANTI_OXYDANT,
      TAG_SLUGS.EXFOLIANT_CHIMIQUE,
    ],
    avoid: [TAG_SLUGS.PEAU_SENSIBLE],
  },

  [DERMACEUTIC_PRODUCTS_SLUG.TURN_OVER_10]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.GRAIN_PEAU],
    secondary: [
      TAG_SLUGS.CREME_DE_NUIT,
      TAG_SLUGS.TRAITEMENT,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.PEAU_NORMALE,
      TAG_SLUGS.PEAU_MIXTE,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.REPULPANT,
    ],
    avoid: [TAG_SLUGS.PEAU_SENSIBLE],
  },

  [DERMACEUTIC_PRODUCTS_SLUG.TURN_OVER_15]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.GRAIN_PEAU],
    secondary: [
      TAG_SLUGS.CREME_DE_NUIT,
      TAG_SLUGS.TRAITEMENT,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.PEAU_TOUS_TYPES,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.REPULPANT,
      TAG_SLUGS.EXFOLIATION,
    ],
    avoid: [TAG_SLUGS.PEAU_SENSIBLE, TAG_SLUGS.PEAU_REACTIVE],
  },

  [DERMACEUTIC_PRODUCTS_SLUG.HYAL_CEUTIC]: {
    primary: [TAG_SLUGS.DESHYDRATATION, TAG_SLUGS.BARRIERE_CUTANEE],
    secondary: [
      TAG_SLUGS.CREME_HYDRATANTE,
      TAG_SLUGS.HYDRATATION,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.PEAU_TOUS_TYPES,
      TAG_SLUGS.NON_COMEDOGENE,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.VEGAN,
    ],
    avoid: [],
  },

  [DERMACEUTIC_PRODUCTS_SLUG.REGEN_CEUTIC]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.REPULPANT],
    secondary: [
      TAG_SLUGS.CREME_HYDRATANTE,
      TAG_SLUGS.HYDRATATION,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.PEAU_TOUS_TYPES,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.REPARATEUR,
      TAG_SLUGS.ANTI_OXYDANT,
    ],
    avoid: [],
  },

  [DERMACEUTIC_PRODUCTS_SLUG.HYAL_CEUTIC_REDENS_PLUS]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.DESHYDRATATION],
    secondary: [
      TAG_SLUGS.CREME_HYDRATANTE,
      TAG_SLUGS.HYDRATATION,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.TEXTURE_RICHE,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.REPULPANT,
    ],
    avoid: [],
  },

  [DERMACEUTIC_PRODUCTS_SLUG.K_CEUTIC]: {
    primary: [TAG_SLUGS.POST_ACNE, TAG_SLUGS.CICATRISATION],
    secondary: [
      TAG_SLUGS.PROTECTION_SOLAIRE,
      TAG_SLUGS.CREME_SOLAIRE,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.PEAU_REACTIVE,
      TAG_SLUGS.APAISANT,
      TAG_SLUGS.REPARATEUR,
      TAG_SLUGS.HYPOALLERGENIQUE,
      TAG_SLUGS.SANS_PARFUM,
    ],
    avoid: [],
  },

  [DERMACEUTIC_PRODUCTS_SLUG.PANTHENOL_CEUTIC]: {
    primary: [TAG_SLUGS.PEAU_SENSIBLE, TAG_SLUGS.BARRIERE_CUTANEE],
    secondary: [
      TAG_SLUGS.BAUME,
      TAG_SLUGS.EMOLLIENCE,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.PEAU_ATOPIQUE,
      TAG_SLUGS.REPARATEUR,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.APAISANT,
    ],
    avoid: [],
  },

  [DERMACEUTIC_PRODUCTS_SLUG.C25_CREAM]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.ECLAT],
    secondary: [
      TAG_SLUGS.CREME_HYDRATANTE,
      TAG_SLUGS.TRAITEMENT,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.PEAU_TOUS_TYPES,
      TAG_SLUGS.ANTI_OXYDANT,
      TAG_SLUGS.PHOTO_VIEILLISSEMENT,
      TAG_SLUGS.TEINT_TERNE,
    ],
    avoid: [],
  },

  [DERMACEUTIC_PRODUCTS_SLUG.ACTIV_RETINOL_0_5]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.PHOTO_VIEILLISSEMENT],
    secondary: [
      TAG_SLUGS.SERUM,
      TAG_SLUGS.TRAITEMENT,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.PEAU_NORMALE,
      TAG_SLUGS.PEAU_MIXTE,
      TAG_SLUGS.REPULPANT,
      TAG_SLUGS.ANTI_OXYDANT,
    ],
    avoid: [TAG_SLUGS.GROSSESSE_COMPATIBLE],
  },

  [DERMACEUTIC_PRODUCTS_SLUG.ACTIV_RETINOL_1_0]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.PHOTO_VIEILLISSEMENT],
    secondary: [
      TAG_SLUGS.SERUM,
      TAG_SLUGS.TRAITEMENT,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.PEAU_GRASSE,
      TAG_SLUGS.PEAU_MIXTE,
      TAG_SLUGS.REPULPANT,
      TAG_SLUGS.GRAIN_PEAU,
    ],
    avoid: [TAG_SLUGS.PEAU_SENSIBLE, TAG_SLUGS.GROSSESSE_COMPATIBLE],
  },

  [DERMACEUTIC_PRODUCTS_SLUG.DERMA_LIFT_5_0]: {
    primary: [TAG_SLUGS.ANTI_AGE, TAG_SLUGS.REPULPANT],
    secondary: [
      TAG_SLUGS.SERUM,
      TAG_SLUGS.TRAITEMENT,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.PEAU_TOUS_TYPES,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.ANTI_OXYDANT,
    ],
    avoid: [],
  },

  [DERMACEUTIC_PRODUCTS_SLUG.REVEAL_4X]: {
    primary: [TAG_SLUGS.CERNES_POCHES, TAG_SLUGS.DESHYDRATATION],
    secondary: [
      TAG_SLUGS.CONTOUR_YEUX,
      TAG_SLUGS.SOIN_YEUX,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.PEAU_TOUS_TYPES,
      TAG_SLUGS.ECLAT,
      TAG_SLUGS.HUMECTANT,
    ],
    avoid: [],
  },

  [DERMACEUTIC_PRODUCTS_SLUG.RADIANCE]: {
    primary: [TAG_SLUGS.ANTI_TACHES, TAG_SLUGS.HYPERPIGMENTATION],
    secondary: [
      TAG_SLUGS.CREME_HYDRATANTE,
      TAG_SLUGS.TRAITEMENT,
      TAG_SLUGS.MATIN,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.PEAU_TOUS_TYPES,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.ECLAT,
      TAG_SLUGS.EXFOLIANT_CHIMIQUE,
    ],
    avoid: [],
  },

  [DERMACEUTIC_PRODUCTS_SLUG.YELLOW_CREAM]: {
    primary: [TAG_SLUGS.ANTI_TACHES, TAG_SLUGS.HYPERPIGMENTATION],
    secondary: [
      TAG_SLUGS.SPOT_TREATMENT,
      TAG_SLUGS.TRAITEMENT,
      TAG_SLUGS.SOIR,
      TAG_SLUGS.PEAU_TOUS_TYPES,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.VEGAN,
      TAG_SLUGS.EXFOLIANT_CHIMIQUE,
    ],
    avoid: [TAG_SLUGS.PEAU_SENSIBLE],
  },
}
