export const BIODERMA_PRODUCT_SLUGS = {
  BIODERMA_CREALINE_DEFENSIVE_RICHE: 'bioderma-crealine-defensive-riche',
  BIODERMA_CREALINE_DEFENSIVE_LEGERE: 'bioderma-crealine-defensive-legere',
  BIODERMA_CREALINE_DEFENSIVE: 'bioderma-crealine-defensive',
  BIODERMA_CREALINE_AR_PLUS: 'bioderma-crealine-ar-plus',
  BIODERMA_CREALINE_GEL_MOUSSANT: 'bioderma-crealine-gel-moussant',
  BIODERMA_CREALINE_FORT: 'bioderma-crealine-fort',
  BIODERMA_CREALINE_DS_PLUS: 'bioderma-crealine-ds-plus',
  BIODERMA_CREALINE_HUILE_MICELLAIRE: 'bioderma-crealine-huile-micellaire',
  BIODERMA_CREALINE_H2O: 'bioderma-crealine-h2o',

  BIODERMA_CICABIO_CREME: 'bioderma-cicabio-creme',
  BIODERMA_CICABIO_CREME_PLUS: 'bioderma-cicabio-creme-plus',
  BIODERMA_CICABIO_CREME_PLUS_SPF50: 'bioderma-cicabio-creme-plus-spf50',
  BIODERMA_CICABIO_BAUME_LAVANT: 'bioderma-cicabio-baume-lavant',
  BIODERMA_CICABIO_RESTOR: 'bioderma-cicabio-restor',
  BIODERMA_CICABIO_SOIN_ISOLANT: 'bioderma-cicabio-soin-isolant',
  BIODERMA_CICABIO_ARNICA: 'bioderma-cicabio-arnica',

  BIODERMA_SENSIBIO_AR: 'bioderma-sensibio-ar-plus',

  BIODERMA_ATODERM_HUILE_DOUCHE: 'bioderma-atoderm-huile-douche',
  BIODERMA_ATODERM_INTENSIVE_GEL_CREME: 'bioderma-atoderm-intensive-gel-creme',
  BIODERMA_ATODERM_INTENSIVE_EYE: 'bioderma-atoderm-intensive-eye',
  BIODERMA_ATODERM_INTENSIVE_BAUME: 'bioderma-atoderm-intensive-baume',

  BIODERMA_PIGMENTBIO_SENSITIVE_AREAS: 'bioderma-pigmentbio-sensitive-areas',

  BIODERMA_SEBIUM_GEL_MOUSSANT: 'bioderma-sebium-gel-moussant',
  BIODERMA_SEBIUM_KERATO_PLUS: 'bioderma-sebium-kerato-plus',
  BIODERMA_SEBIUM_HYDRA_CLEANSER: 'bioderma-sebium-hydra-cleanser',
  BIODERMA_SEBIUM_H2O: 'bioderma-sebium-h2o',
  BIODERMA_SEBIUM_HYDRA: 'bioderma-sebium-hydra',
  BIODERMA_SEBIUM_SENSITIVE: 'bioderma-sebium-sensitive',

  BIODERMA_PHOTODERM_XDEFENSE_SPF50: 'bioderma-photoderm-xdefense-spf50',
}
export const BIODERMA_PRODUCT_DATA = [
  {
    name: 'Créaline Defensive Riche',
    brand: 'Bioderma',
    kind: 'skincare',
    unit: 'pump',
    slug: BIODERMA_PRODUCT_SLUGS.BIODERMA_CREALINE_DEFENSIVE_RICHE,
    totalAmount: 40,
    amountUnit: 'ml',
    priceCents: 1398,
    description:
      'Crème active apaisante riche pour peaux sensibles et sensibilisées, sèches à très sèches.',
    notes:
      "Texture riche enveloppante. Technologie Défensive renforce l'auto-défense cutanée. Hydratation 12h.",
    inci: 'AQUA/WATER/EAU, GLYCERIN, DICAPRYLYL ETHER, GLYCOL PALMITATE, BUTYLENE GLYCOL, CETYL PALMITATE, GLYCERYL STEARATE CITRATE, SQUALANE, SUCROSE STEARATE, TRIDECYL TRIMELLITATE, GLYCERYL DIBEHENATE, POLYSORBATE 60, PENTYLENE GLYCOL, TRIBEHENIN, GLYCERYL BEHENATE, ACRYLATES/C10-30 ALKYL ACRYLATE CROSSPOLYMER, CAPRYLYL GLYCOL, CARNOSINE, HYDROXYETHYL ACRYLATE/SODIUM ACRYLOYLDIMETHYL TAURATE COPOLYMER, MANNITOL, XYLITOL, TOCOPHEROL, SALVIA MILTIORRHIZA FLOWER/LEAF/ROOT EXTRACT, RHAMNOSE, GLYCINE SOJA (SOYBEAN) OIL, SORBITAN ISOSTEARATE, SODIUM HYDROXIDE, PALMITOYL TETRAPEPTIDE-10',
    url: 'https://www.bioderma.fr',
  },
  {
    name: 'Créaline Defensive Légère',
    brand: 'Bioderma',
    kind: 'skincare',
    unit: 'pump',
    slug: BIODERMA_PRODUCT_SLUGS.BIODERMA_CREALINE_DEFENSIVE_LEGERE,
    totalAmount: 40,
    amountUnit: 'ml',
    priceCents: 1398,
    description:
      'Crème active apaisante légère pour peaux sensibles et sensibilisées, normales à mixtes.',
    notes:
      'Texture légère et fraîche. Même technologie Défensive que la version Riche, idéale jour/sous maquillage.',
    inci: 'AQUA/WATER/EAU, GLYCERIN, DICAPRYLYL ETHER, PROPYLHEPTYL CAPRYLATE, BUTYLENE GLYCOL, GLYCERYL STEARATE CITRATE, GLYCOL PALMITATE, SQUALANE, SUCROSE STEARATE, MANGIFERA INDICA (MANGO) SEED BUTTER, PENTYLENE GLYCOL, ACRYLATES/C10-30 ALKYL ACRYLATE CROSSPOLYMER, CAPRYLYL GLYCOL, CARNOSINE, HYDROXYETHYL ACRYLATE/SODIUM ACRYLOYLDIMETHYL TAURATE COPOLYMER, MANNITOL, XYLITOL, TOCOPHEROL, SALVIA MILTIORRHIZA FLOWER/LEAF/ROOT EXTRACT, RHAMNOSE, GLYCINE SOJA (SOYBEAN) OIL, POLYSORBATE 60, SORBITAN ISOSTEARATE, PALMITOYL TETRAPEPTIDE-10',
    url: 'https://www.bioderma.fr',
  },
  {
    name: 'Cicabio Crème+',
    brand: 'Bioderma',
    kind: 'skincare',
    unit: 'pump',
    slug: BIODERMA_PRODUCT_SLUGS.BIODERMA_CICABIO_CREME_PLUS,
    totalAmount: 40,
    amountUnit: 'ml',
    priceCents: 698,
    description:
      'Soin ultra-réparateur apaisant pour peaux abîmées, irritées ou lésées (visage, corps, zones intimes).',
    notes:
      'Texture effet pansement. Antalgicine™ + Optimal Repair complex. Restaure microbiome en 3h.',
    inci: 'AQUA/WATER/EAU, CAPRYLIC/CAPRIC TRIGLYCERIDE, GLYCERIN, POLYGLYCERYL-3 POLYRICINOLEATE, BRASSICA CAMPESTRIS (RAPESEED) SEED OIL, BUTYLENE GLYCOL, TAPIOCA STARCH, HYDROGENATED RAPESEED OIL, XYLOSE, POLYGLYCERYL-3 DIISOSTEARATE, SIMMONDSIA CHINENSIS (JOJOBA) SEED OIL, MAGNESIUM SULFATE, PENTYLENE GLYCOL, SQUALANE, 1,2-HEXANEDIOL, CAPRYLYL GLYCOL, SODIUM POLYGLUTAMATE, SODIUM CITRATE, XANTHAN GUM, SODIUM HYALURONATE, TOCOPHEROL, MANNITOL, RHAMNOSE, XYLITOL, ACETYL DIPEPTIDE-1 CETYL ESTER, HELIANTHUS ANNUUS (SUNFLOWER) SEED OIL, CITRIC ACID, FRUCTOOLIGOSACCHARIDES',
    url: 'https://www.bioderma.fr',
  },

  {
    name: 'Sensibio AR+',
    brand: 'Bioderma',
    kind: 'skincare',
    unit: 'pump',
    slug: BIODERMA_PRODUCT_SLUGS.BIODERMA_SENSIBIO_AR,
    totalAmount: 40,
    amountUnit: 'ml',
    priceCents: 1800,
    description: 'Soin écobiologique anti-rougeurs haute tolérance. Technologie Rosactiv™ 2.0.',
    notes: 'Excellente base de maquillage. Sans parfum.',
    inci: 'AQUA/WATER/EAU, GLYCERIN, C15-19 ALKANE, C10-18 TRIGLYCERIDES, DIPROPYLENE GLYCOL, GLYCERYL STEARATE CITRATE, HELIANTHUS ANNUUS (SUNFLOWER) SEED WAX, PENTYLENE GLYCOL, SQUALANE, SUCROSE STEARATE, CORN STARCH MODIFIED, COCOS NUCIFERA (COCONUT) OIL, MALTOOLIGOSYL GLUCOSIDE, GLYCERYL CAPRYLATE/CAPRATE, SCLEROTIUM GUM, GLYCYRRHETINIC ACID, HYDROGENATED STARCH HYDROLYSATE, XANTHAN GUM, 1-METHYLHYDANTOIN-2-IMIDE, PHYTOSPHINGOSINE, SODIUM CITRATE, CITRIC ACID, MANNITOL, XYLITOL, o-CYMEN-5-OL, BENZOTRIAZOLYL DODECYL P-CRESOL, RHAMNOSE, TOCOPHEROL, HELIANTHUS ANNUUS (SUNFLOWER) SEED OIL',
    url: 'https://www.bioderma.fr',
  },
  {
    name: 'Atoderm Huile de douche',
    brand: 'Bioderma',
    kind: 'skincare',
    unit: 'bottle',
    slug: BIODERMA_PRODUCT_SLUGS.BIODERMA_ATODERM_HUILE_DOUCHE,
    totalAmount: 1000,
    amountUnit: 'ml',
    priceCents: 1400,
    description:
      "Huile lavante relipidante et hydratante pour peaux sèches à atopiques. Offre 24h d'hydratation.",
    notes: '33% agents hydratants et relipidants. Technologie Skin Barrier Therapy. Brevet DAF.',
    inci: 'AQUA/WATER, GLYCERIN, PEG-7 GLYCERYL COCOATE, SODIUM COCOAMPHOACETATE, LAURYL GLUCOSIDE, COCO-GLUCOSIDE, GLYCERYL OLEATE, CITRIC ACID, PEG-90 GLYCERYL ISOSTEARATE, FRAGRANCE, MANNITOL, POLYSORBATE 20, XYLITOL, LAURETH-2, RHAMNOSE, NIACINAMIDE, FRUCTOOLIGOSACCHARIDES, TOCOPHEROL, HYDROGENATED PALM GLYCERIDES CITRATE, LECITHIN, ASCORBYL PALMITATE',
    url: 'https://www.bioderma.fr',
  },
  {
    name: 'Créaline Huile micellaire',
    brand: 'Bioderma',
    kind: 'skincare',
    unit: 'pump',
    slug: BIODERMA_PRODUCT_SLUGS.BIODERMA_CREALINE_HUILE_MICELLAIRE,
    totalAmount: 150,
    amountUnit: 'ml',
    priceCents: 1300,
    description:
      'Huile nettoyante et démaquillante apaisante pour peaux sensibles. Élimine le maquillage waterproof.',
    notes:
      'Technologie micellaire double action. Enrichie en Oméga 3-6 et Acide aminé (Sodium PCA).',
    inci: 'ETHYLHEXYL PALMITATE, BRASSICA CAMPESTRIS (RAPESEED) SEED OIL, POLYGLYCERYL-4 OLEATE, AQUA/WATER, SODIUM PCA, PROPANEDIOL, CAPRYLIC/CAPRIC TRIGLYCERIDE, BENZOTRIAZOLYL DODECYL P-CRESOL, TOCOPHEROL, HELIANTHUS ANNUUS (SUNFLOWER) SEED OIL, LAMINARIA OCHROLEUCA EXTRACT, STEARYL GLYCYRRHETINATE',
    url: 'https://www.bioderma.fr',
  },
  {
    name: 'Photoderm XDEFENSE ULTRA-FLUID SPF50+ INVISIBLE',
    brand: 'Bioderma',
    kind: 'sunscreen',
    unit: 'bottle',
    slug: BIODERMA_PRODUCT_SLUGS.BIODERMA_PHOTODERM_XDEFENSE_SPF50,
    totalAmount: 40,
    amountUnit: 'ml',
    priceCents: 1900,
    description:
      'Soin solaire détox très haute protection contre les UV et la pollution. Texture ultra-fluide invisible.',
    notes: 'SPF50+, UVA 35.9. Action biologique détoxifiante. Respecte les écosystèmes aquatiques.',
    inci: 'AQUA/WATER, C12-15 ALKYL BENZOATE, SILICA, GLYCERIN, BIS-ETHYLHEXYLOXYPHENOL METHOXYPHENYL TRIAZINE, BUTYL METHOXYDIBENZOYLMETHANE, ETHYLHEXYL METHOXYCRYLENE, DIETHYLAMINO HYDROXYBENZOYL HEXYL BENZOATE, DIISOPROPYL SEBACATE, LAUROYL LYSINE, PROPANEDIOL, DICAPRYLYL CARBONATE, 1,2-HEXANEDIOL, POLYSORBATE 60, CETYL PHOSPHATE, ARGININE, BENTONITE, HYDROXYACETOPHENONE, FRAGRANCE, CITRIC ACID, ECTOIN, MANNITOL, METHOXYPHENYLIMINO DIMETHYLCYCLOHEXENYL ETHYL GLYCINATE, SODIUM PHYTATE, XANTHAN GUM, XYLITOL, RHAMNOSE, O-CYMEN-5-OL, BIOSACCHARIDE GUM-4, TRIMETHOXYBENZYL ACETYLSINAPATE, SODIUM HYALURONATE, TOCOPHEROL',
    url: 'https://www.bioderma.fr',
  },
  {
    name: 'Créaline H2O',
    brand: 'Bioderma',
    kind: 'skincare',
    unit: 'bottle',
    slug: BIODERMA_PRODUCT_SLUGS.BIODERMA_CREALINE_H2O,
    totalAmount: 250, // Hypothèse standard non spécifiée précisément dans le texte, mais prix 10€
    amountUnit: 'ml',
    priceCents: 1000,
    description:
      'Eau micellaire démaquillante originale pour peaux sensibles. Nettoie et apaise sans rinçage.',
    notes: 'Complexe breveté D.A.F. Micelles biomimétiques. Sans rinçage.',
    inci: 'AQUA/WATER, PEG-6 CAPRYLIC/CAPRIC GLYCERIDES, DISODIUM EDTA, CETRIMONIUM BROMIDE, PROPYLENE GLYCOL, CUCUMIS SATIVUS (CUCUMBER) FRUIT EXTRACT, FRUCTOOLIGOSACCHARIDES, MANNITOL, XYLITOL, RHAMNOSE',
    url: 'https://www.bioderma.fr',
  },
  {
    name: 'Cicabio Crème Réparatrice Apaisante',
    brand: 'Bioderma',
    kind: 'skincare',
    unit: 'tube',
    slug: BIODERMA_PRODUCT_SLUGS.BIODERMA_CICABIO_CREME,
    totalAmount: 100,
    amountUnit: 'ml',
    priceCents: 1299,
    description: 'Soin réparateur pour peaux irritées favorisant la reconstruction épidermique.',
    notes:
      'Complexe Cuivre-Zinc antibactérien. Actif Antalgicine contre le grattage. Texture film respirable.',
    inci: 'AQUA/WATER, GLYCERIN, ETHYLHEXYL PALMITATE, FRUCTOOLIGOSACCHARIDES, ZINC OXIDE, OCTYLDODECANOL, BUTYLENE GLYCOL, POLYACRYLAMIDE, MANNITOL, XYLITOL, RHAMNOSE, LAMINARIA OCHROLEUCA EXTRACT, COPPER SULFATE, ZINC SULFATE, SODIUM HYALURONATE, VITIS VINIFERA (GRAPE) VINE EXTRACT, ASIATICOSIDE, ASIATIC ACID, MADECCASSIC ACID, C13-14 ISOPARAFFIN, OCTYLDODECYL XYLOSIDE, PEG-30 DIPOLYHYDROXYSTEARATE, CAPRYLIC/CAPRIC TRIGLYCERIDE, LAURETH-7, LAURETH-3, HYDROXYETHYLCELLULOSE, ACETYL DIPEPTIDE-1 CETYL ESTER',
    url: 'https://www.bioderma.fr',
  },
  {
    name: 'Sébium Gel Moussant Nettoyant Purifiant',
    brand: 'Bioderma',
    kind: 'skincare',
    unit: 'pump',
    slug: BIODERMA_PRODUCT_SLUGS.BIODERMA_SEBIUM_GEL_MOUSSANT,
    totalAmount: 500,
    amountUnit: 'ml',
    priceCents: 1210,
    description:
      'Gel nettoyant purifiant pour peaux mixtes à grasses. Régule l’excès de sébum en douceur.',
    notes: 'Sulfates de zinc et cuivre. Base lavante douce sans savon. Fabriqué en France.',
    inci: 'AQUA/WATER, SODIUM COCOAMPHOACETATE, SODIUM LAURETH SULFATE, METHYLPROPANEDIOL, DISODIUM EDTA, MANNITOL, XYLITOL, RHAMNOSE, FRUCTOOLIGOSACCHARIDES, ZINC SULFATE, COPPER SULFATE, GINKGO BILOBA LEAF EXTRACT, PEG-90 GLYCERLY ISOSTEARATE, LACTIC ACID, LAURETH-2, POTASSIUM SORBATE, SODIUM CHLORIDE, PROPYLENE GLYCOL, SODIUM HYDROXIDE, FRAGRANCE',
    url: 'https://www.bioderma.fr',
  },
  {
    name: 'Atoderm Intensive gel-crème',
    brand: 'Bioderma',
    kind: 'skincare',
    unit: 'pump',
    slug: BIODERMA_PRODUCT_SLUGS.BIODERMA_ATODERM_INTENSIVE_GEL_CREME,
    totalAmount: 500,
    amountUnit: 'ml',
    priceCents: 2000,
    description:
      'Soin émollient frais ultra-léger pour peaux très sèches à atopiques. Absorption immédiate.',
    notes:
      'Catégorie Emollient PLUS. Technologie Skin Barrier Therapy. Enrichi en Niacinamide et Enoxolone.',
    inci: 'AQUA/WATER, GLYCERIN, NIACINAMIDE, SODIUM POLYACRYLATE, DIPOTASSIUM GLYCYRRHIZATE, HYDROGENATED POLYDECENE, PENTYLENE GLYCOL, 1,2-HEXANEDIOL, CAPRYLYL GLYCOL, MANNITOL, POLYSORBATE 20, XYLITOL, RHAMNOSE, SODIUM CITRATE, POLYQUATERNIUM-51, FRUCTOOLIGOSACCHARIDES, CAPRYLIC/CAPRIC TRIGLYCERIDE, LAMINARIA OCHROLEUCA EXTRACT',
    url: 'https://www.bioderma.fr',
  },
  {
    name: 'Atoderm Intensive eye',
    brand: 'Bioderma',
    kind: 'skincare',
    unit: 'tube',
    slug: BIODERMA_PRODUCT_SLUGS.BIODERMA_ATODERM_INTENSIVE_EYE,
    totalAmount: 100,
    amountUnit: 'ml',
    priceCents: 2200,
    description: 'Soin 3-en-1 pour paupières irritées : apaise, répare et démaquille.',
    notes:
      'Enoxolone anti-grattage. Complexe Lipigenium (céramides). Adapté porteurs de lentilles.',
    inci: 'AQUA/WATER, GLYCERIN, PARAFFINUM LIQUIDUM/MINERAL OIL, HELIANTHUS ANNUUS (SUNFLOWER) SEED OIL, DIPROPYLENE GLYCOL, BRASSICA CAMPESTRIS (RAPESEED) SEED OIL, HYDROXYETHYL ACRYLATE/SODIUM ACRYLOYLDIMETHYL TAURATE COPOLYMER, SUCROSE STEARATE, 1,2-HEXANEDIOL, GLYCYRRHETINIC ACID, SODIUM CITRATE, POLYSORBATE 60, SORBITAN ISOSTEARATE, MANNITOL, SODIUM LAUROYL LACTYLATE, XYLITOL, CITRIC ACID, PENTYLENE GLYCOL, RHAMNOSE, TOCOPHEROL, PHYTOSPHINGOSINE, CERAMIDE NP, SODIUM HYALURONATE, ETHYLHEXYLGLYCERIN, CERAMIDE AP, CHOLESTEROL, CARBOMER, XANTHAN GUM, FRUCTOOLIGOSACCHARIDES, CAPRYLIC/CAPRIC TRIGLYCERIDE, LAMINARIA OCHROLEUCA EXTRACT, CERAMIDE EOP',
    url: 'https://www.bioderma.fr',
  },
  {
    name: 'Atoderm Intensive baume',
    brand: 'Bioderma',
    kind: 'skincare',
    unit: 'pump',
    slug: BIODERMA_PRODUCT_SLUGS.BIODERMA_ATODERM_INTENSIVE_BAUME,
    totalAmount: 200,
    amountUnit: 'ml',
    priceCents: 1300,
    description: 'Soin relipidant et apaisant intensif pour peaux à tendance atopique.',
    notes: 'Actif PEA anti-démangeaisons. Technologie Skin Barrier Therapy. Complexe Lipigenium.',
    inci: 'AQUA/WATER, GLYCERIN, PARAFFINUM LIQUIDUM/MINERAL OIL, HELIANTHUS ANNUUS (SUNFLOWER) SEED OIL, BEHENYL ALCOHOL, SUCROSE STEARATE, CANOLA/CANOLA OIL, HYDROXYETHYL ACRYLATE/SODIUM ACRYLOYLDIMETHYL TAURATE COPOLYMER, PENTYLENE GLYCOL, BETA-SITOSTEROL, XYLITOL, ZINC GLUCONATE, ACRYLATES/C10-30 ALKYL ACRYLATE CROSSPOLYMER, PALMITAMIDE MEA, 1,2-HEXANEDIOL, CAPRYLYL GLYCOL, SODIUM CITRATE, MANNITOL, RHAMNOSE, SODIUM LAUROYL LACTYLATE, SODIUM HYDROXIDE, POLYSORBATE 60, SORBITAN ISOSTEARATE, TOCOPHEROL, PHYTOSPHINGOSINE, CERAMIDE NP, ETHYLHEXYLGLYCERIN, CERAMIDE AP, CHOLESTEROL, CARBOMER, XANTHAN GUM, FRUCTOOLIGOSACCHARIDES, CAPRYLIC/CAPRIC TRIGLYCERIDE, LAMINARIA OCHROLEUCA EXTRACT, CITRIC ACID, CERAMIDE EOP',
    url: 'https://www.bioderma.fr',
  },
  {
    name: 'Pigmentbio Sensitive Areas',
    brand: 'Bioderma',
    kind: 'skincare',
    unit: 'tube',
    slug: BIODERMA_PRODUCT_SLUGS.BIODERMA_PIGMENTBIO_SENSITIVE_AREAS,
    totalAmount: 75,
    amountUnit: 'ml',
    priceCents: 2299,
    description:
      "Crème éclaircissante pour zones sensibles et intimes sujettes à l'hyperpigmentation.",
    notes:
      'Cible les zones de frottement. Acide Azélaïque et Licorice. Peut être utilisé après rasage.',
    inci: 'AQUA/WATER, GLYCERIN, CETYL ALCOHOL, DIMETHICONE, POLYMETHYLSILSESQUIOXANE, DIPROPYLENE GLYCOL, PROPYLHEPTYL CAPRYLATE, CAPRYLIC/CAPRIC TRIGLYCERIDE, HDI/TRIMETHYLOL HEXYLLACTONE CROSSPOLYMER, C14-22 ALCOHOLS, PENTYLENE GLYCOL, CARBOMER, POLYSILICONE-11, CAPRYLYL GLYCOL, 1,2-HEXANEDIOL, AMMONIUM ACRYLOYLDIMETHYLTAURATE/VP COPOLYMER, BUTYLENE GLYCOL, DISODIUM EDTA, LYSINE, C12-20 ALKYL GLUCOSIDE, AZELAIC ACID, LAMINARIA OCHROLEUCA EXTRACT, MANNITOL, SALICYLIC ACID, XYLITOL, ANDROGRAPHIS PANICULATA LEAF EXTRACT, RHAMNOSE, SODIUM HYDROXIDE, GLYCYRRHIZA GLABRA (LICORICE) ROOT EXTRACT, DECYL GLUCOSIDE, FRUCTOOLIGOSACCHARIDES, TOCOPHEROL',
    url: 'https://www.bioderma.fr',
  },
  {
    name: 'Sébium Kerato+',
    brand: 'Bioderma',
    kind: 'skincare',
    unit: 'tube',
    slug: BIODERMA_PRODUCT_SLUGS.BIODERMA_SEBIUM_KERATO_PLUS,
    totalAmount: 30,
    amountUnit: 'ml',
    priceCents: 1200,
    description: 'Gel-crème anti-imperfections haute tolérance pour peaux acnéiques.',
    notes: "1.8% Acide Salicylique. 10% Ester d'Acide Malique. Technologie Fluidactiv.",
    inci: 'AQUA/WATER, DI-C12-13 ALKYL MALATE, PROPANEDIOL, PROPYLHEPTYL CAPRYLATE, GLYCERIN, SALICYLIC ACID, SODIUM POLYACRYLOYLDIMETHYL TAURATE, ARACHIDYL ALCOHOL, DIMETHICONE, CETEARYL ALCOHOL, BEHENYL ALCOHOL, COCO-GLUCOSIDE, ARACHIDYL GLUCOSIDE, SODIUM HYDROXIDE, SODIUM CITRATE, CHONDRUS CRISPUS EXTRACT, MANNITOL, PROPYL GALLATE, XYLITOL, FRAGRANCE, RHAMNOSE, SODIUM METABISULFITE, TOCOPHEROL',
    url: 'https://www.bioderma.fr',
  },
  {
    name: 'Sébium Hydra cleanser',
    brand: 'Bioderma',
    kind: 'skincare',
    unit: 'bottle',
    slug: BIODERMA_PRODUCT_SLUGS.BIODERMA_SEBIUM_HYDRA_CLEANSER,
    totalAmount: 200, // Contenance moyenne constatée pour ce type de produit Bioderma
    amountUnit: 'ml',
    priceCents: 1300,
    description:
      'Nettoyant apaisant et relipidant pour peaux grasses fragilisées par les traitements desséchants.',
    notes: 'Huile de karité. Glycérine. Complexe D.A.F. Nettoie tout en hydratant.',
    inci: 'AQUA/WATER, CAPRYLYL/CAPRYL GLUCOSIDE, BUTYROSPERMUM PARKII (SHEA) OIL, GLYCERIN, METHYLPROPANEDIOL, DISODIUM COCOYL GLUTAMATE, CITRIC ACID, PENTYLENE GLYCOL, SCLEROTIUM GUM, XANTHAN GUM, CAPRYLYL GLYCOL, PROPANEDIOL, SODIUM CITRATE, FRAGRANCE, MANNITOL, SACCHARIDE ISOMERATE, XYLITOL, BENZOTRIAZOLYL DODECYL P-CRESOL, RHAMNOSE, TOCOPHEROL, HELIANTHUS ANNUUS (SUNFLOWER) SEED OIL, AMINOETHANESULFINIC ACID, SODIUM METABISULFITE',
    url: 'https://www.bioderma.fr',
  },
  {
    name: 'Sébium H2O',
    brand: 'Bioderma',
    kind: 'skincare',
    unit: 'bottle',
    slug: BIODERMA_PRODUCT_SLUGS.BIODERMA_SEBIUM_H2O,
    totalAmount: 250,
    amountUnit: 'ml',
    priceCents: 1200,
    description:
      'Eau micellaire purifiante pour peaux mixtes à grasses. Nettoie et limite la sécrétion de sébum.',
    notes: 'Gluconate de Zinc et Sulfate de Cuivre. Technologie micellaire biomimétique.',
    inci: 'AQUA/WATER, PEG-6 CAPRYLIC/CAPRIC GLYCERIDES, SODIUM CITRATE, CITRIC ACID, DISODIUM EDTA, ZINC GLUCONATE, CETRIMONIUM BROMIDE, COPPER SULFATE, FRAGRANCE, FRUCTOOLIGOSACCHARIDES, MANNITOL, RHAMNOSE, XYLITOL, PROPYLENE GLYCOL, GINKGO BILOBA LEAF EXTRACT',
    url: 'https://www.bioderma.fr',
  },
  {
    name: 'Sébium Hydra',
    brand: 'Bioderma',
    kind: 'skincare',
    unit: 'tube',
    slug: BIODERMA_PRODUCT_SLUGS.BIODERMA_SEBIUM_HYDRA,
    totalAmount: 40, // Contenance standard tube Sébium Hydra
    amountUnit: 'ml',
    priceCents: 1300,
    description:
      'Soin réhydratant compensateur pour peaux à tendance acnéique sous traitements ultra-desséchants.',
    notes: "Céramide 3. Allantoïne apaisante. 24h d'hydratation.",
    inci: 'AQUA/WATER, GLYCERIN, PARAFFINUM LIQUIDUM/MINERAL OIL, ETHYLHEXYL PALMITATE, DIPROPYLENE GLYCOL, XYLITOL, BIS-PEG/PPG-16/16 PEG/PPG-16/16 DIMETHICONE, SODIUM ACRYLATE/SODIUM ACRYLOYLDIMETHYL TAURATE COPOLYMER, ISOHEXADECANE, CAPRYLIC/CAPRIC TRIGLYCERIDE, GLYCYRRHETINIC ACID, TOCOPHERYL ACETATE, POLYSORBATE 80, DISODIUM EDTA, ALLANTOIN, FRUCTOOLIGOSACCHARIDES, MANNITOL, PROPYLENE GLYCOL, CETRIMONIUM BROMIDE, CERAMIDE 3, FRAGRANCE, RHAMNOSE, GINKGO BILOBA LEAF EXTRACT, DODECYL GALLATE, LAMINARIA OCHROLEUCA EXTRACT',
    url: 'https://www.bioderma.fr',
  },
  {
    name: 'Sébium Sensitive',
    brand: 'Bioderma',
    kind: 'skincare',
    unit: 'tube',
    slug: BIODERMA_PRODUCT_SLUGS.BIODERMA_SEBIUM_SENSITIVE,
    totalAmount: 30, // Contenance standard Sébium Sensitive
    amountUnit: 'ml',
    priceCents: 1200,
    description: 'Soin apaisant et réhydratant pour peaux sensibles à tendance acnéique.',
    notes: 'Technologie Seborestore (Bakuchiol). Gluconate de Zinc séborégulateur. Glycérine.',
    inci: 'AQUA/WATER, GLYCERIN, METHYL METHACRYLATE CROSSPOLYMER, DIPROPYLENE GLYCOL, ZINC GLUCONATE, COCO-CAPRYLATE/CAPRATE, VINYL DIMETHICONE/METHICONE SILSESQUIOXANE CROSSPOLYMER, CAPRYLIC/CAPRIC TRIGLYCERIDE, ARACHIDYL ALCOHOL, BEHENYL ALCOHOL, POLYACRYLATE CROSSPOLYMER-6, SODIUM POLYACRYLATE, GLYCYRRHETINIC ACID, PROPYLENE GLYCOL, ARACHIDYL GLUCOSIDE, BAKUCHIOL, FRAGRANCE, LAMINARIA OCHROLEUCA EXTRACT, MANNITOL, XYLITOL, SODIUM METABISULFITE, RHAMNOSE, GINKGO BILOBA LEAF EXTRACT, TOCOPHEROL, FRUCTOOLIGOSACCHARIDES',
    url: 'https://www.bioderma.fr',
  },
  {
    name: 'Cicabio Crème+ SPF50+',
    brand: 'Bioderma',
    kind: 'sunscreen',
    unit: 'tube',
    slug: BIODERMA_PRODUCT_SLUGS.BIODERMA_CICABIO_CREME_PLUS_SPF50,
    totalAmount: 40,
    amountUnit: 'ml',
    priceCents: 1200,
    description:
      'Soin ultra-réparateur et protecteur anti-taches pour peaux abîmées exposées au soleil.',
    notes:
      'Complexe Réparation optimale (Acide Hyaluronique, Polyglutamique). Technologie Antalgicine.',
    inci: 'AQUA/WATER, DIETHYLHEXYL BUTAMIDO TRIAZONE, DICAPRYLYL CARBONATE, DIISOPROPYL SEBACATE, PROPANEDIOL, BUTYL METHOXYDIBENZOYLMETHANE, CORN STARCH MODIFIED, BIS-ETHYLHEXYLOXYPHENOL METHOXYPHENYL TRIAZINE, POLYGLYCERYL-6 STEARATE, DIETHYLAMINO HYDROXYBENZOYL HEXYL BENZOATE, DIBUTYL ADIPATE, ETHYLHEXYL TRIAZONE, BUTYLENE GLYCOL, PENTYLENE GLYCOL, XYLOSE, C20-22 ALKYL PHOSPHATE, C20-22 ALCOHOLS, MICROCRYSTALLINE CELLULOSE, GLYCERYL CAPRYLATE, SQUALANE, POLYGLYCERYL-6 BEHENATE, SODIUM POLYGLUTAMATE, POLYACRYLATE CROSSPOLYMER-6, SODIUM CITRATE, XANTHAN GUM, DIPALMITOYL HYDROXYPROLINE, SODIUM HYALURONATE, O-CYMEN-5-OL, MANNITOL, RHAMNOSE, XYLITOL, SODIUM HYDROXIDE, ACETYL DIPEPTIDE-1 CETYL ESTER, GLABRIDIN, TOCOPHEROL, FRUCTOOLIGOSACCHARIDES, PROPYLHEPTYL CAPRYLATE',
    url: 'https://www.bioderma.fr',
  },
  {
    name: 'Cicabio Baume Lavant',
    brand: 'Bioderma',
    kind: 'skincare',
    unit: 'tube',
    slug: BIODERMA_PRODUCT_SLUGS.BIODERMA_CICABIO_BAUME_LAVANT,
    totalAmount: 200,
    amountUnit: 'ml',
    priceCents: 1100,
    description: 'Nettoyant protecteur favorisant la cicatrisation des peaux abîmées et irritées.',
    notes: 'Gluconate de Zinc antibactérien. Huile de karité et squalane. Technologie Antalgicine.',
    inci: 'AQUA/WATER, CAPRYLYL/CAPRYL GLUCOSIDE, BUTYROSPERMUM PARKII (SHEA) OIL, GLYCERIN, METHYLPROPANEDIOL, DISODIUM COCOYL GLUTAMATE, PENTYLENE GLYCOL, SQUALANE, ACRYLATES/C10-30 ALKYL ACRYLATE CROSSPOLYMER, ZINC GLUCONATE, CAPRYLIC/CAPRIC TRIGLYCERIDE, XANTHAN GUM, CITRIC ACID, CAPRYLYL GLYCOL, BUTYLENE GLYCOL, PROPANEDIOL, SODIUM CITRATE, SACCHARIDE ISOMERATE, SODIUM HYDROXIDE, BENZOTRIAZOLYL DODECYL P-CRESOL, MANNITOL, RHAMNOSE, XYLITOL, TOCOPHEROL, HELIANTHUS ANNUUS (SUNFLOWER) SEED OIL, ACETYL DIPEPTIDE-1 CETYL ESTER, FRUCTOOLIGOSACCHARIDES',
    url: 'https://www.bioderma.fr',
  },
  {
    name: 'Cicabio Restor',
    brand: 'Bioderma',
    kind: 'skincare',
    unit: 'tube',
    slug: BIODERMA_PRODUCT_SLUGS.BIODERMA_CICABIO_RESTOR,
    totalAmount: 100,
    amountUnit: 'ml',
    priceCents: 1800,
    description:
      'Soin apaisant protecteur pour peaux fragilisées par les traitements anticancéreux.',
    notes: 'Panthénol et Acide Hyaluronique. Huile de Karité. Sans parfum.',
    inci: 'AQUA/WATER, BUTYROSPERMUM PARKII (SHEA) OIL, GLYCERIN, PANTHENOL, BUTYLENE GLYCOL, BEHENYL ALCOHOL, HYDROGENATED CASTOR OIL, PROPANEDIOL, JOJOBA ESTERS, CAPRYLOYL GLYCINE, SQUALANE, SUCROSE STEARATE, HELIANTHUS ANNUUS (SUNFLOWER) SEED WAX, PENTYLENE GLYCOL, SODIUM CITRATE, SUCROSE LAURATE, SODIUM POLYACRYLATE, POLYACRYLATE CROSSPOLYMER-6, XANTHAN GUM, SODIUM HYDROXIDE, POLYGLYCERIN-3, MANNITOL, SODIUM HYALURONATE, XYLITOL, RHAMNOSE, ACETYL DIPEPTIDE-1 CETYL ESTER, ACACIA DECURRENS FLOWER WAX',
    url: 'https://www.bioderma.fr',
  },
  {
    name: 'Cicabio Arnica+',
    brand: 'Bioderma',
    kind: 'skincare',
    unit: 'tube',
    slug: BIODERMA_PRODUCT_SLUGS.BIODERMA_CICABIO_ARNICA,
    totalAmount: 40,
    amountUnit: 'ml',
    priceCents: 900,
    description: 'Soin SOS décongestionnant pour peaux abîmées présentant des bleus ou des bosses.',
    notes: "Extrait d'Arnica Montana. Technologie Antalgicine. Zinc. Sans parfum.",
    inci: 'AQUA/WATER, GLYCERIN, DICAPRYLYL CARBONATE, CAPRYLIC/CAPRIC TRIGLYCERIDE, PROPYLENE GLYCOL, BEHENYL ALCOHOL, CAPRYLOYL GLYCINE, CETYL PALMITATE, ARACHIDYL ALCOHOL, SODIUM ACRYLATES COPOLYMER, TITANIUM DIOXIDE, HYDROGENATED POLYISOBUTENE, BUTYLENE GLYCOL, PENTYLENE GLYCOL, SODIUM CITRATE, HELIANTHUS ANNUUS (SUNFLOWER) SEED OIL, SODIUM HYDROXIDE, ARACHIDYL GLUCOSIDE, PHOSPHOLIPIDS, POLYGLYCERYL-10 STEARATE, ZINC SULFATE, APIGENIN, XANTHAN GUM, ARNICA MONTANA FLOWER EXTRACT, LAURETH-3, TOCOPHEROL, HYDROGENATED LECITHIN, LAMINARIA OCHROLEUCA EXTRACT, HYDROXYETHYLCELLULOSE, ACETYL DIPEPTIDE-1 CETYL ESTER, FRUCTOOLIGOSACCHARIDES, MANNITOL, XYLITOL, POTASSIUM SORBATE, RHAMNOSE',
    url: 'https://www.bioderma.fr',
  },
  {
    name: 'Cicabio Crème+',
    brand: 'Bioderma',
    kind: 'skincare',
    unit: 'tube',
    slug: BIODERMA_PRODUCT_SLUGS.BIODERMA_CICABIO_CREME_PLUS,
    totalAmount: 100,
    amountUnit: 'ml',
    priceCents: 1100,
    description:
      'Soin ultra-réparateur apaisant nouvelle génération qui restaure le microbiome cutané.',
    notes:
      'Complexe Réparation optimale (Acide polyglutamique, hyaluronique, xylose). Technologie Antalgicine.',
    inci: 'AQUA/WATER, CAPRYLIC/CAPRIC TRIGLYCERIDE, GLYCERIN, POLYGLYCERYL-3 POLYRICINOLEATE, BRASSICA CAMPESTRIS (RAPESEED) SEED OIL, BUTYLENE GLYCOL, TAPIOCA STARCH, HYDROGENATED RAPESEED OIL, XYLOSE, POLYGLYCERYL-3 DIISOSTEARATE, SIMMONDSIA CHINENSIS (JOJOBA) SEED OIL, MAGNESIUM SULFATE, PENTYLENE GLYCOL, SQUALANE, 1,2-HEXANEDIOL, CAPRYLYL GLYCOL, SODIUM POLYGLUTAMATE, SODIUM CITRATE, XANTHAN GUM, SODIUM HYALURONATE, TOCOPHEROL, MANNITOL, RHAMNOSE, XYLITOL, ACETYL DIPEPTIDE-1 CETYL ESTER, HELIANTHUS ANNUUS (SUNFLOWER) SEED OIL, CITRIC ACID, FRUCTOOLIGOSACCHARIDES',
    url: 'https://www.bioderma.fr',
  },
  {
    name: 'Créaline Gel moussant',
    brand: 'Bioderma',
    kind: 'skincare',
    unit: 'pump',
    slug: BIODERMA_PRODUCT_SLUGS.BIODERMA_CREALINE_GEL_MOUSSANT,
    totalAmount: 500,
    amountUnit: 'ml',
    priceCents: 1600,
    description: 'Gel nettoyant doux apaisant et hydratant pour peaux sensibles.',
    notes: 'Complexe breveté D.A.F. Relipidant. Sans savon. Sans parfum.',
    inci: 'AQUA/WATER, SODIUM COCOAMPHOACETATE, PROPANEDIOL, SODIUM LAUROYL SARCOSINATE, CITRIC ACID, COCO-GLUCOSIDE, GLYCERYL OLEATE, SODIUM CITRATE, PEG-90 GLYCERYL ISOSTEARATE, MANNITOL, XYLITOL, LAURETH-2, RHAMNOSE, FRUCTOOLIGOSACCHARIDES, TOCOPHEROL, HYDROGENATED PALM GLYCERIDES CITRATE',
    url: 'https://www.bioderma.fr',
  },
  {
    name: 'Créaline Fort',
    brand: 'Bioderma',
    kind: 'skincare',
    unit: 'tube',
    slug: BIODERMA_PRODUCT_SLUGS.BIODERMA_CREALINE_FORT,
    totalAmount: 40,
    amountUnit: 'ml',
    priceCents: 1700,
    description: 'Soin apaisant d’action rapide pour les peaux sensibles rougies et échauffées.',
    notes:
      'Enoxolone (Acide glycyrrhétinique). Allantoïne. Complexe D.A.F. Pour rougeurs mécaniques ou solaires.',
    inci: 'AQUA/WATER, PARAFFINUM LIQUIDUM/MINERAL OIL, DIPROPYLENE GLYCOL, CERA ALBA/BEESWAX, CETYL ALCOHOL, GLYCYRRHETINIC ACID, DICAPRYLYL CARBONATE, GLYCERYL STEARATE, PALMITIC ACID, STEARIC ACID, SORBITAN SESQUIOLEATE, PENTYLENE GLYCOL, TOCOPHEROL ACETATE, 1,2-HEXANEDIOL, CAPRYLYL GLYCOL, CARBOMER, ALLANTOIN, MANNITOL, XYLITOL, RHAMNOSE, SODIUM HYDROXIDE, SODIUM PCA, CAPRYLIC/CAPRIC TRIGLYCERIDE, FRUCTOOLIGOSACCHARIDES, TOCOPHEROL, LAMINARIA OCHROLEUCA EXTRACT',
    url: 'https://www.bioderma.fr',
  },
  {
    name: 'Créaline DS+ Crème',
    brand: 'Bioderma',
    kind: 'skincare',
    unit: 'tube',
    slug: BIODERMA_PRODUCT_SLUGS.BIODERMA_CREALINE_DS_PLUS,
    totalAmount: 40,
    amountUnit: 'ml',
    priceCents: 1400,
    description:
      'Soin apaisant et assainissant pour peaux sujettes aux rougeurs et squames (Dermite Séborrhéique).',
    notes:
      'Action anti-fongique (Piroctone Olamine, Climbazole). Acide glycyrrhétinique. Sans parfum.',
    inci: 'AQUA/WATER, COCOS NUCIFERA (COCONUT) OIL, PROPYLENE GLYCOL, CAPRYLIC/CAPRIC TRIGLYCERIDE, DIMETHICONE, GLYCYRRHETINIC ACID, SORBITAN SESQUIOLEATE, CETYL ALCOHOL, PHENOXYETHANOL, CARBOMER, SCLEROTIUM GUM, PIROCTONE OLAMINE, GLYCERYL UNDECYLENATE, UNDECYLENIC GLYCERIDES, CLIMBAZOLE, SODIUM HYDROXIDE, FRUCTOOLIGOSACCHARIDES, MANNITOL, XYLITOL, RHAMNOSE, LAMINARIA OCHROLEUCA EXTRACT',
    url: 'https://www.bioderma.fr',
  },
  {
    name: 'Créaline Défensive',
    brand: 'Bioderma',
    kind: 'skincare',
    unit: 'tube',
    slug: BIODERMA_PRODUCT_SLUGS.BIODERMA_CREALINE_DEFENSIVE,
    totalAmount: 40,
    amountUnit: 'ml',
    priceCents: 1700,
    description:
      'Crème active apaisante qui renforce le pouvoir d’autodéfense de la peau face aux agressions.',
    notes:
      'Technologie Défensive (Carnosine, Vitamine E). Polyphénols de Sauge Rouge. Texture légère.',
    inci: 'AQUA/WATER, GLYCERIN, DICAPRYLYL ETHER, PROPYLHEPTYL CAPRYLATE, BUTYLENE GLYCOL, GLYCERYL STEARATE CITRATE, GLYCOL PALMITATE, SQUALANE, SUCROSE STEARATE, MANGIFERA INDICA (MANGO) SEED BUTTER, PENTYLENE GLYCOL, ACRYLATES/C10-30 ALKYL ACRYLATE CROSSPOLYMER, CAPRYLYL GLYCOL, CARNOSINE, HYDROXYETHYL ACRYLATE/SODIUM ACRYLOYLDIMETHYL TAURATE COPOLYMER, MANNITOL, XYLITOL, TOCOPHEROL, SALVIA MILTIORRHIZA FLOWER/LEAF/ROOT EXTRACT, RHAMNOSE, GLYCINE SOJA (SOYBEAN) OIL, POLYSORBATE 60, SORBITAN ISOSTEARATE, PALMITOYL TETRAPEPTIDE-10',
    url: 'https://www.bioderma.fr',
  },
  {
    name: 'Créaline AR+ Crème',
    brand: 'Bioderma',
    kind: 'skincare',
    unit: 'pump',
    slug: BIODERMA_PRODUCT_SLUGS.BIODERMA_CREALINE_AR_PLUS,
    totalAmount: 40,
    amountUnit: 'ml',
    priceCents: 1800,
    description:
      'Soin anti-rougeurs intense qui réduit les rougeurs et prévient leur réapparition.',
    notes:
      'Technologie Rosactiv 2.0. Acide glycyrrhétinique. Phytosphingosine. Lipides biomimétiques.',
    inci: 'AQUA/WATER, GLYCERIN, C15-19 ALKANE, C10-18 TRIGLYCERIDES, DIPROPYLENE GLYCOL, GLYCERYL STEARATE CITRATE, HELIANTHUS ANNUUS (SUNFLOWER) SEED WAX, PENTYLENE GLYCOL, SQUALANE, SUCROSE STEARATE, CORN STARCH MODIFIED, COCOS NUCIFERA (COCONUT) OIL, MALTOOLIGOSYL GLUCOSIDE, GLYCERYL CAPRYLATE/CAPRATE, SCLEROTIUM GUM, GLYCYRRHETINIC ACID, HYDROGENATED STARCH HYDROLYSATE, XANTHAN GUM, 1-METHYLHYDANTOIN-2-IMIDE, PHYTOSPHINGOSINE, SODIUM CITRATE, CITRIC ACID, MANNITOL, XYLITOL, O-CYMEN-5-OL, BENZOTRIAZOLYL DODECYL P-CRESOL, RHAMNOSE, TOCOPHEROL, HELIANTHUS ANNUUS (SUNFLOWER) SEED OIL',
    url: 'https://www.bioderma.fr',
  },
  {
    name: 'Créaline Défensive riche',
    brand: 'Bioderma',
    kind: 'skincare',
    unit: 'tube',
    slug: BIODERMA_PRODUCT_SLUGS.BIODERMA_CREALINE_DEFENSIVE_RICHE,
    totalAmount: 40,
    amountUnit: 'ml',
    priceCents: 1600,
    description:
      'Soin apaisant riche pour peaux sensibles et sèches renforçant la barrière cutanée.',
    notes:
      'Technologie Défensive. Carnosine. Polyphénols de Sauge Rouge. Texture onctueuse et nourrissante.',
    inci: 'AQUA/WATER, GLYCERIN, DICAPRYLYL ETHER, GLYCOL PALMITATE, BUTYLENE GLYCOL, CETYL PALMITATE, GLYCERYL STEARATE CITRATE, SQUALANE, SUCROSE STEARATE, TRIDECYL TRIMELLITATE, GLYCERYL DIBEHENATE, POLYSORBATE 60, PENTYLENE GLYCOL, TRIBEHENIN, GLYCERYL BEHENATE, ACRYLATES/C10-30 ALKYL ACRYLATE CROSSPOLYMER, CAPRYLYL GLYCOL, CARNOSINE, HYDROXYETHYL ACRYLATE/SODIUM ACRYLOYLDIMETHYL TAURATE COPOLYMER, MANNITOL, XYLITOL, TOCOPHEROL, SALVIA MILTIORRHIZA FLOWER/LEAF/ROOT EXTRACT, RHAMNOSE, GLYCINE SOJA (SOYBEAN) OIL, SORBITAN ISOSTEARATE, SODIUM HYDROXIDE, PALMITOYL TETRAPEPTIDE-10',
    url: 'https://www.bioderma.fr',
  },
  {
    name: 'Cicabio Soin Réparateur Apaisant Isolant',
    brand: 'Bioderma',
    kind: 'skincare',
    unit: 'tube',
    slug: BIODERMA_PRODUCT_SLUGS.BIODERMA_CICABIO_SOIN_ISOLANT,
    totalAmount: 40,
    amountUnit: 'ml',
    priceCents: 849,
    description: 'Soin réparateur assainissant pour peaux agressées et asséchées.',
    notes: 'Synergie Résveratrol et Cuivre. Acide hyaluronique. Antalgicine. Texture nourrissante.',
    inci: 'AQUA/WATER, GLYCERIN, PARAFFINUM LIQUIDUM/MINERAL OIL, CAPRYLIC/CAPRIC TRIGLYCERIDE, FRUCTOOLIGOSACCHARIDES, POLYGLYCERYL-4 DIISOSTEARATE/POLYHYDROXYSTEARATE/SEBACATE, PROPANEDIOL, XYLITOL, ZINC STEARATE, SODIUM CITRATE, BUTYLENE GLYCOL, CAPRYLOYL GLYCINE, MANNITOL, RHAMNOSE, LAMINARIA OCHROLEUCA EXTRACT, COPPER SULFATE, ZINC SULFATE, SODIUM HYALURONATE, VITIS VINIFERA (GRAPE) VINE EXTRACT, LAURETH-3, ASIATICOSIDE, ASIATIC ACID, MADECCASSIC ACID, HYDROXYETHYLCELLULOSE, ACETYL DIPEPTIDE-1 CETYL ESTER, POTASSIUM SORBATE, SODIUM HYDROXIDE',
    url: 'https://www.bioderma.fr',
  },
]
