import { TAG_SLUGS } from '../../tags/seed-tags'
import { BIODERMA_PRODUCT_SLUGS } from './bioderma'

export const BIODERMA_PRODUCT_TAGS: { productSlug: string; tagSlug: string }[] = [
  // Créaline Defensive Riche (peaux sèches à très sèches, sensibles/sensibilisées, apaisante riche, hydratation 12h, renforce auto-défense/barrière)
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_CREALINE_DEFENSIVE_RICHE,
    tagSlug: TAG_SLUGS.PEAU_SENSIBLE,
  },
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_CREALINE_DEFENSIVE_RICHE,
    tagSlug: TAG_SLUGS.PEAU_SECHE,
  },
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_CREALINE_DEFENSIVE_RICHE,
    tagSlug: TAG_SLUGS.DESHYDRATATION,
  },
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_CREALINE_DEFENSIVE_RICHE,
    tagSlug: TAG_SLUGS.BARRIERE_CUTANEE,
  },
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_CREALINE_DEFENSIVE_RICHE,
    tagSlug: TAG_SLUGS.REPARATEUR,
  },
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_CREALINE_DEFENSIVE_RICHE,
    tagSlug: TAG_SLUGS.CREME_HYDRATANTE,
  },

  // Créaline Defensive Légère (peaux normales à mixtes, sensibles/sensibilisées, apaisante légère, même tech défensive, jour/sous maquillage)
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_CREALINE_DEFENSIVE_LEGERE,
    tagSlug: TAG_SLUGS.PEAU_SENSIBLE,
  },
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_CREALINE_DEFENSIVE_LEGERE,
    tagSlug: TAG_SLUGS.PEAU_MIXTE,
  },
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_CREALINE_DEFENSIVE_LEGERE,
    tagSlug: TAG_SLUGS.PEAU_NORMALE,
  },
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_CREALINE_DEFENSIVE_LEGERE,
    tagSlug: TAG_SLUGS.BARRIERE_CUTANEE,
  },
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_CREALINE_DEFENSIVE_LEGERE,
    tagSlug: TAG_SLUGS.CREME_HYDRATANTE,
  },

  // Cicabio Crème+ (ultra-réparateur, peaux abîmées/irritées/lésées, microbiome, effet pansement, apaisant, restauration barrière)
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_CICABIO_CREME_PLUS,
    tagSlug: TAG_SLUGS.REPARATEUR,
  },
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_CICABIO_CREME_PLUS,
    tagSlug: TAG_SLUGS.BARRIERE_CUTANEE,
  },
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_CICABIO_CREME_PLUS,
    tagSlug: TAG_SLUGS.PEAU_SENSIBLE,
  },
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_CICABIO_CREME_PLUS,
    tagSlug: TAG_SLUGS.CREME_HYDRATANTE,
  },
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_CICABIO_CREME_PLUS,
    tagSlug: TAG_SLUGS.ANTI_ROUGEURS,
  },

  // Sensibio AR+ (anti-rougeurs haute tolérance, Rosactiv™ 2.0, sans parfum, excellente base maquillage)
  { productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_SENSIBIO_AR, tagSlug: TAG_SLUGS.ANTI_ROUGEURS },
  { productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_SENSIBIO_AR, tagSlug: TAG_SLUGS.ROSACEE },
  { productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_SENSIBIO_AR, tagSlug: TAG_SLUGS.COUPEROSE },
  { productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_SENSIBIO_AR, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },
  { productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_SENSIBIO_AR, tagSlug: TAG_SLUGS.CREME_HYDRATANTE },
  { productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_SENSIBIO_AR, tagSlug: TAG_SLUGS.SANS_PARFUM },
  // Cicabio Crème+
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_ATODERM_HUILE_DOUCHE,
    tagSlug: TAG_SLUGS.NETTOYANT,
  },
  { productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_ATODERM_HUILE_DOUCHE, tagSlug: TAG_SLUGS.HUILE },
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_ATODERM_HUILE_DOUCHE,
    tagSlug: TAG_SLUGS.PEAU_SECHE,
  },
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_ATODERM_HUILE_DOUCHE,
    tagSlug: TAG_SLUGS.PEAU_ATOPIQUE,
  },
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_ATODERM_HUILE_DOUCHE,
    tagSlug: TAG_SLUGS.SANS_SAVON,
  },

  // Créaline Huile micellaire
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_CREALINE_HUILE_MICELLAIRE,
    tagSlug: TAG_SLUGS.NETTOYANT,
  },
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_CREALINE_HUILE_MICELLAIRE,
    tagSlug: TAG_SLUGS.HUILE,
  },
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_CREALINE_HUILE_MICELLAIRE,
    tagSlug: TAG_SLUGS.PEAU_SENSIBLE,
  },
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_CREALINE_HUILE_MICELLAIRE,
    tagSlug: TAG_SLUGS.PEAU_REACTIVE,
  },

  // Photoderm XDEFENSE SPF50+
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_PHOTODERM_XDEFENSE_SPF50,
    tagSlug: TAG_SLUGS.PROTECTION_SOLAIRE,
  },
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_PHOTODERM_XDEFENSE_SPF50,
    tagSlug: TAG_SLUGS.ANTI_OXYDANT,
  },
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_PHOTODERM_XDEFENSE_SPF50,
    tagSlug: TAG_SLUGS.PEAU_SENSIBLE,
  },

  // Créaline H2O
  { productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_CREALINE_H2O, tagSlug: TAG_SLUGS.NETTOYANT },
  { productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_CREALINE_H2O, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },
  { productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_CREALINE_H2O, tagSlug: TAG_SLUGS.SANS_PARFUM },

  // Cicabio Crème
  { productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_CICABIO_CREME, tagSlug: TAG_SLUGS.REPARATEUR },
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_CICABIO_CREME,
    tagSlug: TAG_SLUGS.BARRIERE_CUTANEE,
  },
  { productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_CICABIO_CREME, tagSlug: TAG_SLUGS.PEAU_REACTIVE },
  { productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_CICABIO_CREME, tagSlug: TAG_SLUGS.SANS_PARFUM },

  // Sébium Gel Moussant
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_SEBIUM_GEL_MOUSSANT,
    tagSlug: TAG_SLUGS.NETTOYANT,
  },
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_SEBIUM_GEL_MOUSSANT,
    tagSlug: TAG_SLUGS.PEAU_GRASSE,
  },
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_SEBIUM_GEL_MOUSSANT,
    tagSlug: TAG_SLUGS.PEAU_MIXTE,
  },
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_SEBIUM_GEL_MOUSSANT,
    tagSlug: TAG_SLUGS.SEBO_REGULATEUR,
  },
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_SEBIUM_GEL_MOUSSANT,
    tagSlug: TAG_SLUGS.SANS_SAVON,
  },

  // Atoderm Intensive gel-crème
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_ATODERM_INTENSIVE_GEL_CREME,
    tagSlug: TAG_SLUGS.CREME_HYDRATANTE,
  },
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_ATODERM_INTENSIVE_GEL_CREME,
    tagSlug: TAG_SLUGS.PEAU_ATOPIQUE,
  },
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_ATODERM_INTENSIVE_GEL_CREME,
    tagSlug: TAG_SLUGS.PEAU_SECHE,
  },
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_ATODERM_INTENSIVE_GEL_CREME,
    tagSlug: TAG_SLUGS.SANS_PARFUM,
  },

  // Atoderm Intensive eye
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_ATODERM_INTENSIVE_EYE,
    tagSlug: TAG_SLUGS.CONTOUR_YEUX,
  },
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_ATODERM_INTENSIVE_EYE,
    tagSlug: TAG_SLUGS.REPARATEUR,
  },
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_ATODERM_INTENSIVE_EYE,
    tagSlug: TAG_SLUGS.PEAU_ATOPIQUE,
  },
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_ATODERM_INTENSIVE_EYE,
    tagSlug: TAG_SLUGS.SANS_PARFUM,
  },

  // Atoderm Intensive baume
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_ATODERM_INTENSIVE_BAUME,
    tagSlug: TAG_SLUGS.CREME_HYDRATANTE,
  },
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_ATODERM_INTENSIVE_BAUME,
    tagSlug: TAG_SLUGS.EMOLLIENT,
  },
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_ATODERM_INTENSIVE_BAUME,
    tagSlug: TAG_SLUGS.PEAU_ATOPIQUE,
  },
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_ATODERM_INTENSIVE_BAUME,
    tagSlug: TAG_SLUGS.SANS_PARFUM,
  },

  // Pigmentbio Sensitive Areas
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_PIGMENTBIO_SENSITIVE_AREAS,
    tagSlug: TAG_SLUGS.ANTI_TACHES,
  },
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_PIGMENTBIO_SENSITIVE_AREAS,
    tagSlug: TAG_SLUGS.HYPERPIGMENTATION,
  },
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_PIGMENTBIO_SENSITIVE_AREAS,
    tagSlug: TAG_SLUGS.PEAU_SENSIBLE,
  },

  // Sébium Kerato+
  { productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_SEBIUM_KERATO_PLUS, tagSlug: TAG_SLUGS.ANTI_ACNE },
  { productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_SEBIUM_KERATO_PLUS, tagSlug: TAG_SLUGS.EXFOLIANT },
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_SEBIUM_KERATO_PLUS,
    tagSlug: TAG_SLUGS.KERATOLYTIQUE,
  },
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_SEBIUM_KERATO_PLUS,
    tagSlug: TAG_SLUGS.PEAU_GRASSE,
  },

  // Sébium Hydra cleanser
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_SEBIUM_HYDRA_CLEANSER,
    tagSlug: TAG_SLUGS.NETTOYANT,
  },
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_SEBIUM_HYDRA_CLEANSER,
    tagSlug: TAG_SLUGS.PEAU_REACTIVE,
  },
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_SEBIUM_HYDRA_CLEANSER,
    tagSlug: TAG_SLUGS.POST_ACNE,
  },

  // Sébium H2O
  { productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_SEBIUM_H2O, tagSlug: TAG_SLUGS.NETTOYANT },
  { productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_SEBIUM_H2O, tagSlug: TAG_SLUGS.PEAU_GRASSE },
  { productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_SEBIUM_H2O, tagSlug: TAG_SLUGS.SEBO_REGULATEUR },

  // Sébium Hydra
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_SEBIUM_HYDRA,
    tagSlug: TAG_SLUGS.CREME_HYDRATANTE,
  },
  { productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_SEBIUM_HYDRA, tagSlug: TAG_SLUGS.DESHYDRATATION },
  { productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_SEBIUM_HYDRA, tagSlug: TAG_SLUGS.POST_ACNE },

  // Sébium Sensitive
  { productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_SEBIUM_SENSITIVE, tagSlug: TAG_SLUGS.ANTI_ACNE },
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_SEBIUM_SENSITIVE,
    tagSlug: TAG_SLUGS.PEAU_SENSIBLE,
  },
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_SEBIUM_SENSITIVE,
    tagSlug: TAG_SLUGS.ANTI_ROUGEURS,
  },

  // Cicabio Crème+ SPF50+
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_CICABIO_CREME_PLUS_SPF50,
    tagSlug: TAG_SLUGS.PROTECTION_SOLAIRE,
  },
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_CICABIO_CREME_PLUS_SPF50,
    tagSlug: TAG_SLUGS.REPARATEUR,
  },
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_CICABIO_CREME_PLUS_SPF50,
    tagSlug: TAG_SLUGS.ANTI_TACHES,
  },

  // Cicabio Baume Lavant
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_CICABIO_BAUME_LAVANT,
    tagSlug: TAG_SLUGS.NETTOYANT,
  },
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_CICABIO_BAUME_LAVANT,
    tagSlug: TAG_SLUGS.REPARATEUR,
  },
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_CICABIO_BAUME_LAVANT,
    tagSlug: TAG_SLUGS.SANS_SAVON,
  },

  // Cicabio Restor
  { productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_CICABIO_RESTOR, tagSlug: TAG_SLUGS.REPARATEUR },
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_CICABIO_RESTOR,
    tagSlug: TAG_SLUGS.BARRIERE_CUTANEE,
  },
  { productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_CICABIO_RESTOR, tagSlug: TAG_SLUGS.SANS_PARFUM },

  // Cicabio Arnica+
  { productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_CICABIO_ARNICA, tagSlug: TAG_SLUGS.REPARATEUR },
  { productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_CICABIO_ARNICA, tagSlug: TAG_SLUGS.PEAU_REACTIVE },

  // Cicabio Crème+
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_CICABIO_CREME_PLUS,
    tagSlug: TAG_SLUGS.REPARATEUR,
  },
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_CICABIO_CREME_PLUS,
    tagSlug: TAG_SLUGS.BARRIERE_CUTANEE,
  },
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_CICABIO_CREME_PLUS,
    tagSlug: TAG_SLUGS.SANS_PARFUM,
  },

  // Créaline Gel moussant
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_CREALINE_GEL_MOUSSANT,
    tagSlug: TAG_SLUGS.NETTOYANT,
  },
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_CREALINE_GEL_MOUSSANT,
    tagSlug: TAG_SLUGS.PEAU_SENSIBLE,
  },
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_CREALINE_GEL_MOUSSANT,
    tagSlug: TAG_SLUGS.SANS_SAVON,
  },

  // Créaline Fort
  { productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_CREALINE_FORT, tagSlug: TAG_SLUGS.ANTI_ROUGEURS },
  { productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_CREALINE_FORT, tagSlug: TAG_SLUGS.PEAU_REACTIVE },
  { productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_CREALINE_FORT, tagSlug: TAG_SLUGS.FLUSHS },

  // Créaline DS+ Crème
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_CREALINE_DS_PLUS,
    tagSlug: TAG_SLUGS.ANTI_ROUGEURS,
  },
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_CREALINE_DS_PLUS,
    tagSlug: TAG_SLUGS.PEAU_SENSIBLE,
  },
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_CREALINE_DS_PLUS,
    tagSlug: TAG_SLUGS.ANTISEPTIQUE,
  },

  // Créaline Défensive
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_CREALINE_DEFENSIVE,
    tagSlug: TAG_SLUGS.CREME_HYDRATANTE,
  },
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_CREALINE_DEFENSIVE,
    tagSlug: TAG_SLUGS.PEAU_REACTIVE,
  },
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_CREALINE_DEFENSIVE,
    tagSlug: TAG_SLUGS.BARRIERE_CUTANEE,
  },

  // Créaline AR+ Crème
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_CREALINE_AR_PLUS,
    tagSlug: TAG_SLUGS.ANTI_ROUGEURS,
  },
  { productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_CREALINE_AR_PLUS, tagSlug: TAG_SLUGS.ROSACEE },
  { productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_CREALINE_AR_PLUS, tagSlug: TAG_SLUGS.COUPEROSE },
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_CREALINE_AR_PLUS,
    tagSlug: TAG_SLUGS.CREME_HYDRATANTE,
  },

  // Créaline Défensive riche
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_CREALINE_DEFENSIVE_RICHE,
    tagSlug: TAG_SLUGS.CREME_HYDRATANTE,
  },
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_CREALINE_DEFENSIVE_RICHE,
    tagSlug: TAG_SLUGS.PEAU_SECHE,
  },
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_CREALINE_DEFENSIVE_RICHE,
    tagSlug: TAG_SLUGS.PEAU_SENSIBLE,
  },

  // Cicabio Soin Réparateur Isolant
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_CICABIO_SOIN_ISOLANT,
    tagSlug: TAG_SLUGS.REPARATEUR,
  },
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_CICABIO_SOIN_ISOLANT,
    tagSlug: TAG_SLUGS.OCCLUSIF,
  },
  {
    productSlug: BIODERMA_PRODUCT_SLUGS.BIODERMA_CICABIO_SOIN_ISOLANT,
    tagSlug: TAG_SLUGS.PEAU_REACTIVE,
  },
]
