import { TAG_SLUGS } from '../../tags/seed-tags'
import { SVR_PRODUCT_SLUGS } from './svr'

export const SVR_PRODUCT_TAGS: { productSlug: string; tagSlug: string }[] = [
  {
    productSlug: SVR_PRODUCT_SLUGS.SVR_TOPIALYSE_GEL_LAVANT,
    tagSlug: TAG_SLUGS.NETTOYANT,
  },
  {
    productSlug: SVR_PRODUCT_SLUGS.SVR_TOPIALYSE_GEL_LAVANT,
    tagSlug: TAG_SLUGS.SANS_SAVON,
  },
  // --- Xérial 30 Gel-Crème ---
  {
    productSlug: SVR_PRODUCT_SLUGS.SVR_XERIAL_30_GEL_CREME,
    tagSlug: TAG_SLUGS.KERATOLYTIQUE,
  },
  {
    productSlug: SVR_PRODUCT_SLUGS.SVR_XERIAL_30_GEL_CREME,
    tagSlug: TAG_SLUGS.PEAU_SECHE,
  },
  // --- Ampoule A Lift ---
  {
    productSlug: SVR_PRODUCT_SLUGS.SVR_AMPOULE_A_LIFT,
    tagSlug: TAG_SLUGS.SERUM,
  },
  {
    productSlug: SVR_PRODUCT_SLUGS.SVR_AMPOULE_A_LIFT,
    tagSlug: TAG_SLUGS.ANTI_AGE,
  },
  // --- Sebiaclear Ampoule Flash ---
  {
    productSlug: SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_FLASH_15,
    tagSlug: TAG_SLUGS.ANTI_ACNE,
  },

  {
    productSlug: SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_FLASH_15,
    tagSlug: TAG_SLUGS.COUPEROSE,
  },
  {
    productSlug: SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_FLASH_15,
    tagSlug: TAG_SLUGS.ANTI_ACNE,
  },
  {
    productSlug: SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_FLASH_15,
    tagSlug: TAG_SLUGS.ANTI_TACHES,
  },
  {
    productSlug: SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_FLASH_15,
    tagSlug: TAG_SLUGS.ANTI_ROUGEURS,
  },

  {
    productSlug: SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_FLASH_15,
    tagSlug: TAG_SLUGS.HYPERPIGMENTATION,
  },
  {
    productSlug: SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_FLASH_15,
    tagSlug: TAG_SLUGS.ROSACEE,
  },
  // ─── Topialyse Baume Lavant Apaisant ───
  {
    productSlug: SVR_PRODUCT_SLUGS.SVR_TOPIALYSE_BAUME_LAVANT,
    tagSlug: TAG_SLUGS.NETTOYANT,
  },
  {
    productSlug: SVR_PRODUCT_SLUGS.SVR_TOPIALYSE_BAUME_LAVANT,
    tagSlug: TAG_SLUGS.PEAU_ATOPIQUE,
  },
  {
    productSlug: SVR_PRODUCT_SLUGS.SVR_TOPIALYSE_BAUME_LAVANT,
    tagSlug: TAG_SLUGS.SANS_SAVON,
  },

  // ─── Topialyse Concentré Lavant Pâte à Mousser ───
  {
    productSlug: SVR_PRODUCT_SLUGS.SVR_TOPIALYSE_GEL_LAVANT,
    tagSlug: TAG_SLUGS.NETTOYANT,
  },
  {
    productSlug: SVR_PRODUCT_SLUGS.SVR_TOPIALYSE_GEL_LAVANT,
    tagSlug: TAG_SLUGS.PEAU_SECHE,
  },
  {
    productSlug: SVR_PRODUCT_SLUGS.SVR_TOPIALYSE_GEL_LAVANT,
    tagSlug: TAG_SLUGS.BARRIERE_CUTANEE,
  },

  // ─── Topialyse Barrière Crème Isolante ───
  {
    productSlug: SVR_PRODUCT_SLUGS.SVR_TOPIALYSE_BARRIERE,
    tagSlug: TAG_SLUGS.BARRIERE_CUTANEE,
  },
  {
    productSlug: SVR_PRODUCT_SLUGS.SVR_TOPIALYSE_BARRIERE,
    tagSlug: TAG_SLUGS.REPARATEUR,
  },
  {
    productSlug: SVR_PRODUCT_SLUGS.SVR_TOPIALYSE_BARRIERE,
    tagSlug: TAG_SLUGS.OCCLUSIF,
  },

  // ─── Topialyse Mains Nourrissant ───
  {
    productSlug: SVR_PRODUCT_SLUGS.SVR_TOPIALYSE_MAINS,
    tagSlug: TAG_SLUGS.PEAU_SECHE,
  },
  {
    productSlug: SVR_PRODUCT_SLUGS.SVR_TOPIALYSE_MAINS,
    tagSlug: TAG_SLUGS.CREME_HYDRATANTE,
  },

  // ─── Xérial 50 Extrême Crème Pieds ───
  {
    productSlug: SVR_PRODUCT_SLUGS.SVR_XERIAL_50_EXTREME_PIEDS,
    tagSlug: TAG_SLUGS.KERATOLYTIQUE,
  },
  {
    productSlug: SVR_PRODUCT_SLUGS.SVR_XERIAL_50_EXTREME_PIEDS,
    tagSlug: TAG_SLUGS.EXFOLIANT,
  },
  {
    productSlug: SVR_PRODUCT_SLUGS.SVR_XERIAL_50_EXTREME_PIEDS,
    tagSlug: TAG_SLUGS.PEAU_SECHE,
  },

  // ─── Xérial Fissures & Crevasses Réparateur ───
  {
    productSlug: SVR_PRODUCT_SLUGS.SVR_XERIAL_FISSURES_CREVASSES,
    tagSlug: TAG_SLUGS.REPARATEUR,
  },
  {
    productSlug: SVR_PRODUCT_SLUGS.SVR_XERIAL_FISSURES_CREVASSES,
    tagSlug: TAG_SLUGS.BARRIERE_CUTANEE,
  },

  // ─── Xérial DM Psoriasis ───
  {
    productSlug: SVR_PRODUCT_SLUGS.SVR_XERIAL_DM_PSORIASIS,
    tagSlug: TAG_SLUGS.KERATOLYTIQUE,
  },
  {
    productSlug: SVR_PRODUCT_SLUGS.SVR_XERIAL_DM_PSORIASIS,
    tagSlug: TAG_SLUGS.PEAU_ATOPIQUE,
  },

  // ─── Xérial 30 Crème Pieds Quotidien ───
  {
    productSlug: SVR_PRODUCT_SLUGS.SVR_XERIAL_30_PIEDS,
    tagSlug: TAG_SLUGS.KERATOLYTIQUE,
  },
  {
    productSlug: SVR_PRODUCT_SLUGS.SVR_XERIAL_30_PIEDS,
    tagSlug: TAG_SLUGS.EMOLLIENT,
  },
  // Sensifine AR (spécifique rougeurs + sensible)
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SENSIFINE_AR_SPF50, tagSlug: TAG_SLUGS.ANTI_ROUGEURS },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SENSIFINE_AR_SPF50, tagSlug: TAG_SLUGS.ROSACEE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SENSIFINE_AR_SPF50, tagSlug: TAG_SLUGS.COUPEROSE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SENSIFINE_AR_SPF50, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SENSIFINE_AR_SPF50, tagSlug: TAG_SLUGS.PROTECTION_SOLAIRE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SENSIFINE_AR_SPF50, tagSlug: TAG_SLUGS.CREME_HYDRATANTE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SENSIFINE_AR_SPF50, tagSlug: TAG_SLUGS.SANS_PARFUM },

  { productSlug: SVR_PRODUCT_SLUGS.SVR_SENSIFINE_AR, tagSlug: TAG_SLUGS.ANTI_ROUGEURS },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SENSIFINE_AR, tagSlug: TAG_SLUGS.ROSACEE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SENSIFINE_AR, tagSlug: TAG_SLUGS.COUPEROSE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SENSIFINE_AR, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SENSIFINE_AR, tagSlug: TAG_SLUGS.PEAU_REACTIVE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SENSIFINE_AR, tagSlug: TAG_SLUGS.CREME_HYDRATANTE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SENSIFINE_AR, tagSlug: TAG_SLUGS.PIGMENTS_VERTS },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SENSIFINE_AR, tagSlug: TAG_SLUGS.SANS_PARFUM },

  { productSlug: SVR_PRODUCT_SLUGS.SVR_SENSIFINE_EXTREME, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SENSIFINE_EXTREME, tagSlug: TAG_SLUGS.PEAU_REACTIVE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SENSIFINE_EXTREME, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SENSIFINE_EXTREME, tagSlug: TAG_SLUGS.REPARATEUR },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SENSIFINE_EXTREME, tagSlug: TAG_SLUGS.CREME_HYDRATANTE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SENSIFINE_EXTREME, tagSlug: TAG_SLUGS.SANS_PARFUM },

  { productSlug: SVR_PRODUCT_SLUGS.SVR_SENSIFINE_HUILE_NUIT, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SENSIFINE_HUILE_NUIT, tagSlug: TAG_SLUGS.PEAU_REACTIVE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SENSIFINE_HUILE_NUIT, tagSlug: TAG_SLUGS.SOIN_DE_NUIT },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SENSIFINE_HUILE_NUIT, tagSlug: TAG_SLUGS.HUILE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SENSIFINE_HUILE_NUIT, tagSlug: TAG_SLUGS.REPARATEUR },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SENSIFINE_HUILE_NUIT, tagSlug: TAG_SLUGS.SANS_PARFUM },

  { productSlug: SVR_PRODUCT_SLUGS.SVR_SENSIFINE_MASQUE_SOS, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SENSIFINE_MASQUE_SOS, tagSlug: TAG_SLUGS.PEAU_REACTIVE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SENSIFINE_MASQUE_SOS, tagSlug: TAG_SLUGS.MASQUE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SENSIFINE_MASQUE_SOS, tagSlug: TAG_SLUGS.FLUSHS },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SENSIFINE_MASQUE_SOS, tagSlug: TAG_SLUGS.SANS_PARFUM },

  { productSlug: SVR_PRODUCT_SLUGS.SVR_SENSIFINE_NUTRI_BAUME, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SENSIFINE_NUTRI_BAUME, tagSlug: TAG_SLUGS.PEAU_SECHE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SENSIFINE_NUTRI_BAUME, tagSlug: TAG_SLUGS.CREME_HYDRATANTE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SENSIFINE_NUTRI_BAUME, tagSlug: TAG_SLUGS.COUPEROSE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SENSIFINE_NUTRI_BAUME, tagSlug: TAG_SLUGS.SANS_PARFUM },

  {
    productSlug: SVR_PRODUCT_SLUGS.SVR_SENSIFINE_BAUME_DEMAQUILLANT,
    tagSlug: TAG_SLUGS.PEAU_SENSIBLE,
  },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SENSIFINE_BAUME_DEMAQUILLANT, tagSlug: TAG_SLUGS.NETTOYANT },
  {
    productSlug: SVR_PRODUCT_SLUGS.SVR_SENSIFINE_BAUME_DEMAQUILLANT,
    tagSlug: TAG_SLUGS.SANS_SAVON,
  },
  {
    productSlug: SVR_PRODUCT_SLUGS.SVR_SENSIFINE_BAUME_DEMAQUILLANT,
    tagSlug: TAG_SLUGS.SANS_PARFUM,
  },

  { productSlug: SVR_PRODUCT_SLUGS.SVR_SENSIFINE_AQUA_GEL, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SENSIFINE_AQUA_GEL, tagSlug: TAG_SLUGS.PEAU_NORMALE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SENSIFINE_AQUA_GEL, tagSlug: TAG_SLUGS.CREME_HYDRATANTE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SENSIFINE_AQUA_GEL, tagSlug: TAG_SLUGS.SANS_PARFUM },

  {
    productSlug: SVR_PRODUCT_SLUGS.SVR_SENSIFINE_DERMO_NETTOYANT,
    tagSlug: TAG_SLUGS.PEAU_SENSIBLE,
  },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SENSIFINE_DERMO_NETTOYANT, tagSlug: TAG_SLUGS.NETTOYANT },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SENSIFINE_DERMO_NETTOYANT, tagSlug: TAG_SLUGS.SANS_PARFUM },

  { productSlug: SVR_PRODUCT_SLUGS.SVR_SENSIFINE_HYDRA_CREME, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SENSIFINE_HYDRA_CREME, tagSlug: TAG_SLUGS.PEAU_SECHE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SENSIFINE_HYDRA_CREME, tagSlug: TAG_SLUGS.CREME_HYDRATANTE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SENSIFINE_HYDRA_CREME, tagSlug: TAG_SLUGS.SANS_PARFUM },

  // Topialyse (focus peaux sèches/atopiques, relipidant, barrière)
  { productSlug: SVR_PRODUCT_SLUGS.SVR_TOPIALYSE_BAUME_PROTECT, tagSlug: TAG_SLUGS.PEAU_SECHE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_TOPIALYSE_BAUME_PROTECT, tagSlug: TAG_SLUGS.PEAU_ATOPIQUE },
  {
    productSlug: SVR_PRODUCT_SLUGS.SVR_TOPIALYSE_BAUME_PROTECT,
    tagSlug: TAG_SLUGS.BARRIERE_CUTANEE,
  },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_TOPIALYSE_BAUME_PROTECT, tagSlug: TAG_SLUGS.REPARATEUR },
  {
    productSlug: SVR_PRODUCT_SLUGS.SVR_TOPIALYSE_BAUME_PROTECT,
    tagSlug: TAG_SLUGS.CREME_HYDRATANTE,
  },

  { productSlug: SVR_PRODUCT_SLUGS.SVR_TOPIALYSE_CREME, tagSlug: TAG_SLUGS.PEAU_SECHE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_TOPIALYSE_CREME, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_TOPIALYSE_CREME, tagSlug: TAG_SLUGS.CREME_HYDRATANTE },

  { productSlug: SVR_PRODUCT_SLUGS.SVR_TOPIALYSE_HUILE_LAVANTE, tagSlug: TAG_SLUGS.PEAU_SECHE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_TOPIALYSE_HUILE_LAVANTE, tagSlug: TAG_SLUGS.PEAU_ATOPIQUE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_TOPIALYSE_HUILE_LAVANTE, tagSlug: TAG_SLUGS.NETTOYANT },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_TOPIALYSE_HUILE_LAVANTE, tagSlug: TAG_SLUGS.HUILE },

  // ... (tu peux continuer pour les autres Topialyse, Xerial, etc., sur le même principe : peau sèche/atopique pour Topialyse, très sèche/urée/kératolytique pour Xerial, etc.)
  // Par exemple pour Xerial :
  { productSlug: SVR_PRODUCT_SLUGS.SVR_XERIAL_10_LAIT, tagSlug: TAG_SLUGS.PEAU_SECHE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_XERIAL_10_LAIT, tagSlug: TAG_SLUGS.DESHYDRATATION },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_XERIAL_10_LAIT, tagSlug: TAG_SLUGS.CREME_HYDRATANTE },

  // [C20] Biotic Regenerating Radiance Cream (et variantes [C20] Biotic / Fluide)
  { productSlug: SVR_PRODUCT_SLUGS.SVR_C20_BIOTIC, tagSlug: TAG_SLUGS.ECLAT },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_C20_BIOTIC, tagSlug: TAG_SLUGS.ANTI_AGE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_C20_BIOTIC, tagSlug: TAG_SLUGS.ANTI_OXYDANT },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_C20_BIOTIC, tagSlug: TAG_SLUGS.DESHYDRATATION },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_C20_BIOTIC, tagSlug: TAG_SLUGS.CREME_HYDRATANTE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_C20_BIOTIC, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },

  { productSlug: SVR_PRODUCT_SLUGS.SVR_C20_FLUIDE, tagSlug: TAG_SLUGS.ECLAT },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_C20_FLUIDE, tagSlug: TAG_SLUGS.ANTI_OXYDANT },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_C20_FLUIDE, tagSlug: TAG_SLUGS.ANTI_AGE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_C20_FLUIDE, tagSlug: TAG_SLUGS.CREME_HYDRATANTE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_C20_FLUIDE, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },

  // Cicavit+ Crème HPPI (réparatrice, anti-marques, apaisante)
  { productSlug: SVR_PRODUCT_SLUGS.SVR_CICAVIT_PLUS_CREME_HPPI, tagSlug: TAG_SLUGS.REPARATEUR },
  {
    productSlug: SVR_PRODUCT_SLUGS.SVR_CICAVIT_PLUS_CREME_HPPI,
    tagSlug: TAG_SLUGS.BARRIERE_CUTANEE,
  },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_CICAVIT_PLUS_CREME_HPPI, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_CICAVIT_PLUS_CREME_HPPI, tagSlug: TAG_SLUGS.ANTI_ROUGEURS },
  {
    productSlug: SVR_PRODUCT_SLUGS.SVR_CICAVIT_PLUS_CREME_HPPI,
    tagSlug: TAG_SLUGS.CREME_HYDRATANTE,
  },

  // Sebiaclear Gel Flash 4H (localisé anti-imperfections)
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_GEL_FLASH_4H, tagSlug: TAG_SLUGS.ANTI_ACNE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_GEL_FLASH_4H, tagSlug: TAG_SLUGS.POST_ACNE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_GEL_FLASH_4H, tagSlug: TAG_SLUGS.PEAU_GRASSE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_GEL_FLASH_4H, tagSlug: TAG_SLUGS.PEAU_MIXTE },

  // Sebiaclear Spray Corps (imperfections corps)
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_SPRAY_CORPS, tagSlug: TAG_SLUGS.ANTI_ACNE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_SPRAY_CORPS, tagSlug: TAG_SLUGS.POST_ACNE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_SPRAY_CORPS, tagSlug: TAG_SLUGS.PEAU_GRASSE },

  // Sebiaclear Micro-Peel (lotion exfoliante douce)
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_MICRO_PEEL, tagSlug: TAG_SLUGS.ANTI_ACNE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_MICRO_PEEL, tagSlug: TAG_SLUGS.PORES_DILATES },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_MICRO_PEEL, tagSlug: TAG_SLUGS.EXFOLIANT },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_MICRO_PEEL, tagSlug: TAG_SLUGS.PEAU_GRASSE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_MICRO_PEEL, tagSlug: TAG_SLUGS.PEAU_MIXTE },

  // Sebiaclear Gel Moussant (nettoyant purifiant)
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_GEL_MOUSSANT, tagSlug: TAG_SLUGS.ANTI_ACNE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_GEL_MOUSSANT, tagSlug: TAG_SLUGS.NETTOYANT },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_GEL_MOUSSANT, tagSlug: TAG_SLUGS.SANS_SAVON },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_GEL_MOUSSANT, tagSlug: TAG_SLUGS.PEAU_GRASSE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_GEL_MOUSSANT, tagSlug: TAG_SLUGS.PEAU_MIXTE },

  // Sebiaclear Sérum (anti-imperfections + anti-rides adultes)
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_SERUM, tagSlug: TAG_SLUGS.ANTI_ACNE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_SERUM, tagSlug: TAG_SLUGS.ANTI_AGE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_SERUM, tagSlug: TAG_SLUGS.SERUM },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_SERUM, tagSlug: TAG_SLUGS.POST_ACNE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_SERUM, tagSlug: TAG_SLUGS.PEAU_GRASSE },

  // Sebiaclear Crème Lavante (nettoyant apaisant acné déshydratée)
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_CREME_LAVANTE, tagSlug: TAG_SLUGS.ANTI_ACNE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_CREME_LAVANTE, tagSlug: TAG_SLUGS.NETTOYANT },
  {
    productSlug: SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_CREME_LAVANTE,
    tagSlug: TAG_SLUGS.DESHYDRATATION,
  },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_CREME_LAVANTE, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },

  // Sebiaclear Hydra (crème réparatrice acné sous traitement)
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_HYDRA, tagSlug: TAG_SLUGS.ANTI_ACNE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_HYDRA, tagSlug: TAG_SLUGS.REPARATEUR },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_HYDRA, tagSlug: TAG_SLUGS.CREME_HYDRATANTE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_HYDRA, tagSlug: TAG_SLUGS.POST_ACNE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_HYDRA, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },

  // Sebiaclear Active Gel (correcteur intensif imperfections)
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_ACTIVE_GEL, tagSlug: TAG_SLUGS.ANTI_ACNE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_ACTIVE_GEL, tagSlug: TAG_SLUGS.POST_ACNE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_ACTIVE_GEL, tagSlug: TAG_SLUGS.PORES_DILATES },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_ACTIVE_GEL, tagSlug: TAG_SLUGS.PEAU_GRASSE },

  // Sebiaclear Mat+Pores (matifiant, pores)
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_MAT_PORES, tagSlug: TAG_SLUGS.ANTI_ACNE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_MAT_PORES, tagSlug: TAG_SLUGS.PORES_DILATES },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_MAT_PORES, tagSlug: TAG_SLUGS.BRILLANCE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_MAT_PORES, tagSlug: TAG_SLUGS.PEAU_GRASSE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_MAT_PORES, tagSlug: TAG_SLUGS.PEAU_MIXTE },

  // Sebiaclear Crème SPF50+ (protection + anti-imperfections)
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_CREME_SPF50, tagSlug: TAG_SLUGS.ANTI_ACNE },
  {
    productSlug: SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_CREME_SPF50,
    tagSlug: TAG_SLUGS.PROTECTION_SOLAIRE,
  },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_CREME_SPF50, tagSlug: TAG_SLUGS.PEAU_GRASSE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_CREME_SPF50, tagSlug: TAG_SLUGS.POST_ACNE },

  // Sebiaclear Eau Micellaire (nettoyant purifiant)
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_EAU_MICELLAIRE, tagSlug: TAG_SLUGS.ANTI_ACNE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_EAU_MICELLAIRE, tagSlug: TAG_SLUGS.NETTOYANT },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_EAU_MICELLAIRE, tagSlug: TAG_SLUGS.PEAU_GRASSE },

  // Sebiaclear Active Teinté (teinté correcteur imperfections)
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_ACTIVE_TEINTE, tagSlug: TAG_SLUGS.ANTI_ACNE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_ACTIVE_TEINTE, tagSlug: TAG_SLUGS.POST_ACNE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_ACTIVE_TEINTE, tagSlug: TAG_SLUGS.PEAU_GRASSE },

  // [C] Eye Biotic (contour yeux éclat / cernes)
  { productSlug: SVR_PRODUCT_SLUGS.SVR_C_EYE_BIOTIC, tagSlug: TAG_SLUGS.ECLAT },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_C_EYE_BIOTIC, tagSlug: TAG_SLUGS.ANTI_AGE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_C_EYE_BIOTIC, tagSlug: TAG_SLUGS.CERNES_POCHES },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_C_EYE_BIOTIC, tagSlug: TAG_SLUGS.CONTOUR_YEUX },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_C_EYE_BIOTIC, tagSlug: TAG_SLUGS.ANTI_OXYDANT },

  // [Collagen] Biotic (fermeté, rebond)
  { productSlug: SVR_PRODUCT_SLUGS.SVR_COLLAGEN_BIOTIC, tagSlug: TAG_SLUGS.ANTI_AGE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_COLLAGEN_BIOTIC, tagSlug: TAG_SLUGS.ECLAT },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_COLLAGEN_BIOTIC, tagSlug: TAG_SLUGS.CREME_HYDRATANTE },

  // [Filler] Biotic (liftant rides yeux/lèvres)
  { productSlug: SVR_PRODUCT_SLUGS.SVR_FILLER_BIOTIC, tagSlug: TAG_SLUGS.ANTI_AGE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_FILLER_BIOTIC, tagSlug: TAG_SLUGS.REPARATEUR },

  // [Pepti] Biotic (rides + matifiant)
  { productSlug: SVR_PRODUCT_SLUGS.SVR_PEPTI_BIOTIC, tagSlug: TAG_SLUGS.ANTI_AGE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_PEPTI_BIOTIC, tagSlug: TAG_SLUGS.BRILLANCE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_PEPTI_BIOTIC, tagSlug: TAG_SLUGS.PEAU_MIXTE },

  // [Hyalu] Biotic (repulpant, hydratation)
  { productSlug: SVR_PRODUCT_SLUGS.SVR_HYALU_BIOTIC, tagSlug: TAG_SLUGS.ANTI_AGE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_HYALU_BIOTIC, tagSlug: TAG_SLUGS.DESHYDRATATION },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_HYALU_BIOTIC, tagSlug: TAG_SLUGS.CREME_HYDRATANTE },
  // [C20] Fluide (énergisant, éclat, lissant, vitamine C 20%, hydratation, fini peau de pêche)
  { productSlug: SVR_PRODUCT_SLUGS.SVR_C20_FLUIDE, tagSlug: TAG_SLUGS.ECLAT },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_C20_FLUIDE, tagSlug: TAG_SLUGS.ANTI_OXYDANT },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_C20_FLUIDE, tagSlug: TAG_SLUGS.ANTI_AGE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_C20_FLUIDE, tagSlug: TAG_SLUGS.DESHYDRATATION },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_C20_FLUIDE, tagSlug: TAG_SLUGS.CREME_HYDRATANTE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_C20_FLUIDE, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },

  // Cicavit+ Gel Moussant (nettoyant doux, apaisant, zones irritées, microbiote)
  { productSlug: SVR_PRODUCT_SLUGS.SVR_CICAVIT_GEL_MOUSSANT, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_CICAVIT_GEL_MOUSSANT, tagSlug: TAG_SLUGS.NETTOYANT },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_CICAVIT_GEL_MOUSSANT, tagSlug: TAG_SLUGS.SANS_SAVON },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_CICAVIT_GEL_MOUSSANT, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_CICAVIT_GEL_MOUSSANT, tagSlug: TAG_SLUGS.REPARATEUR },

  // Cicavit+ Crème Mains (barrière, réparatrice, mains abîmées)
  { productSlug: SVR_PRODUCT_SLUGS.SVR_CICAVIT_CREME_MAINS, tagSlug: TAG_SLUGS.REPARATEUR },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_CICAVIT_CREME_MAINS, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_CICAVIT_CREME_MAINS, tagSlug: TAG_SLUGS.PEAU_SECHE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_CICAVIT_CREME_MAINS, tagSlug: TAG_SLUGS.CREME_HYDRATANTE },

  // Cicavit+ Crème SPF50+ (protection + cicatrisante, anti-marques UV)
  { productSlug: SVR_PRODUCT_SLUGS.SVR_CICAVIT_CREME_SPF50, tagSlug: TAG_SLUGS.PROTECTION_SOLAIRE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_CICAVIT_CREME_SPF50, tagSlug: TAG_SLUGS.REPARATEUR },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_CICAVIT_CREME_SPF50, tagSlug: TAG_SLUGS.ANTI_ROUGEURS },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_CICAVIT_CREME_SPF50, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },

  // Cicavit+ Baume Lèvres (réparateur lèvres gercées)
  { productSlug: SVR_PRODUCT_SLUGS.SVR_CICAVIT_BAUME_LEVRES, tagSlug: TAG_SLUGS.REPARATEUR },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_CICAVIT_BAUME_LEVRES, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_CICAVIT_BAUME_LEVRES, tagSlug: TAG_SLUGS.PEAU_SECHE },

  // Cicavit+ SOS Grattage (apaisant démangeaisons, effet froid)
  { productSlug: SVR_PRODUCT_SLUGS.SVR_CICAVIT_SOS_GRATTAGE, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_CICAVIT_SOS_GRATTAGE, tagSlug: TAG_SLUGS.REPARATEUR },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_CICAVIT_SOS_GRATTAGE, tagSlug: TAG_SLUGS.ANTI_ROUGEURS },

  // Cicavit DM+ Cicatrices (gel silicone cicatrices post-chirurgicales)
  { productSlug: SVR_PRODUCT_SLUGS.SVR_CICAVIT_DM_PLUS, tagSlug: TAG_SLUGS.REPARATEUR },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_CICAVIT_DM_PLUS, tagSlug: TAG_SLUGS.ANTI_ROUGEURS },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_CICAVIT_DM_PLUS, tagSlug: TAG_SLUGS.POST_ACNE },

  // Clairial Ampoule (concentré anti-taches, tous types, anti-pollution)
  { productSlug: SVR_PRODUCT_SLUGS.SVR_CLAIRIAL_AMPOULE, tagSlug: TAG_SLUGS.ANTI_TACHES },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_CLAIRIAL_AMPOULE, tagSlug: TAG_SLUGS.HYPERPIGMENTATION },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_CLAIRIAL_AMPOULE, tagSlug: TAG_SLUGS.ECLAT },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_CLAIRIAL_AMPOULE, tagSlug: TAG_SLUGS.SERUM },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_CLAIRIAL_AMPOULE, tagSlug: TAG_SLUGS.ANTI_OXYDANT },

  // Clairial Sérum (anti-taches, éclat immédiat)
  { productSlug: SVR_PRODUCT_SLUGS.SVR_CLAIRIAL_SERUM, tagSlug: TAG_SLUGS.ANTI_TACHES },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_CLAIRIAL_SERUM, tagSlug: TAG_SLUGS.HYPERPIGMENTATION },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_CLAIRIAL_SERUM, tagSlug: TAG_SLUGS.ECLAT },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_CLAIRIAL_SERUM, tagSlug: TAG_SLUGS.SERUM },

  // Clairial Crème SPF50+ (2-en-1 dépigmentant + protection)
  { productSlug: SVR_PRODUCT_SLUGS.SVR_CLAIRIAL_CREME_SPF50, tagSlug: TAG_SLUGS.ANTI_TACHES },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_CLAIRIAL_CREME_SPF50, tagSlug: TAG_SLUGS.HYPERPIGMENTATION },
  {
    productSlug: SVR_PRODUCT_SLUGS.SVR_CLAIRIAL_CREME_SPF50,
    tagSlug: TAG_SLUGS.PROTECTION_SOLAIRE,
  },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_CLAIRIAL_CREME_SPF50, tagSlug: TAG_SLUGS.CREME_HYDRATANTE },

  // Clairial Day (teintée SPF30, anti-pollution/lumière bleue)
  { productSlug: SVR_PRODUCT_SLUGS.SVR_CLAIRIAL_DAY, tagSlug: TAG_SLUGS.ANTI_TACHES },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_CLAIRIAL_DAY, tagSlug: TAG_SLUGS.HYPERPIGMENTATION },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_CLAIRIAL_DAY, tagSlug: TAG_SLUGS.PROTECTION_SOLAIRE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_CLAIRIAL_DAY, tagSlug: TAG_SLUGS.ECLAT },

  // Clairial Night Peel (peeling doux nocturne anti-taches)
  { productSlug: SVR_PRODUCT_SLUGS.SVR_CLAIRIAL_NIGHT_PEEL, tagSlug: TAG_SLUGS.ANTI_TACHES },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_CLAIRIAL_NIGHT_PEEL, tagSlug: TAG_SLUGS.HYPERPIGMENTATION },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_CLAIRIAL_NIGHT_PEEL, tagSlug: TAG_SLUGS.EXFOLIANT },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_CLAIRIAL_NIGHT_PEEL, tagSlug: TAG_SLUGS.ECLAT },

  // Densitium Bi-Sérum (anti-gravité, redensifiant, relâchement)
  { productSlug: SVR_PRODUCT_SLUGS.SVR_DENSITIUM_BI_SERUM, tagSlug: TAG_SLUGS.ANTI_AGE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_DENSITIUM_BI_SERUM, tagSlug: TAG_SLUGS.SERUM },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_DENSITIUM_BI_SERUM, tagSlug: TAG_SLUGS.DESHYDRATATION },

  // Densitium Crème (anti-âge global, raffermissant, maturité/ménopause)
  { productSlug: SVR_PRODUCT_SLUGS.SVR_DENSITIUM_CREME, tagSlug: TAG_SLUGS.ANTI_AGE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_DENSITIUM_CREME, tagSlug: TAG_SLUGS.CREME_HYDRATANTE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_DENSITIUM_CREME, tagSlug: TAG_SLUGS.PEAU_SECHE },

  // Densitium Contour des Yeux (rides, cernes, poches)
  { productSlug: SVR_PRODUCT_SLUGS.SVR_DENSITIUM_YEUX, tagSlug: TAG_SLUGS.ANTI_AGE },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_DENSITIUM_YEUX, tagSlug: TAG_SLUGS.CERNES_POCHES },
  { productSlug: SVR_PRODUCT_SLUGS.SVR_DENSITIUM_YEUX, tagSlug: TAG_SLUGS.CONTOUR_YEUX },
]
