import { TAG_SLUGS } from '../../tags/seed-tags'
import { SVR_PRODUCT_SLUGS } from './svr'

type ProductTagGroups = {
  primary: string[]
  secondary: string[]
  avoid: string[]
}

export const SVR_PRODUCT_TAGS: Record<string, ProductTagGroups> = {
  [SVR_PRODUCT_SLUGS.SVR_SENSIFINE_AR_SPF50]: {
    primary: [
      TAG_SLUGS.ANTI_ROUGEURS,
      TAG_SLUGS.ROSACEE,
      TAG_SLUGS.COUPEROSE,
      TAG_SLUGS.FLUSHS,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.PEAU_REACTIVE,
      TAG_SLUGS.PROTECTION_SOLAIRE,
      TAG_SLUGS.SOLAIRE_VISAGE,
      TAG_SLUGS.SOIN_DE_JOUR,
      TAG_SLUGS.CREME_HYDRATANTE,
      TAG_SLUGS.PHOTO_VIEILLISSEMENT,
      TAG_SLUGS.LUMIERE_BLEUE,
      TAG_SLUGS.POLLUTION,
    ],
    secondary: [
      TAG_SLUGS.HUMECTANT,
      TAG_SLUGS.APAISANT,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.FILTRES_CHIMIQUES,
      TAG_SLUGS.NON_COMEDOGENE,
    ],
    avoid: [
      TAG_SLUGS.PEAU_GRASSE,
      TAG_SLUGS.BRILLANCE,
      TAG_SLUGS.COMEDOGENE,
      TAG_SLUGS.FILTRES_MINERAUX,
    ],
  },

  [SVR_PRODUCT_SLUGS.SVR_SENSIFINE_AR]: {
    primary: [
      TAG_SLUGS.ANTI_ROUGEURS,
      TAG_SLUGS.ROSACEE,
      TAG_SLUGS.COUPEROSE,
      TAG_SLUGS.FLUSHS,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.PEAU_REACTIVE,
      TAG_SLUGS.SOIN_DE_JOUR,
      TAG_SLUGS.CREME_HYDRATANTE,
    ],
    secondary: [
      TAG_SLUGS.HUMECTANT,
      TAG_SLUGS.EMOLLIENT,
      TAG_SLUGS.APAISANT,
      TAG_SLUGS.PIGMENTS_VERTS,
      TAG_SLUGS.MICROBIOME,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.NON_COMEDOGENE,
    ],
    avoid: [TAG_SLUGS.PEAU_GRASSE, TAG_SLUGS.BRILLANCE, TAG_SLUGS.COMEDOGENE],
  },

  [SVR_PRODUCT_SLUGS.SVR_SENSIFINE_EXTREME]: {
    primary: [
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.PEAU_REACTIVE,
      TAG_SLUGS.BARRIERE_CUTANEE,
      TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE,
      TAG_SLUGS.SOIN_DE_JOUR,
      TAG_SLUGS.SOIN_DE_NUIT,
      TAG_SLUGS.CREME_HYDRATANTE,
      TAG_SLUGS.REPARATEUR,
    ],
    secondary: [
      TAG_SLUGS.HUMECTANT,
      TAG_SLUGS.EMOLLIENT,
      TAG_SLUGS.APAISANT,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.HYPOALLERGENIQUE,
      TAG_SLUGS.NON_COMEDOGENE,
    ],
    avoid: [TAG_SLUGS.ANTI_ACNE, TAG_SLUGS.EXFOLIANT, TAG_SLUGS.KERATOLYTIQUE, TAG_SLUGS.BRILLANCE],
  },

  [SVR_PRODUCT_SLUGS.SVR_SENSIFINE_HUILE_NUIT]: {
    primary: [
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.PEAU_REACTIVE,
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.SOIN_DE_NUIT,
      TAG_SLUGS.HUILE,
      TAG_SLUGS.REPARATEUR,
      TAG_SLUGS.BARRIERE_CUTANEE,
    ],
    secondary: [
      TAG_SLUGS.EMOLLIENT,
      TAG_SLUGS.APAISANT,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.HYPOALLERGENIQUE,
      TAG_SLUGS.NON_COMEDOGENE,
    ],
    avoid: [
      TAG_SLUGS.PEAU_GRASSE,
      TAG_SLUGS.PEAU_MIXTE,
      TAG_SLUGS.ANTI_ACNE,
      TAG_SLUGS.BRILLANCE,
      TAG_SLUGS.COMEDOGENE,
    ],
  },

  [SVR_PRODUCT_SLUGS.SVR_SENSIFINE_MASQUE_SOS]: {
    primary: [
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.PEAU_REACTIVE,
      TAG_SLUGS.MASQUE,
      TAG_SLUGS.REPARATEUR,
      TAG_SLUGS.BARRIERE_CUTANEE,
    ],
    secondary: [
      TAG_SLUGS.APAISANT,
      TAG_SLUGS.HUMECTANT,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.HYPOALLERGENIQUE,
      TAG_SLUGS.NON_COMEDOGENE,
    ],
    avoid: [TAG_SLUGS.EXFOLIANT, TAG_SLUGS.KERATOLYTIQUE, TAG_SLUGS.ANTI_ACNE],
  },

  [SVR_PRODUCT_SLUGS.SVR_SENSIFINE_NUTRI_BAUME]: {
    primary: [
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.PEAU_REACTIVE,
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.SOIN_DE_JOUR,
      TAG_SLUGS.SOIN_DE_NUIT,
      TAG_SLUGS.CREME_HYDRATANTE,
      TAG_SLUGS.BARRIERE_CUTANEE,
    ],
    secondary: [
      TAG_SLUGS.HUMECTANT,
      TAG_SLUGS.EMOLLIENT,
      TAG_SLUGS.OCCLUSIF,
      TAG_SLUGS.TEXTURE_RICHE,
      TAG_SLUGS.APAISANT,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.HYPOALLERGENIQUE,
      TAG_SLUGS.NON_COMEDOGENE,
    ],
    avoid: [TAG_SLUGS.PEAU_GRASSE, TAG_SLUGS.PEAU_MIXTE, TAG_SLUGS.BRILLANCE, TAG_SLUGS.ANTI_ACNE],
  },

  [SVR_PRODUCT_SLUGS.SVR_SENSIFINE_BAUME_DEMAQUILLANT]: {
    primary: [
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.PEAU_REACTIVE,
      TAG_SLUGS.DEMAQUILLANT,
      TAG_SLUGS.NETTOYANT,
    ],
    secondary: [
      TAG_SLUGS.EMOLLIENT,
      TAG_SLUGS.OCCLUSIF,
      TAG_SLUGS.APAISANT,
      TAG_SLUGS.SANS_SAVON,
      TAG_SLUGS.NON_COMEDOGENE,
    ],
    avoid: [TAG_SLUGS.PEAU_GRASSE, TAG_SLUGS.ANTI_ACNE, TAG_SLUGS.BRILLANCE],
  },

  [SVR_PRODUCT_SLUGS.SVR_SENSIFINE_AQUA_GEL]: {
    primary: [
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.PEAU_REACTIVE,
      TAG_SLUGS.PEAU_NORMALE,
      TAG_SLUGS.PEAU_MIXTE,
      TAG_SLUGS.SOIN_DE_JOUR,
      TAG_SLUGS.CREME_HYDRATANTE,
    ],
    secondary: [
      TAG_SLUGS.HUMECTANT,
      TAG_SLUGS.TEXTURE_LEGERE,
      TAG_SLUGS.APAISANT,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.HYPOALLERGENIQUE,
      TAG_SLUGS.NON_COMEDOGENE,
    ],
    avoid: [TAG_SLUGS.PEAU_SECHE, TAG_SLUGS.ANTI_ACNE, TAG_SLUGS.EXFOLIANT],
  },

  [SVR_PRODUCT_SLUGS.SVR_SENSIFINE_DERMO_NETTOYANT]: {
    primary: [
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.PEAU_REACTIVE,
      TAG_SLUGS.NETTOYANT,
      TAG_SLUGS.DEMAQUILLANT,
    ],
    secondary: [
      TAG_SLUGS.APAISANT,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.HYPOALLERGENIQUE,
      TAG_SLUGS.NON_COMEDOGENE,
      TAG_SLUGS.SANS_SAVON,
    ],
    avoid: [TAG_SLUGS.EXFOLIANT, TAG_SLUGS.KERATOLYTIQUE, TAG_SLUGS.ANTI_ACNE],
  },

  [SVR_PRODUCT_SLUGS.SVR_SENSIFINE_HYDRA_CREME]: {
    primary: [
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.PEAU_REACTIVE,
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.PEAU_NORMALE,
      TAG_SLUGS.SOIN_DE_JOUR,
      TAG_SLUGS.CREME_HYDRATANTE,
    ],
    secondary: [
      TAG_SLUGS.HUMECTANT,
      TAG_SLUGS.EMOLLIENT,
      TAG_SLUGS.APAISANT,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.HYPOALLERGENIQUE,
      TAG_SLUGS.NON_COMEDOGENE,
    ],
    avoid: [TAG_SLUGS.PEAU_GRASSE, TAG_SLUGS.BRILLANCE, TAG_SLUGS.ANTI_ACNE],
  },

  [SVR_PRODUCT_SLUGS.SVR_CICAVIT_PLUS_CREME_HPPI]: {
    primary: [
      TAG_SLUGS.CICATRISATION,
      TAG_SLUGS.REPARATEUR,
      TAG_SLUGS.ANTI_ROUGEURS,
      TAG_SLUGS.POST_ACNE,
      TAG_SLUGS.BARRIERE_CUTANEE,
      TAG_SLUGS.SOIN_DE_JOUR,
      TAG_SLUGS.SOIN_DE_NUIT,
      TAG_SLUGS.CREME_HYDRATANTE,
    ],
    secondary: [
      TAG_SLUGS.MICROBIOME,
      TAG_SLUGS.HUMECTANT,
      TAG_SLUGS.EMOLLIENT,
      TAG_SLUGS.APAISANT,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.NON_COMEDOGENE,
    ],
    avoid: [TAG_SLUGS.EXFOLIANT, TAG_SLUGS.KERATOLYTIQUE, TAG_SLUGS.ANTI_ACNE],
  },

  [SVR_PRODUCT_SLUGS.SVR_CICAVIT_GEL_MOUSSANT]: {
    primary: [
      TAG_SLUGS.NETTOYANT,
      TAG_SLUGS.CICATRISATION,
      TAG_SLUGS.ANTISEPTIQUE,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.PEAU_REACTIVE,
    ],
    secondary: [
      TAG_SLUGS.MICROBIOME,
      TAG_SLUGS.PREBIOTIQUE,
      TAG_SLUGS.APAISANT,
      TAG_SLUGS.SANS_SAVON,
      TAG_SLUGS.NON_COMEDOGENE,
    ],
    avoid: [TAG_SLUGS.ANTI_ACNE, TAG_SLUGS.KERATOLYTIQUE, TAG_SLUGS.EXFOLIANT],
  },

  [SVR_PRODUCT_SLUGS.SVR_CICAVIT_CREME_MAINS]: {
    primary: [TAG_SLUGS.REPARATEUR, TAG_SLUGS.BARRIERE_CUTANEE, TAG_SLUGS.CICATRISATION],
    secondary: [
      TAG_SLUGS.HUMECTANT,
      TAG_SLUGS.EMOLLIENT,
      TAG_SLUGS.OCCLUSIF,
      TAG_SLUGS.PREBIOTIQUE,
      TAG_SLUGS.MICROBIOME,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.NON_COMEDOGENE,
    ],
    avoid: [],
  },

  [SVR_PRODUCT_SLUGS.SVR_CICAVIT_CREME_SPF50]: {
    primary: [
      TAG_SLUGS.CICATRISATION,
      TAG_SLUGS.ANTI_ROUGEURS,
      TAG_SLUGS.POST_ACNE,
      TAG_SLUGS.HYPERPIGMENTATION,
      TAG_SLUGS.ANTI_TACHES,
      TAG_SLUGS.PROTECTION_SOLAIRE,
      TAG_SLUGS.SOLAIRE_VISAGE,
      TAG_SLUGS.PHOTO_VIEILLISSEMENT,
      TAG_SLUGS.REPARATEUR,
      TAG_SLUGS.SOIN_DE_JOUR,
    ],
    secondary: [
      TAG_SLUGS.MICROBIOME,
      TAG_SLUGS.PREBIOTIQUE,
      TAG_SLUGS.FILTRES_CHIMIQUES,
      TAG_SLUGS.NON_COMEDOGENE,
    ],
    avoid: [TAG_SLUGS.PEAU_SECHE, TAG_SLUGS.FILTRES_MINERAUX],
  },

  [SVR_PRODUCT_SLUGS.SVR_CICAVIT_BAUME_LEVRES]: {
    primary: [TAG_SLUGS.REPARATEUR, TAG_SLUGS.CICATRISATION],
    secondary: [
      TAG_SLUGS.HUMECTANT,
      TAG_SLUGS.EMOLLIENT,
      TAG_SLUGS.OCCLUSIF,
      TAG_SLUGS.APAISANT,
      TAG_SLUGS.MICROBIOME,
      TAG_SLUGS.PREBIOTIQUE,
      TAG_SLUGS.SANS_PARFUM,
    ],
    avoid: [],
  },

  [SVR_PRODUCT_SLUGS.SVR_CICAVIT_SOS_GRATTAGE]: {
    primary: [
      TAG_SLUGS.ANTI_ROUGEURS,
      TAG_SLUGS.CICATRISATION,
      TAG_SLUGS.POST_ACNE,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.PEAU_REACTIVE,
      TAG_SLUGS.ECZEMA,
    ],
    secondary: [TAG_SLUGS.APAISANT, TAG_SLUGS.MICROBIOME],
    avoid: [TAG_SLUGS.ANTI_ACNE, TAG_SLUGS.EXFOLIANT],
  },

  [SVR_PRODUCT_SLUGS.SVR_CICAVIT_DM_PLUS]: {
    primary: [
      TAG_SLUGS.CICATRISATION,
      TAG_SLUGS.REPARATEUR,
      TAG_SLUGS.ANTI_ROUGEURS,
      TAG_SLUGS.PROTECTION_CUTANEE,
    ],
    secondary: [TAG_SLUGS.MICROBIOME, TAG_SLUGS.PREBIOTIQUE, TAG_SLUGS.SANS_PARFUM],
    avoid: [TAG_SLUGS.ANTI_ACNE, TAG_SLUGS.EXFOLIANT],
  },

  [SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_FLASH_15]: {
    primary: [
      TAG_SLUGS.ANTI_ACNE,
      TAG_SLUGS.POST_ACNE,
      TAG_SLUGS.ANTI_TACHES,
      TAG_SLUGS.HYPERPIGMENTATION,
      TAG_SLUGS.PORES_DILATES,
      TAG_SLUGS.PEAU_GRASSE,
      TAG_SLUGS.PEAU_MIXTE,
      TAG_SLUGS.SERUM,
      TAG_SLUGS.SEBO_REGULATEUR,
      TAG_SLUGS.MATIFIANT,
      TAG_SLUGS.ANTI_BACTERIEN,
      TAG_SLUGS.KERATOLYTIQUE,
    ],
    secondary: [TAG_SLUGS.ANTI_OXYDANT],
    avoid: [
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.PEAU_REACTIVE,
      TAG_SLUGS.ROSACEE,
      TAG_SLUGS.ANTI_ROUGEURS,
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE,
      TAG_SLUGS.GROSSESSE_COMPATIBLE,
    ],
  },

  [SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_GEL_FLASH_4H]: {
    primary: [
      TAG_SLUGS.ANTI_ACNE,
      TAG_SLUGS.PORES_DILATES,
      TAG_SLUGS.POST_ACNE,
      TAG_SLUGS.PEAU_GRASSE,
      TAG_SLUGS.PEAU_MIXTE,
      TAG_SLUGS.SEBO_REGULATEUR,
      TAG_SLUGS.KERATOLYTIQUE,
    ],
    secondary: [TAG_SLUGS.TEXTURE_LEGERE],
    avoid: [
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.PEAU_REACTIVE,
      TAG_SLUGS.ROSACEE,
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE,
      TAG_SLUGS.GROSSESSE_COMPATIBLE,
    ],
  },

  [SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_SPRAY_CORPS]: {
    primary: [
      TAG_SLUGS.ANTI_ACNE,
      TAG_SLUGS.POST_ACNE,
      TAG_SLUGS.ANTI_TACHES,
      TAG_SLUGS.HYPERPIGMENTATION,
      TAG_SLUGS.KERATOLYTIQUE,
      TAG_SLUGS.SEBO_REGULATEUR,
    ],
    secondary: [],
    avoid: [
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.PEAU_REACTIVE,
      TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE,
      TAG_SLUGS.GROSSESSE_COMPATIBLE,
    ],
  },

  [SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_MICRO_PEEL]: {
    primary: [
      TAG_SLUGS.EXFOLIANT,
      TAG_SLUGS.ANTI_ACNE,
      TAG_SLUGS.PORES_DILATES,
      TAG_SLUGS.POST_ACNE,
      TAG_SLUGS.BRILLANCE,
      TAG_SLUGS.PEAU_GRASSE,
      TAG_SLUGS.PEAU_MIXTE,
      TAG_SLUGS.TONIQUE,
      TAG_SLUGS.KERATOLYTIQUE,
      TAG_SLUGS.SEBO_REGULATEUR,
      TAG_SLUGS.MATIFIANT,
      TAG_SLUGS.ASTRINGENT,
    ],
    secondary: [],
    avoid: [
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.PEAU_REACTIVE,
      TAG_SLUGS.ROSACEE,
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE,
      TAG_SLUGS.GROSSESSE_COMPATIBLE,
    ],
  },

  [SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_GEL_MOUSSANT]: {
    primary: [
      TAG_SLUGS.NETTOYANT,
      TAG_SLUGS.ANTI_ACNE,
      TAG_SLUGS.PORES_DILATES,
      TAG_SLUGS.BRILLANCE,
      TAG_SLUGS.PEAU_GRASSE,
      TAG_SLUGS.PEAU_MIXTE,
      TAG_SLUGS.SEBO_REGULATEUR,
      TAG_SLUGS.MATIFIANT,
      TAG_SLUGS.KERATOLYTIQUE,
    ],
    secondary: [TAG_SLUGS.SANS_SAVON],
    avoid: [
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.PEAU_REACTIVE,
      TAG_SLUGS.ROSACEE,
      TAG_SLUGS.GROSSESSE_COMPATIBLE,
    ],
  },

  [SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_SERUM]: {
    primary: [
      TAG_SLUGS.ANTI_ACNE,
      TAG_SLUGS.POST_ACNE,
      TAG_SLUGS.ANTI_TACHES,
      TAG_SLUGS.HYPERPIGMENTATION,
      TAG_SLUGS.PORES_DILATES,
      TAG_SLUGS.ANTI_AGE,
      TAG_SLUGS.PEAU_GRASSE,
      TAG_SLUGS.PEAU_MIXTE,
      TAG_SLUGS.SERUM,
      TAG_SLUGS.SEBO_REGULATEUR,
      TAG_SLUGS.KERATOLYTIQUE,
      TAG_SLUGS.POLLUTION,
    ],
    secondary: [TAG_SLUGS.ANTI_OXYDANT, TAG_SLUGS.HUMECTANT],
    avoid: [
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.PEAU_REACTIVE,
      TAG_SLUGS.ROSACEE,
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE,
      TAG_SLUGS.GROSSESSE_COMPATIBLE,
    ],
  },

  [SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_CREME_LAVANTE]: {
    primary: [
      TAG_SLUGS.NETTOYANT,
      TAG_SLUGS.ANTI_ACNE,
      TAG_SLUGS.DESHYDRATATION,
      TAG_SLUGS.PEAU_GRASSE,
      TAG_SLUGS.PEAU_MIXTE,
    ],
    secondary: [
      TAG_SLUGS.HUMECTANT,
      TAG_SLUGS.APAISANT,
      TAG_SLUGS.SANS_SAVON,
      TAG_SLUGS.NON_COMEDOGENE,
    ],
    avoid: [TAG_SLUGS.PEAU_SECHE, TAG_SLUGS.KERATOLYTIQUE, TAG_SLUGS.GROSSESSE_COMPATIBLE],
  },

  [SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_HYDRA]: {
    primary: [
      TAG_SLUGS.ANTI_ACNE,
      TAG_SLUGS.DESHYDRATATION,
      TAG_SLUGS.POST_ACNE,
      TAG_SLUGS.BARRIERE_CUTANEE,
      TAG_SLUGS.PEAU_GRASSE,
      TAG_SLUGS.PEAU_MIXTE,
      TAG_SLUGS.CREME_HYDRATANTE,
      TAG_SLUGS.SOIN_DE_JOUR,
    ],
    secondary: [
      TAG_SLUGS.HUMECTANT,
      TAG_SLUGS.EMOLLIENT,
      TAG_SLUGS.MICROBIOME,
      TAG_SLUGS.APAISANT,
      TAG_SLUGS.NON_COMEDOGENE,
    ],
    avoid: [TAG_SLUGS.PEAU_SECHE, TAG_SLUGS.GROSSESSE_COMPATIBLE],
  },

  [SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_ACTIVE_GEL]: {
    primary: [
      TAG_SLUGS.ANTI_ACNE,
      TAG_SLUGS.POST_ACNE,
      TAG_SLUGS.PORES_DILATES,
      TAG_SLUGS.BRILLANCE,
      TAG_SLUGS.PEAU_GRASSE,
      TAG_SLUGS.PEAU_MIXTE,
      TAG_SLUGS.SEBO_REGULATEUR,
      TAG_SLUGS.MATIFIANT,
      TAG_SLUGS.KERATOLYTIQUE,
    ],
    secondary: [TAG_SLUGS.TEXTURE_LEGERE, TAG_SLUGS.NON_COMEDOGENE],
    avoid: [
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.PEAU_REACTIVE,
      TAG_SLUGS.ROSACEE,
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE,
      TAG_SLUGS.GROSSESSE_COMPATIBLE,
    ],
  },

  [SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_MAT_PORES]: {
    primary: [
      TAG_SLUGS.PORES_DILATES,
      TAG_SLUGS.BRILLANCE,
      TAG_SLUGS.ANTI_ACNE,
      TAG_SLUGS.POST_ACNE,
      TAG_SLUGS.PEAU_GRASSE,
      TAG_SLUGS.PEAU_MIXTE,
      TAG_SLUGS.SEBO_REGULATEUR,
      TAG_SLUGS.MATIFIANT,
      TAG_SLUGS.ASTRINGENT,
      TAG_SLUGS.KERATOLYTIQUE,
      TAG_SLUGS.CREME_HYDRATANTE,
      TAG_SLUGS.SOIN_DE_JOUR,
    ],
    secondary: [TAG_SLUGS.NON_COMEDOGENE],
    avoid: [
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.ROSACEE,
      TAG_SLUGS.GROSSESSE_COMPATIBLE,
    ],
  },

  [SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_CREME_SPF50]: {
    primary: [
      TAG_SLUGS.ANTI_ACNE,
      TAG_SLUGS.POST_ACNE,
      TAG_SLUGS.ANTI_TACHES,
      TAG_SLUGS.PHOTO_VIEILLISSEMENT,
      TAG_SLUGS.PROTECTION_SOLAIRE,
      TAG_SLUGS.SOLAIRE_VISAGE,
      TAG_SLUGS.PORES_DILATES,
      TAG_SLUGS.PEAU_GRASSE,
      TAG_SLUGS.PEAU_MIXTE,
      TAG_SLUGS.SOIN_DE_JOUR,
      TAG_SLUGS.MATIFIANT,
      TAG_SLUGS.KERATOLYTIQUE,
    ],
    secondary: [TAG_SLUGS.FILTRES_CHIMIQUES, TAG_SLUGS.NON_COMEDOGENE],
    avoid: [
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.ROSACEE,
      TAG_SLUGS.FILTRES_MINERAUX,
      TAG_SLUGS.GROSSESSE_COMPATIBLE,
    ],
  },

  [SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_EAU_MICELLAIRE]: {
    primary: [
      TAG_SLUGS.NETTOYANT,
      TAG_SLUGS.DEMAQUILLANT,
      TAG_SLUGS.ANTI_ACNE,
      TAG_SLUGS.PORES_DILATES,
      TAG_SLUGS.PEAU_GRASSE,
      TAG_SLUGS.PEAU_MIXTE,
      TAG_SLUGS.KERATOLYTIQUE,
    ],
    secondary: [TAG_SLUGS.SANS_SAVON],
    avoid: [
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.ROSACEE,
      TAG_SLUGS.GROSSESSE_COMPATIBLE,
    ],
  },

  [SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_ACTIVE_TEINTE]: {
    primary: [
      TAG_SLUGS.ANTI_ACNE,
      TAG_SLUGS.POST_ACNE,
      TAG_SLUGS.ANTI_TACHES,
      TAG_SLUGS.PORES_DILATES,
      TAG_SLUGS.BRILLANCE,
      TAG_SLUGS.PEAU_GRASSE,
      TAG_SLUGS.PEAU_MIXTE,
      TAG_SLUGS.SEBO_REGULATEUR,
      TAG_SLUGS.MATIFIANT,
      TAG_SLUGS.KERATOLYTIQUE,
      TAG_SLUGS.SOLAIRE_TEINTE,
    ],
    secondary: [TAG_SLUGS.NON_COMEDOGENE],
    avoid: [
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.ROSACEE,
      TAG_SLUGS.GROSSESSE_COMPATIBLE,
    ],
  },

  [SVR_PRODUCT_SLUGS.SVR_TOPIALYSE_BAUME_PROTECT]: {
    primary: [
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.PEAU_ATOPIQUE,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.ECZEMA,
      TAG_SLUGS.BARRIERE_CUTANEE,
      TAG_SLUGS.REPARATEUR,
    ],
    secondary: [
      TAG_SLUGS.EMOLLIENT,
      TAG_SLUGS.OCCLUSIF,
      TAG_SLUGS.TEXTURE_RICHE,
      TAG_SLUGS.MICROBIOME,
      TAG_SLUGS.PREBIOTIQUE,
      TAG_SLUGS.BIOMIMETIQUE,
      TAG_SLUGS.APAISANT,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.NON_COMEDOGENE,
    ],
    avoid: [TAG_SLUGS.PEAU_GRASSE, TAG_SLUGS.PEAU_MIXTE, TAG_SLUGS.ANTI_ACNE, TAG_SLUGS.BRILLANCE],
  },

  [SVR_PRODUCT_SLUGS.SVR_TOPIALYSE_CREME]: {
    primary: [TAG_SLUGS.PEAU_SECHE, TAG_SLUGS.PEAU_SENSIBLE, TAG_SLUGS.BARRIERE_CUTANEE],
    secondary: [
      TAG_SLUGS.EMOLLIENT,
      TAG_SLUGS.OCCLUSIF,
      TAG_SLUGS.HUMECTANT,
      TAG_SLUGS.TEXTURE_RICHE,
      TAG_SLUGS.MICROBIOME,
      TAG_SLUGS.PREBIOTIQUE,
      TAG_SLUGS.APAISANT,
      TAG_SLUGS.BIO_NATUREL,
    ],
    avoid: [TAG_SLUGS.PEAU_GRASSE, TAG_SLUGS.PEAU_MIXTE, TAG_SLUGS.ANTI_ACNE, TAG_SLUGS.BRILLANCE],
  },

  [SVR_PRODUCT_SLUGS.SVR_TOPIALYSE_HUILE_LAVANTE]: {
    primary: [
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.PEAU_ATOPIQUE,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.ECZEMA,
      TAG_SLUGS.NETTOYANT,
      TAG_SLUGS.BARRIERE_CUTANEE,
    ],
    secondary: [
      TAG_SLUGS.EMOLLIENT,
      TAG_SLUGS.MICROBIOME,
      TAG_SLUGS.PREBIOTIQUE,
      TAG_SLUGS.APAISANT,
      TAG_SLUGS.SANS_SAVON,
      TAG_SLUGS.NON_COMEDOGENE,
    ],
    avoid: [TAG_SLUGS.PEAU_GRASSE, TAG_SLUGS.PEAU_MIXTE, TAG_SLUGS.ANTI_ACNE],
  },

  [SVR_PRODUCT_SLUGS.SVR_TOPIALYSE_GEL_LAVANT]: {
    primary: [TAG_SLUGS.PEAU_SECHE, TAG_SLUGS.PEAU_SENSIBLE, TAG_SLUGS.NETTOYANT],
    secondary: [
      TAG_SLUGS.HUMECTANT,
      TAG_SLUGS.APAISANT,
      TAG_SLUGS.SANS_SAVON,
      TAG_SLUGS.NON_COMEDOGENE,
    ],
    avoid: [TAG_SLUGS.ANTI_ACNE, TAG_SLUGS.KERATOLYTIQUE],
  },

  [SVR_PRODUCT_SLUGS.SVR_TOPIALYSE_BAUME_LAVANT]: {
    primary: [
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.PEAU_ATOPIQUE,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.ECZEMA,
      TAG_SLUGS.NETTOYANT,
      TAG_SLUGS.BARRIERE_CUTANEE,
    ],
    secondary: [
      TAG_SLUGS.EMOLLIENT,
      TAG_SLUGS.HUMECTANT,
      TAG_SLUGS.MICROBIOME,
      TAG_SLUGS.PREBIOTIQUE,
      TAG_SLUGS.APAISANT,
      TAG_SLUGS.SANS_PARFUM,
      TAG_SLUGS.SANS_SAVON,
      TAG_SLUGS.NON_COMEDOGENE,
    ],
    avoid: [TAG_SLUGS.PEAU_GRASSE, TAG_SLUGS.ANTI_ACNE],
  },

  [SVR_PRODUCT_SLUGS.SVR_TOPIALYSE_CONCENTRE_LAVANT]: {
    primary: [
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.PEAU_ATOPIQUE,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.NETTOYANT,
      TAG_SLUGS.BARRIERE_CUTANEE,
    ],
    secondary: [
      TAG_SLUGS.EMOLLIENT,
      TAG_SLUGS.MICROBIOME,
      TAG_SLUGS.PREBIOTIQUE,
      TAG_SLUGS.APAISANT,
    ],
    avoid: [TAG_SLUGS.PEAU_GRASSE, TAG_SLUGS.ANTI_ACNE],
  },

  [SVR_PRODUCT_SLUGS.SVR_TOPIALYSE_BARRIERE]: {
    primary: [
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.PEAU_REACTIVE,
      TAG_SLUGS.BARRIERE_CUTANEE,
      TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE,
      TAG_SLUGS.PROTECTION_CUTANEE,
      TAG_SLUGS.REPARATEUR,
    ],
    secondary: [
      TAG_SLUGS.HUMECTANT,
      TAG_SLUGS.EMOLLIENT,
      TAG_SLUGS.OCCLUSIF,
      TAG_SLUGS.APAISANT,
      TAG_SLUGS.SANS_PARFUM,
    ],
    avoid: [TAG_SLUGS.PEAU_GRASSE, TAG_SLUGS.ANTI_ACNE, TAG_SLUGS.BRILLANCE],
  },

  [SVR_PRODUCT_SLUGS.SVR_TOPIALYSE_MAINS]: {
    primary: [TAG_SLUGS.PEAU_SECHE, TAG_SLUGS.REPARATEUR, TAG_SLUGS.BARRIERE_CUTANEE],
    secondary: [TAG_SLUGS.EMOLLIENT, TAG_SLUGS.OCCLUSIF, TAG_SLUGS.TEXTURE_RICHE],
    avoid: [],
  },
  [SVR_PRODUCT_SLUGS.SVR_XERIAL_10_LAIT]: {
    primary: [
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.EXFOLIANT,
      TAG_SLUGS.KERATOLYTIQUE,
      TAG_SLUGS.HUMECTANT,
      TAG_SLUGS.EMOLLIENT,
      TAG_SLUGS.DESHYDRATATION,
    ],
    secondary: [TAG_SLUGS.BIOMIMETIQUE],
    avoid: [
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.PEAU_REACTIVE,
      TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE,
      TAG_SLUGS.GROSSESSE_COMPATIBLE,
    ],
  },
  [SVR_PRODUCT_SLUGS.SVR_XERIAL_50_EXTREME_PIEDS]: {
    primary: [TAG_SLUGS.PEAU_SECHE, TAG_SLUGS.KERATOLYTIQUE, TAG_SLUGS.REPARATEUR],
    secondary: [TAG_SLUGS.EMOLLIENT],
    avoid: [
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.PEAU_REACTIVE,
      TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE,
      TAG_SLUGS.GROSSESSE_COMPATIBLE,
    ],
  },

  [SVR_PRODUCT_SLUGS.SVR_XERIAL_FISSURES_CREVASSES]: {
    primary: [
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.KERATOLYTIQUE,
      TAG_SLUGS.REPARATEUR,
      TAG_SLUGS.CICATRISATION,
    ],
    secondary: [
      TAG_SLUGS.EMOLLIENT,
      TAG_SLUGS.HUMECTANT,
      TAG_SLUGS.PREBIOTIQUE,
      TAG_SLUGS.MICROBIOME,
      TAG_SLUGS.APAISANT,
    ],
    avoid: [
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.PEAU_REACTIVE,
      TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE,
      TAG_SLUGS.GROSSESSE_COMPATIBLE,
    ],
  },

  [SVR_PRODUCT_SLUGS.SVR_XERIAL_30_GEL_CREME]: {
    primary: [TAG_SLUGS.PEAU_SECHE, TAG_SLUGS.KERATOLYTIQUE],
    secondary: [TAG_SLUGS.HUMECTANT, TAG_SLUGS.EMOLLIENT, TAG_SLUGS.SANS_PARFUM],
    avoid: [
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.PEAU_REACTIVE,
      TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE,
      TAG_SLUGS.GROSSESSE_COMPATIBLE,
    ],
  },

  [SVR_PRODUCT_SLUGS.SVR_XERIAL_DM_PSORIASIS]: {
    primary: [
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.ECZEMA,
      TAG_SLUGS.KERATOLYTIQUE,
      TAG_SLUGS.REPARATEUR,
      TAG_SLUGS.BARRIERE_CUTANEE,
    ],
    secondary: [TAG_SLUGS.EMOLLIENT, TAG_SLUGS.HUMECTANT, TAG_SLUGS.TEXTURE_RICHE],
    avoid: [TAG_SLUGS.PEAU_GRASSE, TAG_SLUGS.ANTI_ACNE, TAG_SLUGS.GROSSESSE_COMPATIBLE],
  },

  [SVR_PRODUCT_SLUGS.SVR_XERIAL_30_PIEDS]: {
    primary: [TAG_SLUGS.PEAU_SECHE, TAG_SLUGS.KERATOLYTIQUE, TAG_SLUGS.REPARATEUR],
    secondary: [TAG_SLUGS.HUMECTANT, TAG_SLUGS.EMOLLIENT],
    avoid: [
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.PEAU_REACTIVE,
      TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE,
      TAG_SLUGS.GROSSESSE_COMPATIBLE,
    ],
  },

  [SVR_PRODUCT_SLUGS.SVR_AMPOULE_A_LIFT]: {
    primary: [
      TAG_SLUGS.ANTI_AGE,
      TAG_SLUGS.PORES_DILATES,
      TAG_SLUGS.PHOTO_VIEILLISSEMENT,
      TAG_SLUGS.ECLAT,
      TAG_SLUGS.TEINT_TERNE,
      TAG_SLUGS.POST_ACNE,
      TAG_SLUGS.SERUM,
      TAG_SLUGS.SOIN_DE_NUIT,
      TAG_SLUGS.KERATOLYTIQUE,
      TAG_SLUGS.SEBO_REGULATEUR,
      TAG_SLUGS.REPARATEUR,
    ],
    secondary: [TAG_SLUGS.ANTI_OXYDANT],
    avoid: [
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.PEAU_REACTIVE,
      TAG_SLUGS.ROSACEE,
      TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE,
      TAG_SLUGS.GROSSESSE_COMPATIBLE,
    ],
  },

  [SVR_PRODUCT_SLUGS.SVR_C20_BIOTIC]: {
    primary: [
      TAG_SLUGS.ECLAT,
      TAG_SLUGS.TEINT_TERNE,
      TAG_SLUGS.ANTI_TACHES,
      TAG_SLUGS.ANTI_AGE,
      TAG_SLUGS.PHOTO_VIEILLISSEMENT,
      TAG_SLUGS.DESHYDRATATION,
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.PEAU_NORMALE,
      TAG_SLUGS.SOIN_DE_JOUR,
      TAG_SLUGS.SOIN_DE_NUIT,
      TAG_SLUGS.CREME_HYDRATANTE,
    ],
    secondary: [
      TAG_SLUGS.MICROBIOME,
      TAG_SLUGS.HUMECTANT,
      TAG_SLUGS.EMOLLIENT,
      TAG_SLUGS.ANTI_OXYDANT,
      TAG_SLUGS.TEXTURE_RICHE,
    ],
    avoid: [TAG_SLUGS.PEAU_GRASSE, TAG_SLUGS.BRILLANCE],
  },

  [SVR_PRODUCT_SLUGS.SVR_C20_FLUIDE]: {
    primary: [
      TAG_SLUGS.ECLAT,
      TAG_SLUGS.TEINT_TERNE,
      TAG_SLUGS.ANTI_TACHES,
      TAG_SLUGS.ANTI_AGE,
      TAG_SLUGS.PHOTO_VIEILLISSEMENT,
      TAG_SLUGS.DESHYDRATATION,
      TAG_SLUGS.PEAU_NORMALE,
      TAG_SLUGS.PEAU_MIXTE,
      TAG_SLUGS.PEAU_GRASSE,
      TAG_SLUGS.SOIN_DE_JOUR,
      TAG_SLUGS.SERUM,
    ],
    secondary: [
      TAG_SLUGS.MICROBIOME,
      TAG_SLUGS.HUMECTANT,
      TAG_SLUGS.ANTI_OXYDANT,
      TAG_SLUGS.TEXTURE_LEGERE,
    ],
    avoid: [TAG_SLUGS.PEAU_SECHE, TAG_SLUGS.TEXTURE_RICHE],
  },

  [SVR_PRODUCT_SLUGS.SVR_C_EYE_BIOTIC]: {
    primary: [
      TAG_SLUGS.CERNES_POCHES,
      TAG_SLUGS.ANTI_AGE,
      TAG_SLUGS.ECLAT,
      TAG_SLUGS.CONTOUR_YEUX,
      TAG_SLUGS.REPULPANT,
    ],
    secondary: [TAG_SLUGS.MICROBIOME, TAG_SLUGS.ANTI_OXYDANT, TAG_SLUGS.HUMECTANT],
    avoid: [TAG_SLUGS.PEAU_GRASSE, TAG_SLUGS.ANTI_ACNE],
  },

  [SVR_PRODUCT_SLUGS.SVR_COLLAGEN_BIOTIC]: {
    primary: [
      TAG_SLUGS.ANTI_AGE,
      TAG_SLUGS.REPULPANT,
      TAG_SLUGS.DESHYDRATATION,
      TAG_SLUGS.PHOTO_VIEILLISSEMENT,
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.PEAU_NORMALE,
      TAG_SLUGS.SOIN_DE_JOUR,
      TAG_SLUGS.SOIN_DE_NUIT,
      TAG_SLUGS.CREME_HYDRATANTE,
    ],
    secondary: [
      TAG_SLUGS.MICROBIOME,
      TAG_SLUGS.HUMECTANT,
      TAG_SLUGS.EMOLLIENT,
      TAG_SLUGS.ANTI_OXYDANT,
    ],
    avoid: [TAG_SLUGS.PEAU_GRASSE, TAG_SLUGS.BRILLANCE, TAG_SLUGS.ANTI_ACNE],
  },

  [SVR_PRODUCT_SLUGS.SVR_FILLER_BIOTIC]: {
    primary: [
      TAG_SLUGS.ANTI_AGE,
      TAG_SLUGS.REPULPANT,
      TAG_SLUGS.CERNES_POCHES,
      TAG_SLUGS.CONTOUR_YEUX,
    ],
    secondary: [
      TAG_SLUGS.MICROBIOME,
      TAG_SLUGS.HUMECTANT,
      TAG_SLUGS.ANTI_OXYDANT,
      TAG_SLUGS.TEXTURE_LEGERE,
    ],
    avoid: [TAG_SLUGS.ANTI_ACNE],
  },

  [SVR_PRODUCT_SLUGS.SVR_PEPTI_BIOTIC]: {
    primary: [
      TAG_SLUGS.ANTI_AGE,
      TAG_SLUGS.ECLAT,
      TAG_SLUGS.BRILLANCE,
      TAG_SLUGS.PORES_DILATES,
      TAG_SLUGS.PHOTO_VIEILLISSEMENT,
      TAG_SLUGS.PEAU_MIXTE,
      TAG_SLUGS.PEAU_GRASSE,
      TAG_SLUGS.SOIN_DE_JOUR,
      TAG_SLUGS.SOIN_DE_NUIT,
      TAG_SLUGS.CREME_HYDRATANTE,
      TAG_SLUGS.SEBO_REGULATEUR,
      TAG_SLUGS.MATIFIANT,
    ],
    secondary: [
      TAG_SLUGS.MICROBIOME,
      TAG_SLUGS.HUMECTANT,
      TAG_SLUGS.ANTI_OXYDANT,
      TAG_SLUGS.TEXTURE_LEGERE,
    ],
    avoid: [TAG_SLUGS.PEAU_SECHE, TAG_SLUGS.TEXTURE_RICHE],
  },

  [SVR_PRODUCT_SLUGS.SVR_HYALU_BIOTIC]: {
    primary: [
      TAG_SLUGS.REPULPANT,
      TAG_SLUGS.DESHYDRATATION,
      TAG_SLUGS.ANTI_AGE,
      TAG_SLUGS.ECLAT,
      TAG_SLUGS.PEAU_NORMALE,
      TAG_SLUGS.PEAU_MIXTE,
      TAG_SLUGS.SOIN_DE_JOUR,
      TAG_SLUGS.SOIN_DE_NUIT,
      TAG_SLUGS.CREME_HYDRATANTE,
    ],
    secondary: [
      TAG_SLUGS.MICROBIOME,
      TAG_SLUGS.HUMECTANT,
      TAG_SLUGS.ANTI_OXYDANT,
      TAG_SLUGS.TEXTURE_LEGERE,
    ],
    avoid: [TAG_SLUGS.PEAU_SECHE],
  },

  [SVR_PRODUCT_SLUGS.SVR_CLAIRIAL_AMPOULE]: {
    primary: [
      TAG_SLUGS.ANTI_TACHES,
      TAG_SLUGS.HYPERPIGMENTATION,
      TAG_SLUGS.ECLAT,
      TAG_SLUGS.TEINT_TERNE,
      TAG_SLUGS.POST_ACNE,
      TAG_SLUGS.POLLUTION,
      TAG_SLUGS.SERUM,
      TAG_SLUGS.SOIN_DE_JOUR,
    ],
    secondary: [TAG_SLUGS.ANTI_OXYDANT, TAG_SLUGS.HUMECTANT],
    avoid: [TAG_SLUGS.PEAU_SENSIBLE, TAG_SLUGS.PEAU_REACTIVE, TAG_SLUGS.ROSACEE],
  },

  [SVR_PRODUCT_SLUGS.SVR_CLAIRIAL_SERUM]: {
    primary: [
      TAG_SLUGS.ANTI_TACHES,
      TAG_SLUGS.HYPERPIGMENTATION,
      TAG_SLUGS.ECLAT,
      TAG_SLUGS.TEINT_TERNE,
      TAG_SLUGS.POST_ACNE,
      TAG_SLUGS.SERUM,
      TAG_SLUGS.SOIN_DE_JOUR,
    ],
    secondary: [TAG_SLUGS.ANTI_OXYDANT, TAG_SLUGS.HUMECTANT],
    avoid: [TAG_SLUGS.PEAU_SENSIBLE, TAG_SLUGS.PEAU_REACTIVE, TAG_SLUGS.ROSACEE],
  },

  [SVR_PRODUCT_SLUGS.SVR_CLAIRIAL_CREME_SPF50]: {
    primary: [
      TAG_SLUGS.ANTI_TACHES,
      TAG_SLUGS.HYPERPIGMENTATION,
      TAG_SLUGS.PROTECTION_SOLAIRE,
      TAG_SLUGS.SOLAIRE_VISAGE,
      TAG_SLUGS.PHOTO_VIEILLISSEMENT,
      TAG_SLUGS.LUMIERE_BLEUE,
      TAG_SLUGS.SOIN_DE_JOUR,
      TAG_SLUGS.MATIFIANT,
    ],
    secondary: [TAG_SLUGS.FILTRES_CHIMIQUES, TAG_SLUGS.NON_COMEDOGENE],
    avoid: [
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.PEAU_REACTIVE,
      TAG_SLUGS.ROSACEE,
      TAG_SLUGS.FILTRES_MINERAUX,
    ],
  },

  [SVR_PRODUCT_SLUGS.SVR_CLAIRIAL_DAY]: {
    primary: [
      TAG_SLUGS.ANTI_TACHES,
      TAG_SLUGS.HYPERPIGMENTATION,
      TAG_SLUGS.PROTECTION_SOLAIRE,
      TAG_SLUGS.SOLAIRE_VISAGE,
      TAG_SLUGS.SOLAIRE_TEINTE,
      TAG_SLUGS.PHOTO_VIEILLISSEMENT,
      TAG_SLUGS.LUMIERE_BLEUE,
      TAG_SLUGS.POLLUTION,
      TAG_SLUGS.SOIN_DE_JOUR,
      TAG_SLUGS.ECLAT,
    ],
    secondary: [TAG_SLUGS.FILTRES_CHIMIQUES, TAG_SLUGS.ANTI_OXYDANT],
    avoid: [
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.PEAU_REACTIVE,
      TAG_SLUGS.ROSACEE,
      TAG_SLUGS.FILTRES_MINERAUX,
    ],
  },

  [SVR_PRODUCT_SLUGS.SVR_CLAIRIAL_NIGHT_PEEL]: {
    primary: [
      TAG_SLUGS.ANTI_TACHES,
      TAG_SLUGS.HYPERPIGMENTATION,
      TAG_SLUGS.ECLAT,
      TAG_SLUGS.TEINT_TERNE,
      TAG_SLUGS.POST_ACNE,
      TAG_SLUGS.SOIN_DE_NUIT,
      TAG_SLUGS.EXFOLIANT,
      TAG_SLUGS.KERATOLYTIQUE,
    ],
    secondary: [TAG_SLUGS.HUMECTANT, TAG_SLUGS.ANTI_OXYDANT],
    avoid: [
      TAG_SLUGS.PEAU_SENSIBLE,
      TAG_SLUGS.PEAU_REACTIVE,
      TAG_SLUGS.ROSACEE,
      TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE,
      TAG_SLUGS.GROSSESSE_COMPATIBLE,
    ],
  },

  [SVR_PRODUCT_SLUGS.SVR_DENSITIUM_BI_SERUM]: {
    primary: [
      TAG_SLUGS.ANTI_AGE,
      TAG_SLUGS.REPULPANT,
      TAG_SLUGS.DESHYDRATATION,
      TAG_SLUGS.PHOTO_VIEILLISSEMENT,
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.PEAU_NORMALE,
      TAG_SLUGS.SERUM,
      TAG_SLUGS.SOIN_DE_JOUR,
      TAG_SLUGS.SOIN_DE_NUIT,
    ],
    secondary: [
      TAG_SLUGS.HUMECTANT,
      TAG_SLUGS.EMOLLIENT,
      TAG_SLUGS.ANTI_OXYDANT,
      TAG_SLUGS.TEXTURE_RICHE,
    ],
    avoid: [TAG_SLUGS.PEAU_GRASSE, TAG_SLUGS.PEAU_MIXTE, TAG_SLUGS.BRILLANCE, TAG_SLUGS.ANTI_ACNE],
  },

  [SVR_PRODUCT_SLUGS.SVR_DENSITIUM_CREME]: {
    primary: [
      TAG_SLUGS.ANTI_AGE,
      TAG_SLUGS.REPULPANT,
      TAG_SLUGS.DESHYDRATATION,
      TAG_SLUGS.ECLAT,
      TAG_SLUGS.TEINT_TERNE,
      TAG_SLUGS.PHOTO_VIEILLISSEMENT,
      TAG_SLUGS.PEAU_SECHE,
      TAG_SLUGS.PEAU_NORMALE,
      TAG_SLUGS.SOIN_DE_JOUR,
      TAG_SLUGS.SOIN_DE_NUIT,
      TAG_SLUGS.CREME_HYDRATANTE,
    ],
    secondary: [TAG_SLUGS.HUMECTANT, TAG_SLUGS.EMOLLIENT, TAG_SLUGS.TEXTURE_RICHE],
    avoid: [TAG_SLUGS.PEAU_GRASSE, TAG_SLUGS.PEAU_MIXTE, TAG_SLUGS.BRILLANCE, TAG_SLUGS.ANTI_ACNE],
  },

  [SVR_PRODUCT_SLUGS.SVR_DENSITIUM_YEUX]: {
    primary: [
      TAG_SLUGS.CERNES_POCHES,
      TAG_SLUGS.ANTI_AGE,
      TAG_SLUGS.REPULPANT,
      TAG_SLUGS.CONTOUR_YEUX,
    ],
    secondary: [TAG_SLUGS.HUMECTANT, TAG_SLUGS.EMOLLIENT, TAG_SLUGS.ANTI_OXYDANT],
    avoid: [TAG_SLUGS.ANTI_ACNE],
  },
}
