export const SVR_PRODUCT_SLUGS = {
  // Sensifine
  SVR_SENSIFINE_AR_SPF50: 'svr-sensifine-ar-creme-spf50',
  SVR_SENSIFINE_AR: 'svr-sensifine-ar-creme',
  SVR_SENSIFINE_EXTREME: 'svr-sensifine-extreme-creme-apaisante',
  SVR_SENSIFINE_HUILE_NUIT: 'svr-sensifine-huile-de-nuit-reparatrice',
  SVR_SENSIFINE_MASQUE_SOS: 'svr-sensifine-masque-sos-apaisant',
  SVR_SENSIFINE_NUTRI_BAUME: 'svr-sensifine-nutri-baume-nourrissant',
  SVR_SENSIFINE_BAUME_DEMAQUILLANT: 'svr-sensifine-baume-demaquillant',
  SVR_SENSIFINE_AQUA_GEL: 'svr-sensifine-aqua-gel-hydratant',
  SVR_SENSIFINE_DERMO_NETTOYANT: 'svr-sensifine-dermo-nettoyant-haute-tolerance',
  SVR_SENSIFINE_HYDRA_CREME: 'svr-sensifine-hydra-creme-hydratante',

  // Cicavit
  SVR_CICAVIT_PLUS_CREME_HPPI: 'svr-cicavit-plus-creme-hppi',
  SVR_CICAVIT_GEL_MOUSSANT: 'svr-cicavit-gel-moussant',
  SVR_CICAVIT_CREME_MAINS: 'svr-cicavit-creme-mains',
  SVR_CICAVIT_CREME_SPF50: 'svr-cicavit-creme-spf50',
  SVR_CICAVIT_BAUME_LEVRES: 'svr-cicavit-baume-levres',
  SVR_CICAVIT_SOS_GRATTAGE: 'svr-cicavit-sos-grattage',
  SVR_CICAVIT_DM_PLUS: 'svr-cicavit-dm-plus',

  // Sebiaclear
  SVR_SEBIACLEAR_FLASH_15: 'svr-sebiaclear-ampoule-flash-15-azelaic-acid',
  SVR_SEBIACLEAR_GEL_FLASH_4H: 'svr-sebiaclear-gel-flash-4h',
  SVR_SEBIACLEAR_SPRAY_CORPS: 'svr-sebiaclear-spray-corps',
  SVR_SEBIACLEAR_MICRO_PEEL: 'svr-sebiaclear-micro-peel',
  SVR_SEBIACLEAR_GEL_MOUSSANT: 'svr-sebiaclear-gel-moussant',
  SVR_SEBIACLEAR_SERUM: 'svr-sebiaclear-serum',
  SVR_SEBIACLEAR_CREME_LAVANTE: 'svr-sebiaclear-creme-lavante',
  SVR_SEBIACLEAR_HYDRA: 'svr-sebiaclear-hydra',
  SVR_SEBIACLEAR_ACTIVE_GEL: 'svr-sebiaclear-active-gel',
  SVR_SEBIACLEAR_MAT_PORES: 'svr-sebiaclear-mat-pores',
  SVR_SEBIACLEAR_CREME_SPF50: 'svr-sebiaclear-creme-spf50',
  SVR_SEBIACLEAR_EAU_MICELLAIRE: 'svr-sebiaclear-eau-micellaire',
  SVR_SEBIACLEAR_ACTIVE_TEINTE: 'svr-sebiaclear-active-teinte',

  // Topialyse
  SVR_TOPIALYSE_BAUME_PROTECT: 'svr-topialyse-baume-protect-plus',
  SVR_TOPIALYSE_CREME: 'svr-topialyse-creme-nourrissante',
  SVR_TOPIALYSE_HUILE_LAVANTE: 'svr-topialyse-huile-lavante-relipidante',
  SVR_TOPIALYSE_GEL_LAVANT: 'svr-topialyse-gel-lavant-doux',
  SVR_TOPIALYSE_BAUME_LAVANT: 'svr-topialyse-baume-lavant-apaisant',
  SVR_TOPIALYSE_CONCENTRE_LAVANT: 'svr-topialyse-concentre-lavant-pate-a-mousser',
  SVR_TOPIALYSE_BARRIERE: 'svr-topialyse-barriere-creme-isolante',
  SVR_TOPIALYSE_MAINS: 'svr-topialyse-mains-nourrissant',

  // Xérial
  SVR_XERIAL_10_LAIT: 'svr-xerial-10-lait-corps-hydratant',
  SVR_XERIAL_50_EXTREME_PIEDS: 'svr-xerial-50-extreme-creme-pieds',
  SVR_XERIAL_FISSURES_CREVASSES: 'svr-xerial-fissures-crevasses-reparateur',
  SVR_XERIAL_30_GEL_CREME: 'svr-xerial-30-gel-creme-lissant',
  SVR_XERIAL_DM_PSORIASIS: 'svr-xerial-dm-psoriasis-dispositif-medical',
  SVR_XERIAL_30_PIEDS: 'svr-xerial-30-creme-pieds-quotidien',

  // Autres gammes
  SVR_C20_BIOTIC: 'svr-c20-biotic-regenerating-radiance-cream',
  SVR_C20_FLUIDE: 'svr-c20-fluide',
  SVR_AMPOULE_A_LIFT: 'svr-ampoule-a-lift-resurfacant-retinol',
  SVR_C_EYE_BIOTIC: 'svr-c-eye-biotic',
  SVR_COLLAGEN_BIOTIC: 'svr-collagen-biotic',
  SVR_FILLER_BIOTIC: 'svr-filler-biotic',
  SVR_PEPTI_BIOTIC: 'svr-pepti-biotic',
  SVR_HYALU_BIOTIC: 'svr-hyalu-biotic',

  // Clairial
  SVR_CLAIRIAL_AMPOULE: 'svr-clairial-ampoule',
  SVR_CLAIRIAL_SERUM: 'svr-clairial-serum',
  SVR_CLAIRIAL_CREME_SPF50: 'svr-clairial-creme-spf50',
  SVR_CLAIRIAL_DAY: 'svr-clairial-day',
  SVR_CLAIRIAL_NIGHT_PEEL: 'svr-clairial-night-peel',

  // Densitium
  SVR_DENSITIUM_BI_SERUM: 'svr-densitium-bi-serum',
  SVR_DENSITIUM_CREME: 'svr-densitium-creme',
  SVR_DENSITIUM_YEUX: 'svr-densitium-yeux',
}
export const SVR_PRODUCT_DATA = [
  {
    name: 'Sensifine Extrême',
    brand: 'SVR',
    kind: 'skincare',
    unit: 'pump',
    slug: SVR_PRODUCT_SLUGS.SVR_SENSIFINE_EXTREME,
    totalAmount: 30,
    amountUnit: 'ml',
    priceCents: 2150,
    description:
      'Soin apaisant ultra-minimaliste pour peaux intolérantes. Formule à 6 ingrédients pour une efficacité immédiate sur les inconforts.',
    notes:
      'Eau ionisée brevetée. Huile de jojoba. Sans parfum ni conservateur. Peaux agressées et irritées.',
    inci: 'AQUA/WATER, OCTYLDODECANOL, SIMMONDSIA CHINENSIS (JOJOBA) SEED OIL, HYDROXYETHYL ACRYLATE/SODIUM ACRYLOYLDIMETHYL TAURATE COPOLYMER, MINERAL SALTS, SORBITAN ISOSTEARATE',
    url: 'https://www.labo-svr.com',
  },
  {
    name: 'Sensifine Huile de Nuit',
    brand: 'SVR',
    kind: 'skincare',
    unit: 'dropper',
    slug: SVR_PRODUCT_SLUGS.SVR_SENSIFINE_HUILE_NUIT,
    totalAmount: 30,
    amountUnit: 'ml',
    priceCents: 1990,
    description:
      'Huile de nuit minimaliste de 10 ingrédients pour apaiser, réparer et nourrir les peaux poly-allergiques.',
    notes: 'Texture soyeuse non grasse. Huiles de jojoba, colza et chanvre. Sans parfum.',
    inci: 'BRASSICA CAMPESTRIS (RAPESEED) SEED OIL, COCO-CAPRYLATE/CAPRATE, VITIS VINIFERA (GRAPE) SEED OIL, PRUNUS AMYGDALUS DULCIS (SWEET ALMOND) OIL, CANNABIS SATIVA SEED OIL, COCOS NUCIFERA (COCONUT) OIL, SIMMONDSIA CHINENSIS (JOJOBA) SEED OIL, TOCOPHEROL',
    url: 'https://www.labo-svr.com',
  },
  {
    name: 'Sensifine Masque SOS',
    brand: 'SVR',
    kind: 'skincare',
    unit: 'tube',
    slug: SVR_PRODUCT_SLUGS.SVR_SENSIFINE_MASQUE_SOS,
    totalAmount: 75,
    amountUnit: 'ml',
    priceCents: 1500,
    description:
      'Masque apaisant immédiat sans rinçage pour peaux en crise. Formule concentrée pour calmer les irritations en 10 minutes.',
    notes: 'Vitamine B12. Huile de babassu. Panthénol. Sans parfum.',
    inci: 'AQUA/WATER, ORBIGNYA OLEIFERA SEED OIL, GLYCERIN, CETYL ALCOHOL, 1,2-HEXANEDIOL, SODIUM POLYACRYLATE, CYANOCOBALAMIN, PANTHENOL, PENTAERYTHRITYL TETRA-DI-T-BUTYL HYDROXYHYDROCINNAMATE, CAPRYLYL GLYCOL',
    url: 'https://www.labo-svr.com',
  },
  {
    name: 'Sensifine Nutri-Baume',
    brand: 'SVR',
    kind: 'skincare',
    unit: 'pump',
    slug: SVR_PRODUCT_SLUGS.SVR_SENSIFINE_NUTRI_BAUME,
    totalAmount: 40,
    amountUnit: 'ml',
    priceCents: 1690,
    description:
      'Soin fondant nourrissant aux 10 ingrédients pour peaux fragiles et hypersensibles. Hydratation 24h.',
    notes: 'Beurre de karité. Squalane. Panthénol. Utilisable sur les mains.',
    inci: 'AQUA/WATER, BUTYROSPERMUM PARKII (SHEA) BUTTER, SQUALANE, BEHENYL ALCOHOL, BEHENETH-25, 1,2-HEXANEDIOL, PANTHENOL, CAPRYLYL GLYCOL, CITRIC ACID, SODIUM POLYACRYLATE',
    url: 'https://www.labo-svr.com',
  },
  {
    name: 'Sensifine Baume démaquillant',
    brand: 'SVR',
    kind: 'skincare',
    unit: 'jar',
    slug: SVR_PRODUCT_SLUGS.SVR_SENSIFINE_BAUME_DEMAQUILLANT,
    totalAmount: 100,
    amountUnit: 'g',
    priceCents: 1550,
    description:
      'Baume en huile minimaliste de 9 ingrédients pour démaquiller en profondeur les peaux sensibles.',
    notes: 'Efficace sur maquillage waterproof. Beurre de karité et huile de coco. Parfum coco.',
    inci: 'ISOPROPYL PALMITATE, BUTYROSPERMUM PARKII (SHEA) BUTTER, COCOS NUCIFERA (COCONUT) OIL, C10-18 TRIGLYCERIDES, PEG-7 GLYCERYL COCOATE, HELIANTHUS ANNUUS (SUNFLOWER) SEED WAX, HYDROGENATED VEGETABLE OIL, PENTAERYTHRITYL TETRA-DI-T-BUTYL HYDROXYHYDROCINNAMATE, CITRIC ACID',
    url: 'https://www.labo-svr.com',
  },
  {
    name: 'Sensifine Aqua-Gel',
    brand: 'SVR',
    kind: 'skincare',
    unit: 'pump',
    slug: SVR_PRODUCT_SLUGS.SVR_SENSIFINE_AQUA_GEL,
    totalAmount: 40,
    amountUnit: 'ml',
    priceCents: 1690,
    description:
      'Gel ultra-frais minimaliste de 8 ingrédients pour peaux polyallergiques. Hydratation 12h.',
    notes: 'Aloe Vera. Panthénol. Texture gel non grasse.',
    inci: 'AQUA/WATER, GLYCERIN, 1,2-HEXANEDIOL, ALOE BARBADENSIS LEAF JUICE POWDER, PANTHENOL, ACRYLATES/C10-30 ALKYL ACRYLATE CROSSPOLYMER, CAPRYLYL GLYCOL, SODIUM HYDROXIDE',
    url: 'https://www.labo-svr.com',
  },
  {
    name: 'Sensifine Dermo-Nettoyant',
    brand: 'SVR',
    kind: 'skincare',
    unit: 'pump',
    slug: SVR_PRODUCT_SLUGS.SVR_SENSIFINE_DERMO_NETTOYANT,
    totalAmount: 400,
    amountUnit: 'ml',
    priceCents: 1650,
    description:
      'Nettoyant et démaquillant haute tolérance pour peaux intolérantes. Formule 9 ingrédients sans rinçage.',
    notes: 'Niacinamide. Texture gel-crème. Waterproof.',
    inci: 'AQUA/WATER, HEXYLDECYL STEARATE, PROPANEDIOL, NIACINAMIDE, 1,2-HEXANEDIOL, AMMONIUM ACRYLOYLDIMETHYLTAURATE/VP COPOLYMER, CAPRYLYL GLYCOL, PENTYLENE GLYCOL, XANTHAN GUM',
    url: 'https://www.labo-svr.com',
  },
  {
    name: 'Sensifine Hydra-Crème',
    brand: 'SVR',
    kind: 'skincare',
    unit: 'pump',
    slug: SVR_PRODUCT_SLUGS.SVR_SENSIFINE_HYDRA_CREME,
    totalAmount: 40,
    amountUnit: 'ml',
    priceCents: 1690,
    description: 'Soin minimaliste hydratant 24h pour peaux normales à sèches hypersensibles.',
    notes: '5% Panthénol. Huile de pépins de raisin. Sans parfum.',
    inci: 'AQUA/WATER, VITIS VINIFERA (GRAPE) SEED OIL, HEXYLDECYL STEARATE, PANTHENOL, 1,2-HEXANEDIOL, SODIUM POLYACRYLATE, CAPRYLYL GLYCOL, TOCOPHEROL, CITRIC ACID, HELIANTHUS ANNUUS (SUNFLOWER) SEED OIL',
    url: 'https://www.labo-svr.com',
  },
  {
    name: 'Topialyse Baume Protect+',
    brand: 'SVR',
    kind: 'skincare',
    unit: 'pump',
    slug: SVR_PRODUCT_SLUGS.SVR_TOPIALYSE_BAUME_PROTECT,
    totalAmount: 400,
    amountUnit: 'ml',
    priceCents: 2490,
    description:
      'Soin relipidant protecteur anti-grattage pour peaux très sèches à atopiques. Protège contre les agressions extérieures.',
    notes: 'Céramides AD brevetés. Sucre prébiotique. 46% phase grasse.',
    inci: 'AQUA/WATER, HELIANTHUS ANNUUS (SUNFLOWER) SEED OIL, COCOS NUCIFERA (COCONUT) OIL, ORBIGNYA OLEIFERA SEED OIL, RICINUS COMMUNIS (CASTOR) SEED OIL, CETEARYL ALCOHOL, HYDROGENATED CASTOR OIL, GLYCERIL STEARATE SE, PENTYLENE GLYCOL, CETEARYL GLUCOSIDE, SODIUM STEAROYL GLUTAMATE, OPHIOPOGON JAPONICUS ROOT EXTRACT, 1,2-HEXANEDIOL, CAPRYLYL GLYCOL, ACRYLATES/C10-30 ALKYL ACRYLATE CROSSPOLYMER, MALTODEXTRIN, PENTAERYTHRITYL TETRA-DI-T-BUTYL HYDROXYHYDROCINNAMATE, GLYCOSPHINGOLIPIDS, CITRIC ACID, GLYCOLIPIDS',
    url: 'https://www.labo-svr.com',
  },
  {
    name: 'Topialyse Crème',
    brand: 'SVR',
    kind: 'bodycare',
    unit: 'tube',
    slug: SVR_PRODUCT_SLUGS.SVR_TOPIALYSE_CREME,
    totalAmount: 200,
    amountUnit: 'ml',
    priceCents: 1630,
    description: 'Soin nourrissant et hydratant longue durée pour peaux sèches et sensibles.',
    notes: '27% phase émolliente. Babassu, Karité, Bourrache. Parfum.',
    inci: 'AQUA/WATER, BUTYROSPERMUM PARKII (SHEA) BUTTER, ORBIGNYA OLEIFERA SEED OIL, GLYCERIN, C10-18 TRIGLYCERIDES, COCOS NUCIFERA (COCONUT) OIL, PENTYLENE GLYCOL, GLYCERYL STEARATE CITRATE, GLYCERYL STEARATE SE, BORAGO OFFICINALIS SEED OIL, GLYCERYL GLUCOSIDE, GLYCINE SOJA (SOYBEAN) OIL, SODIUM STEAROYL GLUTAMATE, ALPHA-GLUCAN OLIGOSACCHARIDE, TOCOPHEROL, 1,2-HEXANEDIOL, ACRYLATES/C10-30 ALKYL ACRYLATE CROSSPOLYMER, CAPRYLYL GLYCOL, CITRIC ACID, SODIUM HYDROXIDE, PARFUM',
    url: 'https://www.labo-svr.com',
  },
  {
    name: 'Topialyse Huile Lavante',
    brand: 'SVR',
    kind: 'bodycare',
    unit: 'pump',
    slug: SVR_PRODUCT_SLUGS.SVR_TOPIALYSE_HUILE_LAVANTE,
    totalAmount: 1000,
    amountUnit: 'ml',
    priceCents: 1950,
    description:
      'Huile lavante relipidante anti-irritations pour toute la famille. Nettoie en douceur les peaux sèches à atopiques.',
    notes: '35% actifs relipidants. Niacinamide. Prébiotique.',
    inci: 'AQUA/WATER, GLYCERIN, SODIUM C14-16 OLEFIN SULFONATE, SODIUM LAUROAMPHOACETATE, COCO-BETAINE, NIACINAMIDE, CITRIC ACID, SODIUM OLIVAMPHOACETATE, ALPHA-GLUCAN OLIGOSACCHARIDE, PARFUM, SACCHARIDE ISOMERATE, CAPRYLYL/CAPRYL GLUCOSIDE, SODIUM BENZOATE, POTASSIUM SORBATE, POLYGLYCERYL-3 COCOATE, POLYGLYCERYL-10 LAURATE, GOSSYPIUM HERBACEUM (COTTON) SEED OIL, SODIUM CITRATE',
    url: 'https://www.labo-svr.com',
  },
  {
    name: 'Topialyse Gel Lavant',
    brand: 'SVR',
    kind: 'bodycare',
    unit: 'pump',
    slug: SVR_PRODUCT_SLUGS.SVR_TOPIALYSE_GEL_LAVANT,
    totalAmount: 1000,
    amountUnit: 'ml',
    priceCents: 1250,
    description:
      'Nettoyant doux protecteur anti-dessèchement. Hydratation 24h pour peaux sensibles.',
    notes: 'Glycérine végétale. Tensio-actifs doux. pH physiologique.',
    inci: 'AQUA/WATER, SODIUM C14-16 OLEFIN SULFONATE, COCO-GLUCOSIDE, COCO-BETAINE, GLYCERIN, PARFUM, CITRIC ACID, SODIUM BENZOATE, POTASSIUM SORBATE, SODIUM PHYTATE',
    url: 'https://www.labo-svr.com',
  },
  {
    name: 'Topialyse Baume Lavant',
    brand: 'SVR',
    kind: 'bodycare',
    unit: 'pump',
    slug: SVR_PRODUCT_SLUGS.SVR_TOPIALYSE_BAUME_LAVANT,
    totalAmount: 400,
    amountUnit: 'ml',
    priceCents: 1730,
    description:
      'Soin lavant apaisant et nourrissant pour peaux très sèches à atopiques. Texture crémeuse anti-grattage.',
    notes: '35% actifs hydratants. Niacinamide. Sucre prébiotique. Sans parfum.',
    inci: 'AQUA/WATER, GLYCERIN, SODIUM C14-16 OLEFIN SULFONATE, COCO-BETAINE, COCO-GLUCOSIDE, ACRYLATES/C10-30 ALKYL ACRYLATE CROSSPOLYMER, NIACINAMIDE, TRIDECETH-50, ALPHA-GLUCAN OLIGOSACCHARIDE, SACCHARIDE ISOMERATE, TOCOPHEROL, TOCOPHERYL ACETATE, 1,2-HEXANEDIOL, CAPRYLYL GLYCOL, CITRIC ACID, COCOS NUCIFERA (COCONUT) OIL, GLYCERYL OLEATE, GOSSYPIUM HERBACEUM (COTTON) SEED OIL, HYDROGENATED PALM GLYCERIDES CITRATE, PENTYLENE GLYCOL, SODIUM CITRATE, SODIUM HYDROXIDE, SODIUM LAURETH SULFATE, STYRENE/ACRYLATES COPOLYMER',
    url: 'https://www.labo-svr.com',
  },
  {
    name: 'Topialyse Concentré Lavant',
    brand: 'SVR',
    kind: 'bodycare',
    unit: 'tube',
    slug: SVR_PRODUCT_SLUGS.SVR_TOPIALYSE_CONCENTRE_LAVANT,
    totalAmount: 100,
    amountUnit: 'g',
    priceCents: 1550,
    description:
      'Pâte à mousser concentrée sans eau équivalente à 400ml de gel lavant. Format nomade écologique.',
    notes: '16% phase émolliente. Niacinamide. Huile de coco et bourrache.',
    inci: 'GLYCERIN, SODIUM LAUROYL GLUTAMATE, CAPRYLIC/CAPRIC TRIGLYCERIDE, COCOS NUCIFERA (COCONUT) LIQUID ENDOSPERM, SODIUM METHYL OLEOYL TAURATE, COCOS NUCIFERA (COCONUT) OIL, PROPANEDIOL, SODIUM C14/16 OLEFIN SULFONATE, SODIUM CHLORIDE, PARFUM, CITRIC ACID, BORAGO OFFICINALIS SEED OIL, NIACINAMIDE, COCOS NUCIFERA (COCONUT) FRUIT JUICE, GLYCERYL GLUCOSIDE, LECITHIN, ALPHA-GLUCAN OLIGOSACCHARIDE, HELIANTHUS ANNUUS (SUNFLOWER) SEED OIL, TOCOPHEROL, SODIUM ACRYLATES COPOLYMER, SODIUM CITRATE, SODIUM PHYTATE, POTASSIUM SORBATE, SODIUM BENZOATE',
    url: 'https://www.labo-svr.com',
  },
  {
    name: 'Topialyse Barrière',
    brand: 'SVR',
    kind: 'skincare',
    unit: 'tube',
    slug: SVR_PRODUCT_SLUGS.SVR_TOPIALYSE_BARRIERE,
    totalAmount: 50,
    amountUnit: 'ml',
    priceCents: 1030,
    description:
      'Crème barrière isolante et réparatrice pour zones réactives et irritées. Protège contre les agressions quotidiennes.',
    notes: 'Acide hyaluronique. Oméga 3, 6, 9. Acide glycyrrhizique. Sans parfum.',
    inci: 'AQUA/WATER, HYDROGENATED POLYDECENE, GLYCERIN, ETHYLHEXYL STEARATE, CETEARYL ALCOHOL, DIMETHICONE, CRAMBE ABYSSINICA SEED OIL, POLYESTER-7, GLYCERYL STEARATE, XYLITYLGLUCOSIDE, NEOPENTYL GLYCOL DIHEPTANOATE, 1,2-HEXANEDIOL, BEHENYL ALCOHOL, C10-18 TRIGLYCERIDES, AMINOPROPANEDIOL, CETEARETH-33, DIPOTASSIUM GLYCYRRHIZATE, ELAEIS GUINEENSIS (PALM) OIL, OLEYL ALCOHOL, PHYTOSTEROLS, ANHYDROXYLITOL, CAMELINA SATIVA SEED OIL, HYDROLYZED RICE PROTEIN, SODIUM HYALURONATE, TOCOPHERYL ACETATE, XYLITOL, TRIETHANOLAMINE, AMMONIUM ACRYLOYLDIMETHYLTAURATE/VP COPOLYMER, CETETH-20, CETYL ALCOHOL, DISODIUM EDTA, PEG-75 STEARATE, STEARETH-20, CHLORPHENESIN, PHENOXYETHANOL',
    url: 'https://www.labo-svr.com',
  },
  {
    name: 'Topialyse Mains',
    brand: 'SVR',
    kind: 'bodycare',
    unit: 'tube',
    slug: SVR_PRODUCT_SLUGS.SVR_TOPIALYSE_MAINS,
    totalAmount: 50,
    amountUnit: 'ml',
    priceCents: 600,
    description: 'Soin nourrissant et régénérant pour mains desséchées et abîmées.',
    notes: '27% phase grasse. 7% Beurre de karité. Oméga 3, 6, 9.',
    inci: 'AQUA/WATER, ETHYLHEXYL STEARATE, BUTYROSPERMUM PARKII (SHEA) BUTTER, GLYCERYL STEARATE, CAPRYLIC/CAPRIC TRIGLYCERIDE, GLYCERIN, PEG-100 STEARATE, AMMONIUM ACRYLOYLDIMETHYLTAURATE/VP COPOLYMER, CAMELINA SATIVA SEED OIL, HELIANTHUS ANNUUS (SUNFLOWER) SEED OIL, TOCOPHEROL, TOCOPHERYL ACETATE, 1,2-HEXANEDIOL, ARACHIDYL ALCOHOL, ARACHIDYL GLUCOSIDE, BEHENYL ALCOHOL, CITRIC ACID, O-CYMEN-5-OL, SODIUM BENZOATE, PARFUM',
    url: 'https://www.labo-svr.com',
  },
  {
    name: 'Xerial 10 Lait',
    brand: 'SVR',
    kind: 'bodycare',
    unit: 'pump',
    slug: SVR_PRODUCT_SLUGS.SVR_XERIAL_10_LAIT,
    totalAmount: 400,
    amountUnit: 'ml',
    priceCents: 2300,
    description: 'Lait corps lissant et hydratant 48h pour peaux rugueuses et squameuses.',
    notes: '10% Urée pure. Panthénol. Beurre de karité. Technologie Aquaporines.',
    inci: 'AQUA/WATER, UREA, COCOS NUCIFERA (COCONUT) OIL, GLYCERIN, BUTYROSPERMUM PARKII (SHEA) BUTTER, GLYCERYL STEARATE, CANOLA OIL, BORAGO OFFICINALIS SEED OIL, SILICA, PANTHENOL, PENTYLENE GLYCOL, GLYCERYL GLUCOSIDE, SODIUM CITRATE, TRIACETIN, SERINE, PARFUM, CITRIC ACID, HYDROXYETHYL ACRYLATE/SODIUM ACRYLOYLDIMETHYL TAURATE COPOLYMER, SODIUM STEAROYL GLUTAMATE, 1,2-HEXANEDIOL, CAPRYLYL GLYCOL, CARBOMER, SODIUM LACTATE, HISTIDINE, PROPYLENE GLYCOL, POLYSORBATE 60, SORBITAN ISOSTEARATE, BACILLUS FERMENT, POTASSIUM SORBATE',
    url: 'https://www.labo-svr.com',
  },
  {
    name: 'Xerial 50 Extrême Crème Pieds',
    brand: 'SVR',
    kind: 'bodycare',
    unit: 'tube',
    slug: SVR_PRODUCT_SLUGS.SVR_XERIAL_50_EXTREME_PIEDS,
    totalAmount: 50,
    amountUnit: 'ml',
    priceCents: 1600,
    description: 'Soin kératolytique intense pour pieds très secs avec callosités et durillons.',
    notes: '50% Urée pure. Acide salicylique. Texture non grasse.',
    inci: 'AQUA/WATER, UREA, GLYCERIN, BUTYROSPERMUM PARKII (SHEA) BUTTER, OCTYLDODECANOL, CETEARYL ETHYLHEXANOATE, ISOHEXADECANE, POLYACRYLATE-13, SILICA DIMETHYL SILYLATE, TRIETHANOLAMINE, PANTHENOL, SALICYLIC ACID, SERINE, ALLANTOIN, BACILLUS FERMENT, HISTIDINE, POLYISOBUTENE, OCTYLDODECYL XYLOSIDE, PEG-30 DIPOLYHYDROXYSTEARATE, POLYSORBATE 20, SORBITAN ISOSTEARATE, PROPYLENE GLYCOL, CITRIC ACID, DISODIUM EDTA, POTASSIUM SORBATE',
    url: 'https://www.labo-svr.com',
  },
  {
    name: 'Xerial Fissures & Crevasses',
    brand: 'SVR',
    kind: 'bodycare',
    unit: 'tube',
    slug: SVR_PRODUCT_SLUGS.SVR_XERIAL_FISSURES_CREVASSES,
    totalAmount: 50,
    amountUnit: 'ml',
    priceCents: 1290,
    description: 'Soin réparateur et isolant pour pieds abîmés, fissurés et fendillés.',
    notes: '15% Urée pure. Centella Asiatica. Panthénol. Prébiotique. Résultat en 24h.',
    inci: 'AQUA/WATER, GLYCERIN, UREA, COCOS NUCIFERA (COCONUT) OIL, SIMMONDSIA CHINENSIS (JOJOBA) SEED OIL, C12-16 ALCOHOLS, PANTHENOL, GLYCERYL STEARATE CITRATE, GLYCOL PALMITATE, HELIANTHUS ANNUUS (SUNFLOWER) SEED WAX, SILICA, PENTYLENE GLYCOL, MICROCRYSTALLINE CELLULOSE, 1,2-HEXANEDIOL, SODIUM POLYACRYLATE, GLYCERYL GLUCOSIDE, SODIUM CITRATE, HYDROGENATED LECITHIN, PALMITIC ACID, TRIACETIN, ALPHA-GLUCAN OLIGOSACCHARIDE, CETYL PALMITATE, SERINE, CITRIC ACID, CAPRYLYL GLYCOL, PENTAERYTHRITYL TETRA-DI-T-BUTYL HYDROXYHYDROCINNAMATE, SODIUM LACTATE, CELLULOSE GUM, ASIATICOSIDE, MADECASSIC ACID, HISTIDINE, ASIATIC ACID, PROPYLENE GLYCOL, BACILLUS FERMENT, POTASSIUM SORBATE',
    url: 'https://www.labo-svr.com',
  },
  {
    name: 'Xerial 30 Gel-Crème',
    brand: 'SVR',
    kind: 'bodycare',
    unit: 'tube',
    slug: SVR_PRODUCT_SLUGS.SVR_XERIAL_30_GEL_CREME,
    totalAmount: 75,
    amountUnit: 'ml',
    priceCents: 1550,
    description: 'Soin lissant anti-rugosités et poils incarnés. Hydratation 48h intense.',
    notes: '30% Urée pure. Panthénol. Sans parfum. Texture fondante.',
    inci: 'AQUA/WATER, UREA, COCOS NUCIFERA (COCONUT) OIL, GLYCERIN, OCTYLDODECANOL, HYDROXYETHYL ACRYLATE/SODIUM ACRYLOYLDIMETHYL TAURATE COPOLYMER, PANTHENOL, SILICA, PENTYLENE GLYCOL, GLYCERYL GLUCOSIDE, OCTYLDODECYL XYLOSIDE, PEG-30 DIPOLYHYDROXYSTEARATE, TRIACETIN, SERINE, 1,2-HEXANEDIOL, CAPRYLYL GLYCOL, SODIUM LACTATE, PROPYLENE GLYCOL, DISODIUM EDTA, POLYSORBATE 60, SORBITAN ISOSTEARATE, HISTIDINE, BACILLUS FERMENT, CITRIC ACID, POTASSIUM SORBATE',
    url: 'https://www.labo-svr.com',
  },
  {
    name: 'Xerial DM Psoriasis',
    brand: 'SVR',
    kind: 'skincare',
    unit: 'tube',
    slug: SVR_PRODUCT_SLUGS.SVR_XERIAL_DM_PSORIASIS,
    totalAmount: 200,
    amountUnit: 'ml',
    priceCents: 2690,
    description:
      'Dispositif médical pour le traitement des plaques, squames et démangeaisons du psoriasis vulgaris.',
    notes: '15% Urée pure. Exopolysaccharide marin. 27% agents émollients. Beurre de karité.',
    inci: 'AQUA/WATER, UREA, BUTYROSPERMUM PARKII (SHEA) BUTTER, ORBIGNYA OLEIFERA SEED OIL, CAPRYLIC/CAPRIC TRIGLYCERIDE, DIMETHICONE, GLYCERIN, PROPANEDIOL, GLYCOL PALMITATE, GLYCERYL STEARATE, PEG-100 STEARATE, MYRISTYL ALCOHOL, CAMELINA SATIVA SEED OIL, HYDROXYETHYL ACRYLATE/SODIUM ACRYLOYLDIMETHYL TAURATE COPOLYMER, CERA ALBA, SODIUM CITRATE, TRIACETIN, MYRISTYL GLUCOSIDE, PENTYLENE GLYCOL, POLYACRYLATE CROSSPOLYMER-6, DIMETHICONE CROSSPOLYMER, CITRIC ACID, TOCOPHEROL, 1,2-HEXANEDIOL, CAPRYLYL GLYCOL, PARFUM, CALCIUM PCA, SODIUM LACTATE, GLYCINE SOJA (SOYBEAN) OIL, STEARYL STEARATE, STEARYL PALMITATE, HYDROLYZED HYALURONIC ACID, PARAFFIN, POLYSORBATE 60, SORBITAN ISOSTEARATE, CETYL PALMITATE, CETYL STEARATE, SACCHARIDE ISOMERATE, BEHENIC ACID, STEARIC ACID, CERA MICROCRISTALLINA, ARACHIDIC ACID, PALMITIC ACID, HELIANTHUS ANNUUS (SUNFLOWER) SEED OIL',
    url: 'https://www.labo-svr.com',
  },
  {
    name: 'Xerial 30 Crème Pieds',
    brand: 'SVR',
    kind: 'bodycare',
    unit: 'tube',
    slug: SVR_PRODUCT_SLUGS.SVR_XERIAL_30_PIEDS,
    totalAmount: 50,
    amountUnit: 'ml',
    priceCents: 1350,
    description: 'Soin pieds quotidien nourrissant et lissant. Prévient callosités et rugosités.',
    notes: '30% Urée pure. 1% Acide salicylique. Panthénol. Allantoïne.',
    inci: 'AQUA/WATER, UREA, GLYCERIN, BUTYROSPERMUM PARKII (SHEA) BUTTER, OCTYLDODECANOL, CETEARYL ETHYLHEXANOATE, ISOHEXADECANE, POLYACRYLATE-13, SILICA DIMETHYL SILYLATE, TRIETHANOLAMINE, PANTHENOL, SALICYLIC ACID, SERINE, ALLANTOIN, BACILLUS FERMENT, HISTIDINE, POLYISOBUTENE, OCTYLDODECYL XYLOSIDE, PEG-30 DIPOLYHYDROXYSTEARATE, POLYSORBATE 20, SORBITAN ISOSTEARATE, PROPYLENE GLYCOL, CITRIC ACID, DISODIUM EDTA, POTASSIUM SORBATE',
    url: 'https://www.labo-svr.com',
  },
  {
    name: '[A] Ampoule Lift',
    brand: 'SVR',
    kind: 'skincare',
    unit: 'dropper',
    slug: SVR_PRODUCT_SLUGS.SVR_AMPOULE_A_LIFT,
    totalAmount: 30,
    amountUnit: 'ml',
    priceCents: 3690,
    description:
      'Sérum resurfaçant concentré en vitamine A pour lisser le grain de peau, les rides et resserrer les pores.',
    notes: '0.3% Rétinol pur. 2% NovoRetin. Niacinamide. Céramides.',
    inci: 'AQUA/WATER, GLYCERIN, CAPRYLIC/CAPRIC TRIGLYCERIDE, RETINOL, PENTYLENE GLYCOL, NIACINAMIDE, ...', // INCI tronqué car non fourni complet pour ce produit
    url: 'https://www.labo-svr.com',
  },
  {
    name: 'Sebiaclear Ampoule Flash 15%',
    brand: 'SVR',
    kind: 'skincare',
    unit: 'pump',
    slug: SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_FLASH_15,
    totalAmount: 30,
    amountUnit: 'ml',
    priceCents: 2680,
    description:
      'Ampoule flash 15% azélaïque + zinc + salicylique. Réduction imperfections rapide.',
    notes:
      'Concentration max mais dealbreakers : alcool isopropylique asséchant + salicylique incompatible rétinal + parfum. Pas adapté post-IPL.',
    inci: 'AQUA/WATER/EAU, AZELAIC ACID (15%), GLYCERIN, ISOPROPYL ALCOHOL, ISOPENTYLDIOL, NIACINAMIDE (2%), ZINC GLUCONATE (2%), DICAPRYLYL ETHER, SALICYLIC ACID, PARFUM (FRAGRANCE), PENTYLENE GLYCOL, SODIUM HYDROXIDE, MICROCRYSTALLINE CELLULOSE, 1,2-HEXANEDIOL, CAPRYLYL GLYCOL, SPHINGOMONAS FERMENT EXTRACT, CELLULOSE GUM, TOCOPHEROL',
    url: 'https://www.labo-svr.com',
  },
  {
    name: 'Sensifine AR Crème',
    brand: 'SVR',
    kind: 'skincare',
    unit: 'pump',
    slug: SVR_PRODUCT_SLUGS.SVR_SENSIFINE_AR,
    totalAmount: 40,
    amountUnit: 'ml',
    priceCents: 1350,
    description: 'Soin intensif hydratant avec effet thermorégulateur pour calmer les flushs.',
    notes: 'Contient des pigments verts pour neutraliser les rougeurs.',
    inci: 'AQUA/WATER/EAU, C15-19 ALKANE, ORBIGNYA OLEIFERA SEED OIL, GLYCERIN, BUTYROSPERMUM PARKII (SHEA) BUTTER, POLYGLYCERYL-3 DISTEARATE, CORN STARCH MODIFIED, SQUALANE, BUTYLENE GLYCOL, GLYCERYL STEARATE SE, HYDROLYZED CORN STARCH, PENTYLENE GLYCOL, SODIUM ACRYLATES COPOLYMER, PROPANEDIOL, OPHIOPOGON JAPONICUS ROOT EXTRACT, 1,2-HEXANEDIOL, CAPRYLYL GLYCOL, DAUCUS CAROTA SATIVA (CARROT) ROOT EXTRACT, LECITHIN, SODIUM STEAROYL GLUTAMATE, SPHINGOMONAS FERMENT EXTRACT, GLYCERYL STEARATE CITRATE, MALTODEXTRIN, CITRIC ACID, TETRASODIUM GLUTAMATE DIACETATE, GLYCOSPHINGOLIPIDS, GLYCOLIPIDS, TOCOPHEROL, RHAMNOSE, CI 10020, SODIUM SULFATE, GLUCOSE, GLUCURONIC ACID, HELIANTHUS ANNUUS (SUNFLOWER) SEED OIL, HYDROLYZED YEAST EXTRACT, HYDROLYZED GARDENIA FLORIDA EXTRACT',
  },
  {
    name: '[C20] Biotic Regenerating Radiance Cream',
    brand: 'SVR',
    kind: 'skincare',
    unit: 'pump',
    slug: SVR_PRODUCT_SLUGS.SVR_C20_BIOTIC,
    totalAmount: 50,
    amountUnit: 'ml',
    priceCents: 0,
    description:
      'Crème régénérante éclat avec 20% vitamine C optimisée, probiotiques et acide hyaluronique pour peaux ternes, fatiguées et sensibles.',
    notes:
      "Crème riche et occlusive (6.5/10) grâce aux dérivés d'olive, karité et ascorbyl tetraisopalmitate liposoluble. Texture nourrissante.",
    inci: 'AQUA/WATER/EAU, ASCORBYL TETRAISOPALMITATE, HYDROGENATED ETHYLHEXYL OLIVATE, MYRISTYL ALCOHOL, GLYCERYL STEARATE, LAUROYL LYSINE, PEG-100 STEARATE, BUTYROSPERMUM PARKII (SHEA) BUTTER, SODIUM CITRATE, SILICA, MYRISTYL GLUCOSIDE, MICROCRYSTALLINE CELLULOSE, HYDROXYETHYL ACRYLATE/SODIUM ACRYLOYLDIMETHYL TAURATE COPOLYMER, TOCOPHERYL ACETATE, PENTYLENE GLYCOL, MANNITOL, 1,2-HEXANEDIOL, ALLANTOIN, CAPRYLYL GLYCOL, PARFUM (FRAGRANCE), CITRIC ACID, HYDROGENATED OLIVE OIL UNSAPONIFIABLES, CELLULOSE GUM, POLYSORBATE 60, SORBITAN ISOSTEARATE, SODIUM ACETYLATED HYALURONATE, MALTODEXTRIN, HYDROXYPROPYL METHYLCELLULOSE, CI 77492 (IRON OXIDES), LACTOBACILLUS FERMENT, ALGIN, ASCORBIC ACID',
    url: 'https://fr.svr.com',
  },

  {
    name: 'Cicavit+ Crème HPPI',
    brand: 'SVR',
    slug: SVR_PRODUCT_SLUGS.SVR_CICAVIT_PLUS_CREME_HPPI,
    kind: 'skincare',
    unit: 'tube',
    totalAmount: 100,
    amountUnit: 'ml',
    priceCents: 1750,
    description:
      'Crème réparatrice accélératrice de cicatrisation pour peaux irritées, lésions, rougeurs, post-actes.',
    notes: 'Avec curcuma, niacinamide, HA hydrolysé. Convient visage/corps, famille entière.',
    inci: 'AQUA/WATER/EAU, ORBIGNYA OLEIFERA SEED OIL, HELIANTHUS ANNUUS (SUNFLOWER) SEED OIL, BUTYROSPERMUM PARKII (SHEA) BUTTER, ZEA MAYS (CORN) OIL, PROPANEDIOL, GLYCERYL STEARATE, GLYCERIN, BEHENYL ALCOHOL, NIACINAMIDE, BUTYLENE GLYCOL, CETEARYL ALCOHOL, CORN STARCH MODIFIED, CURCUMA LONGA (TURMERIC) ROOT EXTRACT, GLYCOLIPIDS, GLYCOSPHINGOLIPIDS, HYDROLYZED YEAST EXTRACT, LECITHIN, SODIUM STEAROYL GLUTAMATE, SODIUM STEAROYL LACTYLATE, ALPHA-GLUCAN OLIGOSACCHARIDE, GLUCOSE, HYDROLYZED HYALURONIC ACID, RHAMNOSE, TOCOPHEROL, 1,2-HEXANEDIOL, CAPRYLYL GLYCOL, CITRIC ACID, GLUCURONIC ACID, PENTYLENE GLYCOL, SODIUM HYDROXIDE, SODIUM POLYACRYLATE, XANTHAN GUM',
    url: 'https://www.svr.com',
  },
  {
    name: 'Sebiaclear Gel Flash 4H',
    brand: 'SVR',
    kind: 'skincare',
    unit: 'tube',
    slug: SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_GEL_FLASH_4H,
    totalAmount: 15,
    amountUnit: 'ml',
    priceCents: 1390,
    description:
      'Gel effet patch localisé invisible contre les imperfections dès 4h pour peaux mixtes à grasses.',
    notes:
      '5% Acide azélaïque. 5% Niacinamide. Technologie gel effet patch protecteur. Format nomade.',
    inci: 'AQUA/WATER, ISOPROPYL ALCOHOL, AZELAIC ACID, HYDROXYPROPYL STARCH, NIACINAMIDE, PROPANEDIOL, GLYCERIN, SODIUM CARBOXYMETHYL STARCH, PENTYLENE GLYCOL, SALICYLIC ACID, SODIUM HYDROXIDE, 1,2-HEXANEDIOL, CAPRYLYL GLYCOL, SPHINGOMONAS FERMENT EXTRACT, PARFUM/FRAGRANCE, SODIUM PHYTATE',
    url: 'https://fr.labo-svr.com',
  },
  {
    name: 'Sebiaclear Spray Corps',
    brand: 'SVR',
    kind: 'bodycare',
    unit: 'spray',
    slug: SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_SPRAY_CORPS,
    totalAmount: 150,
    amountUnit: 'ml',
    priceCents: 1700,
    description: 'Spray correcteur pour les imperfections du dos, des épaules et du décolleté.',
    notes:
      '8% Gluconolactone. 5% Niacinamide. 2% Acide lactobionique. 1% Zinc. Diminue les marques post-acné.',
    inci: 'AQUA/WATER, ISOPENTYLDIOL, ALCOHOL DENAT., GLUCONOLACTONE, NIACINAMIDE, LACTOBIONIC ACID, SODIUM HYDROXIDE, ZINC GLUCONATE, PARFUM/FRAGRANCE',
    url: 'https://fr.labo-svr.com',
  },
  {
    name: 'Sebiaclear Micro-Peel',
    brand: 'SVR',
    kind: 'skincare',
    unit: 'bottle',
    slug: SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_MICRO_PEEL,
    totalAmount: 150,
    amountUnit: 'ml',
    priceCents: 1750,
    description:
      "Lotion lissante et désincrustante pour peaux mixtes à grasses à base de duo d'acides.",
    notes:
      '4% Niacinamide. 1% Zinc. Acide lactobionique et salicylique. Texture eau rafraîchissante.',
    inci: 'AQUA/WATER, ALCOHOL DENAT., NIACINAMIDE, LACTOBIONIC ACID, ZINC GLUCONATE, SALICYLIC ACID, SODIUM HYDROXIDE, PARFUM/FRAGRANCE',
    url: 'https://fr.labo-svr.com',
  },
  {
    name: 'Sebiaclear Gel Moussant',
    brand: 'SVR',
    kind: 'skincare',
    unit: 'pump',
    slug: SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_GEL_MOUSSANT,
    totalAmount: 400,
    amountUnit: 'ml',
    priceCents: 1390,
    description:
      'Nettoyant visage et corps sans savon purifiant pour peaux sensibles mixtes à grasses.',
    notes: '4% Gluconolactone. Acide salicylique. Base lavante douce. Sans savon. Matifie la peau.',
    inci: 'AQUA/WATER, GLYCERIN, GLUCONOLACTONE, DECYL GLUCOSIDE, DISODIUM COCOYL GLUTAMATE, COCO-BETAINE, SALICYLIC ACID, ACRYLATES/C10-30 ALKYL ACRYLATE CROSSPOLYMER, SODIUM HYDROXIDE, PARFUM/FRAGRANCE',
    url: 'https://fr.labo-svr.com',
  },
  {
    name: 'Sebiaclear Sérum',
    brand: 'SVR',
    kind: 'skincare',
    unit: 'pump',
    slug: SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_SERUM,
    totalAmount: 30,
    amountUnit: 'ml',
    priceCents: 2390,
    description: 'Soin anti-imperfections et anti-rides pour peaux adultes à tendance acnéique.',
    notes:
      '14% Gluconolactone. 4% Niacinamide. Retinoid-like (Crithmum maritimum). Acide hyaluronique. Anti-pollution.',
    inci: 'AQUA/WATER, GLUCONOLACTONE, METHYL METHACRYLATE CROSSPOLYMER, DICAPRYLYL CARBONATE, NIACINAMIDE, PROPANEDIOL, SODIUM HYDROXIDE, DIMETHICONE, GLYCERIN, BIOSACCHARIDE GUM-4, CAMELLIA JAPONICA FLOWER EXTRACT, CETEARYL DIMETHICONE CROSSPOLYMER, CRITHMUM MARITIMUM EXTRACT, PENTAERYTHRITYL TETRA-DI-T-BUTYL HYDROXYHYDROCINNAMATE, SCLEROTIUM GUM, SALICYLIC ACID, SODIUM HYALURONATE, TOCOPHEROL, 1,2-HEXANEDIOL, CAPRYLIC/CAPRIC TRIGLYCERIDE, CETEARYL ALCOHOL, GLYCERYL STEARATE, HYDROGENATED VEGETABLE OIL, PEG-100 STEARATE, COCO-GLUCOSIDE, PARFUM/FRAGRANCE',
    url: 'https://fr.labo-svr.com',
  },
  {
    name: 'Sebiaclear Crème Lavante',
    brand: 'SVR',
    kind: 'skincare',
    unit: 'pump',
    slug: SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_CREME_LAVANTE,
    totalAmount: 400,
    amountUnit: 'ml',
    priceCents: 1690,
    description:
      'Nettoyant crème apaisant pour peaux acnéiques déshydratées ou sous traitements desséchants.',
    notes: 'Zinc. Niacinamide. Glycérine. Sans savon. Texture enveloppante. Visage et corps.',
    inci: 'AQUA/WATER, GLYCERIN, CETEARYL ALCOHOL, POLYSORBATE 20, NIACINAMIDE, BEHENYL ALCOHOL, CETYL ALCOHOL, XANTHAN GUM, ZINC GLUCONATE, DECYL GLUCOSIDE, DISODIUM COCOYL GLUTAMATE, GLYCERYL STEARATE SE, ACRYLATES/C10-30 ALKYL ACRYLATE CROSSPOLYMER, GLYCERYL STEARATE CITRATE, SODIUM HYDROXIDE, SODIUM PHYTATE, POTASSIUM SORBATE, SODIUM BENZOATE',
    url: 'https://fr.labo-svr.com',
  },
  {
    name: 'Sebiaclear Hydra',
    brand: 'SVR',
    kind: 'skincare',
    unit: 'tube',
    slug: SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_HYDRA,
    totalAmount: 40,
    amountUnit: 'ml',
    priceCents: 1390,
    description:
      'Crème réparatrice et apaisante pour peaux à tendance acnéique sous traitements desséchants.',
    notes: '5% Niacinamide. Céramides. Sucre prébiotique. Acide hyaluronique. Anti-marques.',
    inci: 'AQUA/WATER, PRUNUS AMYGDALUS DULCIS (SWEET ALMOND) OIL, ORBIGNYA OLEIFERA SEED OIL, NIACINAMIDE, DIMETHICONE, GLYCERYL STEARATE CITRATE, SILICA, GLYCERIN, GLYCERYL GLUCOSIDE, PENTYLENE GLYCOL, CETEARYL ALCOHOL, SODIUM POLYACRYLATE STARCH, PARFUM, OPHIOPOGON JAPONICUS ROOT EXTRACT, 1,2-HEXANEDIOL, CAPRYLYL GLYCOL, MALTODEXTRIN, HYDROLYZED HYALURONIC ACID, PENTAERYTHRITYL TETRA-DI-T-BUTYL HYDROXYHYDROCINNAMATE, GLYCOSPHINGOLIPIDS, GLYCOLIPIDS',
    url: 'https://fr.labo-svr.com',
  },
  {
    name: 'Sebiaclear Active Gel',
    brand: 'SVR',
    kind: 'skincare',
    unit: 'tube',
    slug: SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_ACTIVE_GEL,
    totalAmount: 40,
    amountUnit: 'ml',
    priceCents: 1450,
    description:
      'Soin correcteur intensif contre les imperfections sévères (boutons, points noirs, marques).',
    notes: '14% Gluconolactone. 4% Niacinamide. Acide salicylique. Texture gel-crème. Non gras.',
    inci: 'AQUA/WATER, GLUCONOLACTONE, PROPANEDIOL, SILICA, DICAPRYLYL ETHER, NIACINAMIDE, SODIUM HYDROXIDE, DICAPRYLYL CARBONATE, LAUROYL LYSINE, AMMONIUM ACRYLOYLDIMETHYLTAURATE/VP COPOLYMER, HYDROXYETHYL ACRYLATE/SODIUM ACRYLOYLDIMETHYL TAURATE COPOLYMER, CETEARYL ALCOHOL, SALICYLIC ACID, PARFUM, CETEARETH-33, POLYSORBATE 60, SORBITAN ISOSTEARATE, TOCOPHEROL',
    url: 'https://fr.labo-svr.com',
  },
  {
    name: 'Sebiaclear Mat+Pores',
    brand: 'SVR',
    kind: 'skincare',
    unit: 'tube',
    slug: SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_MAT_PORES,
    totalAmount: 40,
    amountUnit: 'ml',
    priceCents: 1350,
    description:
      'Soin matifiant sébo-régulateur et correcteur de pores pour peaux mixtes à grasses.',
    notes: '4% Gluconolactone. 4% Niacinamide. Acide salicylique. 2% Mat SR. Sucres hydrophiles.',
    inci: 'AQUA/WATER, SILICA, PROPANEDIOL, GLUCONOLACTONE, NIACINAMIDE, UNDECANE, ORBIGNYA OLEIFERA SEED OIL, GLYCERYL STEARATE, TRIDECANE, AMMONIUM ACRYLOYLDIMETHYLTAURATE/VP COPOLYMER, PENTYLENE GLYCOL, SODIUM HYDROXIDE, CETEARYL ALCOHOL, HYDROXYETHYL ACRYLATE/SODIUM ACRYLOYLDIMETHYL TAURATE COPOLYMER, SALICYLIC ACID, BUTYLENE GLYCOL, SACCHARIDE ISOMERATE, SODIUM STEAROYL LACTYLATE, 1,2-HEXANEDIOL, CAPRYLYL GLYCOL, PARFUM, POLYSORBATE 60, SORBITAN ISOSTEARATE, XANTHAN GUM, CITRIC ACID, SARCOSINE, SODIUM CITRATE, TOCOPHEROL',
    url: 'https://fr.labo-svr.com',
  },
  {
    name: 'Sebiaclear Crème SPF50+',
    brand: 'SVR',
    kind: 'sunscreen',
    unit: 'tube',
    slug: SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_CREME_SPF50,
    totalAmount: 40,
    amountUnit: 'ml',
    priceCents: 1550,
    description:
      'Haute protection solaire 2-en-1 matifiante et anti-imperfections pour peaux acnéiques.',
    notes: '4% Niacinamide. Acide salicylique. Filtres brevetés SVR. Action anti-marques UV.',
    inci: 'AQUA/WATER, SILICA, DIETHYLAMINO HYDROXYBENZOYL HEXYL BENZOATE, DIISOPROPYL ADIPATE, ETHYLHEXYL TRIAZONE, BEHENETH-25, ISONONYL ISONONANOATE, NIACINAMIDE, BIS-ETHYLHEXYLOXYPHENOL METHOXYPHENYL TRIAZINE, GLYCERIN, C12-15 ALKYL BENZOATE, C15-19 ALKANE, DIETHYLHEXYL BUTAMIDO TRIAZONE, GLYCERYL STEARATE CITRATE, ACRYLATES/C12-22 ALKYL METHACRYLATE COPOLYMER, PENTYLENE GLYCOL, BUTYLENE GLYCOL, SALICYLIC ACID, 1,2-HEXANEDIOL, CAPRYLYL GLYCOL, PARFUM, ARGININE, COCO-GLUCOSIDE, XANTHAN GUM, TOCOPHEROL, SODIUM HYDROXIDE, DISODIUM LAURYL SULFOSUCCINATE, GLYCINE SOJA (SOYBEAN) OIL, LECITHIN, SARCOSINE, LEPIDIUM SATIVUM SPROUT EXTRACT',
    url: 'https://fr.labo-svr.com',
  },
  {
    name: 'Sebiaclear Eau Micellaire',
    brand: 'SVR',
    kind: 'skincare',
    unit: 'bottle',
    slug: SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_EAU_MICELLAIRE,
    totalAmount: 400,
    amountUnit: 'ml',
    priceCents: 1350,
    description:
      'Eau nettoyante purifiante et démaquillante pour peaux grasses à tendance acnéique.',
    notes: 'Gluconolactone. Micelles. Élimine le maquillage waterproof. Sans rinçage.',
    inci: 'AQUA/WATER, POLOXAMER 184, PEG-7 GLYCERYL COCOATE, PENTYLENE GLYCOL, PROPANEDIOL, GLUCONOLACTONE, 1,2-HEXANEDIOL, CITRIC ACID, SODIUM HYDROXIDE, CETRIMONIUM BROMIDE, PARFUM/FRAGRANCE',
    url: 'https://fr.labo-svr.com',
  },
  {
    name: 'Sebiaclear Active Teinté',
    brand: 'SVR',
    kind: 'skincare',
    unit: 'tube',
    slug: SVR_PRODUCT_SLUGS.SVR_SEBIACLEAR_ACTIVE_TEINTE,
    totalAmount: 40,
    amountUnit: 'ml',
    priceCents: 1450,
    description:
      'Soin teinté unificateur qui corrige et camoufle les imperfections des peaux mixtes à grasses.',
    notes: '4% Niacinamide. Acide salicylique. Pigments minéraux micronisés. Teinte universelle.',
    inci: 'AQUA/WATER, DIMETHICONE, CI 77891, CAPRYLYL METHICONE, NIACINAMIDE, PEG-10 DIMETHICONE, DIPHENYL DIMETHICONE, PROPYLENE GLYCOL, PEG/PPG-18/18 DIMETHICONE, NEOPENTYL GLYCOL DIHEPTANOATE, CI 77492, BORON NITRIDE, LAUROYL LYSINE, CETEARYL DIMETHICONE CROSSPOLYMER, DISTEARDIMONIUM HECTORITE, PROPYLENE CARBONATE, SACCHARIDE ISOMERATE, SALICYLIC ACID, CITRIC ACID, SODIUM CITRATE, SODIUM HYDROXIDE, TRIETHOXYCAPRYLYLSILANE, PARFUM, CI 77491, CI 77499',
    url: 'https://fr.labo-svr.com',
  },
  {
    name: '[C] Eye Biotic',
    brand: 'SVR',
    kind: 'skincare',
    unit: 'jar',
    slug: SVR_PRODUCT_SLUGS.SVR_C_EYE_BIOTIC,
    totalAmount: 15,
    amountUnit: 'ml',
    priceCents: 3090,
    description:
      'Contour des yeux illuminateur pour corriger les cernes, les poches et lisser les rides.',
    notes:
      '5% Vitamine C optimisée. Peptide lissant. Extrait de Gentiane. Micro-pigments réflecteurs.',
    inci: 'AQUA/WATER/EAU, ASCORBYL TETRAISOPALMITATE, MICA, SODIUM POLYACRYLATE, CI 77891 (TITANIUM DIOXIDE), ACETYL HEXAPEPTIDE-8, CARBOMER, GENTIANA LUTEA ROOT EXTRACT, LACTOBACILLUS FERMENT, MALTODEXTRIN, SODIUM ACETYLATED HYALURONATE, SODIUM STEAROYL GLUTAMATE, HELIANTHUS ANNUUS (SUNFLOWER) SEED OIL, TIN OXIDE, TOCOPHEROL, 1,2-HEXANEDIOL, CAPRYLYL GLYCOL, CITRIC ACID, PENTYLENE GLYCOL, PROPANEDIOL, SODIUM HYDROXIDE, PARFUM/FRAGRANCE, CI 77491 (IRON OXIDES)',
    url: 'https://fr.labo-svr.com',
  },
  {
    name: '[Collagen] Biotic',
    brand: 'SVR',
    kind: 'skincare',
    unit: 'jar',
    slug: SVR_PRODUCT_SLUGS.SVR_COLLAGEN_BIOTIC,
    totalAmount: 50,
    amountUnit: 'ml',
    priceCents: 4000,
    description: 'Crème rebondissante régénérante pour redonner élasticité et fermeté à la peau.',
    notes:
      '2% Collagène végétal. Vitamine C optimisée. Acide Hyaluronique. Texture à mémoire de forme.',
    inci: 'AQUA/WATER/EAU, PRUNUS AMYGDALUS DULCIS (SWEET ALMOND) OIL, SQUALANE, GLYCERIN, BUTYROSPERMUM PARKII (SHEA) BUTTER, CAESALPINIA SPINOSA GUM, COLLAGEN AMINO ACIDS, LACTOBACILLUS FERMENT, MALTODEXTRIN, SODIUM ACETYLATED HYALURONATE, ASCORBYL TETRAISOPALMITATE, 1,2-HEXANEDIOL, ACRYLATES/C10-30 ALKYL ACRYLATE CROSSPOLYMER, CAPRYLYL GLYCOL, CITRIC ACID, PENTYLENE GLYCOL, SODIUM HYDROXIDE, PARFUM (FRAGRANCE)',
    url: 'https://fr.labo-svr.com',
  },
  {
    name: '[Filler] Biotic',
    brand: 'SVR',
    kind: 'skincare',
    unit: 'tube',
    slug: SVR_PRODUCT_SLUGS.SVR_FILLER_BIOTIC,
    totalAmount: 15,
    amountUnit: 'ml',
    priceCents: 3990,
    description: 'Soin liftant pour combler les rides du contour des yeux et des lèvres.',
    notes:
      'Peptide liftant. Vitamine C optimisée. Acide Hyaluronique. Texture fraîche non collante.',
    inci: 'AQUA/WATER/EAU, HYDROXYPROPYL STARCH, PROPYLENE GLYCOL, C15-19 ALKANE, GLYCERYL STEARATE SE, CAPRYLIC/CAPRIC TRIGLYCERIDE, ISOSTEARYL ALCOHOL, C10-18 TRIGLYCERIDES, ACETYL HEXAPEPTIDE-1, BUTYLENE GLYCOL COCOATE, ETHYLCELLULOSE, HYDROXYACETOPHENONE, LACTOBACILLUS FERMENT, MALTODEXTRIN, PENTAERYTHRITYL TETRA-DI-T-BUTYL HYDROXYHYDROCINNAMATE, SODIUM ACETYLATED HYALURONATE, SODIUM STEAROYL GLUTAMATE, ASCORBYL TETRAISOPALMITATE, GLYCERIN, 1,2-HEXANEDIOL, CAPRYLYL GLYCOL, CITRIC ACID, SODIUM POLYACRYLATE, PARFUM/FRAGRANCE',
    url: 'https://fr.labo-svr.com',
  },
  {
    name: '[Pepti] Biotic',
    brand: 'SVR',
    kind: 'skincare',
    unit: 'jar',
    slug: SVR_PRODUCT_SLUGS.SVR_PEPTI_BIOTIC,
    totalAmount: 50,
    amountUnit: 'ml',
    priceCents: 4590,
    description: 'Gel-matifiant régénérant pour lisser les rides et contrôler la brillance.',
    notes:
      'Peptides lissants. Vitamine C optimisée. Acide Hyaluronique. Idéal peaux mixtes à grasses.',
    inci: 'AQUA/WATER/EAU, GLYCERIN, SQUALANE, ASCORBYL TETRAISOPALMITATE, LAUROYL LYSINE, PRUNUS AMYGDALUS DULCIS (SWEET ALMOND) OIL, SILICA, SODIUM POLYACRYLATE, PENTYLENE GLYCOL, MALTODEXTRIN, 1,2-HEXANEDIOL, CAPRYLYL GLYCOL, CARBOMER, PARFUM (FRAGRANCE), CITRIC ACID, LACTOBACILLUS FERMENT, PENTAERYTHRITYL TETRA-DI-T-BUTYL HYDROXYHYDROCINNAMATE, SODIUM ACETYLATED HYALURONATE, SODIUM STEAROYL GLUTAMATE, SODIUM HYDROXIDE, DIPEPTIDE DIAMINOBUTYROYL BENZYLAMIDE DIACETATE',
    url: 'https://fr.labo-svr.com',
  },
  {
    name: '[C20] Biotic',
    brand: 'SVR',
    kind: 'skincare',
    unit: 'jar',
    slug: SVR_PRODUCT_SLUGS.SVR_C20_BIOTIC,
    totalAmount: 50,
    amountUnit: 'ml',
    priceCents: 4590,
    description: 'Crème éclat régénérante pour revitaliser et uniformiser le teint terne.',
    notes: "20% Vitamine C optimisée. Microbilles vitaminées. 24h d'éclat. Action anti-fatigue.",
    inci: 'WATER/AQUA/EAU, ASCORBYL TETRAISOPALMITATE, HYDROGENATED ETHYLHEXYL OLIVATE, MYRISTYL ALCOHOL, GLYCERYL STEARATE, LAUROYL LYSINE, PEG-100 STEARATE, BUTYROSPERMUM PARKII (SHEA) BUTTER, SODIUM CITRATE, SILICA, MYRISTYL GLUCOSIDE, MICROCRYSTALLINE CELLULOSE, HYDROXYETHYL ACRYLATE/SODIUM ACRYLOYLDIMETHYL TAURATE COPOLYMER, TOCOPHEROL ACETATE, PENTYLENE GLYCOL, MANNITOL, 1,2-HEXANEDIOL, ALLANTOIN, CAPRYLYL GLYCOL, PARFUM (FRAGRANCE), CITRIC ACID, HYDROGENATED OLIVE OIL UNSAPONIFIABLES, CELLULOSE GUM, POLYSORBATE 60, SORBITAN ISOSTEARATE, SODIUM ACETYLATED HYALURONATE, MALTODEXTRIN, HYDROXYPROPYL METHYLCELLULOSE, CI 77492 (IRON OXIDES), LACTOBACILLUS FERMENT, ALGIN',
    url: 'https://fr.labo-svr.com',
  },
  {
    name: '[Hyalu] Biotic',
    brand: 'SVR',
    kind: 'skincare',
    unit: 'jar',
    slug: SVR_PRODUCT_SLUGS.SVR_HYALU_BIOTIC,
    totalAmount: 50,
    amountUnit: 'ml',
    priceCents: 4590,
    description: 'Gelée rafraîchissante repulpante pour hydrater intensément et lisser les rides.',
    notes: "Duo d'acides hyaluroniques. Vitamine C optimisée. 48h d'hydratation.",
    inci: 'AQUA/WATER/EAU, BUTYLENE GLYCOL, GLYCERIN, PROPYLENE GLYCOL, CAPRYLIC/CAPRIC TRIGLYCERIDE, ASCORBYL TETRAISOPALMITATE, 1,2-HEXANEDIOL, C10-18 TRIGLYCERIDES, CARBOMER, MALTODEXTRIN, SODIUM HYALURONATE, SODIUM ACRYLATES COPOLYMER, ACRYLATES/C10-30 ALKYL ACRYLATE CROSSPOLYMER, CAPRYLYL GLYCOL, PARFUM (FRAGRANCE), SODIUM HYDROXIDE, LECITHIN, LACTOBACILLUS FERMENT, PENTAERYTHRITYL TETRA-DI-T-BUTYL HYDROXYHYDROCINNAMATE, SODIUM ACETYLATED HYALURONATE',
    url: 'https://fr.labo-svr.com',
  },
  {
    name: '[C20] Fluide',
    brand: 'SVR',
    kind: 'skincare',
    unit: 'bottle',
    slug: SVR_PRODUCT_SLUGS.SVR_C20_FLUIDE,
    totalAmount: 30,
    amountUnit: 'ml',
    priceCents: 3990,
    description:
      "Fluide énergisant fini peau de pêche pour réveiller l'éclat et lisser le grain de peau.",
    notes:
      "20% Vitamine C optimisée. Booster d'aquaporines. Acide Hyaluronique bas poids. Effet glow immédiat.",
    inci: 'AQUA/WATER/EAU, ASCORBYL TETRAISOPALMITATE, PROPANEDIOL, TRIDECANE, SILICA, ARACHIDYL ALCOHOL, SODIUM POLYACRYLOYLDIMETHYL TAURATE, GLYCERYL GLUCOSIDE, LACTOBACILLUS FERMENT, LAURYL GLUCOSIDE, MALTODEXTRIN, POLYGLYCERYL-6 LAURATE, SODIUM ACETYLATED HYALURONATE, TETRASODIUM GLUTAMATE DIACETATE, GLYCERIN, HELIANTHUS ANNUUS (SUNFLOWER) SEED OIL, TOCOPHEROL, 1,2-HEXANEDIOL, ARACHIDYL GLUCOSIDE, BEHENYL ALCOHOL, CAPRYLYL GLYCOL, CITRIC ACID, MYRISTYL GLUCOSIDE, PENTYLENE GLYCOL, PARFUM/FRAGRANCE',
    url: 'https://fr.labo-svr.com',
  },

  {
    name: 'Cicavit+ Gel Moussant',
    brand: 'SVR',
    kind: 'skincare',
    unit: 'bottle',
    slug: SVR_PRODUCT_SLUGS.SVR_CICAVIT_GEL_MOUSSANT,
    totalAmount: 200,
    amountUnit: 'ml',
    priceCents: 1350,
    description:
      'Nettoyant ultra-doux apaisant et assainissant pour zones irritées et fragilisées.',
    notes: 'Tensioactifs ultra-doux. Sucre prébiotique. Rhamnose. Respecte le microbiote cutané.',
    inci: 'AQUA/WATER/EAU, SODIUM C14-16 OLEFIN SULFONATE, COCO-GLUCOSIDE, COCO-BETAINE, GLYCERIN, PROPANEDIOL, CITRIC ACID, SODIUM BENZOATE, ALPHA-GLUCAN OLIGOSACCHARIDE, POTASSIUM SORBATE, SODIUM PHYTATE, SACCHARIDE ISOMERATE, RHAMNOSE, GLUCOSE, GLUCURONIC ACID, SODIUM CITRATE, DISODIUM ACETYL GLUCOSAMINE PHOSPHATE, CAFFEYL GLUCOSIDE',
    url: 'https://fr.labo-svr.com',
  },
  {
    name: 'Cicavit+ Crème Mains',
    brand: 'SVR',
    kind: 'bodycare',
    unit: 'tube',
    slug: SVR_PRODUCT_SLUGS.SVR_CICAVIT_CREME_MAINS,
    totalAmount: 75,
    amountUnit: 'g',
    priceCents: 1250,
    description: 'Crème barrière réparatrice invisible pour mains abîmées et sur-sollicitées.',
    notes: 'Protection 8h. Beurre de Karité & Huile de Coco. Sucre prébiotique. Fini non gras.',
    inci: 'AQUA/WATER/EAU, GLYCERIN, COCOS NUCIFERA (COCONUT) OIL, DIGLYCERIN, VEGETABLE OIL, C12-16 ALCOHOLS, GLYCOL PALMITATE, CETYL PALMITATE, GLYCERYL STEARATE CITRATE, HELIANTHUS ANNUUS (SUNFLOWER) SEED WAX, SILICA, PENTYLENE GLYCOL, 1,2-HEXANEDIOL, SODIUM POLYACRYLATE, HYDROGENATED LECITHIN, PALMITIC ACID, ALPHA-GLUCAN OLIGOSACCHARIDE, PROPANEDIOL, CAPRYLYL GLYCOL, PENTAERYTHRITYL TETRA-DI-T-BUTYL HYDROXYHYDROCINNAMATE, DISODIUM ACETYL GLUCOSAMINE PHOSPHATE, RHAMNOSE, CAFFEYL GLUCOSIDE, GLUCOSE, GLUCURONIC ACID',
    url: 'https://fr.labo-svr.com',
  },
  {
    name: 'Cicavit+ Crème SPF50+',
    brand: 'SVR',
    kind: 'sunscreen',
    unit: 'tube',
    slug: SVR_PRODUCT_SLUGS.SVR_CICAVIT_CREME_SPF50,
    totalAmount: 40,
    amountUnit: 'ml',
    priceCents: 1550,
    description: 'Protection solaire cicatrisante anti-marques pour peaux abîmées exposées aux UV.',
    notes:
      "Technologie Integral Secure. Niacinamide. Action anti-marques rouges et brunes. Résiste à l'eau.",
    inci: 'AQUA/WATER/EAU, DICAPRYLYL CARBONATE, DIETHYLAMINO HYDROXYBENZOYL HEXYL BENZOATE, DIETHYLHEXYL BUTAMIDO TRIAZONE, DIISOPROPYL ADIPATE, SILICA, CETEARYL ALCOHOL, BIS-ETHYLHEXYLOXYPHENOL METHOXYPHENYL TRIAZINE, CETEARETH-20, ETHYLHEXYL TRIAZONE, DIMETHICONE, NIACINAMIDE, POLYMETHYL METHACRYLATE, PENTYLENE GLYCOL, POLYESTER-7, AMINOMETHYL PROPANOL, BETA-CAROTENE, BETA-SITOSTEROL, CETEARYL DIMETHICONE CROSSPOLYMER, DAUCUS CAROTA SATIVA (CARROT) ROOT EXTRACT, GLYCINE SOJA (SOYBEAN) OIL, HYDROGENATED PHOSPHATIDYLCHOLINE, LECITHIN, LEPIDIUM SATIVUM SPROUT EXTRACT, SQUALENE, ALPHA-GLUCAN OLIGOSACCHARIDE, CAFFEYL GLUCOSIDE, DISODIUM ACETYL GLUCOSAMINE PHOSPHATE, GLUCOSE, GLYCERIN, PHYTIC ACID, RHAMNOSE, TOCOPHEROL, TOCOPHERYL ACETATE, 1,2-HEXANEDIOL, CAPRYLIC/CAPRIC TRIGLYCERIDE, CAPRYLYL GLYCOL, CITRIC ACID, GLUCURONIC ACID, HYDROXYETHYL ACRYLATE/SODIUM ACRYLOYLDIMETHYL TAURATE COPOLYMER, LYSOLECITHIN, NEOPENTYL GLYCOL DIHEPTANOATE, POLYSORBATE 60, PROPANEDIOL, SODIUM LAURETH SULFATE, SORBITAN ISOSTEARATE, XANTHAN GUM, POTASSIUM SORBATE, SODIUM BENZOATE',
    url: 'https://fr.labo-svr.com',
  },
  {
    name: 'Cicavit+ Baume Lèvres',
    brand: 'SVR',
    kind: 'skincare',
    unit: 'tube',
    slug: SVR_PRODUCT_SLUGS.SVR_CICAVIT_BAUME_LEVRES,
    totalAmount: 10,
    amountUnit: 'g',
    priceCents: 730,
    description: 'Baume protecteur et réparateur pour lèvres gercées, abîmées et irritées.',
    notes: '95% actifs hydratants. Huile de Ricin & Amande douce. Film isolant protecteur.',
    inci: 'RICINUS COMMUNIS (CASTOR) SEED OIL, PRUNUS AMYGDALUS DULCIS (SWEET ALMOND) OIL, COCOS NUCIFERA (COCONUT) OIL, BUTYROSPERMUM PARKII (SHEA) BUTTER, HYDROGENATED CASTOR OIL, OLEIC/LINOLEIC/LINOLENIC POLYGLYCERIDES, GLYCERIN, CERA ALBA/BEESWAX/CIRE D’ABEILLE, HELIANTHUS ANNUUS (SUNFLOWER) SEED OIL, AQUA/WATER/EAU, HYDROGENATED VEGETABLE OIL, ALPHA-GLUCAN OLIGOSACCHARIDE, PROPANEDIOL, TOCOPHERYL ACETATE, DISODIUM ACETYL GLUCOSAMINE PHOSPHATE, CAFFEYL GLUCOSIDE, RHAMNOSE, GLUCOSE, GLUCURONIC ACID, CITRIC ACID',
    url: 'https://fr.labo-svr.com',
  },
  {
    name: 'Cicavit+ SOS Grattage',
    brand: 'SVR',
    kind: 'skincare',
    unit: 'spray',
    slug: SVR_PRODUCT_SLUGS.SVR_CICAVIT_SOS_GRATTAGE,
    totalAmount: 40,
    amountUnit: 'ml',
    priceCents: 1490,
    description: 'Spray apaisant immédiat à effet froid pour calmer les démangeaisons.',
    notes: 'Niacinamide. Centella Asiatica. Panthénol (B5). Action anti-marques et anti-grattage.',
    inci: 'AQUA/WATER/EAU, DIMETHYL ETHER, NIACINAMIDE, GLYCERIN, HYDROXYETHYL ACRYLATE/SODIUM ACRYLOYLDIMETHYL TAURATE COPOLYMER, OLEYL ALCOHOL, ISOHEXADECANE, ALPHA-GLUCAN OLIGOSACCHARIDE, COCOS NUCIFERA (COCONUT) OIL, GOSSYPIUM HERBACEUM (COTTON) SEED OIL, PROPANEDIOL, LEVULINIC ACID, SODIUM BENZOATE, PANTHENOL, BUTYLENE GLYCOL, ETHYLHEXYLGLYCERIN, SODIUM LEVULINATE, ZANTHOXYLUM BUNGEANUM FRUIT EXTRACT, POLYSORBATE 60, XANTHAN GUM, PENTYLENE GLYCOL, PUERARIA LOBATA ROOT EXTRACT, SORBITAN ISOSTEARATE, SODIUM HYDROXIDE, CAPRYLYL GLYCOL, CENTELLA ASIATICA EXTRACT, RHAMNOSE, PANTOLACTONE, GLUCOSE, PHYTIC ACID, GLUCURONIC ACID, TOCOPHEROL, HYDROGENATED PALM GLYCERIDES CITRATE',
    url: 'https://fr.labo-svr.com',
  },
  {
    name: 'Cicavit DM+ Cicatrices',
    brand: 'SVR',
    kind: 'skincare',
    unit: 'tube',
    slug: SVR_PRODUCT_SLUGS.SVR_CICAVIT_DM_PLUS,
    totalAmount: 15,
    amountUnit: 'g',
    priceCents: 2790,
    description:
      'Gel de silicone dispositif médical pour réduire les cicatrices post-chirurgicales.',
    notes: '53% Complexe silicone. Réduit les rougeurs et tiraillements. Texture non collante.',
    inci: 'DIMETHICONE, GLYCERIN, AQUA/WATER/EAU, DIMETHICONE CROSSPOLYMER, C30-45 ALKYLDIMETHYLSILYL POLYPROPYLSILSESQUIOXANE, POLYESTER-7, TRIMETHYLSILOXYSILICATE, NEOPENTYL GLYCOL DIHEPTANOATE, PENTYLENE GLYCOL, POLYSORBATE 80, SODIUM ACRYLATE/ SODIUM ACRYLOYLDIMETHYL TAURATE COPOLYMER, SORBITAN OLEATE, ALPHA-GLUCAN OLIGOSACCHARIDE, CAFFEYL GLUCOSIDE, DISODIUM ACETYL GLUCOSAMINE PHOSPHATE, GLUCOSE, RHAMNOSE, 1,2-HEXANEDIOL, CAPRYLYL GLYCOL, CITRIC ACID, GLUCURONIC ACID, ISOHEXADECANE, PROPANEDIOL',
    url: 'https://fr.labo-svr.com',
  },
  {
    name: 'Clairial Ampoule',
    brand: 'SVR',
    kind: 'skincare',
    unit: 'dropper',
    slug: SVR_PRODUCT_SLUGS.SVR_CLAIRIAL_AMPOULE,
    totalAmount: 30,
    amountUnit: 'ml',
    priceCents: 3950,
    description:
      'Concentré triple action qui corrige tous les types de taches, prévient leur apparition et protège de la pollution.',
    notes: '14% Complexe dépigmentant. 2% Vitamine C optimisée. Anti-pollution et anti-récidive.',
    inci: 'AQUA/WATER/EAU, GLYCERIN, OCTYLDODECANOL, CAPRYLIC/CAPRIC TRIGLYCERIDE, ISOPENTYLDIOL, ASCORBYL TETRAISOPALMITATE, BUTYLENE GLYCOL, PENTYLENE GLYCOL, 1,2-HEXANEDIOL, ASCOPHYLLUM NODOSUM EXTRACT, BENTONITE, CYSTOSEIRA TAMARISCIFOLIA EXTRACT, ETHYLHEXYL FERULATE, GLYCOLIPIDS, HYDROLYZED YEAST EXTRACT, LAMINARIA JAPONICA EXTRACT, PULLULAN, SCLEROTIUM GUM, DIACETYL BOLDINE, SODIUM HYALURONATE, CAPRYLYL GLYCOL, CELLULOSE GUM, CITRIC ACID, LYSOLECITHIN, MICROCRYSTALLINE CELLULOSE, SILICA, XANTHAN GUM, POTASSIUM SORBATE, SODIUM BENZOATE, PARFUM/FRAGRANCE',
    url: 'https://fr.labo-svr.com',
  },
  {
    name: 'Clairial Sérum',
    brand: 'SVR',
    kind: 'skincare',
    unit: 'pump',
    slug: SVR_PRODUCT_SLUGS.SVR_CLAIRIAL_SERUM,
    totalAmount: 30,
    amountUnit: 'ml',
    priceCents: 3800,
    description:
      'Sérum concentré anti-taches pour une réduction visible dès 2 semaines et un éclat immédiat.',
    notes:
      '8% Complexe dépigmentant. 2% Vitamine C optimisée. Bio-neige soft focus pour flouter les taches.',
    inci: 'AQUA/WATER/EAU, CAPRYLIC/CAPRIC TRIGLYCERIDE, DIMETHICONE, ASCORBYL TETRAISOPALMITATE, SILICA, DICAPRYLYL CARBONATE, BUTYLENE GLYCOL, BORON NITRIDE, CETEARYL ALCOHOL, PROPANEDIOL, BENTONITE, ETHYLHEXYL FERULATE, PLANKTON EXTRACT, DIACETYL BOLDINE, GLYCERIN, SODIUM HYALURONATE, TOCOPHEROL, TOCOPHERYL ACETATE, UNDECYLENOYL PHENYLALANINE, 1,2-HEXANEDIOL, ACRYLATES/C10-30 ALKYL ACRYLATE CROSSPOLYMER, CAPRYLYL GLYCOL, CITRIC ACID, PENTYLENE GLYCOL, XANTHAN GUM, COCO-GLUCOSIDE, PARFUM (FRAGRANCE)',
    url: 'https://fr.labo-svr.com',
  },
  {
    name: 'Clairial Crème SPF50+',
    brand: 'SVR',
    kind: 'sunscreen',
    unit: 'tube',
    slug: SVR_PRODUCT_SLUGS.SVR_CLAIRIAL_CREME_SPF50,
    totalAmount: 40,
    amountUnit: 'ml',
    priceCents: 3100,
    description:
      'Soin 2-en-1 associant un complexe dépigmentant et une très haute protection solaire large spectre.',
    notes: 'Complexe dépigmentant + Niacinamide. Protection lumière bleue et IR. Fini mat.',
    inci: 'AQUA/WATER/EAU, DIETHYLAMINO HYDROXYBENZOYL HEXYL BENZOATE, DIISOPROPYL ADIPATE, UNDECANE, ISOAMYL LAURATE, BIS-ETHYLHEXYLOXYPHENOL METHOXYPHENYL TRIAZINE, ETHYLHEXYL TRIAZONE, SILICA, BEHENETH-25, NIACINAMIDE, TRIDECANE, ACRYLATES/C12-22 ALKYL METHACRYLATE COPOLYMER, DIETHYLHEXYL BUTAMIDO TRIAZONE, GLYCERYL STEARATE CITRATE, BUTYLENE GLYCOL, HYDROGENATED VEGETABLE OIL, SOLANUM LYCOPERSICUM (TOMATO) FRUIT EXTRACT, ALKANNA TINCTORIA ROOT EXTRACT, ARGININE, DISODIUM LAURYL SULFOSUCCINATE, GLYCOLIPIDS, HYDROLYZED YEAST EXTRACT, LECITHIN, LEPIDIUM SATIVUM SPROUT EXTRACT, GLYCERIN, HELIANTHUS ANNUUS (SUNFLOWER) SEED OIL, TOCOPHEROL, 1,2-HEXANEDIOL, CAPRYLYL GLYCOL, CITRIC ACID, HYDROXYETHYL ACRYLATE/SODIUM ACRYLOYLDIMETHYL TAURATE COPOLYMER, PENTYLENE GLYCOL, POLYSORBATE 60, SORBITAN ISOSTEARATE, XANTHAN GUM, COCO-GLUCOSIDE, PARFUM/FRAGRANCE',
    url: 'https://fr.labo-svr.com',
  },
  {
    name: 'Clairial Day',
    brand: 'SVR',
    kind: 'skincare',
    unit: 'pump',
    slug: SVR_PRODUCT_SLUGS.SVR_CLAIRIAL_DAY,
    totalAmount: 30,
    amountUnit: 'ml',
    priceCents: 3250,
    description:
      'Crème de jour teintée triple protection : SPF30, anti-pollution et anti-lumière bleue.',
    notes:
      'Duo White. Dérivé de férulate. Effet bonne mine unifiant. Convient à toutes les carnations.',
    inci: 'AQUA/WATER/EAU, DIETHYLAMINO HYDROXYBENZOYL HEXYL BENZOATE, C12-15 ALKYL BENZOATE, DIISOPROPYL ADIPATE, CI 77891 (TITANIUM DIOXIDE), BIS-ETHYLHEXYLOXYPHENOL METHOXYPHENYL TRIAZINE, CAPRYLIC/CAPRIC TRIGLYCERIDE, ISOPROPYL LAUROYL SARCOSINATE, SILICA, BORON NITRIDE, CETEARETH-20, GLYCERYL STEARATE, PEG-100 STEARATE, DICAPRYLYL CARBONATE, ACRYLATES/C12-22 ALKYL METHACRYLATE COPOLYMER, PROPANEDIOL, HYDROGENATED VEGETABLE OIL, CI 77492 (IRON OXIDES), PARFUM/FRAGRANCE, PENTYLENE GLYCOL, TOCOPHERYL ACETATE, CELLULOSE ACETATE, ALUMINA, 1,2-HEXANEDIOL, CAPRYLYL GLYCOL, ARGININE, CITRIC ACID, ACRYLATES/AMMONIUM METHACRYLATE COPOLYMER, XANTHAN GUM, CI 77491 (IRON OXIDES), COCO-GLUCOSIDE, SODIUM CITRATE, STEARALKONIUM HECTORITE, PROPYLENE GLYCOL STEARATE, SODIUM HYALURONATE, UNDECYLENOYL PHENYLALANINE, BENTONITE, BUTYLENE GLYCOL, MAGNESIUM STEARATE, ALUMINUM HYDROXIDE, PROPYLENE CARBONATE, DISODIUM LAURYL SULFOSUCCINATE, CI 77499 (IRON OXIDES), ALGIN, SCLEROTIUM GUM, LECITHIN, PULLULAN, TIN OXIDE, YEAST EXTRACT, ETHYLHEXYL FERULATE, TOCOPHEROL, DIACETYL BOLDINE, HYDROLYZED YEAST EXTRACT, GLYCOLIPIDS',
    url: 'https://fr.labo-svr.com',
  },
  {
    name: 'Clairial Night Peel',
    brand: 'SVR',
    kind: 'skincare',
    unit: 'tube',
    slug: SVR_PRODUCT_SLUGS.SVR_CLAIRIAL_NIGHT_PEEL,
    totalAmount: 50,
    amountUnit: 'ml',
    priceCents: 3600,
    description:
      'Peeling doux nocturne pour estomper les taches et unifier le teint grâce à une enzyme de papaye.',
    notes: 'Complexe dépigmentant. Enzyme de papaye. Niacinamide. Applicateur pinceau expert.',
    inci: 'AQUA/WATER/EAU, DICAPRYLYL ETHER, GLYCERIN, ISONONYL ISONONANOATE, NIACINAMIDE, SQUALANE, BEHENYL ALCOHOL, DIGLYCERIN, PROPYLENE GLYCOL, BUTYLENE GLYCOL, PROPANEDIOL, STEARETH-2, STEARETH-21, ALGIN, BENTONITE, CARBOMER, ETHYLHEXYL FERULATE, GLYCOLIPIDS, HYDROLYZED YEAST EXTRACT, PAPAIN, PENTAERYTHRITYL TETRA-DI-T-BUTYL HYDROXYHYDROCINNAMATE, YEAST EXTRACT, DIACETYL BOLDINE, TOCOPHEROL, UNDECYLENOYL PHENYLALANINE, 1,2-HEXANEDIOL, CAPRYLIC/CAPRIC TRIGLYCERIDE, CAPRYLYL GLYCOL, CITRIC ACID, GLYCERYL STEARATE, HYDROXYETHYL ACRYLATE/SODIUM ACRYLOYLDIMETHYL TAURATE COPOLYMER, JOJOBA ESTERS, PEG-100 STEARATE, PENTYLENE GLYCOL, POLYSORBATE 60, SORBITAN ISOSTEARATE, XANTHAN GUM, PARFUM/FRAGRANCE',
    url: 'https://fr.labo-svr.com',
  },
  {
    name: 'Densitium Bi-Sérum',
    brand: 'SVR',
    kind: 'skincare',
    unit: 'pump',
    slug: SVR_PRODUCT_SLUGS.SVR_DENSITIUM_BI_SERUM,
    totalAmount: 15,
    amountUnit: 'ml',
    priceCents: 4990,
    description:
      'Double sérum anti-gravité pour redensifier le visage, lutter contre le relâchement et le double menton.',
    notes:
      '45% actifs dermatologiques. Bio-calcium. Acide hyaluronique ultra-fragmenté. Duo anti-gravité.',
    inci: 'AQUA (PURIFIED WATER), DICAPRYLYL CARBONATE, ISONONYL ISONONANOATE, HEXYLDECYL STEARATE, OLEIC/LINOLEIC/LINOLENIC POLYGLYCERIDES, SQUALANE, PROPANEDIOL, HELIANTHUS ANNUUS (SUNFLOWER) SEED OIL, GLYCERYL BEHENATE/EICOSADIOATE, HYDROXYPROPYL STARCH PHOSPHATE, ARGANIA SPINOSA KERNEL OIL, BIXA ORELLANA SEED EXTRACT, BORAGO OFFICINALIS SEED OIL, GLYCINE SOJA (SOYBEAN) OIL, GLYCOLIPIDS, GLYCOSPHINGOLIPIDS, LAVANDULA STOECHAS EXTRACT, LEONTOPODIUM ALPINUM CALLUS CULTURE EXTRACT, LUPINUS ALBUS SEED EXTRACT, OENOTHERA BIENNIS (EVENING PRIMROSE) OIL, SESAMUM INDICUM (SESAME) OIL UNSAPONIFIABLES, ARTEMISIA ABROTANUM EXTRACT, CALCIUM PCA, GLYCERIN, HYALURONIC ACID, SACCHARIDE ISOMERATE, TOCOPHEROL, 1,2-HEXANEDIOL, ACACIA SENEGAL GUM, BUTYLENE GLYCOL, CAPRYLIC/CAPRIC TRIGLYCERIDE, CAPRYLYL GLYCOL, CITRIC ACID, PENTYLENE GLYCOL, SODIUM CITRATE, XANTHAN GUM, ALPHA-ISOMETHYL IONONE, CITRONELLOL, D-LIMONENE, LINALOOL, PARFUM (FRAGRANCE)',
    url: 'https://fr.labo-svr.com',
  },
  {
    name: 'Densitium Crème',
    brand: 'SVR',
    kind: 'skincare',
    unit: 'jar',
    slug: SVR_PRODUCT_SLUGS.SVR_DENSITIUM_CREME,
    totalAmount: 50,
    amountUnit: 'ml',
    priceCents: 4650,
    description:
      'Soin anti-âge global nourrissant qui raffermit la peau et unifie le teint des peaux normales à sèches.',
    notes:
      'Bio-calcium. Acide hyaluronique ultra-fragmenté. Peptides. Duo d’acides aminés anti-jaunissement.',
    inci: 'AQUA/WATER/EAU, OCTYLDODECANOL, VEGETABLE OIL, ORBIGNYA OLEIFERA SEED OIL, GLYCERYL STEARATE, GLYCERIN, BEHENETH-25, BEHENYL ALCOHOL, CETYL PALMITATE, CETEARYL ALCOHOL, 1,2-HEXANEDIOL, ARGININE PCA, CALCIUM PCA, SODIUM POLYACRYLOYLDIMETHYL TAURATE, BUTYLENE GLYCOL, HYDROXYACETOPHENONE, SODIUM STEAROYL LACTYLATE, MALTODEXTRIN, PARFUM (FRAGANCE), XANTHAN GUM, HYALURONIC ACID, LACTOBACILLUS FERMENT, PENTAERYTHRITYL TETRA-DI-T-BUTYL HYDROXYHYDROCINNAMATE, CARBOMER, SODIUM LACTATE, POLYSORBATE 20, SODIUM HYDROXIDE, PALMITOYL TRIPEPTIDE-1, PALMITOYL TETRAPEPTIDE-7',
    url: 'https://fr.labo-svr.com',
  },
  {
    name: 'Densitium Contour des Yeux',
    brand: 'SVR',
    kind: 'skincare',
    unit: 'pump',
    slug: SVR_PRODUCT_SLUGS.SVR_DENSITIUM_YEUX,
    totalAmount: 15,
    amountUnit: 'ml',
    priceCents: 3190,
    description:
      'Soin ciblé pour corriger les rides, les cernes et les poches du contour de l’œil.',
    notes:
      'Bio-calcium. Acide hyaluronique ultra-fragmenté. Baie de Goji. Tétrapeptides anti-poches.',
    inci: 'AQUA/WATER/EAU, OCTYLDODECANOL, BUTYROSPERMUM PARKII (SHEA) BUTTER, GLYCERIN, CETEARYL ALCOHOL, ORBIGNYA OLEIFERA SEED OIL, DISODIUM CETEARYL SULFOSUCCINATE, GLYCOL PALMITATE, SODIUM POLYACRYLATE, ARGININE PCA, CALCIUM PCA, CERA ALBA/BEESWAX/CIRE D’ABEILLE, GLYCERYL BEHENATE, CETEARETH-20, HYDROXYACETOPHENONE, PARFUM (FRAGRANCE), MALTODEXTRIN, CERATONIA SILIQUA GUM, XANTHAN GUM, 1,2-HEXANEDIOL, CAPRYLYL GLYCOL, HYALURONIC ACID, LACTOBACILLUS FERMENT, PENTAERYTHRITYL TETRA-DI-T-BUTYL HYDROXYHYDROCINNAMATE, PENTYLENE GLYCOL, LACTIC ACID, ROSMARINUS OFFICINALIS (ROSEMARY) LEAF EXTRACT, PALMITOYL TETRAPEPTIDE-7, CHRYSIN, CITRIC ACID',
    url: 'https://fr.labo-svr.com',
  },
]
console.log(SVR_PRODUCT_DATA.length)
console.log(Object.keys(SVR_PRODUCT_SLUGS).length)
