import { TAG_SLUGS } from '../../tags/seed-tags'
import { CYLA_PRODUCT_SLUGS } from './cyla'

export const CYLA_PRODUCT_TAGS: { productSlug: string; tagSlug: string }[] = [
  // Essence Initiale
  { productSlug: CYLA_PRODUCT_SLUGS.ESSENCE_INITIALE, tagSlug: TAG_SLUGS.ESSENCE },
  { productSlug: CYLA_PRODUCT_SLUGS.ESSENCE_INITIALE, tagSlug: TAG_SLUGS.HUMECTANT },
  { productSlug: CYLA_PRODUCT_SLUGS.ESSENCE_INITIALE, tagSlug: TAG_SLUGS.DESHYDRATATION },
  { productSlug: CYLA_PRODUCT_SLUGS.ESSENCE_INITIALE, tagSlug: TAG_SLUGS.BIOMIMETIQUE },
  { productSlug: CYLA_PRODUCT_SLUGS.ESSENCE_INITIALE, tagSlug: TAG_SLUGS.SANS_PARFUM },
  { productSlug: CYLA_PRODUCT_SLUGS.ESSENCE_INITIALE, tagSlug: TAG_SLUGS.SERUM },
  { productSlug: CYLA_PRODUCT_SLUGS.ESSENCE_INITIALE, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },
  { productSlug: CYLA_PRODUCT_SLUGS.ESSENCE_INITIALE, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },
  { productSlug: CYLA_PRODUCT_SLUGS.ESSENCE_INITIALE, tagSlug: TAG_SLUGS.ECLAT },

  // Gel Plume
  { productSlug: CYLA_PRODUCT_SLUGS.GEL_PLUME, tagSlug: TAG_SLUGS.NETTOYANT },
  { productSlug: CYLA_PRODUCT_SLUGS.GEL_PLUME, tagSlug: TAG_SLUGS.DEMAQUILLANT },
  { productSlug: CYLA_PRODUCT_SLUGS.GEL_PLUME, tagSlug: TAG_SLUGS.HUILE }, // Texture hybride 1ère étape
  { productSlug: CYLA_PRODUCT_SLUGS.GEL_PLUME, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },
  { productSlug: CYLA_PRODUCT_SLUGS.GEL_PLUME, tagSlug: TAG_SLUGS.SANS_PARFUM },
  { productSlug: CYLA_PRODUCT_SLUGS.GEL_PLUME, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },
  { productSlug: CYLA_PRODUCT_SLUGS.GEL_PLUME, tagSlug: TAG_SLUGS.REPARATEUR },

  // Crème Filante
  { productSlug: CYLA_PRODUCT_SLUGS.CREME_FILANTE, tagSlug: TAG_SLUGS.NETTOYANT },
  { productSlug: CYLA_PRODUCT_SLUGS.CREME_FILANTE, tagSlug: TAG_SLUGS.SANS_PARFUM },
  { productSlug: CYLA_PRODUCT_SLUGS.CREME_FILANTE, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },
  { productSlug: CYLA_PRODUCT_SLUGS.CREME_FILANTE, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },

  // Crème L

  // Crème Légère Initiale
  { productSlug: CYLA_PRODUCT_SLUGS.CREME_LEGERE_INITIALE, tagSlug: TAG_SLUGS.CREME_HYDRATANTE },
  { productSlug: CYLA_PRODUCT_SLUGS.CREME_LEGERE_INITIALE, tagSlug: TAG_SLUGS.PEAU_MIXTE },
  { productSlug: CYLA_PRODUCT_SLUGS.CREME_LEGERE_INITIALE, tagSlug: TAG_SLUGS.PEAU_GRASSE },
  { productSlug: CYLA_PRODUCT_SLUGS.CREME_LEGERE_INITIALE, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },
  { productSlug: CYLA_PRODUCT_SLUGS.CREME_LEGERE_INITIALE, tagSlug: TAG_SLUGS.BIOMIMETIQUE },
  { productSlug: CYLA_PRODUCT_SLUGS.CREME_LEGERE_INITIALE, tagSlug: TAG_SLUGS.SANS_PARFUM },
  { productSlug: CYLA_PRODUCT_SLUGS.CREME_LEGERE_INITIALE, tagSlug: TAG_SLUGS.SOIN_DE_JOUR },
  { productSlug: CYLA_PRODUCT_SLUGS.CREME_LEGERE_INITIALE, tagSlug: TAG_SLUGS.SOIN_DE_NUIT },
  { productSlug: CYLA_PRODUCT_SLUGS.CREME_LEGERE_INITIALE, tagSlug: TAG_SLUGS.PEAU_NORMALE },
  { productSlug: CYLA_PRODUCT_SLUGS.CREME_LEGERE_INITIALE, tagSlug: TAG_SLUGS.DESHYDRATATION },
  { productSlug: CYLA_PRODUCT_SLUGS.CREME_LEGERE_INITIALE, tagSlug: TAG_SLUGS.REPARATEUR },

  // Crème Intense Initiale
  { productSlug: CYLA_PRODUCT_SLUGS.CREME_INTENSE_INITIALE, tagSlug: TAG_SLUGS.CREME_HYDRATANTE },
  { productSlug: CYLA_PRODUCT_SLUGS.CREME_INTENSE_INITIALE, tagSlug: TAG_SLUGS.PEAU_SECHE },
  { productSlug: CYLA_PRODUCT_SLUGS.CREME_INTENSE_INITIALE, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },
  { productSlug: CYLA_PRODUCT_SLUGS.CREME_INTENSE_INITIALE, tagSlug: TAG_SLUGS.EMOLLIENT },
  { productSlug: CYLA_PRODUCT_SLUGS.CREME_INTENSE_INITIALE, tagSlug: TAG_SLUGS.BIOMIMETIQUE },
  { productSlug: CYLA_PRODUCT_SLUGS.CREME_INTENSE_INITIALE, tagSlug: TAG_SLUGS.SANS_PARFUM },
  { productSlug: CYLA_PRODUCT_SLUGS.CREME_INTENSE_INITIALE, tagSlug: TAG_SLUGS.CREME_HYDRATANTE },
  { productSlug: CYLA_PRODUCT_SLUGS.CREME_INTENSE_INITIALE, tagSlug: TAG_SLUGS.SOIN_DE_JOUR },
  { productSlug: CYLA_PRODUCT_SLUGS.CREME_INTENSE_INITIALE, tagSlug: TAG_SLUGS.SOIN_DE_NUIT },
  { productSlug: CYLA_PRODUCT_SLUGS.CREME_INTENSE_INITIALE, tagSlug: TAG_SLUGS.DESHYDRATATION },
  { productSlug: CYLA_PRODUCT_SLUGS.CREME_INTENSE_INITIALE, tagSlug: TAG_SLUGS.REPARATEUR },
  { productSlug: CYLA_PRODUCT_SLUGS.CREME_INTENSE_INITIALE, tagSlug: TAG_SLUGS.OCCLUSIF },
]
