import { TAG_SLUGS } from '../../tags/seed-tags'
import { COLIBRI_PRODUCT_SLUGS } from './colibri'

export const COLIBRI_PRODUCT_TAGS: { productSlug: string; tagSlug: string }[] = [
  // Brightening Booster (Azelaic 10%)
  {
    productSlug: COLIBRI_PRODUCT_SLUGS.COLIBRI_BRIGHTENING_BOOSTER,
    tagSlug: TAG_SLUGS.ANTI_ROUGEURS,
  },
  { productSlug: COLIBRI_PRODUCT_SLUGS.COLIBRI_BRIGHTENING_BOOSTER, tagSlug: TAG_SLUGS.ECLAT },
  {
    productSlug: COLIBRI_PRODUCT_SLUGS.COLIBRI_BRIGHTENING_BOOSTER,
    tagSlug: TAG_SLUGS.HYPERPIGMENTATION,
  },
  {
    productSlug: COLIBRI_PRODUCT_SLUGS.COLIBRI_BRIGHTENING_BOOSTER,
    tagSlug: TAG_SLUGS.PEAU_SENSIBLE,
  },
  { productSlug: COLIBRI_PRODUCT_SLUGS.COLIBRI_BRIGHTENING_BOOSTER, tagSlug: TAG_SLUGS.SERUM },
  {
    productSlug: COLIBRI_PRODUCT_SLUGS.COLIBRI_BRIGHTENING_BOOSTER,
    tagSlug: TAG_SLUGS.SANS_PARFUM,
  },

  // Pore Control Booster
  { productSlug: COLIBRI_PRODUCT_SLUGS.PORE_CONTROL_BOOSTER, tagSlug: TAG_SLUGS.PORES_DILATES },
  { productSlug: COLIBRI_PRODUCT_SLUGS.PORE_CONTROL_BOOSTER, tagSlug: TAG_SLUGS.BRILLANCE },
  { productSlug: COLIBRI_PRODUCT_SLUGS.PORE_CONTROL_BOOSTER, tagSlug: TAG_SLUGS.SEBO_REGULATEUR },
  { productSlug: COLIBRI_PRODUCT_SLUGS.PORE_CONTROL_BOOSTER, tagSlug: TAG_SLUGS.ANTI_ACNE },
  { productSlug: COLIBRI_PRODUCT_SLUGS.PORE_CONTROL_BOOSTER, tagSlug: TAG_SLUGS.SERUM },
  { productSlug: COLIBRI_PRODUCT_SLUGS.PORE_CONTROL_BOOSTER, tagSlug: TAG_SLUGS.NON_COMEDOGENE },

  // Calming Moisturizer
  { productSlug: COLIBRI_PRODUCT_SLUGS.CALMING_MOISTURIZER, tagSlug: TAG_SLUGS.PEAU_REACTIVE },
  { productSlug: COLIBRI_PRODUCT_SLUGS.CALMING_MOISTURIZER, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },
  { productSlug: COLIBRI_PRODUCT_SLUGS.CALMING_MOISTURIZER, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },
  { productSlug: COLIBRI_PRODUCT_SLUGS.CALMING_MOISTURIZER, tagSlug: TAG_SLUGS.REPARATEUR },
  { productSlug: COLIBRI_PRODUCT_SLUGS.CALMING_MOISTURIZER, tagSlug: TAG_SLUGS.CREME_HYDRATANTE },
  { productSlug: COLIBRI_PRODUCT_SLUGS.CALMING_MOISTURIZER, tagSlug: TAG_SLUGS.SANS_PARFUM },

  // Vitamin C 20 Booster
  { productSlug: COLIBRI_PRODUCT_SLUGS.VITAMIN_C_20_BOOSTER, tagSlug: TAG_SLUGS.ANTI_OXYDANT },
  { productSlug: COLIBRI_PRODUCT_SLUGS.VITAMIN_C_20_BOOSTER, tagSlug: TAG_SLUGS.ANTI_AGE },
  { productSlug: COLIBRI_PRODUCT_SLUGS.VITAMIN_C_20_BOOSTER, tagSlug: TAG_SLUGS.ANTI_TACHES },
  { productSlug: COLIBRI_PRODUCT_SLUGS.VITAMIN_C_20_BOOSTER, tagSlug: TAG_SLUGS.ECLAT },
  { productSlug: COLIBRI_PRODUCT_SLUGS.VITAMIN_C_20_BOOSTER, tagSlug: TAG_SLUGS.SERUM },
  { productSlug: COLIBRI_PRODUCT_SLUGS.VITAMIN_C_20_BOOSTER, tagSlug: TAG_SLUGS.SANS_PARFUM },

  // Vitamin C15 Booster
  { productSlug: COLIBRI_PRODUCT_SLUGS.VITAMIN_C15_BOOSTER, tagSlug: TAG_SLUGS.ANTI_OXYDANT },
  { productSlug: COLIBRI_PRODUCT_SLUGS.VITAMIN_C15_BOOSTER, tagSlug: TAG_SLUGS.ECLAT },
  { productSlug: COLIBRI_PRODUCT_SLUGS.VITAMIN_C15_BOOSTER, tagSlug: TAG_SLUGS.DESHYDRATATION },
  { productSlug: COLIBRI_PRODUCT_SLUGS.VITAMIN_C15_BOOSTER, tagSlug: TAG_SLUGS.SERUM },
  { productSlug: COLIBRI_PRODUCT_SLUGS.VITAMIN_C15_BOOSTER, tagSlug: TAG_SLUGS.HUMECTANT },

  // Barrier Booster
  { productSlug: COLIBRI_PRODUCT_SLUGS.BARRIER_BOOSTER, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },
  { productSlug: COLIBRI_PRODUCT_SLUGS.BARRIER_BOOSTER, tagSlug: TAG_SLUGS.REPARATEUR },
  { productSlug: COLIBRI_PRODUCT_SLUGS.BARRIER_BOOSTER, tagSlug: TAG_SLUGS.EMOLLIENT },
  { productSlug: COLIBRI_PRODUCT_SLUGS.BARRIER_BOOSTER, tagSlug: TAG_SLUGS.PEAU_ATOPIQUE },
  { productSlug: COLIBRI_PRODUCT_SLUGS.BARRIER_BOOSTER, tagSlug: TAG_SLUGS.SERUM },
  { productSlug: COLIBRI_PRODUCT_SLUGS.BARRIER_BOOSTER, tagSlug: TAG_SLUGS.SANS_PARFUM },

  // Antioxidant Serum
  { productSlug: COLIBRI_PRODUCT_SLUGS.ANTIOXIDANT_SERUM, tagSlug: TAG_SLUGS.ANTI_OXYDANT },
  { productSlug: COLIBRI_PRODUCT_SLUGS.ANTIOXIDANT_SERUM, tagSlug: TAG_SLUGS.ANTI_AGE },
  { productSlug: COLIBRI_PRODUCT_SLUGS.ANTIOXIDANT_SERUM, tagSlug: TAG_SLUGS.ECLAT },
  { productSlug: COLIBRI_PRODUCT_SLUGS.ANTIOXIDANT_SERUM, tagSlug: TAG_SLUGS.SERUM },
  { productSlug: COLIBRI_PRODUCT_SLUGS.ANTIOXIDANT_SERUM, tagSlug: TAG_SLUGS.SOIN_DE_JOUR },
]
