// Unknown brands encountered during fetch
// These brands were found in OpenBeautyFacts France but NOT in BRAND_NAMES whitelist
// Generated on: 2026-03-08T11:00:31.508Z
// Total unknown brands: 618

export const UNKNOWN_BRANDS = [
  '3 chênes beauté',
  '3en1',
  '7th Heaven',
  '900 .care',
  '900 care',
  '900.care',
  '900care',
  'ADIDAS',
  'ARNAUD Paris',
  'ARTSAM',
  'AXE',
  'Action',
  'Agrado',
  'Alba',
  'Aleyria Cosmétiques',
  'Alphanova',
  'Alvadiem',
  'Alverde',
  'Always',
  'Amalfi',
  'Amilab',
  'Anaca 3',
  'Ananda & Cie',
  'Anglamark',
  'Anios',
  'Apaisyl',
  'Aptonia',
  'Aquafresh',
  'Argasol',
  'Argiletz',
  'Ariul',
  'Aromandise',
  'Asepta',
  'Asinerie des Varennes',
  'Atelier du lautaret',
  'Atoa',
  'Au Lait',
  'Auchan',
  'Auchan Baby',
  'Auchan Baby Bio',
  'Auchan Bio',
  'Aussie',
  'Avogood Time With Me',
  'Axe',
  'Ayur-vana',
  'Azbane',
  'BIO',
  'BIOLANE',
  'BREVIA',
  'Babysoin',
  'Bactidose',
  'Balea',
  'Balia',
  'Ballot flurin',
  'Ballot-Flurin',
  'Barb\'Art',
  'Batiste',
  'Baume du tigre made by Olic ltd Thailand',
  'BeauTerra',
  'Bed head',
  'Beesline',
  'Beiersdorf',
  'Beiesdorf',
  'Bella baby',
  'Belo',
  'Berdoues parfums et cosmétiques',
  'Biences',
  'Bilboa',
  'Bio Labell',
  'Bio Naïa',
  'Bio k',
  'Bio naïa',
  'BioKARITÉ',
  'Biocoop',
  'Biogaran',
  'Biolane',
  'Biomed',
  'Bioorganique',
  'Biopha',
  'Bioseptyl',
  'Biovie',
  'Biovie Lea Nature',
  'Blondépil',
  'Bonpreu',
  'Boutique Nature',
  'Bretagne Cosmétiques Marins',
  'Briochin',
  'Brush Baby',
  'Brut',
  'Bull Dog',
  'Bulldog',
  'By U',
  'Byly',
  'Byphasse',
  'Bébé Cadum',
  'CATTIER',
  'CHARCOAL',
  'CHARCOAL TOOTHPASTE',
  'COSMO NATUREL',
  'Cajoline',
  'California Naturals',
  'Cantu',
  'Caron',
  'Carrefour',
  'Carrefour Soft',
  'Cartier Paris',
  'Casino',
  'Catrice',
  'Cattier',
  'Ce\'BIO',
  'Centifolia',
  'Champs de Provence',
  'Chemins d\'Orient',
  'Christophe Robin',
  'Cicabiafine',
  'Clarins',
  'Clémence & Vivien',
  'Coco SOUPLINE',
  'Colgate',
  'Colgate Palmolive',
  'Colgate-Palmolive',
  'CollectOr',
  'Cooper',
  'Cora',
  'Coriana',
  'Corine de Farme',
  'Corinne de farme',
  'Corpore Sano',
  'Coslys',
  'Cosm\'ethik',
  'Cosmia',
  'Cosmia Baby',
  'Cosmia Bio',
  'Cosmo Naturel',
  'Cosmonaturel',
  'Cotril',
  'Cottage',
  'Couleurs Nature',
  'Creme of nature',
  'Crusoé',
  'DOP',
  'Dabur ltd',
  'Dax & Terra',
  'De Saint Hilaire',
  'Decathlon',
  'Deliplus',
  'Denta Pro',
  'Dentalux',
  'Dentamyl',
  'Dentavie',
  'Dentifrice',
  'Dercos',
  'Derhum',
  'Dermaclay',
  'Dermophil',
  'Dermophil indien',
  'Desert Essence',
  'Dessange',
  'Doliprane',
  'Dop',
  'Douce Nature',
  'Douce nature',
  'Dr. Herma',
  'Durex',
  'Décathlon',
  'Déesse',
  'EAfit',
  'Eco +',
  'Eco+',
  'Ecoclair',
  'Ecolabel',
  'Ecos',
  'Efiseptyl',
  'Eg labo',
  'Ehrmann',
  'Elgidium',
  'Elmex',
  'Elsrve',
  'Emma Noël',
  'Endro',
  'Energie Fruit',
  'EtiaXil',
  'Etiaxil',
  'Eugène Perma',
  'EvoLuderm',
  'Evoluderm',
  'Explain',
  'FLEURANCE NATURE',
  'FORTÉPHARMA',
  'Fa',
  'Fabfactory',
  'Faith in nature',
  'Femfresh',
  'Fess\'Net',
  'Fessnett',
  'Florame',
  'Floressance',
  'Fluocaril',
  'Formil',
  'Fragonard',
  'Franck PROVOST',
  'Franck Provost',
  'Franck Provost Paris',
  'Frosch',
  'G. Pohl-Boskamp',
  'GSK',
  'Galeo',
  'Garnier Ultra Doux',
  'Gerlon',
  'Gilette',
  'Gillette',
  'Givenchy',
  'GlaxoSmithKline',
  'Gliss',
  'Grazie',
  'Groupe Ice',
  'Guerlain Paris',
  'HEAD & SHOULDERS',
  'HOLLAND\'S FINEST',
  'Hakle',
  'Hawaiian Tropic',
  'Hawaiian tropic',
  'Head & Shoulders',
  'Heads & shoulders',
  'Henkel',
  'Herbalife',
  'Hindustan Unilever Limited',
  'Horace',
  'Huggies',
  'Hugo Boss',
  'Hyfac',
  'Hygie',
  'Hyper U',
  'Héloïse',
  'IPRAD',
  'ISANA',
  'Inecto',
  'Inell',
  'Innovit',
  'Insectes comestibles',
  'Intermarché',
  'Intima',
  'Intimy',
  'Isabel',
  'Isana Professional',
  'Ivy aïa',
  'JEANNE EN PROVENCE',
  'Jack\'s cream',
  'Jacques Briochin',
  'Jardin D\'oléane',
  'Jean-Paul GAULTIER',
  'Jeanne Arthes',
  'Jil Sander',
  'John Frieda',
  'Johnson & Johnson',
  'Johnson\'s',
  'Jowaé',
  'Juzo',
  'Jx F',
  'KAP',
  'KERALA NATURE',
  'KERASOIN',
  'Karo Pharma',
  'Kenzo',
  'Keranove Naturanove',
  'Kiko',
  'Kiko Milano',
  'Kneipp',
  'Kraze',
  'Krème',
  'L\'Arbre Vert',
  'L\'OREAL NORGE AS',
  'L\'Oréal',
  'L\'Oréal Men Expert',
  'L\'Oréal Paris Elseve',
  'L\'arbre vert',
  'LM Bio cosmétiques',
  'La Barbière de Paris',
  'La Boucle',
  'La Fourche',
  'La Savonnières du Moulin',
  'La Soulane',
  'La Vie Claire',
  'La vie est à Nous',
  'Labell',
  'Labell Men',
  'Labell bio',
  'Lacura',
  'Laino',
  'Lait soin désaltérant',
  'Lancaster',
  'Lavera',
  'Le Briochin',
  'Lenor',
  'Leonor grey',
  'Les Cosmétiques Design Paris',
  'Les Petits Plaisirs',
  'Les Plaisirs Nature',
  'Les petits bains de Provence',
  'Licor del Polo',
  'Lily of the desert',
  'Listerine',
  'Logodent',
  'Logona',
  'Lolu',
  'Loovara',
  'Lotus',
  'Louise émoi',
  'Love & Green',
  'Love Beauty and Planet',
  'Love and be Loved',
  'Love beauty and planet',
  'Lovea',
  'Luminelle',
  'Lupilu',
  'Lux',
  'LÉA NATURE SO BIO ETIC',
  'Léa NATURE',
  'Léa Nature',
  'Léa nature',
  'L’Oréal Men Expert',
  'L’oreal',
  'MB Cosmetics',
  'MIR',
  'MONT LURE',
  'MRS AND LADY\'S',
  'MYLA',
  'Magasins U',
  'Maisitoo',
  'Maison Sidonie Champagne',
  'Maison Verte',
  'Maison verte',
  'Manava',
  'Marionnaud',
  'Marius Fabre',
  'Marque Repere',
  'Marque Repère',
  'Max & More',
  'Maxbrands marketing',
  'Maxilase',
  'Medicine of the People',
  'Melvita',
  'Mennen',
  'Mercadona',
  'Mercurochrome',
  'MiR',
  'Miele',
  'Mitosyl',
  'Mkl green nature',
  'Monoprix',
  'Monsavon',
  'Mont St Michel',
  'Mother’s earth',
  'Mussofi',
  'MyLubie',
  'N.A.E',
  'N.A.E.',
  'NARTA',
  'NAZCA',
  'Naf Naf',
  'Najel',
  'Nana',
  'Narta',
  'Narta Homme',
  'Nat&Nove',
  'Nateïs',
  'Natracare',
  'Natural Honey',
  'Nature Box',
  'Naturé Moi',
  'Naté',
  'Nett',
  'Nidé.co',
  'Nivea Men',
  'Nivea for men',
  'Nivea men',
  'Nivea sun',
  'Null',
  'NutriBiotic',
  'OGX',
  'OLIVELLA',
  'OLiVELLA',
  'ONIC',
  'OPLAPLEX',
  'OPTISMILE NATURAL',
  'OSMA',
  'Oenobiol',
  'OptiSmile',
  'Oral-B',
  'Organic shop',
  'Organique by Himalaya Herbal Healthcare',
  'Original beard balm',
  'Out of India',
  'PALMOLIVE',
  'PARODONTAX',
  'PIERRE FABRE ORALE CARE',
  'PULPE DE VIE',
  'Palmer\'s',
  'Palmer’s',
  'Palmolive',
  'Pampers',
  'Parasol',
  'Parodontax',
  'Passage du désir',
  'Pasta del Capitano',
  'Paãvo',
  'Perle de Jument',
  'Persavon',
  'Pharmactiv',
  'Pharmamil',
  'Phy',
  'Pic sol',
  'Pimpant',
  'Pipkin',
  'Planete Au Naturel',
  'Planters',
  'Plex care',
  'Pomette',
  'Pommette',
  'Pouce',
  'Pranarōm',
  'Prephar',
  'Prim\'soins',
  'Primark',
  'Prix Mini',
  'Procter & Gamble',
  'Proraso',
  'Pulpe de vie',
  'Pur Aloé',
  'Pur essentiel',
  'Pure & Care',
  'Puressential',
  'Puressentiel',
  'Pétrole Hahn',
  'Pétrole hahn',
  'QIPAO',
  'R+Co',
  'RITUALS...',
  'Rainett zero%',
  'Rampal Latour',
  'Rampâl Latour',
  'Regenerate',
  'René FURTERER',
  'Respectueuse',
  'Respire',
  'Revlon',
  'Rexona',
  'Rexona Men',
  'Rimmel',
  'Rituals',
  'Rossmann',
  'S\'nonas',
  'SANEX',
  'SARYANE',
  'SAUGELLA',
  'SAVONNERIE AUBAGNAISE',
  'SB',
  'SC Johnson',
  'SCHWARZE SEIFE',
  'SENSODYNE',
  'SIPRES',
  'Saint-Gervais Mont Blanc',
  'Sanaka bio',
  'Sanex',
  'Sanofi',
  'Sanytol',
  'Savon Le Naturel',
  'Savon artisanal du Val d\'Argent',
  'Savon le naturel',
  'Savonnerie Rampal Latour',
  'Savonnerie du Regagnas',
  'Schmidt\'s',
  'Schmidt’s',
  'Scholl',
  'Schwarzkopf and Henkel',
  'Secret',
  'Sensodyne',
  'Shea Moisture',
  'Shea moisture',
  'Signal',
  'Skip',
  'Smart',
  'Smithkine',
  'So Authentic',
  'So Bio',
  'So Bio Etic',
  'So Bio Etic Léa Nature',
  'So\'Bio Etic',
  'So\'bio étic',
  'Sobio',
  'Soft (carrefour)',
  'Sol de Janeiro',
  'Sothys',
  'Soupline',
  'Spirosan',
  'Sports Akileine',
  'Sun Dance',
  'Syoss',
  'Tahiti',
  'TeddyCare',
  'The Green Emporium',
  'The Humble Co',
  'This IS it',
  'Tigi',
  'Timotei',
  'Tomotheí',
  'Tontree',
  'Treacle moon',
  'Triswim',
  'Ty',
  'U',
  'U Bio',
  'U bio',
  'Ulric de Varens',
  'Ultra rafraîchissante',
  'Umbro',
  'Un ottled',
  'Unbottled',
  'Unilever',
  'Unilever norge as',
  'Unknown',
  'Ushuaia',
  'Ushuaïa',
  'Vademecum',
  'Vaseline',
  'Vassilena Cosmetics',
  'Veet',
  'Venus',
  'Vichy Homme',
  'Viofluor',
  'Vitanove',
  'Vitanove styling',
  'Wake up',
  'Wella',
  'Wild',
  'Williams',
  'Woogie',
  'Wouroud parfums',
  'XHC',
  'XueShanBaiCao',
  'Yasuragi Spa',
  'Yes love nail care',
  'Ysiance',
  'Yves Saint Laurent',
  'Zef',
  'Zenova suncare',
  'Zenzitude',
  'Ziaja',
  'ZzzQuil Sommeil',
  'acorelle',
  'alphanova sun',
  'always',
  'bio naïa',
  'bio.k',
  'biocoop',
  'bonté Everyday',
  'by U homme',
  'bébé cadum',
  'canenco',
  'cattier',
  'cigalbio',
  'codage Paris',
  'colgate',
  'comptoirs et compagnies',
  'copura',
  'cosmolive',
  'delab',
  'dentalux LIDL',
  'earth balance',
  'ekolep',
  'elmex',
  'evoluderm',
  'fer à cheval',
  'floralys',
  'greenweez',
  'head & shoulders',
  'hema',
  'henkel',
  'intimate care',
  'l arbre vert',
  'l\'arbre vert',
  'l-oreal',
  'la vie claire',
  'labell',
  'les petits bains de provence',
  'love & green',
  'maison verte',
  'mane\'n tail and body',
  'mennen',
  'mercurochrome',
  'monoprix',
  'nivea men',
  'null',
  'out of the blue',
  'pampers',
  'parasol',
  'parondontax',
  'planta viva',
  'rloralys de Lidl',
  'rossman',
  'sanex',
  'sanytol',
  'sasi',
  'sensodyne',
  'skincare',
  'text',
  'the saem',
  'this is it',
  'u',
  'un coin de provence',
  'unilever',
  'upsa',
  'ushuai',
  'vitabeast.fr',
  'vitalio',
  'wild',
  'Énergie fruit bio',
  'énergie fruit'
] as const;

// Copy-paste interesting brands from here to BRAND_NAMES if needed
