import { TAG_SLUGS } from '../../tags/seed-tags'
import { BOJ_PDOCUT_SLUGS } from './beautyOfJoseon'

export const BEAUTY_OF_JOSEON_PRODUCT_TAGS: { productSlug: string; tagSlug: string }[] = [
  // Dynasty Cream
  {
    productSlug: BOJ_PDOCUT_SLUGS.BEAUTY_OF_JOSEON_DYNASTY_CREAM,
    tagSlug: TAG_SLUGS.CREME_HYDRATANTE,
  },
  { productSlug: BOJ_PDOCUT_SLUGS.BEAUTY_OF_JOSEON_DYNASTY_CREAM, tagSlug: TAG_SLUGS.ECLAT },
  {
    productSlug: BOJ_PDOCUT_SLUGS.BEAUTY_OF_JOSEON_DYNASTY_CREAM,
    tagSlug: TAG_SLUGS.BARRIERE_CUTANEE,
  },
  { productSlug: BOJ_PDOCUT_SLUGS.BEAUTY_OF_JOSEON_DYNASTY_CREAM, tagSlug: TAG_SLUGS.OCCLUSIF },
  { productSlug: BOJ_PDOCUT_SLUGS.BEAUTY_OF_JOSEON_DYNASTY_CREAM, tagSlug: TAG_SLUGS.SANS_PARFUM },
  { productSlug: BOJ_PDOCUT_SLUGS.BEAUTY_OF_JOSEON_DYNASTY_CREAM, tagSlug: TAG_SLUGS.PEAU_NORMALE },

  // Ginseng Essence Water
  { productSlug: BOJ_PDOCUT_SLUGS.BOJ_GINSENG_ESSENCE_WATER, tagSlug: TAG_SLUGS.TONIQUE },
  { productSlug: BOJ_PDOCUT_SLUGS.BOJ_GINSENG_ESSENCE_WATER, tagSlug: TAG_SLUGS.DESHYDRATATION },
  { productSlug: BOJ_PDOCUT_SLUGS.BOJ_GINSENG_ESSENCE_WATER, tagSlug: TAG_SLUGS.ECLAT },
  { productSlug: BOJ_PDOCUT_SLUGS.BOJ_GINSENG_ESSENCE_WATER, tagSlug: TAG_SLUGS.ANTI_OXYDANT },
  { productSlug: BOJ_PDOCUT_SLUGS.BOJ_GINSENG_ESSENCE_WATER, tagSlug: TAG_SLUGS.HUMECTANT },
  { productSlug: BOJ_PDOCUT_SLUGS.BOJ_GINSENG_ESSENCE_WATER, tagSlug: TAG_SLUGS.SANS_PARFUM },

  // Glow Replenishing Rice Milk
  { productSlug: BOJ_PDOCUT_SLUGS.BEAUTY_OF_JOSEON_GLOW_RICE_MILK, tagSlug: TAG_SLUGS.TONIQUE },
  { productSlug: BOJ_PDOCUT_SLUGS.BEAUTY_OF_JOSEON_GLOW_RICE_MILK, tagSlug: TAG_SLUGS.BRILLANCE },
  {
    productSlug: BOJ_PDOCUT_SLUGS.BEAUTY_OF_JOSEON_GLOW_RICE_MILK,
    tagSlug: TAG_SLUGS.PORES_DILATES,
  },
  { productSlug: BOJ_PDOCUT_SLUGS.BEAUTY_OF_JOSEON_GLOW_RICE_MILK, tagSlug: TAG_SLUGS.PEAU_MIXTE },
  { productSlug: BOJ_PDOCUT_SLUGS.BEAUTY_OF_JOSEON_GLOW_RICE_MILK, tagSlug: TAG_SLUGS.PEAU_GRASSE },
  { productSlug: BOJ_PDOCUT_SLUGS.BEAUTY_OF_JOSEON_GLOW_RICE_MILK, tagSlug: TAG_SLUGS.SANS_PARFUM },

  // Relief Sun Aqua-fresh
  {
    productSlug: BOJ_PDOCUT_SLUGS.BOJ_RELIEF_SUN_AQUA_FRESH,
    tagSlug: TAG_SLUGS.PROTECTION_SOLAIRE,
  },
  { productSlug: BOJ_PDOCUT_SLUGS.BOJ_RELIEF_SUN_AQUA_FRESH, tagSlug: TAG_SLUGS.PEAU_MIXTE },
  { productSlug: BOJ_PDOCUT_SLUGS.BOJ_RELIEF_SUN_AQUA_FRESH, tagSlug: TAG_SLUGS.PEAU_GRASSE },
  { productSlug: BOJ_PDOCUT_SLUGS.BOJ_RELIEF_SUN_AQUA_FRESH, tagSlug: TAG_SLUGS.DESHYDRATATION },
  { productSlug: BOJ_PDOCUT_SLUGS.BOJ_RELIEF_SUN_AQUA_FRESH, tagSlug: TAG_SLUGS.NON_COMEDOGENE },
  { productSlug: BOJ_PDOCUT_SLUGS.BOJ_RELIEF_SUN_AQUA_FRESH, tagSlug: TAG_SLUGS.SANS_PARFUM },
]
