import { TAG_SLUGS } from '../../tags/seed-tags'
import { MIXA_PRODUCT_SLUGS } from './mixa'

export const MIXA_PRODUCT_TAGS: { productSlug: string; tagSlug: string }[] = [
  // Crème Niacinamide Correction Éclat
  { productSlug: MIXA_PRODUCT_SLUGS.NIACINAMIDE_CORRECTION_ECLAT, tagSlug: TAG_SLUGS.ANTI_TACHES },
  {
    productSlug: MIXA_PRODUCT_SLUGS.NIACINAMIDE_CORRECTION_ECLAT,
    tagSlug: TAG_SLUGS.HYPERPIGMENTATION,
  },
  { productSlug: MIXA_PRODUCT_SLUGS.NIACINAMIDE_CORRECTION_ECLAT, tagSlug: TAG_SLUGS.ECLAT },
  { productSlug: MIXA_PRODUCT_SLUGS.NIACINAMIDE_CORRECTION_ECLAT, tagSlug: TAG_SLUGS.PEAU_SECHE },

  // Crème Fraîche et Fondante à l'Acide Hyaluronique
  { productSlug: MIXA_PRODUCT_SLUGS.ACIDE_HYALURONIQUE_FRAICHE, tagSlug: TAG_SLUGS.DESHYDRATATION },
  { productSlug: MIXA_PRODUCT_SLUGS.ACIDE_HYALURONIQUE_FRAICHE, tagSlug: TAG_SLUGS.HUMECTANT },
  {
    productSlug: MIXA_PRODUCT_SLUGS.ACIDE_HYALURONIQUE_FRAICHE,
    tagSlug: TAG_SLUGS.CREME_HYDRATANTE,
  },

  // Crème pour Peaux Sèches et Sensibles
  { productSlug: MIXA_PRODUCT_SLUGS.PEAUX_SECHES_SENSIBLES, tagSlug: TAG_SLUGS.PEAU_SECHE },
  { productSlug: MIXA_PRODUCT_SLUGS.PEAUX_SECHES_SENSIBLES, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },
  { productSlug: MIXA_PRODUCT_SLUGS.PEAUX_SECHES_SENSIBLES, tagSlug: TAG_SLUGS.EMOLLIENT },

  // Crème Panthénol Confort
  { productSlug: MIXA_PRODUCT_SLUGS.PANTHENOL_CONFORT, tagSlug: TAG_SLUGS.PEAU_REACTIVE },
  { productSlug: MIXA_PRODUCT_SLUGS.PANTHENOL_CONFORT, tagSlug: TAG_SLUGS.PEAU_ATOPIQUE },
  { productSlug: MIXA_PRODUCT_SLUGS.PANTHENOL_CONFORT, tagSlug: TAG_SLUGS.SANS_PARFUM },
  { productSlug: MIXA_PRODUCT_SLUGS.PANTHENOL_CONFORT, tagSlug: TAG_SLUGS.REPARATEUR },

  // Crème Céramide Protection
  { productSlug: MIXA_PRODUCT_SLUGS.CERAMIDE_PROTECTION, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },
  { productSlug: MIXA_PRODUCT_SLUGS.CERAMIDE_PROTECTION, tagSlug: TAG_SLUGS.PEAU_ATOPIQUE },
  { productSlug: MIXA_PRODUCT_SLUGS.CERAMIDE_PROTECTION, tagSlug: TAG_SLUGS.SANS_PARFUM },
  { productSlug: MIXA_PRODUCT_SLUGS.CERAMIDE_PROTECTION, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },

  // Crème Cica Réparation (Urée)
  { productSlug: MIXA_PRODUCT_SLUGS.CICA_REPARATION, tagSlug: TAG_SLUGS.EXFOLIANT },
  { productSlug: MIXA_PRODUCT_SLUGS.CICA_REPARATION, tagSlug: TAG_SLUGS.KERATOLYTIQUE },
  { productSlug: MIXA_PRODUCT_SLUGS.CICA_REPARATION, tagSlug: TAG_SLUGS.REPARATEUR },
  { productSlug: MIXA_PRODUCT_SLUGS.CICA_REPARATION, tagSlug: TAG_SLUGS.PEAU_SECHE },

  // Crème des Peaux Très Sèches et Ternes (Cacao)
  { productSlug: MIXA_PRODUCT_SLUGS.PEAUX_TRES_SECHES_TERNES, tagSlug: TAG_SLUGS.PEAU_SECHE },
  { productSlug: MIXA_PRODUCT_SLUGS.PEAUX_TRES_SECHES_TERNES, tagSlug: TAG_SLUGS.ECLAT },
  { productSlug: MIXA_PRODUCT_SLUGS.PEAUX_TRES_SECHES_TERNES, tagSlug: TAG_SLUGS.OCCLUSIF },
]
