import { TAG_SLUGS } from '../../tags/seed-tags'
import { SERUMS_PEPTIDES_PRODUCT_SLUGS } from './serums-peptides'

export const PEPTIDES_PRODUCT_TAGS: { productSlug: string; tagSlug: string }[] = [
  {
    productSlug: SERUMS_PEPTIDES_PRODUCT_SLUGS.NIOD_COPPER_AMINO_ISOLATE_LIPID_1,
    tagSlug: TAG_SLUGS.ANTI_AGE,
  },
  {
    productSlug: SERUMS_PEPTIDES_PRODUCT_SLUGS.NIOD_COPPER_AMINO_ISOLATE_LIPID_1,
    tagSlug: TAG_SLUGS.BARRIERE_CUTANEE,
  },
  {
    productSlug: SERUMS_PEPTIDES_PRODUCT_SLUGS.NIOD_COPPER_AMINO_ISOLATE_LIPID_1,
    tagSlug: TAG_SLUGS.DESHYDRATATION,
  },
  {
    productSlug: SERUMS_PEPTIDES_PRODUCT_SLUGS.NIOD_COPPER_AMINO_ISOLATE_LIPID_1,
    tagSlug: TAG_SLUGS.PEAU_SECHE,
  },
  {
    productSlug: SERUMS_PEPTIDES_PRODUCT_SLUGS.NIOD_COPPER_AMINO_ISOLATE_LIPID_1,
    tagSlug: TAG_SLUGS.SOIN_DE_NUIT,
  },
  {
    productSlug: SERUMS_PEPTIDES_PRODUCT_SLUGS.NIOD_COPPER_AMINO_ISOLATE_LIPID_1,
    tagSlug: TAG_SLUGS.SERUM,
  },
  {
    productSlug: SERUMS_PEPTIDES_PRODUCT_SLUGS.NIOD_COPPER_AMINO_ISOLATE_LIPID_1,
    tagSlug: TAG_SLUGS.ANTI_OXYDANT,
  },
  {
    productSlug: SERUMS_PEPTIDES_PRODUCT_SLUGS.NIOD_COPPER_AMINO_ISOLATE_LIPID_1,
    tagSlug: TAG_SLUGS.REPARATEUR,
  },
  {
    productSlug: SERUMS_PEPTIDES_PRODUCT_SLUGS.NOOANCE_PEPTIDES_CUIVRE_2,
    tagSlug: TAG_SLUGS.ANTI_AGE,
  },
  {
    productSlug: SERUMS_PEPTIDES_PRODUCT_SLUGS.NOOANCE_PEPTIDES_CUIVRE_2,
    tagSlug: TAG_SLUGS.BARRIERE_CUTANEE,
  },
  {
    productSlug: SERUMS_PEPTIDES_PRODUCT_SLUGS.NOOANCE_PEPTIDES_CUIVRE_2,
    tagSlug: TAG_SLUGS.SOIN_DE_JOUR,
  },
  {
    productSlug: SERUMS_PEPTIDES_PRODUCT_SLUGS.NOOANCE_PEPTIDES_CUIVRE_2,
    tagSlug: TAG_SLUGS.SOIN_DE_NUIT,
  },
  {
    productSlug: SERUMS_PEPTIDES_PRODUCT_SLUGS.NOOANCE_PEPTIDES_CUIVRE_2,
    tagSlug: TAG_SLUGS.SERUM,
  },
  {
    productSlug: SERUMS_PEPTIDES_PRODUCT_SLUGS.NOOANCE_PEPTIDES_CUIVRE_2,
    tagSlug: TAG_SLUGS.HUMECTANT,
  },
  {
    productSlug: SERUMS_PEPTIDES_PRODUCT_SLUGS.NOOANCE_PEPTIDES_CUIVRE_2,
    tagSlug: TAG_SLUGS.REPARATEUR,
  },
  {
    productSlug: SERUMS_PEPTIDES_PRODUCT_SLUGS.NOOANCE_PEPTIDES_CUIVRE_2,
    tagSlug: TAG_SLUGS.NON_COMEDOGENE,
  },
]
