export const GG_PRODUCTS_SLUGS = {
  GG_A_GAME_20: 'geek-gorgeous-a-game-20',
  GG_HYDRATION_STATION: 'geek-gorgeous-hydration-station',
  GEEK_GORGEOUS_POWER_PEPTIDES: 'geek-gorgeous-power-peptides',
  CALM_DOWN: 'geek-gorgeous-calm-down',
  CHEER_UP: 'geek-gorgeous-cheer-up',
  SMOOTH_OUT: 'geek-gorgeous-smooth-out',
  MIGHTY_MELT: 'geek-gorgeous-mighty-melt',
  JELLY_JOKER: 'geek-gorgeous-jelly-joker',
  LIQUID_HYDRATION: 'geek-gorgeous-liquid-hydration',
  HAPPIER_BARRIER: 'geek-gorgeous-happier-barrier',
  A_GAME_10: 'geek-gorgeous-a-game-10',
  A_GAME_5: 'geek-gorgeous-a-game-5',
  C_GLOW: 'geek-gorgeous-c-glow',
  STRESS_LESS: 'geek-gorgeous-stress-less',
  APAD: 'geek-gorgeous-apad',
  B_BOMB: 'geek-gorgeous-b-bomb',
  POREFECTLY_CLEAR: 'geek-gorgeous-porefectly-clear',
  HA_5_LIGHT: 'geek-gorgeous-ha-5-light',
  HA_5_RICH: 'geek-gorgeous-ha-5-rich',
}

export const GG_PRODUCTS_DATA = [
  {
    name: 'Power Peptides Serum',
    brand: 'Geek & Gorgeous',
    slug: GG_PRODUCTS_SLUGS.GEEK_GORGEOUS_POWER_PEPTIDES,
    kind: 'skincare',
    unit: 'dropper',
    totalAmount: 30,
    amountUnit: 'ml',
    priceCents: 1500,
    description:
      'Sérum anti-âge concentré en peptides (Matrixyl, copper peptides, etc.) pour booster le collagène, réduire rides et améliorer fermeté/élasticité.',
    notes:
      'Formule riche en peptides variés + panthénol/allantoïne. Sans parfum, adapté aux routines anti-âge.',
    inci: 'AQUA (WATER), GLYCERIN, BUTYLENE GLYCOL, PENTYLENE GLYCOL, POLYGLYCERYL-6 STEARATE, CAPRYLIC/CAPRIC TRIGLYCERIDE, PANTHENOL, DICAPRYLYL CARBONATE, DICAPRYLYL ETHER, POTASSIUM CETYL PHOSPHATE, POLYGLYCERYL-6 BEHENATE, TETRAPEPTIDE-21, PALMITOYL TRIPEPTIDE-1, PALMITOYL TETRAPEPTIDE-7, PALMITOYL TRIPEPTIDE-38, COPPER PALMITOYL HEPTAPEPTIDE-14, HEPTAPEPTIDE-15 PALMITATE, SACCHARIDE ISOMERATE, ALLANTOIN, CETEARYL ALCOHOL, GLYCERYL STEARATE SE, TAPIOCA STARCH, ACRYLATES/C10-30 ALKYL ACRYLATE CROSSPOLYMER, CARBOMER, POLYSORBATE 20, HYDROXYPROPYL CYCLODEXTRIN, LACTIC ACID/GLYCOLIC ACID COPOLYMER, POLYVINYL ALCOHOL, CITRIC ACID, SODIUM CITRATE, SODIUM HYDROXIDE, PHENOXYETHANOL, ETHYLHEXYLGLYCERIN',
    url: 'https://geekandgorgeous.com',
  },
  {
    name: 'A-Game 20',
    brand: 'Geek & Gorgeous',
    slug: GG_PRODUCTS_SLUGS.GG_A_GAME_20,
    kind: 'skincare',
    unit: 'dropper',
    totalAmount: 30,
    amountUnit: 'ml',
    priceCents: 2280,
    description:
      'Sérum au rétinal très puissant (retinal 0.2%) pour une action anti-âge intense : réduction des rides, texture améliorée, éclat. Formule stabilisée et tolérable.',
    notes:
      'Haute puissance – commencer lentement (2-3x/semaine). Contient ectoine, panthénol et allantoïne pour minimiser irritations. Sans parfum.',
    inci: 'Aqua (Water), Caprylic/Capric Triglyceride, Oleyl Erucate, Glycerin, Triheptanoin, Cetearyl Olivate, Sorbitan Olivate, Panthenol, Ectoin, Cellulose, Allantoin, Retinal, Biosaccharide Gum-1, Tocopherol, Tocopheryl Acetate, Hydroxyethyl Acrylate/Sodium Acryloyldimethyl Taurate Copolymer, Citric Acid, Disodium EDTA, Phenoxyethanol, Ethylhexylglycerin',
    url: 'https://geekandgorgeous.com',
  },

  {
    name: 'Hydration Station',
    brand: 'Geek & Gorgeous',
    slug: GG_PRODUCTS_SLUGS.GG_HYDRATION_STATION,
    kind: 'skincare',
    unit: 'tube',
    totalAmount: 50,
    amountUnit: 'ml',
    priceCents: 880,
    description:
      'Gel-crème hydratant léger et apaisant avec ectoine, prébiotiques (xylitol derivatives) et allantoïne. Hydrate sans alourdir, renforce la barrière cutanée.',
    notes: 'Fini gel non gras, idéal peaux mixtes/déshydratées. Sans parfum, vegan.',
    inci: 'Aqua (Water), C15-19 Alkane, Glycerin, Caprylic/Capric Triglyceride, PEG/PPG/Polybutylene Glycol-8/5/3 Glycerin, Isosorbide Dicaprylate, Ectoin, Xylitylglucoside, Bisabolol, Allantoin, Anhydroxylitol, Xylitol, Hydroxyethyl Acrylate/Sodium Acryloyldimethyl Taurate Copolymer, Ammonium Acryloyldimethyltaurate/VP Copolymer, Glucose, Citric Acid, Tocopherol, Ethylhexylglycerin, Phenoxyethanol',
    url: 'https://geekandgorgeous.com',
  },
  {
    name: 'Calm Down',
    brand: 'Geek & Gorgeous',
    kind: 'skincare',
    unit: 'bottle',
    slug: GG_PRODUCTS_SLUGS.CALM_DOWN,
    totalAmount: 100,
    amountUnit: 'ml',
    priceCents: 2800,
    description:
      'Exfoliant liquide doux et apaisant conçu pour les peaux très sensibles et sujettes aux rougeurs[cite: 13].',
    notes:
      'pH 3.5-3.9. Contient 3.2% PHA et 0.8% BHA. Ne rend pas la peau photosensible[cite: 13].',
    inci: 'Aqua (Water) • Glycereth-26 • Gluconolactone • Lactobionic Acid • Propanediol • Salicylic Acid • Panthenol • Glycerin • Opuntia Ficus‐Indica (Prickly Pear) Extract • Saccharomyces Cerevisiae Extract • Phragmites Kharka (Topical Reed) Extract • Poria Cocos Extract • Sodium Hydroxide • Phenoxyethanol [cite: 13]',
    url: 'https://geekandgorgeous.com/products/calm-down',
  },
  {
    name: 'Cheer Up',
    brand: 'Geek & Gorgeous',
    kind: 'skincare',
    unit: 'bottle',
    slug: GG_PRODUCTS_SLUGS.CHEER_UP,
    totalAmount: 100,
    amountUnit: 'ml',
    priceCents: 2800,
    description: "Exfoliant pour peaux mixtes à 5% d'acide mandélique et 1% de BHA[cite: 13].",
    notes:
      "pH 3.2-3.6. Antibactérien et anti-inflammatoire. Idéal pour les pores dilatés et l'acné[cite: 13].",
    inci: 'Aqua (Water) • Propanediol • Mandelic Acid • Salicylic Acid • Xylitylglucoside • Anhydroxylitol • Xylitol • Sarcosine • Butylene Glycol • Pentylene Glycol • Glucose • Xanthan Gum • Sodium Hydroxide • Phenoxyethanol [cite: 13]',
    url: 'https://geekandgorgeous.com/products/cheer-up',
  },
  {
    name: 'Smooth Out',
    brand: 'Geek & Gorgeous',
    kind: 'skincare',
    unit: 'bottle',
    slug: GG_PRODUCTS_SLUGS.SMOOTH_OUT,
    totalAmount: 100,
    amountUnit: 'ml',
    priceCents: 3000,
    description:
      "Exfoliant anti-âge puissant avec 12% d'AHA (10% Glycolique + 2% Lactique)[cite: 13].",
    notes: 'pH 3.5-3.9. Stimule le collagène. Utiliser un SPF le matin impérativement[cite: 13].',
    inci: 'Aqua (Water) • Glycolic Acid • Lactic Acid • Sodium Hydroxide • Glycerin • Methyl Gluceth-20 • Galactoarabinan • Panthenol • Sodium Hyaluronate Crosspolymer • Opuntia Ficus‐Indica (Prickly Pear) Extract • Saccharomyces Cerevisiae Extract • Xylitylglucoside • Anhydroxylitol • Xylitol • Pentylene Glycol • Glucose • Ethylhexylglycerin • Sodium Benzoate • Potassium Benzoate • Phenoxyethanol [cite: 13]',
    url: 'https://geekandgorgeous.com/products/smooth-out',
  },
  {
    name: 'Mighty Melt',
    brand: 'Geek & Gorgeous',
    kind: 'skincare',
    unit: 'jar',
    slug: GG_PRODUCTS_SLUGS.MIGHTY_MELT,
    totalAmount: 98,
    amountUnit: 'ml',
    priceCents: 1280,
    description:
      'Baume démaquillant doux qui dissout le maquillage waterproof et les solaires[cite: 13].',
    notes: 'Se rince sans résidu gras. Idéal comme première étape du double nettoyage[cite: 13].',
    inci: 'Ethylhexyl Palmitate • Oleyl Erucate • Olive Oil PEG-7 Esters • PEG-20 Glyceryl Triisostearate • Synthetic Wax • Phenoxyethanol • Ethylhexylglycerin [cite: 13]',
    url: 'https://geekandgorgeous.com/products/mighty-melt',
  },
  {
    name: 'Jelly Joker',
    brand: 'Geek & Gorgeous',
    kind: 'skincare',
    unit: 'tube',
    slug: GG_PRODUCTS_SLUGS.JELLY_JOKER,
    totalAmount: 150,
    amountUnit: 'ml',
    priceCents: 950,
    description: 'Nettoyant gel basse pH doux qui respecte la barrière cutanée[cite: 13].',
    notes: 'pH 4.8-5.4. Texture gel riche non moussante. Ne pique pas les yeux[cite: 13].',
    inci: 'Aqua (Water) • PEG-6 Caprylic/Capric Glycerides • Propanediol • Methyl Gluceth-20 • Poloxamer 184 • Caprylic/Capric Triglyceride • Hydroxyethyl Acrylate/Sodium Acryloyldimethyl Taurate Copolymer • Ammonium Acryloyldimethyltaurate/VP Copolymer • Panthenol • Allantoin • Xylitylglucoside • Anhydroxylitol • Xylitol • Glucose • Citric Acid • Phenoxyethanol • Ethylhexylglycerin [cite: 13]',
    url: 'https://geekandgorgeous.com/products/jelly-joker',
  },
  {
    name: 'Liquid Hydration',
    brand: 'Geek & Gorgeous',
    kind: 'skincare',
    unit: 'spray',
    slug: GG_PRODUCTS_SLUGS.LIQUID_HYDRATION,
    totalAmount: 110,
    amountUnit: 'ml',
    priceCents: 850,
    description:
      "Toner hydratant en spray avec 5% de Panthénol et facteurs naturels d'hydratation[cite: 13].",
    notes: 'pH 4.5-5. Apaise et renforce la barrière cutanée[cite: 13].',
    inci: 'Aqua (Water) • Panthenol • Peg/Ppg/Polybutylene Glycol-8/5/3 Glycerin • Sodium PCA • Diglycerin • Urea • Hydrolyzed Rice Protein • Sorbitol • Lysine • PCA • Allantoin • Lactic Acid • Tocopherol • Citric Acid • Tetrasodium Glutamate Diacetate • Ethylhexylglycerin • Phenoxyethanol • Sodium Benzoate • Potassium Sorbate [cite: 13]',
    url: 'https://geekandgorgeous.com/products/liquid-hydration',
  },
  {
    name: 'Happier Barrier',
    brand: 'Geek & Gorgeous',
    kind: 'skincare',
    unit: 'tube',
    slug: GG_PRODUCTS_SLUGS.HAPPIER_BARRIER,
    totalAmount: 50,
    amountUnit: 'ml',
    priceCents: 1080,
    description:
      'Crème hydratante nourrissante mais légère avec Squalane et lipides identiques à la peau[cite: 13].',
    notes: 'pH 5.0-5.6. Contient 7% de Squalane et 0.1% de Céramide 2[cite: 13].',
    inci: 'Aqua (Water) • Squalane • Glycerin • Dicaprylyl Carbonate • Jojoba Oil/Macadamia Seed Oil Esters • Polyglyceryl-3 Methylglucose Distearate • Butylene Glycol • Cetearyl Alcohol • Hydroxyethyl Acrylate/Sodium Acryloyldimethyl Taurate Copolymer • Simmondsia Chinensis (Jojoba) Seed Oil • Saccharide Isomerate • Camellia Sinensis Leaf Extract • Bisabolol • Allantoin • Ceramide NG • Squalene • Phytosteryl Macadamiate • Phytosterols • Tocopherol • Tocopheryl Acetate • Citric Acid • Sodium Citrate • Ethylhexylglycerin • Phenoxyethanol [cite: 13]',
    url: 'https://geekandgorgeous.com/products/happier-barrier',
  },
  {
    name: 'A-Game 10',
    brand: 'Geek & Gorgeous',
    kind: 'skincare',
    unit: 'bottle',
    slug: GG_PRODUCTS_SLUGS.A_GAME_10,
    totalAmount: 30,
    amountUnit: 'ml',
    priceCents: 1880,
    description:
      'Sérum haute puissance au Rétinal 0.1% pour lutter contre le vieillissement[cite: 13].',
    notes: 'pH 6-6.5. Texture émulsion jaune. Ne pas utiliser si enceinte[cite: 13].',
    inci: 'Aqua (Water) • Caprylic/Capric Triglyceride • Oleyl Erucate • Glycerin • Triheptanoin • Cyclodextrin • Cetearyl Olivate • Sorbitan Olivate • Hydroxyethyl Acrylate/Sodium Acryloyldimethyl Taurate Copolymer • Biosaccharide Gum-1 • Allantoin • Retinal • Rubus Chamaemorus (Cloudberry) Seed Oil • Panthenol • Citric Acid • Tocopheryl Acetate • Disodium Edta • Pentylene Glycol • Lonicera Japonica (Honeysuckle) Flower Extract • Lonicera Caprifolium (Honeysuckle) Flower Extract • Ethylhexylglycerin • Phenoxyethanol [cite: 13]',
    url: 'https://geekandgorgeous.com/products/a-game-10',
  },
  {
    name: 'A-Game 5',
    brand: 'Geek & Gorgeous',
    kind: 'skincare',
    unit: 'bottle',
    slug: GG_PRODUCTS_SLUGS.A_GAME_5,
    totalAmount: 30,
    amountUnit: 'ml',
    priceCents: 1380,
    description:
      'Émulsion légère au Rétinal 0.05% pour une introduction douce aux rétinoïdes[cite: 13].',
    notes: 'pH 6-6.5. Idéal pour débuter. Usage soir[cite: 13].',
    inci: 'Aqua (Water) • Caprylic/Capric Triglyceride • Oleyl Erucate • Glycerin • Triheptanoin • Cetearyl Olivate • Sorbitan Olivate • Cyclodextrin • Hydroxyethyl Acrylate/Sodium Acryloyldimethyl Taurate Copolymer • Biosaccharide Gum-1 • Allantoin • Retinal • Rubus Chamaemorus (Cloudberry) Seed Oil • Panthenol • Citric Acid • Tocopheryl Acetate • Disodium Edta • Pentylene Glycol • Lonicera Japonica (Honeysuckle) Flower Extract • Lonicera Caprifolium (Honeysuckle) Flower Extract • Ethylhexylglycerin • Phenoxyethanol [cite: 13]',
    url: 'https://geekandgorgeous.com/products/a-game-5',
  },
  {
    name: 'C-Glow',
    brand: 'Geek & Gorgeous',
    kind: 'skincare',
    unit: 'dropper',
    slug: GG_PRODUCTS_SLUGS.C_GLOW,
    totalAmount: 30,
    amountUnit: 'ml',
    priceCents: 1250,
    description:
      'Sérum ultra-léger avec 15% de Vitamine C pure, Acide Féruleique et Vitamine E[cite: 13].',
    notes: "pH 3-3.4. Conserver au réfrigérateur. Texture liquide comme de l'eau[cite: 13].",
    inci: 'Aqua (Water) • (L-)Ascorbic Acid • Dimethyl Isosorbide • Butylene Glycol • Peg/Ppg/Polybutylene Glycol-8/5/3 Glycerin • Ferulic Acid • Tocopherol • Phenoxyethanol • Ethylhexylglycerin • Sodium Hydroxide [cite: 13]',
    url: 'https://geekandgorgeous.com/products/c-glow',
  },
  {
    name: 'Stress Less',
    brand: 'Geek & Gorgeous',
    kind: 'skincare',
    unit: 'dropper',
    slug: GG_PRODUCTS_SLUGS.STRESS_LESS,
    totalAmount: 30,
    amountUnit: 'ml',
    priceCents: 1200,
    description:
      'Gel soyeux avec 0.2% Beta-Glucan et 0.3% Madecassoside pour réparer la peau[cite: 13].',
    notes: 'pH 5-5.5. Apaise les irritations et renforce la barrière cutanée[cite: 13].',
    inci: 'Aqua (Water) • Methyl Gluceth-20 • Saccharide Isomerate • Glycerin • Madecassoside • Beta-Glucan • 1,2-Hexanediol • Citric Acid • Sodium Citrate • Caprylyl Glycol • Carbomer • Sodium Hydroxide • Ethylhexylglycerin • Phenoxyethanol [cite: 13]',
    url: 'https://geekandgorgeous.com/products/stress-less',
  },
  {
    name: 'aPAD',
    brand: 'Geek & Gorgeous',
    kind: 'skincare',
    unit: 'dropper',
    slug: GG_PRODUCTS_SLUGS.APAD,
    totalAmount: 30,
    amountUnit: 'ml',
    priceCents: 1180,
    description:
      "Sérum léger à 20% d'Azeclair (dérivé d'acide azélaïque) pour réguler le sébum[cite: 13].",
    notes: 'pH 5.5-6.5. Calme les rougeurs et unifie le teint. Idéal rosacée[cite: 13].',
    inci: 'Aqua (Water) • Potassium Azeloyl Diglycinate • Propanediol • Glycerin • Methyl Gluceth-20 • Allantoin • Hydroxyethylcellulose • Xanthan Gum • Citric Acid • Ethylhexylglycerin • Phenoxyethanol [cite: 13]',
    url: 'https://geekandgorgeous.com/products/apad',
  },
  {
    name: 'B-Bomb',
    brand: 'Geek & Gorgeous',
    kind: 'skincare',
    unit: 'dropper',
    slug: GG_PRODUCTS_SLUGS.B_BOMB,
    totalAmount: 30,
    amountUnit: 'ml',
    priceCents: 850,
    description:
      'Sérum à 10% de Niacinamide, Zinc PCA et Sarcosine pour peaux mixtes/grasses[cite: 13].',
    notes: 'pH 5.5-6.5. Aide sur les pores dilatés, les imperfections et la brillance[cite: 13].',
    inci: 'Aqua (Water) • Niacinamide • Butylene Glycol • Glycereth-26 • Zinc PCA • Sarcosine • Propanediol • Pentylene Glycol • Xanthan Gum • Ethylhexylglycerin • Phenoxyethanol [cite: 13]',
    url: 'https://geekandgorgeous.com/products/b-bomb',
  },
  {
    name: 'Porefectly Clear',
    brand: 'Geek & Gorgeous',
    kind: 'skincare',
    unit: 'dropper',
    slug: GG_PRODUCTS_SLUGS.POREFECTLY_CLEAR,
    totalAmount: 30,
    amountUnit: 'ml',
    priceCents: 780,
    description: "Gel exfoliant léger avec 2% d'acide salicylique (BHA) et Sarcosine[cite: 13].",
    notes: 'pH 3.5-3.9. Désobstrue les pores et cible les points noirs[cite: 13].',
    inci: 'Aqua (Water) • Pentylene Glycol • Dipropylene Glycol • Methyl Gluceth-20 • Salicylic Acid • Butylene Glycol • Sarcosine • Allantoin • Sodium Hydroxide • Xanthan Gum • Disodium EDTA [cite: 13]',
    url: 'https://geekandgorgeous.com/products/porefectly-clear',
  },
  {
    name: 'HA 5 Light',
    brand: 'Geek & Gorgeous',
    kind: 'skincare',
    unit: 'dropper',
    slug: GG_PRODUCTS_SLUGS.HA_5_LIGHT,
    totalAmount: 30,
    amountUnit: 'ml',
    priceCents: 950,
    description: "Sérum avec 5 formes d'acide hyaluronique pour peaux mixtes à grasses[cite: 13].",
    notes: 'pH 4.5-5.5. Texture gel fine, non collante[cite: 13].',
    inci: 'Aqua (Water) • Glycerin • Peg/Ppg/Polybutylene Glycol-8/5/3 Glycerin • Sodium Hyaluronate Crosspolymer • Sodium Hyaluronate • Tremella Fuciformis (Mushroom) Extract • Hydrolyzed Hyaluronic Acid • Panthenol • Tocopherol • Carbomer • Propanediol • Pentylene Glycol • Sodium Hydroxide • Ethylhexylglycerin • Phenoxyethanol [cite: 13]',
    url: 'https://geekandgorgeous.com/products/ha-5-light',
  },
  {
    name: 'HA 5 Rich',
    brand: 'Geek & Gorgeous',
    kind: 'skincare',
    unit: 'dropper',
    slug: GG_PRODUCTS_SLUGS.HA_5_RICH,
    totalAmount: 30,
    amountUnit: 'ml',
    priceCents: 950,
    description:
      "Sérum riche avec 5 formes d'acide hyaluronique pour peaux normales à sèches[cite: 13].",
    notes: 'pH 4.5-5.5. Hydrate, adoucit et repulpe[cite: 13].',
    inci: 'Aqua (Water) • Betaine • Glycerin • Sodium Hyaluronate Crosspolymer • Sodium Hyaluronate • Tremella Fuciformis (Mushroom) Extract • Hydrolyzed Hyaluronic Acid • Panthenol • Polyacrylate Crosspolymer-6 • Propanediol • Pentylene Glycol • Sodium Hydroxide • Ethylhexylglycerin • Phenoxyethanol [cite: 13]',
    url: 'https://geekandgorgeous.com/products/ha-5-rich',
  },
]
