export const GARANCIA_PRODUCT_SLUGS = {
  GARANCIA_ROUGEURS: 'garancia-que-mes-rougeurs-disparaissent',
}

export const GARANCIA_PRODUCT_DATA = [
  {
    name: 'Que mes Rougeurs Disparaissent',
    brand: 'Garancia',
    kind: 'skincare',
    unit: 'pump',
    slug: GARANCIA_PRODUCT_SLUGS.GARANCIA_ROUGEURS,
    totalAmount: 30,
    amountUnit: 'ml',
    priceCents: 3100,
    description: 'Sérum lacté concentré à action ultra-rapide sur les flushs.',
    notes: 'Yuka 100/100. Résultats en 30 minutes.',
    inci: 'AQUA (WATER/EAU)*, HEPTYL UNDECYLENATE*, METHYLPROPANEDIOL, BUTYLENE GLYCOL, GLYCYRRHETINIC ACID*, GLYCERIN*, VACCINIUM MYRTILLUS LEAF EXTRACT*, PLANKTON EXTRACT*, PANTHENOL*, ESCIN*, ARRABIDAEA CHICA LEAF/STEM EXTRACT*, RUSCUS ACULEATUS ROOT EXTRACT*, AMMONIUM GLYCYRRHIZATE*, CENTELLA ASIATICA EXTRACT*, HYDROLYZED YEAST PROTEIN*, CALENDULA OFFICINALIS FLOWER EXTRACT*, TOCOPHEROL, CITRIC ACID*, PARFUM (FRAGRANCE), ACRYLATES/C10-30 ALKYL ACRYLATE CROSSPOLYMER, GLYCERYL UNDECYLENATE*, SODIUM BENZOATE, SODIUM CITRATE, POTASSIUM SORBATE, ETHYLHEXYLGLYCERIN, SODIUM HYDROXIDE',
  },
]
