import { TAG_SLUGS } from '../../tags/seed-tags'
import { GARANCIA_PRODUCT_SLUGS } from './garancia'

export const GARANCIA_PRODUCT_TAGS: { productSlug: string; tagSlug: string }[] = [
  // Que mes Rougeurs Disparaissent (Sérum concentré anti-rougeurs)
  { productSlug: GARANCIA_PRODUCT_SLUGS.GARANCIA_ROUGEURS, tagSlug: TAG_SLUGS.ANTI_ROUGEURS },
  { productSlug: GARANCIA_PRODUCT_SLUGS.GARANCIA_ROUGEURS, tagSlug: TAG_SLUGS.FLUSHS },
  { productSlug: GARANCIA_PRODUCT_SLUGS.GARANCIA_ROUGEURS, tagSlug: TAG_SLUGS.COUPEROSE },
  { productSlug: GARANCIA_PRODUCT_SLUGS.GARANCIA_ROUGEURS, tagSlug: TAG_SLUGS.ROSACEE },
  { productSlug: GARANCIA_PRODUCT_SLUGS.GARANCIA_ROUGEURS, tagSlug: TAG_SLUGS.PEAU_SENSIBLE },
  { productSlug: GARANCIA_PRODUCT_SLUGS.GARANCIA_ROUGEURS, tagSlug: TAG_SLUGS.PEAU_REACTIVE },
  { productSlug: GARANCIA_PRODUCT_SLUGS.GARANCIA_ROUGEURS, tagSlug: TAG_SLUGS.BARRIERE_CUTANEE },
  { productSlug: GARANCIA_PRODUCT_SLUGS.GARANCIA_ROUGEURS, tagSlug: TAG_SLUGS.SERUM },
  { productSlug: GARANCIA_PRODUCT_SLUGS.GARANCIA_ROUGEURS, tagSlug: TAG_SLUGS.HYPOALLERGENIQUE },
  { productSlug: GARANCIA_PRODUCT_SLUGS.GARANCIA_ROUGEURS, tagSlug: TAG_SLUGS.REPARATEUR },
]
